<?php
/**
 * Generated by UnicaenCode
 * Commande : php public/index.php UnicaenCode  module='Agrement'
 */
return [
    'Agrement\Assertion\AgrementAssertion'                  => __DIR__ . '/src/Assertion/AgrementAssertion.php',
    'Agrement\Assertion\AgrementAssertionFactory'           => __DIR__ . '/src/Assertion/AgrementAssertionFactory.php',
    'Agrement\Controller\AgrementController'                => __DIR__ . '/src/Controller/AgrementController.php',
    'Agrement\Controller\Factory\AgrementControllerFactory' => __DIR__ . '/src/Controller/Factory/AgrementControllerFactory.php',
    'Agrement\Entity\Db\Agrement'                           => __DIR__ . '/src/Entity/Db/Agrement.php',
    'Agrement\Entity\Db\TblAgrement'                        => __DIR__ . '/src/Entity/Db/TblAgrement.php',
    'Agrement\Entity\Db\TypeAgrement'                       => __DIR__ . '/src/Entity/Db/TypeAgrement.php',
    'Agrement\Form\Factory\AgrementFormFactory'             => __DIR__ . '/src/Form/Factory/AgrementFormFactory.php',
    'Agrement\Form\Saisie'                                  => __DIR__ . '/src/Form/Saisie.php',
    'Agrement\Module'                                       => __DIR__ . '/Module.php',
    'Agrement\Service\AgrementService'                      => __DIR__ . '/src/Service/AgrementService.php',
    'Agrement\Service\AgrementServiceFactory'               => __DIR__ . '/src/Service/AgrementServiceFactory.php',
    'Agrement\Service\TblAgrementService'                   => __DIR__ . '/src/Service/TblAgrementService.php',
    'Agrement\Service\TblAgrementServiceFactory'            => __DIR__ . '/src/Service/TblAgrementServiceFactory.php',
    'Agrement\Service\TypeAgrementService'                  => __DIR__ . '/src/Service/TypeAgrementService.php',
    'Agrement\Service\TypeAgrementServiceFactory'           => __DIR__ . '/src/Service/TypeAgrementServiceFactory.php',
    'Agrement\View\Helper\AgrementVewHelperFactory'         => __DIR__ . '/src/View/Helper/AgrementVewHelperFactory.php',
    'Agrement\View\Helper\AgrementViewHelper'               => __DIR__ . '/src/View/Helper/AgrementViewHelper.php',
];