<?php
/**
 * Generated by UnicaenCode
 * Commande : php public/index.php UnicaenCode  module='Agrement'
 */
return [
    'agrement/agrement/supprimer'  => __DIR__ . '/view/agrement/agrement/supprimer.phtml',
    'agrement/agrement/lister'     => __DIR__ . '/view/agrement/agrement/lister.phtml',
    'agrement/agrement/saisir-lot' => __DIR__ . '/view/agrement/agrement/saisir-lot.phtml',
    'agrement/agrement/voir'       => __DIR__ . '/view/agrement/agrement/voir.phtml',
    'agrement/agrement/saisir'     => __DIR__ . '/view/agrement/agrement/saisir.phtml',
    'agrement/agrement/index'      => __DIR__ . '/view/agrement/agrement/index.phtml',
];