<?php

use Application\Acl\IntervenantRole;
use Application\Entity\Db\TypeVolumeHoraire;
use UnicaenApp\View\Helper\Messenger;

/* @var $typeVolumeHoraire TypeVolumeHoraire */

$titles = [
  TypeVolumeHoraire::CODE_PREVU   => 'Référentiel',
  TypeVolumeHoraire::CODE_REALISE => 'Constatation du référentiel réalisé',
];

$title = $titles[$typeVolumeHoraire->getCode()];
if ($intervenant){
    $title .= ' <small>'.$intervenant.'</small>';
    $this->headTitle()->append($intervenant->getNomUsuel())->append("Enseignements");
}
else {  
    $this->headTitle()->append("Référentiel");
}

$serviceReferentielListe = $this->serviceReferentielListe( $services );
$serviceReferentielListe
        ->setTypeVolumeHoraire($typeVolumeHoraire)
        ->setAddButtonVisibility($canAddServiceReferentiel);
?>

<h1 class="page-header"><?php echo $title; ?></h1>

<?php echo $this->messenger()->addMessagesFromFlashMessenger() ?>

<style>
    .modal-dialog { 
        width: 70%;
    }
    div.row {
        padding:1px;
    }
    th.heures, td.heures { width: 3em !important; }
</style>

<?php if (! $intervenant): ?>
    <?php if ($this->isAllowed('ServiceReferentielListView', 'info-only-structure')): ?>
        <?php echo $this->messenger()->setMessages(array('warning' => "Est visible ici le référentiel prévisionnel des intervenants affectés "
                . "ou enseignant dans votre structure de responsabilité ({$role->getStructure()}) ou l'une de ses sous-structures.")); ?>
    <?php endif; ?>
<?php endif; ?>

<?php if ('afficher' === $action ): ?>

    <?php if ($this->isAllowed('ServiceReferentielListView', 'aide-intervenant')): ?>
        <?php //echo $this->messenger()->setMessage(
              //  "Merci de saisir les heures effectuées <strong>sans majoration</strong>. Exemple: saisissez 1h CM et non 1,5h TD."); ?>
    <?php endif; ?>

    <?php echo $serviceReferentielListe->render(); ?>

<?php else:?>

    <?php echo $this->messenger()->setMessage('Cliquez sur "Afficher" pour afficher le référentiel.', Messenger::INFO); ?>

<?php endif;