<h1><?php echo $title ?></h1>

<style>
    form.service-referentiel .form-group { float: left; }
    form.service-referentiel input { width: 100px; }
    form.service-referentiel input[type=submit] { margin-top: 2em; }
    button.fonction-referentiel-ajouter   { display: block; margin-top: 0.5em; }
    button.fonction-referentiel-supprimer { margin: 2em 0 0 1em; }
</style>

<?php if (isset($exception)) { echo $this->messenger()->setException($exception); } ?>

<?php
$form->setAttribute('id', $formId = uniqid('form-'))->prepare();
$serviceReferentiel = $form->get('intervenant');
?>

<?php 
echo $this->form()->openTag($form);
echo $this->formCollection()->setElementHelper($this->formControlGroup())->render($serviceReferentiel->get('serviceReferentiel'));
?> 
<div class="text-info" id="fonction-comptage"></div>
<?php 
echo $this->formButton($form->get('ajouter'));
echo $this->formHidden($form->get('security'));
echo $this->formSubmit($form->get('submit')->setAttribute('class', 'btn btn-primary'));
echo $this->form()->closeTag();
?>

<?php 
// collecte des structures associées aux fonctions
$structuresFonction = [];
foreach ($fonctions as $fonction) {
    $structuresFonction[$fonction->getId()] = (($s = $fonction->getStructure()) ? $s->getId() : 0);
}
?>

<script>
    var formId = "<?php echo $form->getAttribute('id') ?>";
    var form   = $("#" + formId);
    var structureSelectSel = "select.fonction-referentiel-structure"; 
    var fonctionSelectSel  = "select.fonction-referentiel-fonction"; 
    var structuresFonction = <?php echo json_encode($structuresFonction) ?>;
    
    $("body").on('click', "#" + formId + " button.fonction-referentiel-ajouter", function() {
        addLigne();
        return false;
    });
    $("body").on('click', "#" + formId + " button.fonction-referentiel-supprimer", function() {
        if (getLigneCurrentCount() > 0) {
            removeLigne($(this));
        }  
        return false; 
    });
        
    $(function() {
        updateLigneCounter();
        applyStructureFonction();
        $(":input").tooltip();
        
        $('body')
            .on('change', "#" + formId + " " + fonctionSelectSel, function() {
                applyStructureFonction();
            })
            .on('change', "#" + formId + " input.fonction-referentiel-heures", function() {
                updateLigneCounter();
            });
    });
    
    /**
     * Si une structure est associée à la fonction sélectionnée, on la sélectionne
     * et interdit les autres structures.
     */
    function applyStructureFonction()
    {
        $("fieldset.fonction-referentiel").each(function(index, fs) {
            var fonctionVal     = $(fonctionSelectSel, fs).val();
            var structureSelect = $(structureSelectSel, fs);

            $('option', structureSelect).attr('disabled', false);
                
            // si une structure est associée à la fonction sélectionnée
            if (structuresFonction[fonctionVal]) {
                structureSelect.val(structuresFonction[fonctionVal]);
                $('option:not(:selected)', structureSelect).attr('disabled', true);
            }
        });
    }
    
    function addLigne() 
    {
        var currentCount = getLigneCurrentCount();
        var template = $('> fieldset > span', form).data('template');
        var ligne = $(template.replace(/__index__/g, currentCount));
        $('> fieldset', form).append(ligne.fadeIn());
        updateLigneCounter();
        return ligne;
    }
    
    function removeLigne(button) 
    {
        $(button).parentsUntil('fieldset').parent().remove();
        updateLigneCounter();
        return false;
    }
    
    function getLignes()
    {
        return $('> fieldset > fieldset', form);
    }
    
    function getLigneCurrentCount()
    {
        return getLignes().length;
    }
    
    function getLigneCurrentTotal()
    {
        var total = 0;
        $.each(getLignes(), function(index, ligne) { total = total + parseFloat($(".fonction-referentiel-heures", ligne).val()); });
        return total;
    }
    
    function updateLigneCounter() 
    {
        var msg = "Aucune fonction référentiel.";
        var currentCount = getLigneCurrentCount();
        if (currentCount) {
            var total = getLigneCurrentTotal();
            msg = currentCount + " fonction(s) référentiel (total = " + total + ").";
        }
        $("#fonction-comptage").html(msg);
    }
</script>