<?php
/**
 * @var $this  \Application\View\Renderer\PhpRenderer
 * @var $form  \Application\Form\TypeRessource\TypeRessourceSaisieForm
 */
echo $this->messenger()->addCurrentMessagesFromFlashMessenger();
$type = $dossierAutre->getType()->getId();

echo $this->form()->openTag($form); ?>

<div class="row">
    <div class="col-md-3">
        <?= $this->formControlGroup($form->get('libelle')); ?>
    </div>
    <div class="col-md-6">
        <?= $this->formControlGroup($form->get('description')); ?>
    </div>
    <div class="col-md-6">
        <?= $this->formControlGroup($form->get('type')); ?>
    </div>
    <div class="col-md-6">
        <?= $this->formControlGroup($form->get('obligatoire')); ?>
    </div>
    <div class="col-md-12">

        <ul class="nav nav-tabs" role="tablist">
            <li role="presentation" class="<?= ($type != '3') ? 'active' : ''; ?>"><a href="#json" aria-controls="json"
                                                                                      role="tab"
                >Valeurs manuelles</a></li>
            <li role="presentation" class="<?= ($type == '3') ? 'active' : ''; ?>"><a href="#sql" aria-controls="sql"
                                                                                      role="tab"
                >Valeurs via SQL </a></li>
        </ul>

        <div class="tab-content">
            <div role="tabpanel" class="tab-pane <?= ($type != '3') ? 'active' : ''; ?>"
                 id="json">
                <div class="panel panel-default json-value">
                    <div class="panel-heading" role="tab">
                        <label>Valeurs sous forme JSON<br/>
                            <small style="font-weight:normal">Format : { "0":"VALUE1" , "1":"VALUE2" ...}</small></label>
                    </div>
                    <div class="panel-body">
                        <?= $this->formTextarea($form->get('json-value')) ?>
                    </div>
                </div>
            </div>
            <div role="tabpanel" class="tab-pane <?= ($dossierAutre->getType()->getId() == '3') ? 'active' : ''; ?>"
                 id="sql">
                <div class="panel panel-default sql-value">
                    <div class="panel-heading" role="tab">
                        <label>Valeurs sous forme SQL<br/> <small style="font-weight:normal">Format : SELECT
                                votre_champs as VALUE_OPTION FROM
                                votre_table</small></label>
                    </div>
                    <div class="panel-body">
                        <?= $this->formTextarea($form->get('sql-value')) ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<?= $this->formSubmit($form->get('submit')); ?>
<?= $this->formControlGroup($form->get('security')); ?>

<?= $this->form()->closeTag(); ?>
</div>


<script>


    $(function ()
    {

        WidgetInitializer.add('autres-saisir', {
            jsonValueEditor: null,
            sqlValueEditor: null,

            save: function ()
            {
                var jsonValue = $("<input>")
                    .attr("type", 'hidden')
                    .attr("name", 'json-value')
                    .val(this.jsonValueEditor.getSession().getValue());
                this.element.append($(jsonValue));

                var sqlValue = $("<input>")
                    .attr("type", 'hidden')
                    .attr("name", 'sql-value')
                    .val(this.sqlValueEditor.getSession().getValue());
                this.element.append($(sqlValue));

            },

            _create: function ()
            {
                var that = this;

                that.element.find('#btn-save').click(function () { that.save();});
                that.element.find('.nav a').click(function (e) {
                    e.preventDefault();
                    $('a[href="' + $(this).attr('href') + '"]').tab('show');
                    return false;
                })

                var options = {
                    minLines: 15, maxLines: 40,
                };
                that.jsonValueEditor = ace.edit("json-value");
                that.jsonValueEditor.setTheme("ace/theme/github");
                that.jsonValueEditor.getSession().setMode("ace/mode/json");
                that.jsonValueEditor.setOptions(options);

                that.sqlValueEditor = ace.edit("sql-value");
                that.sqlValueEditor.setTheme("ace/theme/github");
                that.sqlValueEditor.getSession().setMode("ace/mode/sql");
                that.sqlValueEditor.setOptions(options);


            }
        });

    });


</script>
<style>

    .autres-saisir .panel-heading {
        padding-top: 3px;
        padding-bottom: 3px;
    }

    .autres-saisir .panel-body {
        padding: 0px;
    }

    .autres-saisir #sql .ace_editor {
        border: none;
        border-radius: 0;
        margin-bottom: 0px;
        margin-top: 0px;
    }
</style>