<?php
/*
* @author JORIOT Florian <florian.joriot at unicaen.fr>
*/

/**
 * @var $this  \Application\View\Renderer\PhpRenderer
 */

use Application\Provider\Privileges;

function affBooleen($flg)
{
    // affiche booléen avec des glypheIcon
    return ($flg ? '<i class="fas fa-check "></i>' : '<i class="fas fa-xmark "></i>');
}

$this->headTitle()->append("Gestion des types de formations");
$canEdit = $this->isAllowed(Privileges::getResourceId(Privileges::ODF_TYPE_FORMATION_EDITION));
echo $this->messenger()->addCurrentMessagesFromFlashMessenger();
?>

<h1 class="page-header">Gestion des types de formations</h1>
<div class="triables ui-sortable">
    <?php foreach ($groupeTypeFormations as $groupeTypeFormation): ?>
        <div class="champ-triable" data-id= <?php echo $groupeTypeFormation->getId() ?>>
            <div class="card bg-default">
                <div class="card-header"><?= $groupeTypeFormation->getLibelleLong(); ?> (<?= $groupeTypeFormation->getLibelleCourt(); ?>)
                    <?php if ($canEdit): ?>
                        <div class="float-end">
                            <a class="ajax-modal " data-event="type-formation-edition"
                               href="<?= $this->url('type-formation/saisie-groupe', ['groupeTypeFormation' => $groupeTypeFormation->getId()], ['query' => ['tab' => 'edition']]) ?>"
                               title="Modifier la collection"><i class="fas fa-pen-to-square"></i></a>

                            <?php if (!$groupeTypeFormation->getSource()->getImportable()): ?>
                                <a class="pop-ajax " data-title="Suppression d'une collection" data-content="Êtes-vous sur de vouloir supprimer ?"
                                   data-confirm="true"
                                   data-submit-reload="true"
                                   href="<?= $this->url('type-formation/supprimer-groupe', ['groupeTypeFormation' => $groupeTypeFormation->getId()]) ?>"
                                   title="Supprimer la collection"><i class="fas fa-trash-can"></i></a>
                            <?php endif; ?>

                            <i class="fas fa-arrows-up-down"
                               title="Vous pouvez trier les champs en déplaçant les lignes du tableau"></i>
                        </div>
                    <?php endif; ?>
                </div>
                <div class="card-body">
                    <table class="table table-bordered table-sm">
                        <thead>
                        <tr>
                            <th style="text-align: center" width="20%">Libellé court</th>
                            <th style="text-align: center" width="60%">Libellé long</th>
                            <th style="text-align: center">Source</th>
                            <?php if ($canEdit): ?>
                                <th style="text-align: center">Actions</th>
                            <?php endif; ?>
                        </tr>
                        </thead>
                        <tbody class="triables ui-sortable">
                        <?php foreach ($groupeTypeFormation->getTypeFormation() as $typeFormation): ?>
                            <tr class="champ-triable" data-id= <?php echo $typeFormation->getId() ?>>
                                <td style=""><?= $typeFormation->getLibelleCourt(); ?></td>
                                <td><?= $typeFormation->getLibelleLong(); ?></td>
                                <td style="text-align: center"><?= $typeFormation->getSource()->getLibelle(); ?></td>
                                <?php if ($canEdit): ?>
                                    <td style="text-align: center">
                                        <a class="ajax-modal" data-event="type-formation-edition"
                                           href="<?= $this->url('type-formation/saisie', ['typeFormation' => $typeFormation->getId(), 'groupeTypeFormation' => $groupeTypeFormation->getId()], ['query' => ['tab' => 'edition']]) ?>"
                                           title="Modifier le type de formation"><i class="fas fa-pen-to-square"></i></a>
                                        <?php if (!$typeFormation->getSource()->getImportable()): ?>
                                            <a class="pop-ajax" data-title="Suppression du type de formation"
                                               data-content="Êtes-vous sur de vouloir supprimer ?"
                                               data-confirm="true"
                                               data-submit-reload="true"
                                               href="<?= $this->url('type-formation/supprimer', ['typeFormation' => $typeFormation->getId()]) ?>"
                                               title="Supprimer le type de formation"><i class="fas fa-trash-can"></i></a>
                                        <?php endif; ?>
                                    </td>
                                <?php endif; ?>

                            </tr>
                        <?php endforeach; ?>
                        </tbody>
                    </table>
                    <?php if ($canEdit): ?>
                        <tr class="champ-triable">
                            <a class="btn btn-primary ajax-modal " data-event="type-formation-edition"
                               href="<?= $this->url('type-formation/ajout', ['groupeTypeFormation' => $groupeTypeFormation->getId()]); ?>"><i
                                        class="fas fa-plus"></i>
                                Ajout d'un nouveau type de formation</a>
                        </tr>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    <?php endforeach; ?>
</div>
<?php if (!empty($typeFormationsWithoutGroupe)): ?>
    <div class="card bg-danger">
        <div class="card-header ">Type de formation ne possédant pas de groupe
        </div>
        <table class="table table-bordered table-sm bg-danger">
            <thead>
            <tr>
                <th style="text-align: center" width="20%">Libellé court</th>
                <th style="text-align: center" width="60%">Libellé long</th>
                <th style="text-align: center">Source</th>
                <?php if ($canEdit): ?>
                    <th style="text-align: center">Actions</th>
                <?php endif; ?>
            </tr>
            </thead>
            <tbody class="triables ui-sortable">
            <?php foreach ($typeFormationsWithoutGroupe as $typeFormationWithoutGroupe): ?>
                <tr>
                    <td><?= $typeFormationWithoutGroupe->getLibelleCourt(); ?></td>
                    <td><?= $typeFormationWithoutGroupe->getLibelleLong(); ?></td>
                    <td style="text-align: center"><?= $typeFormationWithoutGroupe->getSource()->getLibelle(); ?></td>
                    <?php if ($canEdit): ?>
                        <td style="text-align: center">
                            <a class="ajax-modal" data-event="type-formation-edition"
                               href="<?= $this->url('type-formation/saisie', ['typeFormation' => $typeFormationWithoutGroupe->getId()], ['query' => ['tab' => 'edition']]) ?>"
                               title="Modifier le type de formation"><i class="fas fa-pen-to-square"></i></a>
                            <?php if (!$typeFormationWithoutGroupe->getSource()->getImportable()): ?>
                                <a class="pop-ajax" data-title="Suppression du type de formation" data-content="Êtes-vous sur de vouloir supprimer ?"
                                   data-confirm="true"
                                   data-submit-reload="true"
                                   href="<?= $this->url('type-formation/supprimer', ['typeFormation' => $typeFormationWithoutGroupe->getId()]) ?>"
                                   title="Supprimer le type de formation"><i class="fas fa-trash-can"></i></a>
                            <?php endif; ?>

                        </td>
                    <?php endif; ?>
                </tr>
            <?php endforeach; ?>

            </tbody>
        </table>
    </div>
<?php endif; ?>
<?php if ($canEdit): ?>
    <tr class="champ-triable">
        <a class="btn btn-primary ajax-modal " data-event="groupe-type-formation-edition" href="<?= $this->url('type-formation/saisie-groupe'); ?>"><i
                    class="fas fa-plus"></i>
            Ajout d'un nouveau groupe
        </a>
    </tr>
<?php endif; ?>

<script type="text/javascript">
    $(function () {
        $(".triables").sortable({
            handle: '.fa-arrows-up-down',
            axis: 'y',
            update: function (event, ui) {
                var champsIds = '';
                ui.item.parent().find('div.champ-triable').each(function () {
                    if (champsIds != '') champsIds += ',';
                    champsIds += $(this).data('id');
                });

                $.ajax({
                    type: 'POST',
                    url: "<?= $this->url('type-formation/trier')?>",
                    data: {champsIds: champsIds},
                    success: function () { unicaenVue.flashMessenger.toast("Tri effectué", 'success'); },
                });
            }
        });
    });

    $(function () {
        $("body").on("type-formation-edition", function (event, data) {
            window.location.reload();
        });
    });

    $(function () {
        $("body").on("groupe-type-formation-edition", function (event, data) {
            window.location.reload();
        });
    });
</script>