<?php

namespace Framework\Container;

use Laminas\ServiceManager\ServiceManager;

class Container extends ServiceManager
{
    private ?AutowireFactory $autowireFactory = null;


    private function getAutowireFactory(): AutowireFactory
    {
        if ($this->autowireFactory === null) {
            $this->autowireFactory = new AutowireFactory();
        }
        return $this->autowireFactory;
    }


    public function get($name)
    {
        if ($this->has($name)) {
            return parent::get($name); // TODO: Change the autogenerated stub
        }
        if (class_exists($name)) {
            $object = $this->getAutowireFactory()->__invoke($this, $name);
            $this->setService($name, $object);
            return $object;
        }
    }

}