<?php

namespace Framework\Container;

use Doctrine\ORM\EntityManager;
use Laminas\ServiceManager\ServiceManager;
use UnicaenApp\Service\EntityManagerAwareInterface;

class Container extends ServiceManager
{
    private ?AutowireFactory $autowireFactory = null;



    private function getAutowireFactory(): AutowireFactory
    {
        if ($this->autowireFactory === null) {
            $this->autowireFactory = new AutowireFactory();
        }
        return $this->autowireFactory;
    }



    private function injectInitializers(mixed $object): void
    {
        if ($object instanceof EntityManagerAwareInterface) {
            $object->setEntityManager(
                $this->get(EntityManager::class),
            );
        }
    }



    public function get($name)
    {
        if ($this->has($name)) {
            return parent::get($name); // TODO: Change the autogenerated stub
        }
        if (class_exists($name)) {
            $object = $this->getAutowireFactory()->__invoke($this, $name);
            $this->setService($name, $object);
            $this->injectInitializers($object);
            return $object;
        }
    }

}