<?php

use Application\Provider\Privilege\Privileges;
use Service\Entity\Db\TypeService;

/**
 * @var $this                           \Application\View\Renderer\PhpRenderer
 * @var $title                          string
 * @var $intervenant                    \Intervenant\Entity\Db\Intervenant
 * @var $contrats                       \Contrat\Entity\Db\Contrat[]
 * @var $avenant_param                  boolean
 * @var $contratDirect                  boolean
 * @var $hasContrat                     boolean
 * @var $services
 * @var $missionNotContrat              bool[]
 * @var $contratSignatureActivation     boolean
 */

$structList = [];
foreach ($contrats as $contrat) {
    $structList[] = $contrat->getStructure()->getId();
}

$serviceNonContractToShow = [];
foreach ($services['non-contractualises'] as $structure => $servicesNCTypes) {
    if ($avenant_param == 1 || (!in_array($structure, $structList) && !in_array(null, $structList) && !($avenant_param < 0 && $hasContrat))) {
        $serviceNonContractToShow[] = $structure;
    }
}


$this->intervenant($intervenant)->renderTitle("Contrat/avenant");
echo $this->messenger()->addCurrentMessagesFromFlashMessenger();

if (empty($serviceNonContractToShow)) {
    $this->messenger()->addMessage('Des heures prévisionnelles d\'enseignement validées ne font l\'objet d\'aucun contrat ou avenant. En voici la liste ci-dessous :', 'danger');
} else {
    $this->messenger()->addMessage('Tous les enseignements prévisionnels validés ont fait l\'objet d\'un contrat ou d\'un avenant.', 'success');
}

$showEnseignement = (!$hasContrat && !empty($serviceNonContractToShow) || $avenant_param > 0 || $avenant_param == 0) && !empty($serviceNonContractToShow);
$this->messenger() ?>

<style>
    th.structure, td.structure {
        width: 10%;
    }

    .ui-datepicker {
        z-index: 1151 !important;
    }

    td .card {
        margin-bottom: 0px;
    }

</style>

<?php if ($contrats || !empty($serviceNonContractToShow)):
    if ($showEnseignement || !empty($missionNotContrat)): ?>
        <table class="table table-bordered table-hover">
            <tr>
                <th class="structure">Composante</th>
                <th>heure(s) non contractualisé(s)</th>
            </tr>
            <?php $contratPrevu = []; ?>
            <?php foreach ($services['non-contractualises'] as $structure => $serviceNonContract): ?>
                <?php foreach (TypeService::CODES as $typeServiceCode):
                    foreach ($serviceNonContract[$typeServiceCode] as $sid => $servicesNC):
                        $typeService = $servicesNC->getTypeService();
                        $structure = $servicesNC->getStructure();
                        if (in_array($structure, $contratPrevu) && $typeServiceCode != TypeService::CODE_MISSION) {
                            continue;
                        }
                        if (!in_array($structure->getId(), $serviceNonContractToShow) && $typeServiceCode != TypeService::CODE_MISSION) {
                            continue;
                        }
                        $contratPrevu[] = $structure;
                        $contrat        = new \Contrat\Entity\Db\Contrat();
                        $contrat->setIntervenant($intervenant);
                        $contrat->setStructure($structure);

                        $canCreer = $this->isAllowed($contrat, Privileges::CONTRAT_CREATION);
                        ?>

                        <?php if ($typeServiceCode != TypeService::CODE_MISSION || isset($missionNotContrat[$servicesNC->getMission()->getId()]) || (!isset($missionNotContrat[$servicesNC->getMission()->getId()]) && $avenant_param > 0)): ?>
                        <tr>
                            <td><?= $structure ?></td>
                            <td>
                                <?php if ($canCreer):
                                    if ($typeServiceCode != TypeService::CODE_MISSION && $showEnseignement):
                                        if ($contratDirect):?>
                                            <a class="btn btn-primary"
                                               href="<?= $this->url('contrat/creer', ['intervenant' => $intervenant->getId(), 'structure' => $structure->getId(), 'mission' => null]); ?>">
                                                <i class="fas fa-file"></i> Créer
                                                un <?= $hasContrat ? 'avenant' : 'contrat' ?>
                                            </a>
                                        <?php else: ?>
                                            <a class="btn btn-primary"
                                               href="<?= $this->url('contrat/creer', ['intervenant' => $intervenant->getId(), 'structure' => $structure->getId(), 'mission' => null]); ?>">
                                                <i class="fas fa-file"></i> Créer un
                                                projet <?= $hasContrat ? 'd\'avenant' : 'de contrat' ?>
                                            </a>
                                        <?php endif;
                                    else: ?>
                                        <?php if ($contratDirect): ?>
                                            <a class="btn btn-primary"
                                               href="<?= $this->url('contrat/creer-mission', ['intervenant' => $intervenant->getId(), 'mission' => $servicesNC->getMission()->getId()]); ?>">
                                                <i class="fas fa-file"></i> Créer
                                                un <?= !isset($missionNotContrat[$servicesNC->getMission()->getId()]) ? 'avenant' : 'contrat' ?>
                                            </a>
                                        <?php else: ?>
                                            <a class="btn btn-primary"
                                               href="<?= $this->url('contrat/creer-mission', ['intervenant' => $intervenant->getId(), 'mission' => $servicesNC->getMission()->getId()]); ?>">
                                                <i class="fas fa-file"></i> Créer un
                                                projet <?= !isset($missionNotContrat[$servicesNC->getMission()->getId()]) ? 'd\'avenant' : 'de contrat' ?>
                                            </a>
                                        <?php endif; ?>
                                    <?php endif;
                                else:
                                    try {
                                        echo $this->feuilleDeRoute($intervenant)->renderWhyNonAtteignable(\Application\Entity\Db\WfEtape::CODE_CONTRAT, $structure);
                                    } catch (\Exception $e) {
                                        //TODO Le referentiel ne possède pas d'agréement et ne peut donc etre contractualisé sans service lorsque l'agréement est obligatoire
                                        echo "Ces heures ne peuvent pas être contractualisées";
                                    }
                                endif; ?>
                                <p>
                                    Services (validés) non contractualisés :<br/>
                                    <small><a title="Cliquez pour afficher/masquer les enseignements concernés"
                                              href="#details-enseignements-structure-<?= $structure->getId() ?>"
                                              role="button"
                                              aria-expanded="true"
                                              aria-controls="details-enseignements-structure-<?= $structure->getId() ?>"
                                              data-bs-toggle="collapse"
                                        >Afficher/masquer</a></small>
                                </p>
                                <div class="collapse <?php if ($canCreer): ?>in<?php endif; ?>"
                                     id="details-enseignements-structure-<?= $structure->getId() ?>">
                                    <?php if ($servicesNC->getMission()): ?>
                                        <?= $this->partial('contrat/contrat/partial/contrat-heures', ['contrat' => $contrat, 'services' => $services['non-contractualises'][$structure->getId()], 'structure' => $structure, 'mission' => $servicesNC->getMission()->getId(), 'contractualiser' => false]); ?>
                                    <?php else: ?>
                                        <?= $this->partial('contrat/contrat/partial/contrat-heures', ['contrat' => $contrat, 'services' => $services['non-contractualises'][$structure->getId()], 'structure' => $structure, 'mission' => null, 'contractualiser' => false]); ?>
                                    <?php endif; ?>
                                </div>
                            </td>
                        </tr>
                    <?php endif; ?>
                    <?php endforeach; ?>
                <?php endforeach; ?>
            <?php endforeach; ?>
        </table>
    <?php endif; ?>
    <div class="well">
        <h2>Contrats et avenants</h2>
        <?php foreach ($contrats as $key => $contrat): ?>
            <!--La signature électronique est activé et il n'y a pas déjà eu de date de retour signée renseignée manuellement-->
            <?php if ($contratSignatureActivation && !(!empty($contrat->getDateRetourSigne() && empty($contrat->getProcessSignature())))): ?>
                <?php echo $this->partial('contrat/contrat/partial/contrat-signature-electronique', ['contrat' => $contrat, 'services' => $services['contractualises'][$contrat->getId()], 'emailIntervenant' => $emailIntervenant, 'contratDirect' => $contratDirect, 'avenant_param' => $avenant_param, 'contratSignatureActivation' => $contratSignatureActivation, 'libelleCircuitSignature' => $libelleCircuitSignature, 'infosSignature' => $infosSignature[$key]]); ?>
            <?php else: ?>
                <!--Signature électronique n'est pas activé on reste sur le mode manuel-->
                <?php echo $this->partial('contrat/contrat/partial/contrat', ['contrat' => $contrat, 'services' => $services['contractualises'][$contrat->getId()], 'emailIntervenant' => $emailIntervenant, 'contratDirect' => $contratDirect, 'avenant_param' => $avenant_param]); ?>
            <?php endif; ?>

        <?php endforeach; ?>
    </div>
<?php else: ?>
    <p>Aucun contrat/avenant trouvé.</p>
<?php endif; ?>

<hr/>
<?= $this->feuilleDeRoute($intervenant)->renderNav(\Application\Entity\Db\WfEtape::CODE_CONTRAT); ?>

<script>
    $("body").on("envoi-mail-contrat", function (event, data) {
        console.log('event envoyé et affiché');
        event.div.modal('hide'); // ferme la fenêtre modale
        window.location.reload();
    });
</script>