<?php

/**
 * @var $this \Application\View\Renderer\PhpRenderer
 * @var $form \Contrat\Form\ContratRetourForm
 * @var $done boolean
 */

?>
    <h1 class="page-header"><?= $title ?></h1>

<?php

if (!$done) echo $this->messenger()->addMessagesFromFlashMessenger();
if ($canSaisieDateSigne || $contratDate) {
    $form->prepare();
    echo $this->form()->openTag($form);
    echo $this->formControlGroup($form->get('dateRetourSigne'));
    echo $this->formHidden($form->get('security'));
    echo $this->formSubmit($form->get('submit')->setAttribute('class', 'btn btn-primary'));
    echo $this->form()->closeTag();
} else {
    echo "Un fichier doit être déposé pour pouvoir renseigner la date de retour signé";
}
