<?php 
use Application\Service\Workflow\Step\Step;
use Application\Entity\Db\Intervenant;

$wf   = $this->wf;   /* @var $data \Application\Service\Workflow\WorkflowIntervenant */
$data = $this->data; /* @var $data \SplObjectStorage */
$data->rewind();
?>
    
<?php while ($data->valid()): ?>

    <?php 
    $step         = $data->current(); /* @var $step Step */
    $intervenants = $data->getInfo(); /* @var $intervenants Intervenant[] */
    $vars = [
        'role'         => $role, 
        'wf'           => $wf, 
        'step'         => $step, 
        'intervenants' => $intervenants,
    ];
    $data->next();
    ?>

    <?php echo $this->partial('application/workflow/partial/step', $vars) ?>

<?php endwhile; ?>