<style>
    body { font-family: ubuntu,arial,sans-serif; }
    .vu { font-size: 80%; }
    .titre { text-align: center; border-style: solid; border-width: 1px; }
    .etab { font-weight: bold; }
    .intervenant { font-weight: bold; }
    .partie { margin-left: 50px; }
    .articles dt { font-weight: bold; margin-top: 10px; }
    .demeurant { vertical-align: top; width: 100px; }
    .insee { width: 100px; }
    .services table { border-style: solid; border-width: 1px; width: 80% }
    .services table th { border-bottom-style: solid; border-bottom-width: 1px; }
    .services table tfoot td { border-top-style: dotted; border-top-width: 1px; }
    .fait { text-align: center; }
    .signatures { width: 100%; }
    .signatures td { text-align: center; }
    .attention { font-weight: bold; }
    .renvoyer { font-weight: bold; text-align: center; }
</style>

<table class="table table-bordered">
    <tr>
        <td width="300px">DIRECTION DES RESSOURCES HUMAINES</td>
        <td class="vu">
            VU la loi 84-16 du 11/01/1984 portant dispositions statutaires relatives à la fonction publique de l'Etat ;<br /><br />
            VU le code de l'éducation, notamment son article L. 712-5 ;<br /><br />
            VU l’article L952-1 du code de l’éducation qui mentionne les chargés d’enseignement comme faisant
partie des personnels enseignants ;<br /><br />
            VU l’article D952-5 du code de l’éducation qui fait référence au décret n°87-889 du 29/10/1987
relatif aux conditions de recrutement et d'emploi de vacataires pour l'enseignement supérieur ;<br /><br />
            VU le décret n° 83-1175 du 23 décembre 1983 modifié relatif aux indemnités
pour enseignements complémentaires institués dans les établissements
publics à caractère scientifique et culturel et les autres établissements
d'enseignement supérieur relevant du ministère de l'éducation nationale ;<br /><br />
            VU le décret n° 87-889 du 29 octobre 1987 modifié relatif aux conditions de
recrutement et d'emploi de vacataires pour l'enseignement supérieur ;<br /><br />
            VU la proposition du directeur de la composante.
            <br /><br />
        </td>
    </tr>
</table>

<?php
$e = $f ? 'e' : '';
$qualiteIntervenant = $estATV ? "d'agent temporaire vacataire" : "de chargé$e d'enseignement vacataire";
?>

<h1 class="titre">
    <?php if ($estUnAvenant): ?>
        Avenant au contrat de travail initial modifiant le volume horaire initial
        de recrutement en qualité <?= $qualiteIntervenant ?>
    <?php else: ?>
        Contrat de travail <?= $qualiteIntervenant ?>
    <?php endif ?>
</h1>

<p>Entre d'une part :</p>
<p class="partie">
    <span class="etab"><?= $etablissement ?></span>, <?= $etablissementRepresente ?>
</p>

<p>et d'autre part :</p>
<p class="partie">
    <span class="intervenant"><?= $nomIntervenant ?></span>, né<?= $e ?> le <?= $dateNaissance ?><br />
</p>
<table class="partie">
    <tr>
        <td class="demeurant">Demeurant</td>
        <td><?= $adresseIntervenant ?></td>
    </tr>
</table>
<table class="partie">
    <tr>
        <td class="insee">N° INSEE</td>
        <td><?= $numeroINSEE ?></td>
    </tr>
</table>

<p>Il a été convenu ce qui suit :</p>

<p style="page-break-inside: avoid;">
<dl class="articles">

    <?php
    $servicesToString = $this->partial('application/service/partial/liste', ['services' => $servicesRecaps])
            . "Total des heures équivalent TD effectuées par $nomCompletIntervenant à " . lcfirst($etablissement)
            . " toutes composantes confondues : $totalHETD.";
    $noArticle = 1;
    ?>

    <?php if ($estUnAvenant): ?>

        <dt>Article <?= $noArticle++ ?> :</dt>
        <dd>
            <p>Le contrat de travail initial de <?= $nomCompletIntervenant ?> est <?= $contratIniModif ? "modifié" : "complété" ?> comme suit :</p>
            <div class="services"><?= $servicesToString ?></div>
        </dd>

    <?php else: ?>

        <dt>Article <?= $noArticle++ ?> :</dt>
        <dd>
            <p><?= $nomCompletIntervenant ?> est recruté<?= $e ?> pour l'année universitaire <?= $annee ?> en qualité
            <?= $qualiteIntervenant ?>.</p>
        </dd>

        <dt>Article <?= $noArticle++ ?> :</dt>
        <dd>
            <p>L'intéressé<?= $e ?> est chargé<?= $e ?> d'assurer les heures effectives d'enseignement suivantes :</p>
            <div class="services"><?= $servicesToString ?></div>
            <p>L'intéressé<?= $e ?> s'engage à assurer, sans rémunération complémentaire, toutes les obligations liées à ses enseignements (suivi pédagogique des étudiants, contrôle des connaissances et examens).</p>
        </dd>

    <?php endif ?>
</dl>
</p>

<p style="page-break-inside: avoid;">
    <dl class="articles">
        <dt>Article <?= $noArticle++ ?> :</dt>
        <dd>
            <p>L'intéressé<?= $e ?> sera rémunéré<?= $e ?> au taux horaire en vigueur pour les travaux dirigés fixé par arrêté publié au Journal Officiel, soit <?= \UnicaenApp\Util::formattedFloat($tauxHoraire->getValeur(), \NumberFormatter::DECIMAL, 2) ?> euros depuis le <?= $tauxHoraire->getHistoCreation()->format(\Application\Constants::DATE_FORMAT) ?>.</p>
            <p>L'intéressé<?= $e ?> est autorisé<?= $e ?>, le cas échéant, à percevoir une rémunération
            de formation continue fondée sur l'article D714-60 du code de l'Éducation, dans les conditions et selon les modalités de calcul
            approuvées par le conseil d'administration de l'université.</p>
            <p>Le paiement a lieu au vu de l'état liquidatif visé par le directeur de la composante et de la production d'un dossier complet.</p>
            <p>Une inexécution partielle du service imputable à l'intéressé<?= $e ?> entraîne un abattement correspondant aux heures non faites.</p>
        </dd>
    </dl>
</p>

<p class="fait">Fait à <?= $lieuSignature ?>, le <?= $dateSignature ?></p>

<table class="signatures">
    <tr>
        <td>Signature de l'intéressé<?= $e ?><br /><?= $nomIntervenant ?></td>
        <td>Pour <?= $civilitePresident ?>, par délégation :</td>
    </tr>
    <tr>
        <td><br /><br /><br /><br /></td>
        <td><br /><br /><br /><br /></td>
    </tr>
</table>

<p class="attention">Attention : Si le contrat n'est pas retourné signé, aucun service ne sera mis en paiement.</p>

<p class="renvoyer"><?= $mentionRetourner ?></p>