<style>
    body { font-family: ubuntu,arial,sans-serif; }
    .vu { font-size: 80%; }
    .titre { text-align: center; }
    .intitule-partie { font-weight: bold; }
    .partie { margin-left: 50px; }
    .articles dt { font-weight: bold; }
    .fait { text-align: center; }
    .signatures { width: 100%; }
    .signatures td { text-align: center; }
    .notes { font-style: italic; font-size: 90%; }
    .renvoyer { font-weight: bold; text-align: center; }
</style>

<table class="table table-bordered">
    <tr>
        <td width="300px">DIRECTION DES RESSOURCES HUMAINES</td>
        <td class="vu">
            VU le code de l'éducation, notamment son article L. 712-5 ;<br /><br />
            VU la loi n° 83-634 du 13 juillet 1983 modifiée portant droits et obligations des
fonctionnaires, ensemble le loi n° 84-16 du 11 janvier 1984 modifiée portant
dispositions statutaires relatives à la fonction publique de l'Etat ;<br /><br />
            VU la loi n° 2007-1199 du 10 août 2007 relative aux libertés et responsabilités
des universités, notamment son article 46 ;<br /><br />
            VU le décret n° 83-1175 du 23 décembre 1983 modifié relatif aux indemnités
DIRECTION DES RESSOURCES HUMAINES
pour enseignements complémentaires institués dans les établissements
publics à caractère scientifique et culturel et les autres établissements
d'enseignement supérieur relevant du ministère de l'éducation nationale ;<br /><br />
            VU le décret n° 87-889 du 29 octobre 1987 modifié relatif aux conditions de
recrutement et d'emploi de vacataires pour l'enseignement supérieur ;<br /><br />
            VU la proposition du directeur de la composante ;<br /><br />
            VU l'avis du Conseil Scientifique, réuni en formation restreinte, du XXXXXXX.<br /><br />
        </td>
    </tr>
</table>

<h1 class="titre">Contrat de travail de vacataire et chargé d'enseignement</h1>

<p class="intitule-partie">Entre</p>
<p class="partie">L'Université de Caen, représentée par son Président, Pierre SINEUX</p>

<p class="intitule-partie">d'une part, et</p>
<p class="partie">
    MACHIN Cousin, né le XXXXXX<br />
</p>
<table class="partie">
    <tr>
        <td>Demeurant</td>
        <td>XXXXX<br />ZZZZZZ<br />ZZZZZZ</td>
    </tr>
</table>
<table class="partie">
    <tr>
        <td>N° INSEE</td>
        <td>XXXXX</td>
    </tr>
</table>

<p class="intitule-partie">d'autre part</p>

<p class="partie">Il a été convenu de qui suit :</p>

<dl class="articles">
    <dt>Article 1er :</dt>
    <dd>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis sed sem libero. Nam urna magna, fringilla et blandit aliquam, condimentum a velit. Vivamus sollicitudin blandit augue ut dapibus. Vivamus faucibus quis massa id tempus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis auctor suscipit mauris, in suscipit quam lacinia ut. Nam ac mollis enim, quis tincidunt sem.</dd>

    <dt>Article 2 :</dt>
    <dd>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis sed sem libero. Nam urna magna, fringilla et blandit aliquam, condimentum a velit. Vivamus sollicitudin blandit augue ut dapibus. Vivamus faucibus quis massa id tempus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis auctor suscipit mauris, in suscipit quam lacinia ut. Nam ac mollis enim, quis tincidunt sem.</dd>

    <dt>Article 3 :</dt>
    <dd>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis sed sem libero. Nam urna magna, fringilla et blandit aliquam, condimentum a velit. Vivamus sollicitudin blandit augue ut dapibus. Vivamus faucibus quis massa id tempus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis auctor suscipit mauris, in suscipit quam lacinia ut. Nam ac mollis enim, quis tincidunt sem.</dd>
</dl>

<p class="fait">Fait à Caen, le XXXX</p>

<table class="signatures">
    <tr>
        <td>Signature de l'intéressé (1)<br />BUTERY Laurent</td>
        <td>Pour le Président, par délégation :<br />Le Directeur Général des Services</td>
    </tr>
    <tr>
        <td><br /><br /><br /><br /></td>
        <td><br /><br /><br /><br /></td>
    </tr>
</table>

<p class="notes">(1) Précédée de la mention "lu et approuvé"</p>

<p class="renvoyer">Exemplaire à renvoyer</p>