<?php $this->headTitle()->append($intervenant->getNomUsuel())->append("Contrat/avenant") ?>

<h1 class="page-header"><?php echo $title ?></h1>

<?php echo $this->messenger()->addMessagesFromFlashMessenger()->addMessages($messages) ?>

<?php if ($action && count($servicesDispos)): ?>
    <?php echo $this->serviceListe($servicesDispos)->render(); ?>
    <form method="POST">
        <input class="btn btn-primary" type="submit" name="submit" value="<?php echo $action ?>" />
    </form>
    <hr />
<?php endif; ?>

<?php echo $this->partial('application/contrat/partial/list', array(
    'contrats'    => $contrats,
    'services'    => $services, 
    'intervenant' => $intervenant,
    'role'        => $role));