<h2 class="page-header"><?php echo $title ?></h2>

<?php echo $this->messenger(true) ?>

<?php echo $this->partial('application/contrat/partial/list', array(
    'contrat'     => $contrat,
    'avenants'    => $avenants,
    'intervenant' => $intervenant)); ?>

<?php if ($action): ?>
<form method="POST">
    <input class="btn btn-primary" type="submit" name="submi" value="<?php echo $action ?>" />
</form>
<?php endif; ?>