<?php

use \Application\Service\Traits\ParametresServiceAwareTrait;
use Application\Provider\Privilege\Privileges;

/**
 * @var $this              \Application\View\Renderer\PhpRenderer
 * @var $title             string
 * @var $intervenant       \Application\Entity\Db\Intervenant
 * @var $contrats          \Application\Entity\Db\Contrat[]
 * @var $avenant           boolean
 * @var $contratDirect     boolean
 */

$hasContrat = false;
foreach ($contrats as $contrat) {
    if (!$contrat->estUnProjet()) {
        $hasContrat = true;
    }
}

$this->intervenant($intervenant)->renderTitle("Contrat/avenant");
echo $this->messenger()->addCurrentMessagesFromFlashMessenger();

if ($services['non-contractualises']) {
    $this->messenger()->addMessage('Des heures prévisionnelles d\'enseignement validées ne font l\'objet d\'aucun contrat ou avenant. En voici la liste ci-dessous :', 'danger');
} else {
    $this->messenger()->addMessage('Tous les enseignements prévisionnels validés ont fait l\'objet d\'un contrat ou d\'un avenant.', 'success');
}

$this->messenger() ?>

<style>
    th.structure, td.structure {
        width: 10%;
    }

    .ui-datepicker {
        z-index: 1151 !important;
    }

    td .panel {
        margin-bottom: 0px;
    }

</style>

<?php if ($contrats || $services['non-contractualises']): ?>

    <?php if ($services['non-contractualises']): ?>
        <?php if (!$hasContrat || $avenant): ?>
            <table class="table table-bordered table-hover">
            <tr>
                <th class="structure">Composante</th>
                <th>Enseignement(s) non contractualisé(s)</th>
            </tr>

            <?php foreach ($services['non-contractualises'] as $sid => $servicesNC):
                $structure = current($servicesNC)->getElementPedagogique()->getStructure();
                $contrat = new \Application\Entity\Db\Contrat();
                $contrat->setIntervenant($intervenant);
                $contrat->setStructure($structure);

                $canCreer = $this->isAllowed($contrat, Privileges::CONTRAT_CREATION);
                ?>
                <tr>
                    <td><?= $structure ?></td>
                    <td>
                        <?php if ($canCreer):
                            if ($contratDirect):?>
                                <a class="btn btn-primary"
                                   href="<?= $this->url('contrat/creer', ['intervenant' => $intervenant->getId(), 'structure' => $structure->getId()]); ?>">
                                    <i class="fas fa-file"></i> Créer un <?= $hasContrat ? 'avenant' : 'contrat' ?>
                                </a>
                            <?php else: ?>
                                <a class="btn btn-primary"
                                   href="<?= $this->url('contrat/creer', ['intervenant' => $intervenant->getId(), 'structure' => $structure->getId()]); ?>">
                                    <i class="fas fa-file"></i> Créer un projet <?= $hasContrat ? 'd\'avenant' : 'de contrat' ?>
                                </a>
                            <?php endif;
                        else:
                            echo $this->feuilleDeRoute($intervenant)->renderWhyNonAtteignable(\Application\Entity\Db\WfEtape::CODE_CONTRAT, $structure);
                        endif; ?>
                        <p>
                            Enseignements (validés) non contractualisés :<br/>
                            <small><a title="Cliquez pour afficher/masquer les enseignements concernés"
                                      href="#details-enseignements-structure-<?= $sid ?>"
                                      role="button"
                                      aria-expanded="true" aria-controls="details-enseignements-structure-<?= $sid ?>"
                                      data-toggle="collapse"
                                >Afficher/masquer</a></small>
                        </p>
                        <div class="collapse <?php if ($canCreer): ?>in<?php endif; ?>"
                             id="details-enseignements-structure-<?= $sid ?>">
                            <?= $this->serviceListe($servicesNC)->setReadonly(true)->setColumnVisibility('structure-ens', false)->render(); ?>
                        </div>
                    </td>
                </tr>
            <?php endforeach; ?>
        <?php else: ?>
            <div class="well">
                <h2>La création d'avenant n'est pas disponible, elle a été désactivée dans les paramètres.</h2>
            </div>
        <?php endif; ?>
        </table>

    <?php endif; ?>
    <div class="well">
        <h2>Contrats et avenants</h2>
        <?php foreach ($contrats as $contrat): ?>
            <?= $this->partial('application/contrat/partial/contrat', ['contrat' => $contrat, 'services' => $services['contractualises'][$contrat->getId()], 'emailIntervenant' => $emailIntervenant, 'contratDirect' => $contratDirect]);
            ?>

        <?php endforeach; ?>
    </div>
<?php else: ?>
    <p>Aucun contrat/avenant trouvé.</p>
<?php endif; ?>

<hr/>
<?= $this->feuilleDeRoute($intervenant)->renderNav(\Application\Entity\Db\WfEtape::CODE_CONTRAT); ?>

<script>
    $("body").on("envoi-mail-contrat", function (event, data)
    {
        console.log('event envoyé et affiché');
        event.div.modal('hide'); // ferme la fenêtre modale
        window.location.reload();
    });
</script>