<?php

/**
 * @var $this  \Application\View\Renderer\PhpRenderer
 * @var $form  ModeleForm
 * @var $title string
 */

use Application\Form\Contrat\ModeleForm;

?>
<h1 class="page-header"><?php echo $title ?></h1>

<?php

echo $this->messenger()->addCurrentMessagesFromFlashMessenger();

echo $this->form()->openTag($form);

?>

<?= $this->formControlGroup($form->get('libelle')) ?>
<div class="row">
    <div class="col-md-6">
        <?= $this->formControlGroup($form->get('structure')) ?>
    </div>
    <div class="col-md-6">
        <?= $this->formControlGroup($form->get('statut')) ?>
    </div>
</div>
<?= $this->formControlGroup($form->get('fichier')) ?>
<div class="alert alert-info" role="alert">
    Le champ "requête" ne doit être rempli que si des champs supplémentaires
    (qui ne seraient pas fournis par la vue v_contrat_main) doivent être transmis au modèle pour publipostage.
    En outre, une variable <b>:contrat</b> doit être insérée dans la requête pour que l'outil de publipostage puisse
    lui transmettre l'identifiant du contrat qui a été demandé.<br/>
    Exemple de requête :
    <pre style="padding:1px;font-size: 8pt">SELECT "n"+1 "n2"
FROM   v_contrat_main c
WHERE  c.contrat_id = :contrat</pre>
</div>
<?= $this->formControlGroup($form->get('requete')) ?>

<div class="panel-group" id="blocs" role="tablist" aria-multiselectable="true">

    <?php for ($i = 1; $i <= 10; $i++): ?>
        <div class="panel panel-default modele-contrat-bloc" id="bloc<?= $i ?>">
            <div class="panel-heading" role="tab" id="headingOne">
                <label>Champ de référence : </label> <?= $this->formText($form->get("bloc-$i-nom")) ?>
            </div>
            <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
                <div class="panel-body">
                    <?= $this->formTextarea($form->get("bloc-$i-requete")) ?>
                </div>
            </div>
        </div>
    <?php endfor; ?>
    <button type="button" class="btn btn-default btn-xs ajout-bloc">
        <i class="fa-solid fa-plus"></i> Ajouter un bloc
    </button>
</div>
<?php
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();


?>
<script>

    $(function ()
    {
        WidgetInitializer.add('contrat-modeles-editer', {
            requeteEditor: null,
            blocs: {},

            save: function ()
            {
                var requete = $("<input>")
                    .attr("type", "hidden")
                    .attr("name", "requete")
                    .val(this.requeteEditor.getSession().getValue());
                this.element.append($(requete));

                for (var i = 1; i <= 10; i++) {
                    var binput = $("<input>")
                        .attr("type", "hidden")
                        .attr("name", "bloc-" + i + "-requete")
                        .val(this.blocs[i].getSession().getValue());
                    this.element.append($(binput));
                }
            },

            ajoutBloc: function ()
            {
                for (var i = 1; i <= 10; i++) {
                    if (!this.isBlocRempli(i)) {
                        this.showBloc(i);
                        break;
                    }
                }
            },

            isBlocRempli: function (bloc)
            {
                var res = this.element.find('bloc-' + bloc + '-nom').val() != ''
                    && this.blocs[bloc].getSession().getValue() != '';

                return res;
            },

            showBloc: function (bloc)
            {
                this.element.find(".modele-contrat-bloc#bloc" + bloc).show();
            },

            hideBloc: function (bloc)
            {
                this.element.find(".modele-contrat-bloc#bloc" + bloc).hide();
            },

            _create: function ()
            {
                var that = this;

                that.element.find('.btn-save').click(function () { that.save();});
                that.element.find('.ajout-bloc').click(function () {that.ajoutBloc()});

                var options = {
                    minLines: 15, maxLines: 30,
                };

                that.requeteEditor = ace.edit("requete");
                that.requeteEditor.setTheme("ace/theme/github");
                that.requeteEditor.getSession().setMode("ace/mode/sql");
                that.requeteEditor.setOptions(options);

                for (var i = 1; i <= 10; i++) {
                    that.blocs[i] = ace.edit("bloc-" + i + "-requete");
                    that.blocs[i].setTheme("ace/theme/github");
                    that.blocs[i].getSession().setMode("ace/mode/sql");
                    that.blocs[i].setOptions(options);

                    if (that.isBlocRempli(i)) {
                        that.showBloc(i);
                    } else {
                        that.hideBloc(i);
                    }
                }
            }
        });

    });

</script>
<style>
    .modele-contrat-bloc {
        display: none;
    }

    .modele-contrat-bloc .panel-heading {
        padding-top: 3px;
        padding-bottom: 3px;
    }

    .modele-contrat-bloc .panel-heading .form-control {
        display: inline;
    }

    .modele-contrat-bloc .panel-heading .bloc-nom {
        width: 70%;
    }

    #fichier {
        height: none;
    }
</style>