<?php

use Application\Entity\Db\ModeleContrat;
use Application\Provider\Privilege\Privileges;

/**
 * @var $this    \Application\View\Renderer\PhpRenderer
 * @var $modeles ModeleContrat[]
 */

$canEdit = $this->isAllowed(Privileges::getResourceId(Privileges::CONTRAT_MODELES_EDITION));


/* On réutilise l'ACE d'UnicaenImport (pas top) */
echo $this->inlinescript()->appendFile($this->basePath() . '/vendor/ace-builds-master/src-min/ace.js');

?>
<h1 class="page-header">Gestion des modèles de contrats</h1>

<table class="table table-bordered">
    <thead>
    <tr>
        <th rowspan="2">Libellé</th>
        <th colspan="2">Éventuellement dédié à</th>
        <?php if ($canEdit): ?>
            <th rowspan="2" style="width:1%">Actions</th><?php endif; ?>
    </tr>
    <tr>
        <th>Composante</th>
        <th>Statut intervenant</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($modeles as $modele): ?>
        <tr>
            <td><?php
                echo $this->tag('a', [
                    'href' => $this->url('contrat/modeles/telecharger', ['modeleContrat' => $modele->getId()]),
                ])->text($modele->getLibelle());
                ?></td>
            <td><?= $modele->getStructure() ?></td>
            <td><?= $modele->getStatut() ?></td>
            <?php if ($canEdit): ?>
                <td>
                    <a class="ajax-modal" data-event="modeles-editer"
                       href="<?= $this->url('contrat/modeles/editer', ['modeleContrat' => $modele->getId()]) ?>">
                        <i class="fa-solid fa-pencil"></i>
                    </a>
                    <a class="pop-ajax"
                       data-event="type-intervention-saisie"
                       href="<?= $this->url('contrat/modeles/supprimer', ['modeleContrat' => $modele->getId()]) ?>"
                       title="Supprimer le modèle de contrat"
                       data-content="<p class='lead text-danger'><strong>Attention!</strong> Confirmez-vous cette suppression ?</p>"
                       data-confirm="true"
                       data-confirm-button="Oui"
                       data-cancel-button="Non"
                       data-submit-reload="true"
                    >
                        <i class="fa-solid fa-trash-can"></i>
                    </a>
                </td>
            <?php endif; ?>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<?php if ($canEdit): ?>
    <a class="btn btn-primary ajax-modal" data-event="modeles-editer" href="<?= $this->url('contrat/modeles/editer') ?>">
        <i class="fa-solid fa-plus"></i>
        Ajouter un modèle de contrat
    </a>
<?php endif; ?>
<script>

    $(function () {

        $("body").on("modeles-editer", function (event, data) {
            window.location.reload();
        });

    });

</script>
