<?php

/**
 * @var $this               \Application\View\Renderer\PhpRenderer
 * @var $doitEtreRequalifie boolean
 * @var $form               \Application\Form\Intervenant\ContratValidation
 */

?>
    <h1 class="page-header"><?php echo $title ?></h1>

<?php

echo $this->messenger()->addCurrentMessagesFromFlashMessenger();
if ($form) {
    $form->prepare();
    echo $this->form()->openTag($form);
    echo $this->formControlGroup($form->get('valide'));
    echo $this->formHidden($form->get('security'));
    echo $this->formSubmit($form->get('submit')->setAttribute('class', 'btn btn-primary'));
    echo $this->form()->closeTag();
}