<h2 class="page-header">Contrat et avenants <small><?php echo $intervenant ?></small></h2>

<?php if (!$contrats): ?>

    <?php //echo $this->messenger()->setMessage(sprintf("Le contrat de %s n'a pas encore été créé.", $intervenant)) ?>

<?php else: ?>

<?php echo $this->messenger(true) ?>

<?php echo $this->partial('application/contrat/partial/list', array(
    'contrats'    => $contrats, 
    'services'    => $services, 
    'intervenant' => $intervenant)); ?>

<?php endif; ?>


<?php if ($role instanceof \Application\Acl\IntervenantRole): ?>
    <hr />
    <?php echo $this->workflow($role->getIntervenant(), $role)->navNext() ?>
<?php endif; ?>
