<?php
/**
 * @var $this              \Application\View\Renderer\PhpRenderer
 */

use Mission\Entity\Db\MissionTauxRemu;
use Mission\Entity\Db\MissionTauxRemuValeur;


$this->headTitle()->append("Gestion des taux de missions");
echo $this->messenger()->addCurrentMessagesFromFlashMessenger();
?>
<h1 class="page-header">Gestion des taux de missions</h1>

<?php
/** @var MissionTauxRemu[] $tauxMissions */
/** @var string $annee */
$anneeSplit = explode('/', $annee); ?>

<table class="table table-bordered table-sm">
    <thead>
    <tr>
        <th style="text-align: center">Libelle</th>
        <th style="text-align: center">Code</th>
        <th style="text-align: center">Valeurs de l'année <?php echo $annee ?></th>
        <th style="text-align: center">Action</th>
    </tr>
    </thead>

    <tbody>
    <?php foreach ($tauxMissions as $tauxRemu):
        $tauxRemuValeurs = $tauxRemu->getTauxRemuValeurs();
        $dateDebutAnnee = "01-09-" . $anneeSplit[0];
        $dateFinAnnee = "01-09-" . $anneeSplit[1];
        $dateValide = false;
        $taux = ""; ?>
        <tr>
            <td><?php echo $tauxRemu->getLibelle(); ?></td>
            <td><?php echo $tauxRemu->getCode(); ?></td>
            <td style="text-align: center">
                <?php foreach ($tauxRemuValeurs as $tauxRemuValeur):
                    /** @var MissionTauxRemuValeur $tauxRemuValeur */
                    if ($tauxRemuValeur->getDateEffet() >= new DateTime($dateDebutAnnee) && $tauxRemuValeur->getDateEffet() < new DateTime($dateFinAnnee)):
                        $dateValide = true; ?>
                        <?php $newDate = $tauxRemuValeur->getDateEffet()->format('d/m/Y'); ?>

                        <a class="ajax-modal " data-event="taux-valeur-edition"
                           href="<?= $this->url("missions-taux/saisir-valeur", ['tauxRemuValeur' => $tauxRemuValeur->getId()], ['query' => ['tauxRemu' => $tauxRemu->getId()]]) ?>"
                           title="Modifier la valeur du taux">
                            <?php echo $tauxRemuValeur->getValeur() ?> - <?php echo $newDate ?><br>
                        </a>
                    <?php else:
                        $taux = $taux . "valeur: " . $tauxRemuValeur->getValeur() . " - Date: " . $tauxRemuValeur->getDateEffet()->format('d/m/Y') . "\n";
                    endif;
                endforeach;
                if ($taux != "") : ?>
                    <i class="fa-solid fa-circle-question" title="<?= $taux ?>"></i>
                <?php elseif (!$dateValide): ?>
                    <a class="ajax-modal " data-event="taux-valeur-edition"
                       href="<?= $this->url("missions-taux/saisir-valeur", ['tauxRemu' => $tauxRemu->getId()]) ?>"
                       title="Ajouter une valeur">
                        <i class="fas fa-plus"></i> Ajouter une valeur
                    </a>
                <?php endif; ?>
            </td>
            <td><a class="ajax-modal " data-event="taux-edition"
                   href="<?= $this->url("missions-taux/saisir", ['tauxRemu' => $tauxRemu->getId()], []) ?>"
                   title="Modifier le taux"><i class="fas fa-pen-to-square"></i></a>

                <a class="pop-ajax " data-title="Suppression d'un taux" data-content="Êtes-vous sur de vouloir supprimer"
                   data-confirm="true"
                   data-submit-reload="true"
                   href="<?= $this->url("missions-taux/supprimer", ['tauxRemu' => $tauxRemu->getId()]) ?>"
                   title="Supprimer le taux"><i class="fas fa-trash-can"></i></a>

            </td>
        </tr>

    <?php endforeach; ?>
    </tbody>

</table>
<div>
    <a class="btn btn-primary ajax-modal " data-event="taux-edition"
       href="<?= $this->url("missions-taux/saisir", []) ?>"
       title="Ajouter un taux">
        <i class="fas fa-plus"></i> Ajouter un taux
    </a>
</div>


<script type="text/javascript">
    $(function () {
        $("body").on("taux-edition", function (event, data) {
            window.location.reload();
        });
    });

    $(function () {
        $("body").on("taux-valeur-edition", function (event, data) {
            window.location.reload();
        });
    });
</script>