<?php
/**
 * @var $this              \Application\View\Renderer\PhpRenderer
 */

use Application\Provider\Privilege\Privileges;
use Mission\Entity\Db\MissionTauxRemu;
use Mission\Entity\Db\MissionTauxRemuValeur;


$this->headTitle()->append("Gestion des taux de missions");
$canEdit      = $this->isAllowed(Privileges::getResourceId(Privileges::MISSION_EDITION_TAUX));
$canSupprimer = $this->isAllowed(Privileges::getResourceId(Privileges::MISSION_SUPPRESSION_TAUX));
echo $this->messenger()->addCurrentMessagesFromFlashMessenger();
?>
<h1 class="page-header">Gestion des taux de missions</h1>

<?php
/** @var MissionTauxRemu[] $tauxMissions */
/** @var string $annee */
$anneeSplit = explode('/', $annee);


echo $this->vue('mission/liste-taux', [
    'canAddTaux' => true,
]);