<?php

/**
 * @var $this \Application\View\Renderer\PhpRenderer
 * @var $errors array
 * @var $discipline \OffreFormation\Entity\Db\Discipline
 * @var $form \Application\Form\Supprimer
 * @var $title string
 */

$this->messenger()->addCurrentMessagesFromFlashMessenger();
if ($form){
    echo '<p class="lead text-danger"><strong>Attention!</strong> Confirmez-vous la suppression de la discipline '.$discipline.' ?</p>';
    echo $this->formSupprimer($form);
}
