<?php
/**
 * Generated by UnicaenCode
 * Commande : ose-code  module='Enseignement'
 */
return [
    'enseignement/constatation'                     => __DIR__ . '/view/enseignement/constatation.phtml',
    'enseignement/initialisation'                   => __DIR__ . '/view/enseignement/initialisation.phtml',
    'enseignement/rafraichir-ligne'                 => __DIR__ . '/view/enseignement/rafraichir-ligne.phtml',
    'enseignement/volume-horaire/saisie-calendaire' => __DIR__ . '/view/enseignement/volume-horaire/saisie-calendaire.phtml',
    'enseignement/volume-horaire/saisie'            => __DIR__ . '/view/enseignement/volume-horaire/saisie.phtml',
    'enseignement/volume-horaire/liste'             => __DIR__ . '/view/enseignement/volume-horaire/liste.phtml',
    'enseignement/saisie-form-refresh-vh'           => __DIR__ . '/view/enseignement/saisie-form-refresh-vh.phtml',
    'enseignement/saisie'                           => __DIR__ . '/view/enseignement/saisie.phtml',
    'enseignement/validation'                       => __DIR__ . '/view/enseignement/validation.phtml',
    'enseignement/partial/liste'                    => __DIR__ . '/view/enseignement/partial/liste.phtml',
    'enseignement/partial/validation-enseignement'  => __DIR__ . '/view/enseignement/partial/validation-enseignement.phtml',
    'enseignement/index'                            => __DIR__ . '/view/enseignement/index.phtml',
];