<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Entity\Db;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class FormuleService extends \Application\Entity\Db\FormuleService implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Application\\Entity\\Db\\FormuleService' . "\0" . 'tauxFa', '' . "\0" . 'Application\\Entity\\Db\\FormuleService' . "\0" . 'tauxFc', '' . "\0" . 'Application\\Entity\\Db\\FormuleService' . "\0" . 'tauxFi', '' . "\0" . 'Application\\Entity\\Db\\FormuleService' . "\0" . 'ponderationServiceDu', '' . "\0" . 'Application\\Entity\\Db\\FormuleService' . "\0" . 'ponderationServiceCompl', '' . "\0" . 'Application\\Entity\\Db\\FormuleService' . "\0" . 'id', '' . "\0" . 'Application\\Entity\\Db\\FormuleService' . "\0" . 'service', '' . "\0" . 'Application\\Entity\\Db\\FormuleService' . "\0" . 'formuleVolumeHoraire', '' . "\0" . 'Application\\Entity\\Db\\FormuleService' . "\0" . 'intervenant', '' . "\0" . 'Application\\Entity\\Db\\FormuleService' . "\0" . 'annee', '' . "\0" . 'Application\\Entity\\Db\\FormuleService' . "\0" . 'formuleIntervenant');
        }

        return array('__isInitialized__', '' . "\0" . 'Application\\Entity\\Db\\FormuleService' . "\0" . 'tauxFa', '' . "\0" . 'Application\\Entity\\Db\\FormuleService' . "\0" . 'tauxFc', '' . "\0" . 'Application\\Entity\\Db\\FormuleService' . "\0" . 'tauxFi', '' . "\0" . 'Application\\Entity\\Db\\FormuleService' . "\0" . 'ponderationServiceDu', '' . "\0" . 'Application\\Entity\\Db\\FormuleService' . "\0" . 'ponderationServiceCompl', '' . "\0" . 'Application\\Entity\\Db\\FormuleService' . "\0" . 'id', '' . "\0" . 'Application\\Entity\\Db\\FormuleService' . "\0" . 'service', '' . "\0" . 'Application\\Entity\\Db\\FormuleService' . "\0" . 'formuleVolumeHoraire', '' . "\0" . 'Application\\Entity\\Db\\FormuleService' . "\0" . 'intervenant', '' . "\0" . 'Application\\Entity\\Db\\FormuleService' . "\0" . 'annee', '' . "\0" . 'Application\\Entity\\Db\\FormuleService' . "\0" . 'formuleIntervenant');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (FormuleService $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setTauxFa($tauxFa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTauxFa', array($tauxFa));

        return parent::setTauxFa($tauxFa);
    }

    /**
     * {@inheritDoc}
     */
    public function getTauxFa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTauxFa', array());

        return parent::getTauxFa();
    }

    /**
     * {@inheritDoc}
     */
    public function setTauxFc($tauxFc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTauxFc', array($tauxFc));

        return parent::setTauxFc($tauxFc);
    }

    /**
     * {@inheritDoc}
     */
    public function getTauxFc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTauxFc', array());

        return parent::getTauxFc();
    }

    /**
     * {@inheritDoc}
     */
    public function setTauxFi($tauxFi)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTauxFi', array($tauxFi));

        return parent::setTauxFi($tauxFi);
    }

    /**
     * {@inheritDoc}
     */
    public function getTauxFi()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTauxFi', array());

        return parent::getTauxFi();
    }

    /**
     * {@inheritDoc}
     */
    public function setPonderationServiceDu($ponderationServiceDu)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPonderationServiceDu', array($ponderationServiceDu));

        return parent::setPonderationServiceDu($ponderationServiceDu);
    }

    /**
     * {@inheritDoc}
     */
    public function getPonderationServiceDu()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPonderationServiceDu', array());

        return parent::getPonderationServiceDu();
    }

    /**
     * {@inheritDoc}
     */
    public function setPonderationServiceCompl($ponderationServiceCompl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPonderationServiceCompl', array($ponderationServiceCompl));

        return parent::setPonderationServiceCompl($ponderationServiceCompl);
    }

    /**
     * {@inheritDoc}
     */
    public function getPonderationServiceCompl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPonderationServiceCompl', array());

        return parent::getPonderationServiceCompl();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setService(\Application\Entity\Db\Service $service = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setService', array($service));

        return parent::setService($service);
    }

    /**
     * {@inheritDoc}
     */
    public function getService()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getService', array());

        return parent::getService();
    }

    /**
     * {@inheritDoc}
     */
    public function addFormuleVolumeHoraire(\Application\Entity\Db\FormuleVolumeHoraire $formuleVolumeHoraire)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addFormuleVolumeHoraire', array($formuleVolumeHoraire));

        return parent::addFormuleVolumeHoraire($formuleVolumeHoraire);
    }

    /**
     * {@inheritDoc}
     */
    public function removeFormuleVolumeHoraire(\Application\Entity\Db\FormuleVolumeHoraire $formuleVolumeHoraire)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeFormuleVolumeHoraire', array($formuleVolumeHoraire));

        return parent::removeFormuleVolumeHoraire($formuleVolumeHoraire);
    }

    /**
     * {@inheritDoc}
     */
    public function getFormuleVolumeHoraire(\Application\Entity\Db\TypeVolumeHoraire $typeVolumeHoraire = NULL, \Application\Entity\Db\EtatVolumeHoraire $etatVolumeHoraire = NULL, \Application\Entity\Db\TypeIntervention $typeIntervention = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFormuleVolumeHoraire', array($typeVolumeHoraire, $etatVolumeHoraire, $typeIntervention));

        return parent::getFormuleVolumeHoraire($typeVolumeHoraire, $etatVolumeHoraire, $typeIntervention);
    }

    /**
     * {@inheritDoc}
     */
    public function getHeures(\Application\Entity\Db\TypeVolumeHoraire $typeVolumeHoraire = NULL, \Application\Entity\Db\EtatVolumeHoraire $etatVolumeHoraire = NULL, \Application\Entity\Db\TypeIntervention $typeIntervention = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHeures', array($typeVolumeHoraire, $etatVolumeHoraire, $typeIntervention));

        return parent::getHeures($typeVolumeHoraire, $etatVolumeHoraire, $typeIntervention);
    }

    /**
     * {@inheritDoc}
     */
    public function setIntervenant(\Application\Entity\Db\Intervenant $intervenant = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIntervenant', array($intervenant));

        return parent::setIntervenant($intervenant);
    }

    /**
     * {@inheritDoc}
     */
    public function getIntervenant()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIntervenant', array());

        return parent::getIntervenant();
    }

    /**
     * {@inheritDoc}
     */
    public function setAnnee(\Application\Entity\Db\Annee $annee = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnnee', array($annee));

        return parent::setAnnee($annee);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnnee()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnnee', array());

        return parent::getAnnee();
    }

    /**
     * {@inheritDoc}
     */
    public function setFormuleIntervenant(\Application\Entity\Db\FormuleIntervenant $formuleIntervenant = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFormuleIntervenant', array($formuleIntervenant));

        return parent::setFormuleIntervenant($formuleIntervenant);
    }

    /**
     * {@inheritDoc}
     */
    public function getFormuleIntervenant()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFormuleIntervenant', array());

        return parent::getFormuleIntervenant();
    }

}
