<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Entity\Db;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class FormuleResultat extends \Application\Entity\Db\FormuleResultat implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Application\\Entity\\Db\\FormuleResultat' . "\0" . 'enseignements', '' . "\0" . 'Application\\Entity\\Db\\FormuleResultat' . "\0" . 'heuresSolde', '' . "\0" . 'Application\\Entity\\Db\\FormuleResultat' . "\0" . 'heuresComplFc', '' . "\0" . 'Application\\Entity\\Db\\FormuleResultat' . "\0" . 'heuresComplFa', '' . "\0" . 'Application\\Entity\\Db\\FormuleResultat' . "\0" . 'heuresComplFi', '' . "\0" . 'Application\\Entity\\Db\\FormuleResultat' . "\0" . 'heuresComplReferentiel', '' . "\0" . 'Application\\Entity\\Db\\FormuleResultat' . "\0" . 'heuresComplTotal', '' . "\0" . 'Application\\Entity\\Db\\FormuleResultat' . "\0" . 'service', '' . "\0" . 'Application\\Entity\\Db\\FormuleResultat' . "\0" . 'referentiel', '' . "\0" . 'Application\\Entity\\Db\\FormuleResultat' . "\0" . 'serviceAssure', '' . "\0" . 'Application\\Entity\\Db\\FormuleResultat' . "\0" . 'serviceDu', '' . "\0" . 'Application\\Entity\\Db\\FormuleResultat' . "\0" . 'sousService', '' . "\0" . 'Application\\Entity\\Db\\FormuleResultat' . "\0" . 'id', '' . "\0" . 'Application\\Entity\\Db\\FormuleResultat' . "\0" . 'formuleResultatService', '' . "\0" . 'Application\\Entity\\Db\\FormuleResultat' . "\0" . 'formuleResultatReferentiel', '' . "\0" . 'Application\\Entity\\Db\\FormuleResultat' . "\0" . 'typeVolumeHoraire', '' . "\0" . 'Application\\Entity\\Db\\FormuleResultat' . "\0" . 'intervenant', '' . "\0" . 'Application\\Entity\\Db\\FormuleResultat' . "\0" . 'etatVolumeHoraire', '' . "\0" . 'Application\\Entity\\Db\\FormuleResultat' . "\0" . 'annee');
        }

        return array('__isInitialized__', '' . "\0" . 'Application\\Entity\\Db\\FormuleResultat' . "\0" . 'enseignements', '' . "\0" . 'Application\\Entity\\Db\\FormuleResultat' . "\0" . 'heuresSolde', '' . "\0" . 'Application\\Entity\\Db\\FormuleResultat' . "\0" . 'heuresComplFc', '' . "\0" . 'Application\\Entity\\Db\\FormuleResultat' . "\0" . 'heuresComplFa', '' . "\0" . 'Application\\Entity\\Db\\FormuleResultat' . "\0" . 'heuresComplFi', '' . "\0" . 'Application\\Entity\\Db\\FormuleResultat' . "\0" . 'heuresComplReferentiel', '' . "\0" . 'Application\\Entity\\Db\\FormuleResultat' . "\0" . 'heuresComplTotal', '' . "\0" . 'Application\\Entity\\Db\\FormuleResultat' . "\0" . 'service', '' . "\0" . 'Application\\Entity\\Db\\FormuleResultat' . "\0" . 'referentiel', '' . "\0" . 'Application\\Entity\\Db\\FormuleResultat' . "\0" . 'serviceAssure', '' . "\0" . 'Application\\Entity\\Db\\FormuleResultat' . "\0" . 'serviceDu', '' . "\0" . 'Application\\Entity\\Db\\FormuleResultat' . "\0" . 'sousService', '' . "\0" . 'Application\\Entity\\Db\\FormuleResultat' . "\0" . 'id', '' . "\0" . 'Application\\Entity\\Db\\FormuleResultat' . "\0" . 'formuleResultatService', '' . "\0" . 'Application\\Entity\\Db\\FormuleResultat' . "\0" . 'formuleResultatReferentiel', '' . "\0" . 'Application\\Entity\\Db\\FormuleResultat' . "\0" . 'typeVolumeHoraire', '' . "\0" . 'Application\\Entity\\Db\\FormuleResultat' . "\0" . 'intervenant', '' . "\0" . 'Application\\Entity\\Db\\FormuleResultat' . "\0" . 'etatVolumeHoraire', '' . "\0" . 'Application\\Entity\\Db\\FormuleResultat' . "\0" . 'annee');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (FormuleResultat $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function init(\Application\Entity\Db\Intervenant $intervenant, \Application\Entity\Db\Annee $annee, \Application\Entity\Db\TypeVolumeHoraire $typeVolumeHoraire, \Application\Entity\Db\EtatVolumeHoraire $etatVolumeHoraire)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'init', array($intervenant, $annee, $typeVolumeHoraire, $etatVolumeHoraire));

        return parent::init($intervenant, $annee, $typeVolumeHoraire, $etatVolumeHoraire);
    }

    /**
     * {@inheritDoc}
     */
    public function getAPayer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAPayer', array());

        return parent::getAPayer();
    }

    /**
     * {@inheritDoc}
     */
    public function getEnseignements()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEnseignements', array());

        return parent::getEnseignements();
    }

    /**
     * {@inheritDoc}
     */
    public function getHeuresSolde()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHeuresSolde', array());

        return parent::getHeuresSolde();
    }

    /**
     * {@inheritDoc}
     */
    public function getHeuresComplFc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHeuresComplFc', array());

        return parent::getHeuresComplFc();
    }

    /**
     * {@inheritDoc}
     */
    public function getHeuresComplFa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHeuresComplFa', array());

        return parent::getHeuresComplFa();
    }

    /**
     * {@inheritDoc}
     */
    public function getHeuresComplFi()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHeuresComplFi', array());

        return parent::getHeuresComplFi();
    }

    /**
     * {@inheritDoc}
     */
    public function getHeuresComplReferentiel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHeuresComplReferentiel', array());

        return parent::getHeuresComplReferentiel();
    }

    /**
     * {@inheritDoc}
     */
    public function getHeuresComplTotal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHeuresComplTotal', array());

        return parent::getHeuresComplTotal();
    }

    /**
     * {@inheritDoc}
     */
    public function getService()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getService', array());

        return parent::getService();
    }

    /**
     * {@inheritDoc}
     */
    public function getReferentiel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReferentiel', array());

        return parent::getReferentiel();
    }

    /**
     * {@inheritDoc}
     */
    public function getServiceAssure()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getServiceAssure', array());

        return parent::getServiceAssure();
    }

    /**
     * {@inheritDoc}
     */
    public function getServiceDu()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getServiceDu', array());

        return parent::getServiceDu();
    }

    /**
     * {@inheritDoc}
     */
    public function getSousService()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSousService', array());

        return parent::getSousService();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getFormuleResultatService()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFormuleResultatService', array());

        return parent::getFormuleResultatService();
    }

    /**
     * {@inheritDoc}
     */
    public function getFormuleResultatReferentiel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFormuleResultatReferentiel', array());

        return parent::getFormuleResultatReferentiel();
    }

    /**
     * {@inheritDoc}
     */
    public function getTypeVolumeHoraire()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypeVolumeHoraire', array());

        return parent::getTypeVolumeHoraire();
    }

    /**
     * {@inheritDoc}
     */
    public function getIntervenant()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIntervenant', array());

        return parent::getIntervenant();
    }

    /**
     * {@inheritDoc}
     */
    public function getEtatVolumeHoraire()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEtatVolumeHoraire', array());

        return parent::getEtatVolumeHoraire();
    }

    /**
     * {@inheritDoc}
     */
    public function getAnnee()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnnee', array());

        return parent::getAnnee();
    }

}
