<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Entity\Db;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class FormuleService extends \Application\Entity\Db\FormuleService implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Application\\Entity\\Db\\FormuleService' . "\0" . 'ponderationServiceCompl', '' . "\0" . 'Application\\Entity\\Db\\FormuleService' . "\0" . 'ponderationServiceDu', '' . "\0" . 'Application\\Entity\\Db\\FormuleService' . "\0" . 'tauxFa', '' . "\0" . 'Application\\Entity\\Db\\FormuleService' . "\0" . 'tauxFc', '' . "\0" . 'Application\\Entity\\Db\\FormuleService' . "\0" . 'tauxFi', '' . "\0" . 'Application\\Entity\\Db\\FormuleService' . "\0" . 'id', '' . "\0" . 'Application\\Entity\\Db\\FormuleService' . "\0" . 'service', '' . "\0" . 'Application\\Entity\\Db\\FormuleService' . "\0" . 'intervenant', '' . "\0" . 'Application\\Entity\\Db\\FormuleService' . "\0" . 'annee', '' . "\0" . 'Application\\Entity\\Db\\FormuleService' . "\0" . 'structureAff', '' . "\0" . 'Application\\Entity\\Db\\FormuleService' . "\0" . 'structureEns', '' . "\0" . 'Application\\Entity\\Db\\FormuleService' . "\0" . 'formuleVolumeHoraire');
        }

        return array('__isInitialized__', '' . "\0" . 'Application\\Entity\\Db\\FormuleService' . "\0" . 'ponderationServiceCompl', '' . "\0" . 'Application\\Entity\\Db\\FormuleService' . "\0" . 'ponderationServiceDu', '' . "\0" . 'Application\\Entity\\Db\\FormuleService' . "\0" . 'tauxFa', '' . "\0" . 'Application\\Entity\\Db\\FormuleService' . "\0" . 'tauxFc', '' . "\0" . 'Application\\Entity\\Db\\FormuleService' . "\0" . 'tauxFi', '' . "\0" . 'Application\\Entity\\Db\\FormuleService' . "\0" . 'id', '' . "\0" . 'Application\\Entity\\Db\\FormuleService' . "\0" . 'service', '' . "\0" . 'Application\\Entity\\Db\\FormuleService' . "\0" . 'intervenant', '' . "\0" . 'Application\\Entity\\Db\\FormuleService' . "\0" . 'annee', '' . "\0" . 'Application\\Entity\\Db\\FormuleService' . "\0" . 'structureAff', '' . "\0" . 'Application\\Entity\\Db\\FormuleService' . "\0" . 'structureEns', '' . "\0" . 'Application\\Entity\\Db\\FormuleService' . "\0" . 'formuleVolumeHoraire');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (FormuleService $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getPonderationServiceCompl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPonderationServiceCompl', array());

        return parent::getPonderationServiceCompl();
    }

    /**
     * {@inheritDoc}
     */
    public function getPonderationServiceDu()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPonderationServiceDu', array());

        return parent::getPonderationServiceDu();
    }

    /**
     * {@inheritDoc}
     */
    public function getTauxFa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTauxFa', array());

        return parent::getTauxFa();
    }

    /**
     * {@inheritDoc}
     */
    public function getTauxFc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTauxFc', array());

        return parent::getTauxFc();
    }

    /**
     * {@inheritDoc}
     */
    public function getTauxFi()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTauxFi', array());

        return parent::getTauxFi();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getService()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getService', array());

        return parent::getService();
    }

    /**
     * {@inheritDoc}
     */
    public function getIntervenant()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIntervenant', array());

        return parent::getIntervenant();
    }

    /**
     * {@inheritDoc}
     */
    public function getAnnee()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnnee', array());

        return parent::getAnnee();
    }

    /**
     * {@inheritDoc}
     */
    public function getStructureAff()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStructureAff', array());

        return parent::getStructureAff();
    }

    /**
     * {@inheritDoc}
     */
    public function getStructureEns()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStructureEns', array());

        return parent::getStructureEns();
    }

    /**
     * {@inheritDoc}
     */
    public function getFormuleVolumeHoraire(\Application\Entity\Db\TypeIntervention $typeIntervention = NULL, \Application\Entity\Db\TypeVolumeHoraire $typeVolumeHoraire = NULL, \Application\Entity\Db\EtatVolumeHoraire $etatVolumehoraire = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFormuleVolumeHoraire', array($typeIntervention, $typeVolumeHoraire, $etatVolumehoraire));

        return parent::getFormuleVolumeHoraire($typeIntervention, $typeVolumeHoraire, $etatVolumehoraire);
    }

    /**
     * {@inheritDoc}
     */
    public function getHeures(\Application\Entity\Db\TypeIntervention $typeIntervention = NULL, \Application\Entity\Db\TypeVolumeHoraire $typeVolumeHoraire, \Application\Entity\Db\EtatVolumeHoraire $etatVolumehoraire)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHeures', array($typeIntervention, $typeVolumeHoraire, $etatVolumehoraire));

        return parent::getHeures($typeIntervention, $typeVolumeHoraire, $etatVolumehoraire);
    }

}
