<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Entity\Db;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class FormuleResultatVolumeHoraire extends \Application\Entity\Db\FormuleResultatVolumeHoraire implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Application\\Entity\\Db\\FormuleResultatVolumeHoraire' . "\0" . 'serviceAssure', '' . "\0" . 'Application\\Entity\\Db\\FormuleResultatVolumeHoraire' . "\0" . 'heuresService', '' . "\0" . 'Application\\Entity\\Db\\FormuleResultatVolumeHoraire' . "\0" . 'heuresComplFa', '' . "\0" . 'Application\\Entity\\Db\\FormuleResultatVolumeHoraire' . "\0" . 'heuresComplFi', '' . "\0" . 'Application\\Entity\\Db\\FormuleResultatVolumeHoraire' . "\0" . 'heuresComplFc', '' . "\0" . 'Application\\Entity\\Db\\FormuleResultatVolumeHoraire' . "\0" . 'heuresComplFcMajorees', '' . "\0" . 'Application\\Entity\\Db\\FormuleResultatVolumeHoraire' . "\0" . 'id', '' . "\0" . 'Application\\Entity\\Db\\FormuleResultatVolumeHoraire' . "\0" . 'formuleResultat', '' . "\0" . 'Application\\Entity\\Db\\FormuleResultatVolumeHoraire' . "\0" . 'volumeHoraire');
        }

        return array('__isInitialized__', '' . "\0" . 'Application\\Entity\\Db\\FormuleResultatVolumeHoraire' . "\0" . 'serviceAssure', '' . "\0" . 'Application\\Entity\\Db\\FormuleResultatVolumeHoraire' . "\0" . 'heuresService', '' . "\0" . 'Application\\Entity\\Db\\FormuleResultatVolumeHoraire' . "\0" . 'heuresComplFa', '' . "\0" . 'Application\\Entity\\Db\\FormuleResultatVolumeHoraire' . "\0" . 'heuresComplFi', '' . "\0" . 'Application\\Entity\\Db\\FormuleResultatVolumeHoraire' . "\0" . 'heuresComplFc', '' . "\0" . 'Application\\Entity\\Db\\FormuleResultatVolumeHoraire' . "\0" . 'heuresComplFcMajorees', '' . "\0" . 'Application\\Entity\\Db\\FormuleResultatVolumeHoraire' . "\0" . 'id', '' . "\0" . 'Application\\Entity\\Db\\FormuleResultatVolumeHoraire' . "\0" . 'formuleResultat', '' . "\0" . 'Application\\Entity\\Db\\FormuleResultatVolumeHoraire' . "\0" . 'volumeHoraire');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (FormuleResultatVolumeHoraire $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setServiceAssure($serviceAssure)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setServiceAssure', array($serviceAssure));

        return parent::setServiceAssure($serviceAssure);
    }

    /**
     * {@inheritDoc}
     */
    public function getServiceAssure()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getServiceAssure', array());

        return parent::getServiceAssure();
    }

    /**
     * {@inheritDoc}
     */
    public function setHeuresService($heuresService)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHeuresService', array($heuresService));

        return parent::setHeuresService($heuresService);
    }

    /**
     * {@inheritDoc}
     */
    public function getHeuresService()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHeuresService', array());

        return parent::getHeuresService();
    }

    /**
     * {@inheritDoc}
     */
    public function setHeuresComplFa($heuresComplFa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHeuresComplFa', array($heuresComplFa));

        return parent::setHeuresComplFa($heuresComplFa);
    }

    /**
     * {@inheritDoc}
     */
    public function getHeuresComplFa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHeuresComplFa', array());

        return parent::getHeuresComplFa();
    }

    /**
     * {@inheritDoc}
     */
    public function setHeuresComplFi($heuresComplFi)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHeuresComplFi', array($heuresComplFi));

        return parent::setHeuresComplFi($heuresComplFi);
    }

    /**
     * {@inheritDoc}
     */
    public function getHeuresComplFi()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHeuresComplFi', array());

        return parent::getHeuresComplFi();
    }

    /**
     * {@inheritDoc}
     */
    public function setHeuresComplFc($heuresComplFc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHeuresComplFc', array($heuresComplFc));

        return parent::setHeuresComplFc($heuresComplFc);
    }

    /**
     * {@inheritDoc}
     */
    public function getHeuresComplFc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHeuresComplFc', array());

        return parent::getHeuresComplFc();
    }

    /**
     * {@inheritDoc}
     */
    public function setHeuresComplFcMajorees($heuresComplFcMajorees)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHeuresComplFcMajorees', array($heuresComplFcMajorees));

        return parent::setHeuresComplFcMajorees($heuresComplFcMajorees);
    }

    /**
     * {@inheritDoc}
     */
    public function getHeuresComplFcMajorees()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHeuresComplFcMajorees', array());

        return parent::getHeuresComplFcMajorees();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setFormuleResultat(\Application\Entity\Db\FormuleResultat $formuleResultat = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFormuleResultat', array($formuleResultat));

        return parent::setFormuleResultat($formuleResultat);
    }

    /**
     * {@inheritDoc}
     */
    public function getFormuleResultat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFormuleResultat', array());

        return parent::getFormuleResultat();
    }

    /**
     * {@inheritDoc}
     */
    public function setVolumeHoraire(\Application\Entity\Db\VolumeHoraire $volumeHoraire = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVolumeHoraire', array($volumeHoraire));

        return parent::setVolumeHoraire($volumeHoraire);
    }

    /**
     * {@inheritDoc}
     */
    public function getVolumeHoraire()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVolumeHoraire', array());

        return parent::getVolumeHoraire();
    }

}
