<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Entity\Db;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class FormuleVolumeHoraireReferentiel extends \Application\Entity\Db\FormuleVolumeHoraireReferentiel implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Application\\Entity\\Db\\FormuleVolumeHoraireReferentiel' . "\0" . 'heures', '' . "\0" . 'Application\\Entity\\Db\\FormuleVolumeHoraireReferentiel' . "\0" . 'id', '' . "\0" . 'Application\\Entity\\Db\\FormuleVolumeHoraireReferentiel' . "\0" . 'volumeHoraireReferentiel', '' . "\0" . 'Application\\Entity\\Db\\FormuleVolumeHoraireReferentiel' . "\0" . 'serviceReferentiel', '' . "\0" . 'Application\\Entity\\Db\\FormuleVolumeHoraireReferentiel' . "\0" . 'intervenant', '' . "\0" . 'Application\\Entity\\Db\\FormuleVolumeHoraireReferentiel' . "\0" . 'annee', '' . "\0" . 'Application\\Entity\\Db\\FormuleVolumeHoraireReferentiel' . "\0" . 'typeVolumeHoraire', '' . "\0" . 'Application\\Entity\\Db\\FormuleVolumeHoraireReferentiel' . "\0" . 'etatVolumeHoraire', '' . "\0" . 'Application\\Entity\\Db\\FormuleVolumeHoraireReferentiel' . "\0" . 'formuleServiceReferentiel');
        }

        return array('__isInitialized__', '' . "\0" . 'Application\\Entity\\Db\\FormuleVolumeHoraireReferentiel' . "\0" . 'heures', '' . "\0" . 'Application\\Entity\\Db\\FormuleVolumeHoraireReferentiel' . "\0" . 'id', '' . "\0" . 'Application\\Entity\\Db\\FormuleVolumeHoraireReferentiel' . "\0" . 'volumeHoraireReferentiel', '' . "\0" . 'Application\\Entity\\Db\\FormuleVolumeHoraireReferentiel' . "\0" . 'serviceReferentiel', '' . "\0" . 'Application\\Entity\\Db\\FormuleVolumeHoraireReferentiel' . "\0" . 'intervenant', '' . "\0" . 'Application\\Entity\\Db\\FormuleVolumeHoraireReferentiel' . "\0" . 'annee', '' . "\0" . 'Application\\Entity\\Db\\FormuleVolumeHoraireReferentiel' . "\0" . 'typeVolumeHoraire', '' . "\0" . 'Application\\Entity\\Db\\FormuleVolumeHoraireReferentiel' . "\0" . 'etatVolumeHoraire', '' . "\0" . 'Application\\Entity\\Db\\FormuleVolumeHoraireReferentiel' . "\0" . 'formuleServiceReferentiel');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (FormuleVolumeHoraireReferentiel $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setHeures($heures)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHeures', array($heures));

        return parent::setHeures($heures);
    }

    /**
     * {@inheritDoc}
     */
    public function getHeures()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHeures', array());

        return parent::getHeures();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setVolumeHoraireReferentiel(\Application\Entity\Db\VolumeHoraireReferentiel $volumeHoraireReferentiel = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVolumeHoraireReferentiel', array($volumeHoraireReferentiel));

        return parent::setVolumeHoraireReferentiel($volumeHoraireReferentiel);
    }

    /**
     * {@inheritDoc}
     */
    public function getVolumeHoraireReferentiel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVolumeHoraireReferentiel', array());

        return parent::getVolumeHoraireReferentiel();
    }

    /**
     * {@inheritDoc}
     */
    public function setServiceReferentiel(\Application\Entity\Db\ServiceReferentiel $serviceReferentiel = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setServiceReferentiel', array($serviceReferentiel));

        return parent::setServiceReferentiel($serviceReferentiel);
    }

    /**
     * {@inheritDoc}
     */
    public function getServiceReferentiel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getServiceReferentiel', array());

        return parent::getServiceReferentiel();
    }

    /**
     * {@inheritDoc}
     */
    public function setIntervenant(\Application\Entity\Db\Intervenant $intervenant = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIntervenant', array($intervenant));

        return parent::setIntervenant($intervenant);
    }

    /**
     * {@inheritDoc}
     */
    public function getIntervenant()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIntervenant', array());

        return parent::getIntervenant();
    }

    /**
     * {@inheritDoc}
     */
    public function setAnnee(\Application\Entity\Db\Annee $annee = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnnee', array($annee));

        return parent::setAnnee($annee);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnnee()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnnee', array());

        return parent::getAnnee();
    }

    /**
     * {@inheritDoc}
     */
    public function setTypeVolumeHoraire(\Application\Entity\Db\TypeVolumeHoraire $typeVolumeHoraire = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTypeVolumeHoraire', array($typeVolumeHoraire));

        return parent::setTypeVolumeHoraire($typeVolumeHoraire);
    }

    /**
     * {@inheritDoc}
     */
    public function getTypeVolumeHoraire()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypeVolumeHoraire', array());

        return parent::getTypeVolumeHoraire();
    }

    /**
     * {@inheritDoc}
     */
    public function setEtatVolumeHoraire(\Application\Entity\Db\EtatVolumeHoraire $etatVolumeHoraire = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEtatVolumeHoraire', array($etatVolumeHoraire));

        return parent::setEtatVolumeHoraire($etatVolumeHoraire);
    }

    /**
     * {@inheritDoc}
     */
    public function getEtatVolumeHoraire()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEtatVolumeHoraire', array());

        return parent::getEtatVolumeHoraire();
    }

    /**
     * {@inheritDoc}
     */
    public function setFormuleServiceReferentiel(\Application\Entity\Db\FormuleServiceReferentiel $formuleServiceReferentiel = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFormuleServiceReferentiel', array($formuleServiceReferentiel));

        return parent::setFormuleServiceReferentiel($formuleServiceReferentiel);
    }

    /**
     * {@inheritDoc}
     */
    public function getFormuleServiceReferentiel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFormuleServiceReferentiel', array());

        return parent::getFormuleServiceReferentiel();
    }

}
