<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Entity\Db;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class WfEtape extends \Application\Entity\Db\WfEtape implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Application\\Entity\\Db\\WfEtape' . "\0" . 'code', '' . "\0" . 'Application\\Entity\\Db\\WfEtape' . "\0" . 'libelle', '' . "\0" . 'Application\\Entity\\Db\\WfEtape' . "\0" . 'pertinFunc', '' . "\0" . 'Application\\Entity\\Db\\WfEtape' . "\0" . 'franchFunc', '' . "\0" . 'Application\\Entity\\Db\\WfEtape' . "\0" . 'pertinRuleClass', '' . "\0" . 'Application\\Entity\\Db\\WfEtape' . "\0" . 'franchRuleClass', '' . "\0" . 'Application\\Entity\\Db\\WfEtape' . "\0" . 'stepClass', '' . "\0" . 'Application\\Entity\\Db\\WfEtape' . "\0" . 'structureDependant', '' . "\0" . 'Application\\Entity\\Db\\WfEtape' . "\0" . 'visible', '' . "\0" . 'Application\\Entity\\Db\\WfEtape' . "\0" . 'id', '' . "\0" . 'Application\\Entity\\Db\\WfEtape' . "\0" . 'etapePrecedente', '' . "\0" . 'Application\\Entity\\Db\\WfEtape' . "\0" . 'etapeSuivante');
        }

        return array('__isInitialized__', '' . "\0" . 'Application\\Entity\\Db\\WfEtape' . "\0" . 'code', '' . "\0" . 'Application\\Entity\\Db\\WfEtape' . "\0" . 'libelle', '' . "\0" . 'Application\\Entity\\Db\\WfEtape' . "\0" . 'pertinFunc', '' . "\0" . 'Application\\Entity\\Db\\WfEtape' . "\0" . 'franchFunc', '' . "\0" . 'Application\\Entity\\Db\\WfEtape' . "\0" . 'pertinRuleClass', '' . "\0" . 'Application\\Entity\\Db\\WfEtape' . "\0" . 'franchRuleClass', '' . "\0" . 'Application\\Entity\\Db\\WfEtape' . "\0" . 'stepClass', '' . "\0" . 'Application\\Entity\\Db\\WfEtape' . "\0" . 'structureDependant', '' . "\0" . 'Application\\Entity\\Db\\WfEtape' . "\0" . 'visible', '' . "\0" . 'Application\\Entity\\Db\\WfEtape' . "\0" . 'id', '' . "\0" . 'Application\\Entity\\Db\\WfEtape' . "\0" . 'etapePrecedente', '' . "\0" . 'Application\\Entity\\Db\\WfEtape' . "\0" . 'etapeSuivante');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (WfEtape $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function setCode($code)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCode', array($code));

        return parent::setCode($code);
    }

    /**
     * {@inheritDoc}
     */
    public function getCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCode', array());

        return parent::getCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setLibelle($libelle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLibelle', array($libelle));

        return parent::setLibelle($libelle);
    }

    /**
     * {@inheritDoc}
     */
    public function getLibelle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLibelle', array());

        return parent::getLibelle();
    }

    /**
     * {@inheritDoc}
     */
    public function setPertinFunc($pertinFunc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPertinFunc', array($pertinFunc));

        return parent::setPertinFunc($pertinFunc);
    }

    /**
     * {@inheritDoc}
     */
    public function getPertinFunc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPertinFunc', array());

        return parent::getPertinFunc();
    }

    /**
     * {@inheritDoc}
     */
    public function setFranchFunc($franchFunc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFranchFunc', array($franchFunc));

        return parent::setFranchFunc($franchFunc);
    }

    /**
     * {@inheritDoc}
     */
    public function getFranchFunc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFranchFunc', array());

        return parent::getFranchFunc();
    }

    /**
     * {@inheritDoc}
     */
    public function setPertinRuleClass($pertinRuleClass)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPertinRuleClass', array($pertinRuleClass));

        return parent::setPertinRuleClass($pertinRuleClass);
    }

    /**
     * {@inheritDoc}
     */
    public function getPertinRuleClass()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPertinRuleClass', array());

        return parent::getPertinRuleClass();
    }

    /**
     * {@inheritDoc}
     */
    public function setFranchRuleClass($franchRuleClass)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFranchRuleClass', array($franchRuleClass));

        return parent::setFranchRuleClass($franchRuleClass);
    }

    /**
     * {@inheritDoc}
     */
    public function getFranchRuleClass()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFranchRuleClass', array());

        return parent::getFranchRuleClass();
    }

    /**
     * {@inheritDoc}
     */
    public function setStepClass($stepClass)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStepClass', array($stepClass));

        return parent::setStepClass($stepClass);
    }

    /**
     * {@inheritDoc}
     */
    public function getStepClass()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStepClass', array());

        return parent::getStepClass();
    }

    /**
     * {@inheritDoc}
     */
    public function setStructureDependant($structureDependant)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStructureDependant', array($structureDependant));

        return parent::setStructureDependant($structureDependant);
    }

    /**
     * {@inheritDoc}
     */
    public function getStructureDependant()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStructureDependant', array());

        return parent::getStructureDependant();
    }

    /**
     * {@inheritDoc}
     */
    public function setVisible($visible)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVisible', array($visible));

        return parent::setVisible($visible);
    }

    /**
     * {@inheritDoc}
     */
    public function getVisible()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVisible', array());

        return parent::getVisible();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function addEtapePrecedente(\Application\Entity\Db\WfEtape $etapePrecedente)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addEtapePrecedente', array($etapePrecedente));

        return parent::addEtapePrecedente($etapePrecedente);
    }

    /**
     * {@inheritDoc}
     */
    public function removeEtapePrecedente(\Application\Entity\Db\WfEtape $etapePrecedente)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeEtapePrecedente', array($etapePrecedente));

        return parent::removeEtapePrecedente($etapePrecedente);
    }

    /**
     * {@inheritDoc}
     */
    public function getEtapePrecedente()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEtapePrecedente', array());

        return parent::getEtapePrecedente();
    }

    /**
     * {@inheritDoc}
     */
    public function addEtapeSuivante(\Application\Entity\Db\WfEtape $etapeSuivante)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addEtapeSuivante', array($etapeSuivante));

        return parent::addEtapeSuivante($etapeSuivante);
    }

    /**
     * {@inheritDoc}
     */
    public function removeEtapeSuivante(\Application\Entity\Db\WfEtape $etapeSuivante)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeEtapeSuivante', array($etapeSuivante));

        return parent::removeEtapeSuivante($etapeSuivante);
    }

    /**
     * {@inheritDoc}
     */
    public function getEtapeSuivante()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEtapeSuivante', array());

        return parent::getEtapeSuivante();
    }

}
