<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Entity\Db;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class FormuleIntervenant extends \Application\Entity\Db\FormuleIntervenant implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Application\\Entity\\Db\\FormuleIntervenant' . "\0" . 'heuresServiceStatutaire', '' . "\0" . 'Application\\Entity\\Db\\FormuleIntervenant' . "\0" . 'id', '' . "\0" . 'Application\\Entity\\Db\\FormuleIntervenant' . "\0" . 'intervenant', '' . "\0" . 'Application\\Entity\\Db\\FormuleIntervenant' . "\0" . 'formuleServiceModifie', '' . "\0" . 'Application\\Entity\\Db\\FormuleIntervenant' . "\0" . 'formuleService', '' . "\0" . 'Application\\Entity\\Db\\FormuleIntervenant' . "\0" . 'formuleServiceReferentiel', '' . "\0" . 'Application\\Entity\\Db\\FormuleIntervenant' . "\0" . 'structure');
        }

        return array('__isInitialized__', '' . "\0" . 'Application\\Entity\\Db\\FormuleIntervenant' . "\0" . 'heuresServiceStatutaire', '' . "\0" . 'Application\\Entity\\Db\\FormuleIntervenant' . "\0" . 'id', '' . "\0" . 'Application\\Entity\\Db\\FormuleIntervenant' . "\0" . 'intervenant', '' . "\0" . 'Application\\Entity\\Db\\FormuleIntervenant' . "\0" . 'formuleServiceModifie', '' . "\0" . 'Application\\Entity\\Db\\FormuleIntervenant' . "\0" . 'formuleService', '' . "\0" . 'Application\\Entity\\Db\\FormuleIntervenant' . "\0" . 'formuleServiceReferentiel', '' . "\0" . 'Application\\Entity\\Db\\FormuleIntervenant' . "\0" . 'structure');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (FormuleIntervenant $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setHeuresServiceStatutaire($heuresServiceStatutaire)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHeuresServiceStatutaire', array($heuresServiceStatutaire));

        return parent::setHeuresServiceStatutaire($heuresServiceStatutaire);
    }

    /**
     * {@inheritDoc}
     */
    public function getHeuresServiceStatutaire()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHeuresServiceStatutaire', array());

        return parent::getHeuresServiceStatutaire();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setIntervenant(\Application\Entity\Db\Intervenant $intervenant = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIntervenant', array($intervenant));

        return parent::setIntervenant($intervenant);
    }

    /**
     * {@inheritDoc}
     */
    public function getIntervenant()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIntervenant', array());

        return parent::getIntervenant();
    }

    /**
     * {@inheritDoc}
     */
    public function addFormuleServiceModifie(\Application\Entity\Db\FormuleServiceModifie $formuleServiceModifie)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addFormuleServiceModifie', array($formuleServiceModifie));

        return parent::addFormuleServiceModifie($formuleServiceModifie);
    }

    /**
     * {@inheritDoc}
     */
    public function removeFormuleServiceModifie(\Application\Entity\Db\FormuleServiceModifie $formuleServiceModifie)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeFormuleServiceModifie', array($formuleServiceModifie));

        return parent::removeFormuleServiceModifie($formuleServiceModifie);
    }

    /**
     * {@inheritDoc}
     */
    public function getFormuleServiceModifie()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFormuleServiceModifie', array());

        return parent::getFormuleServiceModifie();
    }

    /**
     * {@inheritDoc}
     */
    public function addFormuleService(\Application\Entity\Db\FormuleService $formuleService)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addFormuleService', array($formuleService));

        return parent::addFormuleService($formuleService);
    }

    /**
     * {@inheritDoc}
     */
    public function removeFormuleService(\Application\Entity\Db\FormuleService $formuleService)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeFormuleService', array($formuleService));

        return parent::removeFormuleService($formuleService);
    }

    /**
     * {@inheritDoc}
     */
    public function getFormuleService()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFormuleService', array());

        return parent::getFormuleService();
    }

    /**
     * {@inheritDoc}
     */
    public function addFormuleServiceReferentiel(\Application\Entity\Db\FormuleServiceReferentiel $formuleServiceReferentiel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addFormuleServiceReferentiel', array($formuleServiceReferentiel));

        return parent::addFormuleServiceReferentiel($formuleServiceReferentiel);
    }

    /**
     * {@inheritDoc}
     */
    public function removeFormuleServiceReferentiel(\Application\Entity\Db\FormuleServiceReferentiel $formuleServiceReferentiel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeFormuleServiceReferentiel', array($formuleServiceReferentiel));

        return parent::removeFormuleServiceReferentiel($formuleServiceReferentiel);
    }

    /**
     * {@inheritDoc}
     */
    public function getFormuleServiceReferentiel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFormuleServiceReferentiel', array());

        return parent::getFormuleServiceReferentiel();
    }

    /**
     * {@inheritDoc}
     */
    public function setStructure(\Application\Entity\Db\Structure $structure = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStructure', array($structure));

        return parent::setStructure($structure);
    }

    /**
     * {@inheritDoc}
     */
    public function getStructure()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStructure', array());

        return parent::getStructure();
    }

}
