<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Entity\Db;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class FormuleResultat extends \Application\Entity\Db\FormuleResultat implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Application\\Entity\\Db\\FormuleResultat' . "\0" . 'serviceDu', '' . "\0" . 'Application\\Entity\\Db\\FormuleResultat' . "\0" . 'enseignements', '' . "\0" . 'Application\\Entity\\Db\\FormuleResultat' . "\0" . 'referentiel', '' . "\0" . 'Application\\Entity\\Db\\FormuleResultat' . "\0" . 'serviceAssure', '' . "\0" . 'Application\\Entity\\Db\\FormuleResultat' . "\0" . 'service', '' . "\0" . 'Application\\Entity\\Db\\FormuleResultat' . "\0" . 'heuresSolde', '' . "\0" . 'Application\\Entity\\Db\\FormuleResultat' . "\0" . 'heuresComplFi', '' . "\0" . 'Application\\Entity\\Db\\FormuleResultat' . "\0" . 'heuresComplFa', '' . "\0" . 'Application\\Entity\\Db\\FormuleResultat' . "\0" . 'heuresComplFc', '' . "\0" . 'Application\\Entity\\Db\\FormuleResultat' . "\0" . 'heuresComplFcMajorees', '' . "\0" . 'Application\\Entity\\Db\\FormuleResultat' . "\0" . 'heuresComplReferentiel', '' . "\0" . 'Application\\Entity\\Db\\FormuleResultat' . "\0" . 'heuresComplTotal', '' . "\0" . 'Application\\Entity\\Db\\FormuleResultat' . "\0" . 'sousService', '' . "\0" . 'Application\\Entity\\Db\\FormuleResultat' . "\0" . 'id', '' . "\0" . 'Application\\Entity\\Db\\FormuleResultat' . "\0" . 'formuleResultatService', '' . "\0" . 'Application\\Entity\\Db\\FormuleResultat' . "\0" . 'formuleResultatServiceReferentiel', '' . "\0" . 'Application\\Entity\\Db\\FormuleResultat' . "\0" . 'formuleResultatVolumeHoraire', '' . "\0" . 'Application\\Entity\\Db\\FormuleResultat' . "\0" . 'formuleResultatVolumeHoraireReferentiel', '' . "\0" . 'Application\\Entity\\Db\\FormuleResultat' . "\0" . 'intervenant', '' . "\0" . 'Application\\Entity\\Db\\FormuleResultat' . "\0" . 'annee', '' . "\0" . 'Application\\Entity\\Db\\FormuleResultat' . "\0" . 'typeVolumeHoraire', '' . "\0" . 'Application\\Entity\\Db\\FormuleResultat' . "\0" . 'etatVolumeHoraire');
        }

        return array('__isInitialized__', '' . "\0" . 'Application\\Entity\\Db\\FormuleResultat' . "\0" . 'serviceDu', '' . "\0" . 'Application\\Entity\\Db\\FormuleResultat' . "\0" . 'enseignements', '' . "\0" . 'Application\\Entity\\Db\\FormuleResultat' . "\0" . 'referentiel', '' . "\0" . 'Application\\Entity\\Db\\FormuleResultat' . "\0" . 'serviceAssure', '' . "\0" . 'Application\\Entity\\Db\\FormuleResultat' . "\0" . 'service', '' . "\0" . 'Application\\Entity\\Db\\FormuleResultat' . "\0" . 'heuresSolde', '' . "\0" . 'Application\\Entity\\Db\\FormuleResultat' . "\0" . 'heuresComplFi', '' . "\0" . 'Application\\Entity\\Db\\FormuleResultat' . "\0" . 'heuresComplFa', '' . "\0" . 'Application\\Entity\\Db\\FormuleResultat' . "\0" . 'heuresComplFc', '' . "\0" . 'Application\\Entity\\Db\\FormuleResultat' . "\0" . 'heuresComplFcMajorees', '' . "\0" . 'Application\\Entity\\Db\\FormuleResultat' . "\0" . 'heuresComplReferentiel', '' . "\0" . 'Application\\Entity\\Db\\FormuleResultat' . "\0" . 'heuresComplTotal', '' . "\0" . 'Application\\Entity\\Db\\FormuleResultat' . "\0" . 'sousService', '' . "\0" . 'Application\\Entity\\Db\\FormuleResultat' . "\0" . 'id', '' . "\0" . 'Application\\Entity\\Db\\FormuleResultat' . "\0" . 'formuleResultatService', '' . "\0" . 'Application\\Entity\\Db\\FormuleResultat' . "\0" . 'formuleResultatServiceReferentiel', '' . "\0" . 'Application\\Entity\\Db\\FormuleResultat' . "\0" . 'formuleResultatVolumeHoraire', '' . "\0" . 'Application\\Entity\\Db\\FormuleResultat' . "\0" . 'formuleResultatVolumeHoraireReferentiel', '' . "\0" . 'Application\\Entity\\Db\\FormuleResultat' . "\0" . 'intervenant', '' . "\0" . 'Application\\Entity\\Db\\FormuleResultat' . "\0" . 'annee', '' . "\0" . 'Application\\Entity\\Db\\FormuleResultat' . "\0" . 'typeVolumeHoraire', '' . "\0" . 'Application\\Entity\\Db\\FormuleResultat' . "\0" . 'etatVolumeHoraire');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (FormuleResultat $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setServiceDu($serviceDu)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setServiceDu', array($serviceDu));

        return parent::setServiceDu($serviceDu);
    }

    /**
     * {@inheritDoc}
     */
    public function getServiceDu()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getServiceDu', array());

        return parent::getServiceDu();
    }

    /**
     * {@inheritDoc}
     */
    public function setEnseignements($enseignements)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEnseignements', array($enseignements));

        return parent::setEnseignements($enseignements);
    }

    /**
     * {@inheritDoc}
     */
    public function getEnseignements()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEnseignements', array());

        return parent::getEnseignements();
    }

    /**
     * {@inheritDoc}
     */
    public function setReferentiel($referentiel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReferentiel', array($referentiel));

        return parent::setReferentiel($referentiel);
    }

    /**
     * {@inheritDoc}
     */
    public function getReferentiel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReferentiel', array());

        return parent::getReferentiel();
    }

    /**
     * {@inheritDoc}
     */
    public function setServiceAssure($serviceAssure)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setServiceAssure', array($serviceAssure));

        return parent::setServiceAssure($serviceAssure);
    }

    /**
     * {@inheritDoc}
     */
    public function getServiceAssure()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getServiceAssure', array());

        return parent::getServiceAssure();
    }

    /**
     * {@inheritDoc}
     */
    public function setService($service)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setService', array($service));

        return parent::setService($service);
    }

    /**
     * {@inheritDoc}
     */
    public function getService()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getService', array());

        return parent::getService();
    }

    /**
     * {@inheritDoc}
     */
    public function setHeuresSolde($heuresSolde)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHeuresSolde', array($heuresSolde));

        return parent::setHeuresSolde($heuresSolde);
    }

    /**
     * {@inheritDoc}
     */
    public function getHeuresSolde()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHeuresSolde', array());

        return parent::getHeuresSolde();
    }

    /**
     * {@inheritDoc}
     */
    public function setHeuresComplFi($heuresComplFi)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHeuresComplFi', array($heuresComplFi));

        return parent::setHeuresComplFi($heuresComplFi);
    }

    /**
     * {@inheritDoc}
     */
    public function getHeuresComplFi()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHeuresComplFi', array());

        return parent::getHeuresComplFi();
    }

    /**
     * {@inheritDoc}
     */
    public function setHeuresComplFa($heuresComplFa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHeuresComplFa', array($heuresComplFa));

        return parent::setHeuresComplFa($heuresComplFa);
    }

    /**
     * {@inheritDoc}
     */
    public function getHeuresComplFa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHeuresComplFa', array());

        return parent::getHeuresComplFa();
    }

    /**
     * {@inheritDoc}
     */
    public function setHeuresComplFc($heuresComplFc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHeuresComplFc', array($heuresComplFc));

        return parent::setHeuresComplFc($heuresComplFc);
    }

    /**
     * {@inheritDoc}
     */
    public function getHeuresComplFc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHeuresComplFc', array());

        return parent::getHeuresComplFc();
    }

    /**
     * {@inheritDoc}
     */
    public function setHeuresComplFcMajorees($heuresComplFcMajorees)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHeuresComplFcMajorees', array($heuresComplFcMajorees));

        return parent::setHeuresComplFcMajorees($heuresComplFcMajorees);
    }

    /**
     * {@inheritDoc}
     */
    public function getHeuresComplFcMajorees()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHeuresComplFcMajorees', array());

        return parent::getHeuresComplFcMajorees();
    }

    /**
     * {@inheritDoc}
     */
    public function setHeuresComplReferentiel($heuresComplReferentiel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHeuresComplReferentiel', array($heuresComplReferentiel));

        return parent::setHeuresComplReferentiel($heuresComplReferentiel);
    }

    /**
     * {@inheritDoc}
     */
    public function getHeuresComplReferentiel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHeuresComplReferentiel', array());

        return parent::getHeuresComplReferentiel();
    }

    /**
     * {@inheritDoc}
     */
    public function setHeuresComplTotal($heuresComplTotal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHeuresComplTotal', array($heuresComplTotal));

        return parent::setHeuresComplTotal($heuresComplTotal);
    }

    /**
     * {@inheritDoc}
     */
    public function getHeuresComplTotal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHeuresComplTotal', array());

        return parent::getHeuresComplTotal();
    }

    /**
     * {@inheritDoc}
     */
    public function setSousService($sousService)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSousService', array($sousService));

        return parent::setSousService($sousService);
    }

    /**
     * {@inheritDoc}
     */
    public function getSousService()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSousService', array());

        return parent::getSousService();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function addFormuleResultatService(\Application\Entity\Db\FormuleResultatService $formuleResultatService)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addFormuleResultatService', array($formuleResultatService));

        return parent::addFormuleResultatService($formuleResultatService);
    }

    /**
     * {@inheritDoc}
     */
    public function removeFormuleResultatService(\Application\Entity\Db\FormuleResultatService $formuleResultatService)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeFormuleResultatService', array($formuleResultatService));

        return parent::removeFormuleResultatService($formuleResultatService);
    }

    /**
     * {@inheritDoc}
     */
    public function getFormuleResultatService()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFormuleResultatService', array());

        return parent::getFormuleResultatService();
    }

    /**
     * {@inheritDoc}
     */
    public function addFormuleResultatServiceReferentiel(\Application\Entity\Db\FormuleResultatServiceReferentiel $formuleResultatServiceReferentiel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addFormuleResultatServiceReferentiel', array($formuleResultatServiceReferentiel));

        return parent::addFormuleResultatServiceReferentiel($formuleResultatServiceReferentiel);
    }

    /**
     * {@inheritDoc}
     */
    public function removeFormuleResultatServiceReferentiel(\Application\Entity\Db\FormuleResultatServiceReferentiel $formuleResultatServiceReferentiel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeFormuleResultatServiceReferentiel', array($formuleResultatServiceReferentiel));

        return parent::removeFormuleResultatServiceReferentiel($formuleResultatServiceReferentiel);
    }

    /**
     * {@inheritDoc}
     */
    public function getFormuleResultatServiceReferentiel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFormuleResultatServiceReferentiel', array());

        return parent::getFormuleResultatServiceReferentiel();
    }

    /**
     * {@inheritDoc}
     */
    public function addFormuleResultatVolumeHoraire(\Application\Entity\Db\FormuleResultatVolumeHoraire $formuleResultatVolumeHoraire)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addFormuleResultatVolumeHoraire', array($formuleResultatVolumeHoraire));

        return parent::addFormuleResultatVolumeHoraire($formuleResultatVolumeHoraire);
    }

    /**
     * {@inheritDoc}
     */
    public function removeFormuleResultatVolumeHoraire(\Application\Entity\Db\FormuleResultatVolumeHoraire $formuleResultatVolumeHoraire)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeFormuleResultatVolumeHoraire', array($formuleResultatVolumeHoraire));

        return parent::removeFormuleResultatVolumeHoraire($formuleResultatVolumeHoraire);
    }

    /**
     * {@inheritDoc}
     */
    public function getFormuleResultatVolumeHoraire()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFormuleResultatVolumeHoraire', array());

        return parent::getFormuleResultatVolumeHoraire();
    }

    /**
     * {@inheritDoc}
     */
    public function addFormuleResultatVolumeHoraireReferentiel(\Application\Entity\Db\FormuleResultatVolumeHoraireReferentiel $formuleResultatVolumeHoraireReferentiel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addFormuleResultatVolumeHoraireReferentiel', array($formuleResultatVolumeHoraireReferentiel));

        return parent::addFormuleResultatVolumeHoraireReferentiel($formuleResultatVolumeHoraireReferentiel);
    }

    /**
     * {@inheritDoc}
     */
    public function removeFormuleResultatVolumeHoraireReferentiel(\Application\Entity\Db\FormuleResultatVolumeHoraireReferentiel $formuleResultatVolumeHoraireReferentiel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeFormuleResultatVolumeHoraireReferentiel', array($formuleResultatVolumeHoraireReferentiel));

        return parent::removeFormuleResultatVolumeHoraireReferentiel($formuleResultatVolumeHoraireReferentiel);
    }

    /**
     * {@inheritDoc}
     */
    public function getFormuleResultatVolumeHoraireReferentiel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFormuleResultatVolumeHoraireReferentiel', array());

        return parent::getFormuleResultatVolumeHoraireReferentiel();
    }

    /**
     * {@inheritDoc}
     */
    public function setIntervenant(\Application\Entity\Db\Intervenant $intervenant = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIntervenant', array($intervenant));

        return parent::setIntervenant($intervenant);
    }

    /**
     * {@inheritDoc}
     */
    public function getIntervenant()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIntervenant', array());

        return parent::getIntervenant();
    }

    /**
     * {@inheritDoc}
     */
    public function setAnnee(\Application\Entity\Db\Annee $annee = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnnee', array($annee));

        return parent::setAnnee($annee);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnnee()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnnee', array());

        return parent::getAnnee();
    }

    /**
     * {@inheritDoc}
     */
    public function setTypeVolumeHoraire(\Application\Entity\Db\TypeVolumeHoraire $typeVolumeHoraire = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTypeVolumeHoraire', array($typeVolumeHoraire));

        return parent::setTypeVolumeHoraire($typeVolumeHoraire);
    }

    /**
     * {@inheritDoc}
     */
    public function getTypeVolumeHoraire()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypeVolumeHoraire', array());

        return parent::getTypeVolumeHoraire();
    }

    /**
     * {@inheritDoc}
     */
    public function setEtatVolumeHoraire(\Application\Entity\Db\EtatVolumeHoraire $etatVolumeHoraire = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEtatVolumeHoraire', array($etatVolumeHoraire));

        return parent::setEtatVolumeHoraire($etatVolumeHoraire);
    }

    /**
     * {@inheritDoc}
     */
    public function getEtatVolumeHoraire()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEtatVolumeHoraire', array());

        return parent::getEtatVolumeHoraire();
    }

}
