<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Entity\Db;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class CompteBancaire extends \Application\Entity\Db\CompteBancaire implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'banqueBic', 'banqueId', 'branche', 'cleRib', 'compte', 'emplacement', 'guichet', 'histoCreation', 'histoDestruction', 'histoModification', 'iban2', 'iban3', 'iban4', 'iban5', 'iban6', 'iban7', 'ibanFin', 'ibanIso', 'paysIso', 'validiteDebut', 'validiteFin', 'id', 'intervenantExterieur', 'histoModificateur', 'histoDestructeur', 'histoCreateur');
        }

        return array('__isInitialized__', 'banqueBic', 'banqueId', 'branche', 'cleRib', 'compte', 'emplacement', 'guichet', 'histoCreation', 'histoDestruction', 'histoModification', 'iban2', 'iban3', 'iban4', 'iban5', 'iban6', 'iban7', 'ibanFin', 'ibanIso', 'paysIso', 'validiteDebut', 'validiteFin', 'id', 'intervenantExterieur', 'histoModificateur', 'histoDestructeur', 'histoCreateur');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (CompteBancaire $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setBanqueBic($banqueBic)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBanqueBic', array($banqueBic));

        return parent::setBanqueBic($banqueBic);
    }

    /**
     * {@inheritDoc}
     */
    public function getBanqueBic()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBanqueBic', array());

        return parent::getBanqueBic();
    }

    /**
     * {@inheritDoc}
     */
    public function setBanqueId($banqueId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBanqueId', array($banqueId));

        return parent::setBanqueId($banqueId);
    }

    /**
     * {@inheritDoc}
     */
    public function getBanqueId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBanqueId', array());

        return parent::getBanqueId();
    }

    /**
     * {@inheritDoc}
     */
    public function setBranche($branche)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBranche', array($branche));

        return parent::setBranche($branche);
    }

    /**
     * {@inheritDoc}
     */
    public function getBranche()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBranche', array());

        return parent::getBranche();
    }

    /**
     * {@inheritDoc}
     */
    public function setCleRib($cleRib)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCleRib', array($cleRib));

        return parent::setCleRib($cleRib);
    }

    /**
     * {@inheritDoc}
     */
    public function getCleRib()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCleRib', array());

        return parent::getCleRib();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompte($compte)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompte', array($compte));

        return parent::setCompte($compte);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompte()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompte', array());

        return parent::getCompte();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmplacement($emplacement)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmplacement', array($emplacement));

        return parent::setEmplacement($emplacement);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmplacement()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmplacement', array());

        return parent::getEmplacement();
    }

    /**
     * {@inheritDoc}
     */
    public function setGuichet($guichet)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGuichet', array($guichet));

        return parent::setGuichet($guichet);
    }

    /**
     * {@inheritDoc}
     */
    public function getGuichet()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGuichet', array());

        return parent::getGuichet();
    }

    /**
     * {@inheritDoc}
     */
    public function setHistoCreation($histoCreation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHistoCreation', array($histoCreation));

        return parent::setHistoCreation($histoCreation);
    }

    /**
     * {@inheritDoc}
     */
    public function getHistoCreation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHistoCreation', array());

        return parent::getHistoCreation();
    }

    /**
     * {@inheritDoc}
     */
    public function setHistoDestruction($histoDestruction)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHistoDestruction', array($histoDestruction));

        return parent::setHistoDestruction($histoDestruction);
    }

    /**
     * {@inheritDoc}
     */
    public function getHistoDestruction()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHistoDestruction', array());

        return parent::getHistoDestruction();
    }

    /**
     * {@inheritDoc}
     */
    public function setHistoModification($histoModification)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHistoModification', array($histoModification));

        return parent::setHistoModification($histoModification);
    }

    /**
     * {@inheritDoc}
     */
    public function getHistoModification()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHistoModification', array());

        return parent::getHistoModification();
    }

    /**
     * {@inheritDoc}
     */
    public function setIban2($iban2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIban2', array($iban2));

        return parent::setIban2($iban2);
    }

    /**
     * {@inheritDoc}
     */
    public function getIban2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIban2', array());

        return parent::getIban2();
    }

    /**
     * {@inheritDoc}
     */
    public function setIban3($iban3)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIban3', array($iban3));

        return parent::setIban3($iban3);
    }

    /**
     * {@inheritDoc}
     */
    public function getIban3()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIban3', array());

        return parent::getIban3();
    }

    /**
     * {@inheritDoc}
     */
    public function setIban4($iban4)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIban4', array($iban4));

        return parent::setIban4($iban4);
    }

    /**
     * {@inheritDoc}
     */
    public function getIban4()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIban4', array());

        return parent::getIban4();
    }

    /**
     * {@inheritDoc}
     */
    public function setIban5($iban5)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIban5', array($iban5));

        return parent::setIban5($iban5);
    }

    /**
     * {@inheritDoc}
     */
    public function getIban5()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIban5', array());

        return parent::getIban5();
    }

    /**
     * {@inheritDoc}
     */
    public function setIban6($iban6)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIban6', array($iban6));

        return parent::setIban6($iban6);
    }

    /**
     * {@inheritDoc}
     */
    public function getIban6()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIban6', array());

        return parent::getIban6();
    }

    /**
     * {@inheritDoc}
     */
    public function setIban7($iban7)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIban7', array($iban7));

        return parent::setIban7($iban7);
    }

    /**
     * {@inheritDoc}
     */
    public function getIban7()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIban7', array());

        return parent::getIban7();
    }

    /**
     * {@inheritDoc}
     */
    public function setIbanFin($ibanFin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIbanFin', array($ibanFin));

        return parent::setIbanFin($ibanFin);
    }

    /**
     * {@inheritDoc}
     */
    public function getIbanFin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIbanFin', array());

        return parent::getIbanFin();
    }

    /**
     * {@inheritDoc}
     */
    public function setIbanIso($ibanIso)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIbanIso', array($ibanIso));

        return parent::setIbanIso($ibanIso);
    }

    /**
     * {@inheritDoc}
     */
    public function getIbanIso()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIbanIso', array());

        return parent::getIbanIso();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaysIso($paysIso)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaysIso', array($paysIso));

        return parent::setPaysIso($paysIso);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaysIso()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaysIso', array());

        return parent::getPaysIso();
    }

    /**
     * {@inheritDoc}
     */
    public function setValiditeDebut($validiteDebut)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValiditeDebut', array($validiteDebut));

        return parent::setValiditeDebut($validiteDebut);
    }

    /**
     * {@inheritDoc}
     */
    public function getValiditeDebut()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValiditeDebut', array());

        return parent::getValiditeDebut();
    }

    /**
     * {@inheritDoc}
     */
    public function setValiditeFin($validiteFin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValiditeFin', array($validiteFin));

        return parent::setValiditeFin($validiteFin);
    }

    /**
     * {@inheritDoc}
     */
    public function getValiditeFin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValiditeFin', array());

        return parent::getValiditeFin();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setIntervenantExterieur(\Application\Entity\Db\IntervenantExterieur $intervenantExterieur = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIntervenantExterieur', array($intervenantExterieur));

        return parent::setIntervenantExterieur($intervenantExterieur);
    }

    /**
     * {@inheritDoc}
     */
    public function getIntervenantExterieur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIntervenantExterieur', array());

        return parent::getIntervenantExterieur();
    }

    /**
     * {@inheritDoc}
     */
    public function setHistoModificateur(\Application\Entity\Db\Utilisateur $histoModificateur = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHistoModificateur', array($histoModificateur));

        return parent::setHistoModificateur($histoModificateur);
    }

    /**
     * {@inheritDoc}
     */
    public function getHistoModificateur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHistoModificateur', array());

        return parent::getHistoModificateur();
    }

    /**
     * {@inheritDoc}
     */
    public function setHistoDestructeur(\Application\Entity\Db\Utilisateur $histoDestructeur = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHistoDestructeur', array($histoDestructeur));

        return parent::setHistoDestructeur($histoDestructeur);
    }

    /**
     * {@inheritDoc}
     */
    public function getHistoDestructeur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHistoDestructeur', array());

        return parent::getHistoDestructeur();
    }

    /**
     * {@inheritDoc}
     */
    public function setHistoCreateur(\Application\Entity\Db\Utilisateur $histoCreateur = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHistoCreateur', array($histoCreateur));

        return parent::setHistoCreateur($histoCreateur);
    }

    /**
     * {@inheritDoc}
     */
    public function getHistoCreateur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHistoCreateur', array());

        return parent::getHistoCreateur();
    }

}
