<div class="panel panel-default">
    <div class="panel-heading">Configuration de la prise en charge</div>
    <div class="panel-body">
        <p>Veuillez paramétrer la prise en charge de l'agent : </p>
        <table class="table">
            <thead>
            <tr>
                <th>Paramètres</th>
                <th>Choix</th>

            </tr>
            </thead>
            <tbody>
            <tr>
                <td><?= $this->formLabel($connecteurFieldset->get('anneeUniversitaire')) ?> :</td>
                <td><?= $this->formSelect($connecteurFieldset->get('anneeUniversitaire')); ?></td>
            </tr>
            <tr>
                <td><?= $this->formLabel($connecteurFieldset->get('emploi')) ?> :</td>
                <td><?= $this->formSelect($connecteurFieldset->get('emploi')); ?></td>
            </tr>

            <tr>
                <td><?= $this->formLabel($connecteurFieldset->get('affectation')) ?> :</td>
                <td><?= $this->formSelect($connecteurFieldset->get('affectation')); ?></td>
            </tr>
            <tr>
                <td><?= $this->formLabel($connecteurFieldset->get('position')) ?> :</td>
                <td><?= $this->formSelect($connecteurFieldset->get('position')); ?></td>
            </tr>
            <tr>
                <td><?= $this->formLabel($connecteurFieldset->get('statut')) ?> :</td>
                <td><?= $this->formSelect($connecteurFieldset->get('statut')); ?></td>
            </tr>
            <tr>
                <td><?= $this->formLabel($connecteurFieldset->get('modaliteService')) ?> :</td>
                <td><?= $this->formSelect($connecteurFieldset->get('modaliteService')); ?></td>
            </tr>


            </tbody>
        </table>

    </div>
</div>