<?php
/**
 * @var \ExportRh\Entity\IntervenantRh        $intervenantRh
 * @var \Dossier\Entity\Db\IntervenantDossier $intervenantDossier
 */

?>

<div class="card bg-default">
    <div class="card-header">Récapitulatif des données personnelles synchronisables pour un renouvellement</div>
    <div class="card-body">

        <table class="table">
            <thead>
            <tr>
                <th>Champs</th>
                <th>OSE</th>
                <th><?= $nameConnecteur ?></th>

            </tr>
            </thead>
            <tbody>
            <tr>
                <td>
                    <?= $this->formCheckbox($generiqueFieldset->get('adressePrincipale')); ?>
                    <?= $this->formLabel($generiqueFieldset->get('adressePrincipale')) ?> :
                </td>
                <td>
                    <?php
                    $adresse = '';
                    $adresse = (!empty($intervenantDossier->getAdresseLieuDit())) ? $intervenantDossier->getAdresseLieuDit() . '<br/>' : '';
                    $adresse .= (!empty($intervenantDossier->getAdresseNumero())) ? $intervenantDossier->getAdresseNumero() . ' ' : '';
                    $adresse .= (!empty($intervenantDossier->getAdresseNumeroCompl())) ? $intervenantDossier->getAdresseNumeroCompl() . ' ' : '';
                    $adresse .= (!empty($intervenantDossier->getAdresseVoirie()) && !empty(trim((string)$intervenantDossier->getAdresseVoie()))) ? strtoupper($intervenantDossier->getAdresseVoirie()) . ' ' : '';
                    $adresse .= (!empty($intervenantDossier->getAdresseVoie())) ? $intervenantDossier->getAdresseVoie() . '<br/>' : '';
                    $adresse .= (!empty($intervenantDossier->getAdressePrecisions())) ? $intervenantDossier->getAdressePrecisions() . '<br/>' : '';
                    $adresse .= $intervenantDossier->getAdresseCodePostal() . ' ' . $intervenantDossier->getAdresseCommune();
                    echo $adresse;
                    ?>
                </td>
                <td class="active">
                    <?php
                    if (!empty($intervenantRh)) {
                        $adresse = '';
                        $adresse .= (!empty(trim((string)$intervenantRh->getAdresseNumero()))) ? $intervenantRh->getAdresseNumero() . ' ' : '';
                        $adresse .= (!empty(trim((string)$intervenantRh->getAdresseNumeroCompl()))) ? $intervenantRh->getAdresseNumeroCompl() . ' ' : '';
                        $adresse .= (!empty(trim((string)$intervenantRh->getAdresseVoirie())) && !empty(trim((string)$intervenantRh->getAdresseVoie()))) ? strtoupper($intervenantRh->getAdresseVoirie()) . ' ' : '';
                        $adresse .= (!empty(trim((string)$intervenantRh->getAdresseVoie()))) ? $intervenantRh->getAdresseVoie() . '<br/>' : '';
                        $adresse .= (!empty(trim((string)$intervenantRh->getAdressePrecisions()))) ? $intervenantRh->getAdressePrecisions() . '<br/>' : '';
                        $adresse .= $intervenantRh->getAdresseCodePostal() . ' ' . $intervenantRh->getAdresseCommune();
                        echo $adresse;
                    }
                    ?>
                </td>
            </tr>
            <tr>
                <td>
                    <?= $this->formCheckbox($generiqueFieldset->get('telPro')); ?>
                    <?= $this->formLabel($generiqueFieldset->get('telPro')) ?> :
                </td>
                <td><?= $intervenantDossier->getTelPro() ?></td>
                <td class="active"><?= (!empty($intervenantRh)) ? $intervenantRh->getTelPro() : '' ?></td>
            </tr>
            <tr>
                <td>
                    <?= $this->formCheckbox($generiqueFieldset->get('telPerso')); ?>
                    <?= $this->formLabel($generiqueFieldset->get('telPerso')) ?> :
                </td>
                <td><?= $intervenantDossier->getTelPerso() ?></td>
                <td class="active"><?= (!empty($intervenantRh)) ? $intervenantRh->getTelPerso() : '' ?></td>
            </tr>
            <tr>
                <td>
                    <?= $this->formCheckbox($generiqueFieldset->get('emailPro')); ?>
                    <?= $this->formLabel($generiqueFieldset->get('emailPro')) ?> :
                </td>
                <td><?= $intervenantDossier->getEmailPro() ?></td>
                <td class="active"><?= (!empty($intervenantRh)) ? $intervenantRh->getEmailPro() : '' ?></td>
            </tr>
            <tr>
                <td>
                    <?= $this->formCheckbox($generiqueFieldset->get('emailPerso')); ?>
                    <?= $this->formLabel($generiqueFieldset->get('emailPerso')) ?> :
                </td>
                <td><?= $intervenantDossier->getEmailPerso() ?></td>
                <td class="active"><?= (!empty($intervenantRh)) ? $intervenantRh->getEmailPerso() : '' ?></td>
            </tr>

            <tr>
                <td>
                    <input name="generiqueFieldset[iban]" type="checkbox" checked="checked">
                    <label>IBAN:</label>
                </td>
                <td>
                    <?= $intervenantDossier->getIBAN() ?>
                    <?php if ($intervenantRh->getIBAN() != $intervenantDossier->getIBAN()): ?>
                        <i class="fas fa-triangle-exclamation" style="color:#a40000;"></i>
                    <?php endif; ?>
                </td>
                <td class="active">
                    <?= (!empty($intervenantRh)) ? $intervenantRh->getIBAN() : '' ?>
                </td>
            </tr>
            <tr>
                <td>
                    <input name="generiqueFieldset[bic]" type="checkbox" checked="checked">
                    <label>BIC:</label>

                </td>
                <td>
                    <?= $intervenantDossier->getBIC() ?>
                    <?php if ($intervenantRh->getBIC() != $intervenantDossier->getBIC()): ?>
                        <!-- <i class="fas fa-triangle-exclamation" style="color:#a40000;"></i>-->
                    <?php endif; ?>
                </td>
                <td class="active">
                    <?= (!empty($intervenantRh)) ? $intervenantRh->getBIC() : '' ?>
                </td>
            </tr>
            <tr>
                <td>
                    <input name="generiqueFieldset[situationMatrimoniale]" type="checkbox" checked="checked" disabled>
                    <?= $this->formLabel($generiqueFieldset->get('situationMatrimoniale')) ?> :
                </td>
                <td>
                    <?= ($intervenantDossier->getSituationMatrimoniale()) ? $intervenantDossier->getSituationMatrimoniale()->getLibelle() : 'Non renseigné'; ?>
                    <?php if ($intervenantRh->getSituationMatrimoniale() != $intervenantDossier->getSituationMatrimoniale()): ?>
                        <i class="fas fa-triangle-exclamation" style="color:#a40000;"></i>
                    <?php endif; ?>
                </td>
                <?php if (!empty($intervenantRh)): ?>
                    <td class="active"><?= ($intervenantRh->getSituationMatrimoniale()) ? $intervenantRh->getSituationMatrimoniale()->getLibelle() : 'Non renseigné' ?></td>
                <?php else: ?>
                    <td class="active">Non renseigné</td>
                <?php endif; ?>
            </tr>
            </tbody>
        </table>
        <p>
            <?php if ($intervenantRh->getSituationMatrimoniale() != $intervenantDossier->getSituationMatrimoniale()): ?>
                <i class="fas fa-triangle-exclamation" style="color:#a40000;"></i> <i
                        style="font-style: italic;color:#555753">&nbsp;Attention, la situation matrimoniale de l'agent a changé, le renouvellement SIHAM
                    ne met pas à jour cette information, pensez à le faire manuellement dans SIHAM.</i>
            <?php endif; ?>
        </p>

    </div>
</div>