<div class="jumbotron">
    <h1>Choisir une structure</h1>
</div>

<style>
    span.sas-highlight { font-weight: bold; }
</style>

<?php $form->prepare(); ?>

<?= $this->form()->openTag($form) ?>
<?= $this->formControlGroup($form->get('structure')); ?>
<input class="btn btn-primary" type="submit" value="Choisir" name="submit">
<?= $this->form()->closeTag() ?>

<script>
    $(function() {
        $(":input").tooltip({ /*placement: 'left'*/ });
    });
</script>