<?php
/**
 * @var $this \Application\View\Renderer\PhpRenderer
 * @var $structures \Application\Entity\Db\Structure[]
 */

use Application\Provider\Privilege\Privileges;
use UnicaenApp\Util;

function affBooleen($flg)
{
    // affiche booléen avec des glypheIcon
    return ($flg ? '<span class="glyphicon glyphicon-ok text-success"></span>' : '<span class="glyphicon glyphicon-remove text-danger refuse"></span>');
}

$this->headTitle()->append("STRUCTUREs");

$canEdit = $this->isAllowed(Privileges::getResourceId(Privileges::STRUCTURES_ADMINISTRATION_EDITION));

?>
    <h1 class="page-header">STRUCTUREs</h1>

    <table class="table table-bordered table-sort">
        <thead>
                    <th style="word-wrap: break-word ; ">Code</th>
                    <th style="word-wrap: break-word ; ">Libelle Court</th>
                    <th style="word-wrap: break-word ; ">Libelle Long</th>
                    <th style="word-wrap: break-word ; ">Enseignement</th>
                    <th style="word-wrap: break-word ; ">Source</th>
                    <th style="word-wrap: break-word ; ">Source Code</th>
                    <th style="word-wrap: break-word ; ">Plafond Referentiel</th>
                    <th style="word-wrap: break-word ; ">Aff Adresse Contrat</th>
<?php if ($canEdit) echo '<th>Actions</th>' ?>
        </thead>
        <tbody>
        <?php foreach ($structures as $fr): ?>
            <tr>
                     <td style="word-wrap: break-word ; "><?= $fr->getCode() ?></td>
                     <td style="word-wrap: break-word ; "><?= $fr->getLibelleCourt() ?></td>
                     <td style="word-wrap: break-word ; "><?= $fr->getLibelleLong() ?></td>
                     <td style="word-wrap: break-word ; "><?= affBooleen($fr->isEnseignement()) ?></td>
                     <td style="word-wrap: break-word ; "><?= $fr->getSource() ?></td>
                     <td style="word-wrap: break-word ; "><?= $fr->getSourceCode() ?></td>
                     <td style="word-wrap: break-word ; "><?= ($fr->getPlafondReferentiel()) ? Util::formattedNumber($fr->getPlafondReferentiel()) :'' ?></td>
                     <td style="word-wrap: break-word ; "><?= affBooleen($fr->isAffAdresseContrat()) ?></td>
                    <?php if ($canEdit) { ?>
                    <td style="text-align:center;width:1px;white-space: nowrap">
                        <a class="ajax-modal" data-event="structure-saisie"
                           href="<?= $this->url('structure/saisie', ['structure' => $fr->getId()]) ?>"
                           title="Modifier la Structure">
                            <span class="glyphicon glyphicon-edit"></span></a>
                        <a class="pop-ajax"
                           href="<?= $this->url('structure/delete', ['structure' => $fr->getId()]) ?>"
                           title="Supprimer la Structure"
                           data-content="<p class='lead text-danger'><strong>Attention!</strong> Confirmez-vous cette suppression ?</p>"
                           data-confirm="true"
                           data-confirm-button="Oui"
                           data-cancel-button="Non"
                           data-submit-reload="true"
                        >
                            <span class="glyphicon glyphicon-remove"></span>
                        </a>
                    </td>
                <?php } ?>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
    <?php if ($canEdit): ?>
    <a class="btn btn-primary ajax-modal" data-event="structure-saisie"
       href="<?= $this->url('structure/saisie') ?>"
       title="Ajouter une STRUCTURE">
        <span class="glyphicon glyphicon-edit"></span>
        Ajouter une STRUCTURE</a>

    <script type="text/javascript">
        $(function () {
            $("body").on("structure-saisie", function (event, data) {
                window.location.reload();
            });
        });
    </script>
<?php endif ?>

