<?php
/**
 * @var $this       \Application\View\Renderer\PhpRenderer
 * @var $structures \Application\Entity\Db\Structure[]
 */

use Application\Provider\Privilege\Privileges;
use UnicaenApp\Util;

function affBooleen($flg)
{
    // affiche booléen avec des glypheIcon
    return ($flg ? '<i class="fa fa-check text-succes"></i>' : '<i class="fa fa-times text-danger refuse"></i>');
}

$this->headTitle()->append("Structures");

$globalCanEdit = $this->isAllowed(Privileges::getResourceId(Privileges::STRUCTURES_ADMINISTRATION_EDITION));

?>
<h1 class="page-header">Structures</h1>

<table class="table table-bordered table-sort">
    <thead>
    <th style="word-wrap: break-word ; ">Code</th>
    <th style="word-wrap: break-word ; ">Libelle Court</th>
    <th style="word-wrap: break-word ; ">Libelle Long</th>
    <th style="word-wrap: break-word ; ">Enseignement</th>
    <th style="word-wrap: break-word ; ">Aff. adresse sur contrat</th>
    <th style="word-wrap: break-word ; ">Source</th>
    <?php if ($globalCanEdit) echo '<th>Actions</th>' ?>
    </thead>
    <tbody>
    <?php foreach ($structures as $structure):
        $canEdit = $this->isAllowed($structure, Privileges::STRUCTURES_ADMINISTRATION_EDITION);
        $canDelete = $canEdit && !$structure->getSource()->getImportable() ?>
        <tr>
            <td style="word-wrap: break-word ; "><?= $structure->getCode() ?></td>
            <td style="word-wrap: break-word ; "><?= $structure->getLibelleCourt() ?></td>
            <td style="word-wrap: break-word ; "><?= $structure->getLibelleLong() ?></td>
            <td style="word-wrap: break-word ; "><?= affBooleen($structure->isEnseignement()) ?></td>
            <td style="word-wrap: break-word ; "><?= affBooleen($structure->isAffAdresseContrat()) ?></td>
            <td style="word-wrap: break-word ; "><?= $structure->getSource() . ($structure->getSource()->getImportable() ? ' (' . $structure->getSourceCode() . ')' : '') ?></td>
            <?php if ($canEdit): ?>
                <td style="text-align:center;width:1px;white-space: nowrap">
                    <?php if ($canEdit): ?>
                        <a class="ajax-modal" data-event="structure-saisie"
                           href="<?= $this->url('structure/voir', ['structure' => $structure->getId()], ['query' => ['tab' => 'edition']]) ?>"
                           title="Modifier la Structure">
                            <i class="fa fa-edit"></i></a>
                    <?php endif; ?>
                    <?php if ($canDelete): ?>
                        <a class="pop-ajax"
                           href="<?= $this->url('structure/delete', ['structure' => $structure->getId()]) ?>"
                           title="Supprimer la Structure"
                           data-content="<p class='lead text-danger'><strong>Attention!</strong> Confirmez-vous cette suppression ?</p>"
                           data-confirm="true"
                           data-confirm-button="Oui"
                           data-cancel-button="Non"
                           data-submit-reload="true"
                        >
                            <i class="fa fa-times"></i>
                        </a>
                    <?php endif; ?>
                </td>
            <?php elseif ($globalCanEdit): ?>
                <td>&nbsp;</td>
            <?php endif; ?>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<?php if ($globalCanEdit): ?>
    <a class="btn btn-primary ajax-modal" data-event="structure-saisie"
       href="<?= $this->url('structure/saisie') ?>"
       title="Ajouter une structure">
        <i class="fa fa-edit"></i>
        Ajouter une structure</a>

    <script type="text/javascript">
        $(function () {
            $("body").on("structure-saisie", function (event, data) {
                window.location.reload();
            });
        });
    </script>
<?php endif ?>

