<?php
/**
 * @var $this  \Application\View\Renderer\PhpRenderer
 * @var $form  \Application\Form\Structure\StructureSaisieForm
 */

echo $this->messenger()->addCurrentMessagesFromFlashMessenger();
echo $this->form()->openTag($form); ?>

<div class="row">
    <div class="col-md-3">
        <?= $this->formControlGroup($form->get('code')) ?>
    </div>
    <div class="col-md-9">
        <?= $this->formControlGroup($form->get('libelle-court')) ?>
    </div>
</div>
<div class="row">
    <div class="col-md-9">
        <?= $this->formControlGroup($form->get('libelle-long')) ?>
    </div>
</div>
<div class="row">
    <div class="col-md-3">
        <?= $this->formControlGroup($form->get('enseignement')) ?>
    </div>
    <div class="col-md-6">
        <?= $this->formControlGroup($form->get('source')) ?>
    </div>
    <div class="col-md-3">
        <?= $this->formControlGroup($form->get('source-code')); ?>
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <?= $this->formControlGroup($form->get('aff-adresse-contrat')) ?>
    </div>
    <div class="col-md-6">
        <?= $this->formControlGroup($form->get('plafond-referentiel')) ?>
    </div>
</div>

<?php
echo $this->formSubmit($form->get('submit'));
echo $this->formControlGroup($form->get('security'));
echo $this->form()->closeTag();
?>
