<?php

/**
 * @var $this \Application\View\Renderer\PhpRenderer
 */

$form->prepare();

echo $this->form()->openTag($form);
echo $this->formControlGroup( $form->get('heures') );
if ($form->has('motif-non-paiement')) {
    echo $this->formControlGroup( $form->get('motif-non-paiement') );

    $ancienMotifNonPaiementElement = new \Zend\Form\Element\Hidden('ancien-motif-non-paiement');
    $ancienMotifNonPaiementElement->setValue($ancienMotifNonPaiement ? $ancienMotifNonPaiement->getId() : null);
    echo $this->formHidden($ancienMotifNonPaiementElement);
}
echo '<hr /><div style="text-align:right">';
echo $this->formRow($form->get('submit'));
echo ' ';
echo $this->formRow($form->get('annuler'));
echo '</div>';
echo $this->formHidden($form->get('type-volume-horaire'));
echo $this->formHidden($form->get('periode'));
echo $this->formHidden($form->get('type-intervention'));
echo $this->formHidden($form->get('service'));
echo $this->form()->closeTag();

echo $this->formErrors( $form );
echo $this->messenger()->addCurrentMessagesFromFlashMessenger();