<?php

namespace Application\Service;

use Application\Entity\Db\Dossier;
use Application\Entity\Db\Intervenant as IntervenantEntity;
use Application\Entity\Db\Structure as StructureEntity;
use Application\Entity\Db\TypeValidation as TypeValidationEntity;
use Application\Entity\Db\Validation as ValidationEntity;
use Application\Entity\Db\TypeVolumeHoraire as TypeVolumeHoraireEntity;
use RuntimeException;
use Doctrine\ORM\QueryBuilder;


/**
 * Description of Validation
 *
 * @author Bertrand GAUTHIER <bertrand.gauthier at unicaen.fr>
 */
class Validation extends AbstractEntityService
{
    use Traits\TypeValidationAwareTrait;
    use Traits\TypeVolumeHoraireAwareTrait;



    /**
     * retourne la classe des entités
     *
     * @return string
     * @throws RuntimeException
     */
    public function getEntityClass()
    {
        return ValidationEntity::class;
    }



    /**
     * Retourne l'alias d'entité courante
     *
     * @return string
     */
    public function getAlias()
    {
        return 'v';
    }



    public function validerDossier(Dossier $dossier)
    {
        $typeDonneesPerso = $this->getServiceTypeValidation()->getByCode(TypeValidationEntity::CODE_DONNEES_PERSO);

        $validation = $this->newEntity();
        $validation->setIntervenant($dossier->getIntervenant());
        $validation->setTypeValidation($typeDonneesPerso);
        $validation->setStructure($dossier->getIntervenant()->getStructure());

        return $this->save($validation);
    }



    /**
     *
     * @param IntervenantEntity            $intervenant
     * @param TypeVolumeHoraireEntity|null $tvh
     *
     * @return ValidationEntity|null
     */
    public function getValidationClotureServices(IntervenantEntity $intervenant)
    {
        $tv = $this->getServiceTypeValidation()->getByCode(TypeValidationEntity::CODE_CLOTURE_REALISE);

        $validation = $this->getRepo()->findOneBy([
            'typeValidation' => $tv,
            'intervenant'    => $intervenant,
        ]);

        if (!$validation){
            $role = $this->getServiceContext()->getSelectedIdentityRole();

            $validation = $this->newEntity($tv);
            $validation->setIntervenant($intervenant);
            $validation->setStructure($role->getStructure() ?: $intervenant->getStructure());
        }

        return $validation;
    }



    /**
     * Supprime (historise par défaut) le service spécifié.
     *
     * @param ValidationEntity $entity Entité à détruire
     * @param bool             $softDelete
     *
     * @return self
     */
    public function delete($entity, $softDelete = true)
    {
        /* On détriut d'abord les dépendances possibles ... */
        foreach ($entity->getVolumeHoraire() as $vh) {
            $entity->removeVolumeHoraire($vh);
        }

        foreach ($entity->getVolumeHoraireReferentiel() as $vh) {
            $entity->removeVolumeHoraireReferentiel($vh);
        }

        return parent::delete($entity, $softDelete); // TODO: Change the autogenerated stub
    }



    /**
     * Retourne une nouvelle entité de la classe donnée
     *
     * @param TypeValidation|string $type
     *
     * @return \Application\Entity\Db\Validation
     */
    public function newEntity($type = null)
    {
        $entity = parent::newEntity();
        $entity->setTypeValidation($type);

        return $entity;
    }



    /**
     * Recherche par type
     *
     * @param TypeValidation|string $type
     * @param QueryBuilder|null     $qb
     *
     * @return QueryBuilder
     */
    public function finderByType($type, QueryBuilder $qb = null, $alias = null)
    {
        list($qb, $alias) = $this->initQuery($qb, $alias);

        if (is_string($type)) {
            $type = $this->getServiceTypeValidation()->getByCode($type);
        }

        $qb
            ->join("$alias.typeValidation", 'tv')
            ->andWhere("tv = :tv")
            ->setParameter('tv', $type);

        return $qb;
    }



    /**
     * @param TypeValidationEntity $typeValidation
     * @param IntervenantEntity    $intervenant
     * @param StructureEntity|null $structure
     *
     * @return array
     */
    public function lister(TypeValidationEntity $typeValidation, IntervenantEntity $intervenant, StructureEntity $structure = null)
    {
        $dql = "
        SELECT
          v
        FROM
          Application\Entity\Db\Validation v
        WHERE
          v.intervenant = :intervenant
          AND v.typeValidation = :typeValidation
          " . ($structure ? 'AND v.structure = :structure' : '') . "
        ORDER BY
          v.histoCreation
        ";

        $params = compact(
            'intervenant', 'typeValidation'
        );
        if ($structure) {
            $params['structure'] = $structure;
        }
        $res         = $this->getEntityManager()->createQuery($dql)->setParameters($params)->getResult();
        $validations = [];
        foreach ($res as $v) {
            $validations[$v->getId()] = $v;
        }

        return $validations;
    }
}