<?php

/* @var $container Zend\Navigation\Navigation */
// On récupère le container en-dessous du 'home'

?>
<dl>
<?php
foreach ($container as $page){
    if ($this->navigation()->accept($page)) {
        //$color = $page->get('border-color') ? 'style="border-left-color:' . $page->get('border-color') . '"' : '';
        //$icon  = $page->get('icon') ? sprintf('<span class="%s"></span>', $page->get('icon')) : '';
        echo '<dt>'.$this->navigation()->htmlify($page).'</dt>';
        echo '<dd>'.$page->get('description').'</dd>';
    }
}
?>
</dl>
<style>

    dt{
        padding-top:2em;
    }

</style>