<?php

/**
 * @var $this      \Application\View\Renderer\PhpRenderer
 * @var $container Zend\Navigation\Navigation
 */

?>
<dl>
    <?php
    foreach ($container as $page) {
        if ($this->navigation()->accept($page)) {
            echo $this->tag('dt')->html( $this->navigation()->htmlify($page) );
            echo $this->tag('dd')->text( $page->get('description') );
        }
    }
    ?>
</dl>
<style>

    dt {
        padding-top: 2em;
    }

</style>