<?php

use UnicaenApp\View\Helper\TagViewHelper;
use Laminas\Navigation\Page\Mvc;

/**
 * @var $container Laminas\Navigation\Navigation
 * @var $this      \Application\View\Renderer\PhpRenderer
 */

echo $this->tag('div', ['class' => 'callout-menu']);
foreach ($container as $page) {
    if ($this->navigation()->accept($page)) {
        $attrs = [
            'class' => 'callout-container',
        ];
        if ($borderColor = $page->get('color')) {
            $attrs['style'] = 'background-color:' . $borderColor;
        }
        if ($description = $page->get('description')) {
            $attrs['title'] = $description;
        }

        echo $this->tag('div', $attrs);
        echo $this->tag('div', ['class' => 'callout']);
        if ($icon = $page->get('icon')) {
            echo $this->tag('span', ['class' => $icon])->open(TagViewHelper::AUTOCLOSE_FULL);
        }
        echo $this->tag('h1')->html($this->navigation()->htmlify($page));

        if ($page->hasPages()) {
            echo '<ul>';
            $children = (array)$page->getPages();
            uasort($children, function (Mvc $a, Mvc $b) {
                return $a->getOrder() > $b->getOrder() ? 1 : 0;
            });
            foreach ($children as $child) {
                if ($this->navigation()->accept($child)) {
                    echo $this->tag('li')->html(/*$child->getOrder() . ' ' .*/ $this->navigation()->htmlify($child));
                }
            }
            echo '</ul>';
        }
        echo '</div>';
        echo '</div>';
    }
}
echo '<div style="clear: both"></div>';
echo '</div>';


