<?php

use UnicaenApp\View\Helper\TagViewHelper;
use Laminas\Navigation\Page\Mvc;

/**
 * @var $container Laminas\Navigation\Navigation
 * @var $this      \Application\View\Renderer\PhpRenderer
 */

$rubriques = [];


foreach ($container as $page) {
    if ($this->navigation()->accept($page)) {
        $rubrique = [
            'color'       => $page->get('color'),
            'description' => $page->get('description'),
            'icon'        => $page->get('icon'),
            'html'        => $this->navigation()->htmlify($page),
            'items'       => [],
        ];

        if ($page->hasPages()) {
            $children = (array)$page->getPages();
            uasort($children, function (Mvc $a, Mvc $b) {
                return $a->getOrder() > $b->getOrder() ? 1 : 0;
            });
            foreach ($children as $child) {
                if ($this->navigation()->accept($child)) {
                    $rubrique['items'][] = $this->navigation()->htmlify($child);
                }
            }
        }

        $rubriques[] = $rubrique;
    }
}


//var_dump($rubriques);


echo $this->tag('div', ['class' => 'callout-menu']);
$i = 0;
foreach ($rubriques as $rubrique) {
    if (!empty($rubrique['items'])) {
        $attrs = [
            'class' => 'callout-container',
        ];
        if ($borderColor = $rubrique['color']) {
            $attrs['style'] = 'background-color:' . $borderColor;
        }
        if ($description = $rubrique['description']) {
            $attrs['title'] = $description;
        }

        if ($i % 2 != 1) {
            echo '<div style="clear: both"></div>';
        }

        echo $this->tag('div', $attrs);
        echo $this->tag('div', ['class' => 'callout']);
        if ($icon = $rubrique['icon']) {
            echo $this->tag('span', ['class' => $icon])->open(TagViewHelper::AUTOCLOSE_FULL);
        }
        echo $this->tag('h1')->html($rubrique['html']);
        echo '<ul>';
        foreach ($rubrique['items'] as $item) {
            echo $this->tag('li')->html($item);
        }
        echo '</ul>';
        echo '</div>';
        echo '</div>';
    }
    $i++;
}
echo '<div style="clear: both"></div>';
echo '</div>';