<?php

use Intervenant\Entity\Db\Statut;
use PieceJointe\Entity\Db\TypePieceJointe;
use PieceJointe\Entity\Db\TypePieceJointeStatut;

/**
 * @var $this                \Application\View\Renderer\PhpRenderer
 * @var $canEdit             boolean
 * @var $typePieceJointe     TypePieceJointe
 * @var $statut              Statut
 * @var $tpjss               TypePieceJointeStatut[]
 * @var $i                   int
 * @var $j                   int
 */

echo $this->tag('td', [
    'onmouseover' => 'sourisHover(' . $i . ',' . $j . ')',
    'class'       => empty($tpjss) ? 'notpjs' : 'tpjs',
])->open();

if (empty($tpjss)) {
    $title = 'Pas de pièce justificative demandée';
    $text  = '-';

    if ($canEdit) {
        echo $this->tag('a', [
            'class'      => 'ajax-modal',
            'data-event' => 'event-update-tpjs',
            'href'       => $this->url('piece-jointe/modifier-type-piece-jointe-statut', ['typePieceJointe' => $typePieceJointe->getId(), 'statut' => $statut->getId()]),
            'title'      => $title,
        ])->text($text);
    } else {
        echo $this->tag('span', [
            'title' => $title,
        ])->text($text);
    }
} else {
    $first = true;
    foreach ($tpjss as $tpjs) {
        if (!$first) {
            echo ' <span class="pj-ou">ou</span> ';
        }
        if ($canEdit) {
            echo $this->tag('a', [
                'class'      => 'ajax-modal',
                'data-event' => 'event-update-tpjs',
                'href'       => $this->url('piece-jointe/modifier-type-piece-jointe-statut', ['typePieceJointe' => $typePieceJointe->getId(), 'statut' => $statut->getId(), 'typePieceJointeStatut' => $tpjs->getId()]),
                'title'      => $tpjs->getTitle(),
            ])->text($tpjs);
        } else {
            echo $this->tag('span', [
                'title' => $tpjs->getTitle(),
            ])->text($tpjs);
        }
        $first = false;
    }
}

echo $this->tag('td')->close();