<?php
/**
 * Liste des services toute simple.
 *
 * Inclue le total des heures par enseignement et le total global.
 */

$totalHeures = 0.0;
?>

<style>
    th.heures, td.heures {
        text-align: right;
    }

    td.heures-total {
        font-weight: bold;
    }

    .modal-dialog {
        width: 70%;
    }

    div.row {
        padding: 1px;
    }

    th.heures, td.heures {
        width: 3em !important;
    }
</style>
<table class="table table-bordered table-hover table-sm">
    <thead>
    <tr>
        <th style="width:20%">Composante</th>
        <th style="width:10%">Code</th>
        <th style="width:60%">Libellé enseignement</th>
        <th style="width:10%">Total des heures</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($this->services as $service): /* @var $service \Enseignement\Entity\Db\Service */ ?>
        <?php
        $heures      = $service->getVolumeHoraireListe()->getHeures();
        $totalHeures += $heures;
        ?>
        <tr>
            <td><?= $service->getElementPedagogique() ? $service->getElementPedagogique()->getStructure() : null ?></td>
            <td><?= $service->getElementPedagogique()->getSourceCode() ?></td>
            <td><?= $service->getElementPedagogique()->getLibelle() ?></td>
            <td class="heures">
                <?= \UnicaenApp\Util::formattedFloat($heures, \NumberFormatter::DECIMAL, 2) ?>
            </td>
        </tr>
    <?php endforeach ?>
    </tbody>
    <tfoot>
    <tr>
        <td></td>
        <td></td>
        <td class="heures heures-total">Total :</td>
        <td class="heures heures-total">
            <?= \UnicaenApp\Util::formattedFloat($totalHeures, \NumberFormatter::DECIMAL, 2) ?>
        </td>
    </tr>
    </tfoot>
</table>