version: '3'

# Ne pas oublier d'ajouter au fichier /etc/hosts :
# 172.21.0.10 ose-dev.pc-local
# 172.21.0.15 ose-test.pc-local

services:
  ose-dev:
    container_name: ose-dev

    environment:
      APPLICATION_ENV: dev
      APPLICATION_HOSTNAME: ose-dev.pc-local
      XDEBUG_CONFIG: "remote_host=172.21.0.10"
      PHP_IDE_CONFIG: "serverName=ose-dev.pc-local"

    build:
      context: .
      dockerfile: Dockerfile
      args:
        PHP_VERSION: 8.0
        APPLICATION_ENV: dev

    volumes:
      - .:/app

    working_dir: /app

    extra_hosts:
      - "host.docker.internal:host-gateway"

    networks:
      devnet:
        ipv4_address: 172.21.0.10



  ose-test:
    container_name: ose-test

    environment:
      APPLICATION_ENV: test
      APPLICATION_HOSTNAME: ose-test.pc-local
      XDEBUG_CONFIG: "remote_host=172.21.0.15"
      PHP_IDE_CONFIG: "serverName=ose-test.pc-local"

    build:
      context: .
      dockerfile: Dockerfile
      args:
        PHP_VERSION: 8.0
        APPLICATION_ENV: test

    volumes:
      - .:/app

    working_dir: /app

    extra_hosts:
      - "host.docker.internal:host-gateway"

    networks:
      devnet:
        ipv4_address: 172.21.0.15



networks:
  devnet:
    external:
      name: laures
