version: '3'

# Ne pas oublier d'ajouter au fichier /etc/hosts :
# 172.21.0.10 ose-dev.pc-local

services:
  ose-dev:
    container_name: ose-dev

    environment:
      XDEBUG_CONFIG: remote_host=172.17.0.1
      PHP_IDE_CONFIG: serverName=ose-dev.pc-local
      APPLICATION_HOSTNAME: ose-dev.pc-local
      APPLICATION_ENV: dev

    build:
      context: .
      dockerfile: Dockerfile
      args:
        PHP_VERSION: 8.0

    volumes:
        - .:/app

    working_dir: /app

    networks:
        devnet:
            ipv4_address: 172.21.0.10

networks:
  devnet:
    external:
        name: laures
