version: '3'

# Ne pas oublier d'ajouter au fichier /etc/hosts :
# 172.25.0.101 ose-dev.localhost

services:
  ose-dev:
    container_name: ose-dev

    build:
      context: .
      dockerfile: Dockerfile

    volumes:
        - .:/var/www/ose

    working_dir: /var/www/ose

    networks:
        launet:
            ipv4_address: 172.25.0.101

networks:
  launet:
    driver: bridge
    ipam:
      config:
      - subnet: 172.25.0.0/24
