version: '3'

# Ne pas oublier d'ajouter au fichier /etc/hosts :
# 172.21.0.10 ose-dev.localhost

services:
  ose-dev:
    container_name: ose-dev

    environment:
      XDEBUG_CONFIG: remote_host=172.17.0.1
      PHP_IDE_CONFIG: serverName=ose-dev.localhost

    build:
      context: .
      dockerfile: Dockerfile

    volumes:
        - .:/app

    working_dir: /app

#    ports:
#      - "8080:80"
#      - "8443:443"

    networks:
        devnet:
            ipv4_address: 172.21.0.10

networks:
  devnet:
    external:
        name: laures
