version: '3'

# Ne pas oublier d'ajouter au fichier /etc/hosts :
# 172.21.0.12 ose-test.localhost

services:
  ose-test:
    container_name: ose-test

    build:
      context: .
      dockerfile: Dockerfile-test

    volumes:
        - .:/app

    working_dir: /app

#    ports:
#      - "8080:80"
#      - "8443:443"

    networks:
        devnet:
            ipv4_address: 172.21.0.12

networks:
  devnet:
    external:
        name: laures
