# Ne pas oublier d'ajouter au fichier /etc/hosts :
# 172.21.0.10 ose-dev.localhost.unicaen.fr
# 172.21.0.15 ose-test.localhost.unicaen.fr

services:
  ose-dev:
    container_name: ose-dev

    environment:
      APPLICATION_ENV: dev
      APPLICATION_HOSTNAME: ose-dev.localhost.unicaen.fr
      XDEBUG_CONFIG: "remote_host=172.21.0.10"
      PHP_IDE_CONFIG: "serverName=ose-dev.localhost.unicaen.fr"
      IGNORE_MV_EXT_SERVICE: "true"

    build:
      context: .
      dockerfile: Dockerfile
      args:
        PHP_VERSION: 8.2
        APPLICATION_ENV: dev

    volumes:
      - .:/app

    working_dir: /app

    extra_hosts:
      - "host.docker.internal:host-gateway"

    networks:
      devnet:
        ipv4_address: 172.21.0.10




  ose-test:
    container_name: ose-test

    environment:
      APPLICATION_ENV: test
      APPLICATION_HOSTNAME: ose-test.localhost.unicaen.fr
      XDEBUG_CONFIG: "remote_host=172.21.0.15"
      PHP_IDE_CONFIG: "serverName=ose-test.localhost.unicaen.fr"
      IGNORE_MV_EXT_SERVICE: "true"

    build:
      context: .
      dockerfile: Dockerfile
      args:
        PHP_VERSION: 8.2
        APPLICATION_ENV: test

    volumes:
      - .:/app

    working_dir: /app

    extra_hosts:
      - "host.docker.internal:host-gateway"

    networks:
      devnet:
        ipv4_address: 172.21.0.15






networks:
  devnet:
    name: laures
    external: true