<h1>Déposer un fichier pour la pièce &laquo; <?php echo $this->typePieceJointe ?> &raquo;</h1>

<?php $form->prepare(); // The correct enctype is set here ?>
<?php echo $this->form()->openTag($form); ?>

    <div class="form-element">
        <?php $fileElement = $form->get('files'); ?>
        <?php echo $this->formLabel($fileElement); ?>
        <?php echo $this->formFile($fileElement); ?>
        <?php echo $this->formElementErrors($fileElement); ?>
    </div>

    <input type="submit" value="Envoyer" />

<?php echo $this->form()->closeTag(); ?>

<script>
$(function() {
//    $("#files").fileinput({'showUpload':false, 'previewFileType':'any', 'browseLabel': "Parcourir &hellip;"});
//    AjaxModalListener.singleton.stop();
//    $("#upload-form").ajaxForm({
//        success: function() { 
//            alert("Thank you for your comment!");
//        },
//    }); 
//    // attach handler to form's submit event 
//    $('#upload-form').submit(function() {
//        // submit the form 
//        $(this).ajaxSubmit(); 
//        // return false to prevent normal browser submit and page navigation 
//        return false; 
//    });
});
</script>