<link href="<?php //echo $this->basePath('css/fileinput.min.css') ?>" media="screen" rel="stylesheet" type="text/css"> 

<?php $this->headTitle()->append($intervenant->getNomUsuel())->append("Pièces justificatives") ?>

<h1 class="page-header"><?php echo $title ?></h1>

<?php
$messenger = $this->messenger(true);
if ($complet) {
    $messenger->addMessage("Toutes les pièces justificatives obligatoires ont été fournies.", 'success');
}
else {
    $messenger->addMessage("Il manque des pièces justificatives obligatoires.", 'danger');
}
echo $messenger;
?>

<?php $form->prepare(); ?>

<style>
    a.modele-doc { margin-left: 20px; }
    span.text-warning { font-style: italic; }
</style>

<div class="row">
    <div class="col-md-6">
        <?php echo $this->form()->openTag($form) ?>
        <?php echo $this->formControlGroup($form->get('pj')) ?>
        <?php echo $this->formElement($form->get('security')) ?>
        <hr />
        <?php echo $form->has('submit') ? $this->formSubmit($form->get('submit')->setAttribute('class', 'btn btn-primary')) : null ?>
        <?php echo $this->form()->closeTag() ?>
    </div>
    
    <div class="col-md-6">
        
        <?php foreach($form->get('pj')->getValueOptions() as $options): ?>
            <?php 
            $typePieceJointe = $options['value'];
            $divId = uniqid('div');
            $formId = 'form-' . $typePieceJointe->getId();
            $urlLister = $this->url('piece-jointe/intervenant/lister', ['typePieceJointe' => $typePieceJointe], [], true);
            $urlAjouter = $this->url('piece-jointe/intervenant/ajouter', ['typePieceJointe' => $typePieceJointe], [], true);
            $formUpload
                    ->setAttribute('id', $formId)
                    ->setAttribute('action', $urlAjouter)
                    ->prepare(); // The correct enctype is set here 
            ?>
            <h3>Fichiers fournis pour la pièce &laquo; <?php echo $typePieceJointe ?> &raquo; :</h3>
            <div class="liste-pj-par-type" id="<?php echo $divId ?>" data-url="<?php echo $urlLister ?>"></div>
            
            <script>
            $(function() {
                $("#<?php echo $formId ?>").ajaxForm({
                    success: function() { 
                        alert("Thank you for your comment!");
                        $("#<?php echo $divId ?>").refresh();
                    },
                    beforeSubmit: function(arr, $form, options) { 
                        // The array of form data takes the following form: 
                        // [ { name: 'username', value: 'jresig' }, { name: 'password', value: 'secret' } ] 
                        console.log(arr);
                        // return false to cancel submit                  
                    }
                }); 
            });
            </script>
        <?php endforeach ?>
        
        <!--<h3>Destinataires des pièces justificatives</h3>
        <?php if (!count($destinataires)): ?>
            <?php 
            $contact = '<a href="' . $this->url('contact') . '">Contact</a>';
            echo $this->messenger()->setMessage(
                    "<strong>Oups!</strong> L'application n'a pas été en mesure de déterminer la liste des destinataires compétents, "
                    . "merci d'utiliser la rubrique $contact en bas de cette page pour signaler cette anomalie.", 'danger');
            ?>
        <?php else: ?>
            <?php echo $this->htmlList($destinataires, false, false, false); ?>
        <?php endif; ?>-->
    </div>
</div>

<br />
<?php 
$message = <<<EOS
<p><strong>Information importante</strong></p>
<p>Votre saisie est terminée.</p>
<p>Votre contrat ne pourra être édité qu'après réception et vérification de l'ensemble des pièces justificatives.<br />
Aucun enseignement ne pourra avoir lieu avant la signature du contrat.</p>
EOS;
echo $this->messenger()->setMessage($message, 'warning');
?>

<?php if ($role instanceof \Application\Acl\IntervenantRole): ?>
    <hr />
    <?php echo $this->workflow($role->getIntervenant(), $role)->navNext() ?>
<?php endif; ?>
    
    
<script>
$(function() {
    // interdiction de décocher une case déjà cochée
    $("input[type=checkbox]:checked").not(":disabled").css('opacity', '0.5').click(function() { return false; });
    
    $(".liste-pj-par-type").each(function(index, elem) { $(elem).refresh(); });
});
</script>

<?php //$this->inlineScript()->prependFile($this->basePath('js/fileinput.min.js')) ?>

<script src="http://malsup.github.com/jquery.form.js"></script> 