<?php
use Application\Assertion\FichierAssertion;

$pj       = $this->pj;                    /* @var $pj       \Application\Entity\Db\PieceJointe */
$fichiers = $pj ? $pj->getFichier() : []; /* @var $fichiers \Application\Entity\Db\Fichier[] */
?>

<?php if (count($fichiers)): ?>

<ul>
<?php foreach ($fichiers as $fichier): ?>
    <li class="fichier-pj">
        
        <!-- lien de téléchargement du fichier -->
        <?php 
        $urlTelecharger = null;
        if ($this->isAllowed($fichier, FichierAssertion::PRIVILEGE_TELECHARGER)) {
            $paramsTelecharger = ['pieceJointe' => $pj->getId(), 'fichier' => $fichier->getId(), 'nomFichier' => $fichier->getNom()];
            $urlTelecharger    = $this->url('piece-jointe/intervenant/telecharger', $paramsTelecharger, [], true);
        }
        echo $this->uploader()->renderUploadedFile($fichier, $urlTelecharger);
        ?>
       
        <!-- lien de suppression du fichier -->
        <?php 
        $urlSupprimer = null;
        if ($this->isAllowed($fichier, FichierAssertion::PRIVILEGE_DELETE)) {
            $paramsSupprimer = ['pieceJointe' => $pj->getId(), 'fichier' => $fichier->getId()];
            $urlSupprimer    = $this->url('piece-jointe/intervenant/supprimer', $paramsSupprimer, [], true); 
        }
        echo $this->uploader()->renderDeleteFile($fichier, $urlSupprimer);
        ?>
            
        <!--<span class="label label-warning"><span class="glyphicon glyphicon-exclamation-sign"></span> Non validée</span>-->
    </li>
<?php endforeach ?>
</ul>

<?php else: ?>

<p>Aucun.</p>

<?php endif ?>