<?php

use Application\Provider\Privilege\Privileges;

/**
 * @var $this \Application\View\Renderer\PhpRenderer
 */

$canEdit = $this->isAllowed(Privileges::getResourceId(Privileges::PIECE_JUSTIFICATIVE_GESTION_EDITION));

echo $this->form()->openTag($form->prepare());
echo $this->messenger()->addCurrentMessagesFromFlashMessenger();

?>

    <div class="row">
        <div class="col-md-12">
            <?php echo $this->formControlGroup($form->get('premier-recrutement')); ?>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <?php echo $this->formControlGroup($form->get('typePieceJointe')); ?>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <?php echo $this->formControlGroup($form->get('changement-rib')); ?>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <?php echo $this->formControlGroup($form->get('fc')); ?>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <?php echo $this->formControlGroup($form->get('seuil-hetd')); ?>
        </div>
        <div class=col-md-4>
            <?php echo $this->formControlGroup($form->get('annee-debut')); ?>
        </div>
        <div class=col-md-4>
            <?php echo $this->formControlGroup($form->get('annee-fin')); ?>
        </div>
    </div>

            <?php
            echo $this->formSubmit($form->get('submit'));
            ?>

        <?php if (($canEdit) && ($form->getObject()->getId())){ ?>

        <a class="pop-ajax btn btn-danger"
           href="<?php echo $this->url('piece-jointe/delete-type-piece-jointe-statut', ['typePieceJointeStatut' => $form->getObject()->getId()]) ?>"
           title="Supprimer le type de piece jointe"
           data-content="<p class='lead text-danger'><strong>Attention!</strong> Confirmez-vous cette suppression ?</p>"
           data-confirm="true"
           data-confirm-button="Oui"
           data-cancel-button="Non"
           data-submit-reload="true"
        >
            Supprimer
        </a>

    <?php } ?>
<?php
echo $this->formRow($form->get('security'));
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();