<?php

use Application\Entity\Db\TypePieceJointe;
use Application\Entity\Db\StatutIntervenant;
use Application\Entity\Db\TypePieceJointeStatut;
use Application\Provider\Privilege\Privileges;

/**
 * @var $typesPiecesJointes TypePieceJointe[]
 * @var $statutsIntervenants StatutIntervenant[][]
 * @var $typesPiecesJointesStatuts TypePieceJointeStatut[][]
 */

$canEdit = $this->isAllowed(Privileges::getResourceId(Privileges::PIECE_JUSTIFICATIVE_GESTION_EDITION));
$i=0;$j=0;
?>

<style>
    .triables {
        align: left;
    }

    .champ-triable tr {
        align: left;
    }

    .tpjs {
        line-height: 1.1em;
        font-size: 8pt;
    }

    .notpjs {

    }
</style>

<script type="text/javascript">

    $(function () {

        $(".triables").sortable({
            handle: '.glyphicon-move',
            axis: 'y',
            update: function (event, ui) {
                var champsIds = '';
                ui.item.parent().find('tr.champ-triable').each(function () {
                    if (champsIds != '') champsIds += ',';
                    champsIds += $(this).data('id');
                });
                $.post(Url('piece-jointe/type-piece-jointe-trier'), {champsIds: champsIds}).done(function (res) {
                    alertFlash(res.msg, 'success', 3000);
                });
            }
        });
    });
    //        $(".triables").disableSelection();

    /**
     *
     * @param i int
     * @param j int
     * position dans le tableau <colonne><ligne>
     *     parcours tout le tableau
     *     met le fond en blanc partout sauf sur l'intersection gauche/haut de la case de la souris dans la couleur #FCF8E3
     */
    function sourisHover(i, j) {
        var k, l, n, m; // indices dans le tableau
        var clr;
        var objCell, objR, objP, objTb;
        var objDiv;
 //       ajuste(); // en incluant ajuste donne le width de la table
        objP = document.getElementById('tblTpjs');
        objTb = objP.children;
        objR = objTb[0].children;
        objCell = objR[0].children;
        n = objCell.length - 1;
        for (l = 1; l < n; l++) {
            objDiv = document.getElementById('th' + l);
            if (l == i) clr = "#FCF8E3";
            else clr = "#FFFFFF";
            objDiv.style.backgroundColor = clr;
        }
        objR = objTb[1].children;
        m = objR.length;
        // la colonne
        for (k = 0; k < m; k++) {
            objCell = objR[k].children;
            n = objCell.length;
            for (l = 0; l < n; l++) {
                if ((k == j) && (l <= i)) clr = "#FCF8E3";
                else if ((l == i) && (k <= j))  clr = "#FCF8E3";
                else clr = "#FFFFFF";
                objCell[l].style.backgroundColor = clr;
            }
        }
    }

    function ajuste(){
        var i,n; // indice de ligne et nbe de colonnes
        var ObjR,objCell,objDiv,objTb;
        var taille;
        objP = document.getElementById('tblTpjs');
        objTb = objP.children;
        objR = objTb[0].children;
        objCell = objR[0].children;
        n = objCell.length - 1;
        taille=n*10+10+objCell[0].clientWidth; // padd 8+2 pour chaque bord * nbe de colonnnes
        for(i=1;i<n;i++){
            objDiv=document.getElementById('th'+i);
            taille+=objDiv.clientWidth;
        }
     alert(taille);
    }

</script>

<?php $this->headTitle()->append($title = "Pièces justificatives attendues par statut d'intervenant") ?>

<h1 class="page-header"><?php echo $title ?></h1>

<table id="tblTpjs" class="table-bordered table-condensed table-header table-header-rotated" style="width:1121px">
    <thead>
    <tr>
        <th class="rotate-45 si" data-si=""><span>&nbsp;</span></th>
        <?php foreach( $statutsIntervenants as $typeId => $statuts ): foreach( $statuts as $statut ): $i++;

        ?>
            <th class="rotate-45 si" data-si="<?php $statut->getLibelle() ?>">
                <div id="<?php echo 'th' . $i ?>"><span><?php echo $statut; ?></span></div>
            </th>
        <?php endforeach; endforeach; ?>
    </tr>
    <tr>
        <th><span>&nbsp;</span></th>
        <?php foreach( $statutsIntervenants as $typeId => $statuts ): ?>
            <th colspan="<?php echo count($statuts) ?>"><?php echo reset($statuts)->getTypeIntervenant() ?></th>
        <?php endforeach; ?>
    </tr>
    </thead>

    <tbody class="triables">
    <?php $i = 0; $j = 0; foreach( $typesPiecesJointes as $typePieceJointe ): $j++; ?>
        <tr class="champ-triable" data-id="<?php echo $typePieceJointe->getId() ?>">
            <th>
                <?php echo $typePieceJointe ?>
                <span class="pull-right">
                    <span class="glyphicon glyphicon-move"
                          title="Vous pouvez trier les champs en déplaçant les lignes du tableau"></span>&nbsp;
                    <?php if ($canEdit): ?>
                    <a class="pop-ajax" data-event="type-piece-jointe-saisie"
                       href="<?php echo $this->url('piece-jointe/type-piece-jointe-saisie', ['typePieceJointe' => $typePieceJointe->getId()]) ?>"
                       title="Modifier le type de pièce jointe"
                       data-submit-reload="true">
                        <span class="glyphicon pull-right glyphicon-edit"></span></a>
                    <a class="pop-ajax"
                       href="<?php echo $this->url('piece-jointe/type-piece-jointe-delete', ['typePieceJointe' => $typePieceJointe->getId()]) ?>"
                       title="Supprimer le type de piece jointe"
                       data-content="<p class='lead text-danger'><strong>Attention!</strong> Confirmez-vous cette suppression ?</p>"
                       data-confirm="true"
                       data-confirm-button="Oui"
                       data-cancel-button="Non"
                       data-submit-reload="true"
                    >
                        <span style="padding-right: 8px" class="glyphicon pull-right glyphicon-trash"></span>
                    </a>
                </span>
                <?php endif; ?>
            </th>
            <?php foreach( $statutsIntervenants as $typeId => $statuts ): foreach( $statuts as $statut ): $i++;
                $tpjs = isset($typesPiecesJointesStatuts[$typePieceJointe->getId()][$statut->getId()]) ? $typesPiecesJointesStatuts[$typePieceJointe->getId()][$statut->getId()] : null;
                $url = $this->url('piece-jointe/modifier-type-piece-jointe-statut', ['typePieceJointe' => $typePieceJointe->getId(), 'statutIntervenant' => $statut->getId(),'typePieceJointeStatut' => $tpjs ? $tpjs->getId() : null]);
                ?>
                <td onmouseover="sourisHover(<?php echo $i . ',' . $j ?>)" class="<?php echo ($tpjs) ? 'tpjs' : 'notpjs' ?>">
                    <?php if ($canEdit): ?>
                        <a
                            class="ajax-modal"
                            data-event="event-update-tpjs"
                            href="<?php echo $url ?>>"
                            title="<?php echo $tpjs ? $tpjs->getTitle() : 'Pas de pièce justificative demandée' ?>"
                        ><?php echo $tpjs ? $tpjs : '-' ?></a>
                    <?php else: ?>
                        <?php echo $tpjs ? $tpjs : '-' ?>
                    <?php endif; ?>
                </td>
            <?php endforeach; endforeach; ?>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<?php if ($canEdit): ?>
<a class="btn btn-primary ajax-modal" data-submit-reload="true"
   href="<?php echo $this->url('piece-jointe/type-piece-jointe-saisie') ?>"
   title="Ajouter un type de pièce jointe"><span class="glyphicon glyphicon-edit"></span>
    Ajouter un type de pièce jointe</a>
<script>
    $(function () {

        $("body").on("event-update-tpjs", function (event, data) {
            window.location.reload();
        });
    });
</script>
<?php endif;