<?php

use Application\Provider\Privilege\Privileges;

/**
 * @var $this        \Application\View\Renderer\PhpRenderer
 * @var $pj          \Application\Entity\Db\PieceJointe
 */

if (empty($pj)) return '';

$params = [
    'pieceJointe' => $pj->getId(),
];

?>

    <!-- actions de validation de la pièce jointe entière -->
<?php if (!$pj->getValidation() && $this->isAllowed(Privileges::getResourceId(Privileges::PIECE_JUSTIFICATIVE_VALIDATION))): ?>
    <a class="valider-pj btn btn-success"
       href="<?= $this->url('piece-jointe/intervenant/valider', $params, [], true) ?>"
       title="Valider la pièce justificative '<?= $pj->getType() ?>'"
       data-loading-text="Patientez..."
    >
        <i class="fas fa-thumbs-up"></i> Valider
    </a>
<?php endif ?>

    <!-- actions de dévalidation de la pièce jointe entière -->
<?php if ($pj->getValidation() && $this->isAllowed(Privileges::getResourceId(Privileges::PIECE_JUSTIFICATIVE_DEVALIDATION))): ?>
    <a class="devalider-pj btn btn-danger"
       href="<?= $this->url('piece-jointe/intervenant/devalider', $params, [], true) ?>"
       title="Dévalider la pièce justificative <?= "'" . $pj->getType() . "'.\n" . $pj->getValidation() ?>"
       data-loading-text="Patientez..."
    >
        <i class="fas fa-thumbs-down"></i> Dévalider
    </a>
<?php endif ?>