<?php
/**
 * @var $this  \Application\View\Renderer\PhpRenderer
 * @var $form  \Application\Form\TypeRessource\TypeRessourceSaisieForm
 */
echo $this->messenger()->addCurrentMessagesFromFlashMessenger();

echo $this->form()->openTag($form); ?>

<div class="row">
    <div class="col-md-3">
        <?= $this->formControlGroup($form->get('libelle')); ?>
    </div>
    <div class="col-md-6">
        <?= $this->formControlGroup($form->get('description')); ?>
    </div>
    <div class="col-md-6">
        <?= $this->formControlGroup($form->get('type')); ?>
    </div>
    <div class="col-md-6">
        <?= $this->formControlGroup($form->get('obligatoire')); ?>
    </div>
</div>
<?= $this->formSubmit($form->get('submit')); ?>
<?= $this->formControlGroup($form->get('security')); ?>

<?= $this->form()->closeTag(); ?>
