<?php


use Application\Assertion\IntervenantDossierAssertion;

$editIdentite  = $this->isAllowed($intervenant, IntervenantDossierAssertion::PRIV_EDIT_IDENTITE);
$editAdresse   = $this->isAllowed($intervenant, IntervenantDossierAssertion::PRIV_EDIT_ADRESSE);
$editContact   = $this->isAllowed($intervenant, IntervenantDossierAssertion::PRIV_EDIT_CONTACT);
$editInsee     = $this->isAllowed($intervenant, IntervenantDossierAssertion::PRIV_EDIT_INSEE);
$editIban      = $this->isAllowed($intervenant, IntervenantDossierAssertion::PRIV_EDIT_IBAN);
$editEmployeur = $this->isAllowed($intervenant, IntervenantDossierAssertion::PRIV_EDIT_EMPLOYEUR);
$canValider    = $this->isAllowed($intervenant, IntervenantDossierAssertion::PRIV_CAN_VALIDE);
$canDevalider  = $this->isAllowed($intervenant, IntervenantDossierAssertion::PRIV_CAN_DEVALIDE);
$canEdit       = $this->isAllowed($intervenant, IntervenantDossierAssertion::PRIV_CAN_EDIT);
$canSupprimer  = $this->isAllowed($intervenant, IntervenantDossierAssertion::PRIV_CAN_SUPPRIME);

$pourcentageComplet = 100;
foreach ($intervenantDossierCompletude as $value) {
    if (!$value) {
        $pourcentageComplet -= floor(100 / count($intervenantDossierCompletude));
    }
}

//$nextEtape    = $validation ? WfEtape::CODE_DONNEES_PERSO_VALIDATION : WfEtape::CODE_DONNEES_PERSO_SAISIE;
$nextEtape = '';
$this->headTitle()->append("Nom intervenant XXX")->append("Données personnelles");
$fieldsets = $form->getFieldsets();
?>


<style>
    .row.display-flex {
        display: flex;
        flex-wrap: wrap;
    }

    .row.display-flex > [class*='col-'] {
        display: flex;
        flex-direction: column;
    }
</style>
<h1 class="page-header">Données personnelles
    <small><?= $intervenant; ?></small>
</h1>
<?php if ($intervenantDossierValidation): ?>
<div class="bg-success" style="padding:10px;">
    <?php endif; ?>

    <?php


    /**
     * Message Importance des données perso.
     */
    if (!$form->getObject()->getId()) {
        $msg = "Ces données sont indispensables pour éditer %s contrat et mettre en paiement %s heures d'enseignement.";
        if ($role->getIntervenant()) {
            $this->messenger()->addMessage(sprintf($msg, 'votre', 'vos'), 'warning');
        } else {
            $this->messenger()->addMessage(sprintf($msg, 'le', 'les'), 'warning');
        }
    }


    echo $this->messenger()->addCurrentMessagesFromFlashMessenger()->addMessagesFromFlashMessenger();

    echo $this->form()->openTag($form);
    ?>
    <!--Progression du dossier-->
    <div class="row">
        <div class="col-md-12">
            Vos données personnelles sont complétées à :
            <div class="progress">
                <div class="progress-bar progress-bar-success" style="width: <?= $pourcentageComplet; ?>%">
                    Complet à <?= $pourcentageComplet; ?>%
                </div>
                <div class="progress-bar progress-bar-warning" style="width: <?= 100 - $pourcentageComplet; ?>%">

                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <?php
        if ($canEdit) {
            echo $this->partial('application/intervenant-dossier/partial/formStatut', compact('form', 'intervenant', 'intervenantDossier', 'intervenantDossierCompletude'));
        } else {
            echo $this->partial('application/intervenant-dossier/partial/formStatutView', compact('form', 'intervenant', 'intervenantDossier', 'intervenantDossierCompletude'));
        }
        ?>
    </div>


    <?php if (empty($intervenantDossierStatut)): ?>
    <div class="row  display-flex hidden">
        <?php else: ?>
        <div class="row  display-flex">
            <?php endif; ?>

            <?php
            /*Fiedlset identite*/
            if ($fieldsetRules['fieldset-identite']) {
                if ($editIdentite) {
                    echo $this->partial('application/intervenant-dossier/partial/formIdentite', compact('form', 'intervenant', 'intervenantDossier', 'intervenantDossierCompletude'));
                } else {
                    echo $this->partial('application/intervenant-dossier/partial/formIdentiteView', compact('form', 'intervenant', 'intervenantDossier', 'intervenantDossierCompletude'));
                }
            }
            /*Fieldset Adresse*/
            if ($fieldsetRules['fieldset-adresse']) {
                if ($editAdresse) {
                    echo $this->partial('application/intervenant-dossier/partial/formAdresse', compact('form', 'intervenant', 'intervenantDossier', 'intervenantDossierCompletude'));
                } else {
                    echo $this->partial('application/intervenant-dossier/partial/formAdresseView', compact('form', 'intervenant', 'intervenantDossier', 'intervenantDossierCompletude'));
                }
            }
            /*Fieldset Contact*/
            if ($fieldsetRules['fieldset-contact']) {
                if ($editContact) {
                    echo $this->partial('application/intervenant-dossier/partial/formContact', compact('form', 'intervenant', 'intervenantDossier', 'intervenantDossierCompletude'));
                } else {
                    echo $this->partial('application/intervenant-dossier/partial/formContactView', compact('form', 'intervenant', 'intervenantDossier', 'intervenantDossierCompletude'));
                }
            }
            /*Fiedlset Insee*/
            if ($fieldsetRules['fieldset-insee']) {
                if ($editInsee) {
                    echo $this->partial('application/intervenant-dossier/partial/formInsee', compact('form', 'intervenant', 'intervenantDossier', 'intervenantDossierCompletude'));
                } else {
                    echo $this->partial('application/intervenant-dossier/partial/formInseeView', compact('form', 'intervenant', 'intervenantDossier', 'intervenantDossierCompletude'));
                }
            }
            if ($fieldsetRules['fieldset-iban']) {
                if ($editIban) {
                    echo $this->partial('application/intervenant-dossier/partial/formBancaire', compact('form', 'intervenant', 'intervenantDossier', 'intervenantDossierCompletude'));
                } else {
                    echo $this->partial('application/intervenant-dossier/partial/formBancaireView', compact('form', 'intervenant', 'intervenantDossier', 'intervenantDossierCompletude'));
                }
            }
            /*Fiedlset Employeur*/
            if ($fieldsetRules['fieldset-employeur']) {
                if ($editEmployeur) {
                    echo $this->partial('application/intervenant-dossier/partial/formEmployeur', compact('form', 'intervenant', 'intervenantDossier', 'intervenantDossierCompletude'));
                } else {
                    echo $this->partial('application/intervenant-dossier/partial/formEmployeurView', compact('form', 'intervenant', 'intervenantDossier', 'intervenantDossierCompletude'));
                }
            }
            /*Fieldset Autres*/
            if ($fieldsetRules['fieldset-autres']) {
                echo $this->partial('application/intervenant-dossier/partial/formAutres', compact('form', 'intervenant', 'intervenantDossier', 'champsAutres', 'intervenantDossierCompletude'));
            }

            ?>
        </div>

        <div class="row">
            <div class="col-md-12">
                <?php
                echo $this->formHidden($this->form->get('security'));
                if ($canEdit) {
                    echo $this->formSubmit($form->get('submit'));
                }

                ?>
                <?php if ($canValider): ?>
                    <a class="valider-dossier btn btn-success pop-ajax"
                       href="<?= $this->url('intervenant/dossier/valider', [], [], true) ?>"
                       title="Valider les données personnelles"
                       data-content="Confirmez-vous cette validation ?"
                       data-confirm="true"
                       data-confirm-button="Je confirme"
                       data-cancel-button="Non"
                       data-submit-reload="true"
                    >
                        <span class="glyphicon glyphicon-thumbs-up"></span> Je valide les données
                    </a>
                <?php endif ?>
                <!-- actions de dévalidation du dossier -->
                <?php if ($canDevalider): ?>
                    <a class="devalider-dossier btn btn-danger pop-ajax"
                       href="<?= $this->url('intervenant/dossier/devalider', [], [], true) ?>"
                       title="Dévalider les données personnelles"
                       data-content="<p class='lead text-danger'><strong>Attention!</strong> Confirmez-vous cette dévalidation ?</p>"
                       data-confirm="true"
                       data-confirm-button="Oui"
                       data-cancel-button="Non"
                       data-submit-reload="true"
                    >
                        <span class="glyphicon glyphicon-thumbs-down"></span> Je dévalide les données
                    </a>
                <?php endif ?>

                <!-- actions de suppression du dossier -->
                <?php if ($canSupprimer): ?>
                    <a class="supprimer-dossier btn btn-danger pop-ajax"
                       href="<?= $this->url('intervenant/dossier/supprimer', [], [], true) ?>"
                       title="Suppression des données personnelles"
                       data-content="<p class='lead text-danger'><strong>Attention!</strong> Confirmez-vous la suppression de toutes les données personnelles ?</p>"
                       data-confirm="true"
                       data-confirm-button="Oui"
                       data-cancel-button="Non"
                       data-submit-reload="true"
                    >
                        <span class="glyphicon glyphicon-thumbs-down"></span> Je supprime les données
                    </a>
                <?php endif ?>
            </div>
        </div>


        <?php
        echo $this->form()->closeTag();
        echo "<br/>";
        echo $this->feuilleDeRoute($intervenant)->renderNav($nextEtape);
        ?>
        <?php if ($intervenantDossierValidation): ?>
    </div>
<?php endif; ?>


    <script type="text/javascript">
        $(function () {

            manageDepartementNaissance();

            function manageDepartementNaissance()
            {
                var selectPays = $("select[name='DossierIdentite[paysNaissance]']");
                var selectDept = $("select[name='DossierIdentite[departementNaissance]']");
                var emptyDept = $("option[value='']", selectDept);

                selectPays.change(function () {
                    if ($("option:selected", selectPays).html() == 'FRANCE') {
                        selectDept.removeProp('disabled').parent().show();
                        emptyDept.html("- NON RENSEIGNÉ -");
                    } else {
                        selectDept.prop('disabled', 'disabled');
                        emptyDept.html("- NON RENSEIGNÉ -").prop('selected', 'selected');
                    }
                });

                selectPays.change();
            }
        });
    </script>
