<?php


use Application\Assertion\IntervenantDossierAssertion;

$editIdentite = $this->isAllowed($intervenant, IntervenantDossierAssertion::PRIV_EDIT_IDENTITE);
$editAdresse  = $this->isAllowed($intervenant, IntervenantDossierAssertion::PRIV_EDIT_ADRESSE);


//$nextEtape = $validation ? WfEtape::CODE_DONNEES_PERSO_VALIDATION : WfEtape::CODE_DONNEES_PERSO_SAISIE;
$this->headTitle()->append("Nom intervenant XXX")->append("Données personnelles");
$fieldsets = $form->getFieldsets();
?>
    <h1 class="page-header">Données personnelles
        <small><?= $intervenant; ?></small>
    </h1>
<?php


/**
 * Message Importance des données perso.
 */
/*if (!$form->getObject()->getId()){
    $msg = "Ces données sont indispensables pour éditer %s contrat et mettre en paiement %s heures d'enseignement.";
    if ($role->getIntervenant()) {
        $this->messenger()->addMessage(sprintf($msg, 'votre', 'vos'), 'warning');
    } else {
        $this->messenger()->addMessage(sprintf($msg, 'le', 'les'), 'warning');
    }
}*/

echo $this->messenger()->addCurrentMessagesFromFlashMessenger()->addMessagesFromFlashMessenger();

echo $this->form()->openTag($form);
?>
    <div class="row">

        <div class="col-md-12">
            <?php
            echo $this->formControlGroup($form->get('statut'));
            ?>
        </div>
    </div>

    <h3>Identité</h3>
    <div class="row">
        <?php
        if ($editIdentite) {
            echo $this->partial('application/intervenant-dossier/partial/formIdentite', compact('form', 'intervenant', 'intervenantDossier'));
        } else {
            echo $this->partial('application/intervenant-dossier/partial/formIdentiteView', compact('form', 'intervenant', 'intervenantDossier'));
        }
        ?>
    </div>
    <div class="row">
        <?php
        if ($editAdresse) {
            echo $this->partial('application/intervenant-dossier/partial/formAdresse', compact('form', 'intervenant', 'intervenantDossier'));
        } else {
            echo $this->partial('application/intervenant-dossier/partial/formAdresseView', compact('form', 'intervenant', 'intervenantDossier'));
        }
        echo $this->partial('application/intervenant-dossier/partial/formContact', compact('form', 'intervenant', 'intervenantDossier'));
        ?>
    </div>
    <div class="row">
        <?php
        echo $this->partial('application/intervenant-dossier/partial/formInsee', compact('form', 'intervenant', 'intervenantDossier'));
        echo $this->partial('application/intervenant-dossier/partial/formBancaire', compact('form', 'intervenant', 'intervenantDossier'));
        ?>
    </div>
    <div class="row">
        <?php
        echo $this->partial('application/intervenant-dossier/partial/formEmployeur', compact('form', 'intervenant', 'intervenantDossier'));
        echo $this->partial('application/intervenant-dossier/partial/formAutres', compact('form', 'intervenant', 'intervenantDossier'));
        ?>
    </div>
    <div class="row">
        <div class="col-md-12">
            <?php
            echo $this->formHidden($this->form->get('security'));
            echo $this->formSubmit($form->get('submit'));
            ?>
        </div>
    </div>

<?php


echo $this->form()->closeTag();
//echo $this->feuilleDeRoute($intervenant)->renderNav($nextEtape);
