<?php
/**
 * @var $this  \Application\View\Renderer\PhpRenderer
 * @var $form  \Mission\Form\MissionTypeForm
 * @var $tab   string
 */


/**
 * @var $typeMission                  \Mission\Entity\Db\TypeMission
 * @var $structures                   \Lieu\Entity\Db\Structure[]
 * @var $centreCoutsTypeMissionStruct Mission\Entity\Db\CentreCoutTypeMission[]
 * @var $forms                        \Mission\Form\MissionCentreCoutsTypeForm[]
 */
?>
<br>
<table class="table table-bordered">
    <thead>
    <tr>
        <td>Structure</td>
        <td>Centre de cout</td>
    </tr>
    </thead>
    <tbody>

    <?php
    /**
     * @var $centreCoutTypeMission \Mission\Entity\Db\CentreCoutTypeMission
     */
    foreach ($structures as $structure): ?>
        <tr>
            <td>
                <?php echo $structure->getLibelle() ?>
            </td>
            <?php if (!isset($centreCoutsTypeMissionStruct[$structure->getId()])): ?>
                <td>
                    <?php echo '<br>' . $this->form($forms[$structure->getId()]); ?>
                </td>
            <?php else: ?>

                <td>
                    <?php echo $centreCoutsTypeMissionStruct[$structure->getId()]->getCentreCouts()->getCode() . "-" . $centreCoutsTypeMissionStruct[$structure->getId()]->getCentreCouts()->getLibelle(); ?>
                    <a class="pop-ajax"
                       data-content="<p class='lead text-danger'><strong>Attention!</strong> Confirmez-vous cette suppression ?</p>"
                       data-confirm="true"
                       data-confirm-button="Oui"
                       data-cancel-button="Non"
                       data-submit-close="true"
                       data-submit-event="event-supprimer-cc"
                       href="<?= $this->url('missions-type/centre-couts-supprimer', ['typeMission' => $typeMission->getId(), 'centreCoutTypeMission' => $centreCoutsTypeMissionStruct[$structure->getId()]->getId()]) ?>"
                       title="Supprimer le scénario"><i class="fas fa-trash-can"></i>
                    </a>
                </td>
            <?php endif; ?>
        </tr>

    <?php endforeach; ?>

    </tbody>
</table>

<script>
    $("body").on("event-supprimer-cc", function (event, data)
    {
        event.preventDefault();
        $that = $("body").find('#centre-couts')
        $that.refresh();
    });
</script>