<?php
/**
 * @var $this  \Application\View\Renderer\PhpRenderer
 * @var $form  \Mission\Form\MissionTypeForm
 * @var $tab   string
 */

use Application\Provider\Privilege\Privileges;

echo '<br>' . $this->form($form);
/**
 * @var $entity             \Mission\Entity\Db\TypeMission
 * @var $centreCoutsLinkers \Doctrine\ORM\PersistentCollection
 */
if ($centreCoutsLinkers != null && !empty($centreCoutsLinkers)): ?>
    <br>
    <table class="table table-bordered">
        <thead>
        <tr>
            <td>Centre de cout</td>
            <td>Action</td>
        </tr>
        </thead>
        <tbody>

        <?php
        /**
         * @var $centreCoutsLinker \Mission\Entity\Db\CentreCoutTypeMission
         */
        foreach ($centreCoutsLinkers as $centreCoutsLinker): ?>
            <tr>
                <td>
                    <?php echo $centreCoutsLinker->getCentreCouts()->getCode() . "-" . $centreCoutsLinker->getCentreCouts()->getLibelle(); ?>
                </td>
                <td>
                    <a class="pop-ajax"
                       data-content="<p class='lead text-danger'><strong>Attention!</strong> Confirmez-vous cette suppression ?</p>"
                       data-confirm="true"
                       data-confirm-button="Oui"
                       data-cancel-button="Non"
                       data-submit-close="true"
                       data-submit-event="event-supprimer-cc"
                       href="<?= $this->url('missions-type/centre-couts-supprimer', ['typeMission' => $entity->getId(), 'centreCoutTypeMission' => $centreCoutsLinker->getId()]) ?>"
                       title="Supprimer le scénario"><i class="fas fa-trash-can"></i>
                    </a>
                </td>
            </tr>
        <?php endforeach; ?>

        </tbody>
    </table>
<?php endif; ?>

<script>
    $("body").on("event-supprimer-cc", function (event, data)
    {
        event.preventDefault();
        $that = $("body").find('#centre-couts')
        $that.refresh();
    });
</script>