<?php
/**
 * @var $this              \Application\View\Renderer\PhpRenderer
 * @var $missionsType \Mission\Entity\Db\TypeMission[]
 */

use Application\Provider\Privileges;

$this->headTitle()->append("Gestion des types de missions");
echo $this->messenger()->addCurrentMessagesFromFlashMessenger();
$canEdit      = $this->isAllowed(Privileges::getResourceId(Privileges::MISSION_EDITION_TYPE));
$canEditPlafond = $this->isAllowed(Privileges::getResourceId(Privileges::PLAFONDS_CONFIG_MISSION));
$canEditCC = $this->isAllowed(Privileges::getResourceId(Privileges::MISSION_EDITION_CENTRE_COUT_TYPE));
$canSupprimer = $this->isAllowed(Privileges::getResourceId(Privileges::MISSION_SUPPRESSION_TYPE));
?>
<h1 class="page-header">Gestion des types de missions</h1>

<table class="table table-bordered table-sm">
    <thead>
    <tr>
        <th>Libellé</th>
        <th>Code</th>
        <th>Accomp. Etudiants</th>
        <th>Besoin de formation</th>
        <th>Type de rémunération</th>
        <th>Type de rémunération majoré</th>
        <?php if ($canSupprimer || $canEdit || $canEditCC || $canEditPlafond): ?>
            <th>Action</th>
        <?php endif; ?>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($missionsType as $missionType) : ?>

        <tr>
            <td><?= $missionType->getLibelle(); ?></td>
            <td class="text-center"><?= $missionType->getCode() ?></td>
            <td class="text-center"><i class="fas fa-<?= $missionType->isAccompagnementEtudiants() ? 'check text-success' : 'xmark text-danger' ?>"></i></td>
            <td class="text-center"><i class="fas fa-<?= $missionType->isBesoinFormation() ? 'check text-success' : 'xmark text-danger' ?>"></i></td>
            <td><?php if ($missionType->getTauxRemu()):
                    echo $missionType->getTauxRemu()->getLibelle();
                endif; ?></td>
            <td><?php if ($missionType->getTauxRemuMajore()):
                    echo $missionType->getTauxRemuMajore()->getLibelle();
                endif; ?></td>
            <?php if ($canSupprimer || $canEdit || $canEditCC || $canEditPlafond): ?>
                <td style="text-align: center">
                    <?php if ($canEdit || $canEditCC || $canEditPlafond):
                        if($canEdit): ?>
                            <a class="ajax-modal " data-event="type-edition"
                               href="<?= $this->url("missions-type/saisir", ['typeMission' => $missionType->getId()]) ?>"
                               title="Modifier le type">
                                <i class="fas fa-pen-to-square"></i>
                            </a>
                        <?php else:?>
                            <a class="ajax-modal " data-event="type-edition"
                               href="<?= $this->url("missions-type/visualiser", ['typeMission' => $missionType->getId()]) ?>"
                               title="Modifier le type">
                                <i class="fas fa-pen-to-square"></i>
                            </a>
                        <?php endif; ?>
                    <?php endif; ?>
                    <?php if ($canSupprimer): ?>
                        <a class="pop-ajax" data-event="type-suppression" data-content="Êtes-vous sur de vouloir supprimer"
                           data-confirm="true"
                           data-submit-reload="true"
                           href="<?= $this->url("missions-type/supprimer", ['typeMission' => $missionType->getId()]) ?>"
                           title="Supprimer le type">
                            <i class="fas fa-trash-can"></i>
                        </a>
                    <?php endif; ?>
                </td>
            <?php endif; ?>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<?php if ($canEdit): ?>
    <div>
        <a class="btn btn-primary ajax-modal " data-event="type-edition"
           href="<?= $this->url("missions-type/saisir", []) ?>"
           title="Ajouter un Type">
            <i class="fas fa-plus"></i> Ajouter un type
        </a>
    </div>
<?php endif; ?>

<script type="text/javascript">
    $(function () {
        $("body").on("type-edition", function (event, data) {
            window.location.reload();
        });
    });

    $(function () {
        $("body").on("type-edition", function (event, data) {
            window.location.reload();
        });
    });
</script>