<?php
/**
 * @var $this              \Application\View\Renderer\PhpRenderer
 */

$this->headTitle()->append("Gestion des types de missions");
echo $this->messenger()->addCurrentMessagesFromFlashMessenger();
$canEdit      = true;
$canSupprimer = true;
?>
<h1 class="page-header">Gestion des types de missions</h1>

<table class="table table-bordered table-sm">
    <thead>
    <tr>
        <th style="text-align: center">Libelle</th>
        <th style="text-align: center">Code</th>
        <th style="text-align: center">Type de rémunération</th>
        <th style="text-align: center">Action</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($missionsType as $missionType) : ?>

        <tr>
            <td style="text-align: center"><?php echo $missionType->getLibelle(); ?></td>
            <td style="text-align: center"><?php echo $missionType->getCode() ?></td>
            <td style="text-align: center"><?php echo $missionType->getMissionTauxRemu()->getLibelle() ?></td>
            <td style="text-align: center">
                <a class="ajax-modal " data-event="type-edition"
                   href="<?= $this->url("missions-type/saisir", ['typeMission' => $missionType->getId()]) ?>"
                   title="Modifier le type">
                    <i class="fas fa-pen-to-square"></i>
                </a>
                <a class="ajax-modal " data-event="type-suppression"
                   href="<?= $this->url("missions-type/supprimer", ['typeMission' => $missionType->getId()]) ?>"
                   title="Supprimer le type">
                    <i class="fas fa-trash-can"></i>
                </a>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<div>
    <a class="btn btn-primary ajax-modal " data-event="type-edition"
       href="<?= $this->url("missions-type/saisir", []) ?>"
       title="Ajouter un Type">
        <i class="fas fa-plus"></i> Ajouter un type
    </a>
</div>

<script type="text/javascript">
    $(function () {
        $("body").on("type-edition", function (event, data) {
            window.location.reload();
        });
    });

    $(function () {
        $("body").on("type-edition", function (event, data) {
            window.location.reload();
        });
    });
</script>