<?php
/**
 * @var $this        \Application\View\Renderer\PhpRenderer
 * @var $form        \Mission\Form\MissionTypeForm
 * @var $tab         string
 * @var $typeMission \Mission\Entity\Db\TypeMission
 */

use Application\Provider\Privilege\Privileges;


$visu = $this->messenger()->addCurrentMessagesFromFlashMessenger() . $this->form($form);

$tabs = [
    [
        'id'      => 'fiche',
        'label'   => 'Fiche',
        'content' => $visu,
    ],
];

$id      = $form->get("id")->getValue();
$canEdit = $this->isAllowed(Privileges::getResourceId(Privileges::PLAFONDS_CONFIG_MISSION));

//TODO décommenter pour mise en place centre couts par mission
//$canEditCC = $this->isAllowed(Privileges::getResourceId(Privileges::MISSION_EDITION_CENTRE_COUT_TYPE));

if ($id && $canEdit) {

    $tabs[] = [
        'id'    => 'plafonds',
        'label' => '<i class="fas fa-signal"></i> Plafonds',
        'url'   => $this->url('plafond/mission', ['typeMission' => $id]),
    ];
}

//TODO décommenter pour mise en place centre couts par mission
//if ($id && $canEditCC) {
//
//    $tabs[] = [
//        'id'    => 'centre-couts',
//        'label' => '<i class="fas fa-signal"></i> Centre de coûts',
//        'url'   => $this->url('missions-type/centre-couts', ['typeMission' => $id]),
//    ];
//}

echo $this->tabajax($tabs, $tab);
