<?php
/**
 * @var $this        \Application\View\Renderer\PhpRenderer
 * @var $form        \Mission\Form\MissionTypeForm
 * @var $tab         string
 * @var $typeMission \Mission\Entity\Db\TypeMission
 */

use Application\Provider\Privileges;

$values = [
    "Libellé"                         => $typeMission->getLibelle(),
    "Code"                            => $typeMission->getCode(),
    "Taux de rémunération par défaut" => $typeMission->getTauxRemu() ? $typeMission->getTauxRemu() : "Aucun",
    "Taux de rémunération majoré"     => $typeMission->getTauxRemuMajore() ? $typeMission->getTauxRemuMajore() : "Aucun",
    "Accompagnement d'étudiants"      => $typeMission->getAccompagnementEtudiants() ? "Oui" : "Non",
    "Besoin de formation"             => $typeMission->getBesoinFormation() ? "Oui" : "Non",
];

$visu = "<dl>\n";
foreach ($values as $key => $value) {
    $visu .= "<dt>$key :</dt><dd>$value</dd>\n";
}
$visu .= "</dl>";

$tabs = [
    [
        'id'      => 'fiche',
        'label'   => 'Fiche',
        'content' => $visu,
    ],
];

$id             = $typeMission->getId();
$canEditPlafond = $this->isAllowed(Privileges::getResourceId(Privileges::PLAFONDS_CONFIG_MISSION));
$canEditCC      = $this->isAllowed(Privileges::getResourceId(Privileges::MISSION_EDITION_CENTRE_COUT_TYPE));

if ($id && $canEditPlafond) {

    $tabs[] = [
        'id'    => 'plafonds',
        'label' => '<i class="fas fa-signal"></i> Plafonds',
        'url'   => $this->url('plafond/mission', ['typeMission' => $id]),
    ];
}

if ($id && $canEditCC) {

    $tabs[] = [
        'id'    => 'centre-couts',
        'label' => '<i class="fas fa-eur"></i> Centre de coûts',
        'url'   => $this->url('missions-type/centre-couts', ['typeMission' => $id]),
    ];
}

echo $this->tabajax($tabs, $tab);
