<?php

/**
 * @var $this        \Application\View\Renderer\PhpRenderer
 * @var $title       string
 * @var $intervenant \Intervenant\Entity\Db\Intervenant
 * @var $differences \Indicateur\Entity\Db\IndicModifDossier[]
 */

use Application\Provider\Privileges;

$canPurge = $this->isAllowed(Privileges::getResourceId(Privileges::DOSSIER_PURGER_DIFFERENCES));

if ($canPurge) {
    $urlPurge = $this->url('intervenant/dossier/purger-differences', ['intervenant' => $this->intervenant->getId()]);
} else {
    $urlPurge = null;
}

?>
    <h1 class="page-header"><?= $title ?></h1>

    <table class="table table-bordered">
        <thead>
        <tr>
            <th>Données concernées</th>
            <th>Données importées de <?= $intervenant->getSource() ?></th>
            <th>Données personnelles saisies</th>
            <th>Horodatage</th>
        </tr>
        </thead>
        <tbody>

        <?php foreach ($differences as $difference): ?>
            <tr>
                <td><?= $difference->getAttrName() ?></td>
                <td>
                    <pre><?= $difference->getAttrOldValue() ?></pre>
                    <div class="float-end">
                        <small>Source: <?= $difference->getAttrOldSourceName() ?></small>
                    </div>
                </td>
                <td>
                    <pre><?= $difference->getAttrNewValue() ?></pre>
                    <div class="float-end">
                        <small>Source: <?= $difference->getAttrNewSourceName() ?></small>
                    </div>
                </td>
                <td>
                    <?= sprintf("Le %s <br>par %s",
                        $difference->getHistoModification()->format(\Application\Constants::DATETIME_FORMAT),
                        $difference->getHistoModificateur()) ?>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>

    <a class="btn btn-secondary" href="javascript:window.history.back()">
        <i class="fas fa-rotate-left" aria-hidden="true"></i>
        Page précédente
    </a>

    <a class="btn btn-warning"
       href="<?= $this->url('intervenant/dossier', ['intervenant' => $intervenant->getId()]) ?>"
    >Voir les données personnelles de <?= $intervenant ?></a>

<?php if ($canPurge): ?>

    <a href="<?= $urlPurge ?>"
       class="btn btn-danger pop-ajax"
       data-submit-event="event-purger-indic"
       data-confirm="true"
    >Ok, effacer cet historique</a>
    <script>
        $("body").on("event-purger-indic", function (event, data)
        {
            window.history.back();
        });
    </script>
<?php endif; ?>