<?php

/**
 * @var $role                         \Application\Entity\Db\Role
 * @var $intervenant                  \Intervenant\Entity\Db\Intervenant
 * @var $intervenantDossier           \Dossier\Entity\Db\IntervenantDossier
 * @var $intervenantDossierValidation \Workflow\Entity\Db\Validation
 * @var $intervenantDossierStatut     \Intervenant\Entity\Db\Statut
 * @var $fieldsetRules                Array
 * @var $champsAutres                 \Application\Entity\Collection
 */


use Dossier\Assertion\IntervenantDossierAssertion;
use Workflow\Entity\Db\WfEtape;

$editIdentite  = $this->isAllowed($intervenant, IntervenantDossierAssertion::PRIV_EDIT_IDENTITE);
$editAdresse   = $this->isAllowed($intervenant, IntervenantDossierAssertion::PRIV_EDIT_ADRESSE);
$editContact   = $this->isAllowed($intervenant, IntervenantDossierAssertion::PRIV_EDIT_CONTACT);
$editInsee     = $this->isAllowed($intervenant, IntervenantDossierAssertion::PRIV_EDIT_INSEE);
$editIban      = $this->isAllowed($intervenant, IntervenantDossierAssertion::PRIV_EDIT_IBAN);
$editEmployeur = $this->isAllowed($intervenant, IntervenantDossierAssertion::PRIV_EDIT_EMPLOYEUR);
$canValider    = $this->isAllowed($intervenant, IntervenantDossierAssertion::PRIV_CAN_VALIDE);
$canDevalider  = $this->isAllowed($intervenant, IntervenantDossierAssertion::PRIV_CAN_DEVALIDE);
$canEdit       = $this->isAllowed($intervenant, IntervenantDossierAssertion::PRIV_CAN_EDIT);
$canSupprimer  = $this->isAllowed($intervenant, IntervenantDossierAssertion::PRIV_CAN_SUPPRIME);
$formErrors    = $this->formErrors($form);

$nextEtape = $intervenantDossierValidation ? WfEtape::CODE_DONNEES_PERSO_VALIDATION : WfEtape::CODE_DONNEES_PERSO_SAISIE;
$this->headTitle()->append($intervenant->getPrenom() . " index.phtml" . $intervenant->getNomUsuel())->append("Données personnelles");
$fieldsets = $form->getFieldsets();
?>


<style>
    .row.display-flex {
        display: flex;
        flex-wrap: wrap;
    }

    .row.display-flex > [class*='col-'] {
        display: flex;
        flex-direction: column;
    }

    div.rib-part {
        display: inline-block;
        vertical-align: top;
    }

    div.rib-part input {
        width: auto;
    }

    div.readonly {
        display: block;
        background-color: #eee;
        padding: 5px;
        height: 30px;
    }
</style>
<?php
    $this->intervenant($intervenant)->renderTitle('Données personnelles');
    echo $this->messenger()->addCurrentMessagesFromFlashMessenger()->addMessagesFromFlashMessenger();
?>


    <!--Progression du dossier-->
    <?php if (!empty($formErrors)): ?>
        <?= $this->formErrors($form); ?>
    <?php else: ?>
        <?php if (!empty($tblDossier)): ?>
            <div class="messenger alert <?= ($tblDossier->getCompletude()) ? 'alert-success' : 'alert-warning' ?> ">
                <?php if ($tblDossier->getCompletude() && $intervenantDossierValidation): ?>
                    Vos données personnelles sont maintenant <span style="font-size:1em;" class="badge bg-success">Complètes</span> et
                    <span
                            style="font-size:1em;" class="badge bg-success">Validées</span>
                <?php elseif ($tblDossier->getCompletude() && !$intervenantDossierValidation): ?>
                    Vos données personnelles sont maintenant <span style="font-size:1em;"
                                                                   class="badge bg-success">complètes</span> et en attente de validation par nos services
                <?php else: ?>
                    Vos données personnelles sont incomplètes, merci de renseigner les informations obligatoires demandées dans les blocs
                    <span style="font-size:1em;" class="badge bg-warning text-dark">A compléter</span>
                <?php endif; ?>
            </div>
        <?php else: ?>
            <div class="messenger alert alert-warning">
                Veuillez vérifier / compléter vos données personnelles pré-renseignées et enregistrer celles-ci pour
                initialiser votre dossier.
            </div>
        <?php endif; ?>

    <?php endif; ?>
    <!--Affichage de l'horodatage pour le dossier de l'intervenant-->
    <?= $this->historique($intervenantDossier) ?>




<!--
Debut du formulaire
-->

    <?= $this->form()->openTag($form); ?>
    <!-- legend champ obligatoire -->
    <p class="text-right"><span class="text-danger">*</span> champs obligatoires pour compléter vos données personnelles
    </p>

    <?php if ($fieldsetRules['fieldset-statut'])  : ?>
        <div class="row">
            <?php
            if ($canEdit) {
                echo $this->partial('dossier/intervenant-dossier/partial/formStatut', compact('form', 'intervenant', 'intervenantDossier', 'tblDossier'));
            } else {
                echo $this->partial('dossier/intervenant-dossier/partial/formStatutView', compact('form', 'intervenant', 'intervenantDossier', 'tblDossier'));
            }
            ?>
        </div>
    <?php endif; ?>
<!--Etape 1-->
<div class="row  display-flex">
    <h1>Etape 1 des données personnelles</h1>
    <!--Identité-->
    <?php
        if ($editIdentite) {
            echo $this->partial('dossier/intervenant-dossier/partial/formIdentite', compact('form', 'intervenant', 'intervenantDossier', 'tblDossier'));
        } else {
            echo $this->partial('dossier/intervenant-dossier/partial/formIdentiteView', compact('form', 'intervenant', 'intervenantDossier', 'tblDossier'));
        }
    ?>

</div>
<!--Etape 2-->
<div class="row  display-flex">
    <h1>Etape 1 des données personnelles</h1>
    <!--Identité-->
    <?php
    if ($editIdentite) {
        echo $this->partial('dossier/intervenant-dossier/partial/formIdentite', compact('form', 'intervenant', 'intervenantDossier', 'tblDossier'));
    } else {
        echo $this->partial('dossier/intervenant-dossier/partial/formIdentiteView', compact('form', 'intervenant', 'intervenantDossier', 'tblDossier'));
    }
    ?>

</div>


<?php
        echo $this->form()->closeTag();
        echo "<br/>";
        echo $this->feuilleDeRoute($intervenant)->renderNav($nextEtape);
        ?>




    <script type="text/javascript">


        $(function () {
            var dataModificated = 0;
            var messageDataModificated = "Vous souhaitez changer de statut, mais vos données personnelles ont été modifié, si vous n'enregistrez pas au préalable, elles seront perdues. Souhaitez vous continuer ?"

            manageDepartementNaissance();
            manageSituationMatrimoniale();


            function manageDepartementNaissance()
            {
                var selectPays = $("select[name='DossierIdentiteComplementaire[paysNaissance]']");
                var selectDept = $("select[name='DossierIdentiteComplementaire[departementNaissance]']");


                var emptyDept = $("option[value='']", selectDept);

                selectPays.change(function () {
                    var pays = $("option:selected", selectPays).html();
                    var paysToLower = pays.toLowerCase();
                    if (paysToLower == 'france') {
                        selectDept.removeAttr('disabled')
                        selectDept.siblings('button').removeClass('disabled')
                        emptyDept.removeAttr('selected')

                    } else {
                        selectDept.prop('disabled', 'disabled')
                        selectDept.siblings('button').addClass('disabled')
                        emptyDept.html("(Sélectionnez un département)").prop("selected", "selected");
                    }
                });

                selectPays.change();
            }

            function manageSituationMatrimoniale()
            {
                var selectSituationMatrimoniale = $("select[name='DossierIdentiteComplementaire[situationMatrimoniale]']");
                var dateSituationMatrimoniale = $("input[name='DossierIdentiteComplementaire[dateSituationMatrimoniale]']").parent('div').parent('div');

                var situation = $("option:selected", selectSituationMatrimoniale).html();

                if (situation == 'Célibataire' || situation == '- NON RENSEIGNÉ') {
                    dateSituationMatrimoniale.hide();
                }

                selectSituationMatrimoniale.change(function () {
                    var situation = $("option:selected", selectSituationMatrimoniale).html();
                    console.log(situation);
                    if (situation == 'Célibataire' || situation == '- NON RENSEIGNÉ -') {
                        dateSituationMatrimoniale.hide();
                    } else {
                        dateSituationMatrimoniale.show();
                    }
                });
            }


            $("select[name='DossierStatut[statut]']").change(function () {
                if (dataModificated) {
                    if (!confirm(messageDataModificated)) {
                        e.preventDefault();
                        e.stopImmediatePropagation();
                    } else {
                        var action = $("form[id='dossier']").attr('action');
                        $("form[id='dossier']").attr('action', action + '/change-statut-dossier');
                        $("form[id='dossier']").submit();
                    }
                } else {
                    var action = $("form[id='dossier']").attr('action');
                    $("form[id='dossier']").attr('action', action + '/change-statut-dossier');
                    $("form[id='dossier']").submit();
                }
            });


            $(".dossierElement").change(function () {
                dataModificated = 1;
            })

            $("body").on("devalide-donnees", function (event, data) {
                window.location = window.location.href;
            });
            $("body").on("valide-donnees", function (event, data) {
                window.location = window.location.href;
            });
            $("body").on("supprimer-donnees", function (event, data) {
                var url = window.location.href;
                var urlRedirect = url.replace('dossier', 'voir')
                window.location = urlRedirect;
            });


        })
        ;
    </script>
