<?php

/**
 * @var $form                         IntervenantDossierForm
 * @var $role                         \Utilisateur\Entity\Db\Role
 * @var $fieldsetRules                Array
 * @var $champsAutres                 \Application\Entity\Collection
 * @var $tblDossier                   \Dossier\Entity\Db\TblDossier
 */


use Dossier\Assertion\IntervenantDossierAssertion;
use Dossier\Form\IntervenantDossierForm;
use Workflow\Entity\Db\WorkflowEtape;

$editIdentite               = $this->isAllowed($tblDossier->getIntervenant(), IntervenantDossierAssertion::PRIV_EDIT_IDENTITE);
$editAdresse                = $this->isAllowed($tblDossier->getIntervenant(), IntervenantDossierAssertion::PRIV_EDIT_ADRESSE);
$editContact                = $this->isAllowed($tblDossier->getIntervenant(), IntervenantDossierAssertion::PRIV_EDIT_CONTACT);
$editInsee                  = $this->isAllowed($tblDossier->getIntervenant(), IntervenantDossierAssertion::PRIV_EDIT_INSEE);
$editIban                   = $this->isAllowed($tblDossier->getIntervenant(), IntervenantDossierAssertion::PRIV_EDIT_IBAN);
$editEmployeur              = $this->isAllowed($tblDossier->getIntervenant(), IntervenantDossierAssertion::PRIV_EDIT_EMPLOYEUR);
$canValider                 = $this->isAllowed($tblDossier->getIntervenant(), IntervenantDossierAssertion::PRIV_CAN_VALIDE);
$canDevalider               = $this->isAllowed($tblDossier->getIntervenant(), IntervenantDossierAssertion::PRIV_CAN_DEVALIDE);
$canEdit                    = $this->isAllowed($tblDossier->getIntervenant(), IntervenantDossierAssertion::PRIV_CAN_EDIT);
$canValiderComplementaire   = $this->isAllowed($tblDossier->getIntervenant(), IntervenantDossierAssertion::PRIV_CAN_VALIDE_COMP);
$canDevaliderComplementaire = $this->isAllowed($tblDossier->getIntervenant(), IntervenantDossierAssertion::PRIV_CAN_DEVALIDE_COMP);
$canEditComplementaire      = $this->isAllowed($tblDossier->getIntervenant(), IntervenantDossierAssertion::PRIV_CAN_EDIT_COMP);
$canSupprimer               = $this->isAllowed($tblDossier->getIntervenant(), IntervenantDossierAssertion::PRIV_CAN_SUPPRIME);
$formErrors                 = $this->formErrors($form);

$wfEtape = $tblDossier->getValidation() ? WorkflowEtape::DONNEES_PERSO_VALIDATION : WorkflowEtape::DONNEES_PERSO_SAISIE;
$this->headTitle()->append($tblDossier->getIntervenant()->getPrenom() . " index.phtml" . $tblDossier->getIntervenant()->getNomUsuel())->append("Données personnelles");
$fieldsets = $form->getFieldsets();
?>


<style>
    .row.display-flex {
        display: flex;
        flex-wrap: wrap;
    }

    .row.display-flex > [class*='col-'] {
        display: flex;
        flex-direction: column;
    }

    div.rib-part {
        display: inline-block;
        vertical-align: top;
    }

    div.rib-part input {
        width: auto;
    }

    div.readonly {
        display: block;
        background-color: #eee;
        padding: 5px;
        height: 30px;
    }
</style>
<?php
$this->intervenant($tblDossier->getIntervenant())->renderTitle('Données personnelles');
echo $this->messenger()->addCurrentMessagesFromFlashMessenger()->addMessagesFromFlashMessenger();
?>


<!--Gestion des erreurs du formulaire-->
<?php if (!empty($formErrors)): ?>
    <?= $this->formErrors($form); ?>
<?php endif; ?>

<!--Affichage de l'horodatage pour le dossier de l'intervenant-->
<?= $this->historique($tblDossier->getDossier()) ?>


<?= $this->form()->openTag($form); ?>

<!--DONNEES PERSONNELLES AVANT RECRUTEMENT-->

<div class="card">
    <?php if ($tblDossier->getValidation()): ?>
        <div class="card-header text-light bg-success">
            <h3>Données personnelles</h3>
        </div>
    <?php else: ?>
        <div class="card-header text-light bg-primary">
            <h3>Données personnelles</h3>
        </div>
    <?php endif; ?>
    <div class="card-body">
        <p class="text-right"><span class="text-danger">*</span> champs obligatoires pour compléter vos données
            personnelles
        </p>
        <?php if (!empty($tblDossier)): ?>
            <div class="messenger alert border">
                <?php if ($tblDossier->isCompletAvantRecrutement() && $tblDossier->getValidation()): ?>
                    Vos données personnelles sont maintenant <span style="font-size:1em;"
                                                                   class="badge bg-success">Complètes</span> et
                    <span
                            style="font-size:1em;" class="badge bg-success">Validées</span>
                <?php elseif ($tblDossier->isCompletAvantRecrutement() && !$tblDossier->getValidation()): ?>
                    Vos données personnelles sont maintenant <span style="font-size:1em;"
                                                                   class="badge bg-success">complètes</span> et en attente de validation par nos services
                <?php else: ?>
                    Vos données personnelles sont incomplètes, merci de renseigner les informations obligatoires demandées dans les blocs
                    <span style="font-size:1em;" class="badge bg-warning text-dark">A compléter</span>
                <?php endif; ?>
            </div>
        <?php else: ?>
            <div class="messenger alert alert-warning">
                Veuillez vérifier / compléter vos données personnelles pré-renseignées et enregistrer celles-ci pour
                initialiser votre dossier.
            </div>
        <?php endif; ?>

        <?php if ($fieldsetRules['fieldset-statut'])  : ?>
            <div class="row">
                <?php
                if ($canEdit) {
                    echo $this->partial('dossier/intervenant-dossier/partial/formStatut', compact('form', 'tblDossier'));
                } else {
                    echo $this->partial('dossier/intervenant-dossier/partial/formStatutView', compact('form', 'tblDossier'));
                }
                ?>
            </div>
        <?php endif; ?>

        <div class="row  display-flex">
            <!--Identité-->
            <?php

            if ($editIdentite && $canEdit) {
                echo $this->partial('dossier/intervenant-dossier/partial/formIdentite', compact('form', 'tblDossier'));
            } else {
                echo $this->partial('dossier/intervenant-dossier/partial/formIdentiteView', compact('form', 'tblDossier'));
            }
            if ($fieldsetRules['fieldset-identite-complementaire'] == 1) {
                if ($editIdentite && $canEdit) {
                    echo $this->partial('dossier/intervenant-dossier/partial/formIdentiteComplementaire', compact('form', 'tblDossier'));
                } else {
                    echo $this->partial('dossier/intervenant-dossier/partial/formIdentiteComplementaireView', compact('form', 'tblDossier'));
                }
            }
            if ($fieldsetRules['fieldset-adresse'] == 1) {
                if ($editAdresse && $canEdit) {
                    echo $this->partial('dossier/intervenant-dossier/partial/formAdresse', compact('form', 'tblDossier'));
                } else {
                    echo $this->partial('dossier/intervenant-dossier/partial/formAdresseView', compact('form', 'tblDossier'));
                }
            }
            if ($fieldsetRules['fieldset-contact'] == 1) {
                if ($editContact && $canEdit) {
                    echo $this->partial('dossier/intervenant-dossier/partial/formContact', compact('form', 'tblDossier'));
                } else {
                    echo $this->partial('dossier/intervenant-dossier/partial/formContactView', compact('form', 'tblDossier'));
                }
            }
            if ($fieldsetRules['fieldset-iban'] == 1) {
                if ($editIban && $canEdit) {
                    echo $this->partial('dossier/intervenant-dossier/partial/formBancaire', compact('form', 'tblDossier'));
                } else {
                    echo $this->partial('dossier/intervenant-dossier/partial/formBancaireView', compact('form', 'tblDossier'));
                }
            }
            if ($fieldsetRules['fieldset-insee'] == 1) {
                if ($editInsee && $canEdit) {
                    echo $this->partial('dossier/intervenant-dossier/partial/formInsee', compact('form', 'tblDossier'));
                } else {
                    echo $this->partial('dossier/intervenant-dossier/partial/formInseeView', compact('form', 'tblDossier'));
                }
            }

            ?>
        </div>
    </div>
    <div class="card-footer border-0 d-flex justify-content-end">

        <!--Etape 2-->
        <!--bouton de validation des données personnelles complémentaires-->
        <div class="row">
            <div class="col-md-12">
                <?php
                echo $this->formHidden($this->form->get('security'));
                if ($canEdit) {
                    echo $this->formSubmit($form->get('submit-button'));
                }

                ?>
                <?php if ($canValider): ?>
                    <a class="valider-dossier btn btn-success pop-ajax me-2"
                       href="<?= $this->url('intervenant/dossier/valider', [], [], true) ?>"
                       title="Valider les données personnelles"
                       data-content="Confirmez-vous cette validation ?"
                       data-confirm="true"
                       data-confirm-button="Je confirme"
                       data-cancel-button="Non"
                       data-submit-event="valide-donnees"
                    >
                        <i class="fas fa-thumbs-up"></i> Je valide les données
                    </a>
                <?php endif ?>
                <!-- actions de dévalidation du dossier -->
                <?php if ($canDevalider): ?>
                    <a class="devalider-dossier btn btn-danger pop-ajax"
                       href="<?= $this->url('intervenant/dossier/devalider', [], [], true) ?>"
                       title="Dévalider les données personnelles"
                       data-content="<p class='lead text-danger'><strong>Attention!</strong> Confirmez-vous cette dévalidation ?</p>"
                       data-confirm="true"
                       data-confirm-button="Oui"
                       data-submit-reload="true"
                       data-cancel-button="Non"
                       data-submit-event="devalide-donnees"
                    >
                        <i class="fas fa-thumbs-down"></i> Je dévalide les données
                    </a>
                <?php endif ?>
            </div>
        </div>
    </div>
</div>

<!--DONNEES PERSONNELLES APRES RECRUTEMENT-->
<?php if ($tblDossier->getValidation() && $tblDossier->getApresRecrutementAttendue() > 0): ?>
    <div class="card">
        <?php if ($tblDossier->getValidationComplementaire()): ?>
            <div class="card-header text-light bg-success">
                <h3>Données personnelles complémentaires</h3>
            </div>
        <?php else: ?>
            <div class="card-header text-light bg-primary">
                <h3>Données personnelles complémentaires</h3>
            </div>
        <?php endif; ?>
        <div class="card-body">
            <p class="text-right"><span class="text-danger">*</span> champs obligatoires pour compléter vos données
                personnelles complémentaires
            </p>
            <?php if (!empty($tblDossier)): ?>
                <div class="messenger alert border">
                    <?php if ($tblDossier->isCompletApresRecrutement() && $tblDossier->getValidationComplementaire()): ?>
                        Vos données personnelles complémentaires sont maintenant <span style="font-size:1em;"
                                                                                       class="badge bg-success">Complètes</span> et
                        <span
                                style="font-size:1em;" class="badge bg-success">Validées</span>
                    <?php elseif ($tblDossier->isCompletApresRecrutement() && !$tblDossier->getValidationComplementaire()): ?>
                        Vos données personnelles complémentaires sont maintenant <span style="font-size:1em;"
                                                                                       class="badge bg-success">complètes</span> et en attente de validation par nos services
                    <?php else: ?>
                        Vos données personnelles complémentaires sont incomplètes, merci de renseigner les informations obligatoires demandées dans les blocs
                        <span style="font-size:1em;" class="badge bg-warning text-dark">A compléter</span>
                    <?php endif; ?>
                </div>
            <?php else: ?>
                <div class="messenger alert alert-warning">
                    Veuillez vérifier / compléter vos données personnelles complémentaires pré-renseignées et
                    enregistrer
                    celles-ci pour
                    initialiser votre dossier.
                </div>
            <?php endif; ?>


            <div class="row  display-flex">
                <!--Identité-->
                <?php

                if ($fieldsetRules['fieldset-identite-complementaire'] == 2) {
                    if ($editIdentite && $canEditComplementaire) {
                        echo $this->partial('dossier/intervenant-dossier/partial/formIdentiteComplementaire', compact('form', 'tblDossier'));
                    } else {
                        echo $this->partial('dossier/intervenant-dossier/partial/formIdentiteComplementaire', compact('form', 'tblDossier'));
                    }
                }
                if ($fieldsetRules['fieldset-adresse'] == 2) {
                    if ($editAdresse && $canEditComplementaire) {
                        echo $this->partial('dossier/intervenant-dossier/partial/formAdresse', compact('form', 'tblDossier'));
                    } else {
                        echo $this->partial('dossier/intervenant-dossier/partial/formAdresseView', compact('form', 'tblDossier'));
                    }
                }
                if ($fieldsetRules['fieldset-contact'] == 2) {
                    if ($editContact && $canEditComplementaire) {
                        echo $this->partial('dossier/intervenant-dossier/partial/formContact', compact('form', 'tblDossier'));
                    } else {
                        echo $this->partial('dossier/intervenant-dossier/partial/formContactView', compact('form', 'tblDossier'));
                    }
                }
                if ($fieldsetRules['fieldset-iban'] == 2) {
                    if ($editIban && $canEditComplementaire) {
                        echo $this->partial('dossier/intervenant-dossier/partial/formBancaire', compact('form', 'tblDossier'));
                    } else {
                        echo $this->partial('dossier/intervenant-dossier/partial/formBancaireView', compact('form', 'tblDossier'));
                    }
                }
                if ($fieldsetRules['fieldset-insee'] == 2) {
                    if ($editInsee && $canEditComplementaire) {
                        echo $this->partial('dossier/intervenant-dossier/partial/formInsee', compact('form', 'tblDossier'));
                    } else {
                        echo $this->partial('dossier/intervenant-dossier/partial/formInseeView', compact('form', 'tblDossier'));
                    }
                }

                ?>


            </div>

        </div>
        <div class="card-footer d-flex justify-content-end">

            <!--Etape 2-->
            <!--bouton de validation des données personnelles complémentaires-->
            <div class="row">
                <div class="col-md-12">
                    <?php
                    echo $this->formHidden($this->form->get('security'));
                    if ($canEdit) {
                        echo $this->formSubmit($form->get('submit-button'));
                    }

                    ?>
                    <?php if ($canValiderComplementaire): ?>
                        <a class="valider-dossier btn btn-success pop-ajax"
                           href="<?= $this->url('intervenant/dossier/valider-complementaire', [], [], true) ?>"
                           title="Valider les données personnelles"
                           data-content="Confirmez-vous cette validation ?"
                           data-confirm="true"
                           data-confirm-button="Je confirme"
                           data-cancel-button="Non"
                           data-submit-event="valide-donnees"
                        >
                            <i class="fas fa-thumbs-up"></i> Je valide les données complémentaires
                        </a>
                    <?php endif ?>
                    <!-- actions de dévalidation du dossier -->
                    <?php if ($canDevaliderComplementaire): ?>
                        <a class="devalider-dossier btn btn-danger pop-ajax"
                           href="<?= $this->url('intervenant/dossier/devalider-complementaire', [], [], true) ?>"
                           title="Dévalider les données personnelles"
                           data-content="<p class='lead text-danger'><strong>Attention!</strong> Confirmez-vous cette dévalidation ?</p>"
                           data-confirm="true"
                           data-confirm-button="Oui"
                           data-submit-reload="true"
                           data-cancel-button="Non"
                           data-submit-event="devalide-donnees"
                        >
                            <i class="fas fa-thumbs-down"></i> Je dévalide les données complémentaires
                        </a>
                    <?php endif ?>

                </div>
            </div>
        </div>
    </div>
<?php endif; ?>




<?php
echo $this->form()->closeTag();
echo "<br/>";
echo $this->vue('workflow/nav', ['intervenant' => $tblDossier->getIntervenant()->getId(),
                                 'etape'       => $wfEtape]);
?>


<script type="text/javascript">


    $(function () {
        var dataModificated = 0;
        var messageDataModificated = "Vous souhaitez changer de statut, mais vos données personnelles ont été modifié, si vous n'enregistrez pas au préalable, elles seront perdues. Souhaitez vous continuer ?"

        manageDepartementNaissance();
        manageSituationMatrimoniale();


        function manageDepartementNaissance()
        {
            var selectPays = $("select[name='DossierIdentiteComplementaire[paysNaissance]']");
            var selectDept = $("select[name='DossierIdentiteComplementaire[departementNaissance]']");


            var emptyDept = $("option[value='']", selectDept);

            selectPays.change(function () {
                var pays = $("option:selected", selectPays).html();
                var paysToLower = pays.toLowerCase();
                if (paysToLower == 'france') {
                    selectDept.removeAttr('disabled')
                    selectDept.siblings('button').removeClass('disabled')
                    emptyDept.removeAttr('selected')

                } else {
                    selectDept.prop('disabled', 'disabled')
                    selectDept.siblings('button').addClass('disabled')
                    emptyDept.html("(Sélectionnez un département)").prop("selected", "selected");
                }
            });

            selectPays.change();
        }

        function manageSituationMatrimoniale()
        {
            var selectSituationMatrimoniale = $("select[name='DossierIdentiteComplementaire[situationMatrimoniale]']");
            var dateSituationMatrimoniale = $("input[name='DossierIdentiteComplementaire[dateSituationMatrimoniale]']").parent('div').parent('div');

            var situation = $("option:selected", selectSituationMatrimoniale).html();

            if (situation == 'Célibataire' || situation == '- NON RENSEIGNÉ') {
                dateSituationMatrimoniale.hide();
            }

            selectSituationMatrimoniale.change(function () {
                var situation = $("option:selected", selectSituationMatrimoniale).html();
                console.log(situation);
                if (situation == 'Célibataire' || situation == '- NON RENSEIGNÉ -') {
                    dateSituationMatrimoniale.hide();
                } else {
                    dateSituationMatrimoniale.show();
                }
            });
        }


        $("select[name='DossierStatut[statut]']").change(function () {
            if (dataModificated) {
                if (!confirm(messageDataModificated)) {
                    e.preventDefault();
                    e.stopImmediatePropagation();
                } else {
                    var action = $("form[id='dossier']").attr('action');
                    $("form[id='dossier']").attr('action', action + '/change-statut-dossier');
                    $("form[id='dossier']").submit();
                }
            } else {
                var action = $("form[id='dossier']").attr('action');
                $("form[id='dossier']").attr('action', action + '/change-statut-dossier');
                $("form[id='dossier']").submit();
            }
        });


        $(".dossierElement").change(function () {
            dataModificated = 1;
        })

        $("body").on("devalide-donnees", function (event, data) {
            window.location = window.location.href;
        });
        $("body").on("valide-donnees", function (event, data) {
            window.location = window.location.href;
        });
        $("body").on("supprimer-donnees", function (event, data) {
            var url = window.location.href;
            var urlRedirect = url.replace('dossier', 'voir')
            window.location = urlRedirect;
        });


    })
    ;
</script>
