<?php echo $this->messenger()->addCurrentMessagesFromFlashMessenger(); ?>

<div class="panel panel-default">
    <div class="panel-heading">Rechercher agent SIHAM</div>
    <div class="panel-body">
        <form action="" method="post">
            <div class="form-group">
                <label for="">Nom</label>
                <input class="form-control" type="text" name="nomUsuel" value=""/>
            </div>
            <div class="form-group">
                <label for="">Prénom</label>
                <input class="form-control" type="text" name="prenom" value=""/>
            </div>
            <button type="submit" class="btn btn-default">Rechercher</button>
        </form>
    </div>
</div>

<div>
    <table class="table table-bordered">
        <thead>
        <th>Nom</th>
        <th>Prenom</th>
        <th>Matricule</th>
        <th>Numéro harpége</th>
        <th>Date de naissance</th>
        </thead>
        <tbody>
        <?php
        /**
         * @var \UnicaenSiham\Entity\Agent $agent
         */
        ?>
        <?php foreach ($agents as $agent): ?>
            <tr>
                <td><?= $agent->getNomUsuel() ?></td>
                <td><?= $agent->getPrenom() ?></td>
                <td><?= $agent->getMatricule() ?></td>
                <td><?= $agent->getNumDossierHarpege() ?></td>
                <td><?= $agent->getDateNaissance() ?></td>
                <td><a href="/siham/voir-agent/<?= $agent->getMatricule() ?>">Voir données persos</a></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="panel panel-default">
    <div class="panel-heading">Lister les nomenclatures :</div>
    <div class="panel-body">
        <ul class="list-group">
            <li class="list-group-item"><a href="/siham/voir-nomenclature/HJB">Nomenclature des grades</a></li>
            <li class="list-group-item"><a href="/siham/voir-nomenclature/HJV">Nomenclature des corps</a></li>
            <li class="list-group-item"><a href="/siham/voir-nomenclature/VSP">Nomenclature des section CNU, BAP et
                    REFERENS</a></li>
            <li class="list-group-item"><a href="/siham/voir-nomenclature/HIS">Nomenclature des spécialités</a></li>
            <li class="list-group-item"><a href="/siham/voir-nomenclature/VFP">Nomenclature des famille professionnelle</a>
            </li>
            <li class="list-group-item"><a href="/siham/voir-nomenclature/HJK">Nomenclature des qualité statutaire</a></li>
            <li class="list-group-item"><a href="/siham/voir-nomenclature/HKE">Nomenclature des catégories</a></li>
            <li class="list-group-item"><a href="/siham/voir-nomenclature/UIP">Nomenclature des types de contrat</a></li>
            <li class="list-group-item"><a href="/siham/voir-nomenclature/HJ8">Nomenclature des types de statut</a></li>
            <li class="list-group-item"><a href="/siham/voir-nomenclature/UHU">Nomenclature des types de modalité de
                    service</a></li>
            <li class="list-group-item"><a href="/siham/voir-nomenclature/UHU">Nomenclature des types de modalité de
                    service</a></li>
            <li class="list-group-item"><a href="/siham/voir-nomenclature/HKK">Nomenclature des types de positions</a></li>
            <li class="list-group-item"><a href="/siham/voir-nomenclature/HKM">Nomenclature modes accés échelons</a></li>
            <li class="list-group-item"><a href="/siham/voir-nomenclature/HKL">Nomenclature modes accés grades</a></li>
            <li class="list-group-item"><a href="/siham/voir-nomenclature/UAA">Nomenclature des codes administrations</a></li>
            <li class="list-group-item"><a href="/siham/voir-nomenclature/DRE">Nomenclature des codes établissements</a></li>
        </ul>
    </div>
</div>


<div class="panel panel-default">
    <div class="panel-heading">Divers :</div>
    <div class="panel-body">
        <ul class="list-group">
            <li class="list-group-item"><a href="/siham/liste-intervenant-pec">Liste des intervenants à prendre en charge</a>
            </li>
        </ul>
    </div>
</div>