<?php echo $this->messenger()->addCurrentMessagesFromFlashMessenger(); ?>

<div class="panel panel-default">
    <div class="panel-heading">Rechercher agent SIHAM</div>
    <div class="panel-body">
        <form action="" method="post">
            <div class="form-group">
                <label for="">Nom</label>
                <input class="form-control" type="text" name="nomUsuel" value=""/>
            </div>
            <div class="form-group">
                <label for="">Prénom</label>
                <input class="form-control" type="text" name="prenom" value=""/>
            </div>
            <button type="submit" class="btn btn-default">Rechercher</button>
        </form>
    </div>
</div>

<div>
    <table class="table table-bordered">
        <thead>
        <th>Nom</th>
        <th>Prenom</th>
        <th>Matricule</th>
        <th>Numéro harpége</th>
        <th>Date de naissance</th>
        </thead>
        <tbody>
        <?php
        /**
         * @var \UnicaenSiham\Entity\Agent $agent
         */
        ?>
        <?php foreach ($agents as $agent): ?>
            <tr>
                <td><?= $agent->getNomUsuel() ?></td>
                <td><?= $agent->getPrenom() ?></td>
                <td><?= $agent->getMatricule() ?></td>
                <td><?= $agent->getNumDossierHarpege() ?></td>
                <td><?= $agent->getDateNaissance() ?></td>
                <td><a href="/siham/voir-agent/<?= $agent->getMatricule() ?>">Voir données persos</a></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="panel panel-default">
    <div class="panel-heading">Rechercher agent SIHAM</div>
    <div class="panel-body">
        <ul class="list-group">
            <li class="list-group-item"><a href="/siham/voir-nomenclature/HJB">Nomenclature des grades</a></li>
            <li class="list-group-item">Dapibus ac facilisis in</li>
            <li class="list-group-item">Morbi leo risus</li>
            <li class="list-group-item">Porta ac consectetur ac</li>
            <li class="list-group-item">Vestibulum at eros</li>
        </ul>
    </div>
</div>