<?php echo $this->messenger()->addCurrentMessagesFromFlashMessenger(); ?>

<?php
/**
 * @var \Application\Entity\Db\IntervenantDossier $dossierIntervenant
 */
?>


<div class="panel panel-default">
    <div class="panel-heading">Résumé du dossier intervenant
        de <?= $intervenant->getPrenom() . ' ' . $intervenant->getNomUsuel() ?></div>
    <div class="panel-body">
        <div class="row">
            <div class="col-md-6">
                <h4>IDENTITE</h4>
                <strong>Civilite :</strong> <?= $dossierIntervenant->getCivilite() ?><br/>
                <strong>Nom :</strong> <?= $dossierIntervenant->getNomUsuel() ?><br/>
                <strong>Nom de naissance :</strong> <?= $dossierIntervenant->getNomPatronymique() ?><br/>
                <strong>Prénom :</strong> <?= $dossierIntervenant->getPrenom() ?><br/>
                <strong>Ville de naissance :</strong> <?= $dossierIntervenant->getCommuneNaissance() ?><br/>
                <strong>Pays de naissance :</strong> <?= $dossierIntervenant->getPaysNaissance() ?><br/>
                <strong>Nationalité :</strong> <?= $dossierIntervenant->getPaysNationalite() ?><br/>
            </div>
            <div class="col-md-6">
                <h4>ADRESSE</h4>
                <?php
                $adresse = '';
                $adresse .= (!empty($dossierIntervenant->getAdresseNumero())) ? $dossierIntervenant->getAdresseNumero() . ' ' : '';
                $adresse .= (!empty($dossierIntervenant->getAdresseNumeroCompl())) ? $dossierIntervenant->getAdresseNumeroCompl() . ' ' : '';
                $adresse .= (!empty($dossierIntervenant->getAdresseVoirie())) ? $dossierIntervenant->getAdresseVoirie() . ' ' : '';
                $adresse .= (!empty($dossierIntervenant->getAdresseVoie())) ? $dossierIntervenant->getAdresseVoie() . ' ' : '';
                $adresse .= (!empty($dossierIntervenant->getAdressePrecisions())) ? '<br/>' . $dossierIntervenant->getAdressePrecisions() . ' ' : '';
                $adresse .= '<br/>';
                $adresse .= $dossierIntervenant->getAdresseCodePostal() . ' ' . $dossierIntervenant->getAdresseCommune();
                echo $adresse;
                ?>
                <br/>
                <?= $dossierIntervenant->getAdressePays() ?>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <h4>COORDONNEES :</h4>
                <strong>Email pro :</strong> <?= $dossierIntervenant->getEmailPro() ?><br/>
                <strong>Email perso :</strong> <?= $dossierIntervenant->getEmailPro() ?><br/>
                <strong>Téléphone pro :</strong> <?= $dossierIntervenant->getTelPro() ?><br/>
                <strong>Téléphone perso :</strong> <?= $dossierIntervenant->getTelPerso() ?><br/>
            </div>
            <div class="col-md-6">
                <h4>INSEE et IBAN</h4>
                <strong>Numéro INSEE : </strong><?= $dossierIntervenant->getNumeroInsee() ?><br/>
                <strong>Numéro provisoire : </strong><?= ($dossierIntervenant->getNumeroInseeProvisoire() == 0) ? 'NON' : 'OUI' ?><br/>
                <strong>IBAN : </strong><?= $dossierIntervenant->getIBAN() ?><br/>
                <strong>BIC : </strong><?= $dossierIntervenant->getBIC() ?><br/>
            </div>
        </div>
        <br/>
        <div class="row">
            <div class="col-md-12">
                <a class="btn btn-info" href="<?= $this->url('intervenant/voir', ['intervenant' => 'code:' . $dossierIntervenant->getIntervenant()->getCode()]); ?>" role="button">
                    Voir le dossier de <?= $dossierIntervenant->getNomUsuel() . ' ' . $dossierIntervenant->getPrenom() ?>
                </a>
            </div>
        </div>
    </div>
</div>
<div class="panel panel-default">
    <div class="panel-heading">Paramétrage de la prise en charge
        de <?= $intervenant->getPrenom() . ' ' . $intervenant->getNomUsuel() ?></div>
    <div class="panel-body">
        <form action="" method="post">

            <div class="form-group">
                <label for="">Année universitaire de prise en charge : </label>
                <select name="anneeUniversitaire" class="form-control">
                    <option value="2020-09-01">2020/2021</option>
                    <option value="2021-09-01">2021/2022</option>
                </select>
            </div>
            <div class="form-group">
                <label for="">Statut du vacataire : </label>
                <select name="statut" class="form-control">
                    <?php foreach ($statuts as $code => $libelle): ?>
                        <option value="<?= $code ?>"> <?= $libelle ?></option>
                    <?php endforeach; ?>
                </select>
            </div>
            <div class="form-group">
                <label for="">Type d'emploi : </label>
                <select name="emploi" class="form-control">
                    <option value="UCNVCE">Vacataire chargé d'enseignement</option>
                    <option value="UCNVA">Vacataire administratif</option>
                </select>
            </div>

            <div class="form-group">
                <label for="">Affectation : </label>
                <select name="uo" class="form-control">
                    <?php foreach ($uo as $value): ?>
                        <option value="<?= $value->codeUO ?>"> <?= $value->libLongUO ?></option>
                    <?php endforeach; ?>
                </select>
            </div>
            <div class="form-group">
                <label for="">Services : </label>
                <select name="modaliteService" class="form-control">
                    <option value="MS100">Temps plein</option>
                </select>
            </div>

            <div class="form-group">
                <label for="">Position Administrative : </label>
                <select name="position-administrative" class="form-control">
                    <option value="ACI01">Affecté dans l'administration</option>
                </select>
            </div>


    </div>
</div>

<button type="submit" class="btn btn-default">Demander la prise en charge</button>


</form>




