<?php echo $this->messenger()->addCurrentMessagesFromFlashMessenger(); ?>

<?php
/**
 * @var \Application\Entity\Db\IntervenantDossier $dossierIntervenant
 */
?>


<form action="" method="post">
    <div class="panel panel-default">
        <div class="panel-heading">Dossier Intervenant
            de <?= $intervenant->getPrenom() . ' ' . $intervenant->getNomUsuel() ?></div>
        <div class="panel-body">
            <div class="form-group">
                <label for="">Civilite : </label>
                <input id="disabledInput" class="form-control" type="text" name="civilite"
                       value="<?= $dossierIntervenant->getCivilite() ?>"/>
            </div>
            <div class="form-group">
                <label for="">nom : </label>
                <input id="disabledInput" class="form-control" type="text" name="nomUsuel"
                       value="<?= $dossierIntervenant->getNomUsuel() ?>"/>
            </div>
            <div class="form-group">
                <label for="">Prénom : </label>
                <input id="disabledInput" class="form-control" type="text" name="prenom"
                       value="<?= $dossierIntervenant->getPrenom() ?>"/>
            </div>
            <div class="form-group">
                <label for="">Date de naissance : </label>
                <input id="disabledInput" class="form-control" type="text" name="dateNaissance"
                       value="<?= $dossierIntervenant->getDateNaissance()->format('Y-m-d') ?>"/>
            </div>
            <div class="form-group">
                <label for="">Ville naissance : </label>
                <input id="disabledInput" class="form-control" type="text" name="villeNaissance"
                       value="<?= $dossierIntervenant->getCommuneNaissance() ?>"/>
            </div>
            <div class="form-group">
                <label for="">Département naissance : </label>
                <input id="disabledInput" class="form-control" type="text" name="departementNaissance"
                       value="<?= $dossierIntervenant->getDepartementNaissance() ?>"/>
            </div>
            <div class="form-group">
                <label for="">Emploi : </label>
                <select name="emploi" class="form-control">
                    <option value="UCNVCE">Vacataire chargé d'enseignement</option>
                    <option value="UCNVA">Vacataire administratif</option>
                </select>
            </div>
            <div class="form-group">
                <label for="">Unité organisationelle : </label>
                <select name="uo" class="form-control">
                    <?php foreach ($uo as $value): ?>
                        <option value="<?= $value->codeUO ?>"> <?= $value->libLongUO ?></option>
                    <?php endforeach; ?>
                </select>
            </div>
            <div class="form-group">
                <label for="">Position Administrative : </label>
                <select name="position-administrative" class="form-control">
                    <option value="DEL06">Délégation mission étude/exercer enseignement</option>
                </select>
            </div>


        </div>
    </div>

    <button type="submit" class="btn btn-default">Lance la PEC</button>

</form>



