<?php echo $this->messenger()->addCurrentMessagesFromFlashMessenger(); ?>

<?php
/**
 * @var \Application\Entity\Db\IntervenantDossier $dossierIntervenant
 */
?>


<div class="panel panel-default">
    <div class="panel-heading">Résumé du dossier intervenant
        de <?= $intervenant->getPrenom() . ' ' . $intervenant->getNomUsuel() ?></div>
    <div class="panel-body">
        <div class="row">
            <div class="col-md-6">
                <h4>Identité</h4>
                <strong>Civilite :</strong> <?= $dossierIntervenant->getCivilite() ?><br/>
                <strong>Nom :</strong> <?= $dossierIntervenant->getNomUsuel() ?><br/>
                <strong>Nom de naissance :</strong> <?= $dossierIntervenant->getNomPatronymique() ?><br/>
                <strong>Prénom :</strong> <?= $dossierIntervenant->getPrenom() ?><br/>
            </div>
            <div class="col-md-6">
                <h4>Adresse</h4>
                <?php
                $adresse = '';
                $adresse .= (!empty($dossierIntervenant->getAdresseNumero())) ? $dossierIntervenant->getAdresseNumero() . ' ' : '';
                $adresse .= (!empty($dossierIntervenant->getAdresseNumeroCompl())) ? $dossierIntervenant->getAdresseNumeroCompl() . ' ' : '';
                $adresse .= (!empty($dossierIntervenant->getAdresseVoirie())) ? $dossierIntervenant->getAdresseVoirie() . ' ' : '';
                $adresse .= (!empty($dossierIntervenant->getAdresseVoie())) ? $dossierIntervenant->getAdresseVoie() . ' ' : '';
                $adresse .= (!empty($dossierIntervenant->getAdressePrecisions())) ? $dossierIntervenant->getAdressePrecisions() . ' ' : '';
                $adresse .= '<br/>';
                $adresse .= $dossierIntervenant->getAdresseCodePostal() . ' ' . $dossierIntervenant->getAdresseCommune();
                echo $adresse;

                ?>
            </div>
        </div>

    </div>
</div>
<div class="panel panel-default">
    <div class="panel-heading">Paramétrage de la prise en charge
        de <?= $intervenant->getPrenom() . ' ' . $intervenant->getNomUsuel() ?></div>
    <div class="panel-body">
        <form action="" method="post">

            <div class="form-group">
                <label for="">Date d'embauche souhaitée : </label>
                <input class="form-control" type="date" name="dateEmbauche" value="" min="2020-01-01" max="2099-12-31"/>
            </div>
            <div class="form-group">
                <label for="">Statut : </label>
                <select name="statut" class="form-control">
                    <?php foreach ($statuts as $code => $libelle): ?>
                        <option value="<?= $code ?>"> <?= $libelle ?></option>
                    <?php endforeach; ?>
                </select>
            </div>
            <div class="form-group">
                <label for="">Emploi restreint : </label>
                <select name="emploi" class="form-control">
                    <option value="UCNVCE">Vacataire chargé d'enseignement</option>
                    <option value="UCNVA">Vacataire administratif</option>
                </select>
            </div>

            <div class="form-group">
                <label for="">Unité organisationelle : </label>
                <select name="uo" class="form-control">
                    <?php foreach ($uo as $value): ?>
                        <option value="<?= $value->codeUO ?>"> <?= $value->libLongUO ?></option>
                    <?php endforeach; ?>
                </select>
            </div>
            <div class="form-group">
                <label for="">Modalité de service restreint: </label>
                <select name="modaliteService" class="form-control">
                    <option value="MS100">Temps plein</option>
                </select>
            </div>
            <div class="form-group">
                <label for="">Modalité full: </label>
                <select name="modaliteServiceFull" class="form-control">
                    <?php foreach ($modalites as $code => $libelle): ?>
                        <option value="<?= $code ?>"> <?= $libelle ?></option>
                    <?php endforeach; ?>
                </select>
            </div>
            <div class="form-group">
                <label for="">Position Administrative restreint : </label>
                <select name="position-administrative" class="form-control">
                    <option value="ACI01">Affecté dans l'administration</option>
                </select>
            </div>
            <div class="form-group">
                <label for="">Position Administrative full : </label>
                <select name="position-administrativeFull" class="form-control">
                    <?php foreach ($positions as $code => $libelle): ?>
                        <option value="<?= $code ?>"> <?= $libelle ?></option>
                    <?php endforeach; ?>
                </select>
            </div>


    </div>
</div>

<button type="submit" class="btn btn-default">Lance la PEC</button>

</form>



