<?php echo $this->messenger()->addCurrentMessagesFromFlashMessenger(); ?>


<div>
    <table class="table table-bordered">
        <thead>
        <th>Code nomenclature</th>
        <th>Libellé long</th>

        </thead>
        <tbody>
        <?php
        /**
         * @var \UnicaenSiham\Entity\Agent $agent
         */
        ?>
        <?php foreach ($result as $item): ?>
            <tr>
                <td><?= $item->codeNomenclature ?></td>
                <td><?= $item->libLongNomenclature ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>