<?php echo $this->messenger()->addCurrentMessagesFromFlashMessenger(); ?>

<?php
/**
 * @var \UnicaenSiham\Entity\Agent $agent
 */
?>

<?php if (!empty($agent)): ?>
    <form action="" method="post">
        <div class="panel panel-default">
            <div class="panel-heading">Données personnelles
                de <?= $agent->getPrenom() . ' ' . $agent->getNomUsuel() ?></div>
            <div class="panel-body">
                <div class="form-group">
                    <label for="">Matricule : </label>
                    <input id="disabledInput" class="form-control" type="text" name="matricule"
                           value="<?= $agent->getMatricule() ?>"/>
                </div>
                <div class="form-group">
                    <label for="">Nom Usuel : </label>
                    <input class="form-control" type="text" name="nomUsuel" value="<?= $agent->getNomUsuel() ?>"/>
                </div>
                <div class="form-group">
                    <label for="">Prénom : </label>
                    <input class="form-control" type="text" name="prenom" value="<?= $agent->getPrenom() ?>"/>
                </div>
                <div class="form-group">
                    <label for="">Date de naissance : </label>
                    <input class="form-control" type="text" name="dateNaissance" value="<?= $agent->getDateNaissance() ?>"/>
                </div>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading">Adresse principale
                de <?= $agent->getPrenom() . ' ' . $agent->getNomUsuel() ?></div>
            <div class="panel-body">
                <div class="form-group">
                    <label for="">Numero de voie : </label>
                    <input class="form-control" type="text" name="noVoieAdresse" value="<?= $agent->getNoVoieAdresse() ?>"/>
                </div>
                <div class="form-group">
                    <label for="">Nature voie : </label>
                    <input class="form-control" type="text" name="natureVoieAdresse"
                           value="<?= $agent->getNatureVoieAdresse() ?>"/>
                </div>
                <div class="form-group">
                    <label for="">Nom de la voie : </label>
                    <input class="form-control" type="text" name="nomVoieAdresse" value="<?= $agent->getNomVoieAdresse() ?>"/>
                </div>
                <div class="form-group">
                    <label for="">Complement adresse : </label>
                    <input class="form-control" type="text" name="complementAdresse"
                           value="<?= $agent->getComplementAdresse() ?>"/>
                </div>
                <div class="form-group">
                    <label for="">Code postal : </label>
                    <input class="form-control" type="text" name="codePostal" value="<?= $agent->getCodePostalAdresse() ?>"/>
                </div>
                <div class="form-group">
                    <label for="">Ville : </label>
                    <input class="form-control" type="text" name="ville"
                           value="<?= $agent->getBureauDistributeurAdresse() ?>"/>
                </div>
                <div class="form-group">
                    <label for="">Date début : </label>
                    <input class="form-control" type="text" name="dateDebut"
                           value="<?= $agent->getDateDebutAdresse() ?>"/>
                </div>
                <div class="form-group">
                    <label for="">Date fin : </label>
                    <input class="form-control" disabled="disabled" type="text" name="dateFin"
                           value="<?= $agent->getDateFinAdresse() ?>"/>
                </div>
                <div>
                    <button type="submit" class="btn btn-default">Ajouter une adresse</button>
                    <a class="btn btn-warning" href="/siham/historiser-adresse/<?= $agent->getMatricule() ?>" role="button">Historiser
                        adresse principale</a>
                </div>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading">Numéros de téléphone et Emails
                de <?= $agent->getPrenom() . ' ' . $agent->getNomUsuel() ?></div>
            <div class="panel-body">
                <div class="form-group">
                    <label for="">Téléphone fixe professionnel : </label>
                    <input class="form-control" type="text" name="telFixePro" value="<?= $agent->getTelephonePro() ?>"/>
                </div>
                <div class="form-group">
                    <input class="form-control" type="hidden" disabled="disabled" name="telFixeProDateDebut"
                           value="<?= $agent->getTelephoneProDateDebut() ?>"/>
                </div>
                <div class="form-group">
                    <input class="form-control" type="hidden" disabled="disabled" name="telFixeProDateFin"
                           value="<?= $agent->getTelephoneProDateFin() ?>"/>
                </div>
                <div class="form-group">
                    <label for="">Téléphone portable perso : </label>
                    <input class="form-control" type="text" name="telPortablePerso"
                           value="<?= $agent->getTelephonePerso() ?>"/>
                </div>
                <div class="form-group">
                    <input class="form-control" type="hidden" disabled="disabled" name="telPortablePersoDateDebut"
                           value="<?= $agent->getTelephonePersoDateDebut() ?>"/>
                </div>
                <div class="form-group">
                    <input class="form-control" type="hidden" disabled="disabled" name="telPortablePersoDateFin"
                           value="<?= $agent->getTelephonePersoDateFin() ?>"/>
                </div>
                <div class="form-group">
                    <label for="">Email pro : </label>
                    <input class="form-control" type="text" name="emailPro"
                           value="<?= $agent->getEmailPro() ?>"/>
                </div>
                <div class="form-group">
                    <input class="form-control" type="hidden" disabled="disabled" name="emailProDateDebut"
                           value="<?= $agent->getEmailProDateDebut() ?>"/>
                </div>
                <div class="form-group">
                    <input class="form-control" type="hidden" disabled="disabled" name="emailProDateFin"
                           value="<?= $agent->getEmailProDateFin() ?>"/>
                </div>
                <div class="form-group">
                    <label for="">Email perso : </label>
                    <input class="form-control" type="text" name="emailPerso"
                           value="<?= $agent->getEmailPerso() ?>"/>
                </div>
                <div class="form-group">
                    <input class="form-control" type="hidden" disabled="disabled" name="emailPersoDateDebut"
                           value="<?= $agent->getEmailPersoDateDebut() ?>"/>
                </div>
                <div class="form-group">
                    <input class="form-control" type="hidden" disabled="disabled" name="emailPersoDateFin"
                           value="<?= $agent->getEmailPersoDateFin() ?>"/>
                </div>
            </div>
        </div>
        <button type="submit" class="btn btn-default">Sauvegarder les modifications</button>
        <a class="btn btn-warning" href="/siham/renouveller-agent/<?= $agent->getMatricule() ?>" role="button">Renouveller
            Agent</a>
        <a class="btn btn-warning" href="/siham/prise-en-charge-agent" role="button">Prise en charge
            Agent</a>
    </form>


<?php endif; ?>
