<?php echo $this->messenger()->addCurrentMessagesFromFlashMessenger(); ?>


<div>
    <table class="table table-bordered table-condensed table-hover table-sort">
        <thead>
        <th>Code nomenclature</th>
        <th>Libellé long</th>

        </thead>
        <tbody>
        <?php
        /**
         * @var \UnicaenSiham\Entity\Agent $agent
         */
        ?>
        <?php foreach ($result as $code => $libelle): ?>
            <tr>
                <td><?= $code ?></td>
                <td><?= $libelle ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>