<h1>Import de données</h1>

<style>
    dt{
        padding-top:2em;
    }
</style>

<dl>
    <dt><a href="<?php echo $this->url('import', array('action' => 'showDiff')) ?>">Écarts entre OSE et ses sources</a></dt>
    <dd>Affiche, table par table, la liste des données différentes entre OSE et ses sources de données</dd>

    <dt><a id="updateAllData" href="<?php echo $this->url('import', array('action' => 'updateAllData')) ?>">
        Mise à jour des données OSE à partir de leurs sources
    </a></dt>
    <dd>Met à jour l'ensemble des données d'OSE à partir de leurs sources respectives.
    </dd>

    <dt><a href="<?php echo $this->url('import', array('action' => 'showImportTbl')) ?>">Tableau de bord principal</a></dt>
    <dd>Liste, table par table, les colonnes dont les données sont importables ou non, leur caractéristiques et l'état de l'import à leur niveau</dd>

    <dt><a id="updateViewsAndPackages" href="<?php echo $this->url('import', array('action' => 'updateViewsAndPackages')) ?>">
        Mise à jour des vues différentielles et des procédures de mise à jour
    </a></dt>
    <dd>Réactualise les vues différentielles d'import. Ces dernières servent à déterminer quelles données ont changé,
        sont apparues ou ont disparues des sources de données.
        Met également à jour les procédures de mise à jour qui actualisent les données OSE à partir des informations
        fournies par les vues différentielles.
        Cette réactualisation n'est utile que si les vues sources ont été modifiées.
    </dd>
</dl>

<div id="dialog" class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">Titre</h4>
      </div>
      <div class="modal-body">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">OK</button>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">

    function makeDialog( aId, dialogId ){
        var aid = 'updateViewsAndPackages';
        $('a#'+aId).click(function(){
            $('div#'+dialogId).find('h4.modal-title').html( $('a#'+aId).html() );
            $('div#'+dialogId).find('div.modal-body').html('En cours de chargement ...');
            $('div#'+dialogId).modal();
            $.get( $('a#'+aId).attr('href'), function( data ) {
                $('div#'+dialogId).find('div.modal-body').html(data);
            });
            return false;
        });
    }


    makeDialog( 'updateViewsAndPackages', 'dialog');
    makeDialog( 'updateAllData', 'dialog');

</script>