<h1>Écarts entre OSE et ses sources</h1>

<?php foreach( $data as $table => $lignes ):
    $tableLabel = ucwords(str_replace( '_', ' ', strtolower($table)));
?>
<h2><?php echo $tableLabel ?></h2>
<div id="DIV_<?php echo $table ?>" data-url="<?php echo $this->url('import', array('action' => 'update','table' => $table)) ?>">
<?php echo $this->differentielListe( $lignes ); ?>

<?php if (count($lignes) > 100) : ?>
<div>Toutes les lignes n'ont pas été affichées, leur nombre dépassant 100</div>
<?php endif; ?>

<?php if (count($lignes) > 0) : ?>
<div>
    <a class="import-update" href="javascript:void(0)" data-table="<?php echo $table ?>">
        <span class="glyphicon glyphicon-refresh"></span>
        Mettre à jour les données
    </a>
</div>
<?php endif; ?>
</div>
<?php endforeach; ?>

<script>
    $(function() {

        $("body").on("click", "a.import-update", function(e) {
             $( "#DIV_"+$(this).data('table') ).refresh();
        });

    });
</script>