<?php foreach( $data as $table => $lignes ): ?>
<?php echo $this->differentielListe( $lignes ); ?>
<?php if (count($lignes) > 100) : ?>
<div>Toutes les lignes n'ont pas été affichées, leur nombre dépassant 100</div>
<?php endif; ?>

<?php if (count($lignes) > 0) : ?>
<div>
    <a class="ajax-modal" href="<?php echo $this->url('import', array('action' => 'updateTables', 'table' => $table)) ?>" data-table="<?php echo $table ?>">
        <span class="glyphicon glyphicon-refresh"></span>
        Mettre à jour les données
    </a>
</div>
<?php endif; ?>

<?php endforeach; ?>