<h1>Écarts entre OSE et ses sources</h1>

<?php foreach( $data as $table => $lignes ):
    $tableLabel = ucwords(str_replace( '_', ' ', strtolower($table)));
?>
<h2><?php echo $tableLabel ?></h2>
<div id="DIV_<?php echo $table ?>" data-url="<?php echo $this->url('import', array('action' => 'update','table' => $table)) ?>">
<?php echo $this->differentielListe( $lignes ); ?>

<?php if (count($lignes) > 100) : ?>
<div>Toutes les lignes n'ont pas été affichées, leur nombre dépassant 100</div>
<?php endif; ?>

<div>
    <a class="import-update-mv" href="javascript:void(0)" data-table="<?php echo $table ?>">
        <span class="glyphicon glyphicon-refresh"></span>
        Mettre à jour la vue matérialisée
    </a>
<?php if (count($lignes) > 0) : ?>
    &nbsp;&nbsp;<a class="import-update" href="javascript:void(0)" data-table="<?php echo $table ?>">
        <span class="glyphicon glyphicon-refresh"></span>
        Mettre à jour les données
    </a>
<?php endif; ?>
</div>
<div class="alert alert-info" role="alert" id="DIV_WAIT_<?php echo $table ?>" style="display:none">
    <img src="<?php echo $this->basePath('loading.gif') ?>" />
    Traitement en cours, merci de patienter. L'opération peut prendre jusqu'à plusieurs minutes.
</div>
</div>
<?php endforeach; ?>

<script>
    $(function() {

        $("body").on("click", "a.import-update-mv", function(e) {
            $( "#DIV_WAIT_"+$(this).data('table') ).show();
            $( "#DIV_"+$(this).data('table') ).refresh({'type-maj': 'vue-materialisee'});
        });

        $("body").on("click", "a.import-update", function(e) {
            $( "#DIV_WAIT_"+$(this).data('table') ).show();
            $( "#DIV_"+$(this).data('table') ).refresh({'type-maj': 'donnees'});
        });

    });
</script>