<?php echo $this->differentielListe( $lignes ); ?>
<?php if (count($lignes) > 100) : ?>
<div>Toutes les lignes n'ont pas été affichées, leur nombre dépassant 100</div>
<?php endif; ?>

<?php if (count($lignes) > 0) : ?>
<div>
    <a class="import-update" href="javascript:void(0)" data-table="<?php echo $table ?>">
        <span class="glyphicon glyphicon-refresh"></span>
        Mettre à jour les données
    </a>
</div>
<?php endif; ?>
<?php

if ($errors){
    echo $this->messenger()->setMessages(array(UnicaenApp\View\Helper\Messenger::ERROR => array($errors)));
}else{
    echo $this->messenger()->setMessages(array(UnicaenApp\View\Helper\Messenger::SUCCESS => array('Synchronisation réalisée avec succès')));
}