<?php

/* @var $form Application\Form\DisciplineForm */
/* @var $errors array */


echo $this->form()->openTag($form->prepare());

if ($errors) {
    echo $this->messenger()->setMessages([UnicaenApp\View\Helper\Messenger::ERROR => $errors]);
}

echo $this->formControlGroup($form->get('source-code'));
echo $this->formControlGroup($form->get('libelle-long'));
echo $this->formControlGroup($form->get('libelle-court'));
echo $this->formRow($form->get('submit'));
echo $this->formHidden($form->get('id'));

echo $this->form()->closeTag();