<?php
/**
 * @var $this              \Application\View\Renderer\PhpRenderer
 */

use Application\Entity\Db\WfEtape;
use Mission\Entity\Db\MissionTauxRemu;
use Mission\Entity\Db\MissionTauxRemuValeur;


$this->headTitle()->append("Gestion des taux de missions");
echo $this->messenger()->addCurrentMessagesFromFlashMessenger();

echo '<hr />';
?>
<h1 class="page-header">Gestion des taux de missions</h1>

<?php foreach ($tauxMissions as $tauxMission):
    /** @var MissionTauxRemu $tauxMission */ ?>
    <div class="card bg-default">
        <div class="card-header"><?= $tauxMission->getLibelle(); ?> (<?= $tauxMission->getCode(); ?>)
            <div class="float-end">
                <a class="ajax-modal " data-event="type-formation-edition"
                   href="<?= $this->url(null, ['tauxMission' => $tauxMission->getId()]) ?>"
                   title="Modifier la collection"><i class="fas fa-pen-to-square"></i></a>

                <a class="pop-ajax " data-title="Suppression d'une collection" data-content="Êtes-vous sur de vouloir supprimer"
                   data-confirm="true"
                   data-submit-reload="true"
                   href="<?= $this->url(null, ['tauxMission' => $tauxMission->getId()]) ?>"
                   title="Supprimer la collection"><i class="fas fa-trash-can"></i></a>

            </div>
        </div>

        <table class="table table-bordered table-sm">
            <thead>
            <tr>
                <th style="text-align: center">Valeur</th>
                <th style="text-align: center">Date début</th>
            </tr>
            </thead>
            <tbody>

            <?php $tauxRemuValeurs = $tauxMission->getTauxRemuValeurs();
            foreach ($tauxRemuValeurs as $tauxRemuValeur):
                /** @var MissionTauxRemuValeur $tauxRemuValeur */ ?>
                <tr>
                    <td style="text-align: center"><?php echo $tauxRemuValeur->getValeur() ?></td>
                    <?php $newDate = $tauxRemuValeur->getDateEffet()->format('d/m/Y'); ?>
                    <td style="text-align: center"><?php echo $newDate ?></td>
                </tr>
            <?php endforeach; ?>

            </tbody>
        </table>
        <div class="card-body">
            <div>
                <button class="btn btn-primary w-25">
                    Ajouter une valeur
                </button>
            </div>
        </div>
    </div>

<?php endforeach; ?>
