<?php
/**
 * @var $this                \Application\View\Renderer\PhpRenderer
 * @var $domaineFonctionnels \Paiement\Entity\Db\DomaineFonctionnel[]
 */

use Application\Provider\Privileges;

$this->headTitle()->append("Domaines fonctionnels");

$canEdit = $this->isAllowed(Privileges::getResourceId(Privileges::DOMAINES_FONCTIONNELS_ADMINISTRATION_EDITION));

?>
<h1 class="page-header">Domaines fonctionnels</h1>

<table class="table table-bordered table-sort">
    <thead>
    <th style="word-wrap: break-word ; ">Libelle</th>
    <th style="word-wrap: break-word ; ">Source</th>
    <th style="word-wrap: break-word ; ">Source Code</th>
    <?php if ($canEdit) echo '<th>Actions</th>' ?>
    </thead>
    <tbody>
    <?php foreach ($domaineFonctionnels as $fr): ?>
        <tr>
            <td style="word-wrap: break-word ; "><?= $fr->getLibelle() ?></td>
            <td style="word-wrap: break-word ; "><?= $fr->getSource() ?></td>
            <td style="word-wrap: break-word ; "><?= $fr->getSourceCode() ?></td>
            <?php if (($canEdit) && ($fr->getSource() == 'OSE')) { ?>
                <td style="text-align:center;width:1px;white-space: nowrap">
                    <a class="ajax-modal" data-event="domaine-fonctionnel-saisie"
                       href="<?= $this->url('domaine-fonctionnel/saisie', ['domaineFonctionnel' => $fr->getId()]) ?>"
                       title="Modifier la DomaineFonctionnel">
                        <i class="fas fa-pen-to-square"></i></a>
                    <a class="pop-ajax"
                       href="<?= $this->url('domaine-fonctionnel/delete', ['domaineFonctionnel' => $fr->getId()]) ?>"
                       title="Supprimer la DomaineFonctionnel"
                       data-content="<p class='lead text-danger'><strong>Attention!</strong> Confirmez-vous cette suppression ?</p>"
                       data-confirm="true"
                       data-confirm-button="Oui"
                       data-cancel-button="Non"
                       data-submit-reload="true"
                    >
                        <i class="fas fa-trash-can"></i>
                    </a>
                </td>
            <?php } else { ?>
                <td></td>
            <?php } ?>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<?php if ($canEdit): ?>
    <a class="btn btn-primary ajax-modal" data-event="domaine-fonctionnel-saisie"
       href="<?= $this->url('domaine-fonctionnel/saisie') ?>"
       title="Ajouter une domaine fonctionnel">
        <i class="fas fa-pen-to-square"></i>
        Ajouter un domaine fonctionnel</a>

    <script type="text/javascript">
        $(function () {
            $("body").on("domaine-fonctionnel-saisie", function (event, data) {
                window.location.reload();
            });
        });
    </script>
<?php endif ?>
