<?php
/**
 * @var $this  \Application\View\Renderer\PhpRenderer
 * @var $form  \Application\Form\DomaineFonctionnel\DomaineFonctionnelSaisieForm
 */
echo $this->messenger()->addCurrentMessagesFromFlashMessenger();

echo $this->form()->openTag($form); ?>

<div class="row">
    <div class="col-md-3">
        <?= $this->formControlGroup($form->get('source-code')); ?>
    </div>
    <div class="col-md-9">
        <?= $this->formControlGroup($form->get('libelle')); ?>
    </div>
</div>
<?= $this->formControlGroup($form->get('source')); ?>

<?= $this->formControlGroup($form->get('security')); ?>
<?= $this->formSubmit($form->get('submit')); ?>
<?= $this->form()->closeTag(); ?>
