<?php

/**
 * @var $this                 \Application\View\Renderer\PhpRenderer
 * @var $title                string
 * @var $configs              \Plafond\Interfaces\PlafondConfigInterface[]
 * @var $entity               object
 * @var $canEdit              bool
 * @var $autoSave             bool
 */

$autoSave = isset($autoSave) ? $autoSave : true;

?>
<?php if ($title): ?><h1 class="page-header"><?= $title ?></h1><?php endif; ?>

<table class="table table-sm table-hover table-bordered plafonds-config">
    <thead>
    <tr>
        <th rowspan="2">Plafond</th>
        <th>Prévisionnel</th>
        <th>Réalisé</th>
        <th>Heures<sup>*</sup></th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($configs as $config): ?>
        <tr>
            <td style="width:50%"><span class="badge bg-secondary"><?= $config->getPlafond()->getNumero() ?></span> <?= $config->getPlafond() ?></td>
            <td><?= $this->plafondConfig($config)->etatPrevu($canEdit); ?></td>
            <td><?= $this->plafondConfig($config)->etatRealise($canEdit); ?></td>
            <td><?= $this->plafondConfig($config)->heures($canEdit); ?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<?php if ($autoSave): ?>
    <?= $this->plafondConfig()->script($entity); ?>
    <a href="<?= $this->url('plafond/construire-calculer') ?>" class="btn btn-info pop-ajax">Construction & calcul de tous les plafonds</a>
<?php endif; ?>
