<?php

/**
 * @var $this \Application\View\Renderer\PhpRenderer
 * @var $form PlafondApplicationForm
 */

use Application\Form\Plafond\PlafondApplicationForm;

?>
    <h1 class="page-header"><?= $title ?></h1>
<?php

echo $this->messenger()->addCurrentMessagesFromFlashMessenger();

echo $this->form()->openTag($form->prepare());
echo $this->formHidden($form->get('plafond'));
echo $this->formHidden($form->get('typeVolumeHoraire'));
?>
    <div class="row">
        <div class="col-md-12"><?= $this->formControlGroup($form->get('plafondEtat')); ?></div>
    </div>
<?php
echo $this->formRow($form->get('submit'));
if ($form->getObject()->getId()) {
    echo ' ' . $this->tag('a', [
            'class'               => 'pop-ajax btn btn-danger',
            'href'                => $this->url('plafond/supprimer-application', ['plafondApplication' => $form->getObject()->getId()]),
            'title'               => 'Supprimer la règle d\'application du plafond',
            'data-content'        => '<p class="lead text-danger"><strong>Attention!</strong> Confirmez-vous cette suppression ?</p>',
            'data-confirm'        => 'true',
            'data-confirm-button' => 'Oui',
            'data-cancel-button'  => 'Non',
            'data-submit-reload'  => 'true',
        ])->text("Supprimer la règle d'application");
}
echo $this->form()->closeTag();