<?php

use Application\Entity\Db\PlafondApplication;
use Application\Provider\Privilege\Privileges;

/**
 * @var $this                 \Application\View\Renderer\PhpRenderer
 * @var $title                string
 * @var $plafonds             PlafondApplication[]
 */

$canEdit   = $this->isAllowed(Privileges::getResourceId(Privileges::PLAFONDS_EDITION));
$canConfig = $this->isAllowed(Privileges::getResourceId(Privileges::PLAFONDS_CONFIG_APPLICATION));

?>
    <h1 class="page-header"><?= $title ?></h1>

    <table class="table table-condensed table-hover table-bordered plafonds-config">
        <thead>
        <tr>
            <th rowspan="2">Périmètre</th>
            <th rowspan="2">Plafond</th>
            <?php if ($canEdit): ?>
                <th rowspan="2">Actions</th>
            <?php endif; ?>
            <th colspan="3">Application</th>
        </tr>
        <tr>
            <th>Prévisionnel</th>
            <th>Réalisé</th>
            <th rowspan="2">Heures<sup>*</sup></th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($plafonds as $plafond): ?>
            <tr>
                <td><?= $plafond->getPlafond()->getPlafondPerimetre() ?></td>
                <td style="width:50%"><?= $plafond->getPlafond(); ?></td>
                <?php if ($canEdit): ?>
                    <td>
                        <a href="<?= $this->url('plafond/modifier', ['plafond' => $plafond->getPlafond()]) ?>" title="Modifier le plafond"><i
                                    class="fa-solid fa-pen-to-square"></i</a>
                        <a class="pop-ajax"
                           href="<?= $this->url('plafond/supprimer', ['plafond' => $plafond->getPlafond()]) ?>"
                           title="Supprimer le plafond"
                           data-content="<p class='lead text-danger'><strong>Attention!</strong> Confirmez-vous cette suppression ?</p>"
                           data-confirm="true"
                           data-confirm-button="Oui"
                           data-cancel-button="Non"
                           data-submit-reload="true"
                        >
                            <i class="fa-solid fa-trash-can"></i
                        </a>
                    </td>
                <?php endif; ?>
                <td><?= $this->plafondConfig($plafond)->etatPrevu($canConfig); ?></td>
                <td><?= $this->plafondConfig($plafond)->etatRealise($canConfig); ?></td>
                <td><?= $this->plafondConfig($plafond)->heures($canConfig); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
<?php if ($canEdit): ?>
    <a href="<?= $this->url('plafond/ajouter') ?>" class="btn btn-default">Création d'un nouveau plafond</a>
    <a href="<?= $this->url('plafond/construire-calculer') ?>" class="btn btn-info pop-ajax">Construction & calcul de tous les plafonds</a>
<?php endif; ?>
<?= $this->plafondConfig()->script() ?>