<?php

use Plafond\Entity\Db\Plafond;
use Application\Entity\Db\PlafondApplication;
use Application\Entity\Db\TypeVolumeHoraire;
use Application\Provider\Privilege\Privileges;

/**
 * @var $this                 \Application\View\Renderer\PhpRenderer
 * @var $title                string
 * @var $plafonds             Plafond[]
 * @var $typesVolumesHoraires TypeVolumeHoraire[]
 * @var $regles               PlafondApplication[][]
 */

$canApply = $this->isAllowed(Privileges::getResourceId(Privileges::PLAFONDS_APPLICATION));
$canEdit  = $this->isAllowed(Privileges::getResourceId(Privileges::PLAFONDS_EDITION));

?>
<h1 class="page-header"><?= $title ?></h1>

<table class="table table-condensed table-hover table-bordered table-sort">
    <thead>
    <tr>
        <th>Périmètre</th>
        <th>Plafond</th>
        <?php if ($canEdit): ?>
            <th>Actions</th>
        <?php endif; ?>
        <?php foreach ($typesVolumesHoraires as $typeVolumeHoraire): ?>
            <th><?= $typeVolumeHoraire ?></th>
        <?php endforeach; ?>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($plafonds as $plafond): ?>
        <tr>
            <td><?= $plafond->getPlafondPerimetre() ?></td>
            <td style="width:50%"><?= $plafond ?></td>
            <?php if ($canEdit): ?>
                <td>
                    <a href="<?= $this->url('plafond/modifier', ['plafond' => $plafond->getId()]) ?>"><span class="glyphicon glyphicon-edit"</a>
                    <a class="pop-ajax"
                       href="<?= $this->url('plafond/supprimer', ['plafond' => $plafond->getId()]) ?>"
                       title="Supprimer le plafond"
                       data-content="<p class='lead text-danger'><strong>Attention!</strong> Confirmez-vous cette suppression ?</p>"
                       data-confirm="true"
                       data-confirm-button="Oui"
                       data-cancel-button="Non"
                       data-submit-reload="true"
                    >
                        <span class="glyphicon glyphicon-trash"></span>
                    </a>
                </td>
            <?php endif; ?>
            <?php foreach ($typesVolumesHoraires as $typeVolumeHoraire): ?>
                <td style="text-align:center;width:25%"><?php

                    $regle = isset($regles[$plafond->getId()][$typeVolumeHoraire->getId()]) ? $regles[$plafond->getId()][$typeVolumeHoraire->getId()] : null;

                    if ($regle) {
                        if ($canApply) {
                            $url = $this->url('plafond/editer-application', [
                                'plafondApplication' => $regle->getId(),
                            ]);
                            echo $this->tag('a', [
                                'class'              => 'pop-ajax',
                                'href'               => $url,
                                'data-submit-reload' => 'true',
                                'data-min-width'     => '400px',
                            ])->html((string)$regle);
                        } else {
                            echo (string)$regle;
                        }
                    } else {
                        if ($canApply) {
                            $url = $this->url('plafond/editer-application', [], ['query' => [
                                'typeVolumeHoraire' => $typeVolumeHoraire->getId(),
                                'plafond'           => $plafond->getId(),
                            ]]);
                            echo $this->tag('a', [
                                'class'              => 'pop-ajax',
                                'href'               => $url,
                                'data-submit-reload' => 'true',
                                'data-min-width'     => '400px',
                            ])->html('Désactivé');
                        }
                    }

                    ?></td>
            <?php endforeach; ?>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<?php if ($canEdit): ?>
    <a href="<?= $this->url('plafond/ajouter') ?>" class="btn btn-default">Création d'un nouveau plafond</a>
    <a href="<?= $this->url('plafond/construire-calculer') ?>" class="btn btn-info pop-ajax">Construction & calcul de tous les plafonds</a>
<?php endif; ?>
