<?php

use Application\Entity\Db\Intervenant;
use Application\Entity\Db\Structure;
use Enseignement\Entity\Db\VolumeHoraire;
use OffreFormation\Entity\Db\ElementPedagogique;
use Referentiel\Entity\Db\FonctionReferentiel;

/**
 * @var $this              \Application\View\Renderer\PhpRenderer
 * @var $entity            Structure|Intervenant|ElementPedagogique|VolumeHoraire|FonctionReferentiel
 * @var $typeVolumeHoraire \Service\Entity\Db\TypeVolumeHoraire
 */

echo $this->plafonds($entity, $typeVolumeHoraire)->affichage();