<?php

use Enseignement\Entity\Db\VolumeHoraire;
use Intervenant\Entity\Db\Intervenant;
use Lieu\Entity\Db\Structure;
use OffreFormation\Entity\Db\ElementPedagogique;
use Referentiel\Entity\Db\FonctionReferentiel;

/**
 * @var $this              \Application\View\Renderer\PhpRenderer
 * @var $entity            Structure|Intervenant|ElementPedagogique|VolumeHoraire|FonctionReferentiel|TypeMission
 * @var $typeVolumeHoraire \Service\Entity\Db\TypeVolumeHoraire
 */

echo $this->plafonds($entity, $typeVolumeHoraire)->affichage();