<h1 class="page-header">Gestion des droits d'accès</h1>

<dl>
    <dt><a href="<?php echo $this->url('gestion/droits/roles') ?>">Gestion des rôles</a></dt>
    <dd>
        Permet de visualiser les rôles existants. Permet également de les modifier,
        d'en ajouter ou d'en supprimer si vous avez les droits requis pour cela.
    </dd>
    
    <dt><a href="<?php echo $this->url('gestion/droits/privileges') ?>">Gestion des privilèges</a></dt>
    <dd>
        Tableau de bord listant, par rôle, les privilèges qui lui sont accordés.
        Le tableau permet également, si vous en avez le droit, de modifier les privilèges accordés par rôle.
    </dd>
</dl>
<style>

   dt{
        padding-top:2em;
    }

</style>