CREATE TABLE UNICAEN_CORRESP_STRUCTURE_CC(
  "ID" NUMBER(*,0) NOT NULL ENABLE,
	"CODE_SIFAC" VARCHAR2(15 CHAR) NOT NULL ENABLE,
	"CODE_HARPEGE" VARCHAR2(250 CHAR) NOT NULL ENABLE,
	 CONSTRAINT "UNICAEN_CORRESP_STR_CC_PK" PRIMARY KEY ("ID")
);

Insert into UNICAEN_CORRESP_STRUCTURE_CC (ID,CODE_SIFAC,CODE_HARPEGE) values ('1','901','U01');
Insert into UNICAEN_CORRESP_STRUCTURE_CC (ID,CODE_SIFAC,CODE_HARPEGE) values ('2','902','U02');
Insert into UNICAEN_CORRESP_STRUCTURE_CC (ID,CODE_SIFAC,CODE_HARPEGE) values ('3','903','U03');
Insert into UNICAEN_CORRESP_STRUCTURE_CC (ID,CODE_SIFAC,CODE_HARPEGE) values ('4','904','U04');
Insert into UNICAEN_CORRESP_STRUCTURE_CC (ID,CODE_SIFAC,CODE_HARPEGE) values ('5','907','U07');
Insert into UNICAEN_CORRESP_STRUCTURE_CC (ID,CODE_SIFAC,CODE_HARPEGE) values ('6','908','U08');
Insert into UNICAEN_CORRESP_STRUCTURE_CC (ID,CODE_SIFAC,CODE_HARPEGE) values ('7','909','U09');
Insert into UNICAEN_CORRESP_STRUCTURE_CC (ID,CODE_SIFAC,CODE_HARPEGE) values ('8','910','U10');
Insert into UNICAEN_CORRESP_STRUCTURE_CC (ID,CODE_SIFAC,CODE_HARPEGE) values ('9','911','I11');
Insert into UNICAEN_CORRESP_STRUCTURE_CC (ID,CODE_SIFAC,CODE_HARPEGE) values ('10','912','I12');
Insert into UNICAEN_CORRESP_STRUCTURE_CC (ID,CODE_SIFAC,CODE_HARPEGE) values ('11','913','I13');
Insert into UNICAEN_CORRESP_STRUCTURE_CC (ID,CODE_SIFAC,CODE_HARPEGE) values ('12','914','U14');
Insert into UNICAEN_CORRESP_STRUCTURE_CC (ID,CODE_SIFAC,CODE_HARPEGE) values ('13','917','M17');
Insert into UNICAEN_CORRESP_STRUCTURE_CC (ID,CODE_SIFAC,CODE_HARPEGE) values ('14','920','U36');
Insert into UNICAEN_CORRESP_STRUCTURE_CC (ID,CODE_SIFAC,CODE_HARPEGE) values ('15','924','U24');
Insert into UNICAEN_CORRESP_STRUCTURE_CC (ID,CODE_SIFAC,CODE_HARPEGE) values ('16','925','U25');
Insert into UNICAEN_CORRESP_STRUCTURE_CC (ID,CODE_SIFAC,CODE_HARPEGE) values ('17','926','U26');
Insert into UNICAEN_CORRESP_STRUCTURE_CC (ID,CODE_SIFAC,CODE_HARPEGE) values ('18','945','C45');
Insert into UNICAEN_CORRESP_STRUCTURE_CC (ID,CODE_SIFAC,CODE_HARPEGE) values ('19','950','UNIV');
Insert into UNICAEN_CORRESP_STRUCTURE_CC (ID,CODE_SIFAC,CODE_HARPEGE) values ('20','953','C53');
Insert into UNICAEN_CORRESP_STRUCTURE_CC (ID,CODE_SIFAC,CODE_HARPEGE) values ('21','961','C61');
Insert into UNICAEN_CORRESP_STRUCTURE_CC (ID,CODE_SIFAC,CODE_HARPEGE) values ('22','971','U55');
Insert into UNICAEN_CORRESP_STRUCTURE_CC (ID,CODE_SIFAC,CODE_HARPEGE) values ('23','980','E01');
Insert into UNICAEN_CORRESP_STRUCTURE_CC (ID,CODE_SIFAC,CODE_HARPEGE) values ('32','drh-formation','drh-formation');
Insert into UNICAEN_CORRESP_STRUCTURE_CC (ID,CODE_SIFAC,CODE_HARPEGE) values ('27','917','14');
Insert into UNICAEN_CORRESP_STRUCTURE_CC (ID,CODE_SIFAC,CODE_HARPEGE) values ('28','903','14');
Insert into UNICAEN_CORRESP_STRUCTURE_CC (ID,CODE_SIFAC,CODE_HARPEGE) values ('25','011','11');
Insert into UNICAEN_CORRESP_STRUCTURE_CC (ID,CODE_SIFAC,CODE_HARPEGE) values ('26','012','12');
Insert into UNICAEN_CORRESP_STRUCTURE_CC (ID,CODE_SIFAC,CODE_HARPEGE) values ('31','013','13');
Insert into UNICAEN_CORRESP_STRUCTURE_CC (ID,CODE_SIFAC,CODE_HARPEGE) values ('24','014','14');
Insert into UNICAEN_CORRESP_STRUCTURE_CC (ID,CODE_SIFAC,CODE_HARPEGE) values ('33','911','15');
Insert into UNICAEN_CORRESP_STRUCTURE_CC (ID,CODE_SIFAC,CODE_HARPEGE) values ('34','912','15');
Insert into UNICAEN_CORRESP_STRUCTURE_CC (ID,CODE_SIFAC,CODE_HARPEGE) values ('35','913','15');
Insert into UNICAEN_CORRESP_STRUCTURE_CC (ID,CODE_SIFAC,CODE_HARPEGE) values ('36','015','15');
Insert into UNICAEN_CORRESP_STRUCTURE_CC (ID,CODE_SIFAC,CODE_HARPEGE) values ('29','909','13');
Insert into UNICAEN_CORRESP_STRUCTURE_CC (ID,CODE_SIFAC,CODE_HARPEGE) values ('30','925','13');
Insert into UNICAEN_CORRESP_STRUCTURE_CC (ID,CODE_SIFAC,CODE_HARPEGE) values ('37','151','15');
Insert into UNICAEN_CORRESP_STRUCTURE_CC (ID,CODE_SIFAC,CODE_HARPEGE) values ('38','152','15');
Insert into UNICAEN_CORRESP_STRUCTURE_CC (ID,CODE_SIFAC,CODE_HARPEGE) values ('39','153','15');
