<table class="table table-bordered table-condensed">
    <thead>
    <tr>
        <th style="width:40%">Libellé</th>
        <th style="width:20%">Siren</th>

    </tr>
    </thead>
    <tbody class="table-hover">
    <?php foreach ($employeurs

    as $employeur): ?>
    <tr>
        <td><?= $employeur['label']; ?></td>
        <td><?= $employeur['siren']; ?></td>
    </tr>
    </tbody>
    <?php endforeach; ?>
</table>


