<table class="table table-bordered table-sm">
<?php
$canEdit = true;
?>
<table id='table-employeur' class="table table-bordered table-sort" data-searching="false">
    <thead>
    <tr>
        <th style="width:40%">Libellé</th>
        <th style="width:20%">Siret</th>
        <th style="text-align: center">Source</th>
        <th style="text-align: center">Actions</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($employeurs as $employeur): ?>

        <tr>
            <td><?= $employeur['label']; ?></td>
            <td><?= $employeur['siret']; ?></td>
            <td style="text-align: center"><?= $employeur['source_code'] ?></td>
            <?php if ($canEdit): ?>
                <td><?php if ($employeur['source_code'] == 'OSE'): ?>
                        <a class="disabled ajax-modal" data-event="employeur-saisie"
                           href="<?= $this->url('employeur/saisie', ['employeur' => $employeur['id']]) ?>"
                           title="Modifier l'employeur">
                            <i class="fas fa-pen-to-square"></i></a>
                        <a class="pop-ajax"
                           href="<?= $this->url('employeur/supprimer', ['employeur' => $employeur['id']]) ?>"
                           title="Supprimer l'employeur"
                           data-content="<p class='lead text-danger'><strong>Attention!</strong> Confirmez-vous cette suppression ?</p>"
                           data-confirm="true"
                           data-confirm-button="Oui"
                           data-cancel-button="Non"
                           data-submit-reload="true"
                        >
                            <i class="fas fa-trash-can"></i>
                        </a>
                    <?php else: ?>
                        Non modifiable
                    <?php endif; ?></td>
            <?php else: ?>
                <td>Non modifiable</td>
            <?php endif; ?>
        </tr>
    <?php endforeach; ?>
    </tbody>

</table>


<?php if ($canEdit): ?>
    <tr class="champ-triable">
        <a class="btn btn-primary ajax-modal " data-event="employeur-edition"
           href="<?= $this->url('employeur/saisie'); ?>"><i
                    class="fas fa-plus"></i>
            Ajout d'un employeur</a>
    </tr>
<?php endif; ?>


<script type="text/javascript">
    $(function () {
        $("body").on("employeur-edition", function (event, data) {
            window.location.reload();
        });
    });

</script>


