<?php

use Application\Filter\StringFromFloat;
use OffreFormation\Entity\Db\VolumeHoraireEns;
use OffreFormation\Form\VolumeHoraireEnsForm;

/**
 * @var $this             \Application\View\Renderer\PhpRenderer
 * @var $vhes             VolumeHoraireEns[]
 * @var $form             VolumeHoraireEnsForm
 */

$canSave = false;

?>
<style>
    .edition-volume-horaire-ens .source {
        white-space: nowrap;
    }

    .edition-volume-horaire-ens td input {
        width: 100%;
    }

</style>
<?= $this->form()->openTag($form); ?>
<table class="table table-bordered table-sm table-hover edition-volume-horaire-ens" style="margin-top: 2px">
    <thead>
    <tr>
        <th>&nbsp;</th>
        <th>Heures</th>
        <th>Groupes</th>
        <th>Source</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($vhes as $vhe):
        $canEdit = $this->isAllowed($vhe, \Application\Provider\Privileges::ODF_ELEMENT_VH_EDITION);

        if ($canEdit) {
            $canSave = true;
            $heures  = $this->formText($form->getElement($vhe,'heures'));
            $groupes = $this->formText($form->getElement($vhe, 'groupes'));
        } else {
            $heures  = StringFromFloat::run($vhe->getHeures(), false);
            $groupes = StringFromFloat::run($vhe->getGroupes(), false);
        }

        ?>
        <tr>
            <td><abbr title="<?= $vhe->getTypeIntervention()->getLibelle() ?>"><?= $vhe->getTypeIntervention() ?></abbr></td>
            <td><?= $heures ?></td>
            <td><?= $groupes ?></td>
            <td class="source"><?= $vhe->getId() ? $vhe->getSource() : 'Non existant' ?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<?php

if ($canSave) {
    echo $this->formSubmit($form->get('submit'));
}
echo $this->form()->closeTag();
echo $this->messenger()->addCurrentMessagesFromFlashMessenger();
