<?php

/**
 * @var $this       \Application\View\Renderer\PhpRenderer
 * @var $controller \Laminas\Mvc\Controller\AbstractController
 * @var $container  \Psr\Container\ContainerInterface
 * @var $viewName   string
 * @var $viewFile   string
 */


$r = [
    [
        'KEY' => 'e-113957505-6',
        'ANNEE_ID' => '2017',
        'SERVICE_ID' => '89226',
        'SERVICE_REFERENTIEL_ID' => NULL,
        'MISSION_ID' => NULL,
        'FORMULE_RES_SERVICE_ID' => '113957505',
        'FORMULE_RES_SERVICE_REF_ID' => NULL,
        'INTERVENANT_ID' => '20970',
        'STRUCTURE_ID' => '229',
        'TYPE_HEURES_ID' => '6',
        'DOMAINE_FONCTIONNEL_ID' => '1',
        'CENTRE_COUT_ID' => '2401',
        'TAUX_REMU_ID' => '1',
        'TAUX_CONGES_PAYES' => '1',
        'SERVICE_HEURES' => '.74',
        'HEURES' => '.12',
        'HORAIRE_DEBUT' => NULL,
        'HORAIRE_FIN' => NULL,
        'PERIODE_ID' => '13',
    ],
    [
        'KEY' => 'e-113957505-6',
        'ANNEE_ID' => '2017',
        'SERVICE_ID' => '89226',
        'SERVICE_REFERENTIEL_ID' => NULL,
        'MISSION_ID' => NULL,
        'FORMULE_RES_SERVICE_ID' => '113957505',
        'FORMULE_RES_SERVICE_REF_ID' => NULL,
        'INTERVENANT_ID' => '20970',
        'STRUCTURE_ID' => '229',
        'TYPE_HEURES_ID' => '6',
        'DOMAINE_FONCTIONNEL_ID' => '1',
        'CENTRE_COUT_ID' => '2401',
        'TAUX_REMU_ID' => '1',
        'TAUX_CONGES_PAYES' => '1',
        'SERVICE_HEURES' => '.74',
        'HEURES' => '.08',
        'HORAIRE_DEBUT' => NULL,
        'HORAIRE_FIN' => NULL,
        'PERIODE_ID' => '13',
    ],
    [
        'KEY' => 'e-113957505-6',
        'ANNEE_ID' => '2017',
        'SERVICE_ID' => '89226',
        'SERVICE_REFERENTIEL_ID' => NULL,
        'MISSION_ID' => NULL,
        'FORMULE_RES_SERVICE_ID' => '113957505',
        'FORMULE_RES_SERVICE_REF_ID' => NULL,
        'INTERVENANT_ID' => '20970',
        'STRUCTURE_ID' => '229',
        'TYPE_HEURES_ID' => '6',
        'DOMAINE_FONCTIONNEL_ID' => '1',
        'CENTRE_COUT_ID' => '2401',
        'TAUX_REMU_ID' => '1',
        'TAUX_CONGES_PAYES' => '1',
        'SERVICE_HEURES' => '.74',
        'HEURES' => '.12',
        'HORAIRE_DEBUT' => NULL,
        'HORAIRE_FIN' => NULL,
        'PERIODE_ID' => '13',
    ],
    [
        'KEY' => 'e-113957505-6',
        'ANNEE_ID' => '2017',
        'SERVICE_ID' => '89226',
        'SERVICE_REFERENTIEL_ID' => NULL,
        'MISSION_ID' => NULL,
        'FORMULE_RES_SERVICE_ID' => '113957505',
        'FORMULE_RES_SERVICE_REF_ID' => NULL,
        'INTERVENANT_ID' => '20970',
        'STRUCTURE_ID' => '229',
        'TYPE_HEURES_ID' => '6',
        'DOMAINE_FONCTIONNEL_ID' => '1',
        'CENTRE_COUT_ID' => '2401',
        'TAUX_REMU_ID' => '1',
        'TAUX_CONGES_PAYES' => '1',
        'SERVICE_HEURES' => '.74',
        'HEURES' => '.08',
        'HORAIRE_DEBUT' => NULL,
        'HORAIRE_FIN' => NULL,
        'PERIODE_ID' => '13',
    ],
    [
        'KEY' => 'e-113957505-6',
        'ANNEE_ID' => '2017',
        'SERVICE_ID' => '89226',
        'SERVICE_REFERENTIEL_ID' => NULL,
        'MISSION_ID' => NULL,
        'FORMULE_RES_SERVICE_ID' => '113957505',
        'FORMULE_RES_SERVICE_REF_ID' => NULL,
        'INTERVENANT_ID' => '20970',
        'STRUCTURE_ID' => '229',
        'TYPE_HEURES_ID' => '6',
        'DOMAINE_FONCTIONNEL_ID' => '1',
        'CENTRE_COUT_ID' => '2401',
        'TAUX_REMU_ID' => '1',
        'TAUX_CONGES_PAYES' => '1',
        'SERVICE_HEURES' => '.74',
        'HEURES' => '.12',
        'HORAIRE_DEBUT' => NULL,
        'HORAIRE_FIN' => NULL,
        'PERIODE_ID' => '13',
    ],
    [
        'KEY' => 'e-113957505-6',
        'ANNEE_ID' => '2017',
        'SERVICE_ID' => '89226',
        'SERVICE_REFERENTIEL_ID' => NULL,
        'MISSION_ID' => NULL,
        'FORMULE_RES_SERVICE_ID' => '113957505',
        'FORMULE_RES_SERVICE_REF_ID' => NULL,
        'INTERVENANT_ID' => '20970',
        'STRUCTURE_ID' => '229',
        'TYPE_HEURES_ID' => '6',
        'DOMAINE_FONCTIONNEL_ID' => '1',
        'CENTRE_COUT_ID' => '2401',
        'TAUX_REMU_ID' => '1',
        'TAUX_CONGES_PAYES' => '1',
        'SERVICE_HEURES' => '.74',
        'HEURES' => '.08',
        'HORAIRE_DEBUT' => NULL,
        'HORAIRE_FIN' => NULL,
        'PERIODE_ID' => '13',
    ],
    [
        'KEY' => 'e-113957505-6',
        'ANNEE_ID' => '2017',
        'SERVICE_ID' => '89226',
        'SERVICE_REFERENTIEL_ID' => NULL,
        'MISSION_ID' => NULL,
        'FORMULE_RES_SERVICE_ID' => '113957505',
        'FORMULE_RES_SERVICE_REF_ID' => NULL,
        'INTERVENANT_ID' => '20970',
        'STRUCTURE_ID' => '229',
        'TYPE_HEURES_ID' => '6',
        'DOMAINE_FONCTIONNEL_ID' => '1',
        'CENTRE_COUT_ID' => '2401',
        'TAUX_REMU_ID' => '1',
        'TAUX_CONGES_PAYES' => '1',
        'SERVICE_HEURES' => '.74',
        'HEURES' => '.09',
        'HORAIRE_DEBUT' => NULL,
        'HORAIRE_FIN' => NULL,
        'PERIODE_ID' => '13',
    ],
    [
        'KEY' => 'e-113957505-6',
        'ANNEE_ID' => '2017',
        'SERVICE_ID' => '89226',
        'SERVICE_REFERENTIEL_ID' => NULL,
        'MISSION_ID' => NULL,
        'FORMULE_RES_SERVICE_ID' => '113957505',
        'FORMULE_RES_SERVICE_REF_ID' => NULL,
        'INTERVENANT_ID' => '20970',
        'STRUCTURE_ID' => '229',
        'TYPE_HEURES_ID' => '6',
        'DOMAINE_FONCTIONNEL_ID' => '1',
        'CENTRE_COUT_ID' => '2401',
        'TAUX_REMU_ID' => '1',
        'TAUX_CONGES_PAYES' => '1',
        'SERVICE_HEURES' => '.74',
        'HEURES' => '.08',
        'HORAIRE_DEBUT' => NULL,
        'HORAIRE_FIN' => NULL,
        'PERIODE_ID' => '13',
    ],










];