<?php
/**
 * @var $this    \Application\View\Renderer\PhpRenderer
 * @var $voiries \Lieu\Entity\Db\Voirie[]
 */

use Application\Provider\Privileges;

$this->headTitle()->append("Gestion des voiries");

$canEdit = $this->isAllowed(Privileges::getResourceId(Privileges::REFERENTIEL_COMMUN_VOIRIE_EDITION));

?>
<h1 class="page-header">Gestion des voiries</h1>

<table class="table table-bordered table-sort">
    <thead>
    <th>Code</th>
    <th>Libelle</th>
    <th>Source<?php if ($canEdit) echo '/Action' ?></th>
    </thead>
    <tbody>
    <?php foreach ($voiries as $voirie): ?>
        <tr>
            <td><?= $voirie->getCode() ?></td>
            <td data-order="<?= $voirie->getLibelle() ?>">
                <?= $voirie->getLibelle() ?>
            </td>
            <td style="text-align:center;width:1px;white-space: nowrap"><?php
                if ($voirie->getSource()->getImportable()) {
                    echo $voirie->getSource();
                } elseif ($canEdit) {
                    ?>
                    <a class="disabled ajax-modal" data-event="voirie-saisie"
                       href="<?= $this->url('voirie/saisie', ['voirie' => $voirie->getId()]) ?>"
                       title="Modifier la voirie"
                    ><i class="fas fa-pen-to-square"></i> </a>
                    <a class="pop-ajax"
                       href="<?= $this->url('voirie/delete', ['voirie' => $voirie->getId()]) ?>"
                       title="Supprimer la voirie"
                       data-content="<p class='lead text-danger'><strong>Attention!</strong> Confirmez-vous cette suppression ?</p>"
                       data-confirm="true"
                       data-confirm-button="Oui"
                       data-cancel-button="Non"
                       data-submit-reload="true"
                    ><i class="fas fa-trash-can"></i> </a>
                    <?php
                } else {
                    echo 'Non modifiable';
                }
                ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<?php if ($canEdit): ?>
    <a class="btn btn-primary ajax-modal" data-event="voirie-saisie"
       href="<?= $this->url('voirie/saisie') ?>"
       title="Ajouter une voirie">
        <i class="fas fa-pen-to-square"></i>
        Ajouter une voirie</a>

    <script type="text/javascript">
        $(function () {
            $("body").on("voirie-saisie", function (event, data) {
                window.location.reload();
            });
        });
    </script>
<?php endif ?>

