<?php

/* @var $intervenant Application\Entity\Db\Intervenant */
/* @var $serviceaAPayer Application\Entity\Db\ServiceAPayerInterface[] */
/* @var $saved boolean */

$title = 'Demande de mise en paiement';
if ($intervenant){
    $title .= ' <small>'.$intervenant.'</small>';
    $this->headTitle()->append($intervenant->getNomUsuel())->append($title);
}else{
    $this->headTitle()->append($title);
}

$this->headTitle()->append($intervenant->getNomUsuel())->append($title) ?>

<h1 class="page-header"><?php echo $title; ?></h1>

<?php
$html = $this->demandeMiseEnPaiement( $servicesAPayer )->render();

/**
 * NB: l'appel $this->messageCollector() doit être fait après $this->demandeMiseEnPaiement() car
 * MiseEnPaiementAssertion transmet des messages au collecteur de messages.
 */
echo $this->messageCollector();

echo $html;

if ($saved){
?>
<script type="text/javascript">
    $(function() {
        alertFlash('La demande de paiement a bien été prise en compte.', 'success', 2000);
    });
</script>
<?php
}