<?php

/**
 * @var $this        \Application\View\Renderer\PhpRenderer
 * @var $intervenant \Application\Entity\Db\Intervenant
 * @var $paiements   \Application\Entity\Db\MiseEnPaiement[]
 */

$this->intervenant($intervenant)->renderTitle('Annulation de mises en paiement');

?>
<form method="post" id="mepform">
    <table class="table table-bordered table-condensed table-extra-condensed table-hover table-sort">
        <thead>
        <tr>
            <th>&nbsp;</th>
            <th>Composante</th>
            <th>Enseignement</th>
            <th>Centre de coûts</th>
            <th>Domaine fonctionel</th>
            <th>Période</th>
            <th>Type</th>
            <th>HETD</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($paiements as $paiement):
            if ($paiement->getFormuleResultatService()) {
                $service = $paiement->getFormuleResultatService()->getService();
                if ($service->getElementPedagogique()) {
                    $composante = $service->getElementPedagogique()->getStructure();
                } else {
                    $composante = $intervenant->getStructure();
                }
            } else {
                $service            = null;
                $serviceReferentiel = $paiement->getFormuleResultatServiceReferentiel()->getServiceReferentiel();
                $composante         = $serviceReferentiel->getStructure();
            }
            ?>
            <tr>
                <td style="text-align:center;vertical-align:middle"><?= $this->formCheckbox(new \Laminas\Form\Element\Checkbox('mep[' . $paiement->getId() . ']')) ?></td>
                <td><?= $this->structure($composante)->renderLink() ?></td>
                <td><?php
                    if ($service) {
                        if ($service->getElementPedagogique()) {
                            echo $this->elementPedagogique($service->getElementPedagogique())->renderLink();
                        } else {
                            if ($service->getDescription()) {
                                echo $this->etablissement($service->getEtablissement())->renderLink() . ' - ' . $service->getDescription();
                            } else {
                                echo $this->etablissement($service->getEtablissement())->renderLink();
                            }
                        }
                    } else {
                        echo $this->fonctionReferentiel($serviceReferentiel->getFonction())->renderLink();
                    }
                    ?></td>
                <td><?= $paiement->getCentreCout() ?></td>
                <td><?= $paiement->getDomaineFonctionnel() ?></td>
                <td data-order="<?= $paiement->getPeriodePaiement() ? $paiement->getPeriodePaiement()->getOrdre() : 999999999 ?>"><?= $paiement->getPeriodePaiement() ? $paiement->getPeriodePaiement()->getLibelleAnnuel($intervenant->getAnnee()) : '<i>Simple demande</i>' ?></td>
                <td><?= $paiement->getTypeHeures() ?></td>
                <td><?= \UnicaenApp\Util::formattedNumber($paiement->getHeures()) ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
    <div>
        <button class="btn btn-default btn-xs" type="button" onclick="$('.table-sort :checkbox').prop('checked', true);">Tout
            sélectionner
        </button>
        <button class="btn btn-default btn-xs" type="button" onclick="$('.table-sort :checkbox').prop('checked', false);">Ne
            rien sélectionner
        </button>
    </div>
    <div style="margin-top: .5em;margin-bottom: .5em">
        <button class="btn btn-danger pop-ajax" type="button"
                data-content="Voulez-vous réellement annuler ces mises en paiement ?
            <div class='alert alert-warning'>
            <button type='button' class='close' data-dismiss='alert' aria-label='Close'><span aria-hidden='true'>&times;</span></button>
                Attention : Retirer les mises en paiement ne signifie pas qu'elles sont supprimées. Elles ne sont remises qu'à l'état de simples demandes de mises en paiement.
                Pour les supprimer définitivement, il convient de retirer également les <a class='no-intranavigation' href='<?= $this->url('intervenant/mise-en-paiement/demande', ['intervenant' => $intervenant->getId()]) ?>'>demandes de mises en paiement</a>.
            </div>
            <div style='text-align:right'>
            <button type='button' class='btn btn-default pop-ajax-hide'>Non</button>
            <button type='button' class='btn btn-primary' onclick='enregistrer()'>Oui</button></div>"
        ><i class="fas fa-trash-can"></i> Annuler les mises en paiement
        </button>
    </div>
    <?= $this->form()->closeTag() ?>
    <script type="text/javascript">

        function enregistrer()
        {
            $("#mepform").submit();
        }

    </script>

