<?php

/* @var $etatPaiement array */
/* @var $hasFoot boolean */

?>
<table class="table table-sm table-bordered etat-paiement">
<thead>
    <tr>
        <th rowspan="2">Identité</th>
        <th rowspan="2">N° INSEE</th>
        <th rowspan="2">Centre de coûts / EOTP</th>
        <th rowspan="2">Domaine fonctionnel</th>
        <th colspan="2" rowspan="2">HETD</th>
        <th rowspan="2">Montant</th>
        <th rowspan="2">Rém. FC D714.60</th>
        <th colspan="2">Exercice</th>
    </tr>
    <tr>
        <th>AA</th>
        <th>AC</th>
    </tr>
</thead>
<tbody>
    <?php foreach( $etatPaiement as $intervenantId => $llEP ) if ($intervenantId != 'total'): ?>
    <?php foreach( $llEP as $hetdRem => $lep ): ?>
    <?php foreach( $lep as $iEP => $ep ): ?>

    <?php if ($iEP !== 'total'): ?>
    <tr>
        <td><?= $ep['intervenant-nom'] ?></td>
        <td style="white-space: nowrap"><?= $ep['intervenant-numero-insee'] ?></td>
        <td><?= $ep['centre-cout-code'] ?></td>
        <td><?= $ep['domaine-fonctionnel-libelle'] ?></td>
        <td class="nombre"><?= $hetdRem == 'hetd' ? \UnicaenApp\Util::formattedNumber($ep['hetd']) : '' ?></td>
        <td class="nombre"><?= $hetdRem == 'hetd' ? \UnicaenApp\Util::formattedPourcentage($ep['hetd-pourc']) : '' ?></td>
        <td class="nombre"><?= $hetdRem == 'hetd' ? \UnicaenApp\Util::formattedEuros($ep['hetd-montant']) : '' ?></td>
        <td class="nombre"><?= $hetdRem == 'hetd' ? '' : \UnicaenApp\Util::formattedEuros($ep['rem-fc-d714']) ?></td>
        <td class="nombre"><?= $hetdRem == 'hetd' ? \UnicaenApp\Util::formattedNumber($ep['exercice-aa']) : '' ?></td>
        <td class="nombre"><?= $hetdRem == 'hetd' ? \UnicaenApp\Util::formattedNumber($ep['exercice-ac']) : '' ?></td>
    </tr>
    <?php endif; ?>
    <?php endforeach; ?>
    <?php if (count($lep) > 1 ): ?>
    <tr>
        <th colspan="4" style="text-align: right">Sous-total <?= $hetdRem == 'hetd' ? 'HC' : 'rém. FC D714.60' ?></th>
        <th class="nombre"><?= $hetdRem == 'hetd' ? \UnicaenApp\Util::formattedNumber($lep['total']['hetd']) : '' ?></th>
        <th class="nombre"><?= $hetdRem == 'hetd' ? \UnicaenApp\Util::formattedPourcentage($lep['total']['hetd-pourc']) : '' ?></th>
        <th class="nombre"><?= $hetdRem == 'hetd' ? \UnicaenApp\Util::formattedEuros($lep['total']['hetd-montant']) : '' ?></th>
        <th class="nombre"><?= $hetdRem == 'hetd' ? '' : \UnicaenApp\Util::formattedEuros($lep['total']['rem-fc-d714']) ?></th>
        <th class="nombre"><?= $hetdRem == 'hetd' ? \UnicaenApp\Util::formattedNumber($lep['total']['exercice-aa']) : \UnicaenApp\Util::formattedEuros($lep['total']['exercice-aa-montant']) ?></th>
        <th class="nombre"><?= $hetdRem == 'hetd' ? \UnicaenApp\Util::formattedNumber($lep['total']['exercice-ac']) : \UnicaenApp\Util::formattedEuros($lep['total']['exercice-ac-montant']) ?></th>
    </tr>
    <?php endif; ?>
    <?php endforeach; ?>
    <?php endif; ?>
</tbody>
<?php if ($hasFoot): ?>
<tfoot class="tfoot bg-info">
    <tr>
        <td colspan="4"><?= (count($etatPaiement)-1) ?> intervenant(s)</td>
        <td class="nombre"><?= \UnicaenApp\Util::formattedNumber($etatPaiement['total']['hetd']) ?></td>
        <td>&nbsp;</td>
        <td class="nombre"><?= \UnicaenApp\Util::formattedEuros($etatPaiement['total']['hetd-montant']) ?></td>
        <td class="nombre"><?= \UnicaenApp\Util::formattedEuros($etatPaiement['total']['rem-fc-d714']) ?></td>
        <td class="nombre"><?= \UnicaenApp\Util::formattedEuros($etatPaiement['total']['exercice-aa-montant']) ?></td>
        <td class="nombre"><?= \UnicaenApp\Util::formattedEuros($etatPaiement['total']['exercice-ac-montant']) ?></td>
    </tr>
</tfoot>
<?php endif; ?>
</table>