<?php

/* @var $etatPaiement array */
/* @var $hasFoot boolean */

?>
<table class="table table-condensed table-bordered etat-paiement">
<thead>
    <tr>
        <th rowspan="2">Identité</th>
        <th rowspan="2">N° INSEE</th>
        <th rowspan="2">Centre de coûts / EOTP</th>
        <th rowspan="2">Domaine fonctionnel</th>
        <th colspan="2" rowspan="2">HETD</th>
        <th rowspan="2">Montant</th>
        <th rowspan="2">Rém. FC D714.60</th>
        <th colspan="2">Exercice</th>
    </tr>
    <tr>
        <th>AA</th>
        <th>AC</th>
    </tr>
</thead>
<tbody>
    <?php foreach( $etatPaiement as $intervenantId => $llEP ) if ($intervenantId != 'total'): ?>
    <?php foreach( $llEP as $hetdRem => $lep ): ?>
    <?php foreach( $lep as $iEP => $ep ): ?>

    <?php if ($iEP !== 'total'): ?>
    <tr>
        <td><?php echo $ep['intervenant-nom'] ?></td>
        <td style="white-space: nowrap"><?php echo $ep['intervenant-numero-insee'] ?></td>
        <td><?php echo $ep['centre-cout-code'] ?></td>
        <td><?php echo $ep['domaine-fonctionnel-libelle'] ?></td>
        <td class="nombre"><?php echo $hetdRem == 'hetd' ? \Common\Util::formattedHeures($ep['hetd']) : '' ?></td>
        <td class="nombre"><?php echo $hetdRem == 'hetd' ? \Common\Util::formattedPourcentage($ep['hetd-pourc']) : '' ?></td>
        <td class="nombre"><?php echo $hetdRem == 'hetd' ? \Common\Util::formattedEuros($ep['hetd-montant']) : '' ?></td>
        <td class="nombre"><?php echo $hetdRem == 'hetd' ? '' : \Common\Util::formattedEuros($ep['rem-fc-d714']) ?></td>
        <td class="nombre"><?php echo $hetdRem == 'hetd' ? \Common\Util::formattedHeures($ep['exercice-aa']) : '' ?></td>
        <td class="nombre"><?php echo $hetdRem == 'hetd' ? \Common\Util::formattedHeures($ep['exercice-ac']) : '' ?></td>
    </tr>
    <?php endif; ?>
    <?php endforeach; ?>
    <?php if (count($lep) > 1 ): ?>
    <tr>
        <th colspan="4" style="text-align: right">Sous-total <?php echo $hetdRem == 'hetd' ? 'HC' : 'rém. FC D714.60' ?></th>
        <th class="nombre"><?php echo $hetdRem == 'hetd' ? \Common\Util::formattedHeures($lep['total']['hetd']) : '' ?></th>
        <th class="nombre"><?php echo $hetdRem == 'hetd' ? \Common\Util::formattedPourcentage($lep['total']['hetd-pourc']) : '' ?></th>
        <th class="nombre"><?php echo $hetdRem == 'hetd' ? \Common\Util::formattedEuros($lep['total']['hetd-montant']) : '' ?></th>
        <th class="nombre"><?php echo $hetdRem == 'hetd' ? '' : \Common\Util::formattedEuros($lep['total']['rem-fc-d714']) ?></th>
        <th class="nombre"><?php echo $hetdRem == 'hetd' ? \Common\Util::formattedHeures($lep['total']['exercice-aa']) : \Common\Util::formattedEuros($lep['total']['exercice-aa-montant']) ?></th>
        <th class="nombre"><?php echo $hetdRem == 'hetd' ? \Common\Util::formattedHeures($lep['total']['exercice-ac']) : \Common\Util::formattedEuros($lep['total']['exercice-ac-montant']) ?></th>
    </tr>
    <?php endif; ?>
    <?php endforeach; ?>
    <?php endif; ?>
</tbody>
<?php if ($hasFoot): ?>
<tfoot class="bg-info">
    <tr>
        <td colspan="4"><?php echo (count($etatPaiement)-1) ?> intervenant(s)</td>
        <td class="nombre"><?php echo \Common\Util::formattedHeures($etatPaiement['total']['hetd']) ?></td>
        <td>&nbsp;</td>
        <td class="nombre"><?php echo \Common\Util::formattedEuros($etatPaiement['total']['hetd-montant']) ?></td>
        <td class="nombre"><?php echo \Common\Util::formattedEuros($etatPaiement['total']['rem-fc-d714']) ?></td>
        <td class="nombre"><?php echo \Common\Util::formattedEuros($etatPaiement['total']['exercice-aa-montant']) ?></td>
        <td class="nombre"><?php echo \Common\Util::formattedEuros($etatPaiement['total']['exercice-ac-montant']) ?></td>
    </tr>
</tfoot>
<?php endif; ?>
</table>