<?php

/* @var $form Application\Form\Paiement\MiseEnPaiementForm */
/* @var $errors string[] */

echo $this->form()->openTag($form->prepare());

echo $this->formControlGroup($form->get('periode'));
echo $this->formControlGroup($form->get('date-mise-en-paiement'));

echo $this->formRow($form->get('submit'));

echo $this->form()->closeTag();
echo $this->formErrors( $form );

?><script type="text/javascript">
    $(function() {
        PaiementMiseEnPaiementForm.get("<?php echo $form->getId(); ?>").init();
    });
</script><?php

if ($errors) echo $this->messenger()->setMessages(array(UnicaenApp\View\Helper\Messenger::ERROR => $errors));