<?php

/* @var $intervenant Application\Entity\Db\Intervenant */
/* @var $services Application\Entity\Db\FormuleResultatService[] */
/* @var $referentiels Application\Entity\Db\FormuleResultatReferentiel[] */

$title = 'Mise en paiement';
if ($intervenant){
    $title .= ' <small>'.$intervenant.'</small>';
    $this->headTitle()->append($intervenant->getNomUsuel())->append("Etat de paiement");
}else{
    $this->headTitle()->append("Etat de paiement");
}

$this->headTitle()->append($intervenant->getNomUsuel())->append("Paiement") ?>

<h1 class="page-header"><?php echo $title; ?></h1>

<?php

foreach( $services as $service ){
    echo $this->paiementLigne( $service )->render();
}

foreach( $referentiels as $referentiel ){
    echo $this->paiementLigne( $referentiel )->render();
}