<?php

/**
 * @var $this \Application\View\Renderer\PhpRenderer
 * @var $form \Application\Form\Chargens\DifferentielForm
 * @var $diff array
 */

$title    = "Différentiel entre deux exports des charges d'enseignement";
$uploader = $this->uploader();

?>
<h1 class="page-header"><?php echo $title ?></h1>

<?php


echo $this->form()->openTag($form);

echo '<div class="row">';

echo '<div class="col-md-6">';
echo $this->formControlGroup($form->get('avant'));
echo '</div>';

echo '<div class="col-md-6">';
echo $this->formControlGroup($form->get('apres'));
echo '</div>';

echo '</div>';

echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();

if (!empty($diff)) {

    foreach ($diff as $dc) {
        echo '<h2>' . $dc['libelle'] . '</h2>';
        foreach ($dc['etapes'] as $de) {
            echo '<h3>' . $de['libelle'] . '</h3>';
            foreach ($de['elements'] as $ep) {
                echo '<h4>' . $ep['libelle'] . ' (' . $ep['code'] . ')</h4>';
                var_dump($ep);
            }
        }
    }
}

?>
<a class="btn btn-default" href="<?= $this->url('chargens'); ?>">
    <i class="fa fa-undo" aria-hidden="true"></i>
    Retour au menu des charges d'enseignement
</a>
