<?php

/**
 * @var $this       \Application\View\Renderer\PhpRenderer
 * @var $etape      \OffreFormation\Entity\Db\Etape
 * @var $scenario   \Application\Entity\Db\Scenario
 * @var $filtre     \Application\Form\Chargens\FiltreForm
 */

?>
<h1 class="page-header">Charges d'enseignement</h1>
<?php

echo $this->chargens()->setFormFiltre($filtre)->render();
echo $this->navigation('navigation')->menuContextuel()->setPartial('unicaen-app/menu-dl.phtml');
?>
<a class="btn btn-secondary" href="<?= $this->url('chargens'); ?>">
    <i class="fas fa-rotate-left" aria-hidden="true"></i>
    Retour au menu des charges d'enseignement
</a>
