<?php

/**
 * @var $this       \Application\View\Renderer\PhpRenderer
 * @var $etape      \Application\Entity\Db\Etape
 * @var $scenario   \Application\Entity\Db\Scenario
 * @var $filtre     \Application\Form\Chargens\FiltreForm
 */

?>
    <h1 class="page-header">Charges d'enseignement</h1>
    <script src="/ose/js/chargens.js"></script>
<?php


echo $this->chargens()->setFormFiltre($filtre)->render();