<?php

use Application\Provider\Privilege\Privileges;

/**
 * @var $this      \Application\View\Renderer\PhpRenderer
 * @var $scenario  \Application\Entity\Db\Scenario
 * @var $seuils    array
 */

$title = "Gestion des seuils de dédoublement";

$this->headTitle()->append($title);

$canEditEtab = $this->isAllowed(Privileges::getResourceId(Privileges::CHARGENS_SEUIL_ETABLISSEMENT_EDITION));
$canEditcomp = $this->isAllowed(Privileges::getResourceId(Privileges::CHARGENS_SEUIL_COMPOSANTE_EDITION));

?>
<h1 class="page-header"><?php echo $title ?></h1>

<div class="row div-filtre chargens-filtre">
    <div class="col-md-4 div-structure">
        <label>Composante : </label>
        <?php echo $this->formSelect($filtre->get('structure')) ?>
    </div>
    <div class="col-md-4 div-scenario">
        <label>Scénario : </label>
        <?php echo $this->formSelect($filtre->get('scenario')) ?>
    </div>
</div>
<br />

<?php if ($scenario) {
    foreach ($seuils['structures'] as $sid => $structure): ?>
        <div class="panel panel-default">
            <div class="panel-heading panel-heading-h3">
                <h3>
                    <?php echo $structure['libelle'] ?>
                </h3>
            </div>
            <table class="table table-hover table-bordered seuils-dedoublement">
                <thead>
                <tr>
                    <th style="width:30%">Type de formation</th>
                    <?php foreach ($structure['types-interventions'] as $tiid => $typeIntervention): ?>
                        <th style="width:10em"
                            title="<?php echo $typeIntervention['libelle'] ?>"><?php echo $typeIntervention['code'] ?></th>
                    <?php endforeach; ?>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($structure['groupes-type-formations'] as $gtfid => $gtfLibelle): ?>
                    <tr id="seuil-gtf-<?php echo $gtfid ?>">
                        <td><?php echo $gtfLibelle; ?></td>
                        <?php foreach ($structure['types-interventions'] as $tiid => $typeIntervention): ?>
                            <td style="text-align:center">
                                <?php
                                /** @var \Application\Entity\Db\SeuilCharge $seuil */
                                $seuil = isset($seuils['seuils'][$sid][$gtfid][$tiid]) ? $seuils['seuils'][$sid][$gtfid][$tiid] : null;

                                if (($sid && $canEditcomp) || (!$sid && $canEditEtab)) {
                                    $input = new \Zend\Form\Element\Text('sd-' . $sid . '-' . $gtfid . '-' . $tiid);
                                    $input->setAttributes([
                                        'class'                      => 'form-control',
                                        'onchange'                   => 'changementSeuil(this)',
                                        'data-structure'             => $sid,
                                        'data-groupe-type-formation' => $gtfid,
                                        'data-type-intervention'     => $tiid,
                                    ]);
                                    if ($seuil) $input->setValue($seuil->getDedoublement());
                                    echo $this->formInput($input);
                                } else {
                                    if ($seuil) echo $seuil->getDedoublement();
                                }

                                ?>
                            </td>
                        <?php endforeach; ?>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    <?php endforeach;
} ?>

<a class="btn btn-default" href="<?php echo $this->url('chargens'); ?>">
    <i class="fa fa-undo" aria-hidden="true"></i>
    Retour au menu des charges d'enseignement
</a>

<script>

    function changementSeuil(element)
    {
        var url = "<?php echo $scenario ? $this->url('chargens/seuil/modifier', ['scenario' => $scenario->getId()]) : null ?>";
        var params = $(element).data();
        params.dedoublement = $(element).val();

        $.post(url, params, function (data)
        {
            alertFlash(data, 'success', 3000);
        }).fail(function (jqXHR)
        {
            alertFlash(data, 'danger', 3000);
            console.log(jqXHR);
        });
    }

    $(function ()
    {
        $(".chargens-filtre #scenario").change(function ()
        {
            var url = "<?php echo $this->url('chargens/seuil') ?>";

            location.href = url + '/' + $(this).val();
        });
    });

</script>
