<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Entity\Db;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Historique extends \Application\Entity\Db\Historique implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'debut', 'fin', 'modification', 'id', 'modificateur', 'destructeur', 'createur');
        }

        return array('__isInitialized__', 'debut', 'fin', 'modification', 'id', 'modificateur', 'destructeur', 'createur');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Historique $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setDebut($debut)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDebut', array($debut));

        return parent::setDebut($debut);
    }

    /**
     * {@inheritDoc}
     */
    public function getDebut()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDebut', array());

        return parent::getDebut();
    }

    /**
     * {@inheritDoc}
     */
    public function setFin($fin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFin', array($fin));

        return parent::setFin($fin);
    }

    /**
     * {@inheritDoc}
     */
    public function getFin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFin', array());

        return parent::getFin();
    }

    /**
     * {@inheritDoc}
     */
    public function setModification($modification)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModification', array($modification));

        return parent::setModification($modification);
    }

    /**
     * {@inheritDoc}
     */
    public function getModification()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModification', array());

        return parent::getModification();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setModificateur(\Application\Entity\Db\Utilisateur $modificateur = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModificateur', array($modificateur));

        return parent::setModificateur($modificateur);
    }

    /**
     * {@inheritDoc}
     */
    public function getModificateur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModificateur', array());

        return parent::getModificateur();
    }

    /**
     * {@inheritDoc}
     */
    public function setDestructeur(\Application\Entity\Db\Utilisateur $destructeur = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDestructeur', array($destructeur));

        return parent::setDestructeur($destructeur);
    }

    /**
     * {@inheritDoc}
     */
    public function getDestructeur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDestructeur', array());

        return parent::getDestructeur();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreateur(\Application\Entity\Db\Utilisateur $createur = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreateur', array($createur));

        return parent::setCreateur($createur);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreateur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreateur', array());

        return parent::getCreateur();
    }

}
