<?php

/**
 * @var $this  \Application\View\Renderer\PhpRenderer
 * @var $form  EtatSortieForm
 * @var $title string
 * @var $activationSignatureElectronique ?string
 */

?>
<h1 class="page-header"><?php echo $title ?></h1>

<?php

echo $this->messenger()->addCurrentMessagesFromFlashMessenger();

/* On réutilise l'ACE d'UnicaenImport (pas top) */
echo $this->inlinescript()->appendFile($this->basePath() . '/ext/ace-builds-master/src-min/ace.js');

echo $this->form()->openTag($form);

?>
<div class="row">
    <div class="col-md-4"><?= $this->formControlGroup($form->get('code')) ?></div>
    <div class="col-md-8"><?= $this->formControlGroup($form->get('libelle')) ?></div>
</div>

<ul class="nav nav-tabs" role="tablist">
    <li role="presentation"><a class="nav-link active" href="#sql" aria-controls="sql" role="tab" data-bs-toggle="tab">Requêtage</a>
    </li>
    <li role="presentation"><a class="nav-link" href="#csv" aria-controls="csv" role="tab" data-bs-toggle="tab">Export
            CSV</a></li>
    <li role="presentation"><a class="nav-link" href="#pdf" aria-controls="pdf" role="tab" data-bs-toggle="tab">Export
            PDF</a></li>
    <li role="presentation"><a class="nav-link" href="#parametrage" aria-controls="parametrage" role="tab"
                               data-bs-toggle="tab">Paramétrages</a>
    </li>
</ul>

<div class="tab-content etat-sortie-saisir">
    <div role="tabcard" class="tab-pane active" id="sql">

        <h2>Requête SQL de document</h2>
        <div class="card bg-default etat-sortie-requete">
            <div class="card-header" role="tab">
                <label>Champ clé : </label>
                <?= $this->formText($form->get('cle')) ?>
            </div>
            <div class="card-body">
                <?= $this->formTextarea($form->get('requete')) ?>
            </div>
        </div>
        <h2>Requêtes SQL par zones</h2>
        <div class="list-group" id="blocs" role="tablist" aria-multiselectable="true">

            <?php for ($i = 1; $i <= 10; $i++): ?>
                <div class="card bg-default etat-sortie-bloc" id="bloc<?= $i ?>">
                    <div class="card-header" role="tab" id="headingOne">
                        <label>Champ de référence : </label>
                        <?= $this->formText($form->get("bloc-$i-nom")) ?>
                        &nbsp;<label>Zone : </label>
                        <?= $this->formSelect($form->get("bloc-$i-zone")) ?>
                    </div>
                    <div class="card-body">
                        <?= $this->formTextarea($form->get("bloc-$i-requete")) ?>
                    </div>
                </div>
            <?php endfor; ?>
        </div>
        <button type="button" class="btn btn-secondary btn-sm ajout-bloc">
            <i class="fas fa-plus"></i> Ajouter une requête
        </button>
    </div>
    <div role="tabcard" class="tab-pane" id="csv">
        <?= $this->formLabel($form->get('csv-params')) ?>
        <div class="card bg-default csv-options">
            <?= $this->formTextarea($form->get('csv-params')) ?>
        </div>

        <?= $this->formLabel($form->get('csv-traitement')) ?>
        <div class="card bg-default variables">
            <div class="card-header">Variables disponibles en entrée</div>
            <table class="table table-xs">
                <tr>
                    <th>$csv</th>
                    <td>
                        <a href="https://git.unicaen.fr/lib/unicaen/app/-/blob/master/src/UnicaenApp/View/Model/CsvModel.php"
                           target="_blank">UnicaenApp\View\Model\CsvModel</a>
                    </td>
                    <td>Document permettant de travailler à sa mise en page</td>
                </tr>
                <tr>
                    <th>$etatSortie</th>
                    <td>
                        <a href="https://git.unicaen.fr/open-source/OSE/-/blob/master/module/Application/src/Entity/Db/EtatSortie.php"
                           target="_blank">EtatSortie\Entity\Db\EtatSortie</a>
                    </td>
                    <td>Etat de sortie</td>
                </tr>
                <tr>
                    <th>$data</th>
                    <td>array</td>
                    <td>Tableau de données issu de la requête exécutée</td>
                </tr>
                <tr>
                    <th>$filtres</th>
                    <td>array</td>
                    <td>Liste des filtres avec les valeurs transmises (format COLONNE => Valeur)</td>
                </tr>
                <tr>
                    <th>$entityManager</th>
                    <td>
                        <a href="https://github.com/webmozart/doctrine-orm/blob/master/lib/Doctrine/ORM/EntityManager.php"
                           target="_blank">Doctrine\ORM\EntityManager</a>
                    </td>
                    <td>Gestionaire d'entités Doctrine (permet d'accéder à la base de données)</td>
                </tr>
            </table>
            <div class="card-body">
                <?= $this->formTextarea($form->get('csv-traitement')) ?>
            </div>
            <div class="card-header">Données en sortie</div>
            <div class="card-body">
                Le traitement doit retourner un tableau de données (array) à publiposter, ou NULL.
            </div>
        </div>


    </div>
    <div role="tabcard" class="tab-pane" id="pdf">
        <?= $this->formControlGroup($form->get('fichier')) ?>
        <?= $this->formControlGroup($form->get('auto-break')) ?>
        <h4><?= $this->formLabel($form->get('pdf-traitement')) ?></h4>
        <div class="card bg-default variables">
            <div class="card-header">Variables disponibles en entrée</div>
            <table class="table table-xs">
                <tr>
                    <th>$document</th>
                    <td>
                        <a href="https://git.unicaen.fr/lib/unicaen/open-document/-/blob/master/src/Document.php"
                           target="_blank">Unicaen\OpenDocument\Document</a>
                    </td>
                    <td>Document permettant de travailler à sa mise en page</td>
                </tr>
                <tr>
                    <th>$etatSortie</th>
                    <td>
                        <a href="https://git.unicaen.fr/open-source/OSE/-/blob/master/module/Application/src/Entity/Db/EtatSortie.php"
                           target="_blank">EtatSortie\Entity\Db\EtatSortie</a>
                    </td>
                    <td>Etat de sortie</td>
                </tr>
                <tr>
                    <th>$data</th>
                    <td>array</td>
                    <td>Tableau de données issu de la requête exécutée</td>
                </tr>
                <tr>
                    <th>$filtres</th>
                    <td>array</td>
                    <td>Liste des filtres avec les valeurs transmises (format COLONNE => Valeur)</td>
                </tr>
                <tr>
                    <th>$entityManager</th>
                    <td>
                        <a href="https://github.com/webmozart/doctrine-orm/blob/master/lib/Doctrine/ORM/EntityManager.php"
                           target="_blank">Doctrine\ORM\EntityManager</a>
                    </td>
                    <td>Gestionaire d'entités Doctrine (permet d'accéder à la base de données)</td>
                </tr>
            </table>
            <div class="card-body">
                <?= $this->formTextarea($form->get('pdf-traitement')) ?>
            </div>
            <div class="card-header">Données en sortie</div>
            <div class="card-body">
                Le traitement doit retourner un tableau de données (array) à publiposter, ou NULL.
            </div>
        </div>
    </div>
    <div role="tabcard" class="tab-pane" id="parametrage">
        <br/>
        <div class="card bg-default variables">
            <div class="card-header">Paramètrage signature électronique</div>
            <?php if($activationSignatureElectronique): ?>
            <div class="card-body" style="padding:10px;">
                <?= $this->formControlGroup($form->get('signatureActivation')); ?>
                <?= $this->formControlGroup($form->get('signatureCircuit')); ?>
            </div>
            <?php else: ?>
                <div class="card-body" style="padding:10px;">
                    <p style="text-align:center;">Vous n'avez aucun parapheur électronique d'activé sur votre instance.</p>
                </div>
            <?php endif; ?>

        </div>
    </div>
</div>

<?php
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();


?>
<script>

    $(function () {

        WidgetInitializer.add('etat-sortie-saisir', {
            requeteEditor: null,
            paramsEditor: null,
            traitementPdfEditor: null,
            traitementCsvEditor: null,
            blocs: {},

            save: function () {
                var csvParams = $("<input>").attr("type", 'hidden').attr("name", 'csv-params').val(this.paramsEditor.getSession().getValue());
                this.element.append($(csvParams));

                var pdfTraitement = $("<input>").attr("type", 'hidden').attr("name", 'pdf-traitement').val(this.traitementPdfEditor.getSession().getValue());
                this.element.append($(pdfTraitement));

                var csvTraitement = $("<input>").attr("type", 'hidden').attr("name", 'csv-traitement').val(this.traitementCsvEditor.getSession().getValue());
                this.element.append($(csvTraitement));

                var requete = $("<input>").attr("type", "hidden").attr("name", "requete").val(this.requeteEditor.getSession().getValue());
                this.element.append($(requete));

                for (var i = 1; i <= 10; i++) {
                    var binput = $("<input>").attr("type", "hidden").attr("name", "bloc-" + i + "-requete").val(this.blocs[i].getSession().getValue());
                    this.element.append($(binput));
                }
            },

            ajoutBloc: function () {
                for (var i = 1; i <= 10; i++) {
                    if (!this.isBlocRempli(i)) {
                        this.showBloc(i);
                        break;
                    }
                }
            },

            isBlocRempli: function (bloc) {
                var res = this.element.find('bloc-' + bloc + '-nom').val() != ''
                    && this.blocs[bloc].getSession().getValue() != '';

                return res;
            },

            showBloc: function (bloc) {
                this.element.find(".etat-sortie-bloc#bloc" + bloc).show();
            },

            hideBloc: function (bloc) {
                this.element.find(".etat-sortie-bloc#bloc" + bloc).hide();
            },

            _create: function () {
                var that = this;

                that.element.find('.btn-save').click(function () {
                    that.save();
                });
                that.element.find('.ajout-bloc').click(function () {
                    that.ajoutBloc()
                });

                var options = {
                    minLines: 15, maxLines: 40,
                };

                that.paramsEditor = ace.edit("csv-params");
                that.paramsEditor.setTheme("ace/theme/github");
                that.paramsEditor.getSession().setMode("ace/mode/json");
                that.paramsEditor.setOptions(options);

                that.traitementPdfEditor = ace.edit("pdf-traitement");
                that.traitementPdfEditor.setTheme("ace/theme/github");
                that.traitementPdfEditor.getSession().setMode({path: "ace/mode/php", inline: true});
                that.traitementPdfEditor.setOptions(options);

                that.traitementCsvEditor = ace.edit("csv-traitement");
                that.traitementCsvEditor.setTheme("ace/theme/github");
                that.traitementCsvEditor.getSession().setMode({path: "ace/mode/php", inline: true});
                that.traitementCsvEditor.setOptions(options);

                that.requeteEditor = ace.edit("requete");
                that.requeteEditor.setTheme("ace/theme/github");
                that.requeteEditor.getSession().setMode("ace/mode/sql");
                that.requeteEditor.setOptions(options);

                for (var i = 1; i <= 10; i++) {
                    that.blocs[i] = ace.edit("bloc-" + i + "-requete");
                    that.blocs[i].setTheme("ace/theme/github");
                    that.blocs[i].getSession().setMode("ace/mode/sql");
                    that.blocs[i].setOptions(options);

                    if (that.isBlocRempli(i)) {
                        that.showBloc(i);
                    } else {
                        that.hideBloc(i);
                    }
                }
            }
        });

    });

</script>
<style>

    #parametrage {

    }

    .etat-sortie-saisir .etat-sortie-bloc {
        display: none;
    }

    .etat-sortie-saisir .etat-sortie-bloc .card-header .form-control {
        display: inline;
    }

    .etat-sortie-saisir #fichier {
        height: none;
    }

    .etat-sortie-saisir .card-header {
        padding-top: 3px;
        padding-bottom: 3px;
    }

    .etat-sortie-saisir .card-body {
        padding: 0px;
    }

    .etat-sortie-saisir #sql .ace_editor {
        border: none;
        border-radius: 0;
        margin-bottom: 0px;
        margin-top: 0px;
    }

    .etat-sortie-saisir #pdf .ace_editor {
        margin: 0 0 1px;
    }

    .etat-sortie-saisir #pdf .variables {
        font-size: 12px;
        margin-bottom: 1px;
    }

    .etat-sortie-saisir #csv .ace_editor {
        margin: 0 0 1px;
    }

    .etat-sortie-saisir #csv .variables {
        font-size: 12px;
        margin-bottom: 1px;
    }
</style>