<h2>Validation du dossier d'un intervenant <small><?php echo $intervenant ?></small></h2>

<?php echo $this->messenger(true) ?>

<?php $form->prepare(); ?>
<?php echo $this->form()->openTag($form); ?>
    <div class="row">
        <div class="col-md-4">
            <?php 
            echo $this->formControlGroup($form->get('complet'));
            echo $this->formControlGroup($form->get('dateCommission'));
            echo $this->formHidden($form->get('security'));
            ?>
            <input class="btn btn-primary" type="submit" value="Enregistrer" name="submit" />
        </div>
    </div>
<?php echo $this->form()->closeTag(); ?>