<?php $this->headTitle()->append($intervenant->getNomUsuel())->append("Validation des données personnelles") ?>

<h1 class="page-header"><?php echo $title ?></h1>

<?php
use Application\Service\Message\MessageConstants as MsgId;

$classValide = $validation->getId() ? "bg-success" : null;

$this->messenger()->addMessagesFromFlashMessenger();

/**
 * Message Données perso saisies/validées ou non.
 */
if (! $this->dossier) {
    $msg = $this->message()->render(MsgId::ID_DONNEES_PERSO_PAS_SAISIES, ['intervenant' => $this->intervenant]);
    $sev = 'danger';
}
elseif ($validation->getId()) {
    $msg = $this->message()->render(MsgId::ID_DONNEES_PERSO_VALIDEES, ['validationDetails' => "<br/><br/>" . $this->validation($this->validation)]);
    $sev = 'success';
}
else {
    $msg = $this->message()->render(MsgId::ID_DONNEES_PERSO_PAS_VALIDEES, ['intervenant' => $this->intervenant]);
    $sev = 'warning';
}
$this->messenger()->addMessage($msg, $sev);

echo $this->messenger();

// si aucune données perso saisies, STOP!
if (! $this->dossier) {
    return;
}
?>

<div class="<?php echo $classValide ?>">
    <?php echo $this->partial('application/dossier/partial/form', [
        'form'     => $formModifier,
        'dossier'  => $dossier,
        'readonly' => true,
    ]) ?>
</div>

<hr />

<?php if ($this->canEdit): ?>

    <?php $form->prepare(); ?>
    <?php echo $this->form()->openTag($form); ?>
    <div class="row">
        <div class="col-md-4">
            <?php 
            echo $this->formControlGroup($form->get('valide')->setAttribute('disabled', ! $this->canEdit));
            echo $this->formHidden($form->get('security'));
            ?>
        </div>
    </div>

    <?php echo $this->formSubmit($form->get('submit')->setAttribute('class', 'btn btn-primary')) ?>
    <?php echo $this->form()->closeTag(); ?>

<?php endif ?>


<?php if ($role instanceof \Application\Acl\IntervenantRole): ?>
    <hr />
    <?php echo $this->workflow($role->getIntervenant(), $role)->navNext() ?>
<?php endif; ?>
    
