<?php $this->headTitle()->append($intervenant->getNomUsuel())->append("Validation des enseignements de type '$typeVolumeHoraire'") ?>

<h1 class="page-header"><?php echo $title ?></small></h1>

<?php echo $this->messenger()->addMessagesFromFlashMessenger()->addMessages($messages) ?>

<?php $formValider->prepare(); ?>

<style>
    th.structure, td.structure { width: 100px; }
</style>

<?php if ($validations): ?>
<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <th class="structure">Composante</th>
            <th>Validation</th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($validations as $validation): ?>
        
        <?php $servicesValidation = $this->partial('application/validation/partial/services-validation', array(
            'validation' => $validation,
            'services' => $services,
            'typeVolumeHoraire' => $typeVolumeHoraire,
        )) ?>
        
        <tr>
            <td class="structure">
                <p><?php echo $validation->getStructure() ?></p>
            </td>
            <td>
                <?php if ($validation->getId()): ?>
                    <?php echo $this->messenger()->setMessage("<br />" . $this->validationDl($validation)->setIncludeTypeValidation(true), 'success') ?>
                    <?php echo $servicesValidation ?>
                    <?php if ($this->isAllowed($validation, 'delete')): ?>
                        <a href="<?php echo $this->url('validation/supprimer', array('validation' => $validation->getId())) ?>"
                           class="validation-delete ajax-modal btn btn-primary" data-event="validation-delete-event">Supprimer cette validation</a>
                    <?php endif ?>
                <?php else: ?>
                    <?php echo $servicesValidation ?>
                    <?php if ($this->isAllowed($validation, 'create')): ?>
                        <div class="row">
                            <div class="col-md-3">
                                <?php 
                                echo $this->form()->openTag($formValider);
                                echo $this->formControlGroup($formValider->get('valide'));
                                echo $this->formHidden($formValider->get('security'));
                                echo $this->formSubmit($formValider->get('submit')->setAttribute('class', 'btn btn-primary'));
                                echo $this->form()->closeTag(); 
                                ?>
                            </div>
                        </div>
                    <?php endif ?>
                <?php endif ?>
            </td>
        </tr>
        
    <?php endforeach; ?>
    </tbody>
</table>
<?php endif; ?>


<?php if ($role instanceof \Application\Acl\IntervenantRole): ?>
    <hr />
    <?php echo $this->workflow($role->getIntervenant(), $role)->navNext() ?>
<?php endif; ?>


<script>
$(function() {
    $("body").on("validation-delete-event", function(event, data) {
        event.div.modal('hide'); // ferme la fenêtre modale
        window.location.reload();
    });
});
</script>