<h1 class="page-header"><?php echo $title ?></small></h1>

<?php $messenger = $this->messenger(true) ?>
<?php if (($validation = reset($validations)) && !$validation->getId()): ?>
    <?php $messenger->addMessage("Des enseignements à valider ont été trouvés...") ?>
<?php else: ?>
    <?php $messenger->addMessage("Aucun enseignement restant à valider n'a été trouvé.") ?>
<?php endif ?>
<?php echo $messenger ?>

<?php $formValider->prepare(); ?>

<style>
    .structure { width: 100px; }
</style>


<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <th class="structure">Composante</th>
            <th>Validation</th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($validations as $validation): ?>
        
        <?php $servicesValidation = $this->partial('application/validation/partial/services-validation', array(
            'validation' => $validation,
            'services' => $services,
            'typeVolumeHoraire' => $typeVolumeHoraire,
        )) ?>
        
        <tr>
            <td class="structure">
                <p><?php echo $validation->getStructure() ?></p>
            </td>
            <td>
                <?php if ($validation->getId()): ?>
                    <?php echo $this->messenger()->setMessage("<br />" . $this->validationDl($validation)->setIncludeTypeValidation(true), 'success') ?>
                    <?php echo $servicesValidation ?>
                    <a href="<?php echo $this->url('validation/supprimer', array('validation' => $validation->getId())) ?>"
                       class="validation-delete ajax-modal btn btn-primary" data-event="validation-delete-event">Supprimer cette validation</a>
                <?php else: ?>
                <?php // if ($formValider->getObject() === $validation): ?>
                <?php echo $servicesValidation ?>
                <div class="row">
                    <div class="col-sm-5">
                        <?php 
                        echo $this->form()->openTag($formValider);
                        echo $this->formControlGroup($formValider->get('valide')->setAttribute('disabled', $readonly));
                        if ($formValider->has('dateCommissionRecherche')) {
                            echo $this->formControlGroup($formValider->get('dateCommissionRecherche')->setAttribute('disabled', $readonly));
                        }
                        if ($formValider->has('dateConseilRestreint')) {
                            echo $this->formControlGroup($formValider->get('dateConseilRestreint')->setAttribute('disabled', $readonly));
                        }
                        echo $this->formHidden($formValider->get('security'));
                        ?>
                        <br />
                        <?php if (!$readonly) {
                            echo $this->formSubmit($formValider->get('submit')->setAttribute('class', 'btn btn-primary'));
                        } ?>
                        <?php echo $this->form()->closeTag(); ?>
                    </div>
                </div>
                <?php // endif ?>
                <?php endif ?>
            </td>
        </tr>
        
    <?php endforeach; ?>
    </tbody>
</table>

<script>
$(function() {
    $("body").on("validation-delete-event", function(event, data) {
        event.div.modal('hide'); // ferme la fenêtre modale
        window.location.reload();
    });
});
</script>