<h2 class="page-header"><?php echo $title ?></small></h2>

<?php echo $this->messenger(true) ?>

<style>
    .structure { width: 100px; }
</style>

<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <th class="structure">Composante</th>
            <th>Validation</th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($validations as $data): ?>
        
        <?php 
        $structure  = $data['structure'];
        $validation = $data['validation'];
        ?>
        
        <?php $servicesValidation = $this->partial('application/validation/partial/services-validation', array(
            'validation' => $validation,
            'services' => $services,
            'typeVolumeHoraire' => $typeVolumeHoraire,
        )) ?>
        
        <tr>
            <td class="structure"><?php echo $structure ?></td>
            <td>
                <?php if ($validation): ?>
                    <?php echo $this->messenger()->setMessage("<br />" . $this->validationDl($validation)/*->setIncludeTypeValidation(true)*/, 'success') ?>
                    <?php echo $servicesValidation ?>
                <?php else: ?>
                    Aucune
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>


<?php if ($role instanceof \Application\Acl\IntervenantRole): ?>
    <hr />
    <?php echo $this->workflow($role->getIntervenant(), $role)->navNext() ?>
<?php endif; ?>
    