<h1 class="page-header"><?php echo $title ?></h1>

<?php echo $this->messenger(true) ?>

<?php $form->prepare(); ?>
<?php if ($form->get('valide')->getValue()): ?>
    <?php echo $this->messenger()->setMessage(
            sprintf("Votre référentiel a été validé. <hr />%s", $this->validationDl($validation)), 'success') ?>
<?php else: ?>
    <?php echo $this->messenger()->setMessage("Votre référentiel n'a pas encore été validé.", 'info') ?>
<?php endif; ?>


<?php if ($role instanceof \Application\Acl\IntervenantRole): ?>
    <hr />
    <?php echo $this->workflow($role->getIntervenant(), $role)->navNext() ?>
<?php endif; ?>
    