<h1 class="page-header"><?php echo $title ?></small></h1>

<?php echo $this->messenger()->addMessagesFromFlashMessenger()->addMessages($messages) ?>

<style>
    .structure { width: 100px; }
</style>

<?php if ($data): ?>
<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <th class="structure">Composante</th>
            <th>Validation</th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($data as $array): ?>
        
        <?php 
        $structure   = $array['structure'];
        $validations = $array['validations'];
        $services    = $array['services'];
        ?>
        
        <?php if ($validations): ?>
            <?php foreach ($validations as $validation): ?>
                <tr>
                    <td class="structure"><?php echo $structure ?></td>
                    <td>
                        <?php $servicesValidation = $this->partial('application/validation/partial/services-validation', array(
                            'validation' => $validation,
                            'services' => $services,
                            'typeVolumeHoraire' => $typeVolumeHoraire,
                        )) ?>
                        <?php echo $this->messenger()->setMessage("<br />" . $this->validationDl($validation)/*->setIncludeTypeValidation(true)*/, 'success') ?>
                        <?php echo $servicesValidation ?>
                    </td>
                </tr>
            <?php endforeach; ?>
        <?php else: ?>
            <tr>
                <td class="structure"><?php echo $structure ?></td>
                <td>Aucune</td>
            </tr>
        <?php endif; ?>
            
    <?php endforeach; ?>
    </tbody>
</table>
<?php endif; ?>


<?php if ($role instanceof \Application\Acl\IntervenantRole): ?>
    <hr />
    <?php echo $this->workflow($role->getIntervenant(), $role)->navNext() ?>
<?php endif; ?>
    