<h1 class="page-header"><?php echo $title ?></h1>

<?php echo $this->messenger()->addMessagesFromFlashMessenger() ?>

<?php $form->prepare(); ?>
<?php if ($form->get('valide')->getValue()): ?>
    <?php echo $this->messenger()->setMessage(
            sprintf("Vos données personnelles ont été validées. <hr />%s", $this->validationDl($validation)), 'success') ?>
<?php else: ?>
    <?php echo $this->messenger()->setMessage("Vos données personnelles n'ont pas encore été validées.", 'info') ?>
<?php endif; ?>


<?php if ($role instanceof \Application\Acl\IntervenantRole): ?>
    <hr />
    <?php echo $this->workflow($role->getIntervenant(), $role)->navNext() ?>
<?php endif; ?>
    