<?php

use Application\Provider\Privilege\Privileges;

/* @var $serviceEtape \Application\Service\EtapeService */

$tabs = [
    [
        'id'      => 'fiche',
        'label'   => 'Fiche',
        'content' => (string)$this->etape($etape),
    ],
];

if ($this->isAllowed($etape,Privileges::ODF_CENTRES_COUT_EDITION)){
    $tabs[] = [
        'id'    => 'centres-couts',
        'label' => '<span class="fas fa-euro-sign"></span> Centres de coûts',
        'url'   => $this->url('of/etape/centres-couts', ['etape' => $etape->getId()]),
    ];
}

if ($this->isAllowed($etape,Privileges::ODF_TAUX_MIXITE_EDITION)){
    $tabs[] = [
        'id'    => 'taux-mixite',
        'label' => '<span class="fas fa-weight-scale"></span> Taux de mixité',
        'url'   => $this->url('of/etape/taux-mixite', ['etape' => $etape->getId()]),
    ];
}

if ($this->isAllowed($etape,Privileges::ODF_MODULATEURS_EDITION)){
    $tabs[] = [
        'id'    => 'modulateurs',
        'label' => '<span class="fas fa-table-list"></span> Modulateurs',
        'url'   => $this->url('of/etape/modulateurs', ['etape' => $etape->getId()]),
    ];
}

echo $this->tabajax($tabs);