<?php

use Application\Entity\Db\Dossier;
use Application\Entity\Db\WfEtape;


//$nextEtape = $validation ? WfEtape::CODE_DONNEES_PERSO_VALIDATION : WfEtape::CODE_DONNEES_PERSO_SAISIE;

$this->headTitle()->append("Nom intervenant XXX")->append("Données personnelles");

?>
    <h1 class="page-header">Données personnelles
        <small>Nom intervenant XXX</small>
    </h1>
<?php


echo $this->messenger()->addCurrentMessagesFromFlashMessenger()->addMessagesFromFlashMessenger();

$this->form()->openTag($form);
echo $this->partial('application/dossier/partial/formIdentite', compact('form'));
if (!$form->isReadOnly()){
    $this->formSubmit($this->form->get('enregistrer')->setAttribute('class', 'btn btn-primary'));
}
$this->formHidden($this->form->get('security'));
$this->form()->closeTag();
//echo $this->feuilleDeRoute($intervenant)->renderNav($nextEtape);
echo $this->partial('application/dossier/partial/formAdresse', compact('form'));
