<link href="<?php echo $this->basePath('css/fileinput.min.css') ?>" media="screen" rel="stylesheet" type="text/css"> 

<?php
$title = $this->translate("Joindre des pièces");
$this->headTitle()->append($title);
?>

<?php if (!$terminal): ?>
    <?php //echo $this->formUpload()->inlineStyle() ?>
<?php endif ?>

<?php //echo $this->formUpload($this->uploadUrl) ?>

<?php if (!$terminal): ?>
    <?php //echo $this->formUpload()->inlineScript() ?>
<?php endif ?>


<?php $form->prepare(); // The correct enctype is set here ?>
<?php echo $this->form()->openTag($form); ?>

    <div class="form-element">
        <?php $fileElement = $form->get('files'); ?>
        <?php echo $this->formLabel($fileElement); ?>
        <?php echo $this->formFile($fileElement); ?>
        <?php echo $this->formElementErrors($fileElement); ?>
    </div>

    <button>Submit</button>

<?php echo $this->form()->closeTag(); ?>

<script>
$(function() {
    $("#files").fileinput({'showUpload':false, 'previewFileType':'any', 'browseLabel': "Parcourir &hellip;"});
});
</script>
    
<?php $this->inlineScript()->prependFile($this->basePath('js/fileinput.min.js')) ?>