<?php

/* @var $this \Application\View\Renderer\PhpRenderer */

$this->headTitle()->append($this->intervenant->getNomUsuel())->append("Données personnelles");
?>

<h1 class="page-header">Données personnelles <small><?php echo $this->intervenant ?></small></h1>

<?php
use Application\Service\Message\MessageConstants as MsgId;

/**
 * Message Données perso saisies ou non.
 */
if ($this->dossier->getId()) {
    $msg = $this->message()->render(MsgId::ID_DONNEES_PERSO_SAISIES, ['intervenant' => $this->intervenant]);
    $sev = 'success';
} else {
    $msg = $this->message()->render(MsgId::ID_DONNEES_PERSO_PAS_SAISIES, ['intervenant' => $this->intervenant]);
    $sev = 'warning';
}
$this->messenger()->addMessage($msg, $sev);

/**
 * Message Données perso validées ou non.
 */
if ($this->validation) {
    $msg = $this->message()->render(MsgId::ID_DONNEES_PERSO_VALIDEES, ['validationDetails' => "<br/><br/>" . $this->validation($this->validation)]);
    $this->messenger()->addMessage($msg, 'success');
}

/**
 * Message Importance des données perso.
 */
$msg = $this->message()->render(MsgId::ID_DONNEES_PERSO_IMPORTANTES);
$this->messenger()->addMessage($msg, 'warning');

echo $this->messenger()->addMessagesFromFlashMessenger();

echo $this->partial('application/dossier/partial/form');

echo $this->feuillederoute($intervenant)->renderNextBtn(\Application\Entity\Db\WfEtape::CODE_DONNEES_PERSO_SAISIE);
