<?php $this->headTitle()->append($intervenant->getNomUsuel())->append("Données personnelles") ?>

<h1 class="page-header">Données personnelles <small><?php echo $intervenant ?></small></h1>

<?php $this->messenger()->addMessage(
        "Ces données sont indispensables pour éditer votre contrat et mettre en paiement vos heures complémentaires éventuelles.",
        'warning'); ?>

<?php
if ($validation) {
    $this->messenger()->addMessage(
            sprintf("Les données personnelles ont été validées. <br /><br />%s", $this->validationDl($validation)), 'success');
}
?>

<?php echo $this->messenger()->addMessagesFromFlashMessenger() ?>

<?php echo $this->partial('application/dossier/partial/form') ?>