<?php

/**
 * @var $this \Application\View\Renderer\PhpRenderer
 * @var $title
 * @var $action boolean
 * @var $error boolean
 */

$divId = uniqid('di-');

?>
<?php if ($action): ?>

    <?php if ($error): ?>

        <div class="alert alert-danger" role="alert">
            <?php echo $error ?>
        </div>
        
    <?php else: ?>

        <div class="alert alert-success" role="alert">
            Calcul du workflow achevé.
        </div>
        
    <?php endif; ?>

<?php else: ?>

    <div id="<?php echo $divId ?>" data-url="<?php echo $this->url('workflow/calculer-tout', [], ['query' => ['action' => '1']]) ?>">
        <img src="<?php echo $this->basePath().'/images/wait.gif' ?>" alt="Attente..."/>
        <div>En cours de calcul... Merci de patienter.</div>
    </div>
    <script>

        $(function(){
            $("#<?php echo $divId?>").refresh();
        });

    </script>

<?php endif; ?>