<?php 
$postUrl = $this->url(
    null, 
    [
        'typePieceJointe'    => $tpjs->getType()->getId(), 
        'statutIntervenant'  => $tpjs->getStatut()->getId(), 
        'premierRecrutement' => (int) $tpjs->getPremierRecrutement()], 
    [], 
    true);

$form = new \Zend\Form\Form();
$form->setAttribute('action', $postUrl);
$form->add([
    'name'    => 'obligatoire',
    'options' => [
        'label' => 'Caractère :',
        'value_options' => $this->obligatoireValueOptions,
    ],
    'type'    => 'Radio'
]);
$form->add([
    'name'    => 'seuil_heures',
    'options' => [
        'label' => 'Seuil HETD :',
    ],
    'type'    => 'Text'
]);

$tpjs = $this->tpjs; /* @var $tpjs \Application\Entity\Db\TypePieceJointeStatut */
$form->get('obligatoire')->setValue((string) $tpjs->getObligatoire());
$form->get('seuil_heures')->setValue($tpjs->getSeuilHeures());
?>

<div class="popover-content">
    <?php echo $this->form()->openTag($form); ?>
        <?php echo $this->formControlGroup($form->get('obligatoire')); ?>
        <?php echo $this->formControlGroup($form->get('seuil_heures')); ?>
        <br />
        <button type="submit" class="btn btn-default">Enregistrer</button>
    <?php echo $this->form()->closeTag(); ?>
</div>