<style>
    div.rappel-volume-horaire-prevu { display: none; }
</style>

<?php
$validation        = $this->validation; /* @var $validation \Application\Entity\Db\Validation */
$services          = $this->services;
$typeVolumeHoraire = $this->typeVolumeHoraire;
$display           = $validation->getId() ? 'display: none' : '';
$intituleConcernes = "Enseignements de type '$typeVolumeHoraire'" . ($validation->getId() ? " concernés par la validation :" : " à valider :");
?>
<p>
    <strong><?php echo $intituleConcernes ?></strong><br />
    <small><a title="Cliquez pour afficher/masquer les enseignements concernés par cette validation"
        href="#" 
        class="voir-enseignements" 
        id="validation-<?php echo $validation->getId() ?>-toggle"
        data-target="#validation-<?php echo $validation->getId() ?>"
        >Afficher/masquer</a></small>
</p>
<div style="<?php echo $display ?>" class="details-enseignements" id="validation-<?php echo $validation->getId() ?>">
    <?php echo $this->serviceListe($services[$validation->getId()])
            ->setTypeVolumeHoraire($typeVolumeHoraire)->setReadonly(true)->render(); ?>
</div>

<script>
$(function() {
    // affichage/masquage des enseignements concernés
    $("#validation-<?php echo $validation->getId() ?>-toggle").click(function() { 
        $($(this).data('target')).slideToggle(); 
        return false;
    });
});
</script>