<?php

/**
 * @var $this         \Application\View\Renderer\PhpRenderer
 * @var $notification \Indicateur\Entity\Db\NotificationIndicateur
 * @var $result       array
 *
 */

use Application\Constants;

if (!function_exists('printValue')) {
    function printValue($value)
    {
        if (is_array($value)) {
            echo '<ul>';
            foreach ($value as $val) {
                echo '<li>' . $val . '</li>';
            }
            echo '</ul>';
        } elseif ($value) {
            echo $value;
        } else {
            echo '&nbsp;';
        }
    }
}

?>

<h1><?= $notification->getIndicateur()->getLibelle(count($result)) ?></h1>
<?php
if (!$notification->getIndicateur()->isSpecial() && count($result) > 0):
    $supCols = current($result);
    unset($supCols['annee-id']);
    unset($supCols['statut-libelle']);
    unset($supCols['structure-libelle']);
    unset($supCols['prioritaire']);
    unset($supCols['intervenant-code']);
    unset($supCols['intervenant-prenom']);
    unset($supCols['intervenant-nom']);
    unset($supCols['intervenant-email-pro']);
    unset($supCols['intervenant-email-perso']);
    $supCols = array_keys($supCols);

    ?>
    <table border="1" style="border-collapse: collapse">
        <thead>
        <tr>
            <th>Prioritaire</th>
            <th>Composante</th>
            <th>Intervenant</th>
            <?php foreach ($supCols as $supCol): ?>
                <th><?= $supCol ?></th>
            <?php endforeach; ?>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($result as $intervenantId => $r): ?>
            <tr>
                <td style="text-align: center"><?= $r['prioritaire'] ? 'P*' : '' ?></td>
                <td><?php printValue($r['structure-libelle']); ?></td>
                <td>
                    <a href="<?= $host . $this->url($notification->getIndicateur()->getRoute(), ['intervenant' => $intervenantId]) ?>">
                        <?= $r['intervenant-nom'] . ' ' . $r['intervenant-prenom'] . ' <small>(n°' . $r['intervenant-code'] . ' / ' . $r['statut-libelle'] . ')</small>' ?>
                    </a>
                </td>
                <?php foreach ($supCols as $supCol): ?>
                    <td><?php printValue($r[$supCol]); ?></td>
                <?php endforeach; ?>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
<?php else: ?>
<a href="<?= $host . $this->url($notification->getIndicateur()->getRoute(),[]); ?>">Pour vous rendre sur OSE, veuillez cliquer sur ce lien.</a>
<?php endif; ?>
<p>
    Vous vous êtes abonné(e) à cet indicateur
    le <?= $notification->getDateAbonnement()->format(Constants::DATETIME_FORMAT) ?>.<br/>
    <a href="<?= $host . $this->url('indicateur') ?>"
       title="Cliquez pour vous rendre à la page de gestion de vos abonnements aux indicateurs">Gérer vos abonnements à
        des indicateurs</a>
</p>