<?php
/**
 * Generated by UnicaenCode
 * Commande : php public/index.php UnicaenCode  module='Intervenant'
 */
return [
    'Intervenant\Assertion\NoteAssertion'               => __DIR__ . '/src/Assertion/NoteAssertion.php',
    'Intervenant\Assertion\StatutAssertion'             => __DIR__ . '/src/Assertion/StatutAssertion.php',
    'Intervenant\Assertion\StatutAssertionFactory'      => __DIR__ . '/src/Assertion/StatutAssertionFactory.php',
    'Intervenant\Controller\NoteController'             => __DIR__ . '/src/Controller/NoteController.php',
    'Intervenant\Controller\NoteControllerFactory'      => __DIR__ . '/src/Controller/NoteControllerFactory.php',
    'Intervenant\Controller\StatutController'           => __DIR__ . '/src/Controller/StatutController.php',
    'Intervenant\Controller\StatutControllerFactory'    => __DIR__ . '/src/Controller/StatutControllerFactory.php',
    'Intervenant\Entity\Db\Note'                        => __DIR__ . '/src/Entity/Db/Note.php',
    'Intervenant\Entity\Db\Statut'                      => __DIR__ . '/src/Entity/Db/Statut.php',
    'Intervenant\Entity\Db\TypeIntervenant'             => __DIR__ . '/src/Entity/Db/TypeIntervenant.php',
    'Intervenant\Entity\Db\TypeNote'                    => __DIR__ . '/src/Entity/Db/TypeNote.php',
    'Intervenant\Form\MailerIntervenantForm'            => __DIR__ . '/src/Form/MailerIntervenantForm.php',
    'Intervenant\Form\MailerIntervenantFormFactory'     => __DIR__ . '/src/Form/MailerIntervenantFormFactory.php',
    'Intervenant\Form\NoteSaisieForm'                   => __DIR__ . '/src/Form/NoteSaisieForm.php',
    'Intervenant\Form\NoteSaisieFormFactory'            => __DIR__ . '/src/Form/NoteSaisieFormFactory.php',
    'Intervenant\Form\StatutSaisieForm'                 => __DIR__ . '/src/Form/StatutSaisieForm.php',
    'Intervenant\Form\StatutSaisieFormFactory'          => __DIR__ . '/src/Form/StatutSaisieFormFactory.php',
    'Intervenant\Module'                                => __DIR__ . '/Module.php',
    'Intervenant\Service\MailService'                   => __DIR__ . '/src/Service/MailService.php',
    'Intervenant\Service\MailServiceFactory'            => __DIR__ . '/src/Service/MailServiceFactory.php',
    'Intervenant\Service\NoteService'                   => __DIR__ . '/src/Service/NoteService.php',
    'Intervenant\Service\NoteServiceFactory'            => __DIR__ . '/src/Service/NoteServiceFactory.php',
    'Intervenant\Service\StatutService'                 => __DIR__ . '/src/Service/StatutService.php',
    'Intervenant\Service\StatutServiceFactory'          => __DIR__ . '/src/Service/StatutServiceFactory.php',
    'Intervenant\Service\TypeIntervenantService'        => __DIR__ . '/src/Service/TypeIntervenantService.php',
    'Intervenant\Service\TypeIntervenantServiceFactory' => __DIR__ . '/src/Service/TypeIntervenantServiceFactory.php',
    'Intervenant\Service\TypeNoteService'               => __DIR__ . '/src/Service/TypeNoteService.php',
    'Intervenant\Service\TypeNoteServiceFactory'        => __DIR__ . '/src/Service/TypeNoteServiceFactory.php',
];