<?php
/**
 * Generated by UnicaenCode
 * Commande : php public/index.php UnicaenCode  module='Intervenant'
 */
return [
    'intervenant/statut/saisie'      => __DIR__ . '/view/intervenant/statut/saisie.phtml',
    'intervenant/statut/index'       => __DIR__ . '/view/intervenant/statut/index.phtml',
    'intervenant/note/voir'          => __DIR__ . '/view/intervenant/note/voir.phtml',
    'intervenant/note/saisir'        => __DIR__ . '/view/intervenant/note/saisir.phtml',
    'intervenant/note/envoyer-email' => __DIR__ . '/view/intervenant/note/envoyer-email.phtml',
    'intervenant/note/index'         => __DIR__ . '/view/intervenant/note/index.phtml',
];