<?php
/**
 * Generated by UnicaenCode
 * Commande : php public/index.php UnicaenCode  module='Intervenant'
 */
return [
    'intervenant/statut/saisie'                  => __DIR__ . '/view/intervenant/statut/saisie.phtml',
    'intervenant/statut/index'                   => __DIR__ . '/view/intervenant/statut/index.phtml',
    'intervenant/corps/saisie'                   => __DIR__ . '/view/intervenant/corps/saisie.phtml',
    'intervenant/corps/index'                    => __DIR__ . '/view/intervenant/corps/index.phtml',
    'intervenant/grade/saisie'                   => __DIR__ . '/view/intervenant/grade/saisie.phtml',
    'intervenant/grade/index'                    => __DIR__ . '/view/intervenant/grade/index.phtml',
    'intervenant/note/voir'                      => __DIR__ . '/view/intervenant/note/voir.phtml',
    'intervenant/note/saisir'                    => __DIR__ . '/view/intervenant/note/saisir.phtml',
    'intervenant/note/envoyer-email'             => __DIR__ . '/view/intervenant/note/envoyer-email.phtml',
    'intervenant/note/index'                     => __DIR__ . '/view/intervenant/note/index.phtml',
    'intervenant/intervenant/supprimer'          => __DIR__ . '/view/intervenant/intervenant/supprimer.phtml',
    'intervenant/intervenant/fiche'              => __DIR__ . '/view/intervenant/intervenant/fiche.phtml',
    'intervenant/intervenant/rechercher'         => __DIR__ . '/view/intervenant/intervenant/rechercher.phtml',
    'intervenant/intervenant/voir'               => __DIR__ . '/view/intervenant/intervenant/voir.phtml',
    'intervenant/intervenant/recherche'          => __DIR__ . '/view/intervenant/intervenant/recherche.phtml',
    'intervenant/intervenant/saisir'             => __DIR__ . '/view/intervenant/intervenant/saisir.phtml',
    'intervenant/intervenant/choisir'            => __DIR__ . '/view/intervenant/intervenant/choisir.phtml',
    'intervenant/intervenant/menu'               => __DIR__ . '/view/intervenant/intervenant/menu.phtml',
    'intervenant/intervenant/synchronisation'    => __DIR__ . '/view/intervenant/intervenant/synchronisation.phtml',
    'intervenant/intervenant/liste'              => __DIR__ . '/view/intervenant/intervenant/liste.phtml',
    'intervenant/intervenant/index'              => __DIR__ . '/view/intervenant/intervenant/index.phtml',
    'intervenant/intervenant/apercevoir'         => __DIR__ . '/view/intervenant/intervenant/apercevoir.phtml',
    'intervenant/intervenant/definir-par-defaut' => __DIR__ . '/view/intervenant/intervenant/definir-par-defaut.phtml',
];