<?php 
use Application\Service\Indicateur\AbstractIntervenantResultIndicateurImpl;
use Common\Constants;
/* @var $indicateurImpl AbstractIntervenantResultIndicateurImpl */
?>

<h1 class="page-header"><?php echo $indicateurImpl->getTitle() ?></h1>

<?php echo $this->partial('application/indicateur/partial/result', ['indicateurImpl' => $indicateurImpl]); ?>

<p>
    Vous vous êtes abonné(e) à cet indicateur le <?php echo $this->ni->getDateAbonnement()->format(Constants::DATETIME_FORMAT) ?>.<br />
    <a href="<?php echo $this->url('indicateur', [], ['force_canonical' => true]) ?>" 
       title="Cliquez pour vous rendre à la page de gestion de vos abonnements aux indicateurs">Gérer vos abonnements à des indicateurs</a>
</p>