<?php 
use Application\Service\Indicateur\AbstractIndicateurImpl;
use Common\Constants;
/* @var $indicateurImpl AbstractIndicateurImpl */
?>

<h1 class="page-header"><?php echo $indicateurImpl->getTitle() ?></h1>

<ul>
<?php foreach ($indicateurImpl->getResult() as $r): ?>
    <li><a href="<?php echo $indicateurImpl->getResultUrl($r) ?>"
           title="Cliquez pour vous rendre à la page concernée"
           ><?php echo $indicateurImpl->getResultFormatter()->filter($r) ?></a></li>
<?php endforeach; ?>
</ul>

<p>
    Vous vous êtes abonné(e) à cet indicateur le <?php echo $this->ni->getDateAbonnement()->format(Constants::DATETIME_FORMAT) ?>.<br />
    <a href="<?php echo $this->url('indicateur', [], ['force_canonical' => true]) ?>" 
       title="Cliquez pour vous rendre à la page de gestion de vos abonnements aux indicateurs">Gérer vos abonnements à des indicateurs</a>
</p>