<?php 
use Application\Service\Indicateur\AbstractIndicateurImpl;
/* @var $indicateurImpl AbstractIndicateurImpl */
?>

<h1 class="page-header"><?php echo $indicateurImpl->getTitle() ?></h1>

<ul>
<?php foreach ($indicateurImpl->getResult() as $r): ?>
    <li><a href="<?php echo $indicateurImpl->getResultUrl($r) ?>"
           title="Cliquez pour vous rendre à la page concernée"><?php echo $r ?></a></li>
<?php endforeach; ?>
</ul>