<?php

use Application\Provider\Privileges;

/**
 * @var $this        \Application\View\Renderer\PhpRenderer
 * @var $annee       \Application\Entity\Db\Annee
 * @var $joursFeries \Paiement\Entity\Db\JourFerie[]
 */

$this->headTitle("Jours fériés $annee");

$canEdit = $this->isAllowed(Privileges::getResourceId(Privileges::JOUR_FERIE_EDITION));


function dateFr(\DateTime $date)
{
    $days = [
        'Monday'    => 'Lundi',
        'Tuesday'   => 'Mardi',
        'Wednesday' => 'Mercredi',
        'Thursday'  => 'Jeudi',
        'Friday'    => 'Vendredi',
        'Saturday'  => 'Samedi',
        'Sunday'    => 'Dimanche',
    ];

    $months = [
        'January'   => 'Janvier',
        'February'  => 'Février',
        'March'     => 'Mars',
        'April'     => 'Avril',
        'May'       => 'Mai',
        'June'      => 'Juin',
        'July'      => 'Juillet',
        'August'    => 'Août',
        'September' => 'Septembre',
        'October'   => 'Octobre',
        'November'  => 'Novembre',
        'Décember'  => 'Décembre',
    ];

    $jour = str_replace(array_keys($days), array_values($days), $date->format('l'));
    $numJour = $date->format('j');
    if ($numJour == '1') $numJour .= '<sup>er</sup>';

    $mois = str_replace(array_keys($months), array_values($months), $date->format('F'));

    return $jour . ' ' . $numJour . ' ' . $mois . ' ' . $date->format('Y');
}

?>
    <h1>Jours fériés <?= $annee ?></h1>
    <table class="table table-bordered">
        <tr>
            <th>Date</th>
            <th>Libellé</th>
            <?php if ($canEdit): ?>
                <th>Actions</th><?php endif; ?>
        </tr>
        <?php foreach ($joursFeries as $jourFerie): ?>
            <tr>
                <td><?= dateFr($jourFerie->getDateJour()) ?></td>
                <td><?= $jourFerie->getLibelle() ?></td>
                <?php if ($canEdit): ?>
                    <td>
                    <a class="mod-ajax" data-submit-reload="true"
                       href="<?= $this->url('jour-ferie/saisie', ['jourFerie' => $jourFerie->getId()]) ?>"
                       title="Modifier le jour férié">
                        <i class="fas fa-pen-to-square"></i></a>
                    <a class="pop-ajax"
                       href="<?= $this->url('jour-ferie/delete', ['jourFerie' => $jourFerie->getId()]) ?>"
                       title="Supprimer le jour férié"
                       data-content="<p class='lead text-danger'><strong>Attention!</strong> Confirmez-vous cette suppression ?</p>"
                       data-confirm="true"
                       data-confirm-button="Oui"
                       data-cancel-button="Non"
                       data-submit-reload="true"
                    ><i class="fas fa-trash-can"></i></a>
                    </td><?php endif; ?>
            </tr>
        <?php endforeach; ?>
    </table>

<?php if ($canEdit): ?>
    <a class="mod-ajax" data-submit-reload="true"
       href="<?= $this->url('jour-ferie/saisie') ?>"
       title="Ajouter un nouveau jour férié">
        <button type="button" class="btn btn-sm btn-primary">Ajouter un jour férié</button>
    </a>
<?php endif; ?>