<?php

/**
 * @var $this       \Application\View\Renderer\PhpRenderer
 * @var $etape      \OffreFormation\Entity\Db\Etape
 * @var $scenario   \Chargens\Entity\Db\Scenario
 * @var $filtre     \Chargens\Form\FiltreForm
 */

?>
<h1 class="page-header">Charges d'enseignement</h1>
<script type="text/javascript" src="<?= $this->basePath('/ext/go.js') ?>"></script>
<script type="text/javascript" src="<?= $this->basePath('/js/chargens.js') ?>"></script>
<?php

echo $this->chargens()->setFormFiltre($filtre)->render();
?>
<a class="btn btn-secondary" href="<?= $this->url('chargens'); ?>">
    <i class="fas fa-rotate-left" aria-hidden="true"></i>
    Retour au menu des charges d'enseignement
</a>
