<?php

/**
 * @var $this \Application\View\Renderer\PhpRenderer
 * @var $pages array|\Framework\Navigation\Page[]
 */

$title = "Charges d'enseignement";

$this->headTitle()->append($title);

?>
    <h1 class="page-header"><?= $title ?></h1>
<dl>
    <?php
    foreach ($pages as $page) {
        echo '<dt><a href="' . $page->getUri() . '">' . $page->getLabel() . '</a></dt>';
        echo '<dd>' . $page->getData('description') . '</dd>';
    }
    ?>
</dl>
<style>

    dt {
        padding-top: 2em;
    }

</style>