<?php

/**
 * @var $container Laminas\Navigation\Navigation
 */


// USAGE dans une vue : echo $this->navigation('navigation')->menuContextuel()->setPartial('unicaen-app/menu-dl.phtml');
?>
<dl>
    <?php
    foreach ($container as $page) {
        $page->setVisible(true);
        if ($this->navigation()->accept($page)) {
            echo $this->tag('dt')->html( $this->navigation()->htmlify($page) );
            echo $this->tag('dd')->text( $page->get('description') );
        }
    }
    ?>
</dl>
<style>

    dt {
        padding-top: 2em;
    }

</style>