<?php
/**
 * @var $this                     \Application\View\Renderer\PhpRenderer
 * @var $modulateurs              \Application\Entity\Db\modulateur[]
 * @var $typeModulateurs          \Application\Entity\Db\typeModulateur[]
 * @var $typeModulateurStructures \Application\Entity\Db\typeModulateurStructure[]
 */

use Application\Provider\Privilege\Privileges;
use UnicaenApp\Util;

function affBooleen($flg)
{
    // affiche booléen avec des glypheIcon
    return ($flg ? '<span class="glyphicon glyphicon-ok text-success"></span>' : '<span class="glyphicon glyphicon-remove text-danger refuse"></span>');
}

$this->headTitle()->append("Modulateurs des taux horaires");

$canEdit = $this->isAllowed(Privileges::getResourceId(Privileges::MODULATEUR_EDITION));

?>
<h1 class="page-header">Modulateurs des taux horaires</h1>
<?php
foreach ($typeModulateurs as $tm) {
    if ($this->isAllowed($tm, Privileges::MODULATEUR_VISUALISATION)) { ?>
        <div class="panel panel-default">
            <div class="panel-heading">
                <div class="panel-title"><?= $tm->getCode() ?>
                    <span style="position:absolute; left: 300px"><?= $tm->getLibelle() ?></span>
                    <span style="position:absolute; right: 50px;">

        <?php if ($canEdit): ?>
            <a class="ajax-modal" data-event="modulateur-saisie"
               href="<?= $this->url('modulateur/saisie', ['typeModulateur' => $tm->getId()]) ?>"
               title="Ajouter un modulateur">
                <span class="glyphicon glyphicon-plus"></span>
            </a>
        <?php endif ?>
                        <a class="ajax-modal" data-event="modulateur-saisie"
                           href="<?= $this->url('modulateur/type-modulateur-saisie', ['typeModulateur' => $tm->getId()]) ?>"
                           title="Modifier le type de modulateur">
                        <span class="glyphicon glyphicon-edit"></span></a>
        <a class="pop-ajax"
           href="<?= $this->url('modulateur/type-modulateur-delete', ['typeModulateur' => $tm->getId()]) ?>"
           title="Supprimer le type de modulateur"
           data-content="<p class='lead text-danger'><strong>Attention!</strong> Confirmez-vous cette suppression ?</p>"
           data-confirm="true"
           data-confirm-button="Oui"
           data-cancel-button="Non"
           data-submit-reload="true"
        >
            <span class="glyphicon glyphicon-remove"></span>
        </a>
                </span>
                </div>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-3">
                        <div class="row">
                            <div class="col-md-9">Publique :</div>
                            <div class="col-md-3"><?= affBooleen($tm->getPublique()) ?></div>
                        </div>
                        <div class="row">
                            <div class="col-md-9">Obligatoire :</div>
                            <div class="col-md-3"><?= affBooleen($tm->getObligatoire()) ?></div>
                        </div>
                        <div class="row">
                            <div class="col-md-9">Saisie par ens:</div>
                            <div class="col-md-3"><?= affBooleen($tm->getSaisieParEnseignant()) ?></div>
                        </div>
                        <table class="table table-bordered">
                        <?php foreach ($typeModulateurStructures
                                       as $tms) { ?>
                            <?php if ($tm->getId() == $tms->getTypeModulateur()->getId()) { ?>
                                <tr>
                                    <td>
                                        <?php if (($tms->getAnneeDebut()) || ($tms->getAnneeFin())) {
                                            if (!$tms->getAnneeDebut()) {
                                                $infoBulle = ' à ' . $tms->getAnneeFin();
                                            } else {
                                                if (!$tms->getAnneeFin()) {
                                                    $infoBulle = ' de ' . $tms->getAnneeDebut();
                                                } else $infoBulle = ' de ' . $tms->getAnneeDebut() . ' à ' . $tms->getAnneeFin();
                                            }
                                        } else $infoBulle = ''; ?>
                                        <?php echo ($infoBulle ? '<abbr title="' . $infoBulle . '">' : '') . $tms->getStructure()->getLibelleCourt();
                                        echo($infoBulle ? '</abbr>' : '');
                                        if ($canEdit) { ?>
                                            <a style="position:absolute; right: 20px;" pop-ajax"
                                               href="<?= $this->url('modulateur/type-modulateur-structure-delete', ['typeModulateurStructure' => $tms->getId()]) ?>"
                                               title="Supprimer le type de modulateur pour la structure"
                                               data-content="<p class='lead text-danger'><strong>Attention!</strong> Confirmez-vous cette suppression ?</p>"
                                               data-confirm="true"
                                               data-confirm-button="Oui"
                                               data-cancel-button="Non"
                                               data-submit-reload="true"
                                            >
                                                <span class="glyphicon glyphicon-remove text-danger"></span>
                                            </a>
                                        <?php } ?>
                                    </td>
                                </tr>
                            <?php }
                        } ?>
                        </table>
                        <?php if ($canEdit) { ?>
                            <a class="ajax-modal" data-event="modulateur-saisie"
                                       href="<?= $this->url('modulateur/type-modulateur-structure-saisie', ['typeModulateur' => $tm->getId()]) ?>"
                                       title="Ajouter un type de modulateur pour une structure">
                                        <button type="button" class="btn-xs btn-primary">Ajouter</button>
                                    </a>
                        <?php } ?>
                    </div>
                    <div class="col-md-9">
                        <table class="table table-bordered">
                            <thead>
                            <th>Code</th>
                            <th>Libelle</th>
                            <th>Taux service</th>
                            <th>Taux heures compl.</th>
                            <?php if ($canEdit) { ?>
                                <th>Actions</th>
                            <?php } ?>
                            </thead>
                            <tbody>
                            <?php foreach ($modulateurs as $modu) {
                                if ($tm->getId() == $modu->getTypeModulateur()->getId()) { ?>
                                    <tr>
                                        <td><?= $modu->getCode() ?></td>
                                        <td><?= $modu->getLibelle() ?></td>
                                        <td><?= Util::formattedNumber($modu->getPonderationServiceDu()) ?></td>
                                        <td><?= Util::formattedNumber($modu->getPonderationServiceCompl()) ?></td>
                                        <?php if ($canEdit) { ?>
                                            <td style="text-align:center;width:1px;white-space: nowrap">
                                                <a class="ajax-modal" data-event="modulateur-saisie"
                                                   href="<?= $this->url('modulateur/saisie', ['typeModulateur' => $tm->getId(), 'modulateur' => $modu->getId()]) ?>"
                                                   title="Modifier le modulateur">
                                                    <span class="glyphicon glyphicon-edit"></span></a>
                                                <a class="pop-ajax"
                                                   href="<?= $this->url('modulateur/delete', ['modulateur' => $modu->getId()]) ?>"
                                                   title="Supprimer le modulateur"
                                                   data-content="<p class='lead text-danger'><strong>Attention!</strong> Confirmez-vous cette suppression ?</p>"
                                                   data-confirm="true"
                                                   data-confirm-button="Oui"
                                                   data-cancel-button="Non"
                                                   data-submit-reload="true"
                                                >
                                                    <span class="glyphicon glyphicon-remove"></span>
                                                </a>
                                            </td>
                                        <?php } ?>
                                    </tr>
                                <?php }
                            } ?>
                            </tbody>
                        </table>
                    </div>

                </div>

            </div>
        </div>
        <?php
    }
} ?>
<?php if (($canEdit) && (!$structure)) : ?>
    <a class="btn btn-primary ajax-modal" data-event="modulateur-saisie"
       href="<?= $this->url('modulateur/type-modulateur-saisie', []) ?>"
       title="Ajouter un type de modulateur">
        <span class="glyphicon glyphicon-edit"></span>
        Ajouter un type de modulateur</a>
    <script type="text/javascript">
        $(function () {
            $("body").on("modulateur-saisie", function (event, data) {
                window.location.reload();
            });
        });
    </script>
<?php endif ?>
