<?php

use Application\Provider\Privilege\Privileges;

/**
 * @var $this    \Application\View\Renderer\PhpRenderer
 * @var $statuts \Intervenant\Entity\Db\Statut[]
 */

$canEdit = $this->isAllowed(Privileges::getResourceId(Privileges::INTERVENANT_STATUT_EDITION));

echo $this->messenger()->addCurrentMessagesFromFlashMessenger();

$this->headTitle()->append($title = "Statuts des intervenants");

?>
<h1 class="page-header"><?php echo $title ?></h1>

<table class="table table-bordered table-hover table-condensed">
    <head>
        <tr>
            <th>Type d'intervenant</th>
            <th>Code</th>
            <th>Libellé</th>
            <?php if ($canEdit): ?>
                <th>Actions</th>
            <?php endif; ?>
        </tr>
    </head>
    <body>
    <?php foreach ($statuts as $statut): ?>
        <tr class="statut" data-id="<?= $statut->getId() ?>">
            <td><?= $statut->getTypeIntervenant() ?></td>
            <td><?= $statut->getCode() ?></td>
            <td><?= $statut->getLibelle() ?></td>
            <?php if ($canEdit): ?>
                <th style="text-align: center">
                    <a href="<?= $this->url('statut/saisie', ['statut' => $statut->getId()]) ?>" title="Modifier le statut">
                        <span class="glyphicon glyphicon-edit"></span>
                    </a>

                    <a class="pop-ajax"
                       href="<?= $this->url('statut/delete', ['statut' => $statut->getId()]) ?>"
                       title="Supprimer le statut"
                       data-content="<p class='lead text-danger'><strong>Attention!</strong> Confirmez-vous cette suppression ?</p>"
                       data-confirm="true"
                       data-confirm-button="Oui"
                       data-cancel-button="Non"
                       data-submit-reload="true"
                    >
                        <span class="glyphicon glyphicon-trash"></span>
                    </a>

                    <a role="button" data-toggle="collapse" title="Vous pouvez trier les statuts en déplaçant les lignes">
                        <i class="fa fa-arrows-alt"></i>
                    </a>
                </th>
            <?php endif; ?>
        </tr>
    <?php endforeach; ?>
    </body>
</table>

<?php if ($canEdit): ?>
    <a class="btn btn-primary" href="<?= $this->url('statut/saisie') ?>" title="Ajouter un statut">
        <span class="glyphicon glyphicon-plus"></span> Ajouter un statut
    </a>

    <script type="text/javascript">
        $(function () {
            function injecte(element)
            {
                var ancre = '#c_' + $(element).data('id');
                var ti = $(element).data('id');
                adr = "<?php echo $this->url('statut/saisie') ?>" + "/" + ti;
                $(ancre).load(adr);
            }

            $(function () {
                $(".triables").sortable({
                    handle: '.fa-arrows-alt',
                    axis: 'y',
                    update: function (event, ui) {
                        var champsIds = '';
                        ui.item.parent().find('div.champ-triable').each(function () {
                            if (champsIds != '') champsIds += ',';
                            console.log($(this)[0]['id']);
                            champsIds += $(this)[0]['id'];
                        });
                        $.post(Url('statut/trier'), {champsIds: champsIds}).done(function (res) {
                            alertFlash(res.msg, 'success', 3000);
                        });
                    }
                });
            });
        });
    </script>
<?php endif; ?>
