<?php

use Application\Provider\Privilege\Privileges;

/**
 * @var $this  \Application\View\Renderer\PhpRenderer
 * @var $form  \Intervenant\Form\StatutSaisieForm
 */

$canEdit = $this->isAllowed(Privileges::getResourceId(Privileges::INTERVENANT_STATUT_EDITION));
echo $this->form()->openTag($form); ?>

<style>
    .temoins {
        margin-left: 0px;
    }

    .temoins .form-group {
        margin-bottom: 1px;
    }

    .temoins .form-group .checkbox {
        margin-top: 1px;
        margin-bottom: 1px;
    }

    .atvb {
        margin-top: 20px;
    }

    .hetd {
        background-color: white;
        vertical-align: bottom;
        border-width: 0;
    }

</style>
<div class="panel panel-default">
    <div class="panel-body">
        <div class="row">
            <div class="col-md-9">
                <div class="row">
                    <div class="col-md-4">
                        <?= $this->formHidden($form->get('id')); ?>
                        <?= $this->formControlGroup($form->get('type-intervenant')); ?>
                    </div>
                    <div class="col-md-8">
                        <?= $this->formControlGroup($form->get('libelle')); ?>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <?= $this->formControlGroup($form->get('code')); ?>
                    </div>
                    <div class="col-md-4">
                        <?= $this->formControlGroup($form->get('code_rh')); ?>
                    </div>
                    <div class="col-md-1 atvb">
                        <?= $this->formControlGroup($form->get('TEM-ATV')); ?>
                    </div>
                    <div class="col-md-1 atvb">
                        <?= $this->formControlGroup($form->get('TEM-VA')); ?>
                    </div>
                    <div class="col-md-2 atvb">
                        <?= $this->formControlGroup($form->get('TEM-BIATSS')); ?>
                    </div>
                </div>


                <div class="row temoins">
                    <?= $this->formControlGroup($form->get('non-autorise')); ?>
                    <?= $this->formControlGroup($form->get('depassement')); ?>
                    <?= $this->formControlGroup($form->get('peut-saisir-referentiel')); ?>
                    <?= $this->formControlGroup($form->get('peut-saisir-service')); ?>
                    <?= $this->formControlGroup($form->get('peut-choisir-dans-dossier')); ?>
                    <?= $this->formControlGroup($form->get('peut-avoir-contrat')); ?>
                    <?= $this->formControlGroup($form->get('peut-saisir-dossier')); ?>
                    <?= $this->formControlGroup($form->get('peut-saisir-motif-non-paiement')); ?>
                    <?= $this->formControlGroup($form->get('peut-cloturer-saisie')); ?>
                    <?= $this->formControlGroup($form->get('peut-saisir-service-ext')); ?>
                    <?= $this->formControlGroup($form->get('depassement-sdshc')); ?>
                    <?= $this->formControlGroup($form->get('prioritaire-indicateurs')); ?>
                    <br/>
                </div>
                <!--Uniquement si le statut existe déjà en base (avec un id)-->
                <?php if (empty($form->get('id')->getValue())): ?>
                <div class="row temoins hidden">
                    <?php else: ?>
                    <div class="row temoins">
                        <?php endif; ?>
                        <fieldset>
                            <legend style="font-size: 14px;font-weight: 700;">Gestion des agréments pour le statut :</legend>
                            <table class="table table-bordered">
                                <thead>
                                <th></th>
                                <th>Activé</th>
                                <th>Valable pendant</th>
                                </thead>
                                <tbody>
                                <?php foreach ($form->getElements() as $element): ?>
                                    <?php if (preg_match('#^CONSEIL[A-Z_]+\b(?!-DUREE_VIE)#', $element->getName())): ?>

                                        <tr>
                                            <td><?= $this->formLabel($form->get($element->getName())); ?></td>
                                            <td><?= $this->formRadio($form->get($element->getName())); ?></td>
                                            <td><?= $this->formControlGroup($form->get($element->getName() . '-DUREE_VIE')); ?></td>
                                        </tr>
                                    <?php endif; ?>
                                <?php endforeach; ?>
                                </tbody>
                            </table>
                        </fieldset>

                    </div>
                    <div class="row temoins">
                        <fieldset>
                            <legend style="font-size: 14px;font-weight: 700;">Paramétrage des modules du dossier
                                intervenant :
                            </legend>
                            <table class="table table-bordered">
                                <thead>
                                <th>Activer</th>
                                <th>Module</th>
                                </thead>
                                <tbody>
                                <tr>
                                    <td><?= $this->formElement($form->get('dossier-identite-complementaire')); ?></td>
                                    <td><?= $form->get('dossier-identite-complementaire')->getLabel(); ?></td>
                                </tr>
                                <tr>
                                    <td><?= $this->formElement($form->get('dossier-adresse')); ?></td>
                                    <td><?= $form->get('dossier-adresse')->getLabel(); ?></td>
                                </tr>
                                <tr>
                                    <td><?= $this->formElement($form->get('dossier-contact')); ?></td>
                                    <td><?= $form->get('dossier-contact')->getLabel(); ?></td>
                                </tr>
                                <tr>
                                    <td><?= $this->formElement($form->get('dossier-insee')); ?></td>
                                    <td><?= $form->get('dossier-insee')->getLabel(); ?></td>
                                </tr>
                                <tr>
                                    <td><?= $this->formElement($form->get('dossier-iban')); ?></td>
                                    <td><?= $form->get('dossier-iban')->getLabel(); ?></td>
                                </tr>
                                <tr>
                                    <td><?= $this->formElement($form->get('dossier-employeur')); ?></td>
                                    <td><?= $form->get('dossier-employeur')->getLabel(); ?></td>
                                </tr>
                                </tbody>
                            </table>

                        </fieldset>
                        <br/>
                    </div>
                    <?php if (empty($form->get('id')->getValue())): ?>
                    <div class="row temoins hidden">
                        <?php else: ?>
                        <div class="row temoins">
                            <?php endif; ?>

                            <fieldset>
                                <legend style="font-size: 14px;font-weight: 700;">Activation des champs personnalisables du
                                    dossier
                                    intervenant :
                                </legend>
                                <table class="table table-bordered">
                                    <thead>
                                    <th>Activer</th>
                                    <th>Libellé</th>
                                    <th>Obligatoire</th>
                                    <th>Description</th>
                                    </thead>
                                    <tbody>
                                    <?php foreach ($champsAutres as $champ): ?>
                                        <tr>
                                            <td><?= $this->formElement($form->get('champ-autre-' . $champ->getId())); ?></td>
                                            <td><?= $champ->getLibelle(); ?></td>
                                            <td><?= ($champ->isObligatoire()) ? 'OUI' : 'NON'; ?></td>
                                            <td><?= $champ->getDescription(); ?></td>
                                        </tr>
                                    <?php endforeach; ?>
                                    <tr>
                                        <td></td>
                                    </tr>
                                    </tbody>
                                </table>

                            </fieldset>
                            <br/>
                        </div>
                        <!--Régles sur les informations contact du dossier intervenant-->
                        <div class="row temoins">
                            <fieldset>
                                <legend style="font-size: 14px;font-weight: 700;">Règles sur les informations de contact du
                                    dossier intervenant :
                                </legend>
                                <table class="table table-bordered">
                                    <thead>
                                    <th>Activer</th>
                                    <th>Description</th>
                                    </thead>
                                    <tbody>
                                    <tr>
                                        <td><?= $this->formElement($form->get('dossier-email-perso')); ?></td>
                                        <td><?= $form->get('dossier-email-perso')->getLabel(); ?></td>
                                    </tr>
                                    <tr>
                                        <td><?= $this->formElement($form->get('dossier-tel-perso')); ?></td>
                                        <td><?= $form->get('dossier-tel-perso')->getLabel(); ?></td>
                                    </tr>
                                    </tbody>
                                </table>

                            </fieldset>
                            <br/>
                        </div>


                        <div class="row">
                            <?= $this->formElement($form->get('security')); ?>
                            <?php if ($canEdit) echo $this->formSubmit($form->get('submit')); ?>
                            <?php if (($canEdit) && ($form->get('id')->getValue())) { ?>
                                <a class="pop-ajax btn btn-danger" data-event="statut-clone"
                                   href="<?php echo $this->url('statut/delete', ['statut' => $form->get('id')->getValue()]) ?>"
                                   title="Supprimer le statut d'intervenant"
                                   data-content="<p class='lead text-danger'><strong>Attention!</strong> Confirmez-vous cette suppression ?</p>"
                                   data-confirm="true" data-confirm-button="Oui"
                                   data-cancel-button="Non"
                                   data-submit-reload="true">
                                    <span class="glyphicon glyphicon-trash"></span> Supprimer</a>
                                <a class="ajax-modal btn btn-warning" data-event="statut-clone"
                                   href="<?php echo $this->url('statut/clone', ['statut' => $form->get('id')->getValue()]) ?>"
                                   title="Dupliquer le statut d'intervenant">
                                    <span class="glyphicon glyphicon-repeat"></span> Dupliquer</a>
                            <?php } ?>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <?= $this->formControlGroup($form->get('service-statutaire')); ?>
                        <?= $this->formControlGroup($form->get('plafond-referentiel')); ?>
                        <?= $this->formControlGroup($form->get('plafond-referentiel-service')); ?>
                        <?= $this->formControlGroup($form->get('plafond-referentiel-hc')); ?>
                        <?= $this->formControlGroup($form->get('maximum-HETD')); ?>
                        <?= $this->formControlGroup($form->get('charges-patronales')); ?>
                        <?= $this->formControlGroup($form->get('plafond-h-h-c')); ?>
                        <?= $this->formControlGroup($form->get('plafond-hc-fi-hors-ead')); ?>
                        <?= $this->formControlGroup($form->get('plafond-h-c')); ?>
                    </div>
                </div>
            </div>

        </div>

    </div>
</div>


<?php
echo $this->form()->closeTag();
echo $this->messenger()->addCurrentMessagesFromFlashMessenger();
?>
<script type="text/javascript">
    $(function () {
        $("body").on("statut-clone", function (event, data) {
            window.location.reload();
        });
        $(".statut-libelle-<?= $form->get('id')->getValue() ?>").html("<?= $form->get('libelle')->getValue() ?>");
    });
</script>

