<?php

use Application\Provider\Privilege\Privileges;

/**
 * @var $this              \Application\View\Renderer\PhpRenderer
 * @var $typesIntervenants \Intervenant\Entity\Db\TypeIntervenant[]
 * @var $statuts           \Intervenant\Entity\Db\Statut[]
 * @var $statut            \Intervenant\Entity\Db\Statut
 * @var $form              \Intervenant\Form\StatutSaisieForm
 */

$canEdit = $this->isAllowed(Privileges::getResourceId(Privileges::INTERVENANT_STATUT_EDITION));

$this->headTitle()->append($title = "Modification d'un statut d'intervenant");

echo $this->tag('h1')->text($title);

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formElement($form->get('security'));
echo $this->messenger()->addCurrentMessagesFromFlashMessenger();

?>

<div class="row">
    <div class="col-md-3">
        <?php
        foreach ($typesIntervenants as $typeIntervenant) {
            echo $this->tag('h3')->text($typeIntervenant);
            echo $this->tag('div', ['class' => 'list-group']);
            foreach ($statuts as $s) {
                if ($s->getTypeIntervenant() == $typeIntervenant) {
                    $url    = $this->url('statut/saisie', ['statut' => $s->getId()]);
                    $active = $s == $statut ? ' active' : '';
                    echo $this->tag('a', ['class' => 'list-group-item' . $active, 'href' => $url])->text($s) . "\n";
                }
            }
            echo '</div>';
        }
        ?>
    </div>
    <div class="col-md-9">
        <!-- Informations générales -->
        <div class="panel panel-default">
            <div class="panel-heading">Informations générales</div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-4">
                        <?= $this->formControlGroup($form->get('typeIntervenant')); ?>
                    </div>
                    <div class="col-md-8">
                        <?= $this->formControlGroup($form->get('libelle')); ?>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <?= $this->formControlGroup($form->get('code')); ?>
                    </div>
                    <div class="col-md-4">
                        <?= $this->formControlGroup($form->get('tauxChargesPatronales')); ?>
                    </div>
                </div>
                <div class="row">
                    <?php for ($i = 1; $i <= 4; $i++): if ($form->has('codesCorresp' . $i)): ?>
                        <div class="col-md-6">
                            <?= $this->formControlGroup($form->get('codesCorresp' . $i)); ?>
                        </div>
                    <?php endif; endfor; ?>
                </div>
                <?= $this->formControlGroup($form->get('prioritaireIndicateurs')); ?>
            </div>
        </div>


        <!-- Données personnelles -->
        <div class="panel panel-default">
            <div class="panel-heading">Données personnelles</div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-12">
                        <?= $this->formControlGroup($form->get('dossier')); ?>
                    </div>
                </div>
                <div class="donneesDetails">
                    <div class="row">
                        <div class="col-md-12">
                            <?= $this->formControlGroup($form->get('dossierSelectionnable')); ?>
                        </div>
                    </div>
                    <fieldset>
                        <legend>Modules à activer :</legend>

                        <div class="row">
                            <div class="col-md-4">
                                <?= $this->formControlGroup($form->get('dossierIdentiteComplementaire')); ?>
                            </div>
                            <div class="col-md-4">
                                <?= $this->formControlGroup($form->get('dossierContact')); ?>
                            </div>
                            <div class="col-md-4">
                                <?= $this->formControlGroup($form->get('dossierAdresse')); ?>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-4">
                                <?= $this->formControlGroup($form->get('dossierBanque')); ?>
                            </div>
                            <div class="col-md-4">
                                <?= $this->formControlGroup($form->get('dossierInsee')); ?>
                            </div>
                            <div class="col-md-4">
                                <?= $this->formControlGroup($form->get('dossierEmployeur')); ?>
                            </div>
                        </div>
                    </fieldset>
                    <fieldset class="donneesContactDetails">
                        <legend>Règles spécifiques au module Contact :</legend>
                        <div class="row">
                            <div class="col-md-12">
                                <?= $this->formControlGroup($form->get('dossierTelPerso')); ?>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <?= $this->formControlGroup($form->get('dossierEmailPerso')); ?>
                            </div>
                        </div>
                    </fieldset>
                    <fieldset>
                        <legend>Autres informations demandées :</legend>
                        <div class="row">
                            <?php for ($i = 1; $i <= 5; $i++): if ($form->has('dossierAutre' . $i)): ?>
                                <div class="col-md-6">
                                    <?= $this->formControlGroup($form->get('dossierAutre' . $i)); ?>
                                </div>
                            <?php endif; endfor; ?>
                        </div>
                    </fieldset>
                </div>
            </div>
        </div>


        <!-- Pièces justificatives -->
        <div class="panel panel-default">
            <div class="panel-heading">Pièces justificatives</div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-12">
                        <?= $this->formControlGroup($form->get('pieceJustificative')); ?>
                        <a target="_blank" href="<?= $this->url('piece-jointe/type-piece-jointe-statut'); ?>">Page d'administration des pièces
                            justificatives</a>
                    </div>
                </div>
            </div>
        </div>


        <!-- Services -->
        <div class="panel panel-default">
            <div class="panel-heading">Services d'enseignement</div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-6">
                        <?= $this->formControlGroup($form->get('servicePrevu')); ?>
                    </div>
                    <div class="col-md-6">
                        <?= $this->formControlGroup($form->get('serviceRealise')); ?>
                    </div>
                </div>
                <div class="row servicesDetails">
                    <div class="col-md-12">
                        <?= $this->formControlGroup($form->get('serviceExterieur')); ?>
                    </div>
                </div>
            </div>
        </div>


        <!-- Référentiel -->
        <div class="panel panel-default">
            <div class="panel-heading">Référentiel</div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-6">
                        <?= $this->formControlGroup($form->get('referentielPrevu')); ?>
                    </div>
                    <div class="col-md-6">
                        <?= $this->formControlGroup($form->get('referentielRealise')); ?>
                    </div>
                </div>
            </div>
        </div>


        <!-- Agréments -->
        <div class="panel panel-default">
            <div class="panel-heading">Agréments</div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-6">
                        <?= $this->formControlGroup($form->get('conseilRestreint')); ?>
                    </div>
                    <div class="col-md-6 agrementCRDetails">
                        <?= $this->formControlGroup($form->get('conseilRestreintDureeVie')); ?>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <?= $this->formControlGroup($form->get('conseilAcademique')); ?>
                    </div>
                    <div class="col-md-6 agrementCADetails">
                        <?= $this->formControlGroup($form->get('conseilAcademiqueDureeVie')); ?>
                    </div>
                </div>
            </div>
        </div>


        <!-- Contrat -->
        <div class="panel panel-default">
            <div class="panel-heading">Contrat de travail et avenants</div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-12">
                        <?= $this->formControlGroup($form->get('contrat')); ?>
                        <a target="_blank" href="<?= $this->url('contrat/modeles'); ?>">Page d'administration des modèles de contrats de travail</a>
                    </div>
                </div>
            </div>
        </div>


        <!-- Calcul des heures complémentaires et mises en paiement -->
        <div class="panel panel-default">
            <div class="panel-heading">Calcul des heures complémentaires et mises en paiement</div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-6">
                        <?= $this->formControlGroup($form->get('serviceStatutaire')); ?>
                    </div>
                    <div class="col-md-6">
                        <?= $this->formControlGroup($form->get('modificationServiceDu')); ?>
                    </div>
                </div>
                <?= $this->formControlGroup($form->get('depassementServiceDuSansHC')); ?>
                <?= $this->formControlGroup($form->get('cloture')); ?>
                <?= $this->formControlGroup($form->get('motifNonPaiement')); ?>
                <?= $this->formControlGroup($form->get('formuleVisualisation')); ?>
                <?= $this->formControlGroup($form->get('paiementVisualisation')); ?>
            </div>
        </div>


        <!-- Plafonds -->
        <div class="panel panel-default">
            <div class="panel-heading">Plafonds</div>
            <div class="panel-body">
                TODO
            </div>
        </div>


        <!-- Boutons d'actions -->
        <a href="<?= $this->url('statut') ?>" class="btn btn-default">
            <i class="fa fa-undo"></i> Retour à la liste des statuts
        </a>
        <?php if ($canEdit): ?>
            <?= $this->formSubmit($form->get('submit')); ?>
            <?php if ($statut->getId()): ?>
                <a class="pop-ajax btn btn-danger" data-event="statut-clone"
                   href="<?= $this->url('statut/delete', ['statut' => $statut->getId()]) ?>"
                   title="Supprimer le statut d'intervenant"
                   data-content="<p class='lead text-danger'><strong>Attention!</strong> Confirmez-vous cette suppression ?</p>"
                   data-confirm="true" data-confirm-button="Oui"
                   data-cancel-button="Non"
                   data-submit-reload="true">
                    <span class="glyphicon glyphicon-trash"></span> Supprimer</a>
                <a class="ajax-modal btn btn-warning" data-event="statut-clone"
                   href="<?= $this->url('statut/clone', ['statut' => $statut->getId()]) ?>"
                   title="Dupliquer le statut d'intervenant">
                    <span class="glyphicon glyphicon-repeat"></span> Dupliquer</a>
            <?php endif; ?>
        <?php endif; ?>

        <?= $this->form()->closeTag(); ?>

    </div>

</div>

<script type="text/javascript">
    $(function () {
        WidgetInitializer.add('statut', {

            donneesVisu: function ()
            {
                var visible = this.el('dossier').val() != 'desactive';

                this.element.find('.donneesDetails').toggle(visible);
            },


            donneesContactVisu: function ()
            {
                var visible = this.el('dossierContact').is(':checked');

                this.element.find('.donneesContactDetails').toggle(visible);
            },


            servicesVisu: function ()
            {
                var visible = !(this.el('servicePrevu').val() == 'desactive' && this.el('serviceRealise').val() == 'desactive');

                this.element.find('.servicesDetails').toggle(visible);
            },

            agrementCRVisu: function ()
            {
                var visible = this.el('conseilRestreint').val() != 'desactive';

                this.element.find('.agrementCRDetails').toggle(visible);
            },

            agrementCAVisu: function ()
            {
                var visible = this.el('conseilAcademique').val() != 'desactive';

                this.element.find('.agrementCADetails').toggle(visible);
            },

            _create: function ()
            {
                var that = this;

                that.donneesVisu();
                that.donneesContactVisu();
                that.servicesVisu();
                that.agrementCRVisu();
                that.agrementCAVisu();

                that.el('dossier').change(function () {that.donneesVisu()});
                that.el('dossierContact').change(function () {that.donneesContactVisu()});
                that.el('servicePrevu').change(function () {that.servicesVisu()});
                that.el('serviceRealise').change(function () {that.servicesVisu()});
                that.el('conseilRestreint').change(function () {that.agrementCRVisu()});
                that.el('conseilAcademique').change(function () {that.agrementCAVisu()});
            },


            el: function (name)
            {
                return this.element.find('[name=' + name + ']');
            }
        })
        ;
    });
</script>