<?php

/**
 * @var $this          \Application\View\Renderer\PhpRenderer
 * @var $title         string
 * @var $form          \Application\Form\Budget\DotationSaisieForm
 * @var $typeRessource \Application\Entity\Db\TypeRessource
 * @var $structure     \Application\Entity\Db\Structure
 */

if ($form) {
    $fid = uniqid('form-saisie-dotation-');
    $form->setAttribute('id', $fid);
}
echo $this->tag('h1', ['class' => 'page-header'])->html($title);

echo $this->messenger()->addCurrentMessagesFromFlashMessenger();

?>
<?php if ($form): ?>
    <?= $this->form()->openTag($form->prepare()); ?>
    <div class="row">
        <div class="col-md-12">
            <?= $this->formControlGroup($form->get('libelle')); ?>
        </div>
    </div>

    <div class="alert alert-info">
        Veuillez saisir le nombre d'HETD relatives à l'année civile en les répartissant pour chacune des deux années
        universitaires.
        <br/>
        NB. N'oubliez pas de réserver une partie de votre budget pour le paiement des charges patronales.
    </div>

    <div class="row">
        <div class="col-md-offset-3 col-md-6">
            <?= $this->formControlGroup($form->get('anneeCivile')); ?>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <?= $this->formControlGroup($form->get('annee1')); ?>
        </div>
        <div class="col-md-6">
            <?= $this->formControlGroup($form->get('annee2')); ?>
        </div>
    </div>
    <?= $this->formRow($form->get('submit')); ?>
    <?= $this->form()->closeTag(); ?>
    <script>

        formSaisieDotationUpdateAnneeCivile();

        function formSaisieDotationUpdateAnneeCivile()
        {
            var form = $('#<?= $fid ?>'),
                annee1 = form.find('input[name="annee1"]'),
                annee2 = form.find('input[name="annee2"]'),
                anneeCivile = form.find('input[name="anneeCivile"]'),

                value;

            value = Formatter.stringToFloat(annee1.val()) + Formatter.stringToFloat(annee2.val());
            annee1.val(Formatter.floatToString(Formatter.stringToFloat(annee1.val())));
            annee2.val(Formatter.floatToString(Formatter.stringToFloat(annee2.val())));
            anneeCivile.val(Formatter.floatToString(value));
        }

    </script>
<?php endif;