<?php 
$wf = $this->workflow($this->intervenant, $this->role)->getWorkflow(); /* @var $wf \Application\Service\Workflow\AbstractWorkflow */

if (! count($wf->getSteps())) {
    return;
}
?>

<style>
    .step.no     { width: 50px; }
    .step.status { width: 50px; }
    td.step.status { text-align: center; }
</style>

<h2>Feuille de route</h2>

<div class="row">
    <div class="col-md-9">
        <ul class="list-group">
            <?php foreach ($wf->getSteps() as $step): /* @var $step \Application\Service\Workflow\Step */ ?>
            <?php if (!$step->getVisible()) continue; ?>
            <li class="list-group-item">
                        <!--<a class="details pull-right" href="#" title="Cliquez pour afficher plus d'informations"><small>En savoir plus...</small></a>-->
                        <?php 
                        $etape  = sprintf('<span class="label label-primary">%s</span> ', $step->getIndex());
                        $etape .= (!$step->getRoute() || $wf->isStepAfterCurrentStep($step) && !$step->getDone()) ?
                            $step->getLabel($this->role) : 
                            sprintf('<a title="%s" href="%s">%s</a>', 
                                "Cliquez sur ce lien pour accéder à la page correspondant à cette étape", 
                                $wf->getStepUrl($step),
                                $step->getLabel($this->role));
                        echo $etape;
                        ?>
                        <?php
                        if ($step->getDone()) {
                            echo '<span title="Fait" class="glyphicon glyphicon-ok text-success pull-right"></span>';
                        }
                        else {
                            echo '<span title="À faire" class="glyphicon glyphicon-remove text-danger pull-right"></span>';
                        }
                        ?>
                        <div class="details" style="display: none;">
                            <small><?php echo $step->getDescription($this->role) ?></small>
                        </div>
            </li>
            <?php endforeach ?>
        </ul> 
    </div>
</div>  

<script>
$(function() {
   $("a.details").click(function() { $(this).siblings("div.details").slideToggle(); });
});
</script>