<style>
    .step.no     { width: 50px; }
    .step.status { width: 50px; }
    td.step.status { text-align: center; }
</style>

<?php /* @var $wf \Application\Service\Workflow\AbstractWorkflow */ ?>


<div class="row">
    <div class="col-md-7">
        <ul class="list-group">
            <?php foreach ($this->wf->getSteps() as $step): /* @var $step \Application\Service\Workflow\Step */ ?>
            <li class="list-group-item">
                        <!--<a class="details pull-right" href="#" title="Cliquez pour afficher plus d'informations"><small>En savoir plus...</small></a>-->
                        <?php 
                        $etape  = sprintf('<span class="label label-primary">%s</span> ', $step->getIndex());
                        $etape .= (!$step->getRoute() || $wf->isStepAfterCurrentStep($step)) ?
                            $step->getLabel($role) : 
                            sprintf('<a title="%s" href="%s">%s</a>', 
                                "Cliquez sur ce lien pour accéder à la page correspondant à cette formation", 
                                $wf->getStepUrl($step),
                                $step->getLabel($role));
                        echo $etape;
                        ?>
                        <?php
                        if ($step->getDone()) {
                            echo '<span title="Fait" class="glyphicon glyphicon-ok text-success pull-right"></span>';
                        }
                        else {
                            echo '<span title="À faire" class="glyphicon glyphicon-remove text-danger pull-right"></span>';
                        }
                        ?>
                        <div class="details" style="display: none;">
                            <small><?php echo $step->getDescription($this->role) ?></small>
                        </div>
            </li>
            <?php endforeach ?>
        </ul> 
    </div>
</div>  
        
<!--<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <th class="step status"></th>
            <th>Formation</th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($this->wf->getSteps() as $step): /* @var $step \Application\Service\Workflow\Step */ ?>
        <tr>
            <td class="step status">
                <?php
                if ($step->getDone()) {
                    echo '<span title="Fait" class="glyphicon glyphicon-ok text-success"></span>';
                }
                else {
                    echo '<span title="À faire" class="glyphicon glyphicon-remove text-danger"></span>';
                }
                ?>
            </td>
            <td>
                <a class="details pull-right" href="#" title="Cliquez pour afficher plus d'informations"><small>En savoir plus...</small></a>
                <p>
                    <?php 
                    $etape  = sprintf('<span class="label label-primary">%s</span> ', $step->getIndex());
                    $etape .= !$step->getRoute() || $wf->isStepAfterCurrentStep($step) ?
                        $step->getLabel($role) : 
                        sprintf('<a title="%s" href="%s">%s</a>', 
                            "Cliquez sur ce lien pour accéder à la page correspondant à cette formation", 
                            $wf->getStepUrl($step),
                            $step->getLabel($role));
                    echo $etape;
                    ?>
                </p> 
                <div class="details" style="display: none;">
                    <small><?php echo $step->getDescription($this->role) ?></small>
                </div>
            </td>
        </tr>
    <?php endforeach ?>
    </tbody>
</table>-->

<script>
$(function() {
   $("a.details").click(function() { $(this).siblings("div.details").slideToggle(); });
});
</script>