<?php

/**
 * @var $this              \Application\View\Renderer\PhpRenderer
 * @var $intervenant       \Application\Entity\Db\Intervenant
 * @var $typeVolumeHoraire \Application\Entity\Db\TypeVolumeHoraire
 * @var $referentiel       boolean
 */

?>
<div id="s<?php echo $referentiel ? 'r' : '' ?>-horodatage" data-url="<?php echo $this->url('service/horodatage', [
        'intervenant'       => $intervenant->getRouteParam(),
        'typeVolumeHoraire' => $typeVolumeHoraire->getId(),
        'referentiel'       => $referentiel,
    ]); ?>">
        <?php echo $this->partial('application/service/horodatage', [
            'intervenant'       => $intervenant,
            'typeVolumeHoraire' => $typeVolumeHoraire,
            'referentiel'       => $referentiel,
        ]); ?>
</div>