<?php
/**
 * @var $this  \Application\View\Renderer\PhpRenderer
 * @var $form  \Application\Form\MotifModificationService\MotifModificationServiceSaisieForm
 */
echo $this->messenger()->addCurrentMessagesFromFlashMessenger();

echo $this->form()->openTag($form); ?>

<div class="row">
    <div class="col-md-4">
        <?= $this->formControlGroup($form->get('code')); ?>
    </div>
    <div class="col-md-8">
        <?= $this->formControlGroup($form->get('libelle')); ?>
    </div>
</div>

<div class="row">
    <div class="col-md-4">
        <?= $this->formControlGroup($form->get('multiplicateur')); ?>
    </div>
    <div class="col-md-8">
        <br>
        <?= $this->formControlGroup($form->get('decharge')); ?>
    </div>
</div>

<?= $this->formControlGroup($form->get('security')); ?>
<?= $this->formSubmit($form->get('submit')); ?>
<?= $this->form()->closeTag(); ?>
