<?php

use Framework\Application\Application;

$this->headTitle()->append($title = $this->translate("Opération impossible")) ?>

<h1 class="text-danger has-error"><?= $title ?></h1>
<h2><?= $this->message ?></h2>

<?php if (isset($this->exception) && ($previous = $this->exception->getPrevious())): ?>
    <h3><?= $previous->getMessage() ?></h3>
<?php endif ?>

<?php if (Application::getInstance()->config()['global']['affichageErreurs'] ?? true): ?>

<?php if (isset($this->exception) && ($this->exception instanceof \Exception || $this->exception instanceof \Error)): ?>

<?php if (!$this->exception instanceof \UnicaenApp\Exception\MessageException): ?>
<hr/>
<h3><?= $this->translate('Additional information') ?>:</h3>
<h4><?= get_class($this->exception); ?></h4>
<dl>
    <dt><?= $this->translate('File') ?>:</dt>
    <dd>
        <pre class="prettyprint linenums"><?= $this->exception->getFile() ?>:<?= $this->exception->getLine() ?></pre>
    </dd>
    <dt><?= $this->translate('Message') ?>:</dt>
    <dd>
        <pre class="prettyprint linenums"><?= $this->exception->getMessage() ?></pre>
    </dd>
    <dt><?= $this->translate('Stack trace') ?>:</dt>
    <dd>
        <pre class="prettyprint linenums"><?= \UnicaenApp\Util::formatTraceString($this->exception->getTraceAsString()) ?></pre>
    </dd>
</dl>
<?php
    $e = $this->exception->getPrevious();
    if ($e) :
?>
<hr/>
<h3><?= $this->translate('Previous exceptions') ?>:</h3>
<ul class="unstyled">
    <?php while($e) : ?>
    <li>
        <h4><?= get_class($e); ?></h4>
        <dl>
            <dt><?= $this->translate('File') ?>:</dt>
            <dd>
                <pre class="prettyprint linenums"><?= $e->getFile() ?>:<?= $e->getLine() ?></pre>
            </dd>
            <dt><?= $this->translate('Message') ?>:</dt>
            <dd>
                <pre class="prettyprint linenums"><?= $e->getMessage() ?></pre>
            </dd>
            <dt><?= $this->translate('Stack trace') ?>:</dt>
            <dd>
                <pre class="prettyprint linenums"><?= \UnicaenApp\Util::formatTraceString($e->getTraceAsString()) ?></pre>
            </dd>
        </dl>
    </li>
    <?php
        $e = $e->getPrevious();
        endwhile;
    ?>
</ul>
<?php endif; ?>

<?php endif ?>

<?php else: ?>

<h4><?= $this->translate('No Exception available') ?></h4>

<?php endif ?>

<?php endif ?>