<?php

use Framework\Application\Application;

$this->headTitle()->append($title = 'Une erreur est survenue');
$details = (Application::getInstance()->config()['global']['affichageErreurs'] ?? true) && isset($this->exception) && ($this->exception instanceof Error || $this->exception instanceof Exception);

?>
<div class="alert alert-danger exception" role="alert">
    <h1><?= $this->translate($title) ?> :</h1>
    <?= $this->exception->getMessage() ?>
    <?php if ($details): ?>
        <hr/>
        <h2><?= $this->translate('Additional information') ?>:</h2>
        <h3><?= get_class($this->exception); ?></h3>
        <dl>
            <dt><?= $this->translate('File') ?>:</dt>
            <dd>
                <pre class="prettyprint linenums"><?= $this->exception->getFile() ?>
                    :<?= $this->exception->getLine() ?></pre>
            </dd>
            <dt><?= $this->translate('Stack trace') ?>:</dt>
            <dd>
                <pre
                        class="prettyprint linenums"><?= \UnicaenApp\Util::formatTraceString($this->exception->getTraceAsString()) ?></pre>
            </dd>
        </dl>
        <?php
        $e = $this->exception->getPrevious();
        if ($e) :
            ?>
            <hr/>
            <h2><?= $this->translate('Previous exceptions') ?>:</h2>
            <ul class="unstyled">
                <?php while ($e) : $id = uniqid('bloc_code_'); ?>
                    <a role="button" data-bs-toggle="collapse" href="#<?= $id ?>" aria-expanded="false"
                       aria-controls="collapseExample">
                        <?= get_class($e) ?>
                    </a><br/>
                    <div class="collapse" id="<?= $id ?>">

                        <dl>
                            <dt><?= $this->translate('File') ?>:</dt>
                            <dd>
                                <pre class="prettyprint linenums"><?= $e->getFile() ?>
                                    :<?= $e->getLine() ?></pre>
                            </dd>
                            <dt><?= $this->translate('Message') ?>:</dt>
                            <dd>
                                <pre class="prettyprint linenums"><?= $e->getMessage() ?></pre>
                            </dd>
                            <dt><?= $this->translate('Stack trace') ?>:</dt>
                            <dd>
                                <pre
                                        class="prettyprint linenums"><?= \UnicaenApp\Util::formatTraceString($e->getTraceAsString()) ?></pre>
                            </dd>
                        </dl>
                    </div>
                    <?php
                    $e = $e->getPrevious();
                endwhile;
                ?>
            </ul>
        <?php endif; ?>
    <?php endif ?>
</div>
