<?php

use Application\Assertion\IntervenantDossierAssertion;

$viewInsee = $this->isAllowed($intervenant, IntervenantDossierAssertion::PRIV_VIEW_INSEE);


$form->prepare();
$dossierInsee = $form->get('DossierInsee');
?>

<style>
    div.rib-part {
        display: inline-block;
        vertical-align: top;
    }

    div.rib-part input {
        width: auto;
    }
</style>


<div class="col-md-6">
    <h3>Insee</h3>
    <?php
    echo $this->formControlGroup($dossierInsee->get('numeroInsee'));
    echo $this->formControlGroup($dossierInsee->get('numeroInseeEstProvisoire'));
    ?>
</div>






