<?php

/**
 * @var $this               \Application\View\Renderer\PhpRenderer
 * @var $form               \Application\Form\Intervenant\IntervenantDossierForm
 * @var $intervenant        \Application\Entity\Db\Intervenant
 * @var $intervenantDossier \Application\Entity\Db\IntervenantDossier
 * @var $tblDossier         \Application\Entity\Db\TblDossier
 */

use Application\Assertion\IntervenantDossierAssertion;

$viewContact = $this->isAllowed($intervenant, IntervenantDossierAssertion::PRIV_VIEW_CONTACT);

/**
 * @var \Application\Entity\Db\IntervenantDossier $intervenantDossier
 */

//$Dossier = $dossier;

$form->prepare();
$dossierContact = $form->get('DossierContact');
?>

<!-- Fiedlset Contact -->
<div class="col-md-6">
    <div class="card bg-default ">
        <div class="card-header">
            CONTACT
            <?php if (!empty($tblDossier)): ?>
                <?php if (!$intervenantDossier->getTblDossier()->getCompletudeContact()): ?>
                    <span class="badge bg-warning text-dark">A compléter</span>
                <?php else: ?>
                    <span class="badge bg-success">Complet</span>
                <?php endif; ?>
            <?php endif; ?>
        </div>
        <div class="card-body">
            <div class="form-group">
                <?= $this->formLabel($dossierContact->get('emailEtablissement')); ?>
                <div class="input-group cold-md-6 readonly">
                    <?php
                    if (!empty($intervenantDossier->getEmailPro())) {
                        echo ($viewContact) ? $intervenantDossier->getEmailPro() : '**********@*****.com';
                    }
                    ?>
                </div>
            </div>
            <div class="form-group">
                <?= $this->formLabel($dossierContact->get('emailPersonnel')); ?>
                <div class="input-group cold-md-6 readonly">
                    <?php
                    if (!empty($intervenantDossier->getEmailPerso())) {
                        echo ($viewContact) ? $intervenantDossier->getEmailPerso() : '**********@*****.com';
                    }
                    ?>
                </div>
            </div>
            <div class="form-group">
                <?= $this->formLabel($dossierContact->get('telephoneProfessionnel')); ?>
                <div class="input-group cold-md-6 readonly">
                    <?php
                    if (!empty($intervenantDossier->getTelPro())) {
                        echo ($viewContact) ? $intervenantDossier->getTelPro() : '** ** ** ** **';
                    }
                    ?>
                </div>
            </div>
            <div class="form-group">
                <?= $this->formLabel($dossierContact->get('telephonePersonnel')); ?>
                <div class="input-group cold-md-6 readonly">
                    <?php
                    if (!empty($intervenantDossier->getTelPerso())) {
                        echo ($viewContact) ? $intervenantDossier->getTelPerso() : '** ** ** ** **';
                    }
                    ?>
                </div>
            </div>
        </div>
    </div>
</div>





