<?php

use Application\Assertion\IntervenantDossierAssertion;

$viewIdentite = $this->isAllowed($intervenant, IntervenantDossierAssertion::PRIV_VIEW_IDENTITE);

/**
 * @var \Application\Entity\Db\IntervenantDossier $intervenantDossier
 */

//$Dossier = $dossier;

$form->prepare();
$dossierIdentite = $form->get('DossierIdentite');


?>

<style>
    div.rib-part {
        display: inline-block;
        vertical-align: top;
    }

    div.rib-part input {
        width: auto;
    }
</style>

<!-- Fiedlset Identite -->

<div class="col-md-12">
    <div class="panel panel-default">
        <div class="panel-heading">
            IDENTITÉ
            <?php if (!$intervenantDossierCompletude['dossierIdentite']): ?>
                <small><span class="label label-warning">A compléter</span></small>
            <?php else: ?>
                <small><span class="label label-success">Complet</span></small>
            <?php endif; ?>
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <?= $this->formLabel($dossierIdentite->get('civilite')); ?>
                        <div class="input-group cold-md-6" style="display:block;background-color:#eee;padding:5px;">
                            <?php
                            if (!empty($intervenantDossier->getCivilite())) {
                                echo $intervenantDossier->getCivilite()->getLibelleCourt();
                            } else {
                                echo 'NON RENSEIGNE';
                            }
                            ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <?= $this->formLabel($dossierIdentite->get('nomUsuel')); ?>
                        <div class="input-group cold-md-6" style="display:block;background-color:#eee;padding:5px;">
                            <?php
                            if (!empty($intervenantDossier->getNomUsuel())) {
                                echo $intervenantDossier->getNomUsuel();
                            } else {
                                echo 'NON RENSEIGNE';
                            }
                            ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <?= $this->formLabel($dossierIdentite->get('nomPatronymique')); ?>
                        <div class="input-group cold-md-6" style="display:block;background-color:#eee;padding:5px;">
                            <?php
                            if (!empty($intervenantDossier->getNomPatronymique())) {
                                echo $intervenantDossier->getNomPatronymique();
                            } else {
                                echo 'NON RENSEIGNE';
                            }
                            ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <?= $this->formLabel($dossierIdentite->get('prenom')); ?>
                        <div class="input-group cold-md-6" style="display:block;background-color:#eee;padding:5px;">
                            <?php
                            if (!empty($intervenantDossier->getPrenom())) {
                                echo $intervenantDossier->getPrenom();
                            } else {
                                echo 'NON RENSEIGNE';
                            }
                            ?>
                        </div>
                    </div>
                </div>


                <div class="col-md-6">
                    <div class="form-group">
                        <?= $this->formLabel($dossierIdentite->get('dateNaissance')); ?>
                        <div class="input-group cold-md-6" style="display:block;background-color:#eee;padding:5px;">
                            <?php
                            if (!empty($dossierIdentite->get('dateNaissance')->getValue())) {
                                echo ($viewIdentite) ? $dossierIdentite->get('dateNaissance')->getValue() : '**/**/****';
                            } else {
                                echo 'NON RENSEIGNE';
                            }
                            ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <?= $this->formLabel($dossierIdentite->get('paysNaissance')); ?>
                        <div class="input-group cold-md-6" style="display:block;background-color:#eee;padding:5px;">
                            <?php
                            if (!empty($intervenantDossier->getPaysNaissance())) {
                                echo ($viewIdentite) ? $intervenantDossier->getPaysNaissance()->getLibelle() : '*******************';
                            } else {
                                echo 'NON RENSEIGNE';
                            }


                            ?>
                        </div>
                    </div>
                    <?php if ($intervenantDossier->getPaysNaissance()->getLibelle() == 'FRANCE'): ?>
                        <div class="form-group">
                            <?= $this->formLabel($dossierIdentite->get('departementNaissance')); ?>
                            <div class="input-group cold-md-6" style="display:block;background-color:#eee;padding:5px;">
                                <?php
                                if (!empty($intervenantDossier->getDepartementNaissance())) {
                                    echo ($viewIdentite) ? $intervenantDossier->getDepartementNaissance()->getLibelle() : '*******************';
                                } else {
                                    echo 'NON RENSEIGNE';
                                }


                                ?>
                            </div>
                        </div>
                    <?php endif; ?>
                    <div class="form-group">
                        <?= $this->formLabel($dossierIdentite->get('villeNaissance')); ?>
                        <div class="input-group cold-md-6" style="display:block;background-color:#eee;padding:5px;">
                            <?php
                            if (!empty($intervenantDossier->getCommuneNaissance())) {
                                echo ($viewIdentite) ? $intervenantDossier->getCommuneNaissance() : '*******************';
                            } else {
                                echo 'NON RENSEIGNE';
                            }


                            ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>








