<?php

/**
 * @var $this             \Application\View\Renderer\PhpRenderer
 * @var $form             \Application\Form\Intervenant\Dossier
 * @var $canValider       boolean
 * @var $canDevalider     boolean
 * @var $canSupprimer     boolean
 * @var $dossier          Dossier
 */

//$Dossier = $dossier;

$form->prepare();
$dossierInsee = $form->get('DossierEmployeur');
?>

<style>
    div.rib-part {
        display: inline-block;
        vertical-align: top;
    }

    div.rib-part input {
        width: auto;
    }
</style>


<!-- Fiedlset Employeur -->
<div class="col-md-6">
    <h3>
        Employeur
        <?php if (!$intervenantDossierCompletude['dossierEmployeur']): ?>
            <small><span class="label label-warning">A compléter</span></small>
        <?php else: ?>
            <small><span class="label label-success">Complet</span></small>
        <?php endif; ?>
    </h3>
    <?= $this->formControlGroup($dossierInsee->get('employeur')); ?>


</div>





