<?php

use Application\Assertion\IntervenantDossierAssertion;

$viewInsee = $this->isAllowed($intervenant, IntervenantDossierAssertion::PRIV_VIEW_INSEE);

/**
 * @var \Application\Entity\Db\IntervenantDossier $intervenantDossier
 */

$form->prepare();
$dossierInsee = $form->get('DossierInsee');
?>

<style>
    div.rib-part {
        display: inline-block;
        vertical-align: top;
    }

    div.rib-part input {
        width: auto;
    }
</style>


<div class="col-md-6">
    <h3>Insee</h3>
    <div class="form-group">
        <?= $this->formLabel($dossierInsee->get('numeroInsee')); ?>
        <div class="input-group cold-md-6" style="display:block;background-color:#eee;padding:5px;">
            <?php
            if (!empty($intervenantDossier->getNumeroInsee())) {
                echo ($viewInsee) ? $intervenantDossier->getNumeroInsee() : '*************************';
            } else {
                echo 'NON RENSEIGNE';
            }
            ?>
        </div>
    </div>
    <div class="form-group">
        <?= $this->formLabel($dossierInsee->get('numeroInseeEstProvisoire')); ?>
        <div class="input-group cold-md-6" style="display:block;background-color:#eee;padding:5px;">
            <?php
            if ($viewInsee) {
                echo ($intervenantDossier->getNumeroInseeProvisoire()) ? 'OUI' : 'NON';
            } else {
                echo '***';
            }
            ?>
        </div>
    </div>
</div>






