<?php


$form->prepare();
$dossierAdresse = $form->get('DossierAdresse');
?>


<div class="col-md-6">
    <h3>Adresse</h3>
    <?= $this->formControlGroup($dossierAdresse->get('precisions')); ?>
    <?= $this->formControlGroup($dossierAdresse->get('lieuDit')); ?>
    <div class="row">
        <div class="col-md-2">
            <?= $this->formControlGroup($dossierAdresse->get('numero')); ?>
        </div>
        <div class="col-md-2">
            <?= $this->formControlGroup($dossierAdresse->get('numeroComplement')); ?>
        </div>
        <div class="col-md-4">
            <?= $this->formControlGroup($dossierAdresse->get('voirie')); ?>
        </div>
        <div class="col-md-4">
            <?= $this->formControlGroup($dossierAdresse->get('voie')); ?>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <?= $this->formControlGroup($dossierAdresse->get('codePostal')); ?>
        </div>
        <div class="col-md-8">
            <?= $this->formControlGroup($dossierAdresse->get('ville')); ?>
        </div>
    </div>
    <?= $this->formControlGroup($dossierAdresse->get('pays')); ?>


</div>





