<?php


$form->prepare();
$dossierStatut = $form->get('DossierStatut');
?>

<style>
    div.rib-part {
        display: inline-block;
        vertical-align: top;
    }

    div.rib-part input {
        width: auto;
    }
</style>

<!-- Fiedlset Insee -->
<div class="col-md-12">
    <div class="panel panel-default ">
        <div class="panel-heading">
            STATUT
        </div>
        <div class="panel-body">
            <?php
            echo $this->formControlGroup($dossierStatut->get('statut'));

            ?>
        </div>
    </div>
</div>






