<?php

/**
 * @var $this               \Application\View\Renderer\PhpRenderer
 * @var $form               \Application\Form\Intervenant\IntervenantDossierForm
 * @var $intervenant        \Application\Entity\Db\Intervenant
 * @var $intervenantDossier \Application\Entity\Db\IntervenantDossier
 * @var $tblDossier         \Application\Entity\Db\TblDossier
 */

use Application\Assertion\IntervenantDossierAssertion;

$viewIdentite = $this->isAllowed($intervenant, IntervenantDossierAssertion::PRIV_VIEW_IDENTITE);

/**
 * @var \Application\Entity\Db\IntervenantDossier $intervenantDossier
 */

//$Dossier = $dossier;

$form->prepare();
$dossierIdentite = $form->get('DossierIdentite');


?>

<!-- Fiedlset Identite -->

<div class="col-md-6">
    <div class="card bg-default">
        <div class="card-header">
            IDENTITÉ
            <?php if (!empty($tblDossier)): ?>
                <?php if (!$intervenantDossier->getTblDossier()->getCompletudeIdentite()): ?>
                    <span class="label label-warning">A compléter</span>
                <?php else: ?>
                    <span class="label label-success">Complet</span>
                <?php endif; ?>
            <?php endif; ?>
        </div>
        <div class="card-body">

            <div class="form-group">
                <?= $this->formLabel($dossierIdentite->get('civilite')); ?>
                <div class="input-group cold-md-6 readonly">
                    <?php
                    if (!empty($intervenantDossier->getCivilite())) {
                        echo $intervenantDossier->getCivilite()->getLibelleCourt();
                    }
                    ?>
                </div>
            </div>
            <div class="form-group">
                <?= $this->formLabel($dossierIdentite->get('nomUsuel')); ?>
                <div class="input-group cold-md-6 readonly">
                    <?php
                    if (!empty($intervenantDossier->getNomUsuel())) {
                        echo $intervenantDossier->getNomUsuel();
                    }
                    ?>
                </div>
            </div>
            <div class="form-group">
                <?= $this->formLabel($dossierIdentite->get('nomPatronymique')); ?>
                <div class="input-group cold-md-6 readonly">
                    <?php
                    if (!empty($intervenantDossier->getNomPatronymique())) {
                        echo $intervenantDossier->getNomPatronymique();
                    }
                    ?>
                </div>
            </div>
            <div class="form-group">
                <?= $this->formLabel($dossierIdentite->get('prenom')); ?>
                <div class="input-group cold-md-6 readonly">
                    <?php
                    if (!empty($intervenantDossier->getPrenom())) {
                        echo $intervenantDossier->getPrenom();
                    }
                    ?>
                </div>
            </div>

        </div>
    </div>
</div>








