<?php


$form->prepare();
$dossierInsee = $form->get('DossierInsee');
?>

<style>
    div.rib-part {
        display: inline-block;
        vertical-align: top;
    }

    div.rib-part input {
        width: auto;
    }
</style>

<!-- Fiedlset Insee -->
<div class="col-md-6">
    <div class="panel panel-default ">
        <div class="panel-heading">
            INSEE
            <?php if (!$intervenantDossierCompletude['dossierInsee']): ?>
                <small><span class="label label-warning">A compléter</span></small>
            <?php else: ?>
                <small><span class="label label-success">Complet</span></small>
            <?php endif; ?>
        </div>
        <div class="panel-body">
            <?php
            echo $this->formControlGroup($dossierInsee->get('numeroInsee'));
            echo $this->formControlGroup($dossierInsee->get('numeroInseeEstProvisoire'));
            ?>
        </div>
    </div>
</div>






