<?php
/**
 * @var $this               \Application\View\Renderer\PhpRenderer
 * @var $form               \Application\Form\Intervenant\IntervenantDossierForm
 * @var $intervenant        \Application\Entity\Db\Intervenant
 * @var $intervenantDossier \Application\Entity\Db\IntervenantDossier
 * @var $tblDossier         \Application\Entity\Db\TblDossier
 */

use Application\Assertion\IntervenantDossierAssertion;

$viewEmployeur = $this->isAllowed($intervenant, IntervenantDossierAssertion::PRIV_VIEW_EMPLOYEUR);
$form->prepare();
$dossierEmployeur = $form->get('DossierEmployeur');

?>

<!-- Fiedlset Employeur -->
<div class="col-md-6">
    <div class="panel panel-default ">
        <div class="panel-heading">
            EMPLOYEUR
            <?php if (!$intervenantDossier->getTblDossier()->getCompletudeEmployeur()): ?>
                <span class="label label-warning">A compléter</span>
            <?php else: ?>
                <span class="label label-success">Complet</span>
            <?php endif; ?>
        </div>
        <div class="panel-body">
            <div class="form-group">
                <?= $this->formLabel($dossierEmployeur->get('employeur')); ?>
                <div class="input-group cold-md-6 readonly">
                    <?php
                    if (!empty($intervenantDossier->getEmployeur())) {
                        $employeur = $intervenantDossier->getEmployeur()->getRaisonSociale();
                        $siren     = $intervenantDossier->getEmployeur()->getSiren();
                        echo ($viewEmployeur) ? $employeur . '(SIRET : ' . $siren . ')' : '***************';
                    }
                    ?>
                </div>
            </div>
        </div>
    </div>
</div>




