<?php

/**
 * @var $this             \Application\View\Renderer\PhpRenderer
 * @var $form             \Application\Form\Intervenant\Dossier
 * @var $canValider       boolean
 * @var $canDevalider     boolean
 * @var $canSupprimer     boolean
 * @var $dossier          Dossier
 */

//$Dossier = $dossier;

$form->prepare();
$dossierInsee = $form->get('DossierAutres');
?>

<style>
    div.rib-part {
        display: inline-block;
        vertical-align: top;
    }

    div.rib-part input {
        width: auto;
    }
</style>


    <div class="col-md-6">
        <h3>Autres</h3>
        <?= $this->formControlGroup($dossierInsee->get('autre1')); ?>
        <?= $this->formControlGroup($dossierInsee->get('autre2')); ?>
        <?= $this->formControlGroup($dossierInsee->get('autre3')); ?>
        <?= $this->formControlGroup($dossierInsee->get('autre4')); ?>
        <?= $this->formControlGroup($dossierInsee->get('autre5')); ?>


    </div>





