<?php

$form->prepare();
$dossierBancaire = $form->get('DossierBancaire');
?>

<style>
    div.rib-part {
        display: inline-block;
        vertical-align: top;
    }

    div.rib-part input {
        width: auto;
    }
</style>

<!-- Fiedlset Bancaire -->
<div class="col-md-6">
    <h3>
        Coordonnées bancaires
        <?php if (!$intervenantDossierCompletude['dossierIban']): ?>
            <small><span class="label label-warning">A compléter</span></small>
        <?php else: ?>
            <small><span class="label label-success">Complet</span></small>
        <?php endif; ?>
    </h3>
    <?php
    /* if($viewIban)
     {*/
    echo $this->formControlGroup($dossierBancaire->get('ribBic'));
    echo $this->formControlGroup($dossierBancaire->get('ribIban'));
    echo $this->formControlGroup($dossierBancaire->get('ribHorsSepa'));
    /* }else{
         echo 'Coordonnées bancaires non visibles';
     }*/

    ?>

</div>





