<?php

/**
 * @var $this               \Application\View\Renderer\PhpRenderer
 * @var $form               \Application\Form\Intervenant\IntervenantDossierForm
 * @var $intervenant        \Application\Entity\Db\Intervenant
 * @var $intervenantDossier \Application\Entity\Db\IntervenantDossier
 * @var $tblDossier         \Application\Entity\Db\TblDossier
 */

use Application\Assertion\IntervenantDossierAssertion;

$viewIdentite = $this->isAllowed($intervenant, IntervenantDossierAssertion::PRIV_VIEW_IDENTITE);

$form->prepare();
$dossierIdentite = $form->get('DossierIdentite');


?>
<!-- Fiedlset Identite -->
<div class="col-md-6">
    <div class="panel panel-default">
        <div class="panel-heading">
            IDENTITÉ
            <?php if (!$tblDossier->getCompletudeIdentite()): ?>
                <span class="label label-warning">A compléter</span>
            <?php else: ?>
                <span class="label label-success">Complet</span>
            <?php endif; ?>
        </div>
        <div class="panel-body">

            <?= $this->formControlGroup($dossierIdentite->get('civilite')); ?>
            <?= $this->formControlGroup($dossierIdentite->get('nomUsuel')); ?>
            <?= $this->formControlGroup($dossierIdentite->get('nomPatronymique')); ?>
            <?= $this->formControlGroup($dossierIdentite->get('prenom')); ?>

        </div>
    </div>
</div>







