<?php

use Application\Assertion\IntervenantDossierAssertion;

$viewIdentite = $this->isAllowed($intervenant, IntervenantDossierAssertion::PRIV_VIEW_IDENTITE);

$form->prepare();
$dossierIdentite = $form->get('DossierIdentite');


?>

<div class="col-md-6">

    <?= $this->formControlGroup($dossierIdentite->get('civilite')); ?>
    <?= $this->formControlGroup($dossierIdentite->get('nomUsuel')); ?>
    <?= $this->formControlGroup($dossierIdentite->get('nomPatronymique')); ?>
    <?= $this->formControlGroup($dossierIdentite->get('prenom')); ?>
</div>
<div class="col-md-6">
    <?php

        echo $this->formControlGroup($dossierIdentite->get('dateNaissance'));
        echo $this->formControlGroup($dossierIdentite->get('paysNaissance'));
        echo $this->formControlGroup($dossierIdentite->get('departementNaissance'));
        echo $this->formControlGroup($dossierIdentite->get('villeNaissance'));
    ?>

</div>





