<?php

/**
 * @var \Application\Entity\Db\IntervenantDossier $intervenantDossier
 */

use Application\Assertion\IntervenantDossierAssertion;

$viewIban = $this->isAllowed($intervenant, IntervenantDossierAssertion::PRIV_VIEW_IBAN);

$form->prepare();
$dossierBancaire = $form->get('DossierBancaire');
?>

<style>
    div.rib-part {
        display: inline-block;
        vertical-align: top;
    }

    div.rib-part input {
        width: auto;
    }
</style>

<!-- Fiedlset Bancaire -->
<div class="col-md-6">
    <h3>
        Coordonnées bancaires
        <?php if (!$intervenantDossierCompletude['dossierIban']): ?>
            <small><span class="label label-warning">A compléter</span></small>
        <?php else: ?>
            <small><span class="label label-success">Complet</span></small>
        <?php endif; ?>
    </h3>
    <div class="form-group">
        <?= $this->formLabel($dossierBancaire->get('ribBic')); ?>
        <div class="input-group cold-md-6" style="display:block;background-color:#eee;padding:5px;">
            <?php
            if (!empty($intervenantDossier->getBIC())) {
                echo ($viewIban) ? $intervenantDossier->getBIC() : '*************';
            } else {
                echo 'NON RENSEIGNE';
            }
            ?>
        </div>
    </div>
    <div class="form-group">
        <?= $this->formLabel($dossierBancaire->get('ribIban')); ?>
        <div class="input-group cold-md-6" style="display:block;background-color:#eee;padding:5px;">
            <?php
            if (!empty($intervenantDossier->getIBAN())) {
                echo ($viewIban) ? $intervenantDossier->getIBAN() : '**************************';
            } else {
                echo 'NON RENSEIGNE';
            }
            ?>
        </div>
    </div>
    <div class="form-group">
        <?= $this->formLabel($dossierBancaire->get('ribHorsSepa')); ?>
        <div class="input-group cold-md-6" style="display:block;background-color:#eee;padding:5px;">
            <?php
            if ($viewIban) {
                echo ($intervenantDossier->isRibHorsSepa()) ? 'OUI' : 'NON';
            } else {
                echo '***';
            }
            ?>
        </div>
    </div>
    <?php

    ?>

</div>





