<?php
/**
 * @var \Application\Entity\Db\IntervenantDossier $intervenantDossier
 */

use Application\Assertion\IntervenantDossierAssertion;

$viewAdresse = $this->isAllowed($intervenant, IntervenantDossierAssertion::PRIV_VIEW_ADRESSE);

$form->prepare();
$dossierAdresse = $form->get('DossierAdresse'); /* @var $dossier \Application\Form\Intervenant\DossierFieldset */
?>

<style>
    div.rib-part {
        display: inline-block;
        vertical-align: top;
    }

    div.rib-part input {
        width: auto;
    }
</style>

<!-- Fiedlset Adresse -->
<div class="col-md-6">
    <div class="panel panel-default">
        <div class="panel-heading">
            ADRESSE
            <?php if (!$intervenantDossierCompletude['dossierAdresse']): ?>
                <span class="label label-warning">A compléter</span>
            <?php else: ?>
                <span class="label label-success">Complet</span>
            <?php endif; ?>
        </div>
        <div class="panel-body">

            <div class="form-group">
                <?= $this->formLabel($dossierAdresse->get('precisions')); ?>
                <div class="input-group cold-md-6" style="display:block;background-color:#eee;padding:5px;">
                    <?php
                    if (!empty($intervenantDossier->getAdressePrecisions())) {
                        echo ($viewAdresse) ? $intervenantDossier->getAdressePrecisions() : '*******************';
                    } else {
                        echo '- NON RENSEIGNÉ -';
                    }
                    ?>
                </div>
            </div>
            <div class="form-group">
                <?= $this->formLabel($dossierAdresse->get('lieuDit')); ?>
                <div class="input-group cold-md-6" style="display:block;background-color:#eee;padding:5px;">
                    <?php
                    if (!empty($intervenantDossier->getAdresseLieuDit())) {
                        echo ($viewAdresse) ? $intervenantDossier->getAdresseLieuDit() : '*******************';
                    } else {
                        echo '- NON RENSEIGNÉ -';
                    }
                    ?>
                </div>
            </div>

            <div class="row">

                <div class="col-md-2">
                    <?= $this->formLabel($dossierAdresse->get('numero')); ?>

                    <div style="display:block;background-color:#eee;padding:5px;">
                        <?php
                        if (!empty($intervenantDossier->getAdresseNumero())) {
                            echo ($viewAdresse) ? $intervenantDossier->getAdresseNumero() : '***';
                        } else {
                            echo 'NR';
                        }
                        ?>
                    </div>
                </div>

                <div class="col-md-2">
                    <?= $this->formLabel($dossierAdresse->get('numeroComplement')); ?>

                    <div style="display:block;background-color:#eee;padding:5px;">
                        <?php
                        if (!empty($intervenantDossier->getAdresseNumeroCompl())) {
                            echo ($viewAdresse) ? $intervenantDossier->getAdresseNumeroCompl()->getLibelle() : '***';
                        } else {
                            echo 'NR';
                        }
                        ?>
                    </div>
                </div>
                <div class="col-md-4">
                    <?= $this->formLabel($dossierAdresse->get('voirie')); ?>

                    <div style="display:block;background-color:#eee;padding:5px;">
                        <?php
                        if (!empty($intervenantDossier->getAdresseVoirie())) {
                            echo ($viewAdresse) ? $intervenantDossier->getAdresseVoirie()->getLibelle() : '***';
                        } else {
                            echo 'NR';
                        }
                        ?>
                    </div>
                </div>
                <div class="col-md-4">
                    <?= $this->formLabel($dossierAdresse->get('voie')); ?>

                    <div style="display:block;background-color:#eee;padding:5px;">
                        <?php
                        if (!empty($intervenantDossier->getAdresseVoie())) {
                            echo ($viewAdresse) ? $intervenantDossier->getAdresseVoie() : '***';
                        } else {
                            echo 'NR';
                        }
                        ?>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <?= $this->formLabel($dossierAdresse->get('codePostal')); ?>

                    <div style="display:block;background-color:#eee;padding:5px;">
                        <?php
                        if (!empty($intervenantDossier->getAdresseCodePostal())) {
                            echo ($viewAdresse) ? $intervenantDossier->getAdresseCodePostal() : '***';
                        } else {
                            echo 'NR';
                        }
                        ?>
                    </div>
                </div>
                <div class="col-md-8">
                    <?= $this->formLabel($dossierAdresse->get('ville')); ?>
                    <div style="display:block;background-color:#eee;padding:5px;">
                        <?php
                        if (!empty($intervenantDossier->getAdresseCommune())) {
                            echo ($viewAdresse) ? $intervenantDossier->getAdresseCommune() : '***';
                        } else {
                            echo '- NON RENSEIGNÉ -';
                        }
                        ?>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <?= $this->formLabel($dossierAdresse->get('pays')); ?>
                <div class="input-group cold-md-6" style="display:block;background-color:#eee;padding:5px;">
                    <?php
                    if (!empty($intervenantDossier->getAdressePays())) {
                        echo ($viewAdresse) ? $intervenantDossier->getAdressePays()->getLibelle() : '*******************';
                    } else {
                        echo '- NON RENSEIGNÉ -';
                    }
                    ?>
                </div>
            </div>

        </div>
    </div>
</div>





