<?php

/**
 * @var $this             \Application\View\Renderer\PhpRenderer
 * @var $form             \Application\Form\Intervenant\Dossier
 * @var $canValider       boolean
 * @var $canDevalider     boolean
 * @var $canSupprimer     boolean
 * @var $dossier          Dossier
 */

//$Dossier = $dossier;

$form->prepare();
$dossierContact = $form->get('DossierContact');
?>

<style>
    div.rib-part {
        display: inline-block;
        vertical-align: top;
    }

    div.rib-part input {
        width: auto;
    }
</style>


    <div class="col-md-6">
        <h3>Contact</h3>
        <?= $this->formLabel($dossierContact->get('emailEtablissement')); ?>
        <div class="input-group">
            <span class="input-group-addon" id="basic-addon1">@</span>
            <?= $this->formElement($dossierContact->get('emailEtablissement')); ?>
        </div>
        <br/>
        <div class="form-group">
                <div class="input-group">
                    <span class="input-group-addon transparent"><span class="glyphicon glyphicon-user"></span></span>
                    <input class="form-control left-border-none" placeholder="User Name" type="text" name="username">
                </div>
        </div>

        <div class="form-group has-feedback has-feedback-left">
            <?= $this->formLabel($dossierContact->get('emailPersonnel')); ?>
            <?= $this->formElement($dossierContact->get('emailPersonnel')); ?>
            <i class="glyphicon glyphicon-user form-control-feedback"></i>
        </div>
        <?= $this->formControlGroup($dossierContact->get('telephoneProfessionnel')); ?>
        <?= $this->formControlGroup($dossierContact->get('telephonePersonnel')); ?>
    </div>





