<?php

/**
 * @var \Application\Entity\Db\IntervenantDossier $intervenantDossier
 */

use Application\Assertion\IntervenantDossierAssertion;

$viewIdentite = $this->isAllowed($intervenant, IntervenantDossierAssertion::PRIV_VIEW_IDENTITE);

/**
 * @var \Application\Entity\Db\IntervenantDossier $intervenantDossier
 */

//$Dossier = $dossier;

$form->prepare();
$dossierIdentiteComplementaire = $form->get('DossierIdentiteComplementaire');


?>

<!-- Fiedlset Identite -->

<div class="col-md-6">
    <div class="panel panel-default">
        <div class="panel-heading">
            IDENTITÉ COMPLEMENTAIRE
            <?php if (!$intervenantDossier->getTblDossier()->getCompletudeIdentiteComp()): ?>
                <span class="label label-warning">A compléter</span>
            <?php else: ?>
                <span class="label label-success">Complet</span>
            <?php endif; ?>
        </div>
        <div class="panel-body">

            <div class="form-group">
                <?= $this->formLabel($dossierIdentiteComplementaire->get('dateNaissance')); ?>
                <div class="input-group cold-md-6 readonly">
                    <?php
                    if (!empty($dossierIdentiteComplementaire->get('dateNaissance')->getValue())) {
                        echo ($viewIdentite) ? $dossierIdentiteComplementaire->get('dateNaissance')->getValue() : '**/**/****';
                    }
                    ?>
                </div>
            </div>
            <div class="form-group">
                <?= $this->formLabel($dossierIdentiteComplementaire->get('paysNaissance')); ?>
                <div class="input-group cold-md-6 readonly">
                    <?php
                    if (!empty($intervenantDossier->getPaysNaissance())) {
                        echo ($viewIdentite) ? $intervenantDossier->getPaysNaissance()->getLibelle() : '*******************';
                    }


                    ?>
                </div>
            </div>
            <?php if ($intervenantDossier->getPaysNaissance() && $intervenantDossier->getPaysNaissance()->getLibelle() == 'FRANCE'): ?>
                <div class="form-group">
                    <?= $this->formLabel($dossierIdentiteComplementaire->get('departementNaissance')); ?>
                    <div class="input-group cold-md-6 readonly">
                        <?php
                        if (!empty($intervenantDossier->getDepartementNaissance())) {
                            echo ($viewIdentite) ? $intervenantDossier->getDepartementNaissance()->getLibelle() : '*******************';
                        }
                        ?>
                    </div>
                </div>
            <?php endif; ?>
            <div class="form-group">
                <?= $this->formLabel($dossierIdentiteComplementaire->get('villeNaissance')); ?>
                <div class="input-group cold-md-6 readonly">
                    <?php
                    if (!empty($intervenantDossier->getCommuneNaissance())) {
                        echo ($viewIdentite) ? $intervenantDossier->getCommuneNaissance() : '*******************';
                    }


                    ?>
                </div>
            </div>

        </div>
    </div>
</div>








