<?php

/**
 * @var $this               \Application\View\Renderer\PhpRenderer
 * @var $form               \Application\Form\Intervenant\IntervenantDossierForm
 * @var $intervenant        \Application\Entity\Db\Intervenant
 * @var $intervenantDossier \Application\Entity\Db\IntervenantDossier
 * @var $tblDossier         \Application\Entity\Db\TblDossier
 */

//$Dossier = $dossier;

$form->prepare();
$dossierContact = $form->get('DossierContact');
?>

<style>
    div.rib-part {
        display: inline-block;
        vertical-align: top;
    }

    div.rib-part input {
        width: auto;
    }
</style>

<!-- Fiedlset Contact -->
<div class="col-md-6 ">
    <div class="panel panel-default ">
        <div class="panel-heading">
            CONTACT
            <?php if (!empty($tblDossier)): ?>
                <?php if (!$tblDossier->getCompletudeContact()): ?>
                    <span class="label label-warning">A compléter</span>
                <?php else: ?>
                    <span class="label label-success">Complet</span>
                <?php endif; ?>
            <?php endif; ?>
        </div>
        <div class="panel-body">
            <?php
            echo $this->formControlGroup($dossierContact->get('emailEtablissement'));
            echo $this->formControlGroup($dossierContact->get('emailPersonnel'));
            echo $this->formControlGroup($dossierContact->get('telephoneProfessionnel'));
            echo $this->formControlGroup($dossierContact->get('telephonePersonnel'));
            ?>
        </div>
    </div>
</div>





