<?php

/**
 * @var $this               \Application\View\Renderer\PhpRenderer
 * @var $form               \Application\Form\Intervenant\IntervenantDossierForm
 * @var $intervenant        \Application\Entity\Db\Intervenant
 * @var $intervenantDossier \Application\Entity\Db\IntervenantDossier
 * @var $tblDossier         \Application\Entity\Db\TblDossier
 */

use Application\Assertion\IntervenantDossierAssertion;

$viewIdentiteComplementaire = $this->isAllowed($intervenant, IntervenantDossierAssertion::PRIV_VIEW_IDENTITE);

$form->prepare();
$dossierIdentiteComplementaire = $form->get('DossierIdentiteComplementaire');


?>
<!-- Fiedlset Identite Complementaire -->
<div class="col-md-6">
    <div class="card bg-default">
        <div class="card-header">
            IDENTITÉ COMPLEMENTAIRE
            <?php if (!empty($tblDossier)): ?>
                <?php if (!$tblDossier->getCompletudeIdentiteComp()): ?>
                    <span class="badge bg-warning text-dark">A compléter</span>
                <?php else: ?>
                    <span class="badge bg-success">Complet</span>
                <?php endif; ?>
            <?php endif; ?>
        </div>
        <div class="card-body">

            <?php
            echo $this->formControlGroup($dossierIdentiteComplementaire->get('dateNaissance'));
            echo $this->formControlGroup($dossierIdentiteComplementaire->get('paysNaissance'));
            echo $this->formControlGroup($dossierIdentiteComplementaire->get('paysNationalite'));
            echo $this->formControlGroup($dossierIdentiteComplementaire->get('departementNaissance'));
            echo $this->formControlGroup($dossierIdentiteComplementaire->get('villeNaissance'));
            ?>

        </div>
    </div>
</div>







