<?php

/**
 * @var $this             \Application\View\Renderer\PhpRenderer
 * @var $form             \Application\Form\Intervenant\Dossier
 * @var $canValider       boolean
 * @var $canDevalider     boolean
 * @var $canSupprimer     boolean
 * @var $dossier          Dossier
 */

//$Dossier = $dossier;

$form->prepare();
$dossierBancaire = $form->get('DossierBancaire');
?>

<style>
    div.rib-part {
        display: inline-block;
        vertical-align: top;
    }

    div.rib-part input {
        width: auto;
    }
</style>


    <div class="col-md-6">
        <h3>Coordonnées bancaires</h3>
        <?= $this->formControlGroup($dossierBancaire->get('ribBic')); ?>
        <?= $this->formControlGroup($dossierBancaire->get('ribIban')); ?>
        <?= $this->formControlGroup($dossierBancaire->get('ribHorsSepa')); ?>
    </div>





