<?php

/**
 * @var $this             \Application\View\Renderer\PhpRenderer
 * @var $form             \Application\Form\Intervenant\Dossier
 * @var $canValider       boolean
 * @var $canDevalider     boolean
 * @var $canSupprimer     boolean
 * @var $dossier          Dossier
 */

//$Dossier = $dossier;

$form->prepare();
$dossierContact = $form->get('DossierContact');
?>

<style>
    div.rib-part {
        display: inline-block;
        vertical-align: top;
    }

    div.rib-part input {
        width: auto;
    }
</style>


    <div class="col-md-6">
        <h3>Contact</h3>
        <?= $this->formControlGroup($dossierContact->get('emailEtablissement')); ?>
        <?= $this->formControlGroup($dossierContact->get('emailPersonnel')); ?>
        <?= $this->formControlGroup($dossierContact->get('telephoneProfessionnel')); ?>
        <?= $this->formControlGroup($dossierContact->get('telephonePersonnel')); ?>
    </div>
</div>




