<?php

/**
 * @var $this             \Application\View\Renderer\PhpRenderer
 * @var $form             \Application\Form\Intervenant\Dossier
 * @var $canValider       boolean
 * @var $canDevalider     boolean
 * @var $canSupprimer     boolean
 * @var $dossier          Dossier
 */

//$Dossier = $dossier;

$form->prepare();
$dossierInsee = $form->get('DossierAutres');
?>

<style>
    div.rib-part {
        display: inline-block;
        vertical-align: top;
    }

    div.rib-part input {
        width: auto;
    }
</style>

<!-- Fiedlset Autres -->
<div class="col-md-6">
    <h3>Autres</h3>
    <?php foreach ($champsAutres as $champ): ?>
        <?= $this->formControlGroup($dossierInsee->get('champ-autre-' . $champ->getId())); ?>
    <?php endforeach; ?>

</div>





