<?php

use Application\Assertion\IntervenantDossierAssertion;

$viewInsee = $this->isAllowed($intervenant, IntervenantDossierAssertion::PRIV_VIEW_INSEE);

/**
 * @var \Application\Entity\Db\IntervenantDossier $intervenantDossier
 */

$form->prepare();
$dossierInsee = $form->get('DossierInsee');
?>

<!-- Fiedlset Insee -->
<div class="col-md-6">
    <div class="panel panel-default ">
        <div class="panel-heading">
            INSEE
            <?php if (!$intervenantDossierCompletude['dossierInsee']): ?>
                <span class="label label-warning">A compléter</span>
            <?php else: ?>
                <span class="label label-success">Complet</span>
            <?php endif; ?>
        </div>
        <div class="panel-body">
            <div class="form-group">
                <?= $this->formLabel($dossierInsee->get('numeroInsee')); ?>
                <div class="input-group cold-md-6 readonly">
                    <?php
                    if (!empty($intervenantDossier->getNumeroInsee())) {
                        echo ($viewInsee) ? $intervenantDossier->getNumeroInsee() : '*************************';
                    }
                    ?>
                </div>
            </div>
            <div class="form-group">
                <?= $this->formLabel($dossierInsee->get('numeroInseeEstProvisoire')); ?>
                <div class="input-group cold-md-6 readonly">
                    <?php
                    if ($viewInsee) {
                        echo ($intervenantDossier->getNumeroInseeProvisoire()) ? 'OUI' : 'NON';
                    }
                    ?>
                </div>
            </div>
        </div>
    </div>
</div>






