<?php

/**
 * @var $this               \Application\View\Renderer\PhpRenderer
 * @var $form               \Application\Form\Intervenant\IntervenantDossierForm
 * @var $intervenant        \Application\Entity\Db\Intervenant
 * @var $intervenantDossier \Application\Entity\Db\IntervenantDossier
 * @var $tblDossier         \Application\Entity\Db\TblDossier
 */

$form->prepare();
$dossierStatut = $form->get('DossierStatut');
?>

<style>
    div.rib-part {
        display: inline-block;
        vertical-align: top;
    }

    div.rib-part input {
        width: auto;
    }
</style>

<!-- Fiedlset Insee -->
<div class="col-md-12">
    <div class="panel panel-default">
        <div class="panel-heading">
            STATUT
        </div>
        <div class="panel-body">
            <div class="form-group">
                <?= $this->formLabel($dossierStatut->get('statut')); ?>
                <div class="input-group cold-md-6 readonly">
                    <?php
                    if (!empty($intervenantDossier->getStatut())) {
                        echo $intervenantDossier->getStatut()->getLibelle();
                    }
                    ?>
                </div>
            </div>
        </div>
    </div>
</div>






