<?php

/**
 * @var $this               \Application\View\Renderer\PhpRenderer
 * @var $form               \Application\Form\Intervenant\IntervenantDossierForm
 * @var $intervenant        \Application\Entity\Db\Intervenant
 * @var $intervenantDossier \Application\Entity\Db\IntervenantDossier
 * @var $tblDossier         \Application\Entity\Db\TblDossier
 */
$form->prepare();
$dossierStatut = $form->get('DossierStatut');
?>

<style>
    div.rib-part {
        display: inline-block;
        vertical-align: top;
    }

    div.rib-part input {
        width: auto;
    }
</style>

<!-- Fiedlset Insee -->
<div class="col-md-12">
    <div class="panel panel-default ">
        <div class="panel-heading">
            STATUT
            <?php if (!$tblDossier->getCompletudeStatut()): ?>
                <span class="label label-warning">A compléter</span>
            <?php else: ?>
                <span class="label label-success">Complet</span>
            <?php endif; ?>
        </div>
        <div class="panel-body">
            <?php
            echo $this->formControlGroup($dossierStatut->get('statut'));

            ?>
        </div>
    </div>
</div>






