<?php

use Application\Assertion\IntervenantDossierAssertion;

$viewInsee = $this->isAllowed($intervenant, IntervenantDossierAssertion::PRIV_VIEW_INSEE);

/**
 * @var \Application\Entity\Db\IntervenantDossier $intervenantDossier
 */

$form->prepare();
$dossierInsee = $form->get('DossierInsee');
?>

<style>
    div.rib-part {
        display: inline-block;
        vertical-align: top;
    }

    div.rib-part input {
        width: auto;
    }
</style>

<!-- Fiedlset Insee -->
<div class="col-md-6">
    <div class="panel panel-default ">
        <div class="panel-heading">
            INSEE
            <?php if (!$intervenantDossierCompletude['dossierInsee']): ?>
                <small><span class="label label-warning">A compléter</span></small>
            <?php else: ?>
                <small><span class="label label-success">Complet</span></small>
            <?php endif; ?>
        </div>
        <div class="panel-body">
            <div class="form-group">
                <?= $this->formLabel($dossierInsee->get('numeroInsee')); ?>
                <div class="input-group cold-md-6" style="display:block;background-color:#eee;padding:5px;">
                    <?php
                    if (!empty($intervenantDossier->getNumeroInsee())) {
                        echo ($viewInsee) ? $intervenantDossier->getNumeroInsee() : '*************************';
                    } else {
                        echo 'NON RENSEIGNE';
                    }
                    ?>
                </div>
            </div>
            <div class="form-group">
                <?= $this->formLabel($dossierInsee->get('numeroInseeEstProvisoire')); ?>
                <div class="input-group cold-md-6" style="display:block;background-color:#eee;padding:5px;">
                    <?php
                    if ($viewInsee) {
                        echo ($intervenantDossier->getNumeroInseeProvisoire()) ? 'OUI' : 'NON';
                    } else {
                        echo '***';
                    }
                    ?>
                </div>
            </div>
        </div>
    </div>
</div>






