<?php
/**
 * @var $this              \Application\View\Renderer\PhpRenderer
 * @var $intervenant       \Intervenant\Entity\Db\Intervenant
 * @var $canAddMission     bool
 * @var $typeVolumeHoraire \Service\Entity\Db\TypeVolumeHoraire
 */

use Workflow\Entity\Db\WfEtape;

$title     = 'Suivi de missions';
$nextEtape = WfEtape::CODE_MISSION_VALIDATION_REALISE;

$this->intervenant($intervenant)->renderTitle($title);

echo $this->plafonds($intervenant, $typeVolumeHoraire);

echo $this->vue('mission/suivi', [
    'intervenant'   => $intervenant->getId(),
    'canAddMission' => $canAddMission,
]);

echo '<br />';
echo $this->feuilleDeRoute($intervenant)->renderNav($nextEtape);