<?php

/**
 * @var $this              \Application\View\Renderer\PhpRenderer
 * @var $title             string
 * @var $form              \Mission\Form\MissionSuiviForm
 */

// S'il n'y a qu'une seule mission et qu'on en a pas déjà une de sélectionnée, alors on la sélectionne !
if (1 === count($form->get('mission')->getValueOptions())){
    if (!$form->get('mission')->getValue()){
        $firstKey = key($form->get('mission')->getValueOptions());
        $form->get('mission')->setValue($firstKey);
    }
}

echo $this->messenger()->addCurrentMessagesFromFlashMessengerWithNamespace('error');
echo $this->form()->openTag($form);

echo $this->tag('h1', ['class' => 'page-header'])->html($title);

echo $this->formControlGroup($form->get('mission'));

echo '<div class="row">';

echo '<div class="col-md-4">';
echo $this->formControlGroup($form->get('date'));
echo '</div>';
echo '<div class="col-md-4">';
echo $this->formControlGroup($form->get('heureDebut'));
echo '</div>';
echo '<div class="col-md-4">';
echo $this->formControlGroup($form->get('heureFin'));
echo '</div>';

echo '</div>';


echo '<div class="row">';

echo '<div class="col-md-4 heures-formation"><label>&nbsp;</label>';
echo $this->formControlGroup($form->get('formation'));
echo '</div>';

echo '</div>';


echo $this->formControlGroup($form->get('description'));

echo $this->formSubmit($form->get('submit'));

echo $this->form()->closeTag();
?>
<script>

    function missionSelect()
    {
        return $('[name=mission]');
    }

    function toggleViewElements()
    {
        var mId = missionSelect().val();

        var mBF = missionSelect().data('besoin-formation');

        if (mBF[mId]){
            $('.heures-formation').show();
        }else{
            $('.heures-formation').hide();
        }

    }

    $(function(){
        missionSelect().on('change', toggleViewElements);
        toggleViewElements();
    });

</script>
