<?php

/**
 * @var $this        \Application\View\Renderer\PhpRenderer
 * @var $intervenant \Intervenant\Entity\Db\Intervenant
 * @var $paiements   \Paiement\Entity\Db\MiseEnPaiement[]
 */

?>
<form method="post" id="mepform">
    <table class="table table-bordered table-xs table-hover table-sort">
        <thead>
        <tr>
            <th>&nbsp;</th>
            <th>Composante</th>
            <th>Enseignement</th>
            <th>Centre de coûts</th>
            <th>Domaine fonctionel</th>
            <th>Période</th>
            <th>Type</th>
            <th>HETD</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($paiements as $paiement):
            if ($paiement->getService()) {
                $service = $paiement->getService();
                $serviceReferentiel = null;
                $mission = null;
                if ($service->getElementPedagogique()) {
                    $composante = $service->getElementPedagogique()->getStructure();
                } else {
                    $composante = $intervenant->getStructure();
                }
            } elseif ($paiement->getServiceReferentiel()) {
                $service = null;
                $serviceReferentiel = $paiement->getServiceReferentiel();
                $mission = null;
                $composante = $serviceReferentiel->getStructure();
            } elseif ($paiement->getMission()) {
                $service = null;
                $serviceReferentiel = null;
                $mission = $paiement->getMission();
                $composante = $mission->getStructure();
            }
            ?>
            <tr>
                <td style="text-align:center;vertical-align:middle"><?= $this->formCheckbox(new \Laminas\Form\Element\Checkbox('mep[' . $paiement->getId() . ']')) ?></td>
                <td><?= $this->structure($composante)->renderLink() ?></td>
                <td><?php
                    if ($service) {
                        if ($service->getElementPedagogique()) {
                            echo $this->elementPedagogique($service->getElementPedagogique())->renderLink();
                        } else {
                            if ($service->getDescription()) {
                                echo $this->etablissement($service->getEtablissement())->renderLink() . ' - ' . $service->getDescription();
                            } else {
                                echo $this->etablissement($service->getEtablissement())->renderLink();
                            }
                        }
                    } elseif ($serviceReferentiel) {
                        echo $this->fonctionReferentiel($serviceReferentiel->getFonctionReferentiel())->renderLink();
                    } elseif ($mission) {
                        echo $mission->getLibelle().' ('.$mission->getTypeMission()->getLibelle().')';
                    }
                    ?></td>
                <td><?= $paiement->getCentreCout() ?></td>
                <td><?= $paiement->getDomaineFonctionnel() ?></td>
                <td data-order="<?= $paiement->getPeriodePaiement() ? $paiement->getPeriodePaiement()->getOrdre() : 999999999 ?>"><?= $paiement->getPeriodePaiement() ? $paiement->getPeriodePaiement()->getLibelleAnnuel($intervenant->getAnnee()) : '<i>Simple demande</i>' ?></td>
                <td><?= $paiement->getTypeHeures() ?></td>
                <td><?= \UnicaenApp\Util::formattedNumber($paiement->getHeures()) ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
    <div>
        <button class="btn btn-secondary btn-sm" type="button"
                onclick="$('.table-sort :checkbox').prop('checked', true);">Tout
            sélectionner
        </button>
        <button class="btn btn-secondary btn-sm" type="button"
                onclick="$('.table-sort :checkbox').prop('checked', false);">Ne
            rien sélectionner
        </button>
    </div>
    <div style="margin-top: .5em;margin-bottom: .5em">
        <button class="btn btn-danger pop-ajax" type="button"
                data-content="Voulez-vous réellement annuler ces mises en paiement ?
            <div class='alert alert-warning'>
            <button type='button' class='btn-close' data-bs-dismiss='alert' aria-label='Close'></button>
                Attention : Retirer les mises en paiement ne signifie pas qu'elles sont supprimées. Elles ne sont remises qu'à l'état de simples demandes de mises en paiement.
                Pour les supprimer définitivement, il convient de retirer également les <a class='no-intranavigation' href='<?= $this->url('intervenant/mise-en-paiement/demande', ['intervenant' => $intervenant->getId()]) ?>'>demandes de mises en paiement</a>.
            </div>
            <div style='text-align:right'>
            <button type='button' class='btn btn-secondary pop-ajax-hide'>Non</button>
            <button type='button' class='btn btn-primary' onclick='enregistrer()'>Oui</button></div>"
        ><i class="fas fa-trash-can"></i> Annuler les mises en paiement
        </button>
    </div>
    <?= $this->form()->closeTag() ?>
    <script type="text/javascript">

        function enregistrer()
        {
            $("#mepform").submit();
        }

    </script>

