<?php

/* @var $etatPaiement array */
/* @var $hasFoot boolean */

$majFc = $etatPaiement['total']['rem-fc-d714'] > 0;
$hasCp = isset($etatPaiement['total']['conges-payes']) && $etatPaiement['total']['conges-payes'];

?>
<table class="table table-sm table-bordered etat-paiement">
<thead>
    <tr>
        <th rowspan="2">Identité</th>
        <th rowspan="2">Centre de coûts / EOTP</th>
        <th rowspan="2">Domaine fonctionnel</th>
        <th colspan="2" rowspan="2">HETD</th>
        <th colspan="2">Taux</th>
        <?php if ($hasCp): ?><th rowspan="2" title="Taux de congés payés à prendre en compte, impactant la conversion des heures en euros">Congés payés *</th><?php endif; ?>
        <th rowspan="2">Montant</th>
        <?php if ($majFc): ?><th rowspan="2">Rém. FC D714.60</th><?php endif; ?>
        <th colspan="2">Exercice</th>
    </tr>
    <tr>
        <th>Libellé</th>
        <th>Valeur</th>
        <th>AA</th>
        <th>AC</th>
    </tr>
</thead>
<tbody>
    <?php foreach( $etatPaiement as $intervenantId => $llEP ) if ($intervenantId != 'total'): ?>
    <?php foreach( $llEP as $hetdRem => $lep ): ?>
    <?php foreach( $lep as $iEP => $ep ): ?>

    <?php if ($iEP !== 'total'): ?>
    <tr>
        <td><?= $ep['intervenant-nom'] ?></td>
        <td><?= $ep['centre-cout-code'] ?></td>
        <td><?= $ep['domaine-fonctionnel-libelle'] ?></td>
        <td class="nombre"><?= $hetdRem == 'hetd' ? \UnicaenApp\Util::formattedNumber($ep['hetd']) : '' ?></td>
        <td class="nombre"><?= $hetdRem == 'hetd' ? \UnicaenApp\Util::formattedPourcentage($ep['hetd-pourc']) : '' ?></td>
        <td><?= $ep['taux-remu'] ?></td>
        <td class="nombre"><?= $hetdRem == 'hetd' ? \UnicaenApp\Util::formattedNumber($ep['taux-horaire']) : '' ?>
        <?php if ($hasCp): ?><td class="nombre"><?= $hetdRem == 'hetd' ? \UnicaenApp\Util::formattedPourcentage($ep['taux-conges-payes']) : '' ?></td><?php endif; ?>
        <td class="nombre"><?= $hetdRem == 'hetd' ? \UnicaenApp\Util::formattedEuros($ep['hetd-montant']) : '' ?></td>
        <?php if ($majFc): ?><td class="nombre"><?= $hetdRem == 'hetd' ? '' : \UnicaenApp\Util::formattedEuros($ep['rem-fc-d714']) ?></td><?php endif; ?>
        <td class="nombre"><?= $hetdRem == 'hetd' ? \UnicaenApp\Util::formattedNumber($ep['exercice-aa']) : '' ?></td>
        <td class="nombre"><?= $hetdRem == 'hetd' ? \UnicaenApp\Util::formattedNumber($ep['exercice-ac']) : '' ?></td>
    </tr>
    <?php endif; ?>
    <?php endforeach; ?>
    <?php if (count($lep) > 1 ): ?>
    <tr>
        <th colspan="3" style="text-align: right">Sous-total <?= $hetdRem == 'hetd' ? 'HC' : 'rém. FC D714.60' ?></th>
        <th class="nombre"><?= $hetdRem == 'hetd' ? \UnicaenApp\Util::formattedNumber($lep['total']['hetd']) : '' ?></th>
        <th class="nombre"><?= $hetdRem == 'hetd' ? \UnicaenApp\Util::formattedPourcentage($lep['total']['hetd-pourc']) : '' ?></th>
        <th>&nbsp;</th>
        <th>&nbsp;</th>
        <?php if ($hetdRem != 'hetd'): ?><th>&nbsp;</th><?php endif; ?>
        <th class="nombre"><?= $hetdRem == 'hetd' ? \UnicaenApp\Util::formattedEuros($lep['total']['hetd-montant']) : '' ?></th>
        <?php if ($hetdRem == 'hetd'): ?><th>&nbsp;</th><?php endif; ?>
        <?php if ($hasCp): ?><th class="nombre"><?= $hetdRem == 'hetd' ? '' : \UnicaenApp\Util::formattedEuros($lep['total']['rem-fc-d714']) ?></th><?php endif; ?>
        <th class="nombre"><?= $hetdRem == 'hetd' ? \UnicaenApp\Util::formattedNumber($lep['total']['exercice-aa']) : \UnicaenApp\Util::formattedEuros($lep['total']['exercice-aa-montant']) ?></th>
        <th class="nombre"><?= $hetdRem == 'hetd' ? \UnicaenApp\Util::formattedNumber($lep['total']['exercice-ac']) : \UnicaenApp\Util::formattedEuros($lep['total']['exercice-ac-montant']) ?></th>
    </tr>
    <?php endif; ?>
    <?php endforeach; ?>
    <?php endif; ?>
</tbody>
<?php if ($hasFoot): ?>
<tfoot class="tfoot bg-info">
    <tr>
        <td colspan="3"><?= (count($etatPaiement)-1) ?> intervenant(s)</td>
        <td class="nombre"><?= \UnicaenApp\Util::formattedNumber($etatPaiement['total']['hetd']) ?></td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <?php if ($majFc): ?><th>&nbsp;</th><?php endif; ?>
        <td class="nombre"><?= \UnicaenApp\Util::formattedEuros($etatPaiement['total']['hetd-montant']) ?></td>
        <?php if ($hasCp): ?><td class="nombre"><?= \UnicaenApp\Util::formattedEuros($etatPaiement['total']['rem-fc-d714']) ?></td><?php endif; ?>
        <td class="nombre"><?= \UnicaenApp\Util::formattedEuros($etatPaiement['total']['exercice-aa-montant']) ?></td>
        <td class="nombre"><?= \UnicaenApp\Util::formattedEuros($etatPaiement['total']['exercice-ac-montant']) ?></td>
    </tr>
</tfoot>
<?php endif; ?>
</table>