<?php

use Application\Provider\Privileges;
use Paiement\Entity\Db\MiseEnPaiement;
use Paiement\Entity\MiseEnPaiementRecherche;
use Paiement\Form\Paiement\MiseEnPaiementRechercheForm;

/* @var $recherche MiseEnPaiementRecherche */
/* @var $rechercheForm MiseEnPaiementRechercheForm */
/* @var $etatPaiement array */

$title = 'Paiement';
switch ($recherche->getEtat()) {
    case MiseEnPaiement::A_METTRE_EN_PAIEMENT:
        $title = 'Mise en paiement';
        $rechercheForm->get('afficher')->setValue('Afficher les demandes à mettre en paiement');
        $rechercheForm->get('exporter-pdf')->setValue('Télécharger au format PDF');
        break;
    case MiseEnPaiement::MIS_EN_PAIEMENT:
        $title = 'État de paiement';
        $rechercheForm->get('afficher')->setValue('Afficher l\'état de paiement');
        $rechercheForm->get('exporter-pdf')->setValue('Télécharger au format PDF');
        break;
}
$rechercheForm->get('exporter-csv-etat')->setValue('Extraction pour tableur (CSV)');
$this->headTitle()->append($title);

?>
    <h1><?= $title ?></h1>
    <div class="card bg-default filter" data-etat="<?= $recherche->getEtat() ?>">

        <div class="card-header">Filtres</div>
        <div class="card-body">
            <?php
            echo $this->form()->openTag($rechercheForm->prepare());

            if ($rechercheForm->hasTypesIntervenants()) {
                echo $this->formControlGroup($rechercheForm->get('typeIntervenant'));
            } else {
                echo '<div class="alert alert-info">Aucune donnée trouvée</div>';
            }

            if ($rechercheForm->hasStructures()) {
                echo $this->formControlGroup($rechercheForm->get('structure'));
            }

            if ($rechercheForm->hasPeriodes()) {
                echo $this->formControlGroup($rechercheForm->get('periode'));
            }

            if ($rechercheForm->hasIntervenants()) {
                echo $this->formControlGroup($rechercheForm->get('intervenants'), $this->formAdvancedMultiCheckbox()->setHeight('20em'));
            }

            if ($rechercheForm->hasTypesIntervenants()) {
                echo $this->formRow($rechercheForm->get('suite')) . ' ';
            }
            echo $this->formRow($rechercheForm->get('afficher')) . ' ';
            if ($this->isAllowed(Privileges::getResourceId(Privileges::MISE_EN_PAIEMENT_EXPORT_CSV))) {
                echo $this->formRow($rechercheForm->get('exporter-csv-etat')) . ' ';
            }
            //Bouton export PDF mise en paiement
            if ($recherche->getEtat() === MiseEnPaiement::A_METTRE_EN_PAIEMENT && $this->isAllowed(Privileges::getResourceId(Privileges::MISE_EN_PAIEMENT_EXPORT_PDF))) {
                echo $this->formRow($rechercheForm->get('exporter-pdf')) . ' ';
            }
            //Bouton export PDF etat de paiement
            if ($recherche->getEtat() === MiseEnPaiement::MIS_EN_PAIEMENT && $this->isAllowed(Privileges::getResourceId(Privileges::MISE_EN_PAIEMENT_EXPORT_PDF_ETAT))) {
                echo $this->formRow($rechercheForm->get('exporter-pdf')) . ' ';
            }

            echo $this->form()->closeTag();
            echo $this->formErrors($rechercheForm);
            ?>
        </div>
    </div>
<?php

if (!empty($etatPaiement)) {
    echo $this->partial('paiement/paiement/etat-paiement-tableau', ['etatPaiement' => $etatPaiement, 'hasFoot' => true]);
    if ($recherche->getEtat() === MiseEnPaiement::A_METTRE_EN_PAIEMENT && $this->isAllowed(Privileges::getResourceId(Privileges::MISE_EN_PAIEMENT_MISE_EN_PAIEMENT))) {
        $url = $this->url('paiement/mise-en-paiement', [
            'structure'    => $rechercheForm->get('structure')->getValue(),
            'intervenants' => implode(',', $rechercheForm->get('intervenants')->getValue()),
        ]);

        ?><a href="<?= $url ?>" data-event="mise-en-paiement-form-submit"
             data-url-redirect="<?= $this->url(null, [], [], true) ?>" class="btn btn-primary ajax-modal">Mise en
            paiement</a><?php
    }
}