<?php
/* @var $periodes \Application\Entity\Db\Periode[] */
/* @var $annee \Application\Entity\Db\Annee */

?>

    <h1>Extraction paie des indemnités de fin de contrat</h1>


<?php if (isset($periodes)): ?>
    <div class="alert alert-info" role="alert">
        Les indémnités de fin de contrat sont calculées automatiquement par OSE et sont disponibles à la mise en paiement sur la période du mois suivant la date
        de
        fin de mon contrat concerné.<br/>
    </div>

    <ul>
        <?php
        foreach ($periodes as $periode) {
            $url = $this->url('paiement/extraction-paie-prime', ['periode' => $periode->getCode()]);
            $title = $periode->getLibelleAnnuel($annee);
            echo '<li><a href="' . $url . '">' . $title . '</a></li>';
        }
        ?>
    </ul>
<?php endif; ?>