<?php

use Application\Provider\Privilege\Privileges;
use Paiement\Entity\MiseEnPaiementRecherche;

/* @var $recherche MiseEnPaiementRecherche */
/* @var $rechercheForm \Application\Form\Paiement\MiseEnPaiementRechercheForm */
/* @var $etatPaiement array */
/* @var $miseEnPaiementForm \Paiement\Form\Paiement\MiseEnPaiementForm */

$title = 'Paiement';
$rechercheForm->get('exporter-csv-imputation')->setValue('Exporter les imputations budgétaires');

$this->headTitle()->append($title);

?>
    <h1><?= $title ?></h1>
    <div class="card bg-default filter" data-etat="<?= $recherche->getEtat() ?>">

        <div class="card-header">Filtres</div>
        <div class="card-body">
            <?= $this->form()->openTag($rechercheForm->prepare()); ?>
            <?php

            echo $this->formControlGroup($rechercheForm->get('type-intervenant'));

            echo $this->formControlGroup($rechercheForm->get('periode'));

            echo $this->formRow($rechercheForm->get('afficher')) . ' ';

            if ($this->isAllowed(Privileges::getResourceId(Privileges::MISE_EN_PAIEMENT_EXPORT_CSV))) {
                echo $this->formRow($rechercheForm->get('exporter-csv-imputation')) . ' ';
            }


            echo $this->form()->closeTag();
            echo $this->formErrors($rechercheForm);
            ?>
        </div>
    </div>
<?php
