<?php

use Application\Provider\Privileges;
use Paiement\Entity\MiseEnPaiementRecherche;
use Paiement\Form\Paiement\MiseEnPaiementRechercheForm;

/* @var $recherche MiseEnPaiementRecherche */
/* @var $rechercheForm MiseEnPaiementRechercheForm */

$title = 'Export des imputations budgétaires dans SIHAM';
$rechercheForm->get('exporter-csv-imputation')->setValue('Exporter les imputations budgétaires');

$this->headTitle()->append($title);

?>
    <h1><?= $title ?></h1>
    <div class="card bg-default filter" data-etat="<?= $recherche->getEtat() ?>">

        <div class="card-header">Filtres</div>
        <div class="card-body">
            <?php
            echo $this->form()->openTag($rechercheForm->prepare());

            if ($rechercheForm->hasTypesIntervenants()) {
                echo $this->formControlGroup($rechercheForm->get('typeIntervenant'));
            } else {
                echo '<div class="alert alert-info">Aucune donnée trouvée</div>';
            }

            if ($rechercheForm->hasStructureFilter() && $rechercheForm->hasStructures()) {
                echo $this->formControlGroup($rechercheForm->get('structure'));
            }

            if ($rechercheForm->hasPeriodeFilter() && $rechercheForm->hasPeriodes()) {
                echo $this->formControlGroup($rechercheForm->get('periode'));
            }

            if ($rechercheForm->hasIntervenants()) {
                echo $this->formControlGroup($rechercheForm->get('intervenants'), $this->formAdvancedMultiCheckbox()->setHeight('20em'));
            }

            if ($rechercheForm->hasTypesIntervenants()) {
                echo $this->formRow($rechercheForm->get('suite')) . ' ';
            }

            if ($this->isAllowed(Privileges::getResourceId(Privileges::MISE_EN_PAIEMENT_EXPORT_CSV))) {
                echo $this->formRow($rechercheForm->get('exporter-csv-imputation')) . ' ';
            }

            echo $this->form()->closeTag();
            echo $this->formErrors($rechercheForm);
            ?>
        </div>
    </div>
<?php
