<?php

/* @var $form \Paiement\Form\Paiement\MiseEnPaiementForm */
/* @var $errors string[] */

echo $this->form()->openTag($form->prepare());

echo $this->formControlGroup($form->get('periode'));
echo $this->formControlGroup($form->get('date-mise-en-paiement'));

echo $this->formRow($form->get('submit'));

echo $this->form()->closeTag();
echo $this->formErrors( $form );

if ($errors) echo $this->messenger()->setMessages([UnicaenApp\View\Helper\Messenger::ERROR => $errors]);