<?php

/**
 * @var $this        \Application\View\Renderer\PhpRenderer
 * @var $intervenant \Application\Entity\Db\Intervenant
 * @var $paiements   \Paiement\Entity\Db\TblPaiement[]
 */

$this->intervenant($intervenant)->renderTitle("Mises en paiement");

$data     = [];
$periodes = [];
$total    = [
    'heures-a-payer'   => 0,
    'heures-demandees' => 0,
    'heures-payees'    => ['total' => 0],
];

foreach ($paiements as $paiement) {
    $sap = $paiement->getServiceAPayer();

    if ($sap instanceof \Application\Entity\Db\FormuleResultatService) {
        $sid = 'service-' . $sap->getService()->getId();
    } else {
        /* @var $sap \Application\Entity\Db\FormuleResultatServiceReferentiel */
        $sid = 'referentiel-' . $sap->getServiceReferentiel()->getId();
    }


    if (!isset($data[$sid])) {
        if ($sap instanceof \Application\Entity\Db\FormuleResultatService) {

            $d = [];

            $service = $sap->getService();
            if ($service->getElementPedagogique()) {
                $d['structure'] = (string)$this->structure($service->getElementPedagogique()->getStructure())->renderLink();
                $d['etape']     = (string)$this->etape($service->getElementPedagogique()->getEtape())->renderLink();
                $d['element']   = (string)$this->elementPedagogique($service->getElementPedagogique())->renderLink();
            } else {
                $d['structure']     = (string)$this->structure($service->getIntervenant()->getStructure())->renderLink();
                $d['etablissement'] = $this->etablissement($service->getEtablissement())->renderLink();
                $d['description']   = $service->getDescription();
            }
        } else {
            $d = [];

            /* @var $sap \Application\Entity\Db\FormuleResultatServiceReferentiel */
            $serviceReferentiel = $sap->getServiceReferentiel();
            $d['structure']     = (string)$this->structure($serviceReferentiel->getStructure())->renderLink();
            $d['fonction']      = (string)$this->fonctionReferentiel($serviceReferentiel->getFonctionReferentiel())->renderLink();
            $d['description']   = $serviceReferentiel->getCommentaires();
        }
        $d['heures-a-payer']     = $paiement->getHeuresAPayer();
        $total['heures-a-payer'] += $paiement->getHeuresAPayer();
        $d['heures-demandees']   = 0;
        $d['heures-payees']      = ['total' => 0];
        $data[$sid]              = $d;
    }

    // addition des heures demandées
    $data[$sid]['heures-demandees'] += $paiement->getHeuresDemandees();
    $total['heures-demandees']      += $paiement->getHeuresDemandees();

    // addition des heures payées
    if ($hp = $paiement->getHeuresPayees()) {
        $data[$sid]['heures-payees']['total'] += $paiement->getHeuresPayees();
        $total['heures-payees']['total']      += $paiement->getHeuresPayees();

        $ppId = $paiement->getPeriodePaiement()->getId();
        if (!isset($periodes[$ppId])) {
            $periodes[$ppId] = $paiement->getPeriodePaiement();
        }
        if (!isset($data[$sid]['heures-payees'][$ppId])) {
            $data[$sid]['heures-payees'][$ppId] = 0;
        }
        $data[$sid]['heures-payees'][$ppId] += $paiement->getHeuresPayees();

        if (!isset($total['heures-payees'][$ppId])) {
            $total['heures-payees'][$ppId] = 0;
        }
        $total['heures-payees'][$ppId] += $paiement->getHeuresPayees();
    }
}

uasort($periodes, function ($p1, $p2) {
    return $p1->getOrdre() - $p2->getOrdre();
});

foreach ($periodes as $id => $periode) {
    /* @var $periode \Application\Entity\Db\Periode */
    $periodes[$id] = $periode->getLibelleAnnuel($intervenant->getAnnee());
}

?>
<table class="table table-bordered table-sm">
    <tr>
        <th style="width:10%">Composante</th>
        <th style="width:25%">Formation</th>
        <th style="width:25%">Enseignement</th>
        <th style="width:10%">À payer <abbr title="Heures équivalent TD">(HETD)</abbr></th>
        <th style="width:10%"><abbr title="Demandes émanant de la composante">Demandes de paiement</abbr> <abbr
                    title="Heures équivalent TD">(HETD)</abbr></th>
        <th style="width:20%">Mises en paiement <abbr title="Heures équivalent TD">(HETD)</abbr></th>
    </tr>
    <?php
    foreach ($data as $d) {
        if ($d['heures-a-payer'] > 0) {
            $d['heures-restantes'] = $d['heures-a-payer'] - $d['heures-payees']['total'];

            echo '<tr>';
            if (isset($d['element'])) {
                // enseignement normal
                echo '<td>' . $d['structure'] . '</td>';
                echo '<td>' . $d['etape'] . '</td>';
                echo '<td>' . $d['element'] . '</td>';
            } elseif (isset($d['etablissement'])) {
                // enseignement extérieur
                echo '<td colspan="2">' . $d['etablissement'] . '</td>';
                echo '<td>' . $d['description'] . '</td>';
            } elseif (isset($d['fonction'])) {
                // référentiel
                echo '<td>' . $d['structure'] . '</td>';
                echo '<td>' . $d['fonction'] . ' <small>(Référentiel)</small></td>';
                echo '<td>' . $d['description'] . '</td>';
            }

            echo '<td>' . \UnicaenApp\Util::formattedNumber($d['heures-a-payer']) . '</td>';
            echo '<td>' . \UnicaenApp\Util::formattedNumber($d['heures-demandees']) . '</td>';
            echo '<td><table class="table table-bordered table-xs" style="margin-bottom: 0px">';

            foreach ($periodes as $pid => $periode) {
                if (isset($d['heures-payees'][$pid])) {
                    $heures = $d['heures-payees'][$pid];
                    echo '<tr><td style="width:60%">' . $periode . '</td><td style="width:40%;text-align:right">' . \UnicaenApp\Util::formattedNumber($heures) . '</td></tr>';
                }
            }
            echo '<tr><th>Total</th><td style="text-align:right">' . \UnicaenApp\Util::formattedNumber($d['heures-payees']['total']) . '</td></tr>';
            if ($d['heures-restantes'] > 0) {
                echo '<tr><th>Restant</th><td style="text-align:right">' . \UnicaenApp\Util::formattedNumber($d['heures-restantes']) . '</td></tr>';
            }

            echo '</table></td>';

            echo '</tr>';
        }
    }
    ?>
</table>
<table class="table table-bordered table-sm" style="width:30em">
    <tr>
        <th>Heures à payer <abbr title="Heures équivalent TD">(HETD)</abbr></th>
        <td colspan="2" style="text-align:right"><?= \UnicaenApp\Util::formattedNumber($total['heures-a-payer']) ?></td>
    </tr>
    <tr>
        <th><abbr title="Demandes émanant de la composante">Demandes de paiement</abbr> <abbr title="Heures équivalent TD">(HETD)</abbr>
        </th>
        <td colspan="2" style="text-align:right"><?= \UnicaenApp\Util::formattedNumber($total['heures-demandees']) ?></td>
    </tr>
    <tr>
        <th rowspan="<?= count($total['heures-payees']) ?>">Mises en paiement <abbr title="Heures équivalent TD">(HETD)</abbr>
        </th>
    </tr>
    <?php foreach ($periodes as $pid => $periode): if (isset($total['heures-payees'][$pid])): ?>
        <tr>
            <td><?= $periode ?></td>
            <td style="text-align:right"><?= \UnicaenApp\Util::formattedNumber($total['heures-payees'][$pid]) ?></td>
        </tr>
    <?php endif; endforeach; ?>
    <tr>
        <th>Mises en paiement (total <abbr title="Heures équivalent TD">HETD</abbr>)</th>
        <td colspan="2"
            style="text-align:right"><?= \UnicaenApp\Util::formattedNumber($total['heures-payees']['total']) ?></td>
    </tr>
    <tr>
        <th>Restant à payer <abbr title="Heures équivalent TD">(HETD)</abbr></th>
        <td colspan="2"
            style="text-align:right"><?= \UnicaenApp\Util::formattedNumber($total['heures-a-payer'] - $total['heures-payees']['total']) ?></td>
    </tr>
</table>