<?php

/**
 * @var $this        \Application\View\Renderer\PhpRenderer
 * @var $intervenant \Application\Entity\Db\Intervenant
 * @var $paiements   \Paiement\Entity\Db\TblPaiement[]
 */

$this->intervenant($intervenant)->renderTitle("Mises en paiement");

$data = [];
$periodes = [];
$total = [
    'heures-a-payer'   => 0,
    'heures-demandees' => 0,
    'heures-payees'    => ['total' => 0],
];

foreach ($paiements as $paiement) {
    $sap = $paiement->getServiceAPayer();

    if ($sap instanceof \Application\Entity\Db\FormuleResultatService) {
        $sapType = 'service';
        $sid = $sapType . '-' . $sap->getService()->getId();
    } elseif ($sap instanceof \Application\Entity\Db\FormuleResultatServiceReferentiel) {
        $sapType = 'referentiel';
        $sid = $sapType . '-' . $sap->getServiceReferentiel()->getId();
    } elseif ($sap instanceof \Mission\Entity\Db\Mission) {
        $sapType = 'mission';
        $sid = $sapType . '-' . $sap->getId();
    }


    if (!isset($data[$sid])) {
        $d = [
            'heures-a-payer'   => 0,
            'heures-demandees' => 0,
            'heures-payees'    => ['total' => 0],
        ];

        if ('service' == $sapType) {
            $service = $sap->getService();
            if ($service->getElementPedagogique()) {
                $d['structure'] = (string)$this->structure($service->getElementPedagogique()->getStructure())->renderLink();
                $d['service'] = [
                    'Formation'    => (string)$this->etape($service->getElementPedagogique()->getEtape())->renderLink(),
                    'Enseignement' => (string)$this->elementPedagogique($service->getElementPedagogique())->renderLink(),
                ];
            } else {
                $d['structure'] = (string)$this->structure($service->getIntervenant()->getStructure())->renderLink();
                $d['service'] = [
                    'Établissement' => $this->etablissement($service->getEtablissement())->renderLink(),
                    'Description'   => $service->getDescription(),
                ];
            }
        } elseif ('referentiel' == $sapType) {
            /* @var $sap \Application\Entity\Db\FormuleResultatServiceReferentiel */
            $serviceReferentiel = $sap->getServiceReferentiel();
            $d['structure'] = (string)$this->structure($serviceReferentiel->getStructure())->renderLink();
            $d['service'] = [
                'Fonction' => (string)$this->fonctionReferentiel($serviceReferentiel->getFonctionReferentiel())->renderLink(),
                ''         => $serviceReferentiel->getCommentaires(),
            ];
        } elseif ('mission' == $sapType) {
            /* @var $mission \Mission\Entity\Db\Mission */
            $mission = $sap;
            $d['structure'] = (string)$this->structure($mission->getStructure())->renderLink();
            $d['service'] = [
                'Type de mission' => (string)$mission->getTypeMission()->getLibelle(),
                ''                => $mission->getLibelle(),
            ];
        }
        $data[$sid] = $d;
    }

    $data[$sid]['heures-a-payer'] += $paiement->getHeuresAPayer();
    $data[$sid]['heures-demandees'] += $paiement->getHeuresDemandees();

    $total['heures-a-payer'] += $paiement->getHeuresAPayer();
    $total['heures-demandees'] += $paiement->getHeuresDemandees();

    // addition des heures payées
    if ($hp = $paiement->getHeuresPayees()) {
        $data[$sid]['heures-payees']['total'] += $paiement->getHeuresPayees();
        $total['heures-payees']['total'] += $paiement->getHeuresPayees();

        $ppId = $paiement->getPeriodePaiement()->getId();
        if (!isset($periodes[$ppId])) {
            $periodes[$ppId] = $paiement->getPeriodePaiement();
        }
        if (!isset($data[$sid]['heures-payees'][$ppId])) {
            $data[$sid]['heures-payees'][$ppId] = 0;
        }
        $data[$sid]['heures-payees'][$ppId] += $paiement->getHeuresPayees();

        if (!isset($total['heures-payees'][$ppId])) {
            $total['heures-payees'][$ppId] = 0;
        }
        $total['heures-payees'][$ppId] += $paiement->getHeuresPayees();
    }
}

uasort($periodes, function ($p1, $p2) {
    return $p1->getOrdre() - $p2->getOrdre();
});

foreach ($periodes as $id => $periode) {
    /* @var $periode \Application\Entity\Db\Periode */
    $periodes[$id] = $periode->getLibelleAnnuel($intervenant->getAnnee());
}

?>
<table class="table table-bordered table-sm">
    <tr>
        <th style="width:10%">Composante</th>
        <th style="width:50%">Service</th>
        <th style="width:10%">À payer <abbr title="Heures équivalent TD">(HETD)</abbr></th>
        <th style="width:10%"><abbr title="Demandes émanant de la composante">Demandes de paiement</abbr> <abbr
                    title="Heures équivalent TD">(HETD)</abbr></th>
        <th style="width:20%">Mises en paiement <abbr title="Heures équivalent TD">(HETD)</abbr></th>
    </tr>
    <?php
    foreach ($data as $d) {
        if ($d['heures-a-payer'] + $d['heures-demandees'] > 0) {
            $d['heures-restantes'] = $d['heures-a-payer'] - $d['heures-payees']['total'];

            echo '<tr>';
            echo '<td>' . $d['structure'] . '</td>';
            echo '<td>';
            foreach ($d['service'] as $k => $v) {
                if ($k) {
                    echo "<b>$k</b> : ";
                }
                echo "$v<br />";
            }
            echo '</td>';
            echo '<td>' . \UnicaenApp\Util::formattedNumber($d['heures-a-payer']) . '</td>';
            echo '<td>' . \UnicaenApp\Util::formattedNumber($d['heures-demandees']) . '</td>';
            echo '<td><table class="table table-bordered table-xs" style="margin-bottom: 0px">';

            foreach ($periodes as $pid => $periode) {
                if (isset($d['heures-payees'][$pid])) {
                    $heures = $d['heures-payees'][$pid];
                    echo '<tr><td style="width:60%">' . $periode . '</td><td style="width:40%;text-align:right">' . \UnicaenApp\Util::formattedNumber($heures) . '</td></tr>';
                }
            }
            echo '<tr><th>Total</th><td style="text-align:right">' . \UnicaenApp\Util::formattedNumber($d['heures-payees']['total']) . '</td></tr>';
            if ($d['heures-restantes'] > 0) {
                echo '<tr><th>Restant</th><td style="text-align:right">' . \UnicaenApp\Util::formattedNumber($d['heures-restantes']) . '</td></tr>';
            }

            echo '</table></td>';

            echo '</tr>';
        }
    }
    ?>
</table>
<table class="table table-bordered table-sm" style="width:30em">
    <tr>
        <th>Heures à payer <abbr title="Heures équivalent TD">(HETD)</abbr></th>
        <td colspan="2" style="text-align:right"><?= \UnicaenApp\Util::formattedNumber($total['heures-a-payer']) ?></td>
    </tr>
    <tr>
        <th><abbr title="Demandes émanant de la composante">Demandes de paiement</abbr> <abbr
                    title="Heures équivalent TD">(HETD)</abbr>
        </th>
        <td colspan="2"
            style="text-align:right"><?= \UnicaenApp\Util::formattedNumber($total['heures-demandees']) ?></td>
    </tr>
    <tr>
        <th rowspan="<?= count($total['heures-payees']) ?>">Mises en paiement <abbr
                    title="Heures équivalent TD">(HETD)</abbr>
        </th>
    </tr>
    <?php foreach ($periodes as $pid => $periode): if (isset($total['heures-payees'][$pid])): ?>
        <tr>
            <td><?= $periode ?></td>
            <td style="text-align:right"><?= \UnicaenApp\Util::formattedNumber($total['heures-payees'][$pid]) ?></td>
        </tr>
    <?php endif; endforeach; ?>
    <tr>
        <th>Mises en paiement (total <abbr title="Heures équivalent TD">HETD</abbr>)</th>
        <td colspan="2"
            style="text-align:right"><?= \UnicaenApp\Util::formattedNumber($total['heures-payees']['total']) ?></td>
    </tr>
    <tr>
        <th>Restant à payer <abbr title="Heures équivalent TD">(HETD)</abbr></th>
        <td colspan="2"
            style="text-align:right"><?= \UnicaenApp\Util::formattedNumber($total['heures-a-payer'] - $total['heures-payees']['total']) ?></td>
    </tr>
</table>