<?php
// Generated by UnicaenCode
return [
    'plafond/plafond/index'              => __DIR__ . '/view/plafond/plafond/index.phtml',
    'plafond/plafond/editer'             => __DIR__ . '/view/plafond/plafond/editer.phtml',
    'plafond/plafond/editer-application' => __DIR__ . '/view/plafond/plafond/editer-application.phtml',
    'plafond/plafond-structure/index'    => __DIR__ . '/view/plafond/plafond-structure/index.phtml',
    'plafond/plafond-structure/editer'   => __DIR__ . '/view/plafond/plafond-structure/editer.phtml',
    'plafond/derogation/index'           => __DIR__ . '/view/plafond/derogation/index.phtml',
];