<?php

use Application\Provider\Privilege\Privileges;

/**
 * @var $this          \Application\View\Renderer\PhpRenderer
 * @var $notes         \Intervenant\Entity\Db\Note[]
 * @var $intervenant   \Application\Entity\Db\Intervenant
 *
 */


$canEdit = $this->isAllowed(Privileges::getResourceId(Privileges::INTERVENANT_NOTE_EDITION));

echo $this->messenger()->addCurrentMessagesFromFlashMessenger();

$this->headTitle()->append($title = "Notes sur l'intervenant");

?>
<h1 class="page-header"><?php echo $title ?></h1>

<table class="table table-bordered table-hover table-condensed">
    <head>
        <tr>
            <th>Libellé</th>
            <th>Contenu</th>
            <th>Action</th>
        </tr>
    </head>
    <body>
    <?php if (!empty($notes)): ?>
        <?php foreach ($notes as $note): ?>
            <tr class="note" data-id="<?= $note->getId() ?>">
                <td class="col-lg-5"><?= $note->getType()->getLibelle() . ' par ' . $note->getHistoCreateur()->getDisplayName() . ' le ' . $note->getHistoCreation()->format(\Application\Constants::DATETIME_FORMAT) ?></td>
                <td class="col-lg-7"><?= $note->getContenu() ?></td>
                <td>
                    <div class="btn-group">
                        <a class="ajax-modal" data-event="note-edition" href="<?= $this->url('note/saisir', ['intervenant' => $intervenant->getId(), 'note' => $note->getId()]); ?>"><i class="fa fa-edit fa-lg" aria-hidden="true"></i></a>
                        <?php $this->isAllowed($note, Privileges::INTERVENANT_NOTE_SUPPRESSION);
                        var_dump($this->isAllowed($note, Privileges::INTERVENANT_NOTE_SUPPRESSION));
                        die;
                        ?>
                        <a class="pop-ajax"
                           href="<?= $this->url('note/supprimer', ['intervenant' => $intervenant->getId(), 'note' => $note->getId()]); ?>"
                           title="Supprimer la note"
                           data-content="<p class='lead text-danger'><strong>Attention!</strong> Confirmez-vous cette suppression ?</p>"
                           data-confirm="true"
                           data-confirm-button="Oui"
                           data-cancel-button="Non"
                           data-submit-reload="true"
                        >
                            <i class="fa fa-trash fa-lg" aria-hidden="true"></i>
                        </a>

                    </div>
                </td>
            </tr>
        <?php endforeach; ?>
    <?php else: ?>
        <tr>
            <td colspan="3">
                Aucune note pour l'intervenant
            </td>
        </tr>
    <?php endif; ?>

    </body>
</table>

<?php if ($canEdit): ?>
    <a class="btn btn-primary ajax-modal" data-event="note-edition" href="<?= $this->url('note/saisir', ['intervenant' => $intervenant->getId()]); ?>"><span class="glyphicon glyphicon-plus"></span> Ajouter une note</a>
<?php endif; ?>
<script type="text/javascript">
    $(function () {
        $("body").on("note-edition", function (event, data) {
            str = window.location.href;
            if (str.indexOf("tab=notes") !== -1) {
                window.location.reload();
            } else {
                window.location.assign(window.location.href + '?tab=notes');
            }
            //window.location.reload();

        });
    });
</script>

