<?php

/* @var $form \Intervenant\Form\NoteSaisieForm */
/* @var $errors array */

echo $this->messenger()->addCurrentMessagesFromFlashMessenger();


echo $this->form()->openTag($form);

echo $this->formControlGroup($form->get('libelle'));
echo $this->formControlGroup($form->get('contenu'));
echo $this->formControlGroup($form->get('type'));
echo $this->formRow($form->get('submit'));
echo $this->formElement($form->get('security'));

echo $this->formHidden($form->get('id'));

echo $this->form()->closeTag();