<?php

/* @var $form \Intervenant\Form\NoteSaisieForm */
/* @var $errors array */

$this->headTitle('test');

echo $this->messenger()->addCurrentMessagesFromFlashMessenger();


echo $this->form()->openTag($form);

echo $this->formControlGroup($form->get('libelle'));
echo $this->formControlGroup($form->get('contenu')->setAttributes(['rows' => 15, 'id' => 'body']));
?>
    <div style="display:none">
        <?= $this->formControlGroup($form->get('type')); ?>
    </div>
<?php
echo $this->formRow($form->get('submit'));
echo $this->formElement($form->get('security'));

echo $this->formHidden($form->get('id'));

echo $this->form()->closeTag();