<?php

use Application\Provider\Privilege\Privileges;

/* @var $role Application\Entity\Db\Role */
/* @var $statut Intervenant\Entity\Db\Statut */
/* @var $privilege UnicaenAuth\Entity\Db\Privilege */

$object = empty($role) ? $statut : $role;

$canEdit = $this->isAllowed(Privileges::getResourceId(Privileges::DROIT_PRIVILEGE_EDITION));

if ($object->getPrivilege()->contains($privilege)):
    ?>

    <?php if ($canEdit): ?><a href="javascript:void(0)" data-action="refuser" title="Privilège accordé. Cliquez pour le retirer."><?php endif; ?>
    <span class="glyphicon glyphicon-ok text-success"></span>
    <?php if ($canEdit): ?></a><?php endif; ?>

<?php else: ?>

    <?php if ($canEdit): ?><a href="javascript:void(0)" data-action="accorder" title="Privilège refusé. Cliquez pour l'accorder."><?php endif; ?>
    <span class="glyphicon glyphicon-remove text-danger refuse"></span>
    <?php if ($canEdit): ?></a><?php endif; ?>

<?php endif; ?>