<?php

use Service\Entity\Db\TypeVolumeHoraire;
use UnicaenApp\View\Helper\Messenger;

/* @var $typeVolumeHoraire TypeVolumeHoraire */

$titles = [
    TypeVolumeHoraire::CODE_PREVU   => 'Référentiel',
    TypeVolumeHoraire::CODE_REALISE => 'Constatation du référentiel réalisé',
];

$title = $titles[$typeVolumeHoraire->getCode()];
$title .= ' <small>' . $intervenant . '</small>';
$this->headTitle()->append($intervenant->getNomUsuel())->append("Enseignements");

$canAddServiceReferentiel = true;

?>

    <h1 class="page-header"><?= $title; ?></h1>

<?php //echo $this->messenger()->addMessagesFromFlashMessenger() ?>

    <style>
        .modal-dialog {
            width: 60%;
        }

        div.row {
            padding: 1px;
        }

        th.heures, td.heures {
            width: 3em !important;
        }
    </style>

<?php

if ('afficher' === $action) {
    $serviceReferentielListe = $this->serviceReferentielListe($services);
    $serviceReferentielListe
        ->setTypeVolumeHoraire($typeVolumeHoraire)
        ->setAddButtonVisibility($canAddServiceReferentiel);

    $serviceReferentielListe->showPrevuToPrevu($intervenant);

    echo $serviceReferentielListe->render();
} else {
    echo $this->messenger()->setMessage('Cliquez sur "Afficher" pour afficher le référentiel.', Messenger::INFO);
}