<?php

use Service\Entity\Db\TypeVolumeHoraire;
use Workflow\Entity\Db\WorkflowEtape;

/**
 * @var $this              \Application\View\Renderer\PhpRenderer
 * @var $typeVolumeHoraire TypeVolumeHoraire
 * @var $intervenant       \Intervenant\Entity\Db\Intervenant
 * @var $referentiels      \Referentiel\Entity\Db\ServiceReferentiel[]
 */


if ($typeVolumeHoraire->isPrevu()) {
    $wfEtape = WorkflowEtape::REFERENTIEL_SAISIE;
    $title     = 'Référentiel';
} else {
    $wfEtape = WorkflowEtape::REFERENTIEL_SAISIE_REALISE;
    $title     = 'Constatation du référentiel réalisé';
}

//$menuUrl = $this->url(null, ['intervenant' => $intervenant->getId()], ['query' => ['menu' => 1]]);

$this->intervenant($intervenant)->renderTitle($title);
echo $this->messenger()->addCurrentMessagesFromFlashMessenger();

$ref = $this->referentiels($typeVolumeHoraire, $intervenant, $referentiels);
$ref->setHorodatage(true);
echo $ref;

echo '<hr />';

echo $this->vue('workflow/nav', ['intervenant' => $intervenant->getId(), 'etape' => $wfEtape]);