<?php

/* @var $service Referentiel\Entity\Db\ServiceReferentiel */
/* @var $params array */

if (!$service) {
    return;
}

$serviceListe = $this->serviceReferentielListe([$service]);
/* @var $serviceListe \Referentiel\View\Helper\ListeViewHelper */

if (!empty($params)) $serviceListe->applyParams($params);

if ($onlyContent) {
    echo $this->serviceReferentielLigne($serviceListe, $service)->render($details);
} else {
    echo $serviceListe->renderLigne($service, $details);
}