<?php

/**
 * @var $this              \Application\View\Renderer\PhpRenderer
 * @var $validations       \Workflow\Entity\Db\Validation[]
 * @var $typeVolumehoraire \Service\Entity\Db\TypeVolumeHoraire
 */

$this->headTitle()->append($intervenant->getNomUsuel())->append($title);

?>
    <h1 class="page-header">
        <?= $title ?>
        <small><?= $intervenant ?></small>
    </h1>
<?php

$wells = [
    'non-valides' => 'Référentiel non validé',
    'valides'     => 'Référentiel validé',
];

echo $this->messenger()->addCurrentMessagesFromFlashMessenger();
echo $this->plafonds($intervenant, $typeVolumeHoraire);

foreach ($wells as $well => $title) {
    if ($services[$well]) {
        echo '<div class="well"><h2>' . $title . '</h2>';
        foreach ($services[$well] as $validationId => $srvs) {
            $validation = $validations[$validationId];
            echo $this->partial('referentiel/partial/validation-referentiel', [
                'validation'        => $validation,
                'structure'         => $validation->getStructure(),
                'services'          => $srvs,
                'typeVolumeHoraire' => $typeVolumeHoraire,
            ]);
        }
        echo '</div>';
    }
}

echo $this->vue('workflow/nav', ['intervenant' => $intervenant->getId(), 'etape' => $typeVolumeHoraire->getWfEtapeReferentielValidation()]);