<?php

/**
 * @var $this                 \Application\View\Renderer\PhpRenderer
 * @var $title                string
 * @var $plafondStructure     \Plafond\Entity\Db\PlafondStructure
 * @var $form                 \Plafond\Form\PlafondStructureForm
 */

?>
    <h1><?= $title ?></h1>
<?php

echo $this->form()->openTag($form);

echo $this->formControlGroup($form->get('plafond'));
echo $this->formControlGroup($form->get('heures'));
echo '<div class="row">';
echo '<div class="col-md-6">';
echo $this->formControlGroup($form->get('anneeDebut'));
echo '</div>';
echo '<div class="col-md-6">';
echo $this->formControlGroup($form->get('anneeFin'));
echo '</div>';
echo '</div>';

echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();

