<?php

/**
 * @var $this                 \Application\View\Renderer\PhpRenderer
 * @var $title                string
 * @var $plafondStructure     \Plafond\Entity\Db\PlafondStructure
 * @var $form                 \Plafond\Form\PlafondStructureForm
 */

?>
    <h1><?= $title ?></h1>
<?php

echo $this->form()->openTag($form);
echo $this->formControlGroup($form->get('plafond'));
echo $this->formControlGroup($form->get('plafondEtat'));
echo $this->formControlGroup($form->get('heures'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
