<?php

use Application\Entity\Db\Annee;
use Application\Provider\Privileges;
use OffreFormation\Entity\Db\TypeIntervention;

/**
 * @var $this                         \Application\View\Renderer\PhpRenderer
 * @var $typesInterventions           TypeIntervention[]
 * @var $annee                        Annee
 */

$this->headTitle()->append("Types d'interventions");

$canEdit = $this->isAllowed(Privileges::getResourceId(Privileges::TYPE_INTERVENTION_EDITION));
?>
<h1 class="page-header">Types d'interventions</h1>

<table class="table table-bordered table-sm table-hover">
    <thead>
    <tr>
        <th rowspan="2">Code</th>
        <th rowspan="2">Libellé</th>
        <th colspan="2">Taux HETD</th>
        <th rowspan="2">Effective</th>
        <th rowspan="2">Règles</th>
        <th rowspan="2" style="text-align:center;">Visibilité</th>
        <?php if ($canEdit): ?>
            <th rowspan="2">Actions</th><?php endif; ?>
    </tr>
    <tr>
        <td class="table-bordered">service</td>
        <td class="table-bordered">compl.</td>
    </tr>
    </thead>
    <tbody class="triables">
    <?php foreach ($typesInterventions as $ti): ?>
        <tr class="champ-triable" data-id="<?= $ti->getId() ?>">
            <td>
                <?= $ti->getCode() ?>&nbsp;
            </td>
            <td><?= $ti->getLibelle() ?></td>
            <?= $this->typeInterventionAdmin($ti); ?>
            <td><?= validiteIntervalle($ti->getAnneeDebut(), $ti->getAnneeFin()); ?></td>
            <td><?= implode(', ', $ti->getRegles()) ?></td>
            <td style="text-align:left;">
                <?= ($ti->isVisible() ? 'Visible' : 'Caché') . ' - ' . ($ti->isVisibleExterieur() ? 'Visible en saisie extérieure' : 'Caché pour la saisie extérieure'); ?>
                <?php
                $tisList = $ti->getTypeInterventionStructureValides($annee);
                $hasTis  = $tisList->count() > 0;
                ?>
                <?php if ($hasTis): ?>
                    <table class="table table-bordered table-xs tbl-tis">
                        <?php foreach ($tisList as $tis) : ?>
                            <tr>
                                <td><?= ($tis->isVisible() ? $tis->getStructure() : '<s>' . $tis->getStructure() . '</s>') ?></td>
                                <td><?= validiteIntervalle($tis->getAnneeDebut(), $tis->getAnneeFin()); ?></td>
                                <?php if ($this->isAllowed($tis, Privileges::TYPE_INTERVENTION_EDITION)): ?>

                                    <td style="width: 50px;">
                                        <a class="pop-ajax"
                                           data-min-width="400"
                                           data-event="type-intervention-saisie"
                                           href="<?= $this->url('type-intervention/type-intervention-structure-saisie', ['typeIntervention' => $ti->getId(), 'typeInterventionStructure' => $tis->getId()]); ?>"
                                           data-submit-reload="true">
                                            <i class="fas fa-pen-to-square"></i></a>
                                        <a class="pop-ajax"
                                           data-event="type-intervention-saisie"
                                           href="<?= $this->url('type-intervention/type-intervention-structure-delete', ['typeInterventionStructure' => $tis->getId()]) ?>"
                                           title="Supprimer le type d'intervention"
                                           data-content="<p class='lead text-danger'><strong>Attention!</strong> Confirmez-vous cette suppression ?</p>"
                                           data-confirm="true" data-confirm-button="Oui"
                                           data-cancel-button="Non"
                                           data-submit-reload="true">
                                            <i class="fas fa-trash-can"></i></a>
                                    </td>
                                <?php endif; ?>
                            </tr>
                        <?php endforeach; ?>
                    </table>
                <?php endif; ?>
                <?php if ($canEdit) : ?>
                    <a class="btn btn-primary btn-sm  pop-ajax"
                       data-event="type-intervention-saisie"
                       href="<?= $this->url('type-intervention/type-intervention-structure-saisie', ['typeIntervention' => $ti->getId()]) ?>"
                       title="Ajouter un type d'intervention pour une structure"
                       data-submit-reload="true">
                        Ajouter une exception pour une structure</a>
                <?php endif; ?>
            </td>
            <?php if ($canEdit): ?>
                <td style="text-align:center;width:1px;white-space: nowrap">
                    <i class="fas fa-arrows-alt"
                       title="Vous pouvez trier les champs en déplaçant les lignes du tableau"></i>
                    <a class="ajax-modal"
                       data-event="type-intervention-saisie"
                       href="<?= $this->url('type-intervention/saisie', ['typeIntervention' => $ti->getId()]) ?>"
                       title="Modifier le type d'intervention">
                        <i class="fas fa-pen-to-square"></i></a>
                    <a class="pop-ajax"
                       href="<?= $this->url('type-intervention/delete', ['typeIntervention' => $ti->getId()]) ?>"
                       title="Supprimer le type d'intervention"
                       data-content="<p class='lead text-danger'><strong>Attention!</strong> Confirmez-vous cette suppression ?</p>"
                       data-confirm="true"
                       data-confirm-button="Oui"
                       data-cancel-button="Non"
                       data-submit-reload="true"
                    >
                        <i class="fas fa-trash-can"></i>
                    </a>
                </td>
            <?php endif; // $ti ?>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<script type="text/javascript">
    $(function () {
        $('[data-bs-toggle="tooltip"]').tooltip()
    })
</script>
<?php if ($canEdit): ?>
    <a class="btn btn-primary ajax-modal" data-event="type-intervention-saisie"
       href="<?= $this->url('type-intervention/saisie') ?>"
       title="Ajouter un type d'intervention">
        <i class="fas fa-plus"></i>
        Ajouter un type d'intervention</a>

    <script type="text/javascript">
        $(function () {
            $("body").on("type-intervention-saisie", function (event, data) {
                window.location.reload();
            });

            $(".triables").sortable({
                handle: '.fa-arrows-alt',
                axis: 'y',
                update: function (event, ui) {
                    var champsIds = '';
                    ui.item.parent().find('tr.champ-triable').each(function () {
                        if (champsIds != '') champsIds += ',';
                        champsIds += $(this).data('id');
                    });
                    console.debug(champsIds);
                    $.ajax({
                        type: 'POST',
                        url: unicaenVue.url('type-intervention/type-intervention-trier'),
                        data: {champsIds: champsIds},
                        success: function (res) {
                            unicaenVue.flashMessenger.toast('Tri des champs effectué', 'success');
                        },
                    });
                }
            });
        });
    </script>
<?php endif; ?>
<style>
    .triables {
        align: left;
    }

    .champ-triable tr {
        align: left;
    }

    .tbl-tis {
        margin-bottom: 1px;
    }
</style>