<?php
/**
 * @var $this  \Application\View\Renderer\PhpRenderer
 * @var $form  \Application\Form\FonctionReferentiel\TypeInterventionSaisieForm
 */
echo $this->messenger()->addCurrentMessagesFromFlashMessenger();

echo $this->form()->openTag($form);

echo $this->formControlGroup($form->get('type-intervention'));
?>
<div class="row">
    <div class="col-md-6">
        <BR>
        <?= $this->formControlGroup($form->get('statut')); ?>
    </div>
    <div class="col-md-3">
        <?= $this->formControlGroup($form->get('taux-hetd-service')); ?>
    </div>
    <div class="col-md-3">
        <?= $this->formControlGroup($form->get('taux-hetd-complementaire')); ?>
    </div>
</div>
<?php echo $this->formSubmit($form->get('submit'));
echo $this->formControlGroup($form->get('security'));
echo $this->form()->closeTag();
?>
