<?php

use Application\Filter\StringFromFloat;
use Application\Provider\Privileges;
use OffreFormation\Entity\Db\TypeInterventionStatut;

/**
 * @var $this                              \Application\View\Renderer\PhpRenderer
 * @var $typeInterventionStatuts           TypeInterventionStatut[]
 * @var $typeIntervention                  TypeIntervention
 * */
echo $this->messenger()->addCurrentMessagesFromFlashMessenger();
$canEdit = $this->isAllowed(Privileges::getResourceId(Privileges::TYPE_INTERVENTION_EDITION));
?>

<table class="table table-bordered table-xs table-hover">
    <thead>
    <tr>
        <th>Statut d'intervenant</th>
        <th>Taux HETD service</th>
        <th>Taux HETD complémentaire</th>
        <?php if ($canEdit): ?>
            <th>Actions</th><?php endif; ?>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($typeInterventionStatuts as $tis): ?>
        <tr>
            <td>
                <?= $tis->getStatut()->getLibelle() ?>&nbsp;
            </td>
            <td>
                <?= StringFromFloat::run($tis->getTauxHETDService()) ?>
            </td>
            <td>
                <?= StringFromFloat::run($tis->getTauxHETDComplementaire()) ?>
            </td>
            <?php if ($canEdit): ?>
                <td>
                    <a class="ajax-modal"
                       data-min-width="400"
                       data-event="type-intervention-statut"
                       href="<?= $this->url('type-intervention/statut-saisie', ['typeIntervention' => $tis->getTypeIntervention()->getId(), 'typeInterventionStatut' => $tis->getId()]); ?>"
                       data-submit-reload="false">
                        <i class="fas fa-pen-to-square"></i></a>
                    <a class="ajax-modal"
                       data-event="type-intervention-statut"
                       href="<?= $this->url('type-intervention/statut-delete', ['typeIntervention' => $tis->getTypeIntervention()->getId(), 'typeInterventionStatut' => $tis->getId()]) ?>"
                       data-submit-reload="false">
                        <i class="fas fa-trash-can"></i></a>
                </td>

            <?php endif; ?>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<?php if ($canEdit) : ?>
    <a class="btn btn-primary ajax-modal"
       data-event="type-intervention-statut"
       href="<?= $this->url('type-intervention/statut-saisie', ['typeIntervention' => $typeIntervention->getId()]) ?>"
       title="Ajouter un statut spécifique pour le type d'intervention"
       onclick="window.close()"
       data-submit-reload="false">
        Ajouter un statut pour le type d'intervention</a>
<?php endif; ?>

<script type="text/javascript">
    $(function () {
        $("body").on("type-intervention-statut", function (event, data) {
        });
    });

</script>