<?php

/**
 * @var $this       \Application\View\Renderer\PhpRenderer
 * @var $errors     array
 * @var $form       \Application\Form\Supprimer
 * @var $title      string
 * /* @var $typeIntervention \OffreFormation\Entity\Db\TypeIntervention
 */

$this->messenger()->addCurrentMessagesFromFlashMessenger();
if ($form) {
    echo '<p></span class="lead text-danger"><strong>Attention!</strong> Confirmez-vous la suppression ?</p>';
    echo $this->formSupprimer($form);
}