<?php
/**
 * Generated by UnicaenCode
 * Commande : php public/index.php UnicaenCode  module='Contrat'
 */
return [
    'Contrat\Assertion\ContratAssertion'                => __DIR__ . '/src/Assertion/ContratAssertion.php',
    'Contrat\Controller\ContratController'              => __DIR__ . '/src/Controller/ContratController.php',
    'Contrat\Controller\ContratControllerFactory'       => __DIR__ . '/src/Controller/ContratControllerFactory.php',
    'Contrat\Entity\Db\Contrat'                         => __DIR__ . '/src/Entity/Db/Contrat.php',
    'Contrat\Entity\Db\ContratServiceListe'             => __DIR__ . '/src/Entity/Db/ContratServiceListe.php',
    'Contrat\Entity\Db\TypeContrat'                     => __DIR__ . '/src/Entity/Db/TypeContrat.php',
    'Contrat\Form\ContratRetourForm'                    => __DIR__ . '/src/Form/ContratRetourForm.php',
    'Contrat\Form\ContratRetourFormFactory'             => __DIR__ . '/src/Form/ContratRetourFormFactory.php',
    'Contrat\Form\ContratValidationForm'                => __DIR__ . '/src/Form/ContratValidationForm.php',
    'Contrat\Form\ContratValidationFormFactory'         => __DIR__ . '/src/Form/ContratValidationFormFactory.php',
    'Contrat\Form\EnvoiMailContratForm'                 => __DIR__ . '/src/Form/EnvoiMailContratForm.php',
    'Contrat\Form\EnvoiMailContratFormFactory'          => __DIR__ . '/src/Form/EnvoiMailContratFormFactory.php',
    'Contrat\Module'                                    => __DIR__ . '/Module.php',
    'Contrat\Processus\ContratProcessus'                => __DIR__ . '/src/Processus/ContratProcessus.php',
    'Contrat\Processus\ContratProcessusFactory'         => __DIR__ . '/src/Processus/ContratProcessusFactory.php',
    'Contrat\Service\ContratService'                    => __DIR__ . '/src/Service/ContratService.php',
    'Contrat\Service\ContratServiceFactory'             => __DIR__ . '/src/Service/ContratServiceFactory.php',
    'Contrat\Service\ContratServiceListeService'        => __DIR__ . '/src/Service/ContratServiceListeService.php',
    'Contrat\Service\ContratServiceListeServiceFactory' => __DIR__ . '/src/Service/ContratServiceListeServiceFactory.php',
    'Contrat\Service\TypeContratService'                => __DIR__ . '/src/Service/TypeContratService.php',
    'Contrat\Service\TypeContratServiceFactory'         => __DIR__ . '/src/Service/TypeContratServiceFactory.php',
];