<?php
/**
 * Generated by UnicaenCode
 * Commande : ose-code  module='Contrat'
 */
return [
    'contrat/contrat/envoyer-mail'           => __DIR__ . '/view/contrat/contrat/envoyer-mail.phtml',
    'contrat/contrat/partial/contrat'        => __DIR__ . '/view/contrat/contrat/partial/contrat.phtml',
    'contrat/contrat/partial/contrat-heures' => __DIR__ . '/view/contrat/contrat/partial/contrat-heures.phtml',
    'contrat/contrat/index'                  => __DIR__ . '/view/contrat/contrat/index.phtml',
    'contrat/contrat/lister-fichier'         => __DIR__ . '/view/contrat/contrat/lister-fichier.phtml',
    'contrat/contrat/saisir-retour'          => __DIR__ . '/view/contrat/contrat/saisir-retour.phtml',
];