<?php
/**
 * Generated by UnicaenCode
 * Commande : php public/index.php UnicaenCode  module='Referentiel'
 */
return [
    'Referentiel\Assertion\ReferentielAssertion'            => __DIR__ . '/src/Assertion/ReferentielAssertion.php',
    'Referentiel\Controller\FonctionReferentielController'  => __DIR__ . '/src/Controller/FonctionReferentielController.php',
    'Referentiel\Controller\ServiceReferentielController'   => __DIR__ . '/src/Controller/ServiceReferentielController.php',
    'Referentiel\Entity\Db\FonctionReferentiel'             => __DIR__ . '/src/Entity/Db/FonctionReferentiel.php',
    'Referentiel\Entity\Db\ServiceReferentiel'              => __DIR__ . '/src/Entity/Db/ServiceReferentiel.php',
    'Referentiel\Entity\Db\TblValidationReferentiel'        => __DIR__ . '/src/Entity/Db/TblValidationReferentiel.php',
    'Referentiel\Entity\Db\VolumeHoraireReferentiel'        => __DIR__ . '/src/Entity/Db/VolumeHoraireReferentiel.php',
    'Referentiel\Entity\VolumeHoraireReferentielListe'      => __DIR__ . '/src/Entity/VolumeHoraireReferentielListe.php',
    'Referentiel\Form\FonctionReferentielSaisieForm'        => __DIR__ . '/src/Form/FonctionReferentielSaisieForm.php',
    'Referentiel\Form\Saisie'                               => __DIR__ . '/src/Form/Saisie.php',
    'Referentiel\Form\SaisieFieldset'                       => __DIR__ . '/src/Form/SaisieFieldset.php',
    'Referentiel\Hydrator\ListeFilterHydrator'              => __DIR__ . '/src/Hydrator/ListeFilterHydrator.php',
    'Referentiel\Module'                                    => __DIR__ . '/Module.php',
    'Referentiel\Processus\ServiceReferentielProcessus'     => __DIR__ . '/src/Processus/ServiceReferentielProcessus.php',
    'Referentiel\Processus\ValidationReferentielProcessus'  => __DIR__ . '/src/Processus/ValidationReferentielProcessus.php',
    'Referentiel\Service\FonctionReferentielService'        => __DIR__ . '/src/Service/FonctionReferentielService.php',
    'Referentiel\Service\ServiceReferentielService'         => __DIR__ . '/src/Service/ServiceReferentielService.php',
    'Referentiel\Service\VolumeHoraireReferentielService'   => __DIR__ . '/src/Service/VolumeHoraireReferentielService.php',
    'Referentiel\View\Helper\FonctionReferentielFactory'    => __DIR__ . '/src/View/Helper/FonctionReferentielFactory.php',
    'Referentiel\View\Helper\FonctionReferentielViewHelper' => __DIR__ . '/src/View/Helper/FonctionReferentielViewHelper.php',
    'Referentiel\View\Helper\FormSaisieFactory'             => __DIR__ . '/src/View/Helper/FormSaisieFactory.php',
    'Referentiel\View\Helper\FormSaisieViewHelper'          => __DIR__ . '/src/View/Helper/FormSaisieViewHelper.php',
    'Referentiel\View\Helper\LigneFactory'                  => __DIR__ . '/src/View/Helper/LigneFactory.php',
    'Referentiel\View\Helper\LigneViewHelper'               => __DIR__ . '/src/View/Helper/LigneViewHelper.php',
    'Referentiel\View\Helper\ReferentielsFactory'           => __DIR__ . '/src/View/Helper/ReferentielsFactory.php',
    'Referentiel\View\Helper\ReferentielsViewHelper'        => __DIR__ . '/src/View/Helper/ReferentielsViewHelper.php',
];