<?php
/**
 * Generated by UnicaenCode
 * Commande : php public/index.php UnicaenCode  module='Referentiel'
 */
return [
    'referentiel/initialisation'                 => __DIR__ . '/view/referentiel/initialisation.phtml',
    'referentiel/rafraichir-ligne'               => __DIR__ . '/view/referentiel/rafraichir-ligne.phtml',
    'referentiel/suppression'                    => __DIR__ . '/view/referentiel/suppression.phtml',
    'referentiel/saisie'                         => __DIR__ . '/view/referentiel/saisie.phtml',
    'referentiel/fonction-referentiel/saisie'    => __DIR__ . '/view/referentiel/fonction-referentiel/saisie.phtml',
    'referentiel/fonction-referentiel/index'     => __DIR__ . '/view/referentiel/fonction-referentiel/index.phtml',
    'referentiel/validation'                     => __DIR__ . '/view/referentiel/validation.phtml',
    'referentiel/partial/validation-referentiel' => __DIR__ . '/view/referentiel/partial/validation-referentiel.phtml',
    'referentiel/index'                          => __DIR__ . '/view/referentiel/index.phtml',
];