<?php

use Application\Provider\Privileges;

//$this->headTitle()->append($title);

/**
 * @var $autre \Dossier\Entity\Db\DossierAutre
 */

$canEdit = $this->isAllowed(Privileges::getResourceId(Privileges::INTERVENANT_AUTRES_EDITION));
echo $this->inlinescript()->appendFile($this->basePath() . '/ext/ace-builds-master/src-min/ace.js');


?>
<h1 class="page-header">Gestion des champs personnalisés pour les données personnelles</h1>

<table class="table table-bordered table-sm table-hover">
    <thead>
    <tr>
        <th>Champ N°</th>
        <th>Libellé</th>
        <th>Obligatoire</th>
        <th>Type</th>
        <th>description</th>
        <?php if ($canEdit): ?>
            <th>Actions</th>
        <?php endif; ?>
    </tr>
    </thead>
    <tbody class="triables">
    <?php foreach ($dossierAutreListe as $autre): ?>
        <tr class="champ-triable" data-id="<?= $autre->getId() ?>">
            <td><?= $autre->getId() ?></td>
            <td><?= $autre->getLibelle() ?></td>
            <td><?= ($autre->isObligatoire()) ? 'OUI' : 'NON'; ?></td>
            <td><?= $autre->getType()->getLibelle() ?></td>
            <td><?= $autre->getDescription() ?></td>
            <?php if ($canEdit): ?>
                <td style="text-align:center;width:1px;white-space: nowrap">
                    <a
                            href="<?= $this->url('autres-infos/saisie', ['dossierAutre' => $autre->getId()]) ?>"
                    <i class="fas fa-pen-to-square"></i></a>
                </td>
            <?php endif; ?>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<style>
    .triables {
        align: left;
    }

    .champ-triable tr {
        align: left;
    }

    .tbl-tis {
        margin-bottom: 1px;
    }
</style>