<?php
/**
 * @var $this      \Application\View\Renderer\PhpRenderer
 * @var $form      \Application\Form\FonctionReferentiel\FonctionReferentielSaisieForm
 * @var $tab       string
 */

/** @var \Application\Entity\Db\FonctionReferentiel $fonction */
$fonction = $form->getObject();

$visu = $this->messenger()->addCurrentMessagesFromFlashMessenger() . $this->form($form);

$tabs = [
    [
        'id'      => 'fiche',
        'label'   => 'Fiche',
        'content' => $visu,
    ],
];

$id = $fonction->getId();

$canEdit = $this->isAllowed($fonction, \Application\Provider\Privilege\Privileges::PLAFONDS_CONFIG_REFERENTIEL);
$canEdit = true;

if ($id && $canEdit) {

    $tabs[] = [
        'id'    => 'plafonds',
        'label' => '<span class="fa-solid fa-signal"></span> Plafonds',
        'url'   => $this->url('plafond/referentiel', ['fonctionReferentiel' => $id]),
    ];

    echo $this->tabajax($tabs, $tab);
} else {
    echo $visu;
}


