<?php 
use Application\Entity\Db\Indicateur;
use Application\Entity\Db\NotificationIndicateur;
use Application\Service\Indicateur\AbstractIndicateurImpl;
?>

<table class="table table-bordered table-condensed">
    <thead>
        <tr>
            <th class="categorie">Catégorie</th>
            <th class="intitule">Intitulé de l'indicateur</th>
            <?php if ($this->showAbonnement): ?>
            <th class="notification">Notification par mail</th>
            <?php endif ?>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->indicateursImpl as $indicateurImpl): /* @var $indicateurs AbstractIndicateurImpl[] */ ?>
            <?php 
            $indicateurEntity = $indicateurImpl->getEntity();  /* @var $indicateurEntity Indicateur */
            ?>
            <tr>
                <td class="categorie">
                    <?php echo $indicateurEntity->getType() ?>
                </td>
                
                <td class="intitule">
                    <?php if ($indicateurImpl->getResultCount()): ?>
                        <a href="<?php echo $this->url('indicateur/result', ['indicateur' => $indicateurEntity->getId()]) ?>"
                           title="Cliquez pour vous rendre à la page concernée"><?php echo $indicateurImpl ?></a>
                    <?php else: ?>
                        <?php echo $indicateurImpl ?>
                    <?php endif ?>
                    
                    <!-- Détails concernant l'indicateur -->
                    <small class="pull-right">
                        <?php echo $this->toggleDetails($detailsDivId = uniqid("details-"), "Afficher/masquer la description") ?>
                    </small>
                    <p style="display: none" id="<?php echo $detailsDivId ?>" class="small">
                        Aucune description disponible.
                    </p>
                </td>
                
                <?php if ($this->showAbonnement): ?>
                <td class="notification">
                    <?php 
                    $abonnement = array_key_exists($key = $indicateurEntity->getId(), $this->abonnements) ?
                        $this->abonnements[$key] :
                        null; /* @var $abonnement \Application\Entity\Db\NotificationIndicateur */
                    $frequence  = $abonnement ? "".$abonnement->getFrequence() : "";
                    $isSelected = function($code) use ($frequence) { return $frequence === "".$code ? 'selected' : null; };
                    $dernNotif  = $abonnement ? $abonnement->getDateDernNotif() : null;
                    ?>
                    <select class="abonnement" name="abonnement" data-id="<?php echo $indicateurEntity->getId() ?>">
                        <option value=""                                                             <?php echo $isSelected("") ?>  >Aucune</option>
                        <option value="<?php echo $val = NotificationIndicateur::PERIODE_HEURE_3 ?>" <?php echo $isSelected($val) ?>>4 par jour</option>
                        <option value="<?php echo $val = NotificationIndicateur::PERIODE_HEURE_6 ?>" <?php echo $isSelected($val) ?>>2 par jour</option>
                        <option value="<?php echo $val = NotificationIndicateur::PERIODE_JOUR ?>"    <?php echo $isSelected($val) ?>>1 par jour</option>
                        <option value="<?php echo $val = NotificationIndicateur::PERIODE_SEMAINE ?>" <?php echo $isSelected($val) ?>>1 par semaine</option>
                    </select>
                    <?php
                    $infos = null;
                    $displayInfos = 'display: none';
                    if (array_key_exists($key = $indicateurEntity->getId(), $this->abonnementsInfos)) {
                        $infos = $this->abonnementsInfos[$key];
                        $displayInfos = null;
                    }
                    ?>
                    <span class="indicateur-info glyphicon glyphicon-info-sign" aria-hidden="true"
                          data-toggle="tooltip" data-placement="right" data-html="true" 
                          title="<?php echo $infos ?>"
                          style="<?php echo $displayInfos ?>"></span>
                </td>
                <?php endif ?>
                
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>


<?php if ($this->showAbonnement): ?>
<script>
    var abonnementUrl = '<?php echo $this->abonnementUrl ?>';
    $(function() {
        $("select.abonnement")
                .each(function() {
                    $(this).data('previousValue', $(this).val());
                }) 
                .change(function() {
                    var select = $(this);
                    var url = abonnementUrl.replace('_indicateur_', select.data('id'));
                    select.addClass("loading");
                    $.post(url, select.serialize(), function(data, textStatus, jqXHR) {
                        if (data.status !== "success") {
                            select.val(select.data('previousValue'));
                        }
                        select.removeClass("loading");
                        var infos = $(".indicateur-info", select.parent()).attr('title', data.infos).tooltip('destroy').tooltip();
                        data.infos ? infos.show() : infos.hide();
                        alertFlash(data.message, data.status, 5000);
                    });
                });
        $(".glyphicon.glyphicon-info-sign").tooltip();
    });
</script>
<?php endif ?>