<?php

use Application\Provider\Privilege\Privileges;

/* @var $structure \Application\Entity\Db\Structure */
/* @var $niveau \Application\Entity\NiveauEtape */
/* @var $etape \Application\Entity\Db\Etape */

/* @var $structures \Application\Entity\Db\Structure[] */
/* @var $niveaux \Application\Entity\NiveauEtape[] */
/* @var $etapes \Application\Entity\Db\Etape[] */
/* @var $elements \Application\Entity\Db\ElementPedagogique[] */


/**
 * @param \Application\Entity\Db\Structure $structure
 * @param \Application\Entity\NiveauEtape  $niveau
 * @param \Application\Entity\Db\Etape     $etape
 */
function makeQuery($structure = null, $niveau = null, $etape = null)
{
    $params = [];
    //@formatter:off
    if ($structure) $params['structure']    = $structure->getId();
    if ($niveau)    $params['niveau']       = $niveau->getId();
    if ($etape)     $params['etape']        = $etape->getId();
    //@formatter:on

    return ['query' => $params];
}


/* Liste des niveaux */
$niveauxItems = [
    null => [
        'label'  => 'Tous niveaux confondus',
        'niveau' => null,
        'url'    => $this->url('of', [], makeQuery($structure)),
    ],
];

foreach ($niveaux as $niv) {
    $niveauxItems[$niv->getId()] = [
        'label'  => (string)$niv,
        'niveau' => $niv,
        'url'    => $this->url('of', [], makeQuery($structure, $niv)),
    ];
}


/* Liste des étapes */
$etapesItems = [
    null => [
        'label'     => 'Toutes formations confondues',
        'etape'     => null,
        'orpheline' => false,
        'url'       => $this->url('of', [], makeQuery($structure, $niveau)),
    ],
];

foreach ($etapes as $etp) {
    $etapesItems[$etp->getId()] = [
        'label'     => sprintf("%s (%s EP)", $etp, count($etp->getElementPedagogique())),
        'etape'     => $etp,
        'orpheline' => $etp->getElementPedagogique()->count() === 0,
        'url'       => $this->url('of', [], makeQuery($structure, $niveau, $etp)),
    ];
}


/* Liste des éléments */

if ($structure){
    $this->headTitle()->append((string)$structure);
}
$this->headTitle()->append("Offre de formation");

/* Lien d'export de l'OF au format CSV */
$this->placeholder('export-of-link')->captureStart();

$canExport = $this->isAllowed(Privileges::getResourceId(Privileges::ODF_EXPORT_CSV));
$canViewEtape = $this->isAllowed(Privileges::getResourceId(Privileges::ODF_ETAPE_VISUALISATION));

if ($canExport && count($elements)) {
    $params      = [
        'structure' => $structure ? $structure->getId() : null,
        'niveau'    => $niveau ? $niveau->getId() : null,
        'etape'     => $etape ? $etape->getId() : null,
    ];
    $urlExportOf = $this->url('of/default', ['action' => 'export'], ['query' => $params]);

    ?>
    <div>
        <a class="pull-right" href="<?php echo $urlExportOf ?>">
            <span class="glyphicon glyphicon-export"></span> Télécharger l'offre de formation au format CSV
        </a>
    </div>
    <?php
}
$this->placeholder('export-of-link')->captureEnd();


?>
<style>
    ul.navigation-etape {
        padding: 0 0 3px 5px;
    }

    ul.navigation-etape li {
        list-style: none;
        display: inline;
    }

    /*th.action, td.action { min-width: 70px; }*/
    div.element-rech div.panel-body label,
    div.element-rech div.panel-body input {
        display: inline;
    }

    div.element-rech div.panel-body input.form-control {
        width: 75%
    }
</style>

<?php ?>

<h1 class="page-header">Offre de formation <?php echo $structure ? '<small>' . $structure . '</small>' : null ?></h1>

<div class="row">

    <div class="col-md-3">

        <!---------------- Champ de sélection d'une structure --------------->
        <div class="panel panel-default">
            <div class="panel-heading">Structure</div>
            <div class="panel-body">
                <?php
                $selectStructure = new \Zend\Form\Element\Select('structure');
                $selectStructure
                    ->setValueOptions(['' => "(Sélectionnez...)"] + \UnicaenApp\Util::collectionAsOptions($structures))
                    ->setValue($structure ? $structure->getId() : null)
                    ->setAttributes(['class' => 'struct']);
                echo $this->formSelect($selectStructure);
                ?>
                <script>
                    $("body").on("change", "select.struct", function (event)
                    {
                        $("*").css('cursor', 'wait');
                        var id = $(this).val();
                        var url = '<?php echo $this->url('of', [], ['query' => ['structure' => '__structure__']]) ?>';
                        $(location).attr('href', url.replace('__structure__', id));
                    });
                </script>
            </div>
        </div>

        <!---------------- Filtre niveau --------------->
        <div class="panel panel-default">
            <div class="panel-heading">Niveau</div>
            <div class="panel-body">
                Cliquez sur le niveau dont vous voulez voir les formations et enseignements...
            </div>
            <?php if (count($niveaux)): ?>
                <ul class="list-group">
                    <?php foreach ($niveauxItems as $ni): ?>
                        <?php if (($niveau === $ni['niveau']) || ($niveau && $ni['niveau'] && $niveau->getId() === $ni['niveau']->getId())): ?>
                            <li class="list-group-item active"><strong><?php echo $ni['label'] ?></strong></li>
                        <?php else: ?>
                            <li class="list-group-item">
                                <a class="niveau"
                                   title="Cliquez pour afficher les formations et les enseignements de ce niveau"
                                   href="<?php echo $ni['url'] ?>"><?php echo $ni['label'] ?></a>
                            </li>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </ul>
            <?php endif; ?>
            <script>
                $("body").on("click", "a.niveau", function (event)
                {
                    $("*").css('cursor', 'wait');
                });
            </script>
        </div>

        <!---------------- Filtre étape --------------->
        <div class="panel panel-default">
            <div class="panel-heading">
                Formation
                <?php if ($this->isAllowed($structure,Privileges::ODF_ETAPE_EDITION)) echo $this->etape($etape)->renderAjouterLink('<span class="glyphicon glyphicon-plus"></span>', ['class' => 'btn-xs', 'style' => 'float:right']) ?>
            </div>
            <div class="panel-body">
                Cliquez sur la formation dont vous voulez voir les enseignements...
            </div>
            <?php if (count($etapes)): ?>
                <ul class="list-group">
                    <?php foreach ($etapesItems as $ei): ?>
                        <?php if ($etape === $ei['etape']): ?>
                            <li class="list-group-item active">
                                <strong><?php echo $ei['label'] ?></strong>
                        <?php else: ?>
                            <li class="list-group-item">
                                <a class="etape<?php if ($ei['orpheline']) echo ' text-danger'; ?>"
                                   title="Cliquez pour afficher les enseignements de cette formation"
                                   href="<?php echo $ei['url'] ?>"><?php echo $ei['label'] ?></a>
                        <?php endif; ?>
                        <?php
                        if ($canViewEtape && $ei['etape'])
                            echo $this->etape($ei['etape'])->renderLink('<span class="btn btn-default btn-xs glyphicon glyphicon-search" style="float:right"></span>');
                        ?>
                        <div style="clear: both"></div>
                        </li>
                    <?php endforeach; ?>
                </ul>
            <?php endif; ?>
            <script>
                $("body").on("click", "a.etape", function (event)
                {
                    $("*").css('cursor', 'wait');
                });
            </script>
        </div>

    </div>

    <div class="col-md-9" role="main">

        <?php if (null === $elements): ?>

            <p><?php echo $this->messenger()->setMessage("Sélectionnez une structure...", 'info') ?></p>

        <?php else: ?>

            <!---------------- Champ de recherche d'un élément pédagogique --------------->
            <div class="element-rech panel panel-default">
                <div class="panel-heading">
                    <?php $compl = $etape ? "de la formation <strong>$etape</strong>" : "toutes formations confondues"; ?>
                    Enseignements <?php echo $compl ?>
                    <!--------------- Bouton d'ajout d'élément pédagogique --------------->
                    <?php if ($this->isAllowed($structure,Privileges::ODF_ELEMENT_EDITION)) echo $this->elementPedagogique()->renderAjouterLink(
                            '<span class="glyphicon glyphicon-plus"></span>',
                            ['class' => 'btn-xs', 'style' => 'float:right']); ?>

                </div>
                <div class="panel-body">
                    <?php if (count($elements)): ?>
                        <p>
                            <?php echo $this->form()->openTag($form) ?>
                            <label class="control-label"><?php echo $form->get('element')->getLabel() ?></label>
                            <?php echo $this->formSearchAndSelect($form->get('element')); ?>
                            <input id="filter" class="btn btn-primary element-rech-submit" type="submit" value="Y aller..."
                                   name="submit"/>
                            <?php echo $this->form()->closeTag() ?>
                        </p>
                        <script>
                            $("body").on("submit", "form.element-rech", function (event)
                            {
                                var form = $(event.target);
                                var id = $("input.sas", form).val();
                                if (id && $("#" + id).offset()) {
                                    $('html, body').animate({
                                        scrollTop: $("#" + id).offset().top - $(window).height() / 2
                                    }, 500, 'swing', function () { $("#" + id).effect("highlight"); });
                                }
                                event.preventDefault();
                            });
                        </script>
                    <?php endif; ?>

                    <p><?php echo count($elements) ?> enseignement(s) trouvé(s).</p>

                    <?php echo $this->placeholder('export-of-link') ?>
                </div>

                <!---------------- Tableau des éléments pédagogiques --------------->
                <table class="table table-bordered table-condensed table-hover">
                    <thead>
                    <tr>
                        <th colspan="2">Formation</th>
                        <th colspan="5">Enseignement</th>
                    </tr>
                    <tr>
                        <th>Niveau</th>
                        <th>Libellé</th>
                        <th>Code</th>
                        <th>Libellé</th>
                        <th>Période</th>
                        <th title="Formation ouverte à distance">FOAD</th>
                        <th title="Régime d'inscription">Rég. d'insc.</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($elements as $ep): /* @var $ep \Application\Entity\Db\ElementPedagogique */ ?>
                        <tr id="<?php echo $ep->getId() ?>">
                            <td><?php echo $ep->getEtape()->getNiveauToString() ?></td>
                            <td class="etape"><?php echo $this->etape($ep->getEtape())->renderLink() ?></td>
                            <td class="element"><?php echo $ep->getCode() ?></td>
                            <td class="element"><?php echo $this->elementPedagogique($ep)->renderLink($ep->getLibelle()) ?></td>
                            <td class="periode"><?php echo $ep->getPeriode() ?: "" ?></td>
                            <td><?php echo (bool)$ep->getTauxFoad() ? "Oui" : "Non" ?></td>
                            <td><?php echo $ep->getRegimesInscription(true) ?></td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>

            </div>

            <?php echo $this->placeholder('export-of-link') ?>

        <?php endif; ?>

    </div>

</div>
