<div class="row" id="reconduction-filters">
    <div class="col-md-12">
        <!---------------- Champ de sélection d'une structure --------------->
        <div class="panel panel-default">
            <div class="panel-heading">Composante</div>
            <div class="panel-body">
                <?php
                $selectStructure = new \Zend\Form\Element\Select('structure');
                $selectStructure
                    ->setValueOptions(['' => "(Sélectionnez une composante)"] + \UnicaenApp\Util::collectionAsOptions($structures))
                    ->setValue($structure ? $structure->getId() : null)
                    ->setAttributes(['class' => 'structure',
                                     'style' => 'width:250px;']);
                echo $this->formSelect($selectStructure);
                ?>

            </div>
        </div>
    </div>

</div>
<div class="row" style="margin:0 5px 0 5px;">
    <div class="col-11">
        <?php
        if($reconductionStep)
        {
            echo "<p class=\"bg-success\" style=\"padding:10px;\">La reconduction de l'offre de formation pour la prochaine année universitaire s'est correctement déroulée.</p>";
        }
        elseif($reconductionStep === false){
            echo "<p class=\"bg-danger\" style=\"padding:10px;\">La reconductiond de l'offre de formation a échoué : <br/><br/>" .  $messageStep . "</p>";
        }
        ?>


        <h3>Offre de formation complémantaire / Année universitaire :  <?php echo $anneeEnCours->getLibelle(); ?></h3>
        <br/>
        <form action="<?php echo $_SERVER['REQUEST_URI']; ?>" method="POST" id="form-reconduction">

            <?php foreach ($offresComplementaires as $ec): ?>
                <table class="reconduction-offre table table-bordered table-condensed table-hover">
                    <thead>
                        <tr>
                            <th><input type="checkbox" class="checkbox-formation" checked="checked" name="etape[]" value="<?= $ec['etape']->getId(); ?>"/></th>
                            <th colspan="6">Formation : <?= $ec['etape']->__toString() . ' (' . $ec['etape']->getAnnee()->getLibelle() . ')'; ?></th>
                        </tr>
                        <tr>
                            <th colspan="2">Code</th>
                            <th>Libellé</th>
                            <th>Période</th>
                            <th title="Formation ouverte à distance">FOAD</th>
                            <th title="Régime d'inscription">Rég. d'insc.</th>
                        </tr>
                    </thead>
                    <tbody>
                    <?php
                    if(empty($ec['elements_pedagogique']))
                    {
                    ?>
                    <tr>
                        <td colspan="7" style="text-align: center;">Aucun élément pédagogique</td>
                    </tr>
                    <?php } ?>

                        <?php foreach ($ec['elements_pedagogique'] as $ep): ?>
                            <tr id="<?= $ep->getId() ?>">
                                <td><input class="checkbox-element" type="checkbox" checked="checked" name="element[<?php echo $ec['etape']->getId();?>][]" value="<?= $ep->getId(); ?>"/></td>
                                <td class="element"><?= $ep->getCode() ?></td>
                                <td class="element"><?= $this->elementPedagogique($ep)->renderLink($ep->getLibelle()) ?></td>
                                <td class="periode"><?= $ep->getPeriode() ?: "" ?></td>
                                <td><?= (bool)$ep->getTauxFoad() ? "Oui" : "Non" ?></td>
                                <td><?= $ep->getRegimesInscription(true) ?></td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            <?php endforeach; ?>
            <input id="reconduction-button" class="btn btn-primary" type="button" value="Reconduire l'offre séléctionnée"/>
        </form>

    </div>
</div>
<div id="modal-dialog" class="modal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <a href="#" data-dismiss="modal" aria-hidden="true" class="close">×</a>
                <h3>Demande de confirmation</h3>
            </div>
            <div class="modal-body">
                <p>Êtes vous sûre de vouloir reconduire ces offres de formation pour la prochaine année universitaire ?</p>
            </div>
            <div class="modal-footer">
                <a href="#" id="btnYes" class="btn confirm">OUI</a>
                <a href="#" data-dismiss="modal" aria-hidden="true" class="btn secondary">NON</a>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">

</script>

