<div class="row" id="reconduction-filters">
    <div class="col-md-4">
        <!---------------- Champ de sélection d'une structure --------------->
        <div class="panel panel-default">
            <div class="panel-heading">Structure</div>
            <div class="panel-body">
                <?php
                $selectStructure = new \Zend\Form\Element\Select('structure');
                $selectStructure
                    ->setValueOptions(['' => "(Sélectionnez une structure)"] + \UnicaenApp\Util::collectionAsOptions($structures))
                    ->setValue($structure ? $structure->getId() : null)
                    ->setAttributes(['class' => 'structure',
                                     'style' => 'width:250px;']);
                echo $this->formSelect($selectStructure);
                ?>

            </div>
        </div>
    </div>
    <div class="col-md-4">
        <!---------------- Champ de sélection niveau --------------->
        <div class="panel panel-default">
            <div class="panel-heading">Niveau</div>
            <div class="panel-body">
                <?php
                $selectNiveau = new \Zend\Form\Element\Select('niveau');
                $selectNiveau
                    ->setValueOptions(['' => "(Sélectionnez un niveau)"] + \UnicaenApp\Util::collectionAsOptions($niveaux))
                    ->setValue($niveau ? $niveau->getId() : null)
                    ->setAttributes(['class' => 'niveau',
                                     'style' => 'width:250px;']);
                echo $this->formSelect($selectNiveau);
                ?>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <!---------------- Champ de sélection formation --------------->
        <div class="panel panel-default">
            <div class="panel-heading">Formation</div>
            <div class="panel-body">
                <?php
                $selectEtapes = new \Zend\Form\Element\Select('etape');
                $selectEtapes
                    ->setValueOptions(['' => "(Sélectionnez une formation)"] + \UnicaenApp\Util::collectionAsOptions($etapes))
                    ->setValue($etape ? $etape->getId() : null)
                    ->setAttributes(['class' => 'etape',
                                    'style' => 'width:250px;']);
                echo $this->formSelect($selectEtapes);
                ?>
            </div>
        </div>
    </div>
</div>
<div class="row" style="margin:0 5px 0 5px;">
    <div class="col-11">
        <!---------------- Tableau des éléments pédagogiques --------------->
        <table class="table table-bordered table-condensed table-hover table-sort">
            <thead>
            <tr>
                <th colspan="3">Formation</th>
                <th colspan="5">Enseignement</th>
            </tr>
            <tr>
                <th><input type="checkbox"/></th>
                <th>Niveau</th>
                <th>Libellé</th>
                <th>Code</th>
                <th>Libellé</th>
                <th>Période</th>
                <th title="Formation ouverte à distance">FOAD</th>
                <th title="Régime d'inscription">Rég. d'insc.</th>
            </tr>
            </thead>
            <?php foreach ($elements as $ep): /* @var $ep \Application\Entity\Db\ElementPedagogique */ ?>
                <tr id="<?= $ep->getId() ?>">
                    <td><input type="checkbox"/></td>
                    <td><?= $ep->getEtape()->getNiveauToString() ?></td>
                    <td class="etape"><?= $this->etape($ep->getEtape())->renderLink() ?></td>
                    <td class="element"><?= $ep->getCode() ?></td>
                    <td class="element"><?= $this->elementPedagogique($ep)->renderLink($ep->getLibelle()) ?></td>
                    <td class="periode"><?= $ep->getPeriode() ?: "" ?></td>
                    <td><?= (bool)$ep->getTauxFoad() ? "Oui" : "Non" ?></td>
                    <td><?= $ep->getRegimesInscription(true) ?></td>
                </tr>
            <?php endforeach; ?>
            <tbody>
            </tbody>
        </table>

        <?php foreach ($etapesComplementaires as $ec): ?>
            <table class="table table-bordered table-condensed table-hover table-sort">
                <thead>
                <tr>
                    <th colspan="3">Formation : <?= $ec['etape']->__toString();?></th>
                    <th colspan="5">Enseignement</th>
                </tr>
                <tr>
                    <th><input type="checkbox"/></th>
                    <th>Niveau</th>
                    <th>Libellé</th>
                    <th>Code</th>
                    <th>Libellé</th>
                    <th>Période</th>
                    <th title="Formation ouverte à distance">FOAD</th>
                    <th title="Régime d'inscription">Rég. d'insc.</th>
                </tr>
                </thead>
            </table>

        <?php endforeach; ?>
    </div>
</div>

<script>
    $("document").ready(function()
    {
        $("body").on("change", "#reconduction-filters select", function(event)
        {
            $("*").css('cursor', 'wait');
            var structure = $('select.structure').val();
            var niveau = $('select.niveau').val();
            var etape = $('select.etape').val();
            var query = '';
            if(structure){ query += 'structure='+structure+'&';}
            if(niveau){ query += 'niveau='+niveau+'&';}
            if(etape){query += 'etape='+etape+'&';}
            var url = '<?= $this->url('of/reconduction'); ?>';
            url += '?' + query;
            $(location).attr('href', url);
        });
       
    });

</script>

