<?php
$this->headScript()->offsetSetFile(100, $this->basePath('/js/reconduction-modulateur.js'));
?>

<div class="row" id="reconduction-filters">
    <div class="col-md-12">
        <!---------------- Champ de sélection d'une structure --------------->
        <div class="panel panel-default">
            <div class="panel-heading">Veuillez sélectionner une composante :</div>
            <div class="panel-body">
                <?php
                $selectStructure = new \Laminas\Form\Element\Select('structure');
                $selectStructure
                    ->setValueOptions(['' => "(Sélectionnez une composante)"] + \UnicaenApp\Util::collectionAsOptions($structures))
                    ->setValue($structure ? $structure->getId() : null)
                    ->setAttributes(['class' => 'structure',
                                     'style' => 'width:250px;']);
                echo $this->formSelect($selectStructure);
                ?>

            </div>
        </div>
    </div>

</div>
<div class="alert alert-warning" role="alert">
    <strong>IMPORTANT</strong><br/>
    Seules les formations reconduites pour la prochaine année universitaire peuvent bénéficier de la reconduction des
    modulateurs d'une année sur l'autre.
    Si la formation n'est pas disponible dans la liste ci-dessous, veuillez vérifier qu'elle a bien été reconduit pour la
    prochaine année universitaire.
</div>

<h3>Veuillez sélectionner les formations pour reconduire les modulateurs :</h3>
<?php
echo $this->messenger()->addCurrentMessagesFromFlashMessenger();
?>
<?php if (empty($etapesReconduites)): ?>
    <table class="reconduction-centre-cout table table-bordered table-condensed table-hover">
        <thead>
        <tr>
            <th colspan="2">Code</th>
            <th>Libellé</th>
            <th>Période</th>
            <th title="Formation ouverte à distance">FOAD</th>
            <th title="Régime d'inscription">Rég. d'insc.</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td colspan="6" style="text-align: center;">
                Aucun modulateur à reconduire
            </td>
        </tr>
        </tbody>
    </table>
<?php else: ?>
    <form action="<?= $this->url('aof/reconduction-modulateur', [], ['query' => ['structure' => $structure->getId()]]) ?>"
          method="POST" id="form-reconduction">

        <table class="reconduction-offre table table-bordered table-condensed table-hover table-sort">
            <thead>
            <tr>
                <th><input class="checkbox-element" type="checkbox" value="" id="check-all"></th>
                <th>Code</th>
                <th>Libellé</th>
                <th>Nombre de <abbr
                            title="Le comptage se fait uniquement sur les éléments pédagogiques n'ayant pas encore de modulateur pour l'année prochaine">modulateur(s)
                        à reconduire</abbr></th>

            </tr>

            </thead>
            <tbody>
            <?php foreach ($etapesReconduites as $er): ?>
                <tr>
                    <td>
                        <input class="checkbox-element" type="checkbox" name="etapes[]" value="<?= $er['ETAPE_CODE']; ?>">
                    </td>
                    <td><?= $er['ETAPE_CODE']; ?></td>
                    <td><?= $er['ETAPE_LIBELLE']; ?></td>
                    <td><?= $er['NB_MODULATEUR']; ?> </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
        <button disabled="disabled" id="reconduction-modulateur-button" class="btn btn-primary pop-ajax" type="button"
                data-content="Voulez-vous réellement reconduire ces centres de coût pour l'année prochaine ?
                <div class='alert alert-warning'>
                <button type='button' class='close' data-dismiss='alert' aria-label='Close'><span aria-hidden='true'>&times;</span></button>
                    Les modulateurs seront reconduits dans leurs globalités pour la prochaine année universitaire sur les formations séléctionnées. Si des modulateurs ont été renseignés manuellement pour l'année prochaine, ils seront écrasés par ceux de cette année.
                </div>
                <div style='text-align:right'>
                <button type='button' class='btn btn-default pop-ajax-hide'>Non</button>
                <button type='button' class='btn btn-primary' id='confirm-reconduction'>Oui</button></div>"><span
                    class="fa-solid fa-share"></span> Reconduire les modulateurs pour l'année suivante
        </button>
    </form>
<?php endif; ?>
