<?php
/**
 * @var $this \Application\View\Renderer\PhpRenderer
 *
 */

$this->headScript()->offsetSetFile(100, $this->basePath('/js/reconduction-offre.js'));
?>


<div class="row" id="reconduction-filters">
    <div class="col-md-12">
        <!---------------- Champ de sélection d'une structure --------------->
        <div class="panel panel-default">
            <div class="panel-heading">Veuillez sélectionner une composante :</div>
            <div class="panel-body">
                <?php
                $selectStructure = new \Laminas\Form\Element\Select('structure');
                $selectStructure
                    ->setValueOptions(['' => "(Sélectionnez une composante)"] + \UnicaenApp\Util::collectionAsOptions($structures))
                    ->setValue($structure ? $structure->getId() : null)
                    ->setAttributes(['class' => 'structure',
                                     'style' => 'width:250px;']);
                echo $this->formSelect($selectStructure);
                ?>

            </div>
        </div>
    </div>

</div>
<div class="row" style="margin:0 5px 0 5px;">
    <div class="col-11">


        <div class="alert alert-warning" role="alert">
            <strong>IMPORTANT</strong><br/>
            Vous pouvez ici reconduire les formations et éléments pédagogiques de l'année en cours pour l'année
            universitaire prochaine. Les lignes avec fond gris sont déjà reconduites pour l'année prochaine.
        </div>

        <h3>Offre de formation complémentaire / Année universitaire : <?php echo $anneeEnCours->getLibelle(); ?></h3>
        <br/>
        <?php
        echo $this->messenger()->addCurrentMessagesFromFlashMessenger();
        ?>

        <?php if (empty($offresComplementaires)): ?>
            <table class="reconduction-offre table table-bordered table-condensed table-hover">
                <thead>
                <tr>
                    <th colspan="2">Code</th>
                    <th>Libellé</th>
                    <th>Période</th>
                    <th title="Formation ouverte à distance">FOAD</th>
                    <th title="Régime d'inscription">Rég. d'insc.</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td colspan="6" style="text-align: center;">
                        Il n'y a pas d'offre complémentaire pour cette composante.
                    </td>
                </tr>
                </tbody>
            </table>
        <?php else: ?>
            <?php if ($fromPost): ?>
                <p><a href="<?= $this->url('aof/reconduction', [], ['query' => ['structure' => $structure->getId()]]) ?>"><
                        Retour à la liste
                        des formations.</a></p>
            <?php else: ?>
                <?php if ($reconductionTotale == 'non'): ?>
                    <div class="well well-sm">Les lignes avec le fond gris ont déjà été reconduites pour la prochaine année
                        universitaire.
                    </div>
                    <form action="<?= $this->url('aof/reconduction', [], ['query' => ['structure' => $structure->getId()]]) ?>"
                          method="POST" id="form-reconduction">

                        <?php foreach ($offresComplementaires

                        as $ec): ?>
                        <?php if ($ec['reconduction_partiel'] == 'oui'): ?>
                        <table class="reconduction-offre table table-bordered table-condensed table-hover">
                            <?php else: ?>
                            <table class="reconduction-offre table table-bordered table-condensed table-hover"
                                   style="display: none;">
                                <?php endif; ?>
                                <thead>
                                <tr class="<?php if ($ec['reconduction'] == 'oui') {
                                    echo "active";
                                } else {
                                    echo "info";
                                } ?>">
                                    <?php if ($ec['reconduction'] == 'oui'): ?>
                                        <th><input title="Formation déjà reconduite pour l'année prochaine" type="checkbox"
                                                   class="checkbox-formation" disabled="disabled" name="etape[]"
                                                   value="<?= $ec['etape']->getId(); ?>"/> <span class="label label-warning"
                                                                                                 style="margin:0 auto;">Reconduit</span>
                                        </th>
                                    <?php else: ?>
                                        <th><input type="checkbox" class="checkbox-formation" checked="checked" name="etape[]"
                                                   value="<?= $ec['etape']->getId(); ?>"/></th>
                                    <?php endif; ?>
                                    <th colspan="6">Formation
                                        : <?= $ec['etape'] . ' (' . $ec['etape']->getAnnee() . ')'; ?></th>
                                </tr>
                                <tr>
                                    <th colspan="2">Code</th>
                                    <th>Libellé</th>
                                    <th>Période</th>
                                    <th title="Formation ouverte à distance">FOAD</th>
                                    <th title="Régime d'inscription">Rég. d'insc.</th>
                                </tr>
                                </thead>
                                <tbody>
                                <?php
                                if (empty($ec['elements_pedagogique'])) {
                                    ?>
                                    <tr>
                                        <td colspan="7" style="text-align: center;">Aucun élément pédagogique</td>
                                    </tr>
                                <?php } ?>

                                <?php foreach ($ec['elements_pedagogique'] as $ep): ?>
                                    <tr id="<?= $ep['element']->getId() ?>" class="<?php if ($ep['reconduction'] == 'oui') {
                                        echo "active";
                                    } ?>">
                                        <?php if ($ep['reconduction'] == 'oui'): ?>
                                            <td>
                                                <input title="Elément pédagogique déjà reconduit pour l'année prochaine"
                                                       class="checkbox-element" disabled="disabled" type="checkbox"
                                                       name="element[<?php echo $ec['etape']->getId(); ?>][]"
                                                       value="<?= $ep['element']->getId(); ?>"/>
                                                <span class="label label-warning">Reconduit</span>
                                            </td>
                                        <?php else: ?>
                                            <td><input class="checkbox-element" type="checkbox" checked="checked"
                                                       name="element[<?php echo $ec['etape']->getId(); ?>][]"
                                                       value="<?= $ep['element']->getId(); ?>"/></td>
                                        <?php endif; ?>
                                        <td class="element"><?= $ep['element']->getCode() ?></td>
                                        <td class="element"><?= $this->elementPedagogique($ep['element'])->renderLink($ep['element']->getLibelle()) ?></td>
                                        <td class="periode"><?= $ep['element']->getPeriode() ?: "" ?></td>
                                        <td><?= (bool)$ep['element']->getTauxFoad() ? "Oui" : "Non" ?></td>
                                        <td><?= $ep['element']->getRegimesInscription(true) ?></td>
                                    </tr>
                                <?php endforeach; ?>
                                </tbody>
                            </table>
                            <?php endforeach; ?>
                            <button id="reconduction-button" class="btn btn-primary pop-ajax" type="button" data-content="Voulez-vous réellement reconduire ces offres pour l'année prochaine ?
                <div class='alert alert-warning'>
                <button type='button' class='close' data-dismiss='alert' aria-label='Close'><span aria-hidden='true'>&times;</span></button>
                    Les formations ainsi que les éléments pédagogiques sélectionnés seront reconduits pour l'année universitaire prochaine.
                </div>
                <div style='text-align:right'>
                <button type='button' class='btn btn-default pop-ajax-hide'>Non</button>
                <button type='button' class='btn btn-primary' id='confirm-reconduction'>Oui</button></div>"><span
                                        class="fas fa-share"></span> Reconduire l'offre pour l'année suivante
                            </button>
                    </form>
                <?php else: ?>
                    <table class="reconduction-offre table table-bordered table-condensed table-hover">
                        <thead>
                        <tr>
                            <th colspan="2">Code</th>
                            <th>Libellé</th>
                            <th>Période</th>
                            <th title="Formation ouverte à distance">FOAD</th>
                            <th title="Régime d'inscription">Rég. d'insc.</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td colspan="6" style="text-align: center;">
                                Toute l'offre complémentaire de cette composante a été reconduit.
                            </td>
                        </tr>
                        </tbody>
                    </table>            <?php endif; ?>
            <?php endif; ?>
        <?php endif; ?>


    </div>
</div>
