<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h3 class="modal-title">Détails d'un élément pédagogique</h3>
</div>
<div class="modal-body">
    <?php echo $this->elementPedagogiqueDl($element, true); ?>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Fermer</button>
</div>