<div class="jumbotron">
    <h1>Pages de démo</h1>
    <h2>Organisation des Services d'Enseignement</h2>
</div>

<ul>
    <!--<li><a href="<?php echo $this->url('demo', array('action' => 'intervenant')) ?>">Intervenants</a></li>-->
    <li>
        Offre de formation : 
        <a href="<?php echo $this->url('demo', array('action' => 'of'), array('query' => array('avecUe' => 1))) ?>">avec UE</a> / 
        <a href="<?php echo $this->url('demo', array('action' => 'of')) ?>">sans UE</a>
    </li>
</ul>