<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title">Détails d'un élément</h4>
</div>
<div class="modal-body">
    <dl class="dl-horizontal">
        <dt>Structure</dt>
        <dd><?php echo $element->getCodStr() . ' - ' . $element->getLibStr() ?></dd>
        <dt>Niveau</dt>
        <dd><?php echo $element->getLibNivVet() ?></dd>
        <dt>VET</dt>
        <dd><?php echo $element->getLibWebVet() ?></dd>
        <dt>Période</dt>
        <dd><?php echo $element->getCodPel() ?></dd>
        <dt>UE</dt>
        <dd><?php echo $element->getLicUe() ?></dd>
        <dt>Code élément</dt>
        <dd><?php echo $element->getCodElp() ?></dd>
        <dt>Libellé élément</dt>
        <dd><?php echo $element->getLibElp() ?></dd>
    </dl>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Fermer</button>
</div>