<?php
/**
 * @var $this                      \Application\View\Renderer\PhpRenderer
 * @var $motifModificationServices \Application\Entity\Db\MotifModificationService[]
 */

use Application\Provider\Privileges;

function affBooleen($flg)
{
    // affiche booléen avec des glypheIcon
    return ($flg ? '<i class="fas fa-check text-succes"></i>' : '<i class="fas fa-xmark text-danger refuse"></i>');
}

$this->headTitle()->append("Motifs de modification de service dû");

$canEdit = $this->isAllowed(Privileges::getResourceId(Privileges::MOTIFS_MODIFICATION_SERVICE_DU_EDITION));

?>
<h1 class="page-header">Motifs de modification de service dû</h1>

<table class="table table-bordered table-sort">
    <thead>
    <th style="word-wrap: break-word ; ">Code</th>
    <th style="word-wrap: break-word ; ">Libelle</th>
    <th style="word-wrap: break-word ; ">Multiplicateur</th>
    <th style="word-wrap: break-word ; "
        title="Le dépassement du service dû ne donnera pas lieu à des heures complémentaires (comme par exemple pour une décharge)">
        Pas d'heures complémentaires
    </th>
    <?php if ($canEdit) echo '<th>Actions</th>' ?>
    </thead>
    <tbody>
    <?php foreach ($motifModificationServices as $fr): ?>
        <tr>
            <td style="word-wrap: break-word ; "><?= $fr->getCode() ?></td>
            <td style="word-wrap: break-word ; "><?= $fr->getLibelle() ?></td>
            <td style="word-wrap: break-word ; "><?= $fr->getMultiplicateur() ?></td>
            <td style="word-wrap: break-word ; "><?= affBooleen($fr->getDecharge()) ?></td>
            <?php if ($canEdit) { ?>
                <td style="text-align:center;width:1px;white-space: nowrap">
                    <a class="ajax-modal" data-event="motif-modification-service-saisie"
                       href="<?= $this->url('motif-modification-service/saisie', ['motifModificationServiceDu' => $fr->getId()]) ?>"
                       title="Modifier le Motif de Modificationde Service dû">
                        <i class="fas fa-pen-to-square"></i></a>
                    <a class="pop-ajax"
                       href="<?= $this->url('motif-modification-service/delete', ['motifModificationServiceDu' => $fr->getId()]) ?>"
                       title="Supprimer le Motif de Modificationde Service dû"
                       data-content="<p class='lead text-danger'><strong>Attention!</strong> Confirmez-vous cette suppression ?</p>"
                       data-confirm="true"
                       data-confirm-button="Oui"
                       data-cancel-button="Non"
                       data-submit-reload="true"
                    >
                        <i class="fas fa-trash-can"></i>
                    </a>
                </td>
            <?php } ?>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<?php if ($canEdit): ?>
    <a class="btn btn-primary ajax-modal" data-event="motif-modification-service-saisie"
       href="<?= $this->url('motif-modification-service/saisie') ?>"
       title="Ajouter un motif de modification du service dû">
        <i class="fas fa-pen-to-square"></i>
        Ajouter un motif de modification du service dû</a>

    <script type="text/javascript">
        $(function () {
            $("body").on("motif-modification-service-saisie", function (event, data) {
                window.location.reload();
            });
        });
    </script>
<?php endif ?>
