<?php
/**
 * Generated by UnicaenCode
 * Commande : php public/index.php UnicaenCode  module='Dossier'
 */
return [
    'dossier/autres/saisie'                                              => __DIR__ . '/view/dossier/autres/saisie.phtml',
    'dossier/autres/index'                                               => __DIR__ . '/view/dossier/autres/index.phtml',
    'dossier/employeur/rechercher'                                       => __DIR__ . '/view/dossier/employeur/rechercher.phtml',
    'dossier/employeur/recherche'                                        => __DIR__ . '/view/dossier/employeur/recherche.phtml',
    'dossier/employeur/saisie'                                           => __DIR__ . '/view/dossier/employeur/saisie.phtml',
    'dossier/employeur/liste'                                            => __DIR__ . '/view/dossier/employeur/liste.phtml',
    'dossier/employeur/index'                                            => __DIR__ . '/view/dossier/employeur/index.phtml',
    'dossier/intervenant-dossier/differences'                            => __DIR__ . '/view/dossier/intervenant-dossier/differences.phtml',
    'dossier/intervenant-dossier/purger-differences'                     => __DIR__ . '/view/dossier/intervenant-dossier/purger-differences.phtml',
    'dossier/intervenant-dossier/partial/formContact'                    => __DIR__ . '/view/dossier/intervenant-dossier/partial/formContact.phtml',
    'dossier/intervenant-dossier/partial/formStatutView'                 => __DIR__ . '/view/dossier/intervenant-dossier/partial/formStatutView.phtml',
    'dossier/intervenant-dossier/partial/formEmployeurView'              => __DIR__ . '/view/dossier/intervenant-dossier/partial/formEmployeurView.phtml',
    'dossier/intervenant-dossier/partial/formAutres'                     => __DIR__ . '/view/dossier/intervenant-dossier/partial/formAutres.phtml',
    'dossier/intervenant-dossier/partial/formInsee'                      => __DIR__ . '/view/dossier/intervenant-dossier/partial/formInsee.phtml',
    'dossier/intervenant-dossier/partial/formStatut'                     => __DIR__ . '/view/dossier/intervenant-dossier/partial/formStatut.phtml',
    'dossier/intervenant-dossier/partial/formIdentiteComplementaireView' => __DIR__ . '/view/dossier/intervenant-dossier/partial/formIdentiteComplementaireView.phtml',
    'dossier/intervenant-dossier/partial/formIdentiteView'               => __DIR__ . '/view/dossier/intervenant-dossier/partial/formIdentiteView.phtml',
    'dossier/intervenant-dossier/partial/formBancaire'                   => __DIR__ . '/view/dossier/intervenant-dossier/partial/formBancaire.phtml',
    'dossier/intervenant-dossier/partial/form'                           => __DIR__ . '/view/dossier/intervenant-dossier/partial/form.phtml',
    'dossier/intervenant-dossier/partial/formInseeView'                  => __DIR__ . '/view/dossier/intervenant-dossier/partial/formInseeView.phtml',
    'dossier/intervenant-dossier/partial/formAdresse'                    => __DIR__ . '/view/dossier/intervenant-dossier/partial/formAdresse.phtml',
    'dossier/intervenant-dossier/partial/formIdentite'                   => __DIR__ . '/view/dossier/intervenant-dossier/partial/formIdentite.phtml',
    'dossier/intervenant-dossier/partial/formEmployeur'                  => __DIR__ . '/view/dossier/intervenant-dossier/partial/formEmployeur.phtml',
    'dossier/intervenant-dossier/partial/formContactView'                => __DIR__ . '/view/dossier/intervenant-dossier/partial/formContactView.phtml',
    'dossier/intervenant-dossier/partial/formIdentiteComplementaire'     => __DIR__ . '/view/dossier/intervenant-dossier/partial/formIdentiteComplementaire.phtml',
    'dossier/intervenant-dossier/partial/formAdresseView'                => __DIR__ . '/view/dossier/intervenant-dossier/partial/formAdresseView.phtml',
    'dossier/intervenant-dossier/partial/formBancaireView'               => __DIR__ . '/view/dossier/intervenant-dossier/partial/formBancaireView.phtml',
    'dossier/intervenant-dossier/index'                                  => __DIR__ . '/view/dossier/intervenant-dossier/index.phtml',
];