<?php

use Application\Provider\Privilege\Privileges;

/**
 * @var $this              \Application\View\Renderer\PhpRenderer
 * @var $structure         \Application\Entity\Db\Structure
 * @var $validation        \Application\Entity\Db\Validation
 * @var $services          \Application\Entity\Db\Service[]
 * @var $typeVolumeHoraire \Application\Entity\Db\TypeVolumeHoraire
 *
 */

$validerUrl   = null;
$devaliderUrl = null;

if ($this->isAllowed($validation, Privileges::ENSEIGNEMENT_VALIDATION)) {
    $validerUrl = $this->url('intervenant/validation/service/valider', [
        'typeVolumeHoraire' => $typeVolumeHoraire->getId(),
        'structure'         => $structure->getId(),
    ], [], true);
}

if ($this->isAllowed($validation, Privileges::ENSEIGNEMENT_DEVALIDATION)) {
    $devaliderUrl = $this->url('intervenant/validation/service/devalider', [
        'validation' => $validation->getId(),
    ], [], true);
}

$id = $validation->getId() ? 'validation-' . $validation->getId() : 'structure-' . $structure->getId();

?>

<div class="validation panel panel-<?= $validation->getId() ? 'success' : 'default' ?>" id="<?= $id ?>">
    <div class="panel-heading panel-heading-h3">
        <h3><?= $validation->getId() ? 'Validation ' : 'Enseignements ' ?><?= $structure ?></h3>
    </div>
    <div class="panel-body">
        <!-- Informations -->
        <?php if ($validation->getId()): ?>
            <ul style="list-style-type: none">
                <li><span class="fas fa-thumbs-up"></span> Validé
                    le <?= $validation->getHistoCreation()->format(\Application\Constants::DATE_FORMAT) ?>
                    par <?= $this->utilisateur($validation->getHistoCreateur()) ?></li>
            </ul>
        <?php endif; ?>

        <!-- Enseignements concernés -->
        <a title="Cliquez pour afficher/masquer les enseignements concernés"
           href="#details-enseignements-<?= $id ?>"
           role="button"
           aria-expanded="false"
           aria-controls="details-enseignements-<?= $id ?>"
           data-toggle="collapse"
        >Enseignements concernés
            <small>(cliquez pour afficher/cacher)</small>
        </a>
        <div class="collapse <?= $validation->getId() ? '' : 'in' ?>" id="details-enseignements-<?= $id ?>">
            <?= $this->serviceListe($services)->setTypeVolumeHoraire($typeVolumeHoraire)->setReadonly(true)->render(); ?>
        </div>

    </div>

    <?php if ($validerUrl || $devaliderUrl): ?>
        <div class="panel-footer">
            <!-- Actions -->
            <?php if ($validerUrl): ?>
                <a
                    href="<?= $validerUrl ?>"
                    class="validation-delete btn btn-primary btn-primary pop-ajax"
                    data-submit-reload="true"
                    data-content="<p class='lead text-danger'><strong>Attention!</strong> Confirmez-vous cette validation ?</p>"
                    data-confirm="true"
                    data-confirm-button="Oui"
                    data-cancel-button="Non"
                ><span class="fas fa-thumbs-up"></span> Valider</a>
            <?php endif; ?>
            <?php if ($devaliderUrl): ?>
                <a
                    href="<?= $devaliderUrl ?>"
                    class="validation-delete btn btn-primary btn-danger pop-ajax"
                    data-submit-reload="true"
                    data-content="<p class='lead text-danger'><strong>Attention!</strong> Confirmez-vous cette dévalidation ?</p>"
                    data-confirm="true"
                    data-confirm-button="Oui"
                    data-cancel-button="Non"
                ><span class="fas fa-thumbs-down"></span> Dévalider</a>
            <?php endif; ?>
        </div>
    <?php endif; ?>
</div>