<?php
/*
* @author JORIOT Florian <florian.joriot at unicaen.fr>
*/

/**
 * @var $this  \Application\View\Renderer\PhpRenderer
 */

use Application\Provider\Privileges;

function affBooleen($flg)
{
    // affiche booléen avec des glypheIcon
    return ($flg ? '<i class="fas fa-check text-succes"></i>' : '<i class="fas fa-xmark text-danger refuse"></i>');
}

$this->headTitle()->append("Gestion des périodes");
$canEdit = $this->isAllowed(Privileges::getResourceId(Privileges::PARAMETRES_PERIODES_EDITION));
echo $this->messenger()->addCurrentMessagesFromFlashMessenger();
?>

<h1 class="page-header">Gestion des périodes</h1>

<table class="table table-bordered table-sm">
    <thead>
    <tr>
        <th style="text-align: center">Code</th>
        <th style="text-align: center">Libellé court</th>
        <th style="text-align: center">Libellé long</th>
        <th style="text-align: center">Enseignement</th>
        <th style="text-align: center">Paiement</th>
        <th style="text-align: center"><abbr title="Ecart de mois avec le début de l'année universitaire choisie">EcartMois</abbr></th>
        <?php if ($canEdit): ?>
            <th style="text-align: center">Actions</th>
        <?php endif; ?>
    </tr>
    </thead>
    <tbody class="triables ui-sortable">
    <?php foreach ($periodes as $periode): ?>
        <tr class="champ-triable" data-id= <?php echo $periode->getId() ?>>
            <td style="text-align: center"><?= $periode->getCode(); ?></td>
            <td style="text-align: center"><?= $periode->getLibelleCourt(); ?></td>
            <td style="text-align: center"><?= $periode->getLibelleLong(); ?></td>
            <td style="text-align: center"><?= affBooleen($periode->getEnseignement()); ?></td>
            <td style="text-align: center"><?= affBooleen($periode->getPaiement()); ?></td>
            <td style="text-align: center" title="Écart de mois avec le début de l'année universitaire choisie"><?= $periode->getEcartMois(); ?></td>
            <?php if ($canEdit): ?>
                <td style="text-align: center">
                    <a class="ajax-modal" data-event="periodes-edition"
                       href="<?= $this->url('periodes/saisie', ['periode' => $periode->getId()], ['query' => ['tab' => 'edition']]) ?>"
                       title="Modifier la période"><i class="fas fa-pen-to-square"></i></a>
                    <a class="pop-ajax" data-title="Suppression de période" data-content="Êtes-vous sur de vouloir supprimer ?" data-confirm="true"
                       data-submit-reload="true"
                       href="<?= $this->url('periodes/supprimer', ['periode' => $periode->getId()]) ?>"
                       title="Supprimer la periode"><i class="fas fa-trash-can"></i></a>
                    <i class="fas fa-arrows-up-down"
                       title="Vous pouvez trier les champs en déplaçant les lignes du tableau"></i>&nbsp;
                </td>
            <?php endif; ?>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<?php if ($canEdit): ?>
    <a class="btn btn-primary ajax-modal" data-event="periodes-edition" href="<?= $this->url('periodes/saisie'); ?>"><i class="fas fa-plus"></i> Ajout
        d'une
        nouvelle periode</a>
<?php endif; ?>

<script type="text/javascript">

    $(function () {
        $(".triables").sortable({
            handle: '.fa-arrows-up-down',
            axis: 'y',
            update: function (event, ui) {
                var champsIds = '';
                ui.item.parent().find('tr.champ-triable').each(function () {
                    if (champsIds != '') champsIds += ',';
                    champsIds += $(this).data('id');
                });

                $.ajax({
                    type: 'POST',
                    url: "<?= $this->url('periodes/trier')?>",
                    data: {champsIds: champsIds},
                    success: function () { unicaenVue.flashMessenger.toast("Tri effectué", 'success'); },
                });



            }
        });
    });

    $(function () {
        $("body").on("periodes-edition", function (event, data) {
            window.location.reload();
        });
    });
</script>