<?php
/*
* @author JORIOT Florian <florian.joriot at unicaen.fr>
*/

/* @var $form Application\Form\Periode\PeriodeSaisieForm */
/* @var $errors array */

echo $this->messenger()->addCurrentMessagesFromFlashMessenger();
//echo $this->form()->openTag($form->prepare());
//echo $this->formControlGroup($form->get('code'));
//echo $this->formControlGroup($form->get('libelleLong'));
//echo $this->formControlGroup($form->get('libelleCourt'));
//echo $this->formControlGroup($form->get('ordre'));
//echo $this->formControlGroup($form->get('enseignement'));
//echo $this->formControlGroup($form->get('paiement'));
//echo $this->formControlGroup($form->get('ecartMois'));
//echo $this->formControlGroup($form->get('ecartMoisPaiement'));
//echo $this->formHidden($form->get('id'));

//echo $this->formSubmit($form->get('submit'));
//echo $this->formControlGroup($form->get('security'));
//echo $this->form()->closeTag();
echo $this->form($form);
