<?php

$form->prepare();

echo $this->form()->openTag($form);
echo $this->formControlGroup($form->get('heures'), 'Zend\Form\View\Helper\FormNumber');
echo '<hr /><div style="text-align:right">';
echo $this->formRow($form->get('submit'));
echo ' ';
echo $this->formRow($form->get('annuler'));
echo '</div>';
echo $this->formHidden($form->get('type-volume-horaire'));
echo $this->formHidden($form->get('service-referentiel'));
echo $this->form()->closeTag() . '<br />';

echo $this->formErrors($form);
if ($errors)
    echo $this->messenger()->setMessages([UnicaenApp\View\Helper\Messenger::ERROR => $errors]);