<?php
/**
 * @var $this \Application\View\Renderer\PhpRenderer
 * @var $typeDotations \Application\Entity\Db\TypeDotation[]
 */

use Application\Provider\Privilege\Privileges;

$this->headTitle()->append("Types de dotation");

$canEdit = $this->isAllowed( Privileges::getResourceId(Privileges::BUDGET_TYPE_DOTATION_EDITION) );

?>
<h1 class="page-header">Type de dotation</h1>
<table class="table table-bordered table-sort">
    <thead>
    <th>Libelle</th>
    <th>Source Code</th>
    <th>Type de ressource</th>
    <th>Src/Actions</th>
    </thead>
    <tbody>
    <?php foreach ($typeDotations as $elt) {
        ?>
        <tr>
            <td><?php echo $elt->getLibelle() ?></td>
            <td><?php echo $elt->getSourceCode() ?></td>
            <td><?php echo $elt->getTypeRessource() ?></td>
            <td style="text-align:center;">
                    <?php if ($elt->getSource()->getImportable() || !$canEdit): ?>
                        <?php echo $elt->getSource() ?>
                    <?php else: ?>
                        <a class="ajax-modal" data-event="type-dotation-saisie"
                           href="<?php echo $this->url('budget/type-dotation-saisie', ['typeDotation' => $elt->getId()]) ?>"
                           title="Modifier le type de dotation">
                            <span class="glyphicon glyphicon-edit"></span></a>
                        <a class="pop-ajax"  data-event="type-dotation-saisie"
                           href="<?php echo $this->url('budget/type-dotation-delete', ['typeDotation' => $elt->getId()]) ?>"
                           title="Supprimer le type de dotation"
                           data-content="<p class='lead text-danger'><strong>Attention!</strong> Confirmez-vous cette suppression ?</p>"
                           data-confirm="true"
                           data-confirm-button="Oui"
                           data-cancel-button="Non"
                           data-submit-reload="true"
                        >
                            <span class="glyphicon glyphicon-remove"></span>
                        </a>
                    <?php endif; ?>
            </td>
        </tr>
    <?php } ?>
</table>
<?php if ($canEdit): ?>
<a class="btn btn-primary ajax-modal" data-event="type-dotation-saisie"
   href="<?php echo $this->url('budget/type-dotation-saisie') ?>"
   title="Ajouter un type de dotation">
    <span class="glyphicon glyphicon-edit"></span>
    Ajouter un type de dotation</a>
<script type="text/javascript">
    $(function () {
        $("body").on("type-dotation-saisie", function (event, data) {
            window.location.reload();
        });
    });
</script>
<?php endif; ?>