<?php

namespace Application;

use Indicateur\Entity\Db\Indicateur;

/**
 * @var $this        \Application\View\Renderer\PhpRenderer
 * @var $indicateurs Indicateur[]
 * @var $counts      array
 */

if (empty($indicateurs)): ?>
    Aucun
<?php else: ?>
    <table class="table table-bordered table-sm">
        <thead>
        <tr>
            <th class="categorie">Catégorie</th>
            <th class="numero">N°</th>
            <th class="intitule">Intitulé de l'indicateur</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($indicateurs as $indicateur):
            if ($indicateur->isSpecial()){
                $urlResult = $this->url($indicateur->getRoute());
            }else{
                $urlResult = $this->url('indicateur/result', ['indicateur' => $indicateur->getId()]);
            }
            $count = $counts[$indicateur->getId()];
            ?>
            <tr class="indicateur" id="<?= $indicateur->getId() ?>">

                <td class="categorie"><?= $indicateur->getTypeIndicateur() ?></td>
                <td class="numero"><?= $indicateur->getNumero() ?></td>
                <td class="intitule">
                    <?php if ($count): ?>
                        <a href="<?= $urlResult ?>"
                           title="Cliquez pour vous rendre à la page concernée"><?= $indicateur->getLibelle($count) ?></a>
                    <?php else: ?>
                        <?= $indicateur->getLibelle($count) ?>
                    <?php endif ?>
                </td>

            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
<?php endif;