<?php

use Application\Entity\Db\TypeVolumeHoraire;
use Indicateur\Entity\Db\IndicateurDepassementCharges;
use Application\Entity\Db\Intervenant;

/**
 * @var $this                         \Application\View\Renderer\PhpRenderer
 * @var $title                        string
 * @var $intervenant                  Intervenant
 * @var $idcs                         IndicateurDepassementCharges[]
 * @var $typeVolumeHoraireCode        string
 */
if ($typeVolumeHoraireCode == TypeVolumeHoraire::CODE_PREVU) {
    $servicesUrl = $this->url('intervenant/services-prevus', ['intervenant' => $intervenant->getId()]);
} else {
    $servicesUrl = $this->url('intervenant/services-realises', ['intervenant' => $intervenant->getId()]);
}

?>
<h1 class="page-header"><?= $title ?></h1>

<table class="table table-bordered table-condensed table-srt">
    <tr>
        <th>Composante</th>
        <th>Enseignement</th>
        <th>Type d'intervention</th>
        <th>Heures</th>
    </tr>

    <?php foreach ($idcs as $idc): ?>
        <tr>
            <td><?= $this->structure($idc->getStructure())->renderLink() ?></td>
            <td><?= $this->elementPedagogique($idc->getElementPedagogique())->renderLink() ?></td>
            <td><?= $idc->getTypeIntervention() ?></td>
            <td><?= floatToString($idc->getHeures()) ?></td>
        </tr>
    <?php endforeach; ?>
</table>
<button class="btn btn-default" type="button" onclick="window.history.back()"><i class="fas fa-rotate-left" aria-hidden="true"></i>
    Retour à l'indicateur
</button>
<a class="btn btn-primary" href="<?= $servicesUrl ?>"><i class="fas fa-list" aria-hidden="true"></i>
    Voir la fiche de services de l'intervenant
</a>