<?php

use \Laminas\Form\Element\Checkbox;
use \Laminas\Form\Element\Select;
use \Application\Provider\Privilege\Privileges;

/**
 * @var $this        \Application\View\Renderer\PhpRenderer
 * @var $indicateurs \Indicateur\Entity\Db\TypeIndicateur[]
 */

$showAbonnements = $this->isAllowed(Privileges::getResourceId(Privileges::INDICATEUR_ABONNEMENT));

$this->headTitle()->append($title = "Indicateurs");

$notif = new Select('abonnement');
$notif->setEmptyOption('Aucune');
$notif->setAttribute('class', 'notif');
$notif->setValueOptions(\Indicateur\Entity\Db\NotificationIndicateur::$frequences);

$inHome = new Checkbox('in-home');
$inHome->setCheckedValue('1');
$inHome->setAttribute('class', 'in-home');
$inHome->setUncheckedValue('0');

$noAbo = new \Indicateur\Entity\Db\NotificationIndicateur();

?>
<h1 class="page-header"><?= $title ?></h1>
<div class="indicateurs-liste">
    <?php foreach ($indicateurs as $typeIndicateur): ?>
        <div class="panel panel-default indicateurs">
            <div class="panel-heading"><?= $typeIndicateur ?></div>
            <table class="table table-bordered table-condensed type-indicateur non-calcule" data-id="<?= $typeIndicateur->getId() ?>">
                <thead>
                <tr>
                    <th class="numero">N°</th>
                    <th class="intitule">Intitulé de l'indicateur</th>
                    <?php if ($showAbonnements): ?>
                        <th class="page-accueil">Page d'accueil</th>
                        <th class="notification">Notification par mail</th>
                    <?php endif ?>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($typeIndicateur->getIndicateur() as $indicateur):
                    /* @var $indicateur Indicateur */
                    $abonnement = $indicateur->getNotification()->first() ?: $noAbo;
                    $urlAbonner = $this->url('indicateur/abonner', ['indicateur' => $indicateur->getId()]);
                    $urlResult = $this->url('indicateur/result', ['indicateur' => $indicateur->getId()]);

                    ?>
                    <tr class="indicateur" id="<?= $indicateur->getId() ?>"
                        data-url="<?= $urlAbonner ?>">

                        <td class="numero">
                            <?= $indicateur->getNumero() ?>
                        </td>
                        <td class="intitule" data-url="<?= $urlResult ?>" style="width:70%"></td>

                        <?php if ($showAbonnements): ?>
                            <td class="page-accueil">
                                <?= $this->formcheckbox($inHome->setValue($abonnement->getInHome())); ?>
                            </td>
                            <td class="notification">
                                <?= $this->formSelect($notif->setValue($abonnement->getFrequence())); ?>
                                <span class="indicateur-info glyphicon glyphicon-info-sign" aria-hidden="true"
                                      data-toggle="tooltip" data-placement="auto" data-html="true"
                                      title="<?= $abonnement->getFrequence() ? $abonnement->getExtraInfos() : '' ?>"
                                      style="<?= $abonnement->getFrequence() ? '' : 'display: none' ?>"></span>
                            </td>
                        <?php endif ?>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    <?php endforeach; ?>
</div>
<script type="text/javascript">
    $(function () {

        WidgetInitializer.add('indicateurs-liste', {

            calculer: function ()
            {
                var that = this;

                that.element.find('td.intitule').html(
                    'Calcul de l\'indicateur en cours <span class="loading">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>'
                );

                that.calculerNextType();
            },

            calculerNextType: function ()
            {
                var typeIndicateur = this.element.find('.type-indicateur.non-calcule:first');
                if (typeIndicateur.length == 1) {
                    this.calculerType(typeIndicateur);
                }
            },

            calculerType: function (typeIndicateur)
            {
                var that = this;

                typeIndicateur.removeClass("non-calcule");
                $.post("<?= $this->url('indicateur') ?>" + "/calcul/" + typeIndicateur.data('id'), [], function (data)
                    {
                        for (id in data) {
                            var td = that.element.find('.indicateur#' + id).find('.intitule');

                            if (data[id].count == 0) {
                                td.html(data[id].libelle);
                            } else {
                                td.html("<a href=" + td.data('url') + ">" + data[id].libelle + '</a>');
                            }
                        }
                        that.calculerNextType();
                    }
                ).fail(function (jqXHR)
                {
                    alertFlash(jqXHR.responseText, 'danger', 5000);
                    console.log(jqXHR);
                    that.calculerNextType();
                });

            },

            _create: function ()
            {
                var that = this;

                setTimeout(function () {that.calculer()}, 100);
            },

        });

    });
</script>
