<?php

use Application\Provider\Privileges;
use Laminas\Form\Element\Checkbox;
use Laminas\Form\Element\Select;

/**
 * @var $this        \Application\View\Renderer\PhpRenderer
 * @var $indicateurs \Indicateur\Entity\Db\TypeIndicateur[]
 */

$showAbonnements = $this->isAllowed(Privileges::getResourceId(Privileges::INDICATEUR_ABONNEMENT));

$this->headTitle()->append($title = "Indicateurs");

$notif = new Select('abonnement');
$notif->setEmptyOption('Aucune');
$notif->setAttribute('class', 'notif');
$notif->setValueOptions(\Indicateur\Entity\Db\NotificationIndicateur::$frequences);

$inHome = new Checkbox('in-home');
$inHome->setCheckedValue('1');
$inHome->setAttribute('class', 'in-home');
$inHome->setUncheckedValue('0');

$noAbo = new \Indicateur\Entity\Db\NotificationIndicateur();

?>
<h1 class="page-header"><?= $title ?></h1>
<div class="indicateurs-liste">
    <?php foreach ($indicateurs as $typeIndicateur): ?>
        <div class="card bg-default indicateurs border-end-0 border-bottom-0 border-start-0">
            <div class="card-header border-start border-end"><?= $typeIndicateur ?></div>
            <table class="table table-bordered table-sm type-indicateur non-calcule" data-id="<?= $typeIndicateur->getId() ?>">
                <thead>
                <tr>
                    <th class="numero">N°</th>
                    <th class="intitule">Intitulé de l'indicateur</th>
                    <?php if ($showAbonnements): ?>
                        <th class="page-accueil">Page d'accueil</th>
                        <th class="notification">Notification par mail</th>
                    <?php endif ?>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($typeIndicateur->getIndicateur() as $indicateur):
                    /* @var $indicateur Indicateur */
                    $abonnement = $indicateur->getNotification()->first() ?: $noAbo;
                    $urlAbonner = $this->url('indicateur/abonner', ['indicateur' => $indicateur->getId()]);
                    if ($indicateur->isSpecial()){
                        $urlResult = $this->url($indicateur->getRoute());
                    }else{
                        $urlResult = $this->url('indicateur/result', ['indicateur' => $indicateur->getId()]);
                    }

                    ?>
                    <tr class="indicateur" id="<?= $indicateur->getId() ?>"
                        data-url="<?= $urlAbonner ?>">

                        <td class="numero">
                            <?= $indicateur->getNumero() ?>
                        </td>
                        <td class="intitule" data-url="<?= $urlResult ?>" style="width:70%"></td>

                        <?php if ($showAbonnements): ?>
                            <td class="page-accueil">
                                <?= $this->formcheckbox($inHome->setValue($abonnement->getInHome())); ?>
                            </td>
                            <td class="notification">
                                <?= $this->formSelect($notif->setValue($abonnement->getFrequence())); ?>
                                <span class="indicateur-info fas fa-circle-info" aria-hidden="true"
                                      data-bs-toggle="tooltip" data-placement="auto" data-html="true"
                                      title="<?= $abonnement->getFrequence() ? $abonnement->getExtraInfos() : '' ?>"
                                      style="<?= $abonnement->getFrequence() ? '' : 'display: none' ?>"></span>
                            </td>
                        <?php endif ?>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    <?php endforeach; ?>
</div>
<script type="text/javascript">
    $(function () {

        WidgetInitializer.add('indicateurs-liste', {

            calculer: function ()
            {
                var that = this;

                that.element.find('td.intitule').html(
                    'Calcul de l\'indicateur en cours <span class="loading">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>'
                );

                that.calculerNextType();
            },

            calculerNextType: function ()
            {
                var typeIndicateur = this.element.find('.type-indicateur.non-calcule:first');
                if (typeIndicateur.length == 1) {
                    this.calculerType(typeIndicateur);
                }
            },

            calculerType: function (typeIndicateur)
            {
                var that = this;

                typeIndicateur.removeClass("non-calcule");
                $.ajax({
                    type: 'POST',
                    url: "<?= $this->url('indicateur') ?>" + "/calcul/" + typeIndicateur.data('id'),
                    data: {},
                    success: function (data) {
                        for (id in data) {
                            var td = that.element.find('.indicateur#' + id).find('.intitule');

                            if (data[id].count == 0) {
                                td.html(data[id].libelle);
                            } else {
                                td.html("<a href=" + td.data('url') + ">" + data[id].libelle + '</a>');
                            }
                        }
                        that.calculerNextType();
                    },
                    error: function (jqXHR) {
                        if (jqXHR.responseText != null && jqXHR.responseText.toString() !== "") {
                            unicaenVue.flashMessenger.toast(jqXHR.responseText, 'error');
                            console.log(jqXHR);
                        }
                        that.calculerNextType();
                    }
                });
            },

            _create: function ()
            {
                var that = this;

                setTimeout(function () {that.calculer()}, 100);
            },

        });



        WidgetInitializer.add('indicateur', {

            _create: function ()
            {
                var that = this;

                this.getElementNotif().change(function () { that.abonner(); });
                this.getElementInHome().change(function () { that.abonner(); });

                this.element.find(".glyphicon.glyphicon-info-sign").tooltip();
            },


            abonner: function ()
            {
                var that = this;
                var notif = this.getElementNotif();
                var inHome = this.getElementInHome();

                notif.data('previousValue', notif.val());
                notif.addClass("loading");
                $.ajax({
                    type: 'POST',
                    url: this.element.data('url'),
                    data: {
                        notification: notif.val(),
                        'in-home': inHome.is(':checked') ? '1' : '0'
                    },
                    success: function (data, textStatus, jqXHR)
                    {
                        if (data.status !== "success") {
                            notif.val(notif.data('previousValue'));
                        }
                        notif.removeClass("loading");
                        var infos = $(".indicateur-info", notif.parent()).attr('title', data.infos).tooltip('destroy').tooltip();
                        notif.val() ? infos.show() : infos.hide();
                        unicaenVue.flashMessenger.toast(data.message, data.status);
                    }
                });
            },

            getElementNotif: function () { return this.element.find('select.notif'); },
            getElementInHome: function () { return this.element.find('input.in-home'); }

        });

    });


</script>
