<?php


$this->intervenant($intervenant)->renderTitle('Candidature');

echo $this->vue('mission/liste-candidatures', [

    'intervenant'                   => $intervenant->getId(),
    'renseignerDonneesPersonnelles' => $renseignerDonneesPersonnelles,
]);

$nextEtape = \Workflow\Entity\Db\WfEtape::CANDIDATURE_VALIDATION;

echo '<hr />';

echo $this->feuilleDeRoute($intervenant)->renderNav($nextEtape);