<?php

use Workflow\Entity\Db\WorkflowEtape;

$this->intervenant($intervenant)->renderTitle('Candidature');

echo $this->vue('mission/liste-candidatures', [
    'intervenant'                   => $intervenant->getId(),
    'renseignerDonneesPersonnelles' => $renseignerDonneesPersonnelles,
]);

$wfEtape = WorkflowEtape::CANDIDATURE_SAISIE;

echo '<hr />';

echo $this->vue('workflow/nav', ['intervenant' => $intervenant->getId(), 'etape' => $wfEtape]);