<?php
/**
 * @var $this              \Application\View\Renderer\PhpRenderer
 * @var $intervenant       \Intervenant\Entity\Db\Intervenant
 */

use Application\Provider\Privileges;

$this->headTitle()->append("Gestion des offres d'emploi");
$canEdit      = $this->isAllowed(Privileges::getResourceId(Privileges::MISSION_EDITION_TYPE));
$canSupprimer = $this->isAllowed(Privileges::getResourceId(Privileges::MISSION_SUPPRESSION_TYPE));
?>

<h1 class="page-header">Offres d'emploi</h1>

<?= $this->vue('mission/liste-offre-emploi', [
    'public' => true,
]); ?>
