<?php
/**
 * @var $this              \Application\View\Renderer\PhpRenderer
 * @var $offreEmploi       \Mission\Entity\Db\OffreEmploi
 * @var $utilisateur       \Utilisateur\Entity\Db\Utilisateur
 * @var $intervenant       \Intervenant\Entity\Db\Intervenant
 * @var $canPostuler
 */

use Application\Provider\Privileges;

$this->headTitle()->append("Gestion des offres d'emploi");
$canEdit               = $this->isAllowed(Privileges::getResourceId(Privileges::MISSION_OFFRE_EMPLOI_MODIFIER));
$canSupprimer          = $this->isAllowed(Privileges::getResourceId(Privileges::MISSION_OFFRE_EMPLOI_SUPPRESSION));
$canValider            = $this->isAllowed(Privileges::getResourceId(Privileges::MISSION_OFFRE_EMPLOI_VALIDER));
$canValiderCandidature = $this->isAllowed(Privileges::getResourceId(Privileges::MISSION_CANDIDATURE_VALIDER));
$idOffre               = ($offreEmploi) ? $offreEmploi->getId() : null;
$titre                 = ($offreEmploi) ? $offreEmploi->getTitre() : 'Liste des offres d\'emploi';

echo $this->messenger()->addCurrentMessagesFromFlashMessenger();


?>


<?= $this->vue('mission/liste-offre-emploi', [
    'id'                    => $idOffre,
    'canModifier'           => $canEdit,
    'canPostuler'           => $canPostuler,
    'canSupprimer'          => $canSupprimer,
    'canValider'            => $canValider,
    'canVoirCandidature'    => $canVoirCandidature,
    'canValiderCandidature' => $canValiderCandidature,
    'utilisateur'           => $utilisateur,
]); ?>
