<?php
/**
 * @var $this              \Application\View\Renderer\PhpRenderer
 * @var $offreEmploi       \Mission\Entity\Db\OffreEmploi
 * @var $utilisateur       \Utilisateur\Entity\Db\Utilisateur
 * @var $intervenant       \Intervenant\Entity\Db\Intervenant
 */

use Application\Provider\Privileges;

$this->headTitle()->append("Gestion des offres d'emploi");
$canEdit      = $this->isAllowed(Privileges::getResourceId(Privileges::MISSION_OFFRE_EMPLOI_MODIFIER));
$canSupprimer = $this->isAllowed(Privileges::getResourceId(Privileges::MISSION_OFFRE_EMPLOI_SUPPRESSION));
$canPostuler  = $this->isAllowed(Privileges::getResourceId(Privileges::MISSION_OFFRE_EMPLOI_POSTULER));
$canValider   = $this->isAllowed(Privileges::getResourceId(Privileges::MISSION_OFFRE_EMPLOI_VALIDER));
$idOffre      = ($offreEmploi) ? $offreEmploi->getId() : null;
$titre        = ($offreEmploi) ? $offreEmploi->getTitre() : 'Liste des offres d\'emploi';

echo $this->messenger()->addCurrentMessagesFromFlashMessenger();


?>

<h1 class="page-header"><?= $titre ?></h1>

<?= $this->vue('mission/liste-offre-emploi', [
    'public'       => true,
    'id'           => $idOffre,
    'canModifier'  => $canEdit,
    'canPostuler'  => $canPostuler,
    'canSupprimer' => $canSupprimer,
    'canValider'   => $canValider,
    'utilisateur'  => $utilisateur,
    'intervenant'  => $intervenant,
]); ?>
