<?php
/**
 * Generated by UnicaenCode
 * Commande : ose-code  module='Application'
 */
return [
    'error/exception'                                => __DIR__ . '/view/error/exception.phtml',
    'error/index'                                    => __DIR__ . '/view/error/index.phtml',
    'application/index/plan'                         => __DIR__ . '/view/application/index/plan.phtml',
    'application/index/index'                        => __DIR__ . '/view/application/index/index.phtml',
    'application/index/changement-annee'             => __DIR__ . '/view/application/index/changement-annee.phtml',
    'layout/ajax'                                    => __DIR__ . '/view/layout/ajax.phtml',
    'layout/menu-principal'                          => __DIR__ . '/view/layout/menu-principal.phtml',
    'layout/layout'                                  => __DIR__ . '/view/layout/layout.phtml',
    'unicaen-app/application/apropos'                => __DIR__ . '/view/unicaen-app/application/apropos.phtml',
    'unicaen-app/application/contact'                => __DIR__ . '/view/unicaen-app/application/contact.phtml',
];