<div style="margin-top:10px;">
    <?= $this->form()->openTag($form); ?>

    <table class="table table-bordered table-extra-condensed">
        <thead>
            <tr>
                <th>Type(s) Modulateur(s)</th>
                <th>Modulateur(s)</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <?php if($form->has('modulateur')): ?>
                    <td><?= $form->get('modulateur')->getLabel(); ?></td>
                    <td><?= $this->formSelect($form->get('modulateur')); ?></td>
                <?php else: ?>
                    <td colspan="2" class="text-center" >Aucun modulateur ne correspond aux enseignements de cette formation.</td>
                <?php endif; ?>
            </tr>
        </tbody>
    </table>
    <table class="table table-bordered table-extra-condensed">
        <thead>
            <tr>
                <th colspan="2">Centre de coûts de l'élément pédagogique</th>
            </tr>
        </thead>
        <tbody>
            <?php if($form->has('fi')): ?>
                <tr>
                    <td class="text-center"><abbr title="Formation initiale"><?= $form->get('fi')->getLabel(); ?></abbr></td>
                    <td><?= $this->formSelect($form->get('fi')); ?></td>
                </tr>
            <?php endif; ?>
            <?php if($form->has('fa')): ?>
                <tr>
                    <td class="text-center"><abbr title="Formation apprentissage"><?= $form->get('fa')->getLabel(); ?></abbr></td>
                    <td><?= $this->formSelect($form->get('fa')); ?></td>
                </tr>
            <?php endif; ?>
            <?php if($form->has('fc')): ?>
                <tr>
                    <td class="text-center"><abbr title="Formation continue"><?= $form->get('fc')->getLabel(); ?></abbr></td>
                    <td><?= $this->formSelect($form->get('fc')); ?></td>
                </tr>
            <?php endif; ?>
        </tbody>
    </table>

    <?= $this->formSubmit($form->get('submit')); ?>

    <?= $this->form()->closeTag($form); ?>


</div>

