<div>
    <?= $this->form()->openTag($form); ?>

    <table class="table table-bordered table-extra-condensed">
        <thead>
            <tr>
                <th>Type(s) Modulateur(s)</th>
                <th>Modulateur(s)</th>
            </tr>
        </thead>
        <tbody>
            <tr>

                    <td><?= $form->get('modulateur')->getLabel(); ?></td>
                    <td><?= $this->formSelect($form->get('modulateur')); ?></td>

            </tr>
        </tbody>
    </table>

    <?= $this->form()->closeTag($form); ?>


</div>