<?php

/**
 * @var $this \Application\View\Renderer\PhpRenderer
 * @var $element \Application\Entity\Db\ElementPedagogique
 * @var $title string
 * @var $form Application\Form\OffreFormation\ElementPedagogiqueSaisie
 */

$this->messenger()->addCurrentMessagesFromFlashMessenger();
if ($form){
    echo '<p class="lead text-danger"><strong>Attention!</strong> Confirmez-vous la suppression de cet enregistrement ?</p>';
    echo $this->elementPedagogique($element)->renderDescription();
    echo $this->formsupprimer($form);
}