<?php

use Application\Provider\Privilege\Privileges;

$tabs = [
    [
        'id'      => 'fiche',
        'label'   => 'Fiche',
        'content' => (string)$this->elementPedagogique($element),
    ],
];

if ($this->isAllowed(Privileges::getResourceId(Privileges::ODF_ELEMENT_VH_VISUALISATION))) {
    $tabs[] = [
        'id'    => 'volume-horaire-ens',
        'label' => '<i class="fas fa-clock"></i> Volumes horaires',
        'url'   => $this->url('of/element/volume-horaire', ['elementPedagogique' => $element->getId()]),
    ];
}

if ($this->isAllowed(Privileges::getResourceId(Privileges::ODF_MODULATEURS_EDITION)) ||
    $this->isAllowed(Privileges::getResourceId(Privileges::ODF_CENTRES_COUT_EDITION))) {
    $tabs[] = [
        'id'    => 'modulateur-cc',
        'label' => '<i class="fas fa-clock"></i> Modulateurs et Centres de coûts',
        'url'   => $this->url('of/element/modulateurs-centres-couts', ['elementPedagogique' => $element->getId()]),
    ];
}


echo $this->tabajax($tabs);
