<?php

use Application\Provider\Privilege\Privileges;

$tabs = [
    [
        'id'      => 'fiche',
        'label'   => 'Fiche',
        'content' => (string)$this->elementPedagogique($element),
    ],
];

if ($this->isAllowed(Privileges::getResourceId(Privileges::ODF_ELEMENT_VH_VISUALISATION))) {
    $tabs[] = [
        'id'    => 'volume-horaire-ens',
        'label' => '<span class="glyphicon glyphicon-time"></span> Volumes horaires',
        'url'   => $this->url('of/element/volume-horaire', ['elementPedagogique' => $element->getId()]),
    ];
}

if($this->isAllowed(Privileges::getResourceId(Privileges::ODF_ELEMENT_MODULATEUR_CC_VISUALISATION))){
    $tabs[] = [
        'id'    => 'modulateur-cc',
        'label' => '<span class="glyphicon glyphicon-time"></span> Modulateurs et Centres de coûts',
        'url'   => $this->url('of/element/voir-modulateurs-centres-couts', ['elementPedagogique' => $element->getId()]),
    ];
}


echo $this->tabajax($tabs);
