<?php

use Application\Entity\Db\VolumeHoraireEns;
use Application\Filter\StringFromFloat;
use Application\Form\OffreFormation\VolumeHoraireEnsForm;

/**
 * @var $this             \Application\View\Renderer\PhpRenderer
 * @var $vhes             VolumeHoraireEns[]
 * @var $form             VolumeHoraireEnsForm
 */

?>
<style>
    .edition-volume-horaire-ens .source {
        white-space: nowrap;
    }

    .edition-volume-horaire-ens td input {
        width: 100%;
    }

</style>
<?php echo $this->form()->openTag($form); ?>
<table class="table table-bordered table-condensed table-hover edition-volume-horaire-ens" style="margin-top: 2px">
    <thead>
    <tr>
        <th>&nbsp;</th>
        <th>Heures</th>
        <th>Groupes</th>
        <th>Source</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($vhes as $vhe):
        $canEdit = $this->isAllowed($vhe, Application\Provider\Privilege\Privileges::ODF_ELEMENT_VH_EDITION);

        if ($canEdit) {
            $heures  = $this->formText($form->getElement($vhe,'heures'));
            $groupes = $this->formText($form->getElement($vhe, 'groupes'));
        } else {
            $heures  = StringFromFloat::run($vhe->getHeures(), false);
            $groupes = StringFromFloat::run($vhe->getGroupes(), false);
        }

        ?>
        <tr>
            <td><abbr title="<?php echo $vhe->getTypeIntervention()->getLibelle() ?>"><?php echo $vhe->getTypeIntervention() ?></abbr></td>
            <td><?php echo $heures ?></td>
            <td><?php echo $groupes ?></td>
            <td class="source"><?php echo $vhe->getId() ? $vhe->getSource() : 'Non existant' ?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<?php if ($form): ?>
    <?php echo $this->formSubmit($form->get('submit')); ?>
<?php endif; ?>
<?php echo $this->form()->closeTag() ?>
<?php echo $this->messenger()->addCurrentMessagesFromFlashMessenger() ?>
