<?php

/**
 * @var $this              \Application\View\Renderer\PhpRenderer
 * @var $typeHeures        array
 * @var $typeInterventions array
 */

?>
<nav class="navbar navbar-default">
    <div class="container-fluid">
         <div class="navbar-header">
            <span class="navbar-brand" href="#">Charges d'enseignement</span>
        </div>

         <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

            <form class="navbar-form navbar-left">

                <div class="btn-group" data-toggle="buttons">
                    <label class="btn btn-default" title="Plein écran">
                        <input type="checkbox" class="fullscreen" autocomplete="off"/><span
                                class="glyphicon glyphicon-fullscreen"></span>
                    </label>
                </div>

                <div class="btn-group" role="group">
                    <button type="button" class="btn btn-default zplus" title="Zoomer">
                        <span class="glyphicon glyphicon-zoom-in"></span>
                    </button>
                    <button type="button" class="btn btn-default zmoins" title="Dézoomer">
                        <span class="glyphicon glyphicon-zoom-out"></span>
                    </button>
                    <button type="button" class="btn btn-default zdefaut" title="Zoom par défaut">
                        <span class="glyphicon glyphicon-search"></span>
                    </button>
                </div>

                <div class="btn-group" data-toggle="buttons">
                    <button type="button" class="btn btn-primary sauvegarder" title="Enregistrer les modifications">
                        <span class="glyphicon glyphicon-save"></span> Enregistrer
                    </button>
                </div>

            </form>

        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>
<div class="form-noeud" style="display:none">
    <div class="row">
        <div class="col-md-4">
            <div class="form-group">
                <label for="choix-minimum" title="Choix minimum">Choix min.</label>
                <input type="number" class="form-control" placeholder="Min." id="choix-minimum"/>
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                <label for="choix-maximum" title="Choix maximum">Choix max.</label>
                <input type="number" class="form-control" placeholder="Max." id="choix-maximum"/>
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                <label for="groupes">Assiduité</label>
                <div class="input-group">
                    <input type="number" class="form-control" placeholder="Assiduité" id="assiduite"
                           aria-describedby="add-assiduite">
                    <span class="input-group-addon" id="add-assiduite">%</span>
                </div>
            </div>
        </div>
    </div>

    <div class="form-group" id="effectifs">
        <label for="groupes" title="Effectifs">Effectifs</label>
        <div class="input-group">

            <div class="row">
                <?php foreach ($typeHeures as $tid => $tval): ?>
                    <div class="col-md-<?php echo floor(12 / count($typeHeures)) ?>">
                        <div class="input-group">
                            <input type="number" class="form-control" placeholder="<?php echo $tval ?>"
                                   id="effectifs-<?php echo $tid ?>"
                                   aria-describedby="add-effectifs-<?php echo $tid ?>">
                            <span class="input-group-addon" id="add-effectifs-<?php echo $tid ?>"><?php echo $tval ?></span>
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
    </div>

    <table class="table table-condensed" id="seuils">
        <thead>
        <th>Seuils</th>
        <th>Ouverture</th>
        <th>Dédoublement</th>
        </thead>
        <tbody>
        <?php foreach ($typeInterventions as $tid => $tval): ?>
            <tr>
                <th style="width:20%"><?php echo $tval ?></th>
                <td style="width:40%">
                    <input type="number" class="form-control" id="seuil-ouverture-<?php echo $tid ?>"/>
                </td>
                <td style="width:40%">
                    <input type="number" class="form-control" id="seuil-dedoublement-<?php echo $tid ?>"/>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>

    <div class="text-right">
        <button type="button" class="btn btn-warning" id="btn-cancel"><i class="fa fa-undo"></i> Annuler</button>
        <button type="button" class="btn btn-primary" id="btn-save"><i class="fa fa-save"></i> Enregistrer</button>
    </div>
</div>
<div class="form-lien" style="display:none">
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <label for="actif" title="Lien actif">Actif</label>
                <input type="checkbox" class="form-control" placeholder="Actif" id="actif" value="1"/>
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <label for="poids" title="Poids du lien par rapport aux autres">Poids</label>
                <input type="text" class="form-control" placeholder="Poids" id="poids"/>
            </div>
        </div>
    </div>

    <div class="text-right">
        <button type="button" class="btn btn-warning" id="btn-cancel"><i class="fa fa-undo"></i> Annuler</button>
        <button type="button" class="btn btn-primary" id="btn-save"><i class="fa fa-save"></i> Enregistrer</button>
    </div>
</div>