<?php

/**
 * @var $this                     Application\View\Renderer\PhpRenderer
 * @var $intervenant              \Intervenant\Entity\Db\Intervenant
 * @var $typesVolumesHoraires     array
 */

$this->intervenant($intervenant)->renderTitle('Calcul HETD');

echo $this->vue('formule/details', [
    'intervenant'          => $intervenant->getId(),
    'typesVolumesHoraires' => $typesVolumesHoraires,
]);