<?php
/**
 * @var $this                     \Application\View\Renderer\PhpRenderer
 * @var $modulateurs              \Paiement\Entity\Db\modulateur[]
 * @var $typeModulateurs          \Paiement\Entity\Db\typeModulateur[]
 * @var $typeModulateurStructures \Paiement\Entity\Db\typeModulateurStructure[]
 */

use Application\Provider\Privileges;
use UnicaenApp\Util;

$this->headTitle()->append("Modulateurs des taux horaires");

$canEdit = $this->isAllowed(Privileges::getResourceId(Privileges::MODULATEUR_EDITION));

?>
<h1 class="page-header">Modulateurs des taux horaires
    <?= $anneeId ?></h1>
<?php
foreach ($typeModulateurs as $tm) {
    if ($this->isAllowed($tm, Privileges::MODULATEUR_VISUALISATION)) { ?>
        <div class="card bg-default">
            <div class="card-header">
                <div class="card-title"><?= $tm->getCode() ?>
                    <span style="position:absolute; left: 300px"><?= $tm->getLibelle() ?></span>
                    <span style="position:absolute; right: 50px;">

        <?php if ($canEdit): ?>
                        <a class="ajax-modal" data-event="modulateur-saisie"
                           href="<?= $this->url('modulateur/saisie', ['typeModulateur' => $tm->getId()]) ?>"
                           title="Ajouter un modulateur">
                <i class="fas fa-plus"></i>
            </a>
                        <a class="ajax-modal" data-event="modulateur-saisie"
                           href="<?= $this->url('modulateur/type-modulateur-saisie', ['typeModulateur' => $tm->getId()]) ?>"
                           title="Modifier le type de modulateur">
                        <i class="fas fa-pen-to-square"></i></a>
        <a class="pop-ajax"
           href="<?= $this->url('modulateur/type-modulateur-delete', ['typeModulateur' => $tm->getId()]) ?>"
           title="Supprimer le type de modulateur"
           data-content="<p class='lead text-danger'><strong>Attention!</strong> Confirmez-vous cette suppression ?</p>"
           data-confirm="true"
           data-confirm-button="Oui"
           data-cancel-button="Non"
           data-submit-reload="true"
        >
            <i class="fas fa-trash-can"></i>
        </a>
                </span>
                </div>
                <?php endif ?>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-md-3">
                        <table class="table table-bordered table-xs" style="margin-top:0.5em; margin-bottom:1px;">
                            <?php foreach ($typeModulateurStructures
                                           as $tms) { ?>
                                <?php if (($tm->getId() == $tms->getTypeModulateur()->getId()) && ((!$tms->getAnneeDebut()) || ($tms->getAnneeDebut()->getId() <= $anneeId)) && ((!$tms->getAnneeFin()) || ($tms->getAnneeFin()->getId() >= $anneeId))) { ?>
                                    <tr>
                                        <td>
                                            <?php if (($tms->getAnneeDebut()) || ($tms->getAnneeFin())) {
                                                if (!$tms->getAnneeDebut()) {
                                                    $infoBulle = ' à ' . $tms->getAnneeFin();
                                                } else {
                                                    if (!$tms->getAnneeFin()) {
                                                        $infoBulle = ' de ' . $tms->getAnneeDebut();
                                                    } else $infoBulle = ' de ' . $tms->getAnneeDebut() . ' à ' . $tms->getAnneeFin();
                                                }
                                            } else $infoBulle = ''; ?>
                                            <?php echo ($infoBulle ? '<abbr title="' . $infoBulle . '">' : '') . $tms->getStructure()->getLibelleCourt();
                                            echo($infoBulle ? '</abbr>' : '');
                                            if ($this->isAllowed($tms, Privileges::MODULATEUR_EDITION)){ ?>
                                                <a style="position:relative; left:10px;" class="ajax-modal"
                                                   data-event="modulateur-saisie"
                                                   href="<?= $this->url('modulateur/type-modulateur-structure-saisie', ['typeModulateur' => $tm->getId(), 'typeModulateurStructure' => $tms->getId()]) ?>"
                                                   title="Éditer un type de modulateur pour une structure">
                                                    <i class="fas fa-pen-to-square"></i>
                                                </a>
                                                <a style="position:relative; left:10px;" class=" pop-ajax"
                                                href="<?= $this->url('modulateur/type-modulateur-structure-delete', ['typeModulateurStructure' => $tms->getId()]) ?>"
                                                title="Supprimer le type de modulateur pour la structure"
                                                data-content="<p class='lead text-danger'><strong>Attention!</strong> Confirmez-vous cette suppression ?</p>"
                                                   data-confirm="true"
                                                   data-confirm-button="Oui"
                                                   data-cancel-button="Non"
                                                   data-submit-reload="true"
                                                >
                                                    <i class="fas fa-trash-can"></i>
                                                </a>
                                            <?php } ?>
                                        </td>
                                    </tr>
                                <?php }
                            } ?>
                        </table>
                        <?php if ($canEdit) { ?>
                            <br>
                            <a class="ajax-modal" data-event="modulateur-saisie"
                               href="<?= $this->url('modulateur/type-modulateur-structure-saisie', ['typeModulateur' => $tm->getId()]) ?>"
                               title="Ajouter un type de modulateur pour une structure">
                                <button type="button" class="btn btn-sm btn-primary">Ajouter une structure</button>
                            </a>
                        <?php } ?>
                    </div>
                    <div class="col-md-9">
                        <table class="table table-bordered">
                            <thead>
                            <th>Code</th>
                            <th>Libelle</th>
                            <th>Taux service</th>
                            <th>Taux heures compl.</th>
                            <?php if ($canEdit) { ?>
                                <th>Actions</th>
                            <?php } ?>
                            </thead>
                            <tbody>
                            <?php foreach ($modulateurs as $modu) {
                                if ($tm->getId() == $modu->getTypeModulateur()->getId()) { ?>
                                    <tr>
                                        <td><?= $modu->getCode() ?></td>
                                        <td><?= $modu->getLibelle() ?></td>
                                        <td><?= Util::formattedNumber($modu->getPonderationServiceDu()) ?></td>
                                        <td><?= Util::formattedNumber($modu->getPonderationServiceCompl()) ?></td>
                                        <?php if ($canEdit) { ?>
                                            <td style="text-align:center;width:1px;white-space: nowrap">
                                                <a class="ajax-modal" data-event="modulateur-saisie"
                                                   href="<?= $this->url('modulateur/saisie', ['typeModulateur' => $tm->getId(), 'modulateur' => $modu->getId()]) ?>"
                                                   title="Modifier le modulateur">
                                                    <i class="fas fa-pen-to-square"></i></a>
                                                <a class="pop-ajax"
                                                   href="<?= $this->url('modulateur/delete', ['modulateur' => $modu->getId()]) ?>"
                                                   title="Supprimer le modulateur"
                                                   data-content="<p class='lead text-danger'><strong>Attention!</strong> Confirmez-vous cette suppression ?</p>"
                                                   data-confirm="true"
                                                   data-confirm-button="Oui"
                                                   data-cancel-button="Non"
                                                   data-submit-reload="true"
                                                >
                                                    <i class="fas fa-trash-can"></i>
                                                </a>
                                            </td>
                                        <?php } ?>
                                    </tr>
                                <?php }
                            } ?>
                            </tbody>
                        </table>

                    </div>

                </div>

            </div>
        </div>
        <?php
    }
} ?>
<?php if (($canEdit) && (!$structure)) : ?>
    <a class="btn btn-primary ajax-modal" data-event="modulateur-saisie"
       href="<?= $this->url('modulateur/type-modulateur-saisie', []) ?>"
       title="Ajouter un type de modulateur">
        <i class="fas fa-pen-to-square"></i>
        Ajouter un type de modulateur</a>
    <script type="text/javascript">
        $(function () {
            $("body").on("modulateur-saisie", function (event, data) {
                window.location.reload();
            });
        });
    </script>
<?php endif ?>
