<?php

/**
 * @var $this               \Application\View\Renderer\PhpRenderer
 * @var $form               \Dossier\Form\IntervenantDossierForm
 * @var $intervenant        \Intervenant\Entity\Db\Intervenant
 * @var $intervenantDossier \Dossier\Entity\Db\IntervenantDossier
 * @var $tblDossier         \Dossier\Entity\Db\TblDossier
 */

use Dossier\Assertion\IntervenantDossierAssertion;

$viewIdentite = $this->isAllowed($intervenant, IntervenantDossierAssertion::PRIV_VIEW_IDENTITE);

/**
 * @var \Dossier\Entity\Db\IntervenantDossier $intervenantDossier
 */

//$Dossier = $dossier;

$form->prepare();
$dossierIdentite = $form->get('DossierIdentite');


?>

<!-- Fiedlset Identite -->

<div class="col-md-6">
    <div class="card bg-default">
        <div class="card-header">
            IDENTITÉ
            <?php if (!empty($tblDossier)): ?>
                <?php if (!$intervenantDossier->getTblDossier()->getCompletudeIdentite()): ?>
                    <span class="badge bg-warning text-dark">A compléter</span>
                <?php else: ?>
                    <span class="badge bg-success">Complet</span>
                <?php endif; ?>
            <?php endif; ?>
        </div>
        <div class="card-body">

            <div class="form-group">
                <?= $this->formLabel($dossierIdentite->get('civilite')); ?>
                <div class="input-group cold-md-6 readonly">
                    <?php
                    if (!empty($intervenantDossier->getCivilite())) {
                        echo $intervenantDossier->getCivilite()->getLibelleCourt();
                    }
                    ?>
                </div>
            </div>
            <div class="form-group">
                <?= $this->formLabel($dossierIdentite->get('nomUsuel')); ?>
                <div class="input-group cold-md-6 readonly">
                    <?php
                    if (!empty($intervenantDossier->getNomUsuel())) {
                        echo $intervenantDossier->getNomUsuel();
                    }
                    ?>
                </div>
            </div>
            <div class="form-group">
                <?= $this->formLabel($dossierIdentite->get('nomPatronymique')); ?>
                <div class="input-group cold-md-6 readonly">
                    <?php
                    if (!empty($intervenantDossier->getNomPatronymique())) {
                        echo $intervenantDossier->getNomPatronymique();
                    }
                    ?>
                </div>
            </div>
            <div class="form-group">
                <?= $this->formLabel($dossierIdentite->get('prenom')); ?>
                <div class="input-group cold-md-6 readonly">
                    <?php
                    if (!empty($intervenantDossier->getPrenom())) {
                        echo $intervenantDossier->getPrenom();
                    }
                    ?>
                </div>
            </div>
            <div class="form-group">
                <?= $this->formLabel($dossierIdentite->get('dateNaissance')); ?>
                <div class="input-group cold-md-6 readonly">
                    <?php
                    if (!empty($dossierIdentite->get('dateNaissance')->getValue())) {
                        $dateNaissance          = $dossierIdentite->get('dateNaissance')->getValue();
                        $dateNaissanceFormatted = DateTime::createFromFormat('Y-m-d', $dateNaissance)->format('d/m/Y');
                        echo ($viewIdentite) ? $dateNaissanceFormatted : '**/**/****';
                    }
                    ?>
                </div>
            </div>


        </div>
    </div>
</div>








