<?php

/**
 * @var $this               \Application\View\Renderer\PhpRenderer
 * @var $form               \Dossier\Form\IntervenantDossierForm
 * @var $tblDossier         \Dossier\Entity\Db\TblDossier
 */

use Dossier\Assertion\IntervenantDossierAssertion;


$form->prepare();
$dossierIdentite = $form->get('DossierIdentite');


?>
<!-- Fiedlset Identite -->
<div class="col-md-6">
    <div class="card bg-default">
        <div class="card-header">
            IDENTITÉ
            <?php if (!empty($tblDossier)): ?>
                <?php if (!$tblDossier->getCompletudeIdentite()): ?>
                    <span class="badge bg-warning text-dark">A compléter</span>
                <?php else: ?>
                    <span class="badge bg-success">Complet</span>
                <?php endif; ?>
            <?php endif; ?>
        </div>
        <div class="card-body">

            <?= $this->formControlGroup($dossierIdentite->get('civilite')); ?>
            <?= $this->formControlGroup($dossierIdentite->get('nomUsuel')); ?>
            <?= $this->formControlGroup($dossierIdentite->get('nomPatronymique')); ?>
            <?= $this->formControlGroup($dossierIdentite->get('prenom')); ?>
            <?= $this->formControlGroup($dossierIdentite->get('dateNaissance')); ?>


        </div>
    </div>
</div>







