<?php

/**
 * @var $this               \Application\View\Renderer\PhpRenderer
 * @var $form               \Dossier\Form\IntervenantDossierForm
 * @var $tblDossier         \Dossier\Entity\Db\TblDossier
 */

use Dossier\Assertion\IntervenantDossierAssertion;

$viewAdresse = $this->isAllowed($tblDossier->getIntervenant(), IntervenantDossierAssertion::PRIV_VIEW_ADRESSE);

$form->prepare();
$dossierAdresse = $form->get('DossierAdresse');
?>

<!-- Fiedlset Adresse -->
<div class="col-md-6">
    <div class="card bg-default">
        <div class="card-header">
            ADRESSE
            <?php if (!empty($tblDossier)): ?>
                <?php if (!$tblDossier->getCompletudeAdresse()): ?>
                    <span class="badge bg-warning text-dark">A compléter</span>
                <?php else: ?>
                    <span class="badge bg-success">Complet</span>
                <?php endif; ?>
            <?php endif; ?>
        </div>
        <div class="card-body">
            <?php if (!empty($tblDossier)): ?>
                <?php if (!$tblDossier->getCompletudeAdresse()): ?>
                    <div class="messenger alert alert-secondary ">
                        Pour compléter votre adresse vous devez renseigner au minimum le champ complément d'adresse ou
                        renseigner votre numéro de rue pour
                        avoir une adresse valide.
                    </div>
                <?php endif; ?>
            <?php endif; ?>

            <div class="form-group">
                <?= $this->formLabel($dossierAdresse->get('lieuDit')); ?>
                <div class="input-group cold-md-6 readonly">
                    <?php
                    if (!empty($tblDossier->getDossier()->getAdresseLieuDit())) {
                        echo ($viewAdresse) ? $tblDossier->getDossier()->getAdresseLieuDit() : '*******************';
                    }
                    ?>
                </div>
            </div>

            <div class="row">

                <div class="col-md-2">
                    <?= $this->formLabel($dossierAdresse->get('numero')); ?>

                    <div class="readonly">
                        <?php
                        if (!empty($tblDossier->getDossier()->getAdresseNumero())) {
                            echo ($viewAdresse) ? $tblDossier->getDossier()->getAdresseNumero() : '***';
                        }
                        ?>
                    </div>
                </div>

                <div class="col-md-2">
                    <?= $this->formLabel($dossierAdresse->get('numeroComplement')); ?>

                    <div class="readonly">
                        <?php
                        if (!empty($tblDossier->getDossier()->getAdresseNumeroCompl())) {
                            echo ($viewAdresse) ? $tblDossier->getDossier()->getAdresseNumeroCompl()->getLibelle() : '***';
                        }
                        ?>
                    </div>
                </div>
                <div class="col-md-4">
                    <?= $this->formLabel($dossierAdresse->get('voirie')); ?>

                    <div class="readonly">
                        <?php
                        if (!empty($tblDossier->getDossier()->getAdresseVoirie())) {
                            echo ($viewAdresse) ? $tblDossier->getDossier()->getAdresseVoirie()->getLibelle() : '***';
                        }
                        ?>
                    </div>
                </div>
                <div class="col-md-4">
                    <?= $this->formLabel($dossierAdresse->get('voie')); ?>

                    <div class="readonly">
                        <?php
                        if (!empty($tblDossier->getDossier()->getAdresseVoie())) {
                            echo ($viewAdresse) ? $tblDossier->getDossier()->getAdresseVoie() : '***';
                        }
                        ?>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <?= $this->formLabel($dossierAdresse->get('precisions')); ?>
                <div class="input-group cold-md-6 readonly">
                    <?php
                    if (!empty($tblDossier->getDossier()->getAdressePrecisions())) {
                        echo ($viewAdresse) ? $tblDossier->getDossier()->getAdressePrecisions() : '*******************';
                    }
                    ?>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <?= $this->formLabel($dossierAdresse->get('codePostal')); ?>

                    <div class="readonly">
                        <?php
                        if (!empty($tblDossier->getDossier()->getAdresseCodePostal())) {
                            echo ($viewAdresse) ? $tblDossier->getDossier()->getAdresseCodePostal() : '***';
                        }
                        ?>
                    </div>
                </div>
                <div class="col-md-8">
                    <?= $this->formLabel($dossierAdresse->get('ville')); ?>
                    <div class="readonly">
                        <?php
                        if (!empty($tblDossier->getDossier()->getAdresseCommune())) {
                            echo ($viewAdresse) ? $tblDossier->getDossier()->getAdresseCommune() : '***';
                        }
                        ?>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <?= $this->formLabel($dossierAdresse->get('pays')); ?>
                <div class="input-group cold-md-6 readonly">
                    <?php
                    if (!empty($tblDossier->getDossier()->getAdressePays())) {
                        echo ($viewAdresse) ? $tblDossier->getDossier()->getAdressePays()->getLibelle() : '*******************';
                    }
                    ?>
                </div>
            </div>

        </div>
    </div>
</div>





