<?php

/**
 * @var $this               \Application\View\Renderer\PhpRenderer
 * @var $form               \Dossier\Form\IntervenantDossierForm
 * @var $tblDossier         \Dossier\Entity\Db\TblDossier
 */
$form->prepare();
$dossierStatut = $form->get('DossierStatut');
?>

<style>
    div.rib-part {
        display: inline-block;
        vertical-align: top;
    }

    div.rib-part input {
        width: auto;
    }
</style>

<!-- Fiedlset Insee -->
<div class="col-md-12">
    <div class="card bg-default ">
        <div class="card-header">
            STATUT
            <?php if (!empty($tblDossier)): ?>
                <?php if (!$tblDossier->getCompletudeStatut()): ?>
                    <span class="badge bg-warning text-dark">A compléter</span>
                <?php else: ?>
                    <span class="badge bg-success">Complet</span>
                <?php endif; ?>
            <?php endif; ?>
        </div>
        <div class="card-body">
            <?php
            echo $this->formControlGroup($dossierStatut->get('statut'));

            ?>
        </div>
    </div>
</div>






