<?php

/**
 * @var $this               \Application\View\Renderer\PhpRenderer
 * @var $form               \Dossier\Form\IntervenantDossierForm
 * @var $tblDossier         \Dossier\Entity\Db\TblDossier
 */

use Dossier\Assertion\IntervenantDossierAssertion;

$viewIdentiteComplementaire = $this->isAllowed($tblDossier->getIntervenant(), IntervenantDossierAssertion::PRIV_VIEW_IDENTITE);

$form->prepare();
$dossierIdentiteComplementaire = $form->get('DossierIdentiteComplementaire');


?>
<!-- Fiedlset Identite Complementaire -->
<div class="col-md-6">
    <div class="card bg-default">
        <div class="card-header">
            IDENTITÉ COMPLEMENTAIRE
            <?php if (!empty($tblDossier)): ?>
                <?php if (!$tblDossier->getCompletudeIdentiteComp()): ?>
                    <span class="badge bg-warning text-dark">A compléter</span>
                <?php else: ?>
                    <span class="badge bg-success">Complet</span>
                <?php endif; ?>
            <?php endif; ?>
        </div>
        <div class="card-body">

            <?php
            echo $this->formControlGroup($dossierIdentiteComplementaire->get('paysNaissance'));
            echo $this->formControlGroup($dossierIdentiteComplementaire->get('paysNationalite'));
            echo $this->formControlGroup($dossierIdentiteComplementaire->get('departementNaissance'));
            echo $this->formControlGroup($dossierIdentiteComplementaire->get('villeNaissance'));
            ?>

            <div class="row">
                <div class="col-md-6">
                    <?= $this->formControlGroup($dossierIdentiteComplementaire->get('situationMatrimoniale')); ?>
                </div>
                <div class="col-md-6">
                    <?= $this->formControlGroup($dossierIdentiteComplementaire->get('dateSituationMatrimoniale')); ?>
                </div>
            </div>

        </div>
    </div>
</div>







