<?php

/**
 * @var $this               \Application\View\Renderer\PhpRenderer
 * @var $form               \Dossier\Form\IntervenantDossierForm
 * @var $tblDossier         \Dossier\Entity\Db\TblDossier
 */

use Dossier\Assertion\IntervenantDossierAssertion;

$viewInsee = $this->isAllowed($tblDossier->getIntervenant(), IntervenantDossierAssertion::PRIV_VIEW_INSEE);

/**
 * @var \Dossier\Entity\Db\IntervenantDossier $intervenantDossier
 */

$form->prepare();
$dossierInsee = $form->get('DossierInsee');
?>

<!-- Fiedlset Insee -->
<div class="col-md-6">
    <div class="card bg-default ">
        <div class="card-header">
            INSEE
            <?php if (!empty($tblDossier)): ?>
                <?php if (!$tblDossier->getDossier()->getTblDossier()->getCompletudeInsee()): ?>
                    <span class="badge bg-warning text-dark">A compléter</span>
                <?php else: ?>
                    <span class="badge bg-success">Complet</span>
                <?php endif; ?>
            <?php endif; ?>
        </div>
        <div class="card-body">
            <div class="form-group">
                <?= $this->formLabel($dossierInsee->get('numeroInsee')); ?>
                <div class="input-group cold-md-6 readonly">
                    <?php
                    if (!empty($tblDossier->getDossier()->getNumeroInsee())) {
                        echo ($viewInsee) ? $tblDossier->getDossier()->getNumeroInsee() : '*************************';
                    }
                    ?>
                </div>
            </div>
            <div class="form-group">
                <?= $this->formLabel($dossierInsee->get('numeroInseeEstProvisoire')); ?>
                <div class="input-group cold-md-6 readonly">
                    <?php
                    if ($viewInsee) {
                        echo ($tblDossier->getDossier()->getNumeroInseeProvisoire()) ? 'OUI' : 'NON';
                    }
                    ?>
                </div>
            </div>
        </div>
    </div>
</div>






