<?php

/**
 * @var $this               \Application\View\Renderer\PhpRenderer
 * @var $form               \Dossier\Form\IntervenantDossierForm
 * @var $tblDossier         \Dossier\Entity\Db\TblDossier
 */

$form->prepare();
$dossierStatut = $form->get('DossierStatut');
?>

<style>
    div.rib-part {
        display: inline-block;
        vertical-align: top;
    }

    div.rib-part input {
        width: auto;
    }
</style>

<!-- Fiedlset Insee -->
<div class="col-md-12">
    <div class="card bg-default">
        <div class="card-header">
            STATUT
        </div>
        <div class="card-body">
            <div class="form-group">
                <?= $this->formLabel($dossierStatut->get('statut')); ?>
                <div class="input-group cold-md-6 readonly">
                    <?php
                    if (!empty($tblDossier->getDossier()->getStatut())) {
                        echo $tblDossier->getDossier()->getStatut()->getLibelle();
                    }
                    ?>
                </div>
            </div>
        </div>
    </div>
</div>






