<?php

/**
 * @var $this               \Application\View\Renderer\PhpRenderer
 * @var $form               \Dossier\Form\IntervenantDossierForm
 * @var $tblDossier         \Dossier\Entity\Db\TblDossier
 */
//$Dossier = $dossier;

$form->prepare();
$dossierInsee = $form->get('DossierEmployeur');
?>

<style>
    div.rib-part {
        display: inline-block;
        vertical-align: top;
    }

    div.rib-part input {
        width: auto;
    }
</style>


<!-- Fiedlset Employeur -->
<div class="col-md-6">
    <div class="card bg-default ">
        <div class="card-header">
            EMPLOYEUR PRINCIPAL
            <?php if (!empty($tblDossier)): ?>
                <?php if (!$tblDossier->getCompletudeEmployeur()): ?>
                    <span class="badge bg-warning text-dark">A compléter</span>
                <?php else: ?>
                    <span class="badge bg-success">Complet</span>
                <?php endif; ?>
            <?php endif; ?>
        </div>
        <div class="card-body">
            <div class="well" role="alert">Saissisez les premières lettres de votre employeur ou directement le N° de
                SIRET.
            </div>
            <?= $this->formControlGroup($dossierInsee->get('employeur')); ?>
        </div>
    </div>
</div>








