<?php
/**
 * @var $this               \Application\View\Renderer\PhpRenderer
 * @var $form               \Dossier\Form\IntervenantDossierForm
 * @var $intervenant        \Intervenant\Entity\Db\Intervenant
 * @var $intervenantDossier \Dossier\Entity\Db\IntervenantDossier
 * @var $tblDossier         \Dossier\Entity\Db\TblDossier
 */

use Dossier\Assertion\IntervenantDossierAssertion;

$viewIban = $this->isAllowed($intervenant, IntervenantDossierAssertion::PRIV_VIEW_IBAN);

$form->prepare();
$dossierBancaire = $form->get('DossierBancaire');
?>

<!-- Fiedlset Bancaire -->
<div class="col-md-6">
    <div class="card bg-default ">
        <div class="card-header">
            COORDONNÉES BANCAIRES
            <?php if (!empty($tblDossier)): ?>
                <?php if (!$intervenantDossier->getTblDossier()->getCompletudeBanque()): ?>
                    <span class="badge bg-warning text-dark">A compléter</span>
                <?php else: ?>
                    <span class="badge bg-success">Complet</span>
                <?php endif; ?>
            <?php endif; ?>
        </div>
        <div class="card-body">
            <div class="form-group">
                <?= $this->formLabel($dossierBancaire->get('ribIban')); ?>
                <div class="input-group cold-md-6 readonly">
                    <?php
                    if (!empty($intervenantDossier->getIBAN())) {
                        echo ($viewIban) ? $intervenantDossier->getIBAN() : '**************************';
                    }
                    ?>
                </div>
            </div>
            <div class="form-group">
                <?= $this->formLabel($dossierBancaire->get('ribBic')); ?>
                <div class="input-group cold-md-6 readonly">
                    <?php
                    if (!empty($intervenantDossier->getBIC())) {
                        echo ($viewIban) ? $intervenantDossier->getBIC() : '*************';
                    }
                    ?>
                </div>
            </div>
            <div class="form-group">
                <?= $this->formLabel($dossierBancaire->get('ribHorsSepa')); ?>
                <div class="input-group cold-md-6 readonly">
                    <?php
                    if ($viewIban) {
                        echo ($intervenantDossier->isRibHorsSepa()) ? 'OUI' : 'NON';
                    } else {
                        echo '***';
                    }
                    ?>
                </div>
            </div>
            <?php

            ?>

        </div>
    </div>
</div>




