<?php

/**
 * @var $this               \Application\View\Renderer\PhpRenderer
 * @var $form               \Dossier\Form\IntervenantDossierForm
 * @var $tblDossier         \Dossier\Entity\Db\TblDossier
 */

//$Dossier = $dossier;

$form->prepare();
$dossierContact = $form->get('DossierContact');
?>

<style>
    div.rib-part {
        display: inline-block;
        vertical-align: top;
    }

    div.rib-part input {
        width: auto;
    }
</style>

<!-- Fiedlset Contact -->
<div class="col-md-6 ">
    <div class="card bg-default ">
        <div class="card-header">
            CONTACT
            <?php if (!empty($tblDossier)): ?>
                <?php if (!$tblDossier->getCompletudeContact()): ?>
                    <span class="badge bg-warning text-dark">A compléter</span>
                <?php else: ?>
                    <span class="badge bg-success">Complet</span>
                <?php endif; ?>
            <?php endif; ?>
        </div>
        <div class="card-body">
            <?php
            echo $this->formControlGroup($dossierContact->get('emailEtablissement'));
            echo $this->formControlGroup($dossierContact->get('emailPersonnel'));
            echo $this->formControlGroup($dossierContact->get('telephoneProfessionnel'));
            echo $this->formControlGroup($dossierContact->get('telephonePersonnel'));
            ?>
        </div>
    </div>
</div>





