<?php

/**
 * @var $this               \Application\View\Renderer\PhpRenderer
 * @var $form               \Dossier\Form\IntervenantDossierForm
 * @var $tblDossier         \Dossier\Entity\Db\TblDossier
 */

use Application\Provider\Privileges;

$viewContact = $this->isAllowed($tblDossier->getDossier(), Privileges::DOSSIER_CONTACT_VISUALISATION);

/**
 * @var \Dossier\Entity\Db\IntervenantDossier $intervenantDossier
 */

//$Dossier = $dossier;

$form->prepare();
$dossierContact = $form->get('DossierContact');
?>

<!-- Fiedlset Contact -->
<div class="col-md-6">
    <div class="card bg-default ">
        <div class="card-header">
            CONTACT
            <?php if (!empty($tblDossier)): ?>
                <?php if (!$tblDossier->getDossier()->getTblDossier()->getCompletudeContact()): ?>
                    <span class="badge bg-warning text-dark">A compléter</span>
                <?php else: ?>
                    <span class="badge bg-success">Complet</span>
                <?php endif; ?>
            <?php endif; ?>
        </div>
        <div class="card-body">
            <div class="form-group">
                <?= $this->formLabel($dossierContact->get('emailEtablissement')); ?>
                <div class="input-group cold-md-6 readonly">
                    <?php
                    if (!empty($tblDossier->getDossier()->getEmailPro())) {
                        echo ($viewContact) ? $tblDossier->getDossier()->getEmailPro() : '**********@*****.com';
                    }
                    ?>
                </div>
            </div>
            <div class="form-group">
                <?= $this->formLabel($dossierContact->get('emailPersonnel')); ?>
                <div class="input-group cold-md-6 readonly">
                    <?php
                    if (!empty($tblDossier->getDossier()->getEmailPerso())) {
                        echo ($viewContact) ? $tblDossier->getDossier()->getEmailPerso() : '**********@*****.com';
                    }
                    ?>
                </div>
            </div>
            <div class="form-group">
                <?= $this->formLabel($dossierContact->get('telephoneProfessionnel')); ?>
                <div class="input-group cold-md-6 readonly">
                    <?php
                    if (!empty($tblDossier->getDossier()->getTelPro())) {
                        echo ($viewContact) ? $tblDossier->getDossier()->getTelPro() : '** ** ** ** **';
                    }
                    ?>
                </div>
            </div>
            <div class="form-group">
                <?= $this->formLabel($dossierContact->get('telephonePersonnel')); ?>
                <div class="input-group cold-md-6 readonly">
                    <?php
                    if (!empty($tblDossier->getDossier()->getTelPerso())) {
                        echo ($viewContact) ? $tblDossier->getDossier()->getTelPerso() : '** ** ** ** **';
                    }
                    ?>
                </div>
            </div>
        </div>
    </div>
</div>





