<?php

/**
 * @var $this               \Application\View\Renderer\PhpRenderer
 * @var $form               \Dossier\Form\IntervenantDossierForm
 * @var $tblDossier         \Dossier\Entity\Db\TblDossier
 */

use Dossier\Assertion\IntervenantDossierAssertion;

$viewIdentite = $this->isAllowed($tblDossier->getIntervenant(), IntervenantDossierAssertion::PRIV_VIEW_IDENTITE);

//$Dossier = $dossier;

$form->prepare();
$dossierIdentiteComplementaire = $form->get('DossierIdentiteComplementaire');


?>

<!-- Fiedlset Identite -->

<div class="col-md-6">
    <div class="card bg-default">
        <div class="card-header">
            IDENTITÉ COMPLEMENTAIRE
            <?php if (!empty($tblDossier)): ?>
                <?php if (!$tblDossier->getDossier()->getTblDossier()->getCompletudeIdentiteComp()): ?>
                    <span class="badge bg-warning text-dark">A compléter</span>
                <?php else: ?>
                    <span class="badge bg-success">Complet</span>
                <?php endif; ?>
            <?php endif; ?>

        </div>
        <div class="card-body">


            <div class="form-group">
                <?= $this->formLabel($dossierIdentiteComplementaire->get('paysNaissance')); ?>
                <div class="input-group cold-md-6 readonly">
                    <?php
                    if (!empty($tblDossier->getDossier()->getPaysNaissance())) {
                        echo ($viewIdentite) ? $tblDossier->getDossier()->getPaysNaissance()->getLibelle() : '*******************';
                    }


                    ?>
                </div>
            </div>
            <div class="form-group">
                <?= $this->formLabel($dossierIdentiteComplementaire->get('paysNationalite')); ?>
                <div class="input-group cold-md-6 readonly">
                    <?php
                    if (!empty($tblDossier->getDossier()->getPaysNationalite())) {
                        echo ($viewIdentite) ? $tblDossier->getDossier()->getPaysNationalite()->getLibelle() : '*******************';
                    }

                    ?>
                </div>
            </div>
            <?php if ($tblDossier->getDossier()->getPaysNaissance() && $tblDossier->getDossier()->getPaysNaissance()->getLibelle() == 'FRANCE'): ?>
                <div class="form-group">
                    <?= $this->formLabel($dossierIdentiteComplementaire->get('departementNaissance')); ?>
                    <div class="input-group cold-md-6 readonly">
                        <?php
                        if (!empty($tblDossier->getDossier()->getDepartementNaissance())) {
                            echo ($viewIdentite) ? $tblDossier->getDossier()->getDepartementNaissance()->getLibelle() : '*******************';
                        }
                        ?>
                    </div>
                </div>
            <?php endif; ?>
            <div class="form-group">
                <?= $this->formLabel($dossierIdentiteComplementaire->get('villeNaissance')); ?>
                <div class="input-group cold-md-6 readonly">
                    <?php
                    if (!empty($tblDossier->getDossier()->getCommuneNaissance())) {
                        echo ($viewIdentite) ? $tblDossier->getDossier()->getCommuneNaissance() : '*******************';
                    }


                    ?>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <?= $this->formLabel($dossierIdentiteComplementaire->get('situationMatrimoniale')); ?>
                        <div class="input-group cold-md-6 readonly">
                            <?php
                            if (!empty($tblDossier->getDossier()->getSituationMatrimoniale())) {
                                echo ($viewIdentite) ? $tblDossier->getDossier()->getSituationMatrimoniale()->getLibelle() : '********';
                            }
                            ?>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <?= $this->formLabel($dossierIdentiteComplementaire->get('dateSituationMatrimoniale')); ?>
                        <div class="input-group cold-md-6 readonly">
                            <?php
                            if (!empty($dossierIdentiteComplementaire->get('dateSituationMatrimoniale')->getValue())) {
                                $dateMatrimoniale          = $dossierIdentiteComplementaire->get('dateSituationMatrimoniale')->getValue();
                                $dateMatrimonialeFormatted = DateTime::createFromFormat('Y-m-d', $dateMatrimoniale)->format('d/m/Y');
                                echo ($viewIdentite) ? $dateMatrimonialeFormatted : '**/**/****';
                            }
                            ?>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>








