<?php
/**
 * @var $this               \Application\View\Renderer\PhpRenderer
 * @var $form               \Dossier\Form\IntervenantDossierForm
 * @var $intervenant        \Intervenant\Entity\Db\Intervenant
 * @var $intervenantDossier \Dossier\Entity\Db\IntervenantDossier
 * @var $tblDossier         \Dossier\Entity\Db\TblDossier
 */

$form->prepare();
$dossierBancaire = $form->get('DossierBancaire');
?>

<style>
    div.rib-part {
        display: inline-block;
        vertical-align: top;
    }

    div.rib-part input {
        width: auto;
    }
</style>

<!-- Fiedlset Bancaire -->
<div class="col-md-6">
    <div class="card bg-default ">
        <div class="card-header">
            COORDONNÉES BANCAIRES
            <?php if (!empty($tblDossier)): ?>
                <?php if (!$tblDossier->getCompletudeBanque()): ?>
                    <span class="badge bg-warning text-dark">A compléter</span>
                <?php else: ?>
                    <span class="badge bg-success">Complet</span>
                <?php endif; ?>
            <?php endif; ?>

        </div>
        <div class="card-body">
            <?php

            echo $this->formControlGroup($dossierBancaire->get('ribIban'));
            echo $this->formControlGroup($dossierBancaire->get('ribBic'));
            echo $this->formControlGroup($dossierBancaire->get('ribHorsSepa'));

            ?>

        </div>
    </div>
</div>




