<?php

/**
 * @var $listTypesRessources \Paiement\Entity\Db\TypeRessource[]
 */

use Application\Provider\Privileges;

$this->headTitle()->append($title);

$canEdit = $this->isAllowed(Privileges::getResourceId(Privileges::TYPE_RESSOURCE_EDITION));

?>
<h1 class="page-header">Types de ressources</h1>

<table class="table table-bordered table-sm table-hover">
    <thead>
    <tr>
        <th>Code</th>
        <th>Libellé</th>
        <th>FI</th>
        <th>FA</th>
        <th>FC</th>
        <th>FC Majorée</th>
        <th>Référentiel</th>
        <th>Mission</th>
        <th>Établissement</th>
        <?php if ($canEdit): ?>
            <th>Actions</th>
        <?php endif; ?>
    </tr>
    </thead>
    <tbody class="triables">
    <?php foreach ($listTypesRessources as $type): ?>
        <tr class="champ-triable" data-id="<?= $type->getId() ?>">
            <td>
                <?= $type->getCode() ?>&nbsp;
            </td>
            <td><?= $type->getLibelle() ?></td>
            <td><?= ($type->getFi()) ? 'OUI' : 'NON'; ?></td>
            <td><?= ($type->getFa()) ? 'OUI' : 'NON'; ?></td>
            <td><?= ($type->getFc()) ? 'OUI' : 'NON'; ?></td>
            <td><?= ($type->getPrimes()) ? 'OUI' : 'NON'; ?></td>
            <td><?= ($type->getReferentiel()) ? 'OUI' : 'NON'; ?></td>
            <td><?= ($type->getMission()) ? 'OUI' : 'NON'; ?></td>
            <td><?= ($type->getEtablissement()) ? 'OUI' : 'NON'; ?></td>
            <?php if ($canEdit): ?>
                <td style="text-align:center;width:1px;white-space: nowrap">
                    <a class="ajax-modal"
                       data-event="type-ressource-saisie"
                       href="<?= $this->url('type-ressource/saisie', ['typeRessource' => $type->getId()]) ?>"
                       data-submit-reload="true">
                        <i class="fas fa-pen-to-square"></i></a>
                    <a class="pop-ajax"
                       href="<?= $this->url('type-ressource/delete', ['typeRessource' => $type->getId()]) ?>"
                       title="Supprimer le type de ressource"
                       data-content="<p class='lead text-danger'><strong>Attention!</strong> Confirmez-vous cette suppression ?</p>"
                       data-confirm="true"
                       data-confirm-button="Oui"
                       data-cancel-button="Non"
                       data-submit-reload="true"
                    >
                        <i class="fas fa-trash-can"></i>
                    </a>
                </td>
            <?php endif; ?>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<?php if ($canEdit): ?>
    <a class="btn btn-primary ajax-modal" data-event="type-ressource-saisie"
       href="<?= $this->url('type-ressource/saisie') ?>"
       title="Ajouter un type de ressource">
        <i class="fas fa-plus"></i>
        Ajouter un type de ressource</a>
<?php endif; ?>

<script type="text/javascript">
    $(function () {
        $("body").on("type-ressource-saisie", function (event, data) {
            window.location.reload();
        });
    });
</script>
<style>
    .triables {
        align: left;
    }

    .champ-triable tr {
        align: left;
    }

    .tbl-tis {
        margin-bottom: 1px;
    }
</style>