<?php
/**
 * @var $this  \Application\View\Renderer\PhpRenderer
 * @var $form  \Paiement\Form\TypeRessource\TypeRessourceSaisieForm
 */
echo $this->messenger()->addCurrentMessagesFromFlashMessenger();

echo $this->form()->openTag($form); ?>

<div class="row">
    <div class="col-md-3">
        <?= $this->formControlGroup($form->get('code')); ?>
    </div>
    <div class="col-md-6">
        <?= $this->formControlGroup($form->get('libelle')); ?>
    </div>
</div>
<div class="row">
    <div class="col-md-4"><?= $this->formControlGroup($form->get('fi')); ?></div>
    <div class="col-md-4"><?= $this->formControlGroup($form->get('fa')); ?></div>
    <div class="col-md-4"><?= $this->formControlGroup($form->get('fc')); ?></div>
</div>
<div class="row">
    <div class="col-md-4"><?= $this->formControlGroup($form->get('fc_majore')); ?></div>
    <div class="col-md-4"><?= $this->formControlGroup($form->get('referentiel')); ?></div>
    <div class="col-md-4"><?= $this->formControlGroup($form->get('mission')); ?></div>
</div>
<div class="row">
    <div class="col-md-4"><?= $this->formControlGroup($form->get('etablissement')); ?></div>
</div>
<?= $this->formSubmit($form->get('submit')); ?>
<?= $this->formControlGroup($form->get('security')); ?>

<?= $this->form()->closeTag(); ?>
