<?php

return [
    // Dépendances externes
    'Laminas\Filter',
    'Laminas\Form',
    'Laminas\Hydrator',
    'Laminas\I18n',
    'Laminas\InputFilter',
    'Laminas\Mvc\Plugin\FlashMessenger',
    'Laminas\Navigation',
    'Laminas\Router',
    'Laminas\Session',
    'Laminas\Validator',
    'DoctrineModule',
    'DoctrineORMModule',

    // Bibliothèques Unicaen
    'Unicaen\BddAdmin',
    'Unicaen\Framework',
    'ZfcUser',
    'UnicaenApp',
    'UnicaenAuthentification',
    'UnicaenMail',
    'UnicaenImport',
    'UnicaenTbl',
    'UnicaenSiham',
    'UnicaenVue',
    'UnicaenSignature',

    // Modules de l'application
    'Application',
    'Administration',
    'Agrement',
    'Intervenant',
    'Service',
    'EtatSortie',
    'Chargens',
    'Enseignement',
    'Referentiel',
    'Mission',
    'Paiement',
    'OffreFormation',
    'PieceJointe',
    'Plafond',
    'Indicateur',
    'ExportRh',
    'Dossier',
    'Contrat',
    'Lieu',
    'Formule',
    'Signature',
    'Workflow',
    'Utilisateur',
];