<?php
/**
 * @var $this \Application\View\Renderer\PhpRenderer
 * @var $TypesInterventions \Application\Entity\Db\TypeIntervention[]
 */

use Application\Provider\Privilege\Privileges;
use UnicaenApp\Util;

$this->headTitle()->append("Gestion des types d'interventions");

$canEdit = $this->isAllowed(Privileges::getResourceId(Privileges::TYPE_INTERVENTION_EDITION));

?>
<h1 class="page-header">Gestion des types d'interventions</h1>

<table class="table table-bordered">
    <thead>
    <th>Code</th>
    <th>Libelle</th>
    <th>Taux HETD service</th>
    <th>Taux HETD complémentaire</th>
    <th>Personnalisée</th>
    <th>Visible</th>
    <th>Enseignement</th>
    <?php if ($canEdit) echo '<th>Actions</th>' ?>
    </thead>
    <tbody>
    <?php foreach ($typesInterventions as $ti): ?>
        <tr>
            <td><?php echo $ti->getCode() ?></td>
            <td><?php echo $ti->getLibelle() ?></td>
            <td style="text-align:right;"><?php echo Util::formattedNumber($ti->getTauxHetdService()) ?></td>
            <td style="text-align:right;"><?php echo Util::formattedNumber($ti->getTauxHetdComplementaire()) ?></td>
            <td style="text-align:center;"><?php echo ($ti->getInterventionIndividualisee()?'Oui':'Non') ?></td>
            <td style="text-align:center;"><?php echo ($ti->isVisible()?'Oui':'Non') ?></td>
            <td style="text-align:center;"><?php echo ($ti->getEnseignement()?'Oui':'Non') ?></td>
            <?php if ($canEdit): ?>
                <td style="text-align:center;width:1px;white-space: nowrap">
                    <a class="ajax-modal" data-event="type-intervention-saisie"
                       href="<?php echo $this->url('type-intervention/saisie', ['typeIntervention' => $ti->getId()]) ?>"
                       title="Modifier le type d'intervention">
                        <span class="glyphicon glyphicon-edit"></span></a>
                    <a class="pop-ajax"
                       href="<?php echo $this->url('type-intervention/delete', ['typeIntervention' => $ti->getId()]) ?>"
                       title="Supprimer le type d'intervention"
                       data-content="<p class='lead text-danger'><strong>Attention!</strong> Confirmez-vous cette suppression ?</p>"
                       data-confirm="true"
                       data-confirm-button="Oui"
                       data-cancel-button="Non"
                       data-submit-reload="true"
                    >
                        <span class="glyphicon glyphicon-remove"></span>
                    </a>
                </td>
            <?php endif ?>
        </tr>
    <?php endforeach ?>
    </tbody>
</table>
<?php if ($canEdit): ?>
    <a class="btn btn-primary ajax-modal" data-event="type-intervention-saisie"
       href="<?php echo $this->url('type-intervention/saisie') ?>"
       title="Ajouter un type d'intervention">
        <span class="glyphicon glyphicon-edit"></span>
        Ajouter un type d'intervention</a>

    <script type="text/javascript">
        $(function () {
            $("body").on("type-intervention-saisie", function (event, data) {
                window.location.reload();
            });
        });
    </script>
<?php endif ?>
