<?php

use Application\Entity\Db\TypeInterventionStatut;
use Application\Provider\Privilege\Privileges;
use UnicaenApp\Util;

/**
 * @var $this                              \Application\View\Renderer\PhpRenderer
 * @var $typeInterventionStatuts           TypeInterventionStatut[]
 * @var $typeIntervention TypeIntervention
 * */
echo $this->messenger()->addCurrentMessagesFromFlashMessenger();
$canEdit = $this->isAllowed(Privileges::getResourceId(Privileges::TYPE_INTERVENTION_EDITION));
$this->headTitle()->append("Statuts spécifique pour " .$typeIntervention);
?>


<h1 class="page-header">Statuts spécifiques
    pour <?= $typeIntervention ?>
</h1>

<table class="table table-bordered table-condensed table-extra-condensed table-hover">
    <thead>
    <tr>
        <th>Statut d'intervenant</th>
        <th>Taux HETD service</th>
        <th>Taux HETD complémentaire</th>
        <?php if ($canEdit): ?>
            <th>Actions</th><?php endif; ?>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($typeInterventionStatuts as $tis): ?>
        <tr>
        <td>
            <?= $tis->getStatutIntervenant()->getLibelle() ?>&nbsp;
        </td>
        <td>
            <?= Util::formattedNumber($tis->getTauxHETDService()) ?>
        </td>
        <td>
            <?= Util::formattedNumber($tis->getTauxHETDComplementaire()) ?>
        </td>
        <?php if ($canEdit): ?>
            <td>
                <a class="ajax-modal"
                   data-min-width="400"
                   data-event="type-intervention-statut"
                   href="<?= $this->url('type-intervention/statut-saisie', ['typeIntervention' => $tis->getTypeIntervention()->getId(),'typeInterventionStatut' => $tis->getId()]); ?>"
                   data-submit-reload="false">
                    <span class="glyphicon glyphicon-edit"></span></a>
                <a class="ajax-modal"
                   data-event="type-intervention-statut"
                   href="<?= $this->url('type-intervention/statut-delete', ['typeInterventionStatut' => $tis->getId()]) ?>"
                   title="Supprimer le type d'intervention"
                   data-content="<p class='lead text-danger'><strong>Attention!</strong> Confirmez-vous cette suppression ?</p>"
                   data-confirm="true" data-confirm-button="Oui"
                   data-cancel-button="Non"
                   data-submit-reload="false">
                    <span class="glyphicon glyphicon-trash"></span></a>
            </td>

        <?php endif; ?>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<?php if ($canEdit) : ?>
    <a class="btn btn-primary ajax-modal"
       data-event="type-intervention-statut"
       href="<?= $this->url('type-intervention/statut-saisie', ['typeIntervention' => $typeIntervention->getId()]) ?>"
       title="Ajouter un statut spécifique pour le type d'intervention"
       onclick="window.close()"
       data-submit-reload="false">
        Ajouter un statut pour le type d'intervention</a>
<?php endif; ?>

<script type="text/javascript">
        $(function () {
            $("body").on("type-intervention-statut", function (event, data) {
            });
        });

</script>