<?php
/**
 * @var $this  \Application\View\Renderer\PhpRenderer
 * @var $form  \Application\Form\CcActivite\CcActiviteSaisieForm
 */
echo $this->messenger()->addCurrentMessagesFromFlashMessenger();

echo $this->form()->openTag($form); ?>

<div class="row">
    <div class="col-md-3">
        <?= $this->formControlGroup($form->get('code')); ?>
    </div>
    <div class="col-md-9">
        <?= $this->formControlGroup($form->get('libelle')); ?>
    </div>
</div>

<div class="row">
    <div class="col-md-4">
        <?= $this->formControlGroup($form->get('fi')); ?>
    </div>
    <div class="col-md-4">
        <?= $this->formControlGroup($form->get('fa')); ?>
    </div>
    <div class="col-md-4">
        <?= $this->formControlGroup($form->get('fc')); ?>
    </div>

</div>

<div class="row">
    <div class="col-md-4">
        <?= $this->formControlGroup($form->get('fc-majorees')); ?>
    </div>
    <div class="col-md-4">
        <?= $this->formControlGroup($form->get('referentiel')); ?>
    </div>

</div>
<?= $this->formControlGroup($form->get('security')); ?>
<?= $this->formSubmit($form->get('submit')); ?>
<?= $this->form()->closeTag(); ?>
