<?php

use Application\Assertion\ContratAssertion;
use Application\Provider\Privilege\Privileges;

/**
 * @var $this     \Application\View\Renderer\PhpRenderer
 * @var $contrat  \Application\Entity\Db\Contrat
 * @var $services \Application\Entity\Db\Service[]
 */

$validation     = $contrat->getValidation();
$retourSigne    = $contrat->getDateRetourSigne();
$dateEnvoiEmail = $contrat->getDateEnvoiEmail();
$uploader       = $this->uploader();

$urlExport = $this->isAllowed($contrat, ContratAssertion::PRIV_EXPORT)
    ? $this->url('contrat/exporter', ['contrat' => $contrat->getId()]) // oui car on peut le voir!!
    : null;

$urlLister = $this->isAllowed($contrat, ContratAssertion::PRIV_LISTER_FICHIERS)
    ? $this->url('contrat/lister-fichier', ['contrat' => $contrat->getId()], [], true)
    : null;

$urlEmail = $this->isAllowed($contrat, Privileges::CONTRAT_ENVOI_EMAIL)
    ? $this->url('contrat/envoyer-mail', ['contrat' => $contrat->getId()], ['modal' => 1]) . '?modal=1'
    : null;


$urlValidation = $this->isAllowed($contrat, Privileges::CONTRAT_VALIDATION)
    ? $this->url('contrat/valider', ['contrat' => $contrat->getId()])
    : null;

$urlDevalidation = $this->isAllowed($contrat, Privileges::CONTRAT_DEVALIDATION)
    ? $this->url('contrat/devalider', ['contrat' => $contrat->getId()])
    : null;

$urlSaisieRetour = $this->isAllowed($contrat, Privileges::CONTRAT_SAISIE_DATE_RETOUR_SIGNE)
    ? $this->url('contrat/saisir-retour', ['contrat' => $contrat->getId()])
    : null;

$urlAjouter = $this->isAllowed($contrat, ContratAssertion::PRIV_AJOUTER_FICHIER)
    ? $this->url('contrat/deposer-fichier', ['contrat' => $contrat->getId()], [], true)
    : null;

$urlSuppression = $this->isAllowed($contrat, Privileges::CONTRAT_SUPPRESSION)
    ? $this->url('contrat/supprimer', ['contrat' => $contrat->getId()])
    : null;

$disableEmail = (empty($emailIntervenant)) ? true : false;

if ($urlAjouter) {
    $uploader->setUrl($urlAjouter);
}

$panel = ($retourSigne !== null) ? 'success' : ($validation ? 'info' : 'default');

?>
<div class="contrat panel panel-<?= $panel ?>" id="contrat-<?= $contrat->getId() ?>">
    <div class="panel-heading panel-heading-h3">
        <?php if ($urlExport && $urlEmail): ?>
            <span class="pull-right">
                <?php if ($disableEmail): ?>
                    <a class="disabled btn btn-<?= $panel ?>" href="<?= $urlEmail ?>"
                       title="L'intervenant du contrat n'a pas renseigné son email.">
                <?php endif; ?>
                        <?php if (!$disableEmail): ?>
                    <a data-event="envoi-mail-contrat" class="ajax-modal btn btn-<?= $panel ?>"
                       title="Envoyer le contrat par mail"

                       href="<?= $urlEmail ?>">
                <?php endif; ?>
                <span class="glyphicon glyphicon-send"></span> Envoyer par mail
            </a>
            </span>
        <?php endif; ?>
        <!-- Lien de téléchargement du fichier -->
        <?php if ($urlExport): ?>

            <span class="pull-right">
            <a class="btn btn-<?= $panel ?>" href="<?= $urlExport ?>" title="Exporter le contrat/avenant au format PDF">
                <span class="glyphicon glyphicon-export"></span> Exporter en PDF
            </a>
            </span>
        <?php endif; ?>
        <!-- Lien de téléchargement du fichier -->

        <h3><?= $contrat->toString() ?> - <?= $contrat->getStructure() ?></h3>
    </div>

    <div class="panel-body">
        <!-- Informations -->
        <ul style="list-style-type: none">
            <li><span class="glyphicon glyphicon-thumbs-up"></span> Créé
                le <?= $contrat->getHistoCreation()->format(\Application\Constants::DATE_FORMAT) ?>
                par <?= $this->utilisateur($contrat->getHistoCreateur()) ?></li>
            <?php if ($validation): ?>
                <li><span class="glyphicon glyphicon-thumbs-up"></span> Validé
                    le <?= $validation->getHistoCreation()->format(\Application\Constants::DATE_FORMAT) ?>
                    par <?= $this->utilisateur($validation->getHistoCreateur()) ?></li>
            <?php endif; ?>
            <?php if ($dateEnvoiEmail): ?>
                <li><span class="glyphicon glyphicon-thumbs-up"></span> Envoyé par email
                    le <?= $dateEnvoiEmail->format(\Application\Constants::DATE_FORMAT) ?>
                </li>
            <?php endif; ?>
            <?php if ($retourSigne): ?>
                <li><span class="glyphicon glyphicon-thumbs-up"></span> Retourné signé
                    le <?= $retourSigne->format(Application\Constants::DATE_FORMAT) ?></li>
            <?php endif ?>
        </ul>

        <!-- Upload de fichiers -->
        <?php if ($urlLister): ?>
            <div class="upload-container">
                <hr/>
                <div class="row">
                    <!-- Liste des fichiers déposés -->
                    <div class="col-md-6">
                        <?= $uploader->renderUploadedFiles($urlLister) ?>
                    </div>
                    <!-- formulaire de dépôt -->
                    <?php if ($urlAjouter): ?>
                        <div class="col-md-6">
                            <?= $uploader->renderForm() ?>
                        </div>
                    <?php endif; ?>
                </div>
            </div>
        <?php endif; ?>

        <!-- Liste des enseignements concernés -->
        <div>
            <hr/>
            <a title="Cliquez pour afficher/masquer les enseignements concernés"
               href="#details-enseignements-contrat-<?= $contrat->getId() ?>"
               role="button"
               aria-expanded="false"
               aria-controls="details-enseignements-contrat-<?= $contrat->getId() ?>"
               data-toggle="collapse"
            >Enseignements concernés
                <small>(cliquez pour afficher/cacher)</small>
            </a>
            <div class="collapse" id="details-enseignements-contrat-<?= $contrat->getId() ?>">
                <?= $this->serviceListe($services)->setReadonly(true)->setColumnVisibility('structure-ens', false)->render(); ?>
            </div>
        </div>
    </div>

    <?php if ($urlValidation || $urlSaisieRetour || $urlDevalidation || $urlSuppression): ?>
        <div class="panel-footer">
            <!-- Actions -->
            <?php if ($urlValidation): ?>
                <a
                        href="<?= $urlValidation ?>"
                        class="btn btn-primary pop-ajax"
                        title="Valider les données personnelles"
                        data-content="Confirmez-vous cette validation ?"
                        data-confirm="true"
                        data-confirm-button="Je confirme"
                        data-cancel-button="Non"
                        data-submit-reload="true"
                >
                    <span class="glyphicon glyphicon-thumbs-up"></span> Valider
                </a>
            <?php endif; ?>

            <?php if ($urlSaisieRetour): ?>
                <a href="<?= $urlSaisieRetour ?>" class="btn btn-primary pop-ajax"
                   data-submit-reload="true">
                    <span
                            class="glyphicon glyphicon-calendar"></span> <?= $contrat->getDateRetourSigne() ? 'Modifier' : 'Saisir' ?>
                    la date de retour signé
                </a>
            <?php endif; ?>

            <?php if ($urlDevalidation): ?>
                <a
                        href="<?= $urlDevalidation ?>"
                        class="btn btn-danger pop-ajax"
                        data-submit-reload="true"
                        data-content="<p class='lead text-danger'><strong>Attention!</strong> Confirmez-vous cette dévalidation ?</p>"
                        data-confirm="true"
                        data-confirm-button="Oui"
                        data-cancel-button="Non"
                >
                    <span class="glyphicon glyphicon-thumbs-down"></span> Dévalider
                </a>
            <?php endif; ?>

            <?php if ($urlSuppression): ?>
                <a
                        href="<?= $urlSuppression ?>"
                        class="btn btn-danger pop-ajax"
                        data-content="<p class='lead text-danger'><strong>Attention!</strong> Confirmez-vous la suppression <?= lcfirst($contrat->toString(true, true)) ?> ?</p>"
                        data-confirm="true"
                        data-confirm-button="Oui"
                        data-cancel-button="Non"
                        data-submit-reload="true"
                >
                    <i class="fa-solid fa-trash-can"></i> Supprimer
                </a>
            <?php endif; ?>
        </div>
    <?php endif; ?>
</div>