<?php 
$contrats    = $this->contrats;
$intervenant = $this->intervenant; /* @var $intervenant \Application\Entity\Db\Intervenant */
$role        = $this->role;
?>

<style>
    th.structure, td.structure { max-width: 100px; }
</style>

<?php if ($contrats): ?>
<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <th class="structure">Composante d'enseignement</th>
            <th>Contrat ou avenant</th>
            <th>Retour<br />signé</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($contrats as $contrat): /* @var $contrat \Application\Entity\Db\Contrat */ ?>
        <tr>
            <?php 
            $contratToString = $contrat->toString(true, true);
            $urlExport       = $this->url('contrat/exporter',  array('contrat' => $contrat->getId()));
            $urlValidation   = $this->url('contrat/valider',   array('contrat' => $contrat->getId()));
            $urlDevalidation = $this->url('contrat/devalider', array('contrat' => $contrat->getId()));
            ?>
            <td class="structure"><?php echo $contrat->getStructure() ?></td>
            <td>
                <p>
                    <strong><?php echo $contrat ?></strong> créé le 
                    <?php echo $contrat->getHistoModification()->format(\Common\Constants::DATE_FORMAT) ?> par 
                    <?php echo $this->mailto($contrat->getHistoModificateur()) ?>
                    <span class="pull-right">
                        <a href="<?php echo $urlExport ?>"><span class="glyphicon glyphicon-export"></span> Exporter en PDF</a>
                    </span>
                </p>
                <p>
                    <?php if (($validation = $contrat->getValidation())): ?>
                        <?php echo $this->messenger()->setMessage((string)$this->validationDl($validation), 'success') ?>
                        <?php if ($role instanceof Application\Acl\ComposanteDbRole && $contrat->estUnAvenant()): ?>
                            <a href="<?php echo $urlDevalidation ?>" class="btn btn-primary ajax-modal"
                               data-event="event-validation-suppr">Suppimer la validation <?php echo $contrat->toString(true, true) ?></a>
                        <?php endif; ?>
                    <?php else: ?>
                        <?php if ($role instanceof Application\Acl\ComposanteDbRole): ?>
                            <a href="<?php echo $urlValidation ?>" class="btn btn-primary ajax-modal"
                               data-event="event-contrat-validation">Valider <?php echo $contrat->toString(true) ?></a>
                        <?php endif; ?>
                    <?php endif; ?>
                </p>
                <p>
                    <?php echo $this->partial('application/contrat/partial/services-contrat', array(
                            'label'    => "Enseignements ayant déclenché la création de ce contrat/avenant :",
                            'contrat'  => $contrat,
                            'services' => $this->services[$contrat->getId()])) ?>
                </p>
            </td>
            <td><?php echo ($d = $contrat->getDateRetourSigne()) ? $d->format(Common\Constants::DATETIME_FORMAT) : null ?></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<?php else: ?>
<p>Aucun contrat/avenant trouvé.</p>
<?php endif; ?>


<script>
    $("body").on("event-contrat-validation event-validation-suppr", function(event, data) {
        event.div.modal('hide'); // ferme la fenêtre modale
        window.location.reload();
    });
</script>