<?php
/**
 * Generated by UnicaenCode
 * Commande : ose-code  module='PieceJointe'
 */
return [
    'PieceJointe\Assertion\PiecesJointesAssertion'                      => __DIR__ . '/src/Assertion/PiecesJointesAssertion.php',
    'PieceJointe\Controller\Factory\PieceJointeControllerFactory'       => __DIR__ . '/src/Controller/Factory/PieceJointeControllerFactory.php',
    'PieceJointe\Controller\PieceJointeController'                      => __DIR__ . '/src/Controller/PieceJointeController.php',
    'PieceJointe\Entity\Db\PieceJointe'                                 => __DIR__ . '/src/Entity/Db/PieceJointe.php',
    'PieceJointe\Entity\Db\TblPieceJointe'                              => __DIR__ . '/src/Entity/Db/TblPieceJointe.php',
    'PieceJointe\Entity\Db\TblPieceJointeDemande'                       => __DIR__ . '/src/Entity/Db/TblPieceJointeDemande.php',
    'PieceJointe\Entity\Db\TblPieceJointeFournie'                       => __DIR__ . '/src/Entity/Db/TblPieceJointeFournie.php',
    'PieceJointe\Entity\Db\TypePieceJointe'                             => __DIR__ . '/src/Entity/Db/TypePieceJointe.php',
    'PieceJointe\Entity\Db\TypePieceJointeStatut'                       => __DIR__ . '/src/Entity/Db/TypePieceJointeStatut.php',
    'PieceJointe\Form\Factory\ModifierTypePieceJointeStatutFormFactory' => __DIR__ . '/src/Form/Factory/ModifierTypePieceJointeStatutFormFactory.php',
    'PieceJointe\Form\Factory\TypePieceJointeSaisieFormFactory'         => __DIR__ . '/src/Form/Factory/TypePieceJointeSaisieFormFactory.php',
    'PieceJointe\Form\ModifierTypePieceJointeStatutForm'                => __DIR__ . '/src/Form/ModifierTypePieceJointeStatutForm.php',
    'PieceJointe\Form\TypePieceJointeSaisieForm'                        => __DIR__ . '/src/Form/TypePieceJointeSaisieForm.php',
    'PieceJointe\Hydrator\TypePieceJointeStatutHydrator'                => __DIR__ . '/src/Hydrator/TypePieceJointeStatutHydrator.php',
    'PieceJointe\Module'                                                => __DIR__ . '/Module.php',
    'PieceJointe\Service\Factory\PieceJointeServiceFactory'             => __DIR__ . '/src/Service/Factory/PieceJointeServiceFactory.php',
    'PieceJointe\Service\Factory\TblPieceJointeServiceFactory'          => __DIR__ . '/src/Service/Factory/TblPieceJointeServiceFactory.php',
    'PieceJointe\Service\Factory\TypePieceJointeServiceFactory'         => __DIR__ . '/src/Service/Factory/TypePieceJointeServiceFactory.php',
    'PieceJointe\Service\Factory\TypePieceJointeStatutServiceFactory'   => __DIR__ . '/src/Service/Factory/TypePieceJointeStatutServiceFactory.php',
    'PieceJointe\Service\PieceJointeService'                            => __DIR__ . '/src/Service/PieceJointeService.php',
    'PieceJointe\Service\TblPieceJointeService'                         => __DIR__ . '/src/Service/TblPieceJointeService.php',
    'PieceJointe\Service\TypePieceJointeService'                        => __DIR__ . '/src/Service/TypePieceJointeService.php',
    'PieceJointe\Service\TypePieceJointeStatutService'                  => __DIR__ . '/src/Service/TypePieceJointeStatutService.php',
];