<?php
/**
 * Generated by UnicaenCode
 * Commande : ose-code  module='PieceJointe'
 */
return [
    'piece-jointe/piece-jointe/lister'                            => __DIR__ . '/view/piece-jointe/piece-jointe/lister.phtml',
    'piece-jointe/piece-jointe/configuration'                     => __DIR__ . '/view/piece-jointe/piece-jointe/configuration.phtml',
    'piece-jointe/piece-jointe/archiver'                          => __DIR__ . '/view/piece-jointe/piece-jointe/archiver.phtml',
    'piece-jointe/piece-jointe/type-piece-jointe-saisie'          => __DIR__ . '/view/piece-jointe/piece-jointe/type-piece-jointe-saisie.phtml',
    'piece-jointe/piece-jointe/modifier-type-piece-jointe-statut' => __DIR__ . '/view/piece-jointe/piece-jointe/modifier-type-piece-jointe-statut.phtml',
    'piece-jointe/piece-jointe/validation'                        => __DIR__ . '/view/piece-jointe/piece-jointe/validation.phtml',
    'piece-jointe/piece-jointe/infos'                             => __DIR__ . '/view/piece-jointe/piece-jointe/infos.phtml',
    'piece-jointe/piece-jointe/partial/piece-jointe'              => __DIR__ . '/view/piece-jointe/piece-jointe/partial/piece-jointe.phtml',
    'piece-jointe/piece-jointe/partial/mail'                      => __DIR__ . '/view/piece-jointe/piece-jointe/partial/mail.phtml',
    'piece-jointe/piece-jointe/partial/tpjs-cell'                 => __DIR__ . '/view/piece-jointe/piece-jointe/partial/tpjs-cell.phtml',
    'piece-jointe/piece-jointe/partial/tpjs-ligne'                => __DIR__ . '/view/piece-jointe/piece-jointe/partial/tpjs-ligne.phtml',
    'piece-jointe/piece-jointe/refuser'                           => __DIR__ . '/view/piece-jointe/piece-jointe/refuser.phtml',
    'piece-jointe/piece-jointe/index'                             => __DIR__ . '/view/piece-jointe/piece-jointe/index-new.phtml',
    'piece-jointe/piece-jointe/type-piece-jointe-statut'          => __DIR__ . '/view/piece-jointe/piece-jointe/type-piece-jointe-statut.phtml',
];