<?php

/**
 * @var $this \Application\View\Renderer\PhpRenderer
 */

use Laminas\View\Helper\Navigation as NavigationHelper;

if (isset($_SERVER['HTTP_X_REQUESTED_WITH']) && strtolower($_SERVER['HTTP_X_REQUESTED_WITH']) === 'xmlhttprequest') {
    echo $this->content;
    return;
}


$version = $this->appInfos()->getConfig()->get('version');

echo "<!DOCTYPE html>";
?>

<html lang="fr">
<head>
    <link href="" media="all" rel="stylesheet" type="text/css">
    <!-- Meta -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Application d'Organisation des services d'enseignement">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <?= $this->headTitle($this->appInfos()->nom)->setSeparator(' - ')->setAutoEscape(true) . "\n"; ?>

    <!-- Dépendances -->
    <link href="<?= $this->basePath('/ext/open-sans-gh-pages/open-sans.css') ?>" media="all" rel="stylesheet"
          type="text/css">
    <link href="<?= $this->basePath('/vendor/font-awesome/css/all.min.css') ?>" media="all" rel="stylesheet"
          type="text/css">


    <!-- CSS générale à l'application -->
    <link href="<?= $this->basePath('/css/app.css?v=' . $version) ?>" media="all" rel="stylesheet" type="text/css">

    <!-- Autres links ajoutés dynamiquement -->
    <?= $this->headLink(); ?>

    <!-- Eléments de mise en forme (CSS et icônes) chargés depuis la config OSE -->
    <?php if ($customCss = (AppAdmin::config()['etablissement']['css'] ?? null)) : ?>
        <link href="<?= $customCss ?>" media="all" rel="stylesheet" type="text/css">
    <?php endif; ?>

    <?php
    $icons = AppAdmin::config()['etablissement']['icons'] ?? [];

    foreach ($icons as $icon) {
        // Protection pour éviter d'appeler d'anciennes icônes Unicaen
        $forbidden = 'www.unicaen.fr/images/favicon/';
        if (isset($icon['href']) && str_contains($icon['href'], $forbidden)) {
            continue;
        }
        $ihtml = "\t<link rel=\"icon\" ";
        foreach ($icon as $attrName => $attrVal) {
            $ihtml .= $attrName . '="' . $attrVal . '" ';
        }
        $ihtml .= "/>\n";
        echo $ihtml;
    }
    ?>

    <!-- Scripts globaux -->
    <script type="text/javascript" src="<?= $this->basePath('/vendor/jquery/jquery.min.js') ?>"></script>
    <script type="text/javascript" src="<?= $this->basePath('/ext/jquery-ui-1.14.1/jquery-ui.min.js') ?>"></script>
    <script type="text/javascript" src="<?= $this->basePath('/js/util.js?v=sss' . $version) ?>"></script>
    <?= $this->vite(); ?>
    <?= $this->headScript(); ?>

</head>

<body class="<?= AppAdmin::env() ?> p-0">

<?php require __DIR__ . '/partial/navbar.phtml'; ?>
<?php require __DIR__ . '/partial/content.phtml'; ?>
<?php require __DIR__ . '/partial/footer.phtml'; ?>


<!-- Scripts (dépendances) -->
<script type="text/javascript"
        src="<?= $this->basePath('/vendor/bootstrap/js/bootstrap.bundle.min.js') ?>"></script>
<script type="text/javascript" src="<?= $this->basePath('/ext/jquery.form-3.51.js') ?>"></script>
<script type="text/javascript"
        src="<?= $this->basePath('/vendor/bootstrap-select/js/bootstrap-select.js') ?>"></script>
<script type="text/javascript"
        src="<?= $this->basePath('/vendor/bootstrap-select/js/i18n/defaults-fr_FR.js') ?>"></script>

<!-- Scripts de l'application -->
<script type="text/javascript" src="<?= $this->basePath('/js/unicaen.js?v=' . $version) ?>"></script>
<script type="text/javascript" src="<?= $this->basePath('/js/widget-initializer.js?v=' . $version) ?>"></script>
<script type="text/javascript" src="<?= $this->basePath('/js/intranavigator.js?v=' . $version) ?>"></script>
<script type="text/javascript" src="<?= $this->basePath('/js/pop-ajax.js?v=' . $version) ?>"></script>
<script type="text/javascript" src="<?= $this->basePath('/js/mod-ajax.js?v=' . $version) ?>"></script>
<script type="text/javascript" src="<?= $this->basePath('/js/tab-ajax.js?v=' . $version) ?>"></script>
<script type="text/javascript" src="<?= $this->basePath('/js/app.js?v=' . $version) ?>"></script>
<script type="text/javascript" src="<?= $this->basePath('/js/paiement.js?v=' . $version) ?>"></script>

<!-- Scripts chargés dynamiquement -->
<?= $this->inlineScript(); ?>

</body>
</html>