<?php

/**
 * @var $this             \Application\View\Renderer\PhpRenderer
 */

use Laminas\View\Helper\Navigation as NavigationHelper;

/** @var NavigationHelper $navigationHelper */
$navigationHelper = $this->navigation('navigation');
$pages            = $navigationHelper->getContainer();

$version = $this->appInfos()->getConfig()->get('version');

echo $this->doctype();
?>

<html lang="fr">
<head>
    <link href="" media="all" rel="stylesheet" type="text/css">
    <!-- Meta -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Application d'Organisation des services d'enseignement">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <?= $this->headTitle($this->appInfos()->nom)->setSeparator(' - ')->setAutoEscape(true) . "\n"; ?>

    <!-- Dépendances -->
    <link href="<?= $this->basePath('/vendor/jquery-ui-1.12.1/jquery-ui.min.css') ?>" media="all" rel="stylesheet" type="text/css">
    <link href="<?= $this->basePath('/vendor/open-sans-gh-pages/open-sans.css') ?>" media="all" rel="stylesheet" type="text/css">
    <link href="<?= $this->basePath('/vendor/font-awesome-6.0.0/css/all.min.css') ?>" media="all" rel="stylesheet" type="text/css">
    <link href="<?= $this->basePath('/vendor/bootstrap-select-1.14.0/css/bootstrap-select.min.css') ?>" media="all" rel="stylesheet" type="text/css">
    <link href="<?= $this->basePath('/vendor/DataTables-1.12.1/css/dataTables.bootstrap5.min.css') ?>" media="all" rel="stylesheet" type="text/css">


    <!-- CSS générale à l'application -->
    <link href="<?= $this->basePath('/css/app.css?v=' . $version) ?>" media="all" rel="stylesheet" type="text/css">

    <!-- Autres links ajoutés dynamiquement -->
    <?= $this->headLink(); ?>

    <!-- Eléments de mise en forme (CSS et icônes) chargés depuis la config OSE -->
    <?php if ($customCss = AppConfig::get('etablissement', 'css')) : ?>
        <link href="<?= $customCss ?>" media="all" rel="stylesheet" type="text/css">
    <?php endif; ?>

    <?php
    $icons = AppConfig::get('etablissement', 'icons');
    if (is_array($icons)) {
        foreach ($icons as $icon) {
            $ihtml = "\t<link rel=\"icon\" ";
            foreach ($icon as $attrName => $attrVal) {
                $ihtml .= $attrName . '="' . $attrVal . '" ';
            }
            $ihtml .= "/>\n";
            echo $ihtml;
        }
    }
    ?>

    <!-- Scripts globaux -->
    <script type="text/javascript" src="<?= $this->basePath('/vendor/jquery-3.6.0.min.js') ?>"></script>
    <script type="text/javascript" src="<?= $this->basePath('/vendor/jquery-ui-1.12.1/jquery-ui.min.js') ?>"></script>
    <script type="text/javascript" src="<?= $this->basePath('/vendor/axios/axios.min.js') ?>"></script>
    <script type="text/javascript" src="<?= $this->basePath('/js/util.js?v=' . $version) ?>"></script>
    <?= $this->vite()->head(); ?>
    <?= $this->headScript(); ?>
</head>

<body class="<?= AppConfig::getEnv() ?> p-0" data-base-url="<?= $this->url('home') ?>">


<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <?= $this->appLink($this->appInfos()->nom) ?>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <?= $navigationHelper
                ->menu($pages)
                ->setUlClass('navbar-nav me-auto mb-2 mb-lg-0')
                ->setPartial('layout/menu-principal.phtml'); ?>
            <?= $this->appConnection(); ?>
        </div>
    </div>
</nav>


<div id="contenu-principal" class="container">
    <?php $pages->rewind();
    if ($menuSecondaire = $navigationHelper->menuSecondaire($pages)->render()): ?>
        <div class="row">
            <div id="sidebar" class="col-xs-6 col-md-2" role="navigation">
                <?= $menuSecondaire; ?>
            </div>
            <div id="content" class="col-xs-12 col-md-10">
                <?= $this->content; ?>
            </div>
        </div>
    <?php else: ?>
        <?= $this->content; ?>
    <?php endif; ?>
</div>


<nav id="footer" class="nav justify-content-center">
    <a title="<?= AppConfig::get('etablissement', 'logoDescription') ?>" class="nav-link lien-univ"
       href="<?= AppConfig::get('etablissement', 'logoUri') ?>"><?= AppConfig::get('etablissement', 'nom') ?></a>
    <a title="&#xC0;propos de cette application" class="nav-link apropos" href="<?= $this->basePath('apropos') ?>">À propos</a>
    <a title="Contact concernant l'application" class="nav-link contact" href="<?= $this->basePath('contact') ?>">Contact</a>
    <a title="Page de navigation au sein de l'application" class="nav-link plan" href="<?= $this->basePath('plan') ?>">Plan de navigation</a>
    <a title="Mentions légales" class="nav-link ml" href="<?= AppConfig::get('etablissement', 'mentionsLegales') ?>">Mentions légales</a>
    <a title="Vie privée" class="nav-link il" href="<?= AppConfig::get('etablissement', 'viePrivee') ?>">Vie privée</a>
</nav>


<!-- Scripts (dépendances) -->
<script type="text/javascript" src="<?= $this->basePath('/vendor/bootstrap-5.0.2/dist/js/bootstrap.bundle.js') ?>"></script>
<script type="text/javascript" src="<?= $this->basePath('/vendor/jquery.form-3.51.js') ?>"></script>
<script type="text/javascript" src="<?= $this->basePath('/vendor/bootstrap-select-1.14.0/js/bootstrap-select.min.js') ?>"></script>
<script type="text/javascript" src="<?= $this->basePath('/vendor/bootstrap-select-1.14.0/js/i18n/defaults-fr_FR.js') ?>"></script>

<!-- Scripts de l'application -->
<script type="text/javascript" src="<?= $this->basePath('/js/unicaen.js?v=' . $version) ?>"></script>
<script type="text/javascript" src="<?= $this->basePath('/js/widget-initializer.js?v=' . $version) ?>"></script>
<script type="text/javascript" src="<?= $this->basePath('/js/intranavigator.js?v=' . $version) ?>"></script>
<script type="text/javascript" src="<?= $this->basePath('/js/pop-ajax.js?v=' . $version) ?>"></script>
<script type="text/javascript" src="<?= $this->basePath('/js/chargens.js?v=' . $version) ?>"></script>
<script type="text/javascript" src="<?= $this->basePath('/js/mod-ajax.js?v=' . $version) ?>"></script>
<script type="text/javascript" src="<?= $this->basePath('/js/tab-ajax.js?v=' . $version) ?>"></script>
<script type="text/javascript" src="<?= $this->basePath('/js/app.js?v=' . $version) ?>"></script>
<script type="text/javascript" src="<?= $this->basePath('/js/paiement.js?v=' . $version) ?>"></script>
<script type="text/javascript" src="<?= $this->basePath('/js/piece-jointe.js?v=' . $version) ?>"></script>

<!-- Scripts chargés dynamiquement -->
<?= $this->inlineScript(); ?>

</body>
</html>