<?php

use Laminas\Navigation\AbstractContainer;
use Laminas\Navigation\Page\AbstractPage;

// Pointeur sur la première page du conteneur
$this->container->rewind();
// On récupère le conteneur en-dessous du 'home'
/** @var AbstractContainer $container */
$container = $this->container->getChildren();

// tri des pages de niveau 1 par 'order'
$sorterByOrder = function (AbstractPage $p1, AbstractPage $p2) {
    $temp = ($p1->getOrder() ?: 0) <=> ($p2->getOrder() ?: 0);

    return $temp;
};
$pagesNiv1     = iterator_to_array($container);
uasort($pagesNiv1, $sorterByOrder);
?>
<ul class="navbar-nav me-auto mb-2 mb-lg-0">
    <?php foreach ($pagesNiv1 as $page): ?>
        <?php
        if (!$this->navigation()->accept($page)) continue; ?>
        <?php /* @var $page Laminas\Navigation\Page\Mvc */ ?>
        <li class="nav-item">
            <a class="nav-link <?php if ($page->isActive()) echo ' active' ?>" href="<?php echo $page->getHref() ?>">
                <?php echo $this->escapeHtml($page->getLabel()); ?>
            </a>
        </li>
    <?php endforeach ?>
</ul>