<?php
/**
 * @var $this                 \Application\View\Renderer\PhpRenderer
 * @var $typesVolumesHoraires \Service\Entity\Db\TypeVolumeHoraire[]
 * @var $intervenant          \Intervenant\Entity\Db\Intervenant
 * @var $canEdit              bool
 * @var $data                 array
 *
 */

echo '<br />';

echo $this->messenger()->addCurrentMessagesFromFlashMessenger();

?>
<?php if ($canEdit): ?>

    <form method="post" action="<?= $this->url('derogations', ['intervenant' => $intervenant->getId()]) ?>">

<?php endif; ?>
    <table class="table table-bordered table-hover">
        <thead>
        <tr>
            <th rowspan="2">Plafond</th>
            <?php foreach ($typesVolumesHoraires as $typeVolumeHoraire): ?>
                <th colspan="3"><?= $typeVolumeHoraire->getLibelle() ?></th>
            <?php endforeach; ?>
            <th rowspan="2">Dérogation</th>
        </tr>
        <tr>
            <?php foreach ($typesVolumesHoraires as $typeVolumeHoraire): ?>
                <th>État</th>
                <th>Heures</th>
                <th>Plafond</th>
            <?php endforeach; ?>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($data as $id => $plafond): ?>
            <tr>
                <td><span class="badge bg-secondary"><?= $plafond['numero'] ?></span> <?= $plafond['libelle'] ?></td>
                <?php foreach ($typesVolumesHoraires as $typeVolumeHoraire): $tvh = $typeVolumeHoraire->getCode() ?>
                    <td><?= $plafond["$tvh-etat"] ?? 'Désactivé' ?></td>
                    <td<?php if ($plafond["$tvh-class"] ?? false) echo ' class="' . $plafond["$tvh-class"] . '"'; ?>><?= $plafond["$tvh-heures"] ?? '' ?></td>
                    <td><?= $plafond["$tvh-plafond"] ?? '' ?></td>
                <?php endforeach; ?>

                <td>
                    <?php if ($canEdit): ?>
                        <input class="form-control" type="text" name="plafond-<?= $id ?>"
                               value="<?= $plafond['derogation'] ?>"/>
                    <?php else: ?>
                        <?= floatToString($plafond['derogation']) ?>
                    <?php endif; ?>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
<?php if ($canEdit && !empty($data)): ?>

    <input type="hidden" name="action" value="save"/>
    <button class="btn btn-primary" type="submit">Enregistrer les modifications</button>
    </form>

<?php endif;
