<?php

/**
 * @var $this         \Application\View\Renderer\PhpRenderer
 * @var $tpj          \Application\Entity\Db\TypePieceJointe
 * @var $pj           \Application\Entity\Db\PieceJointe
 * @var $intervenant  \Application\Entity\Db\Intervenant
 * @var $canEdit      boolean
 * @var $canValider   boolean
 * @var $canDevalider boolean
 * @var $obligatoire  boolean
 */

$hasValidation = $pj && $pj->getValidation();

$linksModelesDocs = null;
if (($url = $tpj->getUrlModeleDoc())) {
    if (0 === strpos($url, 'http://') || 0 === strpos($url, 'https://')) {
//        $target = "_blank";
        $href   = $url;
    } else {
//        $target = "_self";
        $href   = $this->basePath($url);
    }

    $fileName         = ltrim(strrchr($href, '/'), '/');
    $linksModelesDocs = $this->tag('a', [
        'class'  => 'modele-doc',
        //'target' => $target,
        'title'  => 'Cliquez pour télécharger le document à remplir',
        'href'   => $href,
    ])->html(
        $this->tag('span', ['class' => 'glyphicon glyphicon-file'])->openClose() . " " . $fileName
    );
}

$type = (string)$tpj;
if ($tpj->getCode() === \Application\Entity\Db\TypePieceJointe::CARTE_ETUD) {
    $type .= " " . $intervenant->getAnnee();
}

$uploader = $this->uploader()->setUrl($this->url('piece-jointe/intervenant/fichier/televerser', ['typePieceJointe' => $tpj->getId()], [], true));

//Vérification si piece est de l'année en cours

?>
<div
        class="tpj <?= $obligatoire ? 'tpj-obligatoire ' : '' ?>tpj-<?= $tpj->getId() ?> panel panel-<?= $pj && $pj->getValidation() ? 'success' : 'default' ?> upload-container"
        data-tpj="<?= $tpj->getId() ?>"
>
    <div class="panel-heading panel-heading-h3">
        <h3>
            <?php if((!$hasValidation && $canValider) || ($hasValidation && $canDevalider)): ?>

                <?php if($pj && $pj->annee->getId() != $annee->getId()): ?>
                    <div class="validation-bar pull-right"
                         data-url="">
                        <span style="font-size:0.75em;">Fourni(e) en 2019 (<a href="<?= $this->url('piece-jointe/intervenant/archiver', ['pieceJointe' => $pj->getId()], [], true) ?>">archiver</a>)</span>
                    </div>
                <?php else: ?>
                    <div class="validation-bar pull-right"
                         data-url="<?= $this->url('piece-jointe/intervenant/validation', ['typePieceJointe' => $tpj->getId()], [], true) ?>">
                        <?= $this->partial('application/piece-jointe/validation', compact('pj')) ?>
                    </div>
                <?php endif; ?>
            <?php endif; ?>
            <?= $type ?><br/>
        </h3>
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col-md-6">
                <!-- Modèle de document éventuel -->
                <?php if ($linksModelesDocs): ?>
                    <div>
                        <label>Documents à télécharger et à remplir :</label><br/>
                        <?= $this->htmlList((array)$linksModelesDocs, false, false, false) ?>
                    </div>
                <?php endif ?>
                <!-- Liste des fichiers déposés -->
                <?= $uploader->renderUploadedFiles($this->url('piece-jointe/intervenant/fichier/lister', ['typePieceJointe' => $tpj->getId(), 'pieceJointe' => (!is_null($pj))?$pj->getId():''], [], true)) ?>
            </div>
            <div class="col-md-6">
                <!-- formulaire éventuel de dépôt de PJ -->
                <?php if ($canEdit): ?>
                    <?php
                    $uploader->getForm()->setAttribute('style', 'display:' . (($pj && $pj->getValidation()) ? 'none' : 'block'));
                    echo $uploader->renderForm();
                    ?>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>