<?php

/**
 * @var $this         \Application\View\Renderer\PhpRenderer
 * @var $tpj          \Application\Entity\Db\TypePieceJointe
 * @var $pj           \Application\Entity\Db\PieceJointe
 * @var $intervenant  \Application\Entity\Db\Intervenant
 * @var $canEdit      boolean
 * @var $canValider   boolean
 * @var $canArchiver  boolean
 * @var $canDevalider boolean
 * @var $obligatoire  boolean
 * @var $annee        \Application\Entity\Db\Annee
 */

$hasValidation = $pj && $pj->getValidation();

$linksModelesDocs = null;
if (($url = $tpj->getUrlModeleDoc())) {
    if (0 === strpos($url, 'http://') || 0 === strpos($url, 'https://')) {
//        $target = "_blank";
        $href = $url;
    } else {
//        $target = "_self";
        $href = $this->basePath($url);
    }
    $href             = str_replace(':annee', (string)$intervenant->getAnnee()->getId(), $href);
    $fileName         = ltrim(strrchr($href, '/'), '/');
    $linksModelesDocs = $this->tag('a', [
        'class' => 'modele-doc',
        //'target' => $target,
        'title' => 'Cliquez pour télécharger le document à remplir',
        'href'  => $href,
    ])->html(
        $this->tag('span', ['class' => 'glyphicon glyphicon-file'])->openClose() . " " . $fileName
    );
}

$type = (string)$tpj;
if ($tpj->getCode() === \Application\Entity\Db\TypePieceJointe::CARTE_ETUD) {
    $type .= " " . $intervenant->getAnnee();
}

$uploader = $this->uploader()->setUrl($this->url('piece-jointe/intervenant/fichier/televerser', ['typePieceJointe' => $tpj->getId()], [], true));

?>
<div
        class="tpj <?= $obligatoire ? 'tpj-obligatoire ' : '' ?>tpj-<?= $tpj->getId() ?> panel panel-<?= $pj && $pj->getValidation() ? 'success' : 'default' ?> upload-container"
        data-tpj="<?= $tpj->getId() ?>"
>
    <div class="panel-heading panel-heading-h3">
        <h3>
            <?php if ($hasValidation && $canArchiver && $pj && $pj->getIntervenant()->getAnnee()->getId() != $annee->getId()): ?>
                <div class="validation-bar pull-right"
                     data-url="<?= $this->url('piece-jointe/intervenant/archiver', ['pieceJointe' => $pj->getId()], [], true) ?>">
                    <a class="archiver-pj btn btn-success pop-ajax"
                       href="<?= $this->url('piece-jointe/intervenant/archiver', ['pieceJointe' => $pj->getId()], [], true) ?>"
                       data-loading-text="Patientez..."
                       title="Archiver cette pièce jointe pour en fournir une plus récente ?"
                       data-content="Archiver cette pièce jointe pour en fournir une plus récente ?"
                       data-confirm="true"
                       data-submit-reload="true"
                       data-confirm-button="Oui"
                       data-cancel-button="Non"
                    >
                        <span class="glyphicon glyphicon-refresh"></span> Modifier (si besoin)
                    </a>
                </div>
            <?php elseif ((!$hasValidation && $canValider && $pj && $pj->getIntervenant()->getAnnee()->getId() == $annee->getId()) || ($hasValidation && $canDevalider && $pj && $pj->getIntervenant()->getAnnee()->getId() == $annee->getId())): ?>
                <div class="validation-bar pull-right"
                     data-url="<?= $this->url('piece-jointe/intervenant/validation', ['typePieceJointe' => $tpj->getId()], [], true) ?>">
                    <?= $this->partial('application/piece-jointe/validation', compact('pj')) ?>
                </div>
            <?php endif; ?>

            <!--Infos sur document fourni sur une autre année-->
            <?=
            ($pj && $pj->getIntervenant()->getAnnee()->getId() != $annee->getId()) ? $type . "  <span style=\"font-size:0.6em;\">Fourni(e) en " . $pj->getIntervenant()->getAnnee()->getId() . "</span>" : $type;
            ?>
            <!--Info sur document facultatif-->
            <?=
            !$obligatoire ? '<span style="font-size:0.6em;"> (Document facultatif)</span>' : ''
            ?>
            <br/>
        </h3>
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col-md-6">
                <!-- Modèle de document éventuel -->
                <?php if ($linksModelesDocs): ?>
                    <div>
                        <label>Documents à télécharger et à remplir :</label><br/>
                        <?= $this->htmlList((array)$linksModelesDocs, false, false, false) ?>
                    </div>
                <?php endif ?>
                <!-- Liste des fichiers déposés -->
                <?= $uploader->renderUploadedFiles($this->url('piece-jointe/intervenant/fichier/lister', ['typePieceJointe' => $tpj->getId(), 'pieceJointe' => (!is_null($pj)) ? $pj->getId() : ''], [], true)) ?>
            </div>
            <div class="col-md-6">
                <!-- formulaire éventuel de dépôt de PJ -->
                <?php if ($canEdit): ?>
                    <?php
                    $uploader->getForm()->setAttribute('style', 'display:' . (($pj && $pj->getValidation()) ? 'none' : 'block'));
                    echo $uploader->renderForm();
                    ?>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>