<?php

/**
 * @var $this \Application\View\Renderer\PhpRenderer
 * @var $tpj \Application\Entity\Db\TypePieceJointe
 * @var $pj \Application\Entity\Db\PieceJointe
 * @var $intervenant \Application\Entity\Db\Intervenant
 * @var $canEdit boolean
 * @var $obligatoire boolean
 */

$linksModelesDocs = null;
if (($url = $tpj->getUrlModeleDoc())) {
    $href             = $this->basePath($url);
    $fileName         = ltrim(strrchr($href, '/'), '/');
    $linksModelesDocs = $this->tag('a', [
        'class' => 'modele-doc',
        'title' => 'Cliquez pour télécharger le document à remplir',
        'href'  => $href,
    ])->html(
        $this->tag('span', ['class' => 'glyphicon glyphicon-file'])->openClose() . " " . $fileName
    );
}

$type = (string)$tpj;
if ($tpj->getCode() === \Application\Entity\Db\TypePieceJointe::CARTE_ETUD) {
    $type .= " " . $intervenant->getAnnee();
}

$uploader = $this->uploader()->setUrl($this->url('piece-jointe/intervenant/fichier/televerser', ['typePieceJointe' => $tpj->getId()], [], true));

?>
<div
    class="tpj <?php echo $obligatoire ? 'tpj-obligatoire ' : '' ?>tpj-<?php echo $tpj->getId() ?> panel panel-<?php echo $pj && $pj->getValidation() ? 'success' : 'default' ?> upload-container"
    data-tpj="<?php echo $tpj->getId() ?>"
>
    <div class="panel-heading">
        <h3>
            <div class="validation-bar pull-right"
                 data-url="<?php echo $this->url('piece-jointe/intervenant/validation', ['typePieceJointe' => $tpj->getId()], [], true) ?>">
                <?php echo $this->partial('application/piece-jointe/validation', compact('pj')) ?>
            </div>
            <?php echo $type ?><br/>
        </h3>
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col-md-6">
                <!-- Modèle de document éventuel -->
                <?php if ($linksModelesDocs): ?>
                    <div>
                        <label>Documents à télécharger et à remplir :</label><br/>
                        <?php echo $this->htmlList((array)$linksModelesDocs, false, false, false) ?>
                    </div>
                <?php endif ?>
                <!-- Liste des fichiers déposés -->
                <?php echo $uploader->renderUploadedFiles($this->url('piece-jointe/intervenant/fichier/lister', ['typePieceJointe' => $tpj->getId()], [], true)) ?>
            </div>
            <div class="col-md-6">
                <!-- formulaire éventuel de dépôt de PJ -->
                <?php if ($canEdit): ?>
                    <?php
                    $uploader->getForm()->setAttribute('style', 'display:'.(($pj && $pj->getValidation())? 'none' : 'block'));
                    echo $uploader->renderForm();
                    ?>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>