<?php 
use Application\Assertion\FichierAssertion;
?>

<!-- actions de validation du fichier -->
<?php if ($this->isAllowed($this->fichier, FichierAssertion::PRIVILEGE_VALIDER)): ?>
    <?php
    $paramsValider = ['pieceJointe' => $pj->getId(), 'fichier' => $this->fichier->getId()];
    $urlValider    = $this->url('piece-jointe/intervenant/valider', $paramsValider, [], true);
    ?>
    <a class="valider-pj btn btn-xs btn-default" href="<?php echo $urlValider ?>" title="Valider le fichier '<?php echo $this->fichier->getNom() ?>'" data-loading-text="Patientez...">
        <span class="glyphicon glyphicon-thumbs-up"></span> Valider</a> 
<?php endif ?>

<!-- affichage de la validation éventuelle du fichier -->
<?php if ($this->fichier && $this->fichier->getValidation()): ?>
    <?php $title = (string) $this->fichier->getValidation() ?>
    <span class="label label-success" title="<?php echo $title ?>"><span class="glyphicon glyphicon-thumbs-up"></span> Validé</span>
<?php endif ?>

<!-- actions de dévalidation du fichier -->
<?php if ($this->isAllowed($this->fichier, FichierAssertion::PRIVILEGE_DEVALIDER)): ?>
    <?php
    $paramsDevalider = ['pieceJointe' => $pj->getId(), 'fichier' => $this->fichier->getId()];
    $urlDevalider    = $this->url('piece-jointe/intervenant/devalider', $paramsDevalider, [], true); 
    ?>
    <a class="devalider-pj btn btn-xs btn-default" href="<?php echo $urlDevalider ?>" title="Dévalider le fichier '<?php echo $this->fichier->getNom() ?>'" data-loading-text="Patientez...">
        <span class="glyphicon glyphicon-thumbs-down"></span> Dévalider</a> 
<?php endif ?>
            