<?php 
use Application\Assertion\PieceJointeAssertion;
?>

<?php if (!$this->pj) return ''; ?>

<!-- actions de validation de la pièce jointe entière -->
<?php if ($this->isAllowed($this->pj, PieceJointeAssertion::PRIVILEGE_VALIDER)): ?>
    <?php
    $paramsValider = ['pieceJointe' => $this->pj->getId()];
    $urlValider    = $this->url('piece-jointe/intervenant/valider', $paramsValider, [], true);
    ?>
    <a class="valider-pj btn btn-success" href="<?php echo $urlValider ?>" title="Valider la pièce justificative '<?php echo $this->pj->getType() ?>'" data-loading-text="Patientez...">
        <span class="glyphicon glyphicon-thumbs-up"></span> Valider</a> 
<?php endif ?>

<!-- affichage de la validation éventuelle de la pièce jointe entière -->
<?php if ($this->pj && $this->pj->getValidation()): ?>
    <?php $title = (string) $this->pj->getValidation() ?>
    <span class="label label-success" title="<?php echo $title ?>"><span class="glyphicon glyphicon-thumbs-up"></span> Validée</span>
<?php endif ?>

<!-- actions de dévalidation de la pièce jointe entière -->
<?php if ($this->isAllowed($this->pj, PieceJointeAssertion::PRIVILEGE_DEVALIDER)): ?>
    <?php
    $paramsDevalider = ['pieceJointe' => $this->pj->getId()];
    $urlDevalider    = $this->url('piece-jointe/intervenant/devalider', $paramsDevalider, [], true); 
    ?>
    <a class="devalider-pj btn btn-danger" href="<?php echo $urlDevalider ?>" title="Dévalider la pièce justificative '<?php echo $this->pj->getType() ?>'" data-loading-text="Patientez...">
        <span class="glyphicon glyphicon-thumbs-down"></span> Dévalider</a> 
<?php endif ?>