<?php

/**
 * @var $listeActivites \Paiement\Entity\Db\CcActivite[]
 */

use Application\Provider\Privileges;

$this->headTitle()->append("Types d'activité des centres de coûts");

$canEdit = $this->isAllowed(Privileges::getResourceId(Privileges::BUDGET_CC_ACTIVITE_EDITION));


?>
<h1 class="page-header">Types d'activité des centres de coûts</h1>
<table class="table table-bordered table-sm table-hover">
    <thead>
    <tr>
        <th>Code</th>
        <th>Libellé</th>
        <th>FI</th>
        <th>FA</th>
        <th>FC</th>
        <th>FC Majorée</th>
        <th>Référentiel</th>
        <th>Mission</th>
        <?php if ($canEdit): ?>
            <th>Actions</th>
        <?php endif; ?>
    </tr>
    </thead>
    <tbody class="triables">
    <?php foreach ($listeActivites as $activite): ?>
        <tr class="champ-triable" data-id="<?= $activite->getId() ?>">
            <td>
                <?= $activite->getCode() ?>&nbsp;
            </td>
            <td><?= $activite->getLibelle() ?></td>
            <td><?= ($activite->getFi()) ? 'OUI' : 'NON'; ?></td>
            <td><?= ($activite->getFa()) ? 'OUI' : 'NON'; ?></td>
            <td><?= ($activite->getFc()) ? 'OUI' : 'NON'; ?></td>
            <td><?= ($activite->getPrimes()) ? 'OUI' : 'NON'; ?></td>
            <td><?= ($activite->getReferentiel()) ? 'OUI' : 'NON'; ?></td>
            <td><?= ($activite->getMission()) ? 'OUI' : 'NON'; ?></td>
            <?php if ($canEdit): ?>
                <td style="text-align:center;width:1px;white-space: nowrap">
                    <a class="ajax-modal"
                       data-event="centre-cout-activite-saisie"
                       href="<?= $this->url('centre-cout-activite/saisie', ['ccActivite' => $activite->getId()]) ?>"
                       data-submit-reload="true">
                        <i class="fas fa-pen-to-square"></i></a>
                    <a class="pop-ajax"
                       href="<?= $this->url('centre-cout-activite/delete', ['ccActivite' => $activite->getId()]) ?>"
                       title="Supprimer le type d'activité"
                       data-content="<p class='lead text-danger'><strong>Attention!</strong> Confirmez-vous cette suppression ?</p>"
                       data-confirm="true"
                       data-confirm-button="Oui"
                       data-cancel-button="Non"
                       data-submit-reload="true"
                    >
                        <i class="fas fa-trash-can"></i>
                    </a>
                </td>
            <?php endif; ?>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<?php if ($canEdit): ?>
    <a class="btn btn-primary ajax-modal" data-event="centre-cout-activite-saisie"
       href="<?= $this->url('centre-cout-activite/saisie') ?>"
       title="Ajouter un type d'activité">
        <i class="fas fa-plus"></i>
        Ajouter un type d'activité</a>
<?php endif; ?>

<script type="text/javascript">
    $(function () {
        $("body").on("centre-cout-activite-saisie", function (event, data) {
            window.location.reload();
        });
    });
</script>
<style>
    .triables {
        align: left;
    }

    .champ-triable tr {
        align: left;
    }

    .tbl-tis {
        margin-bottom: 1px;
    }
</style>