<?php

use Enseignement\Entity\VolumeHoraireListe;

/**
 * @var $this               \Application\View\Renderer\PhpRenderer
 * @var $volumeHoraireListe VolumeHoraireListe
 * @var $readOnly           bool
 * @var $semestriel         bool
 */

if ($semestriel) {
    echo $this
        ->volumeHoraireListe($volumeHoraireListe)
        ->setReadOnly($readOnly)
        ->render();
} else {
    echo $this
        ->volumeHoraireListeCalendaire($volumeHoraireListe)
        ->setReadOnly($readOnly)
        ->render();
}