<?php

/**
 * @var $this  \Application\View\Renderer\PhpRenderer
 * @var $form  \Enseignement\Form\VolumeHoraireSaisieForm
 */


$submit = $this->formSubmit($form->get('submit'));
$annuler = $this->formButton($form->get('annuler'));

$form->prepare();

echo $this->form()->openTag($form);
echo $this->formControlGroup($form->get('heures'));
if ($form->canEditMNP()) {
    echo $this->formControlGroup($form->get('motif-non-paiement'));
}

if ($form->canEditTag()) {
    echo $this->formControlGroup($form->get('tag'));
}
echo '<hr /><div style="text-align:right">';
echo $this->formRow($form->get('submit'));
echo ' ';
echo $this->formRow($form->get('annuler'));
echo '</div>';

echo $this->formHidden($form->get('type-volume-horaire'));
echo $this->formHidden($form->get('type-intervention'));
echo $this->formHidden($form->get('periode'));
echo $this->formHidden($form->get('service'));
if (!$form->canEditMNP()) {
    echo $this->formHidden($form->get('motif-non-paiement'));
}
if (!$form->canEditTag()) {
    echo $this->formHidden($form->get('tag'));
}
echo $this->formHidden($form->get('ancien-motif-non-paiement'));
echo $this->formHidden($form->get('ancien-tag'));
echo $this->form()->closeTag();
echo $this->formErrors($form);
echo $this->messenger()->addCurrentMessagesFromFlashMessenger();