
<h1>Tableau de bord principal</h1>

<?php foreach( $data as $tname => $columns ): ?>
    <h2><?php echo $tname ?></h2>
    <table class="table table-striped table-bordered table-hover">
    <tr>
        <th>Colonne</th>
        <th>Type</th>
        <th>Longueur</th>
        <th>Nullable</th>
        <th>Val. par défaut</th>
        <th>Table de réf.</th>
        <th>Colonne de réf.</th>
        <th>Import actif</th>
    </tr>
    <?php foreach( $columns as $cname => $column ): ?>
    <tr class="<?php 
        if (! $column->importActif && ! $column->hasDefault && ! $column->nullable) echo 'danger';
        elseif (! $column->importActif) echo 'warning';
    ?>">
        <th><?php echo $cname ?></th>
        <td><?php echo $column->dataType ?></td>
        <td style="text-align:center"><?php echo $column->length ?></td>
        <td style="text-align:center"><?php echo $column->nullable ? '<span class="glyphicon glyphicon-ok"></span>' : '' ?></td>
        <td style="text-align:center"><?php echo $column->hasDefault ? '<span class="glyphicon glyphicon-ok"></span>' : '' ?></td>
        <td><?php echo $column->refTableName ?></td>
        <td><?php echo $column->refColumnName ?></td>
        <td style="text-align:center"><?php echo $column->importActif ? '<span class="glyphicon glyphicon-ok"></span>' : '' ?></td>
    </tr>
    <?php endforeach; ?>
    </table>
<?php endforeach; ?>
