<div class="container-fluid text-sm-center p-5 bg-light jumbotron">
    <h1>Choisir un établissement</h1>
</div>

<style>
    span.sas-highlight {
        font-weight: bold;
    }
</style>

<?php $form->prepare(); ?>

<?= $this->form()->openTag($form) ?>
<?= $this->formControlGroup($form->get('etablissement')); ?>
<input class="btn btn-primary" type="submit" value="Choisir" name="submit">
<?= $this->form()->closeTag() ?>

<script>
    $(function () {
        $(":input").tooltip({ /*placement: 'left'*/});
    });
</script>