<?php


$this->headTitle()->append("Types de ressources");

//$canEdit = $this->isAllowed(Privileges::getResourceId(Privileges::TYPE_INTERVENTION_EDITION));
?>
<h1 class="page-header">Types de ressources</h1>

<table class="table table-bordered table-condensed table-hover">
    <thead>
    <tr>
        <th>Code</th>
        <th>Libellé</th>
        <th>FA</th>
        <th>FI</th>
        <th>FC</th>
        <th>Actions</th>
    </tr>
    </thead>
    <tbody class="triables">
    <?php foreach ($listTypesRessources as $type): ?>
        <tr class="champ-triable" data-id="<?= $type->getId() ?>">
            <td>
                <?= $type->getCode() ?>&nbsp;
            </td>
            <td><?= $type->getLibelle() ?></td>
            <td><?= ($type->getFa())?'OUI':'NON'; ?></td>
            <td><?= ($type->getFi())?'OUI':'NON'; ?></td>
            <td><?= ($type->getFc())?'OUI':'NON'; ?></td>
            <td style="text-align:center;width:1px;white-space: nowrap">
                <a class="ajax-modal"
                   data-event="type-ressource-saisie"
                   href="<?= $this->url('type-ressource/saisie', ['typeRessource' => $type->getId()]) ?>"
                   title="Modifier le type de ressource">
                    <span class="glyphicon glyphicon-edit"></span></a>
                <a class="pop-ajax"
                   href="<?= $this->url('type-ressource/delete', ['typeRessource' => $type->getId()]) ?>"
                   title="Supprimer le type de ressource"
                   data-content="<p class='lead text-danger'><strong>Attention!</strong> Confirmez-vous cette suppression ?</p>"
                   data-confirm="true"
                   data-confirm-button="Oui"
                   data-cancel-button="Non"
                   data-submit-reload="true"
                >
                    <span class="glyphicon glyphicon-trash"></span>
                </a>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<style>
    .triables {
        align: left;
    }

    .champ-triable tr {
        align: left;
    }

    .tbl-tis {
        margin-bottom: 1px;
    }
</style>