<?php
/**
 * @var $this  \Application\View\Renderer\PhpRenderer
 * @var $form  \Application\Form\TypeRessource\TypeRessourceSaisieForm
 */
echo $this->messenger()->addCurrentMessagesFromFlashMessenger();

echo $this->form()->openTag($form); ?>

<div class="row">
    <div class="col-md-3">
        <?= $this->formControlGroup($form->get('code')); ?>
    </div>
    <div class="col-md-6">
        <?= $this->formControlGroup($form->get('libelle')); ?>
    </div>

</div>

<?= $this->formControlGroup($form->get('security')); ?>
<?= $this->formSubmit($form->get('submit')); ?>
<?= $this->form()->closeTag(); ?>
