<?php

/**
 * @var $this              \Application\View\Renderer\PhpRenderer
 * @var $typeVolumeHoraire Service\Entity\Db\TypeVolumeHoraire
 */

use Application\Entity\Db\WfEtape;
use Application\Provider\Privilege\Privileges;

/**
 * @var $intervenant         \Application\Entity\Db\Intervenant
 * @var $cloture             \Application\Entity\Db\Validation|null
 * @var $role                \Application\Acl\Role
 * @var $services            \Application\Entity\Db\Service[]
 * @var $servicesReferentiel \Application\Entity\Db\ServiceReferentiel[]
 */

$service = new \Application\Entity\Db\Service();
$service->setIntervenant($intervenant);
$service->setTypeVolumeHoraire($typeVolumeHoraire);
$canAddService = $this->isAllowed($service, $typeVolumeHoraire->getPrivilegeEnseignementEdition());

if ($typeVolumeHoraire->isPrevu()) {
    $nextEtape = WfEtape::CODE_SERVICE_SAISIE;
    $title     = 'Enseignements';
} else {
    $nextEtape = WfEtape::CODE_SERVICE_SAISIE_REALISE;
    $title     = 'Constatation des enseignements réalisés';
}

$menuUrl = $this->url(null, ['intervenant' => $intervenant->getId()], ['query' => ['menu' => 1]]);

$btnNextUrl = $this->url('workflow/feuille-de-route-btn-next', ['intervenant' => $intervenant->getId(), 'wfEtapeCode' => $nextEtape]);

$this->intervenant($intervenant)->renderTitle($title);

echo $this->messenger()->addCurrentMessagesFromFlashMessenger();

$bottom = false;
if ($cloture) echo $this->partial('application/intervenant/partial/cloture', compact('cloture', 'role', 'bottom'));

/* Services et horodatage */
if ($services !== false) {
    $serviceListe = $this->serviceListe($services);
    $serviceListe->setIntervenant($intervenant);
    $serviceListe->setTypeVolumeHoraire($typeVolumeHoraire)->setAddButtonVisibility($canAddService);
    if ($canAddService && $typeVolumeHoraire->isPrevu()) {
        $serviceListe->showPrevuToPrevu($intervenant);
    }
    echo $serviceListe->render();

    echo $this->partial('application/intervenant/partial/horodatage', [
        'intervenant'       => $intervenant,
        'typeVolumeHoraire' => $typeVolumeHoraire,
        'referentiel'       => false,
    ]);
}

?>
<hr/>
