<?php

/**
 * @var $this                     Application\View\Renderer\PhpRenderer
 * @var $typeVolumeHoraire        Service\Entity\Db\TypeVolumeHoraire
 * @var $intervenant              \Intervenant\Entity\Db\Intervenant
 * @var $enseignements            Enseignement\Entity\Db\Service[]
 */

use Workflow\Entity\Db\WfEtape;

if ($typeVolumeHoraire->isPrevu()) {
    $nextEtape = WfEtape::CODE_SERVICE_SAISIE;
    $title     = 'Enseignements';
} else {
    $nextEtape = WfEtape::CODE_SERVICE_SAISIE_REALISE;
    $title     = 'Constatation des enseignements réalisés';
}

//$menuUrl = $this->url(null, ['intervenant' => $intervenant->getId()], ['query' => ['menu' => 1]]);

$this->intervenant($intervenant)->renderTitle($title);
echo $this->messenger()->addCurrentMessagesFromFlashMessenger();

$ens = $this->enseignements($typeVolumeHoraire, $intervenant, $enseignements);
$ens->setHorodatage(true);
echo $ens;

echo '<hr />';

echo $this->feuilleDeRoute($intervenant)->renderNav($nextEtape);
?>
<script>
    /*
        $(function () {
            WidgetInitializer.includeJs(unicaenVue.url('js/service.js'));

            $('.enseignements').enseignements({
                'heures-change': function () {

                }
            });
        });
    */
</script>