<?php

/**
 * @var $this              \Application\View\Renderer\PhpRenderer
 * @var $validations       \Workflow\Entity\Db\Validation[]
 * @var $typeVolumehoraire \Service\Entity\Db\TypeVolumeHoraire
 */

use Workflow\Entity\Db\WorkflowEtape;


$this->intervenant($intervenant)->renderTitle($title);

$wells = [
    'non-valides' => 'Enseignements non validés',
    'valides'     => 'Enseignements validés',
];

echo $this->messenger()->addCurrentMessagesFromFlashMessenger();
echo $this->plafonds($intervenant, $typeVolumeHoraire);

foreach ($wells as $well => $title) {
    if ($services[$well]) {
        echo '<div class="well"><h2>' . $title . '</h2>';
        foreach ($services[$well] as $validationId => $srvs) {
            $validation = $validations[$validationId];
            echo $this->partial('enseignement/partial/validation-enseignement', [
                'validation'        => $validation,
                'structure'         => $validation->getStructure(),
                'services'          => $srvs,
                'typeVolumeHoraire' => $typeVolumeHoraire,
            ]);
        }
        echo '</div>';
    }
}

echo $this->feuilleDeRoute($intervenant)->renderNav(
    $typeVolumeHoraire->isPrevu() ? WorkflowEtape::ENSEIGNEMENT_VALIDATION : WorkflowEtape::ENSEIGNEMENT_VALIDATION
);
