<?php

/**
 * @var $this    \Application\View\Renderer\PhpRenderer
 * @var $annees  \Application\Entity\Db\Annee[][]
 * @var $canEdit boolean
 */

$annees = array_chunk($annees, 10);

?>
<h1 class="page-header">Gestion des années</h1>

<?php foreach ($annees as $al): ?>
    <div style="float:left;margin:2em">
        <?php foreach ($al as $annee): ?>

            <div style="margin:5px">
                <button type="button" data-id="<?php echo $annee->getId() ?>" class="btn btn-annee <?php echo $annee->isActive() ? 'btn-info active' : 'btn-default' ?>"><?php echo $annee ?></button>
            </div>

        <?php endforeach; ?>
    </div>
<?php endforeach; ?>
<script>

    $('.btn-annee').click(function(){

        var isActive = $(this).hasClass('active');
        var anneeId = $(this).data('id');

        if (isActive){
            $(this).removeClass('active');
            $(this).removeClass('btn-info');
            $(this).addClass('btn-default');
            isActive = false;
        }else{
            $(this).addClass('active');
            $(this).addClass('btn-info');
            $(this).removeClass('btn-default');
            isActive = true;
        }

        $.post( <?php echo var_export( $this->url('parametres/annees'), true) ?>, {annee: anneeId}, function(data) {
            alertFlash(data.message, data.status, 5000);
        });

    });

</script>