<?php

/* @var $form Application\Form\Droits\AffectationForm */
/* @var $errors array */

echo $this->form()->openTag($form->prepare());

if ($errors) {
    echo $this->messenger()->setMessages([UnicaenApp\View\Helper\Messenger::ERROR => $errors]);
}

echo $this->formControlGroup( $form->get('personnel') );
echo $this->formControlGroup( $form->get('role'     ) );
echo $this->formControlGroup( $form->get('structure') );
echo $this->formRow         ( $form->get('submit'   ) );
echo $this->formHidden      ( $form->get('id'       ) );

echo $this->form()->closeTag();