<?php

/**
 * @var $this       \Application\View\Renderer\PhpRenderer
 * @var $privileges UnicaenAuth\Entity\Db\Privilege[]
 * @var $roles      Application\Entity\Db\Role[]
 * @var $statuts    Application\Entity\Db\StatutIntervenant[]
 * @var $filters    array
 */

?>
<h1 class="page-header">Gestion des privilèges</h1>
<table class="droits-tbl table table-bordered table-condensed table-extra-condensed table-header-rotated">
    <thead>
    <tr>
        <th class="menu"><a class="btn btn-default show-all">Supprimer les
                filtres</a></th>
        <?php foreach ($roles as $role): ?>
            <th class="rotate-45 role" data-role="<?php echo $role->getId() ?>" title="<?php echo $role; ?>">
                <div><span><a><?php echo $role; ?></a></span></div>
            </th>
        <?php endforeach; ?>
        <?php if (!empty($roles) && !empty($statuts)): ?>
            <th class="separator rotate-45">&nbsp;</th>
        <?php endif; ?>
        <?php foreach ($statuts as $statut): ?>
            <th class="rotate-45 statut" data-statut="<?php echo $statut->getId() ?>" title="<?php echo $statut; ?>">
                <div><span><a><?php echo $statut; ?></a></span></div>
            </th>
        <?php endforeach; ?>
    </tr>
    <tr>
        <th>Privilèges</th>
        <?php if (!empty($roles)): ?>
            <th class="roles" colspan="<?php echo count($roles); ?>"><a class="roles">Rôles (personnel)</a></th>
        <?php endif; ?>
        <?php if (!empty($roles) && !empty($statuts)): ?>
            <th class="separator">&nbsp;</th>
        <?php endif; ?>
        <?php if (!empty($statuts)): ?>
            <th class="statuts" colspan="<?php echo count($statuts); ?>"><a class="statuts">Statuts (intervenants)</a></th>
        <?php endif; ?>
        <th style="border:none;min-width:166px">&nbsp;</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($privileges as $cat): ?>
        <tr class="categorie" data-categorie="<?php echo $cat['categorie']->getCode() ?>">
            <th class="categorie">&nbsp;</th>
            <th class="categorie" colspan="<?php echo 1 + count($roles) + count($statuts); ?>">
                <a class="categorie"
                   data-categorie="<?php echo $cat['categorie']->getCode() ?>"><?php echo $cat['categorie'] ?></a>
            </th>
        </tr>
        <?php foreach ($cat['privileges'] as $privilege): ?>
            <tr class="categorie" data-categorie="<?php echo $cat['categorie']->getCode() ?>">
                <th class="privilege"><?php echo $privilege ?></th>
                <?php $statut = null;
                foreach ($roles as $role): ?>
                    <td class="modifier role" data-role="<?php echo $role->getId() ?>"
                        data-privilege="<?php echo $privilege->getId() ?>"
                        title="Rôle : <?php echo $role->getLibelle() ?>"
                    >
                        <?php echo $this->partial('/application/droits/partial/tbl-link', compact('role', 'statut', 'privilege')) ?>
                    </td>
                <?php endforeach; ?>
                <?php if (!empty($roles) && !empty($statuts)): ?>
                    <th class="separator ">&nbsp;</th>
                <?php endif; ?>
                <?php $role = null;
                foreach ($statuts as $statut): ?>
                    <td class="modifier statut" data-statut="<?php echo $statut->getId() ?>"
                        data-privilege="<?php echo $privilege->getId() ?>"
                        title="Statut : <?php echo $statut->getLibelle() ?>"
                    >
                        <?php echo $this->partial('/application/droits/partial/tbl-link', compact('role', 'statut', 'privilege')) ?>
                    </td>
                <?php endforeach; ?>
            </tr>
        <?php endforeach; ?>
    <?php endforeach; ?>
    </tbody>
</table>