<?php
$libelle = "J'ai terminé la saisie de la totalité de mon service réalisé";
?>

<!----------------------------------------------------------------------------->
<!--                            Bouton de clôture                            -->
<!----------------------------------------------------------------------------->

<?php if ($this->isAllowed($this->validation, 'create')): ?>

    <?php echo $this->messenger()->renderMessage($this->avertissement, 'warning') ?>

    <button type="button" id="btn-cloturer-saisie" 
            class="btn btn-lg btn-info"><?php echo $libelle ?></button>

    <script>
        var url = '<?php echo $this->url('intervenant/cloturer-saisie', [], [], true) ?>';
        $(function() {
            $("#btn-cloturer-saisie").click(function(e) {
                e.preventDefault();
                if (!confirm("<?php echo $this->confirm ?>")) {
                    return;
                }
                $.post(url, {cloturer: 1}, function() {
                    window.location.reload();
                });
            });
        });
    </script>

<?php endif; ?>

    
<!----------------------------------------------------------------------------->
<!--                       Clôture existante éventuelle                      -->
<!----------------------------------------------------------------------------->

<?php if ($this->isAllowed($this->validation, 'read')): ?>

    <button type="button" id="btn-cloturer-saisie" class="btn btn-lg btn-success" disabled="disabled"><?php echo $libelle ?> le 
            <?php echo $this->validation->getHistoModification()->format(\Common\Constants::DATETIME_FORMAT) ?></button>

    <script>
        $(function() {
            $("#btn-cloturer-saisie").parent().tooltip();
        });
    </script>

<?php endif;