<hr />

<?php if (! $this->validation): ?>

<button type="button" id="btn-cloturer-saisie" class="btn btn-lg btn-info" 
        data-toggle="tooltip"
        title="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat." 
        data-placement="right">J'ai fini de saisir mes services réalisés</button>

<?php echo $this->messenger()->renderMessage("<strong>Attention!</strong> Une fois le bouton cliqué il sera impossible de remodifier le service réalisé.", 'warning') ?>

<script>
    var url = '<?php echo $this->url('intervenant/cloturer-saisie', [], [], true) ?>';
    $(function() {
        $("#btn-cloturer-saisie").tooltip().click(function(e) {
            e.preventDefault();
            if (!confirm("Confirmez-vous que vous avez terminé la saisie des enseignements réalisés ?")) {
                return;
            }
            $.post(url, {cloturer: 1}, function() {
                window.location.reload();
            });
        });
    });
</script>

<?php else: ?>

<span title="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat." 
     data-toggle="tooltip"
     data-placement="right">
    <button type="button" id="btn-cloturer-saisie" class="btn btn-lg btn-success" disabled="disabled">J'ai fini de saisir mes services réalisés le 
            <?php echo $this->validation->getHistoModification()->format(Common\Constants::DATETIME_FORMAT) ?></button>
</span>

<script>
    $(function() {
        $("#btn-cloturer-saisie").parent().tooltip();
    });
</script>

<?php endif;