<?php
/**
 * @var $structure        \Application\Entity\Db\Structure
 * @var $typeIntervenant  \Application\Entity\Db\TypeIntervenant
 * @var $signature1       string
 * @var $signataire1      string
 * @var $signature2       string
 * @var $signataire2      string
 * @var $data             array
 */

?>
<style>
    body {
        font-family: ubuntu, arial, sans-serif;
    }

    .entete {
        font-size: 6pt;
        font-weight: bold;
    }

    .sign-cell {
        padding: 15pt;
        width: 50%;
    }

    .signature {
        border-style: solid;
        border-width: 1px;
        padding: 15pt;
        width: 52em;
    }

    .signature-titre {
        font-weight: bold;
        text-align: center;
    }

    .signature-personne {
        text-align: center;
    }

    .data {
        font-size: 7pt;
        border-collapse: collapse;
    }

    .data thead th {
        background-color: #4472C4;
        color: white;
        border-top-width: 2;
        border-top-style: solid;
        border-bottom-width: 2;
        border-bottom-style: solid;
    }

    .total td {
        background-color: #305496;
        color: white;
        border-bottom-width: 1;
        border-bottom-style: solid;
    }

    .total td.solde_negatif {
        background-color: lightpink;
        color: darkred;
        border-right-width: 2;
        border-right-style: solid;
        border-bottom-width: 1;
        border-bottom-style: solid;
        text-align: center;
    }

    .c1 {
        border-left-width: 2;
        border-left-style: solid;
    }

    .c5 {
        border-right-width: 2;
        border-right-style: solid;
    }

    .c7 {
        border-right-width: 2;
        border-right-style: solid;
    }

    .c8 {
        text-align: center;
    }

    .c9 {
        border-right-width: 2;
        border-right-style: solid;
        text-align: center;
    }

    .c10 {
        text-align: center;
    }

    .c11 {
        text-align: center;
    }

    .c12 {
        text-align: center;
    }

    .c13 {
        border-right-width: 2;
        border-right-style: solid;
        text-align: center;
    }

    .c14 {
        border-right-width: 2;
        border-right-style: solid;
        text-align: center;
    }

    .c15 {
        border-right-width: 2;
        border-right-style: solid;
        text-align: center;
    }

    .data:last-child {
        border-bottom-width: 2;
        border-bottom-style: solid;
    }

</style>

<table style="width:100%" class="entete">
    <tr>
        <td style="width: 85%">
            <table>
                <tr>
                    <td>Composante d'affectation</td>
                    <td><?php echo $structure ? $structure : 'Toutes' ?></td>
                </tr>
                <tr>
                    <td>Type d'intervenant</td>
                    <td><?php echo $typeIntervenant ? $typeIntervenant : 'Tous' ?></td>
                </tr>
            </table>
        </td>
        <td>*<br/>&nbsp;</td>
        <td>
            "service +" : Total heures complémentaires (HETD)<br/>
            "Service -" : Heures sous-service (HETD)
        </td>
    </tr>
</table>


<table class="data" cellpadding="3">
    <thead>
    <tr>
        <th class="c1">Intervenant</th>
        <th class="c2">Statut intervenant</th>
        <th class="c3">Grade</th>
        <th class="c4">Structure d'enseignement</th>
        <th class="c5">Type de formation</th>
        <th class="c6">Formation ou établissement</th>
        <th class="c7">Enseignement ou fonction référentielle</th>
        <th class="c8">Service statutaire</th>
        <th class="c9">Modification de service du</th>
        <th class="c10">Total FI</th>
        <th class="c11">Total FA</th>
        <th class="c12">Total FC</th>
        <th class="c13">Référentiel</th>
        <th class="c14">Total HETD</th>
        <th class="c15">Service (+/-) *</th>
    </tr>
    </thead>
    <tbody>
    <?php
    foreach ($data as $di):
        $s = 0;

        $ls = [
            'structure'      => '------------',
            'type-formation' => '------------',
            'formation'      => '------------',
            'enseignement'   => '------------',
        ];
        foreach ($di['services'] as $ds):
            $s++;

            if ($ls['formation'] != $ds['formation']) {
                $ls['enseignement'] = '------------';
            }
            if ($ls['type-formation'] != $ds['type-formation']) {
                $ls['formation']    = '------------';
                $ls['enseignement'] = '------------';
            }
            if ($ls['structure'] != $ds['structure']) {
                $ls['type-formation'] = '------------';
                $ls['formation']      = '------------';
                $ls['enseignement']   = '------------';
            }
            ?>
            <tr>
                <td class="c1"><?php echo $s == 1 ? $di['nom'] : '' ?></td>
                <td class="c2"><?php echo $s == 1 ? $di['statut'] : '' ?></td>
                <td class="c3"><?php echo $s == 1 ? $di['grade'] : '' ?></td>
                <td class="c4"><?php echo $ls['structure'] != $ds['structure'] ? $ds['structure'] : '' ?></td>
                <td class="c5"><?php echo $ls['type-formation'] != $ds['type-formation'] ? $ds['type-formation'] : '' ?></td>
                <td class="c6"><?php echo $ls['formation'] != $ds['formation'] ? $ds['formation'] : '' ?></td>
                <td class="c7"><?php echo $ls['enseignement'] != $ds['enseignement'] ? $ds['enseignement'] : '' ?></td>

                <td class="c8"></td>
                <td class="c9"></td>
                <td class="c10"><?php echo \UnicaenApp\Util::formattedFloat($ds['fi']) ?></td>
                <td class="c11"><?php echo \UnicaenApp\Util::formattedFloat($ds['fa']) ?></td>
                <td class="c12"><?php echo \UnicaenApp\Util::formattedFloat($ds['fc']) ?></td>
                <td class="c13"><?php echo \UnicaenApp\Util::formattedFloat($ds['referentiel']) ?></td>
                <td class="c14"><?php echo \UnicaenApp\Util::formattedFloat($ds['total']) ?></td>
                <td class="c15"></td>
            </tr>
            <?php

            $ls = $ds;

        endforeach; ?>
        <tr class="total">
            <td class="c1">Total <?php echo $di['nom'] ?></td>
            <td class="c2"></td>
            <td class="c3"></td>
            <td class="c4"></td>
            <td class="c5"></td>
            <td class="c6"></td>
            <td class="c7"></td>

            <td class="c8"><?php echo \UnicaenApp\Util::formattedFloat($di['service-du']) ?></td>
            <td class="c9"><?php echo \UnicaenApp\Util::formattedFloat($di['modif-service-du']) ?></td>
            <td class="c10"><?php echo \UnicaenApp\Util::formattedFloat($di['fi']) ?></td>
            <td class="c11"><?php echo \UnicaenApp\Util::formattedFloat($di['fa']) ?></td>
            <td class="c12"><?php echo \UnicaenApp\Util::formattedFloat($di['fc']) ?></td>
            <td class="c13"><?php echo \UnicaenApp\Util::formattedFloat($di['referentiel']) ?></td>
            <td class="c14"><?php echo \UnicaenApp\Util::formattedFloat($di['total']) ?></td>
            <td class="<?php echo ($di['solde'] < 0) ? 'solde_negatif' : 'c15' ?>"><?php echo \UnicaenApp\Util::formattedFloat($di['solde']) ?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>


<table style="width:100%">
    <tr>
        <td class="sign-cell">
            <table class="signature">
                <tr>
                    <td class="signature-titre"><?php echo $signature1 ?></td>
                </tr>
                <tr>
                    <td class="signature-personne"><?php echo nl2br($signataire1) ?></td>
                </tr>
                <tr>
                    <td>Date :</td>
                </tr>
                <tr>
                    <td>&nbsp;</td>
                </tr>
                <tr>
                    <td>Signature :</td>
                </tr>
                <tr>
                    <td>&nbsp;</td>
                </tr>
            </table>
        </td>
        <td class="sign-cell">
            <table class="signature">
                <tr>
                    <td class="signature-titre"><?php echo $signature2 ?></td>
                </tr>
                <tr>
                    <td class="signature-personne"><?php echo nl2br($signataire2) ?></td>
                </tr>
                <tr>
                    <td>Date :</td>
                </tr>
                <tr>
                    <td>&nbsp;</td>
                </tr>
                <tr>
                    <td>Signature :</td>
                </tr>
                <tr>
                    <td>&nbsp;</td>
                </tr>
            </table>
        </td>
    </tr>
</table>