<?php if ($rechercheForm): ?>

<style>
    div.filter input[type=radio] { margin-left: 1em; margin-right: 3px; } 
</style>

<div class="panel panel-default filter">
    
    <div class="panel-heading">Filtres</div>
    <div class="panel-body">
        <?php echo $this->form()->openTag($rechercheForm->prepare()); ?>
        <div class="row">
          <div class="col-md-4"><label class="control-label"><?php echo $rechercheForm->get('intervenant')->getLabel() ?></label></div>
          <div class="col-md-8"><?php echo $this->formSearchAndSelect($rechercheForm->get('intervenant')); ?></div>
        </div>
        <div class="row">
          <div class="col-md-4"><label class="control-label"><?php echo $rechercheForm->get('statut-interv')->getLabel() ?></label></div>
          <div class="col-md-8"><?php echo $this->formRadio($rechercheForm->get('statut-interv')); ?></div>
        </div>
        <div class="row">
          <div class="col-md-4"><label class="control-label"><?php echo $rechercheForm->get('structure-ens')->getLabel() ?></label></div>
          <div class="col-md-8"><?php echo $this->formSelect($rechercheForm->get('structure-ens')->setAttribute('class','form-control')); ?></div>
        </div>
        <div class="row">
          <div class="col-md-4"><label class="control-label"><?php echo $rechercheForm->get('etape')->getLabel() ?></label></div>
          <div class="col-md-8"><?php echo $this->formSelect($rechercheForm->get('etape')->setAttribute('class','form-control')); ?></div>
        </div>
        <div class="row">
          <div class="col-md-4"><label class="control-label"><?php echo $rechercheForm->get('element-pedagogique')->getLabel() ?></label></div>
          <div class="col-md-8"><?php echo $this->formSelect($rechercheForm->get('element-pedagogique')->setAttribute('class','form-control')); ?></div>
        </div>
        <div class="row">
          <div class="col-md-4">&nbsp;</div>
          <div class="col-md-8"><?php echo $this->formRow($rechercheForm->get('submit')); ?></div>
        </div>
        <?php
        echo $this->formHidden( $rechercheForm->get('action'));
        echo $this->form()->closeTag();
        echo $this->formErrors( $rechercheForm );
        ?>
    </div>
</div>

<?php endif; ?>