<?php if ($rechercheForm): ?>
<h1>Filtres</h1>
<div class="well well-sm filter">
<?php $rechercheForm->prepare(); ?>
<?php echo $this->form()->openTag($rechercheForm); ?>

<div class="row">
  <div class="col-md-4"><label class="control-label"><?php echo $rechercheForm->get('intervenant')->getLabel() ?></label></div>
  <div class="col-md-8"><?php echo $this->formSelect($rechercheForm->get('intervenant')->setAttribute('class','form-control')); ?></div>
</div>
<div class="row">
  <div class="col-md-4"><label class="control-label"><?php echo $rechercheForm->get('structure-ens')->getLabel() ?></label></div>
  <div class="col-md-8"><?php echo $this->formSelect($rechercheForm->get('structure-ens')->setAttribute('class','form-control')); ?></div>
</div>
<div class="row">
  <div class="col-md-4"><label class="control-label"><?php echo $rechercheForm->get('etape')->getLabel() ?></label></div>
  <div class="col-md-8"><?php echo $this->formSelect($rechercheForm->get('etape')->setAttribute('class','form-control')); ?></div>
</div>
<div class="row">
  <div class="col-md-4"><label class="control-label"><?php echo $rechercheForm->get('element-pedagogique')->getLabel() ?></label></div>
  <div class="col-md-8"><?php echo $this->formSelect($rechercheForm->get('element-pedagogique')->setAttribute('class','form-control')); ?></div>
</div>
<div class="row">
  <div class="col-md-4">&nbsp;</div>
  <div class="col-md-8"><?php echo $this->formRow($rechercheForm->get('submit')); ?></div>
</div>
<?php

echo $this->formHidden( $rechercheForm->get('action'));
echo $this->form()->closeTag();
echo $this->formErrors( $rechercheForm );

?>
</div>
<?php endif; ?>