<h1 class="page-header"><?php echo $title; ?></h1>

<?php echo $this->messenger(true) ?>

<style>
    .modal-dialog { 
        width: 70%;
    }
    div.row {
        padding:1px;
    }
    th.heures, td.heures { width: 3em !important; }
</style>

<?php if ($role instanceof \Application\Acl\DbRole): ?>
<?php echo $this->messenger()->setMessages(array('warning' => "Sont visibles ici les référentiels et les enseignements prévisionnels des intervenants affectés "
        . "ou enseignant dans votre structure de responsabilité ({$role->getStructure()}) ou l'une de ses sous-structures.")); ?>
<?php endif; ?>

<?php if (! $role instanceof \Application\Acl\IntervenantRole): ?>
<div id="filtres" data-url="<?php echo $this->url('service/default', array('action'=>'filtres')) ?>">
    <?php echo $this->filtresListe; ?>
</div>
<?php endif; ?>

<?php if ('afficher' === $action ): ?>

    <?php if ($renderReferentiel): ?>
    <h2>Référentiel
        <?php 
        $urlSaisir = $this->url('service-ref/default', array('action' => 'saisir'));
        ?>
        <a class="ajax-modal services-ref btn btn-default pull-right" data-event="service-ref-add-message" href="<?php echo $urlSaisir ?>" title="Ajouter/modifier les fonctions référentiel"><span class="glyphicon glyphicon-plus"></span> Saisir un nouveau référentiel</a>
    </h2>
    <?php echo $this->servicesRefListe; ?>
    <hr />
    <?php endif; ?>

    <?php if ($role instanceof \Application\Acl\IntervenantRole): ?>
    <?php echo $this->messenger()->setMessage(
            "Merci de saisir les heures effectuées <strong>sans majoration</strong>. Exemple: saisissez 1h CM et non 1,5h TD."); ?>
    <?php endif; ?>

    <?php $url = $this->url('service/default', array('action' => 'saisie')); ?>
    <?php if ($role instanceof \Application\Acl\IntervenantExterieurRole): ?>
        <a class="ajax-modal services btn btn-primary" data-event="service-add-message" href="<?php echo $url ?>" title="Ajouter un nouvel enseignement"><span class="glyphicon glyphicon-plus"></span> Je saisis</a>
    <?php else: ?>
    <h2>Enseignements prévisionnels
        <a class="ajax-modal services btn btn-default pull-right" data-event="service-add-message" href="<?php echo $url ?>" title="Ajouter un enseignement"><span class="glyphicon glyphicon-plus"></span> Saisir un nouveau service</a>
    </h2>
    <?php endif; ?>

    <?php echo $this->serviceListe( $services )->setRenderIntervenants($renderIntervenants)->render(); ?>

    <?php if ($role instanceof \Application\Acl\IntervenantRole): ?>
        <hr />
        <?php echo $this->workflow($role->getIntervenant(), $role)->navNext("J'ai terminé ma saisie, ") ?>
    <?php endif; ?>
    
<?php else:?>
        
    <?php echo $this->messenger()->setMessage('Cliquez sur "Afficher" pour afficher les enseignements.', \UnicaenApp\View\Helper\Messenger::INFO); ?>

<?php endif; ?>