<?php

$title = 'Enseignements';
if ($intervenant && $intervenant instanceof Application\Entity\Db\IntervenantPermanent){
    $title .= ' et référentiel';
}
if ($intervenant){
    $title .= ' <small>'.$intervenant.'</small>';
    $this->headTitle()->append($intervenant->getNomUsuel())->append("Enseignements");
}else{  
    $this->headTitle()->append("Enseignements");
}
?>

<h1 class="page-header"><?php echo $title; ?></h1>

<?php echo $this->messenger()->addMessagesFromFlashMessenger() ?>

<style>
    .modal-dialog { 
        width: 70%;
    }
    div.row {
        padding:1px;
    }
    th.heures, td.heures { width: 3em !important; }
</style>

<?php if (! $intervenant): ?>
<?php if ($this->isAllowed('ServiceListView', 'info-only-structure')): ?>
<?php echo $this->messenger()->setMessages(array('warning' => "Sont visibles ici les référentiels et les enseignements prévisionnels des intervenants affectés "
        . "ou enseignant dans votre structure de responsabilité ({$role->getStructure()}) ou l'une de ses sous-structures.")); ?>
<?php endif; ?>

<div id="filtres" data-url="<?php echo $this->url('service/default', array('action'=>'filtres')) ?>">
    <?php echo $this->filtresListe; ?>
</div>
<?php endif; ?>

<?php if ('afficher' === $action ): ?>

    <?php if ($this->isAllowed('ServiceListView', 'aide-intervenant')): ?>
        <?php echo $this->messenger()->setMessage(
                "Merci de saisir les heures effectuées <strong>sans majoration</strong>. Exemple: saisissez 1h CM et non 1,5h TD."); ?>
    <?php endif; ?>

    <?php if ($canAddService): ?>
    <?php $url = $this->url('service/default', array('action' => 'saisie')); ?>
    <a class="ajax-modal services btn btn-primary" data-event="service-add-message" href="<?php echo $url ?>"
       title="Ajouter un nouvel enseignement"><span class="glyphicon glyphicon-plus"></span> Je saisis</a>
    <?php endif; ?>
    <?php echo $this->serviceListe( $services )->setTypeVolumeHoraire($typeVolumeHoraire)->setIntervenant($intervenant)->render(); ?>

    <?php if ($renderReferentiel): ?>
        <h1>Référentiel</h1>
        <?php if ($canAddServiceReferentiel): ?>
            <?php $urlSaisir = $this->url('service-ref/default', array('action' => 'saisir')); ?>
            <a class="ajax-modal services-ref btn btn-primary" data-event="service-ref-add-message" href="<?php echo $urlSaisir ?>"
               accesskey=""title="Modifier le référentiel"><span class="glyphicon glyphicon-plus"></span> Je saisis</a>
        <?php endif; ?>
        <?php echo $this->servicesRefListe; ?>
        <hr />
    <?php endif; ?>
    <?php echo $this->formuleTotauxHetd; ?>
    <?php if ($role instanceof \Application\Acl\IntervenantRole): ?>
        <hr />
        <?php $url = $this->url('workflow', 
                array('action' => 'nav-next', 'intervenant' => $role->getIntervenant()->getSourceCode()),
                array('query' => array('route' => 'intervenant/services', 'prepend' => $prepend = "J'ai terminé ma saisie, "))) ?>
        <div id="wf-nav-next" data-url="<?php echo $url ?>">
            <?php echo $this->workflow($role->getIntervenant(), $role)->navNext($prepend) ?>
        </div>
    <?php endif; ?>

<?php else:?>

    <?php echo $this->messenger()->setMessage('Cliquez sur "Afficher" pour afficher les enseignements.', \UnicaenApp\View\Helper\Messenger::INFO); ?>

<?php endif; ?>
