<h1 class="page-header">Services <small>Année universitaire <?php echo $annee; ?></small></h1>

<?php
    echo $this->messenger()->setMessages(array('warning' => "Sont visibles ici les référentiels et les services prévisionnels des intervenants affectés "
        . "ou enseignant dans votre structure de responsabilité ou l'une de ses sous-structures."));
?>

<div id="filtres" data-url="<?php echo $this->url('service/default', array('action'=>'filtres')) ?>">
    <?php echo $this->filtresListe; ?>
</div>

<?php if ('afficher' === $action ): ?>

<table class="table table-hover table-bordered">
    <thead>
        <tr>
            <th style="width:40%" rowspan="2">Intervenant</th>
            <th style="width:40%" colspan="<?php echo count($typesIntervention); ?>">Services</th>
            <th style="width:10%" rowspan="2">Référentiel</th>
            <th style="width:10%" rowspan="2">Heures &Eacute;q. TD</th>
        </tr>
        <tr>
            <?php foreach( $typesIntervention as $ti ): ?>
                <th title="<?php echo $ti->getLibelle() ?>"><?php echo $ti ?></th>
            <?php endforeach; ?>
        </tr>
    </thead>
    <tbody>
        <?php foreach( $data as $intervenantId => $line ): ?>
        <tr>
            <?php
            $url = $this->url('service/intervenant', array('intervenant' => $line['intervenant']['SOURCE_CODE']));
            $intervenantPermanent = $line['intervenant']['TYPE_INTERVENANT_CODE'] === \Application\Entity\Db\TypeIntervenant::CODE_PERMANENT;
            $na = '<span title="Non applicable (intervenant vacataire))">NA</span>';
            ?>
            <td><a href="<?php echo $url ?>"><?php echo strtoupper($line['intervenant']['NOM_USUEL']) . ' ' . $line['intervenant']['PRENOM']; ?></a></td>
            <?php foreach( $typesIntervention as $ti ): ?>
            <td><?php echo isset($line['service'][$ti->getId()]) ? $line['service'][$ti->getId()] : 0 ?></td>
            <?php endforeach; ?>
            <td><?php echo array_key_exists('referentiel', $line) ? $line['referentiel'] : ($intervenantPermanent ? 0 : $na) ?></td>
            <td><?php echo $line['hetd'] = 'NC' ?></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<?php else: ?>
<?php echo $this->messenger()->setMessage('Cliquez sur "Afficher" pour afficher les services.', \UnicaenApp\View\Helper\Messenger::INFO); ?>
<?php endif; ?>
