<?php

$interne = $form->get('interne-externe')->getValue() == 'service-interne';

$form->prepare();

echo $this->form()->openTag($form);
if (! isset($context['intervenant'])){
    echo $this->formControlGroup($form->get('intervenant'));
}
echo $this->formControlGroup($form->get('interne-externe'), 'formButtonGroup');
echo '<div id="element-interne" '.(($interne) ? '' : 'style="display:none"').'>'.$this->fieldsetElementPedagogiqueRecherche($form->get('elementPedagogique')).'</div>';
echo '<div id="element-externe" '.(($interne) ? 'style="display:none"' : '').'>'.$this->formControlGroup($form->get('etablissement')).'</div>';
echo $this->formRow($form->get('submit'));
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag().'<br />';

echo $this->formErrors( $form );
if ($errors) echo $this->messenger()->setMessages(array(UnicaenApp\View\Helper\Messenger::ERROR => array($errors)));