<?php

if (! isset($context['etablissement'])){
    throw new Exception('Contexte Etablissement non fourni');
}

$etablissementParam = (integer)$context['etablissement']->getId();
$etablissementValue = (integer)$form->get('etablissement')->getValue();

if (null == $etablissementValue || $etablissementValue == $etablissementParam){
    $interne = true;
}else{
    $interne = false;
}

/*$interneExterne = new \Zend\Form\Element\Radio;
$interneExterne->setLabel('Service effectué : ');
$interneExterne->setName('interne-externe');
$interneExterne->setCheckedValue('service-interne');
$interneExterne->setValueOptions(array(
                     'service-interne' => 'en interne',
                     'service-externe' => 'dans un autre établissement',
     ));
$interneExterne->setLabelAttributes( array('class' => 'btn btn-primary'));*/

//$form->setAttribute('action', $this->url('album', array('action' => 'add')));

    $form->prepare();
    echo $this->form()->openTag($form);
    if (! isset($context['intervenant'])){
        echo $this->formControlGroup($form->get('intervenant'));
    }

    ?><div class="form-group">
    <label class="control-label" for="service-interne">Service effectué : </label>
    <br />
    <div class="btn-group" data-toggle="buttons">
      <label class="btn btn-default <?php echo ($interne) ? 'active' : '' ?>">
        <input type="radio" name="interne-externe" id="service-interne" onchange="serviceShowInterneExterne(this.id)"> en interne
      </label>
      <label class="btn btn-default <?php echo ($interne) ? '' : 'active' ?>">
        <input type="radio" name="interne-externe" id="service-externe" onchange="serviceShowInterneExterne(this.id)"> dans un autre établissement
      </label>
    </div>
</div>
<?php
    echo '<div id="element-interne" '.(($interne) ? '' : 'style="display:none"').'>'.$this->formControlGroup($form->get('elementPedagogique')).'</div>';
    echo '<div id="element-externe" '.(($interne) ? 'style="display:none"' : '').'>'.$this->formControlGroup($form->get('etablissement')).'</div>';
    echo $this->formRow($form->get('submit'));
    echo $this->formHidden($form->get('security'));
    echo $this->formHidden($form->get('id'));
    echo $this->form()->closeTag();
    echo $this->formErrors( $form );

    if ($errors) echo $this->messenger()->setMessages(array(UnicaenApp\View\Helper\Messenger::ERROR => array($errors)));
?>

