<?php

use Framework\Authorize\Authorize;
use UnicaenApp\Util;

/**
 * @var $this               \Application\View\Renderer\PhpRenderer
 * @var $structureElement   \Laminas\Form\Element\Select
 * @var $structure          \Lieu\Entity\Db\Structure
 * @var $dotations          array
 * @var $previsionnelValide float
 * @var $liquidation        array
 */

echo '<h1 class="page-header">Budget ' . $annee . ' - Engagements & Liquidation</h1>';

if ($structureElement) {
    echo $this->formControlGroup($structureElement);
}

?>

<?php if ($structure): ?>
    <div class="engagement">
        <div class="row">

            <!-- Abondements par types de ressources -->
            <?php foreach ($dotations['typesRessources'] as $dtr):
                $canEdit = $this->isAllowed($dtr['entity'], $dtr['entity']->getPrivilegeBudgetEdition());
                ?>
                <div class="col-md-6">
                    <h2><?= $dtr['entity']->getLibelle() ?></h2>
                    <table class="table table-bordered table-hover">
                        <?php foreach ($dtr['abondements'] as $libelle => $abondement): ?>
                            <tr>
                                <td><?= $abondement['libelle'] ?></td>
                                <td class="dotation"><?php fdot($this, $dtr['entity'], $libelle, $abondement, $canEdit) ?></td>
                            </tr>
                        <?php endforeach; ?>
                        <tr>
                            <th>Total</th>
                            <td class="dotation"><?php fdot($this, $dtr['entity'], null, $dtr['total'], $canEdit) ?></td>
                        </tr>
                    </table>
                </div>
            <?php endforeach; ?>
        </div>
        <!-- Liquidation -->
        <div class="liquidation row">
            <h2>Liquidation</h2>
            <table class="table table-bordered">
                <tr>
                    <th rowspan="2">&nbsp;</th>
                    <th rowspan="2">Prévisionnel</th>
                    <th colspan="<?= count($dotations['typesRessources']) ?>">Réalisé (mises en paiement demandées)</th>
                </tr>
                <tr>
                    <?php foreach ($dotations['typesRessources'] as $dtr): ?>
                        <th style="width:12em"><?= $dtr['entity']->getLibelle() ?></th>
                    <?php endforeach; ?>
                </tr>
                <tr>
                    <th>Dotation</th>
                    <td class="hetd"><?= Util::formattedNumber($dotations['total']['heures']) ?><i
                                class="label">HETD</i></td>
                    <?php foreach ($dotations['typesRessources'] as $dtr): ?>
                        <td class="hetd"><?= Util::formattedNumber($dtr['total']['heures']) ?><span class="label">HETD</span>
                        </td>
                    <?php endforeach; ?>
                </tr>
                <tr>
                    <th>HETD positionnées</th>
                    <td class="hetd"><?= Util::formattedNumber($previsionnelValide) ?><span class="label">HETD</span></td>
                    <?php foreach ($dotations['typesRessources'] as $dtr): ?>
                        <td class="hetd"><?= Util::formattedNumber($liquidation[$dtr['entity']->getId()]['dmep']) ?><i
                                    class="label">HETD</i></td>
                    <?php endforeach; ?>
                </tr>
                <tr>
                    <th>Solde</th>
                    <td class="hetd"><?= Util::formattedNumber($dotations['total']['heures'] - $previsionnelValide) ?><i
                                class="label">HETD</i></td>
                    <?php foreach ($dotations['typesRessources'] as $dtr): ?>
                        <td class="hetd"><?= Util::formattedNumber($liquidation[$dtr['entity']->getId()]['solde']) ?><i
                                    class="label">HETD</i></td>
                    <?php endforeach; ?>
                </tr>
            </table>
        </div>
    </div>
    <?php if ($this->isAllowed(Authorize::controllerResource(\Paiement\Controller\BudgetController::class, 'export'))): ?>
        <div class="budget-export">
            <a href="<?= $this->url('budget/export', ['structure' => $structure->getId()]) ?>">
                <i class="fas fa-download"></i>
                Export des données de paiement au format CSV
            </a>
        </div>
    <?php endif; ?>
<?php endif; ?>

<?php function fdot ($view, $typeRessource, $libelle, array $data, $canEdit = true) /* Formatage d'une dotation */
{

    $titleA1 = 'Année ' . $data['anneeCivile1']['annee'] . ' (chiffre en HETD)';
    $titleA2 = 'Année ' . $data['anneeCivile2']['annee'] . ' (chiffre en HETD)';
    $titleA  = 'Année universitaire ' . $data['annee']
        . ' (dont ' . Util::formattedFloat($data['anneeCivile1']['s2'], \NumberFormatter::DECIMAL, 2) . ' au titre de ' . $data['anneeCivile1']['annee']
        . ' et ' . Util::formattedFloat($data['anneeCivile2']['s1']) . ' au titre de ' . $data['anneeCivile2']['annee'] . ' chiffre en HETD)';

    if ($canEdit) {
        $params1              = [
            'annee'         => $data['anneeCivile1']['annee'],
            'structure'     => $view->structure->getId(),
            'typeRessource' => $typeRessource->getId(),
        ];
        $params1['dotation1'] = (isset($data['anneeCivile1']['s1Entity'])) ? $data['anneeCivile1']['s1Entity']->getId() : 'null';
        $params1['dotation2'] = (isset($data['anneeCivile1']['s2Entity'])) ? $data['anneeCivile1']['s2Entity']->getId() : 'null';
        $dotEditUrl1          = $view->url('budget/saisie-dotation', $params1, ['query' => ['libelle' => $libelle]]);


        $params2              = [
            'annee'         => $data['anneeCivile2']['annee'],
            'structure'     => $view->structure->getId(),
            'typeRessource' => $typeRessource->getId(),
        ];
        $params2['dotation1'] = (isset($data['anneeCivile2']['s1Entity'])) ? $data['anneeCivile2']['s1Entity']->getId() : 'null';
        $params2['dotation2'] = (isset($data['anneeCivile2']['s2Entity'])) ? $data['anneeCivile2']['s2Entity']->getId() : 'null';
        $dotEditUrl2          = $view->url('budget/saisie-dotation', $params2, ['query' => ['libelle' => $libelle]]);
    }

    ?>
    <div class="container">
        <div class="row">
            <div class="ha ha1 col" title="<?= $titleA1 ?>">
                <?= Util::formattedNumber($data['anneeCivile1']['heures']) ?><span class="label">HETD</span>
                <?php if ($canEdit): ?>
                    <a href="<?= $dotEditUrl1 ?>" class="mod-ajax" data-submit-reload="true"
                       title="<?= $libelle ? 'Modifier la dotation' : 'Nouvel abondement' ?>">
                        <i class="fas fa-<?= $libelle ? 'pen-to-square' : 'plus' ?>"></i>
                    </a>
                <?php endif; ?>
            </div>
            <div class="ha ha2 col" title="<?= $titleA2 ?>">
                <?= Util::formattedNumber($data['anneeCivile2']['heures']) ?><span class="label">HETD</span>
                <?php if ($canEdit): ?>
                    <a href="<?= $dotEditUrl2 ?>" class="mod-ajax" data-submit-reload="true"
                       title="<?= $libelle ? 'Modifier la dotation' : 'Nouvel abondement' ?>">
                        <i class="fas fa-<?= $libelle ? 'pen-to-square' : 'plus' ?>"></i>
                    </a>
                <?php endif; ?>
            </div>
        </div>
        <div class="row">
            <div class="ha ha3 col" title="<?= $titleA ?>">
                <?= Util::formattedNumber($data['heures']) ?><span class="label">HETD</span>
            </div>
        </div>
    </div>

<?php }