<?php 
use Application\Service\Indicateur\AbstractIndicateurImpl;
/* @var $indicateurImpl AbstractIndicateurImpl */
?>

<h1 class="page-header">Notification indicateurs</h1>

<style>
    .indicateur { width: 35%; }
    .date { width: 5%; }
</style>

<table class="table table-condensed table-bordered">
    <thead>
        <tr>
            <th>Personne</th>
            <th class="indicateur">Indicateur</th>
            <th>Structure concernée</th>
            <th>Fréquence</th>
            <th class="date">Date d'abonnement</th>
            <th class="date">Dernière notif</th>
            <th class="date">Prochaine notif éventuelle</th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($this->nis as $ni): /* @var $ni \Application\Entity\Db\NotificationIndicateur */?>
        <?php 
        $indicateurImpl = $this->serviceIndicateur->getIndicateurImpl($ni->getIndicateur(), $ni->getStructure()); 
        $url = $this->url("notification/indicateur-fetch-title", [], ['query' => ['id' => $ni->getId()]]);
        ?>
        <tr>
            <td><?php echo $ni->getPersonnel() ?></td>
            <td class="indicateur"><?php echo $ni->getIndicateur() ?> <a href="#" class="fetch-title pull-right" data-url="<?php echo $url ?>">Voir</a></td>
            <td><?php echo $ni->getStructure() ?: "(Toutes)" ?></td>
            <td><?php echo $ni->getFrequenceToString() ?></td>
            <td class="date"><?php echo $ni->getDateAbonnementToString() ?></td>
            <td class="date"><?php echo $ni->getDateDernNotifToString() ?></td>
            <td class="date"><?php echo $ni->getDateProchaineNotifToString() ?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<script>
    $(function() {
        $("a.fetch-title").click(function() {
            var that = $(this);
            $.get(that.addClass("loading").data('url')).done(function(data) { that.parent().html(data.title); });
            return false;
        });
    });
</script>