<?php echo $this->form()->openTag($this->form->setAttribute('id','mail-form')); ?>

<?php echo $this->formControlGroup($this->form->get('from')->setLabel("Expéditeur du mail")->setAttribute('disabled','disabled')) ?>
<?php echo $this->formControlGroup($this->form->get('subject')->setLabel("Objet du mail")) ?>
<?php echo $this->formControlGroup($this->form->get('body')->setLabel("Corps du mail")->setAttributes(['rows'=>15,'id'=>'body'])) ?>
<?php echo $this->formSubmit($this->form->get('submit')->setValue("Envoyer")->setAttribute('class', 'btn btn-primary')) ?>

<?php echo $this->form()->closeTag(); ?>


<script type="text/javascript">
    $(function() {
        var selector = "textarea#<?php echo $this->form->get('body')->getAttribute('id') ?>";
        var form     = $("form#<?php echo $this->form->getAttribute('id') ?>");
        var message  = "Êtes-vous sûr(e) de vouloir envoyer ce message aux intervenants (<?php echo $this->count ?>) ?";

        installEditor(selector, form);
    
        //  avant de POSTer
        form.submit(function(e) {
            if (! confirm(message)) {
                e.preventDefault();
                e.stopPropagation();
            }
        });
    });
    
    // fermeture de la modale lorsque nécessaire
    $(document).on('event-send-mail', "body", function(event, data) {
        event.div.modal('hide');
//        var targetSelector = event.a.data('target');
//        event.a.parents(targetSelector).refresh([], function() { $(this).hide().fadeIn(); });
    });
        
    /**
     * Installation d'un éditeur WYSIWYG (vers HTML) : http://www.tinymce.com
     * NB: l'inclusion du script de TinyMCE est faite dans la vue "mère" (application/indicateur/result.phtml).
     * @param {string} selector 
     * @param {object} form 
     */
    function installEditor(selector, form)
    {
        tinymce.editors = [];
        tinymce.init({
            selector:   selector,
            language : 'fr_FR',
            width:      '100%',
            height:     250,
            plugins:    "link",
            statusbar:  false,
            menubar:    false,
            toolbar: "bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link | undo redo"
        });
        // Prevent bootstrap dialog from blocking focusin
        $(document).on('focusin', function(e) {
            if ($(e.target).closest(".mce-window").length) {
                e.stopImmediatePropagation();
            }
        });
        // Indispensable pour que le contenu du textarea soit mis à jour avant de POSTer
        form.submit(function() {
            tinymce.triggerSave();
        });
    }
</script>