<?php

use Application\Provider\Privilege\Privileges;
use Contrat\Assertion\ContratAssertion;
use Contrat\Entity\Db\TblContrat;

/**
 * @var $this                       \Application\View\Renderer\PhpRenderer
 * @var $tblContrat                 TblContrat
 * @var $contratSignatureActivation boolean
 * @var $libelleCircuitSignature    string
 * @var $infosSignature             array
 */

$contrat = $tblContrat->getContrat();

$validation     = $contrat->getValidation();
$retourSigne    = $contrat->getDateRetourSigne();
$dateEnvoiEmail = $contrat->getDateEnvoiEmail();
$uploader       = $this->uploader();

$urlExport = $this->isAllowed($contrat, ContratAssertion::PRIV_EXPORT)
        ? $this->url('contrat/exporter', ['contrat' => $contrat->getId()]) // oui car on peut le voir!!
        : null;

$urlLister = $this->isAllowed($contrat, ContratAssertion::PRIV_LISTER_FICHIERS)
        ? $this->url('contrat/lister-fichier', ['contrat' => $contrat->getId()], [], true)
        : null;

$fichiers                    = $contrat->getFichier();
$urlTelechargerContratSigned = $this->isAllowed($contrat, ContratAssertion::PRIV_LISTER_FICHIERS)
        ? (count($fichiers)) ? $this->url('contrat/telecharger-fichier', ['contrat' => $contrat->getId(), 'fichier' => $fichiers[0]->getId(), 'nomFichier' => $fichiers[0]->getNom()]) : null
        : null;

$urlEmail = $this->isAllowed($contrat, Privileges::CONTRAT_ENVOI_EMAIL)
        ? $this->url('contrat/envoyer-mail', ['contrat' => $contrat->getId()], ['modal' => 1]) . '?modal=1'
        : null;

$urlCreerProcessSignature = $this->isAllowed($contrat, Privileges::CONTRAT_ENVOYER_SIGNATURE_ELECTRONIQUE)
        ? $this->url('contrat/creer-process-signature', ['contrat' => $contrat->getId()])
        : null;

$urlSupprimerProcessSignature = $this->isAllowed($contrat, Privileges::CONTRAT_ENVOYER_SIGNATURE_ELECTRONIQUE)
        ? $this->url('contrat/supprimer-process-signature', ['contrat' => $contrat->getId()])
        : null;

$urlRafraichirProcessSignature = $this->isAllowed($contrat, Privileges::CONTRAT_ENVOYER_SIGNATURE_ELECTRONIQUE)
        ? $this->url('contrat/rafraichir-process-signature', ['contrat' => $contrat->getId()])
        : null;

$urlValidation = $this->isAllowed($contrat, Privileges::CONTRAT_VALIDATION)
        ? $this->url('contrat/valider', ['contrat' => $contrat->getId()])
        : null;

$urlDevalidation = $this->isAllowed($contrat, Privileges::CONTRAT_DEVALIDATION)
        ? $this->url('contrat/devalider', ['contrat' => $contrat->getId()])
        : null;

$urlSaisieRetour = $this->isAllowed($contrat, Privileges::CONTRAT_SAISIE_DATE_RETOUR_SIGNE)
        ? $this->url('contrat/saisir-retour', ['contrat' => $contrat->getId()])
        : null;

$urlAjouter = $this->isAllowed($contrat, ContratAssertion::PRIV_AJOUTER_FICHIER)
        ? $this->url('contrat/deposer-fichier', ['contrat' => $contrat->getId()], [], true)
        : null;

$urlSuppression = $this->isAllowed($contrat, Privileges::CONTRAT_SUPPRESSION)
        ? $this->url('contrat/supprimer', ['contrat' => $contrat->getId()])
        : null;

$disableEmail = (empty($emailIntervenant)) ? true : false;

if ($urlAjouter) {
    $uploader->setUrl($urlAjouter);
}

$card = ($retourSigne !== null) ? 'success' : ($validation ? 'info' : 'default');

?>

<div class="contrat card bg-<?= $card ?>" id="contrat-<?= $contrat->getId() ?>">
    <div class="card-header card-header-h3">
        <?php if ($urlExport && $urlEmail && !$contratSignatureActivation): ?>
            <span class="float-end">
                <?php if ($disableEmail): ?>
                    <a class="disabled btn btn-seconrary" href="<?= $urlEmail ?>"
                       title="L'intervenant du contrat n'a pas renseigné son email.">
                <?php endif; ?>
                        <?php if (!$disableEmail): ?>
                    <a data-event="envoi-mail-contrat" class="ajax-modal btn btn-secondary"
                       title="Envoyer le contrat par mail"

                       href="<?= $urlEmail ?>">
                <?php endif; ?>
                <i class="fas fa-paper-plane-top"></i> Envoyer par mail
            </a>
            </span>
        <?php endif; ?>
        <!-- Lien de téléchargement du fichier -->
        <?php if ($urlExport): ?>

            <span class="float-end">
            <a class="btn btn-secondary" href="<?= $urlExport ?>" title="Exporter le contrat/avenant au format PDF">
                <i class="fas fa-upload"></i> Exporter en PDF
            </a>
            </span>
        <?php endif; ?>

        <h3><?= $contrat->toString() ?>
            <?php if ($contrat->getStructure() != null): ?>- <?= $contrat->getStructure() ?><?php endif; ?></h3>
    </div>

    <div class="card-body">
        <!-- Informations -->
        <ul style="list-style-type: none">
            <li><i class="fas fa-thumbs-up"></i> Créé
                le <?= $contrat->getHistoCreation()->format(\Application\Constants::DATE_FORMAT) ?>
                par <?= $this->utilisateur($contrat->getHistoCreateur()) ?></li>
            <?php if ($validation): ?>
                <li><i class="fas fa-thumbs-up"></i> Validé
                    le <?= $validation->getHistoCreation()->format(\Application\Constants::DATE_FORMAT) ?>
                    par <?= $this->utilisateur($validation->getHistoCreateur()) ?></li>
            <?php endif; ?>
            <?php if ($dateEnvoiEmail): ?>
                <li><i class="fas fa-thumbs-up"></i> Envoyé par email
                    le <?= $dateEnvoiEmail->format(\Application\Constants::DATE_FORMAT) ?>
                </li>
            <?php endif; ?>
            <?php if (!$contrat->getProcessSignature() && $contratSignatureActivation && $contrat->getValidation()): ?>
                <li><i class="fas fa-hourglass-start"></i> En attente d'envoi pour signature électronique</li>
            <?php endif; ?>

            <?php if (array_key_exists($contrat->getId(), $infosSignature)): ?>
                <?php foreach ($infosSignature[$contrat->getId()]['processSignature'] as $info): ?>
                    <li>
                        <?php if (isset($info['urlDocumentSigned'])): ?>
                            <i class="fas fa-signature"></i> <?= $info['label'] . ' :  (<a href="' . $info['urlDocumentSigned'] . '" target="_blank">' . $info['labelInfos'] . '</a>)' ?>
                        <?php else: ?>
                            <i class="fas fa-signature"></i> <?= $info['label'] . ' :  (' . $info['labelInfos'] . ')' ?>
                        <?php endif; ?>
                    </li>
                <?php endforeach; ?>
            <?php endif; ?>
            <?php if ($contrat->getDateRetourSigne()): ?>
                <i class="fas fa-signature"></i> Signature électronique terminée le <?= $contrat->getDateRetourSigne()->format('d/m/Y à H:i'); ?>
            <?php endif; ?>


        </ul>

        <div>
            <hr/>
            <a title="Cliquez pour afficher/masquer les enseignements concernés"
               href="#details-enseignements-contrat-<?= $contrat->getId() ?>"
               role="button"
               aria-expanded="false"
               aria-controls="details-enseignements-contrat-<?= $contrat->getId() ?>"
               data-bs-toggle="collapse"
            >Enseignements concernés
                <small>(cliquez pour afficher/cacher)</small>
            </a>
            <div class="collapse" id="details-enseignements-contrat-<?= $contrat->getId() ?>">
                <?= $this->partial('contrat/contrat/partial/contrat-heures', ['tblContrat' => $tblContrat]); ?>
            </div>
        </div>
    </div>

    <?php if ($urlValidation || $urlSaisieRetour || $urlDevalidation || $urlSuppression || $urlCreerProcessSignature): ?>
        <div class="card-footer">
            <!-- Actions -->
            <?php if ($urlValidation): ?>
                <a
                        href="<?= $urlValidation ?>"
                        class="btn btn-primary pop-ajax"
                        title="Valider le contrat"
                        data-content="Confirmez-vous cette validation ?"
                        data-confirm="true"
                        data-confirm-button="Je confirme"
                        data-cancel-button="Non"
                        data-submit-reload="true"
                >
                    <i class="fas fa-thumbs-up"></i> Valider
                </a>
            <?php endif; ?>

            <!--UX Button waiting-->
            <!--waiting envoyer et rafraichir-->
            <button id="waiting-signature" class=" disabled  d-none btn btn-primary"
                    title="En cours d'exécution">
                <span id="spinner" aria-hidden="true" class="spinner-border spinner-border-sm" role="status"></span>
                &nbsp;Veuillez patienter...
            </button>

            <?php if (!$contrat->getProcessSignature() && $contratSignatureActivation && !empty($urlCreerProcessSignature)): ?>

                <a id="envoyer-signature" href="<?= $urlCreerProcessSignature ?>" class="btn btn-primary"
                   title="Envoyer dans circuit '<?= $libelleCircuitSignature; ?>'">
                    <i class="fas fa-signature"></i>
                    Envoyer pour signature
                </a>

            <?php endif; ?>

            <?php if ($urlRafraichirProcessSignature && $contrat->getProcessSignature() && empty($retourSigne)): ?>
                <a id="refresh-signature" href="<?= $urlRafraichirProcessSignature ?>" class="btn btn-primary">
                    <i class="fas fa-arrows-rotate"></i>
                    Rafraîchir la signature
                </a>

            <?php endif; ?>
            <?php if ($contrat->getProcessSignature() && ($urlTelechargerContratSigned || $urlCreerProcessSignature)): ?>
                <!--https://ose.unicaen.fr/contrat/37471/telecharger-fichier/156945/GAUDET_Yann-Yves_Contrat.pdf-->
                <a href="<?= $urlTelechargerContratSigned ?>" target="_blank" class="btn btn-primary">
                    <i class="fas fa-eye"></i>
                    <?php if ($contrat->getDateRetourSigne()): ?>
                        Voir le contrat signé
                    <?php else: ?>
                        Voir le contrat
                    <?php endif; ?>
                </a>

            <?php endif; ?>

            <?php if ($urlSupprimerProcessSignature && $contrat->getProcessSignature()): ?>
                <a id="supprimer-signature" href="<?= $urlSupprimerProcessSignature ?>" class="btn btn-danger">
                    <i class="fas fa-trash"></i>
                    Supprimer la procédure de signature
                </a>

            <?php endif; ?>

            <!--UX Button waiting-->
            <!--waiting supprimer-->
            <button id="waiting-delete-signature" class=" disabled  d-none btn btn-danger"
                    title="Signature en cours de suppression">
                <span id="spinner" aria-hidden="true" class="spinner-border spinner-border-sm" role="status"></span>
                &nbsp;Veuillez patienter...
            </button>


            <?php if ($urlSaisieRetour && !$contratSignatureActivation): ?>
                <a href="<?= $urlSaisieRetour ?>" class="btn btn-primary pop-ajax" data-submit-reload="true">
                    <i class="fas fa-calendar-days"></i>
                    <?= $contrat->getDateRetourSigne() ? 'Modifier' : 'Saisir' ?> la date de retour signé
                </a>
            <?php endif; ?>

            <?php if ($urlDevalidation && !$contrat->getProcessSignature()): ?>
                <a
                        href="<?= $urlDevalidation ?>"
                        class="btn btn-danger pop-ajax"
                        data-submit-reload="true"
                        data-content="<p class='lead text-danger'><strong>Attention!</strong> Confirmez-vous cette dévalidation ?</p>"
                        data-confirm="true"
                        data-confirm-button="Oui"
                        data-cancel-button="Non"
                >
                    <i class="fas fa-thumbs-down"></i> Dévalider
                </a>
            <?php endif; ?>

            <?php if ($urlSuppression): ?>
                <a
                        href="<?= $urlSuppression ?>"
                        class="btn btn-danger pop-ajax"
                        data-content="<p class='lead text-danger'><strong>Attention!</strong> Confirmez-vous la suppression <?= lcfirst($contrat->toString(true, true)) ?> ?</p>"
                        data-confirm="true"
                        data-confirm-button="Oui"
                        data-cancel-button="Non"
                        data-submit-reload="true"
                >
                    <i class="fas fa-trash-can"></i> Supprimer
                </a>
            <?php endif; ?>
        </div>
    <?php endif; ?>
</div>