<?php

use Application\View\Renderer\PhpRenderer;
use Contrat\Entity\Db\TblContrat;
use UnicaenApp\Util;

/**
 *
 * @var PhpRenderer $this
 * @var TblContrat  $tblContrat
 *
 */


$enseignements          = [];
$enseignementsExterieur = [];
$referentiels           = [];
$missions               = [];

$vhs = $tblContrat->getVolumesHoraires();


//On parcours les volumes horaires, on les ranges par type et trie par periode.
foreach ($vhs as $vh) {
    if (!empty($vh->getMission())) {
        $sid = $vh->getMission()->getId();
        if (!isset($missions[$sid])) {
            $missions[$sid] = [
                    'typeMission' => $vh->getMission()->getTypeMission(),
                    'mission'     => $vh->getMission()->getLibelle(),
                    'heures'      => 0.0];
        }
        $missions[$sid]['heures'] += $vh->getHeures();
    }

    if (!empty($vh->getServiceReferentiel())) {
        if (!empty($vh->getServiceReferentiel()->getFonctionReferentiel())) {
            $frId = $vh->getServiceReferentiel()->getFonctionReferentiel()->getId();
            if (!isset($enseignements[$frId])) {
                $referentiels[$frId]           = [
                        'fonctionLibelle' => $vh->getServiceReferentiel()->getFonctionReferentiel()->getLibelleLong(),
                        'fonctionCode'    => $vh->getServiceReferentiel()->getFonctionReferentiel()->getCode(),
                        'heures'          => $vh->getHeures()
                ];
                if (array_key_exists('autres', $referentiels[$frId])) {
                    $referentiels[$frId]['autres'] += $vh->getAutres();
                }
            }
        }
    }

    if (!empty($vh->getService())) {
        if (!empty($vh->getService()->getElementPedagogique())) {
            $epId    = $vh->getService()->getElementPedagogique()->getId();
            $periode = $vh->getVolumeHoraire()->getPeriode() ? $vh->getVolumeHoraire()->getPeriode()->getCode() : 'N/A';
            $service = $vh->getService();
            $etape = ($service->getEtape()) ?? $service->getElementPedagogique()->getEtape();

            if (!isset($enseignements[$periode][$epId])) {
                $enseignements[$periode][$epId] = [
                    'etapeId'                   => $etape->getId(),
                    'etapeLibelle'              => $etape->getLibelle(),
                    'etapeCode'                 => $etape->getCode(),
                    'periode'                   => $periode,
                    'elementPedagogiqueId'      => $vh->getService()->getElementPedagogique()->getId(),
                    'elementPedagogiqueLibelle' => $vh->getService()->getElementPedagogique()->getLibelle(),
                    'elementPedagogiqueCode'    => $vh->getService()->getElementPedagogique()->getCode(),
                    'cm'                        => 0.0,
                    'td'                        => 0.0,
                    'tp'                        => 0.0,
                    'autres'                    => 0.0,
                ];
            }
            $enseignements[$periode][$epId]['cm']     += $vh->getCm();
            $enseignements[$periode][$epId]['td']     += $vh->getTd();
            $enseignements[$periode][$epId]['tp']     += $vh->getTp();
            $enseignements[$periode][$epId]['autres'] += $vh->getAutres();
        } else {
            $ee      = $vh->getService()->getId();
            $periode = $vh->getVolumeHoraire()->getPeriode()->getCode();
            if (!isset($enseignementsExterieur[$periode][$ee])) {
                $enseignementsExterieur[$periode][$ee] = [
                        'periode'       => $periode,
                        'etablissement' => $vh->getService()->getEtablissement()->getLibelle(),
                        'description'   => $vh->getService()->getDescription(),
                        'cm'            => 0.0,
                        'td'            => 0.0,
                        'tp'            => 0.0,
                        'autres'        => 0.0,
                ];
            }

            $enseignementsExterieur[$periode][$ee]['cm']     += $vh->getCm();
            $enseignementsExterieur[$periode][$ee]['td']     += $vh->getTd();
            $enseignementsExterieur[$periode][$ee]['tp']     += $vh->getTp();
            $enseignementsExterieur[$periode][$ee]['autres'] += $vh->getAutres();
        }
    }
}


?>

<?php
if (!empty($enseignements)):
    ksort($enseignements); ?>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th>Formation</th>
            <th>Période</th>
            <th>Enseignement</th>
            <th>CM</th>
            <th>TD</th>
            <th>TP</th>
            <th>Autres</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($enseignements as $enseignementParPeriode): ?>
            <?php foreach ($enseignementParPeriode as $enseignement): ?>
                <tr>
                    <td>

                        <small class="badge bg-secondary" style="font-size:8pt"
                               title="Enseignement mutualisé entre plusieures formations. Seule la formation principale est présentée ci-dessous">Enseignement
                            mutualisé</small><br/>

                        <?php $url = $this->url('of/etape/voir', ['etape' => $enseignement['etapeId']]); ?>
                        <a href="<?php echo $url ?>"
                           class="ajax-modal"><?php echo $enseignement['etapeLibelle'] ?>
                            (<?php echo $enseignement['etapeCode'] ?>
                            )
                        </a>

                    </td>
                    <td>
                        <?php echo $enseignement['periode'] ?>
                    </td>
                    <td>
                        <?php $url = $this->url('of/element/voir', ['elementPedagogique' => $enseignement['elementPedagogiqueId']]); ?>
                        <a href="<?php echo $url ?>"
                           class="ajax-modal"><?php echo $enseignement['elementPedagogiqueLibelle'] ?>
                            (<?php echo $enseignement['elementPedagogiqueCode'] ?>)
                        </a>

                    </td>
                    <td>
                        <?php echo Util::formattedFloat($enseignement['cm']) ?>
                    </td>
                    <td>
                        <?php echo Util::formattedFloat($enseignement['td']) ?>
                    </td>
                    <td>
                        <?php echo Util::formattedFloat($enseignement['tp']) ?>
                    </td>
                    <td>
                        <?php echo Util::formattedFloat($enseignement['autres']) ?>
                    </td>
                </tr>
            <?php endforeach; ?>
        <?php endforeach; ?>
        </tbody>
    </table>
<?php endif; ?>

<?php if (!empty($referentiels)): ?>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th>Fonction</th>
            <th>Heures</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($referentiels as $referentiel): ?>
            <tr>
                <td>
                    <?php echo $referentiel['fonctionLibelle'] ?>
                    (<?php echo $referentiel['fonctionCode'] ?>)
                </td>
                <td>
                    <?php echo $referentiel['heures'] ?>
                </td>

            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
<?php endif; ?>
<?php if (!empty($missions)): ?>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th>Type de mission</th>
            <th>Libellé de mission</th>
            <th>Heures</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($missions as $mission): ?>
            <tr>
                <td>
                    <?php echo $mission['typeMission'] ?>
                </td>
                <td>
                    <?php echo $mission['mission'] ?>
                </td>
                <td>
                    <?php echo Util::formattedFloat($mission['heures']) ?>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
<?php endif; ?>
<?php if (!empty($enseignementsExterieur)):
    ksort($enseignementsExterieur); ?>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th>Etablissement</th>
            <th>Description</th>
            <th>Semestre</th>
            <th>CM</th>
            <th>TD</th>
            <th>TP</th>
            <th>Autres</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($enseignementsExterieur as $enseignementExterieurParPeriode): ?>
            <?php foreach ($enseignementExterieurParPeriode as $enseignementExterieur): ?>
                <tr>
                    <td>
                        <?= $enseignementExterieur['etablissement'] ?>
                    </td>
                    <td>
                        <?= $enseignementExterieur['description'] ?>
                    </td>
                    <td>
                        <?= $enseignementExterieur['periode'] ?>
                    </td>
                    <td>
                        <?php echo Util::formattedFloat($enseignementExterieur['cm']) ?>
                    </td>
                    <td>
                        <?php echo Util::formattedFloat($enseignementExterieur['td']) ?>
                    </td>
                    <td>
                        <?php echo Util::formattedFloat($enseignementExterieur['tp']) ?>
                    </td>
                    <td>
                        <?php echo Util::formattedFloat($enseignementExterieur['autres']) ?>
                    </td>
                </tr>
            <?php endforeach; ?>
        <?php endforeach; ?>
        </tbody>
    </table>
<?php endif; ?>
