<?php

use Application\View\Renderer\PhpRenderer;
use Service\Entity\Db\TypeService;
use Contrat\Entity\Db\TblContrat;

/**
 *
 * @var PhpRenderer    $this
 * @var TblContrat $tblContrat
 *
 */


$enseignements = [];
$enseiegnementsExterieur = [];
$referentiels = [];
$missions = [];

$vhs = $tblContrat->getVolumesHoraires();
foreach($vhs as $vh) {
    /* @todo */
}



?>

<?php
if (isset($services[TypeService::CODE_ENSEIGNEMENT])): ?>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th>Formation</th>
            <th>Période</th>
            <th>Enseignement</th>
            <th>CM</th>
            <th>TD</th>
            <th>TP</th>
            <th>Autre</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($services[TypeService::CODE_ENSEIGNEMENT] as $element): ?>
            <tr>
                <td>
                    <?php if ($element->getService() && $element->getService()->getElementPedagogique()
                            && $element->getService()->getElementPedagogique()->getCheminPedagogique()->count() > 1): ?>
                        <small class="badge bg-secondary" style="font-size:8pt"
                               title="Enseignement mutualisé entre plusieures formations. Seule la formation principale est présentée ci-dessous">Enseignement
                            mutualisé</small><br/>
                    <?php endif; ?>
                    <?php if ($element->getService()): ?>
                    <?php $url = $this->url('of/etape/voir', ['etape' => $element->getService()->getElementPedagogique()->getEtape()->getId()]); ?>


                    <a href="<?php echo $url ?>"
                       class="ajax-modal"><?php echo $element->getService()->getElementPedagogique()->getEtape() ?>
                        (<?php echo $element->getService()->getElementPedagogique()->getEtape()->getCode() ?>)
                    </a>
                    <?php endif; ?>

                </td>
                <td>
                    <?php if ($element->getService() && $element->getService()->getElementPedagogique()->getPeriode()) {
                        echo $element->getService()->getElementPedagogique()->getPeriode()->getCode();
                    }?>
                </td>
                <td>
                    <?php if ($element->getService()): ?>
                    <?php $url = $this->url('of/element/voir', ['elementPedagogique' => $element->getService()->getElementPedagogique()->getId()]); ?>
                    <a href="<?php echo $url ?>"
                       class="ajax-modal"><?php echo $element->getService()->getElementPedagogique()->getLibelle() ?>
                        (<?php echo $element->getService()->getElementPedagogique()->getCode() ?>)
                    </a>
                    <?php endif; ?>

                </td>
                <td>
                    <?php echo $element->getCm() ?>
                </td>
                <td>
                    <?php echo $element->getTd() ?>
                </td>
                <td>
                    <?php echo $element->getTp() ?>
                </td>
                <td>
                    <?php echo $element->getAutres() ?>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
<?php endif; ?>
<?php if (isset($services[TypeService::CODE_REFERENTIEL])): ?>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th>Fonction</th>
            <th>Heures</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($services[\Service\Entity\Db\TypeService::CODE_REFERENTIEL] as $element): ?>
            <tr>
                <td>
                    <?php echo $element->getServiceReferentiel()->getFonctionReferentiel()->getLibelleLong() ?>
                    (<?php echo $element->getServiceReferentiel()->getFonctionReferentiel()->getCode() ?>)
                </td>
                <td>
                    <?php echo $element->getAutres() ?>
                </td>

            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
<?php endif; ?>
<?php if (isset($services[TypeService::CODE_MISSION])): ?>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th>Type de mission</th>
            <th>Libellé de mission</th>
            <th>Heures</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($services[TypeService::CODE_MISSION] as $element): ?>
            <tr>
                <td>
                    <?php echo $element->getMission()->getTypeMission()->getLibelle() ?>
                    (<?php echo $element->getMission()->getTypeMission()->getCode() ?>)
                </td>
                <td>
                    <?php echo $element->getMission()->getLibelle() ?>
                </td>
                <td>
                    <?php echo $element->getAutres() ?>
                </td>

            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
<?php endif; ?>
