<?php
/* @var  $this \Application\View\Renderer\PhpRenderer */
/* @var $intervenant \Intervenant\Entity\Db\Intervenant */

echo $this->messenger()->addCurrentMessagesFromFlashMessenger();

echo $this->intervenant($intervenant);

echo '<hr />';

$urlRefresh = $this->url('workflow/feuille-de-route-refresh', ['intervenant' => $intervenant->getId()]);

echo $this->vue('workflow/feuille-de-route', ['intervenant' => $intervenant->getId(), 'urlRefresh' => $urlRefresh]);