<?php
/* @var $recents [] */
?>
<h1 class="page-header">Rechercher un intervenant</h1>

<?= $this->messenger()->addCurrentMessagesFromFlashMessenger(); ?>

<div style="padding:1em">

    <?php

    echo $this->vue('intervenant/recherche', []);

    $canAddIntervenant = $this->isAllowed(\Application\Provider\Privileges::getResourceId(\Application\Provider\Privileges::INTERVENANT_CREATION));

    if ($canAddIntervenant) {
        $url = $this->url('intervenant/creer');
        echo $this->tag('a', ['class' => 'btn btn-primary', 'href' => $url])->html("Ajout d'un nouvel intervenant");
    }


    if (!empty($recents)) {
        echo '<h3 style="margin-top:20px;">Intervenants récemment consultés :</h3>';
        echo $this->partial('liste', ['intervenants' => $recents]);
    }


    ?>
</div>
