<?php

/**
 * @var $this            \Application\View\Renderer\PhpRenderer
 * @var $intervenant     \Intervenant\Entity\Db\Intervenant
 * @var $changed         bool
 * @var $errors          array
 * @var $definiParDefaut bool
 * @var $actionDetail    string
 */

if ($intervenant && 'dupliquer' == $actionDetail) {
    $this->intervenant($intervenant)->renderTitle('Ajout de statut');
}

echo $this->form()->openTag($form->prepare());

if ($errors) {
    echo $this->messenger()->setMessages([UnicaenApp\View\Helper\Messenger::ERROR => $errors]);
}

?>
    <div>&nbsp;</div>
    <div class="row">
        <div class="col-md-6">
            <div class="card bg-default">
                <div class="card-header">Données essentielles</div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-6">
                            <?= $this->formControlGroup($form->get('nomUsuel')); ?>
                        </div>
                        <div class="col-md-6">
                            <?= $this->formControlGroup($form->get('prenom')); ?>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <?= $this->formControlGroup($form->get('dateNaissance')); ?>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <?= $this->formControlGroup($form->get('code')); ?>
                        </div>
                        <div class="col-md-6">
                            <?= $this->formControlGroup($form->get('codeRh')); ?>
                        </div>
                    </div>
                    <!--INSEE ET NUMERO DE PRISE EN CHARGE-->
                    <div class="row">

                        <div class="col-md-6">
                            <?= $this->formControlGroup($form->get('numeroInsee')); ?>
                        </div>
                        <div class="col-md-6">
                            <?= $this->formControlGroup($form->get('numeroPec')); ?>
                        </div>

                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="card bg-default">
                <div class="card-header">Nomenclatures</div>
                <div class="card-body">
                    <?php
                    echo $this->formControlGroup($form->get('statut'));
                    echo $this->formControlGroup($form->get('structure'));
                    echo $this->formControlGroup($form->get('discipline'));
                    echo $this->formControlGroup($form->get('grade'));
                    ?>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="card bg-default">
                <div class="card-header">Divers</div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-4"><?= $this->formControlGroup($form->get('civilite')); ?></div>
                        <div class="col-md-8"><?= $this->formControlGroup($form->get('nomPatronymique')); ?></div>
                    </div>
                    <div class="row">
                        <div class="col-md-12"><?= $this->formControlGroup($form->get('emailPerso')); ?></div>
                    </div>
                    <div class="row">
                        <div class="col-md-6"><?= $this->formControlGroup($form->get('validiteDebut')); ?></div>
                        <div class="col-md-6"><?= $this->formControlGroup($form->get('validiteFin')); ?></div>
                    </div>
                    <?php
                    echo $this->formControlGroup($form->get('montantIndemniteFc'));
                    echo $this->formControlGroup($form->get('irrecevable'));
                    ?>

                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="card bg-default">
                <div class="card-header">Liens avec le système d'information</div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-12">
                            <!-- Nav tabs -->
                            <ul class="nav nav-tabs" role="tablist">
                                <li role="presentation" class="active">
                                    <a class="nav-link active" href="#exists-user" data-bs-target="#exists-user" aria-controls="exists-user" role="tab"
                                       data-bs-toggle="tab">Compte existant</a>
                                </li>
                                <li role="presentation">
                                    <a class="nav-link" href="#new-user" data-bs-target="#new-user" aria-controls=new-user" role="tab" data-bs-toggle="tab">Créer
                                        un nouveau compte</a></li>
                            </ul>

                            <!-- Tab panes -->
                            <div class="tab-content">
                                <div role="tabcard" class="tab-pane active" id="exists-user">
                                    <?= $this->formControlGroup($form->get('utilisateur')); ?>
                                </div>
                                <div role="tabcard" class="tab-pane" id="new-user">
                                    <div class="row">
                                        <div class="col-md-6"><?= $this->formControlGroup($form->get('intervenant-edition-login')); ?></div>
                                        <div class="col-md-6"><?= $this->formControlGroup($form->get('intervenant-edition-password')); ?></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6"><?= $this->formControlGroup($form->get('source')); ?></div>
                        <div class="col-md-6"><?= $this->formControlGroup($form->get('sourceCode')); ?></div>
                    </div>
                    <div class="row">
                        <div class="col-md-4"><?= $this->formControlGroup($form->get('syncStatut')); ?></div>
                        <div class="col-md-4"><?= $this->formControlGroup($form->get('syncStructure')); ?></div>
                        <div class="col-md-4"><?= $this->formControlGroup($form->get('syncPec')); ?></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script>

        $(function ()
        {
            WidgetInitializer.add('form-intervenant-edition', {

                _create: function ()
                {
                    var that = this;

                    this.getStatutElement().change(function () {
                        that.getSyncStatutElement().prop("checked", false);
                    });

                    this.getStructureElement().change(function () {
                        that.getSyncStructureElement().prop("checked", false);
                    });

                    this.getChangementEtatBtn().click(function () {
                        that.changementParDefaut();
                    });

                    this.getUserUtilisateurElement().change(function () {
                        that.changementUtilisateur();
                    });

                    this.element.find('[href="#new-user"]').click(function () {
                        console.log('testx');
                        that.getLoginElement().removeAttr('readonly');
                        that.getPasswordElement().removeAttr('readonly');
                    });
                },

                changementParDefaut: function ()
                {
                    var btn = this.getChangementEtatBtn();

                    if (btn.hasClass('active')) {
                        btn.removeClass('active');
                        btn.html('Définir par défaut');
                    } else {
                        btn.addClass('active');
                        btn.html('Ne plus définir par défaut');
                    }
                },

                changementUtilisateur: function ()
                {
                    this.getUserChangeElement().val(1);
                },

                getStatutElement: function () { return this.element.find('select[name="statut"]'); },
                getSyncStatutElement: function () { return this.element.find('input[name="syncStatut"]'); },
                getStructureElement: function () { return this.element.find('select[name="structure"]'); },
                getSyncStructureElement: function () { return this.element.find('input[name="syncStructure"]'); },
                getChangementEtatBtn: function () { return $('#changement-etat-defaut'); },

                getUserChangeElement: function () { return this.element.find('input[name="userChange"]'); },
                getLoginElement: function () { return this.element.find('input[name="intervenant-edition-login"]'); },
                getPasswordElement: function () { return this.element.find('input[name="intervenant-edition-password"]'); },
                getUserUtilisateurElement: function () { return this.element.find('input[name="utilisateur[id]"]'); }
            });

        })
        ;
    </script>

<?php
echo $this->formHidden($form->get('id'));
echo $this->formHidden($form->get('userChange'));
echo $this->form()->closeTag();
echo ' ' . $this->tag('button', [
        'onclick' => "$('.form-intervenant-edition').submit();",
        'class'   => 'btn btn-primary no-intranavigation',
    ])->html('Enregistrer');
if ($intervenant->getId()) {
    echo ' ' . $this->tag('a', [
            'href'  => $this->url('intervenant/definir-par-defaut', ['intervenant' => $intervenant->getId()]),
            'title' => 'Définir par défaut',
            'id'    => 'changement-etat-defaut',
            'class' => 'btn btn-info pop-ajax' . ($definiParDefaut ? ' active' : ''),
        ])->html($definiParDefaut ? 'Ne plus définir par défaut' : 'Définir par défaut');
}