<?php

use Unicaen\Framework\Navigation\Page;
use Intervenant\Entity\Db\Intervenant;
use Application\View\Renderer\PhpRenderer;

/**
 * @var $this             PhpRenderer
 * @var $intervenant      Intervenant
 * @var $tab              string
 * @var $pages            Page[]
 * @var $notificationNote int
 */

$this->intervenant($intervenant)->renderTitle('Fiche');

$tabs = [];
foreach ($pages as $page) {
    if ($page->isVisible()) {
        $tabs[$page->getName()] = [
            'id'            => $page->getName(),
            'label'         => '<i class="' . $page->getIcon() . '"></i> ' . $page->getLabel(),
            'url'           => $page->getUri(['intervenant' => $intervenant->getId()]),
            'force-refresh' => true,
        ];
    }
}

$tabs['fiche']['content'] = $this->partial('intervenant/intervenant/fiche.phtml', compact('intervenant'));

if (array_key_exists('notes', $tabs) && $notificationNote > 0) {
    $tabs['notes']['label'] .= ' <span class="badge" style="background-color: #fc1010;font-size:10px;margin-bottom:5px;">' . $notificationNote . '</span>';
}

echo $this->tabajax($tabs, $tab);