<?php

/**
 * @var $this              \Application\View\Renderer\PhpRenderer
 * @var $title             string
 * @var $form              \Mission\Form\MissionForm
 */

echo $this->messenger()->addCurrentMessagesFromFlashMessengerWithNamespace('error');


if ($form->isValide()) {
    echo $this->messenger()->renderMessage("Cette mission est déjà validée. Il n'est possible de ne modifier que son nombre d'heures et sa date de fin.", 'info');
}

echo $this->tag('h1', ['class' => 'page-header'])->html($title);
echo $this->form()->openTag($form);

if ($form->has('structure')) {
    echo $this->formControlGroup($form->get('structure'));
}
echo $this->formControlGroup($form->get('typeMission'));
echo $this->formControlGroup($form->get('libelleMission'));
echo '<div class="row">';
echo '<div class="col-md-6">';
echo $this->formLabel($form->get('dateDebut'));
echo $this->formElement($form->get('dateDebut'));
echo '</div>';
echo '<div class="col-md-6">';
echo $this->formLabel($form->get('dateFin'));
echo $this->formElement($form->get('dateFin'));
echo '</div>';
echo '</div>';

echo '<div class="row">';
echo '<div class="col-md-6">';
echo $this->formControlGroup($form->get('tauxRemu'));
echo '</div>';
echo '<div class="col-md-6">';
echo $this->formControlGroup($form->get('tauxRemuMajore'));
echo '</div>';
echo '<div class="col-md-6">';
echo $this->formControlGroup($form->get('heures'));
echo '</div>';
echo '<div class="col-md-6 heures-formation">';
echo $this->formControlGroup($form->get('heuresFormation'));
echo '</div>';
echo '</div>';

echo $this->formControlGroup($form->get('description'));

echo '<div class="etudiants-suivis">';
echo $this->formControlGroup($form->get('etudiantsSuivis'));
echo '</div>';

echo $this->formSubmit($form->get('submit'));

echo $this->form()->closeTag();
?>
<script>

    function formElement()
    {
        return $('#<?= $form->getAttribute('id') ?>');
    }

    function typeMissionSelect()
    {
        return formElement().find('[name=typeMission]');
    }

    function toggleViewElements(init)
    {
        var tmId = typeMissionSelect().val();
        var tmData = typeMissionSelect().data('tm');
        if (tmId) {
            if (tmData[tmId]['accompagnementEtudiants']) {
                $('.etudiants-suivis').show();
            } else {
                $('.etudiants-suivis').hide();
            }

            if (tmData[tmId]['besoinFormation']) {
                $('.heures-formation').show();
            } else {
                $('.heures-formation').hide();
            }

            if (init !== true) {
                formElement().find('[name=tauxRemu]').val(tmData[tmId]['tauxRemu']);
                formElement().find('[name=tauxRemuMajore]').val(tmData[tmId]['tauxRemuMajore']);
            }
        }

    }

    $(function () {
        typeMissionSelect().on('change', toggleViewElements);
        toggleViewElements(true);
    });

</script>