<?php

/**
 * @var $this              \Application\View\Renderer\PhpRenderer
 * @var $title             string
 * @var $form              \Mission\Form\MissionForm
 */

echo $this->messenger()->addCurrentMessagesFromFlashMessengerWithNamespace('error');

echo $this->tag('h1', ['class' => 'page-header'])->html($title);
echo $this->form()->openTag($form);

if ($form->has('structure')) {
    echo $this->formControlGroup($form->get('structure'));
}
echo $this->formControlGroup($form->get('typeMission'));
echo '<div class="row">';
echo '<div class="col-md-6">';
echo $this->formControlGroup($form->get('dateDebut'));
echo '</div>';
echo '<div class="col-md-6">';
echo $this->formControlGroup($form->get('dateFin'));
echo '</div>';
echo '</div>';

echo '<div class="row">';
echo '<div class="col-md-6">';
echo $this->formControlGroup($form->get('tauxRemu'));
echo '</div>';
echo '<div class="col-md-6">';
echo $this->formControlGroup($form->get('tauxRemuMajore'));
echo '</div>';
echo '<div class="col-md-6">';
echo $this->formControlGroup($form->get('heures'));

echo '</div>';
echo '</div>';

echo $this->formControlGroup($form->get('description'));

echo '<div class="etudiants-suivis">';
echo $this->formControlGroup($form->get('etudiantsSuivis'));
echo '</div>';

echo $this->formSubmit($form->get('submit'));

echo $this->form()->closeTag();
?>
<script>

    function typeMissionSelect()
    {
        return $('[name=typeMission]');
    }

    function toggleEtudiantsSuivis()
    {
        var tmId = typeMissionSelect().val();

        var tmAcc = typeMissionSelect().data('accompagnement-etudiants');

        if (tmAcc[tmId]){
            $('.etudiants-suivis').show();
        }else{
            $('.etudiants-suivis').hide();
        }
    }

    $(function(){
        typeMissionSelect().on('change', toggleEtudiantsSuivis);
        toggleEtudiantsSuivis();
    });

</script>