<?php

/* @var $form \Utilisateur\Form\AffectationForm */
/* @var $errors array */

echo $this->form()->openTag($form->prepare());

if ($errors) {
    echo $this->messenger()->setMessages([UnicaenApp\View\Helper\Messenger::ERROR => $errors]);
}

echo $this->formControlGroup($form->get('utilisateur'));
echo $this->formControlGroup($form->get('role'));
echo $this->formControlGroup($form->get('structure'));
echo $this->formRow($form->get('submit'));
echo $this->formHidden($form->get('id'));

echo $this->form()->closeTag();

?>
<script type="application/javascript">

    $.widget("ose.affectationForm", {

        onUtilisateurChange: function (item)
        {
            this.getElementStructure().val(item.structure);
        },

        updateStructureVisibility: function ()
        {
            var roleMustHaveStructure = $.inArray(parseInt(this.getElementRole().val()), this.getRolesMustHaveStructure()) > -1;

            if (roleMustHaveStructure) {
                this.getElementStructure().parents('.mb-2').show();
            } else {
                this.getElementStructure().parents('.mb-2').hide();
            }
        },



        _create: function ()
        {
            var that = this;
            this.getElementRole().on('change', function () { that.updateStructureVisibility() });
            this.getElementUtilisateur().on("change", function (e, item) { that.onUtilisateurChange(item); });
            this.updateStructureVisibility();
        },



        //@formatter:off
        getRolesMustHaveStructure   : function () { return this.element.data('roles-must-have-structure'); },
        getElementUtilisateur         : function () { return this.element.find('input[name="utilisateur\\[id\\]"]'); },
        getElementRole              : function () { return this.element.find('select[name="role"]'); },
        getElementStructure         : function () { return this.element.find('select[name="structure"]'); }
        //@formatter:on
    });

    WidgetInitializer.add('affectation-form', 'affectationForm');

</script>
