<?php

/**
 * @var $this         \Application\View\Renderer\PhpRenderer
 * @var $affectations \Utilisateur\Entity\Db\Affectation[]
 * @var $structure    \Lieu\Entity\Db\Structure
 */

use Application\Provider\Privileges;

$head = [
    'structure'   => 'Structure',
    'role'        => 'Rôle',
    'utilisateur' => 'Utilisateur',
    'source'      => '<abbr title="Source de données">Src</abbr>/Actions',
];

$canEdit = $this->isAllowed(Privileges::getResourceId(Privileges::DROIT_AFFECTATION_EDITION));
$ajoutUrl = $this->url('droits/affectations/edition');

?>
<h1 class="page-header">Gestion des affectations</h1>

<table class="table table-bordered table-sm table-sort">
    <thead>
    <tr>
        <?php foreach ($head as $id => $label): ?>
            <th style="white-space: nowrap">
                <?= $label ?>
            </th>
        <?php endforeach; ?>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($affectations as $affectation):
        $editionUrl = $this->url('droits/affectations/edition', ['affectation' => $affectation->getId()]);
        $suppressionUrl = $this->url('droits/affectations/suppression', ['affectation' => $affectation->getId()]);
        ?>
        <tr>
            <td><?php
                $str = (string)$affectation->getStructure();
                if ('' == $str) {
                    $str = '<span class="bg-info">&Eacute;tablissement</span>';
                }
                echo $str;
                ?></td>
            <td><?= $affectation->getRole() ?></td>
            <td><?= $affectation->getUtilisateur() ?></td>
            <td style="text-align: center;width:1%;white-space: nowrap"><?php
                if (!$affectation->getSource()->getImportable() && $canEdit) {
                    ?>
                    <a href="<?= $editionUrl; ?>" class="ajax-modal" data-event="affectation-edition"><i
                                class="fas fa-pen-to-square"></i></a>
                    <a href="<?= $suppressionUrl; ?>" class="pop-ajax" data-submit-reload="1"><i
                                class="fas fa-trash-can"></i></a>
                    <?php
                } else {
                    echo $affectation->getSource();
                }
                ?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<?php if ($canEdit): // droits ?>
    <a href="<?= $ajoutUrl ?>" class="btn btn-primary ajax-modal" data-event="affectation-edition">Ajout d'une nouvelle
        affectation</a>
<?php endif; ?>
<?= $this->modalAjaxDialog('affectations-edition-suppression'); ?>
<script type="text/javascript">
    $(function () {
        $("body").on("affectation-edition", function (event, data) {
            unicaenVue.flashMessenger.toast("L'action a bien été prise en compte", 'success');
            window.location.reload();
        });

        $("body").on("affectation-suppression", function (event, data) {
            window.location.reload();
        });
    });
</script>