<?php

/**
 * @var $this       \Application\View\Renderer\PhpRenderer
 * @var $privileges array
 * @var $roles      \Utilisateur\Entity\Db\Role[]
 */

?>
<h1 class="page-header">Gestion des privilèges</h1>
<table class="droits-tbl table table-bordered table-sm table-header-rotated">
    <thead>
    <tr>
        <th class="menu"></th>
        <?php foreach ($roles as $role): ?>
            <th class="rotate-45 role" data-role="<?= $role->getId() ?>">
                <div title="<?= $role; ?>"><span><a><?= $role; ?></a></span></div>
            </th>
        <?php endforeach; ?>
    </tr>
    </thead>
    <tbody>
    <tr>
        <th class="categorie" colspan="<?= 2 + count($roles); ?>">
            <select class="categorie selectpicker" data-live-search="true" data-width="100%">
                <option value="">Veuillez choisir une catégorie de privilèges ...</option>
                <?php foreach ($privileges as $cat): ?>
                    <option value="<?= $cat['categorie']->getCode() ?>"><?= $cat['categorie'] ?></option>
                <?php endforeach; ?>
            </select>
        </th>
    </tr>
    <?php foreach ($privileges as $cat): ?>
        <?php foreach ($cat['privileges'] as $privilege): ?>
            <tr class="categorie" data-categorie="<?= $cat['categorie']->getCode() ?>" style="display: none">
                <th class="privilege"><?= $privilege ?></th>
                <?php
                foreach ($roles as $role): ?>
                    <td class="modifier role" data-role="<?= $role->getId() ?>" data-privilege="<?= $privilege->getId() ?>">
                        <?= $this->partial('/utilisateur/droits/partial/tbl-link', compact('role', 'privilege')) ?>
                    </td>
                <?php endforeach; ?>

            </tr>
        <?php endforeach; ?>
    <?php endforeach; ?>
    </tbody>
</table>

<script type="application/javascript">

    /**
     * @constructor
     * @this {DroitsTbl}
     * @param {string} id
     * @returns {DroitsTbl}
     */
    $.widget("ose.droitsTbl", {

        modifier: function (td, action)
        {
            var that = this;
            td.html("<div class=\"loading\">&nbsp;</div>");
            td.load(unicaenVue.url('droits/privileges/modifier'), {
                role: td.data("role"),
                privilege: td.data("privilege"),
                action: action
            }, function ()
            {
                that.initModifierClick(td); // pour reconnecter l'action du lien...
            });

        },


        showHideCategorie: function (categorie)
        {
            this.element.find('tr.categorie[data-categorie="' + categorie + '"]').each(function () {

                if ($(this).is(':visible')) {
                    $(this).hide();
                } else {
                    $(this).show();
                }
            });
        },



        showCategorie: function (categorie)
        {
            console.log(categorie);
            this.element.find('tr.categorie[data-categorie!="' + categorie + '"]').hide();
            this.element.find('tr.categorie[data-categorie="' + categorie + '"]').show();
        },


        hideRole: function (roleId)
        {
            this.element.find('th.role[data-role="' + roleId + '"]').hide();
            this.element.find('td.role[data-role="' + roleId + '"]').hide();

            var rolesCount = this.element.find('th.role:visible').length;
            if (rolesCount > 0) {
                this.element.find('th.roles').attr('colspan', rolesCount).show();
            } else {
                this.element.find('th.roles').hide();
            }

            this.updateFirsts();
        },



        updateFirsts: function ()
        {
            this.element.find('th.role.first').removeClass('first');

            this.element.find('th.role:visible:first').addClass('first');
        },



        initModifierClick: function (td)
        {
            var that = this;
            td.find("a").on("click", function ()
            {
                that.modifier(td, $(this).data("action"));
            });
        },



        /**
         * Initialisation
         *
         * @returns {undefined}
         */
        _create: function ()
        {
            var that = this;
            this.element.find("td.modifier").each(function ()
            {
                that.initModifierClick($(this));
            });

            this.element.find('a.categorie').click(function ()
            {
                that.showHideCategorie($(this).data('categorie'));
            });

            this.element.find('th.role a').click(function ()
            {
                var roleId = $(this).parents('.role').data('role');
                that.hideRole(roleId);
            });

            this.element.find('select.categorie').change(function () {
                that.showCategorie($(this).val());
            });

            this.element.find('.modifier').on('mouseover mouseout', function ()
            {

                var id = $(this).data('role');
                var selector = 'role';

                that.element.find('.selected').removeClass('selected');

                $(this).prevAll().addBack()
                .add($(this).parent().prevAll()
                .children(':nth-child(' + ($(this).index() + 1) + '):not(.categorie)')).toggleClass('selected');

                that.element.find('th.' + selector + '[data-' + selector + '="' + id + '"] div').toggleClass('selected');
            });

            this.updateFirsts();
        }
    });

    $(function(){
        WidgetInitializer.add('droits-tbl', 'droitsTbl');
    });


</script>