<h1 class="page-header">Gestion des rôles</h1>
<?php

use Application\Provider\Privileges;

/* @var $roles \Utilisateur\Entity\Db\Role[] */

$canEdit  = $this->isAllowed(Privileges::getResourceId(Privileges::DROIT_ROLE_EDITION));
$ajoutUrl = $this->url('droits/roles/edition');

?>
<table class="table table-sm table-bordered">
    <tr>
        <th>Code</th>
        <th>Libellé</th>
        <th>Périmètre</th>
        <th>Struct. modifiable</th>
        <th>Accessible hors établissement</th>
        <?php if ($canEdit): ?>
            <th>Action</th><?php endif; ?>
    </tr>
    <?php foreach ($roles as $role):
        $editionUrl = $this->url('droits/roles/edition', ['role' => $role->getId()]);
        $suppressionUrl = $this->url('droits/roles/suppression', ['role' => $role->getId()]);
        ?>
        <tr>
            <td><?= $role->getCode(); ?></td>
            <td><?= $role->getLibelle(); ?></td>
            <td><?= $role->getPerimetre(); ?></td>
            <td style="text-align: center;"><?= $role->getPeutChangerStructure() ? '<i class="fas fa-check text-succes"></i' : '<i class="fas fa-xmark text-danger refuse"></i'; ?></td>
            <td style="text-align: center;"><?= $role->isAccessibleExterieur() ? '<i class="fas fa-check text-succes"></i' : '<i class="fas fa-xmark text-danger refuse"></i'; ?></td>
            <?php if ($canEdit): ?>
                <td style="width:1%;white-space: nowrap;text-align: center">
                    <a href="<?= $editionUrl; ?>" class="ajax-modal" data-event="role-edition"><i
                                class="fas fa-pen-to-square"></i></a>
                    <a href="<?= $suppressionUrl; ?>" class="ajax-modal" data-event="role-suppression"><i
                                class="fas fa-trash-can"></i></a>
                </td>
            <?php endif; ?>
        </tr>
    <?php endforeach; ?>
</table>
<?php if ($canEdit): // droits ?>
    <a href="<?= $ajoutUrl ?>" class="btn btn-primary ajax-modal" data-event="role-edition">Création d'un nouveau rôle</a>
<?php endif; ?>
<?= $this->modalAjaxDialog('roles-edition-suppression'); ?>
<script type="text/javascript">
    $(function () {
        $("body").on("role-edition", function (event, data) {
            window.location.reload();
        });

        $("body").on("role-suppression", function (event, data) {
            window.location.reload();
        });
    });
</script>