<?php
/**
 * @var $this      \Application\View\Renderer\PhpRenderer
 * @var $form      \Application\Form\FonctionReferentiel\FonctionReferentielSaisieForm
 * @var $tab       string
 */

/** @var \Referentiel\Entity\Db\FonctionReferentiel $fonction */

use Application\Provider\Privileges;

$fonction = $form->getObject();

$visu = $this->messenger()->addCurrentMessagesFromFlashMessenger() . $this->form($form);

$tabs = [
    [
        'id'      => 'fiche',
        'label'   => 'Fiche',
        'content' => $visu,
    ],
];

$id      = $fonction->getId();
$canEdit = $this->isAllowed(Privileges::getResourceId(Privileges::PLAFONDS_CONFIG_REFERENTIEL));


if ($id && $canEdit) {

    $tabs[] = [
        'id'    => 'plafonds',
        'label' => '<i class="fas fa-signal"></i> Plafonds',
        'url'   => $this->url('plafond/referentiel', ['fonctionReferentiel' => $id]),
    ];

    echo $this->tabajax($tabs, $tab);
} else {
    echo $visu;
}


