<?php

namespace Application\Entity\Db\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EtablissementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @author Laurent LÉCLUSE <laurent.lecluse at unicaen.fr>
 */
class EtablissementRepository extends EntityRepository
{

    /**
     * Recherche par libellé
     *
     * @param string $term
     * @return \Application\Entity\Db\Etablissement[]
     */
    public function findByLibelle($term)
    {
        $terms = explode( ' ', $term );

        $qb = $this->createQueryBuilder('e');

        $concatFields = array(
            'e.libelle',
            'e.departement',
            'e.localisation',
        );

        foreach ($concatFields as $field) {
            if (!isset($searchIn)) {
                $searchIn = $qb->expr()->concat($qb->expr()->literal(''), $field);
                continue;
            }

            $searchIn = $qb->expr()->concat(
                $searchIn,
                $qb->expr()->concat($qb->expr()->literal(' '), $field)
            );
        }

        $haystack = new \Doctrine\ORM\Query\Expr\Func( 'CONVERT', array( $searchIn, '?1' ) );
        $parameters = array(
            1 => 'US7ASCII'
        );

        $index = 2;
        foreach( $terms as $term ){
            $parameters[$index] = "%$term%";
            $qb->andWhere($qb->expr()->like($qb->expr()->upper($haystack), $qb->expr()->upper("CONVERT(?$index, ?1)")));
            $index++;
        }
        $qb->orderBy('e.libelle');
        $qb->setParameters( $parameters );

        return $qb->getQuery()->execute();
    }
}