<?php

namespace Application\Entity\Db\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ServiceReferentielRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceReferentielRepository extends EntityRepository
{
    
}