<?php

use Application\Provider\Privilege\Privileges;
use Chargens\Assertion\ChargensAssertion;

/**
 * @var $this      \Application\View\Renderer\PhpRenderer
 * @var $scenarios \Chargens\Entity\Db\Scenario[]
 */

$title = "Gestion des scénarios";

$this->headTitle()->append($title);

$canEditLocal = $this->isAllowed(Privileges::getResourceId(Privileges::CHARGENS_SCENARIO_COMPOSANTE_EDITION));
$canEditEtab  = $this->isAllowed(Privileges::getResourceId(Privileges::CHARGENS_SCENARIO_ETABLISSEMENT_EDITION));
$canCopy      = $this->isAllowed(Privileges::getResourceId(Privileges::CHARGENS_SCENARIO_DUPLICATION));

$canEdit = $canEditLocal || $canCopy || $canEditEtab;


?>
<h1 class="page-header"><?= $title ?></h1>
<table class="table table-bordered table-sort">
    <thead>
    <tr>
        <th>Scénario</th>
        <th>Type</th>
        <th>Composante</th>
        <?php if ($canEdit): ?>
            <th>Actions</th>
        <?php endif; ?>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($scenarios as $scenario):

        $canEditScenario = $canEdit && $this->isAllowed($scenario, ChargensAssertion::SCENARIO_EDITION);

        ?>
        <tr>
            <td><?= $scenario->getLibelle(); ?></td>
            <td style="text-align:center"><?= $scenario->getTypeString() ?></td>
            <td><?= $this->structure($scenario->getStructure())->renderLink(); ?></td>
            <?php if ($canEdit): ?>
                <td style="text-align: center">
                    <?php if ($canEditScenario): ?>
                        <a class="pop-ajax" data-submit-reload="true"
                           href="<?= $this->url('chargens/scenario/saisir', ['scenario' => $scenario->getId()]) ?>"
                           title="Modifier le scénario"><i class="fas fa-pen-to-square"></i></a>
                    <?php endif; ?>
                    <?php if ($canCopy): ?>
                        <a class="pop-ajax" data-submit-reload="true"
                           href="<?= $this->url('chargens/scenario/dupliquer', ['scenario' => $scenario->getId()]) ?>"
                           title="Dupliquer le scénario"><i class="fas fa-copy"></i></a>
                    <?php endif; ?>
                    <?php if ($canEditScenario): ?>
                        <a class="pop-ajax"
                           data-content="<p class='lead text-danger'><strong>Attention!</strong> Confirmez-vous cette suppression ?</p>"
                           data-confirm="true"
                           data-confirm-button="Oui"
                           data-cancel-button="Non"
                           data-submit-reload="true"
                           href="<?= $this->url('chargens/scenario/supprimer', ['scenario' => $scenario->getId()]) ?>"
                           title="Supprimer le scénario"><i class="fas fa-trash-can"></i></a>
                    <?php endif; ?>
                </td>
            <?php endif; ?>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<?php if ($canEditLocal): ?>
    <a class="btn btn-primary pop-ajax" data-submit-reload="true"
       href="<?= $this->url('chargens/scenario/saisir'); ?>"><i class="fas fa-plus"></i> Ajout d'un
        nouveau scenario local</a>
<?php endif; ?>
<a class="btn btn-secondary" href="<?= $this->url('chargens'); ?>">
    <i class="fas fa-rotate-left" aria-hidden="true"></i>
    Retour au menu des charges d'enseignement
</a>
