<?php

/**
 * @var $this    \Application\View\Renderer\PhpRenderer
 * @var $annees  \Application\Entity\Db\Annee[][]
 * @var $canEdit boolean
 */

use Application\Provider\Privilege\Privileges;

$annees  = array_chunk($annees, 10);
$canEdit = $this->isAllowed(Privileges::getResourceId(Privileges::PARAMETRES_ANNEES_EDITION));


?>
<h1 class="page-header">Gestion des années</h1>

<?php foreach ($annees as $index => $al): if ($index > 5): ?>
    <div style="float:left;margin:2em">
        <?php foreach ($al as $annee): ?>

            <div style="margin:5px">
                <button type="button" <?= (!$canEdit) ? 'disabled="disabled"' : ''; ?> data-id="<?= $annee->getId() ?>"
                        class="btn btn-annee <?= $annee->isActive() ? 'btn-info active' : 'btn-secondary' ?>"><?= $annee ?></button>
            </div>

        <?php endforeach; ?>
    </div>
<?php endif; endforeach; ?>
<script>

    $('.btn-annee').click(function () {

        var isActive = $(this).hasClass('active');
        var anneeId = $(this).data('id');

        if (isActive) {
            $(this).removeClass('active');
            $(this).removeClass('btn-info');
            $(this).addClass('btn-secondary');
            isActive = false;
        } else {
            $(this).addClass('active');
            $(this).addClass('btn-info');
            $(this).removeClass('btn-secondary');
            isActive = true;
        }

        $.ajax({
            type: 'POST',
            url: "<?= $this->url('parametres/annees') ?>",
            data: {annee: anneeId},
            success: function (data) {
                unicaenVue.flashMessenger.toast(data.message, data.status);
            },
        });

    });

</script>