<?php

/**
 * @var $this                 \Application\View\Renderer\PhpRenderer
 * @var $typesIntervenants    \Intervenant\Entity\Db\TypeIntervenant[]
 * @var $typesVolumesHoraires \Application\Entity\Db\TypeVolumeHoraire[]
 * @var $canEdit              boolean
 * @var $forms                \Application\Form\CampagneSaisieForm[][]
 */

?>
    <h1 class="page-header">Paramétrage des campagnes de saisie</h1>

<?= $this->messenger()->addCurrentMessagesFromFlashMessenger(); ?>

<?php foreach ($typesIntervenants as $typeIntervenant): ?>
    <div class="well">
        <h2><?= $typeIntervenant ?></h2>
        <?php foreach ($typesVolumesHoraires as $typeVolumeHoraire):
            $form = $forms[$typeIntervenant->getId()][$typeVolumeHoraire->getId()];
            ?>

            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Saisie du service <?= lcfirst($typeVolumeHoraire) ?></h3>
                </div>
                <div class="panel-body">
                    <?php
                    echo $this->form()->openTag($form);
                    echo $this->formHidden($form->get('typeIntervenant'));
                    echo $this->formHidden($form->get('typeVolumeHoraire'));
                    ?>
                    <div class="row">
                        <div class="col-md-6"><?= $this->formControlGroup($form->get('dateDebut')) ?></div>
                        <div class="col-md-6"><?= $this->formControlGroup($form->get('dateFin')) ?></div>
                    </div>
                    <div class="row">
                        <div
                                class="col-md-12"><?= $this->formControlGroup($form->get('messageIntervenant')) ?></div>
                    </div>
                    <div class="row">
                        <div class="col-md-12"><?= $this->formControlGroup($form->get('messageAutres')) ?></div>
                    </div>
                    <?php
                    if ($canEdit) echo $this->formSubmit($form->get('submit'));
                    echo $this->form()->closeTag();
                    ?>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
<?php endforeach; ?>

<?php

