<?php

/**
 * @var $this \Application\View\Renderer\PhpRenderer
 * @var $form \Application\Form\ParametresForm
 * @var $canEdit boolean
 */

?>
    <h1 class="page-header">Paramètres généraux</h1>

<?= $this->form()->openTag($form); ?>

<div class="well">

    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Années universitaires en cours</h3>
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-md-6">
                    <?= $this->formControlGroup($form->get('annee')); ?>
                </div>
                <div class="col-md-6">
                    <?= $this->formControlGroup($form->get('annee_import')); ?>
                </div>
            </div>
        </div>
    </div>

    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Services et référentiel</h3>
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-md-6">
                    <?= $this->formControlGroup($form->get('modalite_services_prev_ens')); ?>
                </div>
                <div class="col-md-6">
                    <?= $this->formControlGroup($form->get('modalite_services_prev_ref')); ?>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <?= $this->formControlGroup($form->get('modalite_services_real_ens')); ?>
                </div>
                <div class="col-md-6">
                    <?= $this->formControlGroup($form->get('modalite_services_real_ref')); ?>
                </div>
            </div>
        </div>
    </div>

    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Contrat</h3>
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-md-6">
                    <?= $this->formControlGroup($form->get('contrat_civilite_president')); ?>
                </div>
                <div class="col-md-6">
                    <?= $this->formControlGroup($form->get('contrat_etablissement')); ?>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <?= $this->formControlGroup($form->get('contrat_etablissement_represente')); ?>
                </div>
                <div class="col-md-6">
                    <?= $this->formControlGroup($form->get('contrat_lieu_signature')); ?>
                </div>
            </div>
        </div>
    </div>

    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Export PDF des services d'enseignement</h3>
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-md-6">
                    <?= $this->formControlGroup($form->get('export_pdf_services_signature_1')); ?>
                </div>
                <div class="col-md-6">
                    <?= $this->formControlGroup($form->get('export_pdf_services_signature_2')); ?>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <?= $this->formControlGroup($form->get('export_pdf_services_signataire_1')); ?>
                </div>
                <div class="col-md-6">
                    <?= $this->formControlGroup($form->get('export_pdf_services_signataire_2')); ?>
                </div>
            </div>
        </div>
    </div>

    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Gestion des disciplines</h3>
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-md-6">
                    <?= $this->formControlGroup($form->get('discipline_codes_corresp_1_libelle')); ?>
                </div>
                <div class="col-md-6">
                    <?= $this->formControlGroup($form->get('discipline_codes_corresp_2_libelle')); ?>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <?= $this->formControlGroup($form->get('discipline_codes_corresp_3_libelle')); ?>
                </div>
                <div class="col-md-6">
                    <?= $this->formControlGroup($form->get('discipline_codes_corresp_4_libelle')); ?>
                </div>
            </div>
        </div>
    </div>

    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Formule de calcul des HETD</h3>
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-md-6">
                    <?= $this->formControlGroup($form->get('formule_package_name')); ?>
                </div>
                <div class="col-md-6">
                    <?= $this->formControlGroup($form->get('formule_function_name')); ?>
                </div>
            </div>
        </div>
    </div>

    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Liens vers les documentations</h3>
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-md-6">
                    <?= $this->formControlGroup($form->get('doc-intervenant-vacataires')); ?>
                </div>
                <div class="col-md-6">
                    <?= $this->formControlGroup($form->get('doc-intervenant-permanents')); ?>
                </div>
            </div>
        </div>
    </div>

    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Etats de paiement et exports Winpaie</h3>
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-md-6">
                    <?= $this->formControlGroup($form->get('winpaie_carte')); ?>
                </div>
                <div class="col-md-6">
                    <?= $this->formControlGroup($form->get('winpaie_mc')); ?>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <?= $this->formControlGroup($form->get('winpaie_retenue')); ?>
                </div>
                <div class="col-md-6">
                    <?= $this->formControlGroup($form->get('winpaie_sens')); ?>
                </div>
            </div>
        </div>
    </div>

    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Divers</h3>
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-md-6">
                    <?= $this->formControlGroup($form->get('directeur_ressources_humaines_id')); ?>
                </div>
                <div class="col-md-6">
                    <?= $this->formControlGroup($form->get('domaine_fonctionnel_ens_ext')); ?>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <?= $this->formControlGroup($form->get('etablissement')); ?>
                </div>
                <div class="col-md-6">
                    <?= $this->formControlGroup($form->get('oseuser')); ?>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <?= $this->formControlGroup($form->get('pays_france')); ?>
                </div>
                <div class="col-md-6">
                    <?= $this->formControlGroup($form->get('scenario_charges_services')); ?>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <?= $this->formControlGroup($form->get('structure_univ')); ?>
                </div>
            </div>
        </div>
    </div>

</div>
<?php
    if ($canEdit) echo $this->formsubmit( $form->get('submit') );
    echo $this->form()->closeTag();