<?php

/**
 * @var $this        \Application\View\Renderer\PhpRenderer
 * @var $title       string
 * @var $intervenant Intervenant
 * @var $differences \Application\Entity\Db\IndicModifDossier[]
 */

use Application\Provider\Privilege\Privileges;

$canPurge = $this->isAllowed(Privileges::getResourceId(Privileges::DOSSIER_PURGER_DIFFERENCES));

if ($canPurge) {
    $urlPurge = $this->url('intervenant/dossier/purger-differences', ['intervenant' => $this->intervenant->getRouteParam()]);
} else {
    $urlPurge = null;
}

?>
    <h1 class="page-header"><?php echo $title ?></h1>

    <table class="table table-bordered">
        <thead>
        <tr>
            <th>Données concernées</th>
            <th>Données importées de <?php echo $intervenant->getSource() ?></th>
            <th>Données personnelles saisies</th>
            <th>Horodatage</th>
        </tr>
        </thead>
        <tbody>

        <?php foreach ($differences as $difference): ?>
            <tr>
                <td><?php echo $difference->getAttrName() ?></td>
                <td>
                    <pre><?php echo $difference->getAttrOldValue() ?></pre>
                    <div class="pull-right">
                        <small>Source: <?php echo $difference->getAttrOldSourceName() ?></small>
                    </div>
                </td>
                <td>
                    <pre><?php echo $difference->getAttrNewValue() ?></pre>
                    <div class="pull-right">
                        <small>Source: <?php echo $difference->getAttrNewSourceName() ?></small>
                    </div>
                </td>
                <td>
                    <?php echo sprintf("Le %s <br>par %s",
                        $difference->getHistoModification()->format(\Application\Constants::DATETIME_FORMAT),
                        $difference->getHistoModificateur()) ?>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>

    <a class="btn btn-default" href="javascript:window.history.back()">
        <i class="fa fa-undo" aria-hidden="true"></i>
        Page précédente
    </a>

    <a class="btn btn-warning"
       href="<?php echo $this->url('intervenant/dossier', ['intervenant' => $intervenant->getRouteParam()]) ?>"
    >Voir les données personnelles de <?php echo $intervenant ?></a>

<?php if ($canPurge): ?>

    <a href="<?php echo $urlPurge ?>"
       class="btn btn-danger pop-ajax"
       data-submit-event="event-purger-indic"
       data-confirm="true"
    >Ok, effacer cet historique</a>
    <script>
        $("body").on("event-purger-indic", function (event, data)
        {
            window.history.back();
        });
    </script>
<?php endif; ?>