<?php

use Intervenant\Entity\Db\Statut;
use PieceJointe\Entity\Db\TypePieceJointe;
use Application\Provider\Privilege\Privileges;
use PieceJointe\Form\ModifierTypePieceJointeStatutForm;

/**
 * @var $this                \Application\View\Renderer\PhpRenderer
 * @var $title               string
 * @var $form                ModifierTypePieceJointeStatutForm
 * @var $typePieceJointe     TypePieceJointe
 * @var $statut              Statut
 */

$canEdit = $this->isAllowed(Privileges::getResourceId(Privileges::PIECE_JUSTIFICATIVE_GESTION_EDITION));

echo $this->form()->openTag($form->prepare());
echo $this->messenger()->addCurrentMessagesFromFlashMessenger();

?>


<div class="row">
    <div class="col-md-12">
        <?= $this->formControlGroup($form->get('obligatoire')); ?>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <?= $this->formControlGroup($form->get('changement-rib')); ?>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <?= $this->formControlGroup($form->get('nationalite-etrangere')); ?>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <?= $this->formControlGroup($form->get('fc')); ?>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <?= $this->formControlGroup($form->get('fa')); ?>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <?= $this->formControlGroup($form->get('obligatoire-hnp')); ?>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <?= $this->formControlGroup($form->get('type-heure-hetd')); ?>
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <?= $this->formControlGroup($form->get('seuil-hetd')); ?>
    </div>
    <div class="col-md-6">
        <?= $this->formControlGroup($form->get('duree-vie')); ?>
    </div>
</div>

<?= $this->formSubmit($form->get('submit')); ?>

<?php if (($canEdit) && ($form->getObject()->getId())) : ?>

    <a class="pop-ajax btn btn-danger"
       href="<?= $this->url('piece-jointe/delete-type-piece-jointe-statut', ['typePieceJointeStatut' => $form->getObject()->getId()]) ?>"
       title="Supprimer le type de piece jointe"
       data-content="<p class='lead text-danger'><strong>Attention!</strong> Confirmez-vous cette suppression ?</p>"
       data-confirm="true"
       data-confirm-button="Oui"
       data-cancel-button="Non"
       data-submit-reload="true"
    >Supprimer</a>

    <a class="btn btn-secondary"
       href= <?= $this->url('piece-jointe/modifier-type-piece-jointe-statut', ['typePieceJointe' => $typePieceJointe->getId(), 'statut' => $statut->getId()]) ?>
       class="ajax-modal"
       data-event="event-update-tpjs"
    >Ajouter une autre règle</a>
<?php endif;

echo $this->formRow($form->get('security'));
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();

?>

<script type="text/javascript">

    $(document).ready(function () {

        $("input[name='changement-rib']").change(function () {
            var dureeVie = $("input[name='duree-vie']")
            if (this.checked) {
                dureeVie.val('1');
                //dureeVie.attr('type', 'disabled');
            } else {
                dureeVie.removeAttr('disabled');
            }
        })
    });

</script>