<?php
/**
 * @var \Application\Entity\Db\Intervenant        $intervenant
 * @var \ExportRh\Entity\IntervenantRh            $intervenantRh
 * @var \Application\Entity\Db\IntervenantDossier $intervenantDossier
 */

if ($priseEnCharge) {
    $action = 'intervenant/pec';
} elseif ($renouvellement) {
    $action = 'intervenant/ren';
} else {
    $action = 'intervenant/sync';
}

?>
<br/>

<form class="no-intranavigation form-export-rh" action="<?= $this->url($action, ['intervenant' => $intervenant->getId()]) ?>" method="post">

    <?php echo $this->messenger()->addCurrentMessagesFromFlashMessenger()->addMessagesFromFlashMessenger(); ?>


    <?php if ($typeIntervenant == 'P'): ?>
        <div class="messenger alert alert-warning">
            L'export des données intervenants vers <?= $nameConnecteur; ?> n'est disponible que pour les vacataires.
        </div>
    <?php elseif (empty($intervenantDossierValidation)): ?>
        <div class="messenger alert alert-warning">
            Vous devez d'abord valider les données personnelles de <?= $intervenant; ?> pour pouvoir les synchroniser avec <?= $nameConnecteur; ?>
        </div>
    <?php endif; ?>

    <?php if (!empty($intervenantDossierValidation)): ?>

    <div class="well">
        <?php if (empty($intervenantRh)): ?>
            <p>L'intervenant <?= $intervenantDossier->getPrenom() . ' ' . $intervenantDossier->getNomUsuel() ?> n'a pas été trouvé dans <?= $nameConnecteur; ?>. Vous pouvez si vous le souhaiter prendre en charge cet intervenant avec les données de son dossier, résumées ci-dessous :</p>
        <?php else: ?>
            <?php if ($this->isAllowed($intervenant, \ExportRh\Assertion\ExportRhAssertion::PRIV_CAN_INTERVENANT_EXPORT_RH) === false): ?>
                <p><p>L'intervenant <?= $intervenantDossier->getPrenom() . ' ' . $intervenantDossier->getNomUsuel() ?> est bien dans le <?= $nameConnecteur ?> (<strong>numéro de matricule :</strong> <?= $intervenantRh->getCodeRh() ?>). L'export RH n'est disponible que sur l'année universitaire en
                    cours.</p>
            <?php elseif (!empty($affectationEnCours) && !empty($contratsEnCours)): ?>
                <p>L'intervenant <?= $intervenantDossier->getPrenom() . ' ' . $intervenantDossier->getNomUsuel() ?> est bien dans le <?= $nameConnecteur ?> (<strong>numéro de matricule :</strong> <?= $intervenantRh->getCodeRh() ?>). Il possède déjà actuellement une affectation pour l'année
                    universitaire <?= $intervenant->getAnnee()->getLibelle() ?>. Vous pouvez mettre à jour ses données personnelles si vous le souhaitez avec le bouton synchronisation en bas de page.</p>
            <?php elseif (!empty($affectationEnCours) && empty($contratsEnCours)): ?>
                <p>L'intervenant <?= $intervenantDossier->getPrenom() . ' ' . $intervenantDossier->getNomUsuel() ?> est bien dans le <?= $nameConnecteur ?> (<strong>numéro de matricule :</strong> <?= $intervenantRh->getCodeRh() ?>).Il possède une affectation mais pas encore de contrat
                    l'année <?= $intervenant->getAnnee()->getLibelle() ?>. Vous
                    pouvez le renouveller pour cette année à l'aide du formulaire ci-dessous.</p>
            <?php else: ?>
                <p>L'intervenant <?= $intervenantDossier->getPrenom() . ' ' . $intervenantDossier->getNomUsuel() ?> est bien dans le <?= $nameConnecteur ?> (<strong>numéro de matricule :</strong> <?= $intervenantRh->getCodeRh() ?>).Il ne possède pas encore d'affectation pour
                    l'année <?= $intervenant->getAnnee()->getLibelle() ?>. Vous pouvez le renouveller pour cette année à l'aide du formulaire ci-dessous.</p>
            <?php endif; ?>
        <?php endif; ?>
    </div>
    <?php if (!empty($form)): ?>
    <?php
    $form->prepare();
    $generiqueFieldset  = $form->get('generiqueFieldset');
    $connecteurFieldset = $form->get('connecteurForm');

    ?>
    <!-- BLOC AFFECTATION -->
    <?php if (!empty($affectationEnCours)): ?>
        <div class="panel panel-default">
            <div class="panel-heading">Affectation <?= $nameConnecteur ?> en cours</div>
            <div class="panel-body">
                <table class="table">
                    <thead>
                    <tr>
                        <th>Champs</th>
                        <th>Données</th>

                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td>Affecté a</td>
                        <td><?= $affectationEnCours->libLongStructureNiv2 ?></td>
                    </tr>
                    <tr>
                        <td>Date début</td>
                        <td><?= $affectationEnCours->dateDebutAffectation ?></td>
                    </tr>
                    <tr>
                        <td>Date fin</td>
                        <td><?= $affectationEnCours->dateFinAffectation ?></td>
                    </tr>
                    <tr>
                        <td>Type de rattachement</td>
                        <td><?= $affectationEnCours->libLongTypeRattachement ?></td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
    <?php else: ?>
        <div class="panel panel-default">
            <div class="panel-heading">Affectation <?= $nameConnecteur ?> en cours</div>
            <div class="panel-body" style="text-align:center;">
                Aucune affectation en cours dans SIHAM
            </div>
        </div>
    <?php endif; ?>
    <?php if (!empty($contratsEnCours)): ?>
        <div class="panel panel-default">
            <div class="panel-heading">Contrat <?= $nameConnecteur ?> en cours</div>
            <div class="panel-body">
                <table class="table">
                    <tbody>
                    <tr>
                        <td>Type de contrat</td>
                        <td><?= $contratsEnCours->libLongTypeContrat ?></td>
                    </tr>
                    <tr>
                        <td>Date début contrat</td>
                        <td><?= $contratsEnCours->dateDebutContrat ?></td>
                    </tr>
                    <tr>
                        <td>Date fin de contrat prévue</td>
                        <td><?= $contratsEnCours->dateFinPrevueContrat ?></td>
                    </tr>
                    <tr>
                        <td>Date fin de contrat réelle</td>
                        <td><?= $contratsEnCours->dateFinReelleContrat ?></td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
    <?php else: ?>
        <div class="panel panel-default">
            <div class="panel-heading">Contrat <?= $nameConnecteur ?> en cours</div>
            <div class="panel-body" style="text-align:center;">
                Aucun contrat en cours dans SIHAM
            </div>
        </div>
    <?php endif; ?>
    <?php if ($this->isAllowed($intervenant, \ExportRh\Assertion\ExportRhAssertion::PRIV_CAN_INTERVENANT_EXPORT_RH)): ?>
    <!--Partie générique du formulaire-->
    <div class="panel panel-default">
        <div class="panel-heading">Récapitulatif des données personnelles synchronisables</div>
        <div class="panel-body">

            <table class="table">
                <thead>
                <tr>
                    <th>Champs</th>
                    <th>OSE</th>
                    <th><?= $nameConnecteur ?></th>

                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>
                        <?= $this->formCheckbox($generiqueFieldset->get('adressePrincipale')); ?>
                        <?= $this->formLabel($generiqueFieldset->get('adressePrincipale')) ?> :
                    </td>
                    <td>
                        <?php
                        $adresse = '';
                        $adresse .= (!empty($intervenantDossier->getAdresseNumero())) ? $intervenantDossier->getAdresseNumero() . ' ' : '';
                        $adresse .= (!empty($intervenantDossier->getAdresseNumeroCompl())) ? $intervenantDossier->getAdresseNumeroCompl() . ' ' : '';
                        $adresse .= (!empty($intervenantDossier->getAdresseVoirie())) ? $intervenantDossier->getAdresseVoirie() . ' ' : '';
                        $adresse .= (!empty($intervenantDossier->getAdresseVoie())) ? $intervenantDossier->getAdresseVoie() . ' ' : '';
                        $adresse .= (!empty($intervenantDossier->getAdressePrecisions())) ? '<br/>' . $intervenantDossier->getAdressePrecisions() . ' ' : '';
                        $adresse .= '<br/>';
                        $adresse .= $intervenantDossier->getAdresseCodePostal() . ' ' . $intervenantDossier->getAdresseCommune();
                        echo $adresse;
                        ?>
                    </td>
                    <td class="active">
                        <?php
                        if (!empty($intervenantRh)) {
                            $adresse = '';
                            $adresse .= (!empty(trim($intervenantRh->getAdresseNumero()))) ? $intervenantRh->getAdresseNumero() . ' ' : '';
                            $adresse .= (!empty(trim($intervenantRh->getAdresseNumeroCompl()))) ? $intervenantRh->getAdresseNumeroCompl() . ' ' : '';
                            $adresse .= (!empty(trim($intervenantRh->getAdresseVoirie()))) ? $intervenantRh->getAdresseVoirie() . ' ' : '';
                            $adresse .= (!empty(trim($intervenantRh->getAdresseVoie()))) ? $intervenantRh->getAdresseVoie() . ' ' : '';
                            $adresse .= (!empty(trim($intervenantRh->getAdressePrecisions()))) ? '<br/>' . $intervenantRh->getAdressePrecisions() . ' ' : '';
                            $adresse .= '<br/>';
                            $adresse .= $intervenantRh->getAdresseCodePostal() . ' ' . $intervenantRh->getAdresseCommune();
                            echo $adresse;
                        }
                        ?>
                    </td>
                </tr>
                <tr>
                    <td>

                    </td>
                    <td><?= $intervenantDossier->getNomUsuel() ?></td>
                    <td class="active"><?= (!empty($intervenantRh)) ? $intervenantRh->getNomUsuel() : '' ?></td>
                </tr>
                <tr>
                    <td>
                        <?= $this->formCheckbox($generiqueFieldset->get('telPro')); ?>
                        <?= $this->formLabel($generiqueFieldset->get('telPro')) ?> :
                    </td>
                    <td><?= $intervenantDossier->getTelPro() ?></td>
                    <td class="active"><?= (!empty($intervenantRh)) ? $intervenantRh->getTelPro() : '' ?></td>
                </tr>
                <tr>
                    <td>
                        <?= $this->formCheckbox($generiqueFieldset->get('telPerso')); ?>
                        <?= $this->formLabel($generiqueFieldset->get('telPerso')) ?> :
                    </td>
                    <td><?= $intervenantDossier->getTelPerso() ?></td>
                    <td class="active"><?= (!empty($intervenantRh)) ? $intervenantRh->getTelPerso() : '' ?></td>
                </tr>
                <tr>
                    <td>
                        <?= $this->formCheckbox($generiqueFieldset->get('emailPro')); ?>
                        <?= $this->formLabel($generiqueFieldset->get('emailPro')) ?> :
                    </td>
                    <td><?= $intervenantDossier->getEmailPro() ?></td>
                    <td class="active"><?= (!empty($intervenantRh)) ? $intervenantRh->getEmailPro() : '' ?></td>
                </tr>
                <tr>
                    <td>
                        <?= $this->formCheckbox($generiqueFieldset->get('emailPerso')); ?>
                        <?= $this->formLabel($generiqueFieldset->get('emailPerso')) ?> :
                    </td>
                    <td><?= $intervenantDossier->getEmailPerso() ?></td>
                    <td class="active"><?= (!empty($intervenantRh)) ? $intervenantRh->getEmailPerso() : '' ?></td>
                </tr>

                <tr>
                    <td>
                        <?= $this->formCheckbox($generiqueFieldset->get('iban')); ?>
                        <?= $this->formLabel($generiqueFieldset->get('iban')) ?> :
                    </td>
                    <td><?= $intervenantDossier->getIBAN() ?></td>
                    <td class="active"><?= (!empty($intervenantRh)) ? $intervenantRh->getIBAN() : '' ?></td>
                </tr>
                <tr>
                    <td>
                        <?= $this->formCheckbox($generiqueFieldset->get('bic')); ?>
                        <?= $this->formLabel($generiqueFieldset->get('bic')) ?> :
                    </td>
                    <td><?= $intervenantDossier->getBIC() ?></td>
                    <td class="active"><?= (!empty($intervenantRh)) ? $intervenantRh->getBIC() : '' ?></td>
                </tr>
                </tbody>
            </table>

        </div>
    </div>
    <?php if ($priseEnCharge): ?>

    <!-- Formulaire spécifique au connecteur-->
    <?php
    echo $this->partial('export-rh/export-rh/' . $nameConnecteur . '/connecteurForm', compact('connecteurFieldset', 'nameConnecteur', 'intervenant'));
    ?>
</form>

    <p>
        <button onclick="$('.form-export-rh').submit();" class="btn btn-primary no-intranavigation">Prendre en charge l'intervenant</button>
    </p>
<?php elseif ($renouvellement): ?>
    <?php
    echo $this->partial('export-rh/export-rh/' . $nameConnecteur . '/connecteurForm', compact('connecteurFieldset', 'nameConnecteur', 'intervenant'));
    ?>
    </form>
    <p>
        <button onclick="$('.form-export-rh').submit();" class="btn btn-primary no-intranavigation">Renouveller l'intervenant</button>
    </p>
<?php else: ?>
    </form>
    <p>
        <button onclick="$('.form-export-rh').submit();" class="btn btn-primary no-intranavigation">Synchroniser les données personnelles</button>
    </p>
<?php endif; ?>
<?php endif; ?>


<?php endif; ?>
<?php endif; ?>

