<?php

/* @var $affectations Application\Entity\Db\Affectation[] */
/* @var $tri string */

$head = [
    'structure' => 'Structure',
    'role'      => 'Rôle',
    'personnel' => 'Personnel',
    'source'    => 'Src/Actions',
];

$canEdit = $this->isAllowed('privilege/'.\Application\Entity\Db\Privilege::DROIT_AFFECTATION_EDITION);
$ajoutUrl = $this->url( 'droits/affectations/edition' );

?>
<h1 class="page-header">Gestion des affectations</h1>


<table class="table table-bordered table-condensed">
<thead>
    <tr>
    <?php foreach( $head as $id => $label ): ?>
        <th style="white-space: nowrap">
            <a href="?tri=<?php echo $id ?>">
                <?php echo $label ?>
                <?php if ($tri == $id): ?>
                    <span class="glyphicon glyphicon-arrow-down" style="font-size: xx-small"></span>
                <?php endif; ?>
            </a>
        </th>
    <?php endforeach; ?>
    </tr>
</thead>
<tbody>
<?php foreach( $affectations as $affectation ): 
    $editionUrl     = $this->url( 'droits/affectations/edition',     ['affectation' => $affectation->getId()] );
    $suppressionUrl = $this->url( 'droits/affectations/suppression', ['affectation' => $affectation->getId()] );
?>
    <tr>
        <td><?php 
            $str = (string)$affectation->getStructure();
            if ('' == $str){
                $str = '<span class="bg-info">&Eacute;tablissement</span>';
            }
            echo $str;
        ?></td>
        <td><?php echo $affectation->getRole() ?></td>
        <td><?php echo $affectation->getPersonnel() ?></td>
        <td style="text-align: center;width:1%;white-space: nowrap"><?php
            if ($affectation->getSource()->isOse() && $canEdit){
                ?>
                <a href="<?php echo $editionUrl; ?>" class="ajax-modal" data-event="affectation-edition"><span class="glyphicon glyphicon-edit"></span></a>
                <a href="<?php echo $suppressionUrl; ?>" class="ajax-modal" data-event="affectation-suppression"><span class="glyphicon glyphicon-remove"></span></a>
                <?php
            }else{
                echo $affectation->getSource();
            }
        ?></td>
    </tr>
<?php endforeach; ?>
</tbody>
</table>
<?php if ($canEdit): // droits ?>
    <a href="<?php echo $ajoutUrl ?>" class="btn btn-primary ajax-modal" data-event="affectation-edition">Ajout d'une nouvelle affectation</a>
<?php endif; ?>
<?php echo $this->modalAjaxDialog('affectations-edition-suppression'); ?>
<script type="text/javascript">
    $(function() {
        $("body").on("affectation-edition", function(event, data) {
            window.location.reload();
        });

        $("body").on("affectation-suppression", function(event, data) {
            window.location.reload();
        });
    });
</script>