<?php

use Application\Entity\Db\Privilege;

$canViewRoles           = $this->isAllowed( 'privilege/'.Privilege::DROIT_ROLE_VISUALISATION);
$canViewPrivileges      = $this->isAllowed( 'privilege/'.Privilege::DROIT_PRIVILEGE_VISUALISATION);
$canViewAffectations    = $this->isAllowed( 'privilege/'.Privilege::DROIT_AFFECTATION_VISUALISATION);

?>
<h1 class="page-header">Gestion des droits d'accès</h1>

<dl>
    <?php if ($canViewRoles): ?>
    <dt><a href="<?php echo $this->url('droits/roles') ?>">Gestion des rôles</a></dt>
    <dd>
        Permet de visualiser les rôles existants. Permet également de les modifier,
        d'en ajouter ou d'en supprimer si vous avez les droits requis pour cela.
    </dd>
    <?php endif; ?>

    <?php if ($canViewPrivileges): ?>
    <dt><a href="<?php echo $this->url('droits/privileges') ?>">Gestion des privilèges</a></dt>
    <dd>
        Tableau de bord listant, par rôle, les privilèges qui lui sont accordés.
        Le tableau permet également, si vous en avez le droit, de modifier les privilèges accordés par rôle.
    </dd>
    <?php endif; ?>

    <?php if ($canViewAffectations): ?>
    <dt><a href="<?php echo $this->url('droits/affectations') ?>">Gestion des affectations</a></dt>
    <dd>
        Permet de visualiser les affectations existantes et de les modifier le cas échéant. Pour rappel, une affectation
        est la liaison entre un rôle et un personnel.
    </dd>
    <?php endif; ?>
</dl>
<style>

   dt{
        padding-top:2em;
    }

</style>