<?php

/* @var $form Application\Form\Gestion\RoleForm */
/* @var $errors array */


echo $this->form()->openTag($form->prepare());

if ($errors) {
    echo $this->messenger()->setMessages([UnicaenApp\View\Helper\Messenger::ERROR => $errors]);
}

echo $this->formControlGroup($form->get('code'));
echo $this->formControlGroup($form->get('libelle'));
echo $this->formControlGroup($form->get('perimetre'));
echo $this->formControlGroup($form->get('peut-changer-structure'));
echo $this->formControlGroup($form->get('accessible-exterieur'));
echo $this->formRow($form->get('submit'));
echo $this->formHidden($form->get('id'));

echo $this->form()->closeTag();