<style>
    div.bootstrap-select.header-select { width: 85% !important; }
    button.form-set-value { width: 10% !important; }
</style>

<?php

$this->headTitle($title);
echo '<h1 class="page-header">' . $title . '</h1>';

echo $this->formEtapeCentreCoutSaisie($form);

echo $this->formErrors($form);
if ($errors) {
    echo $this->messenger()->setMessages([UnicaenApp\View\Helper\Messenger::ERROR => $errors]);
}
?>

<script>
    $(function() {
        /**
         * Redéfinition de la fonction définie dans "app.js" pour que cela fonctionne avec le "bootstrap-select" installé
         * sur les select.
         */
        EtapeCentreCout.setFormValues = function (typeHeuresCode, value)
        {
            $('form#etape-centre-cout select[name$="\\[' + typeHeuresCode + '\\]"]').selectpicker('val', value);
        }

        /**
         * Installation d'un "bootstrap-select" sur les select.
         */
        $('select.selectpicker').attr('data-live-search', 'true').selectpicker();
    });

</script>