<?php $this->headTitle($title); ?>
<h1 class="page-header"><?php echo $title ?></h1>

<?php

echo $this->etapeCentreCoutForm($form);

echo $this->formErrors($form);
if ($errors) {
    echo $this->messenger()->setMessages([UnicaenApp\View\Helper\Messenger::ERROR => $errors]);
}

?>
<style>
    div.bootstrap-select.header-select {
        width: 85% !important;
    }

    button.form-set-value {
        width: 10% !important;
    }
</style>
