<?php
/**
 * Generated by UnicaenCode
 * Commande : ose-code  module='ExportRh'
 */
return [
    'export-rh/export-rh/siham/dataREN'                => __DIR__ . '/view/export-rh/export-rh/siham/dataREN.phtml',
    'export-rh/export-rh/siham/dataPEC'                => __DIR__ . '/view/export-rh/export-rh/siham/dataPEC.phtml',
    'export-rh/export-rh/siham/dataSYNC'               => __DIR__ . '/view/export-rh/export-rh/siham/dataSYNC.phtml',
    'export-rh/export-rh/siham/connecteurForm'         => __DIR__ . '/view/export-rh/export-rh/siham/connecteurForm.phtml',
    'export-rh/export-rh/exporter'                     => __DIR__ . '/view/export-rh/export-rh/exporter.phtml',
    'export-rh/administration/chercher-intervenant-rh' => __DIR__ . '/view/export-rh/administration/chercher-intervenant-rh.phtml',
    'export-rh/administration/voir-intervenant-rh'     => __DIR__ . '/view/export-rh/administration/voir-intervenant-rh.phtml',
    'export-rh/administration/index'                   => __DIR__ . '/view/export-rh/administration/index.phtml',
];