<?php
/**
 * @var $this                       \Application\View\Renderer\PhpRenderer
 * @var $intervenant                \Application\Entity\Db\Intervenant
 * @var $missionsWithoutPrime       int
 * @var $canAddMission              bool
 * @var $typeVolumeHoraire          \Service\Entity\Db\TypeVolumeHoraire
 */

use Application\Entity\Db\WfEtape;
use Application\Provider\Privilege\Privileges;

$canGerer = $this->isAllowed(Privileges::getResourceId(Privileges::MISSION_PRIME_GESTION));

$title = 'Indemnités de fin de contrat';
$nextEtape = WfEtape::CODE_MISSION_VALIDATION_REALISE;

$this->intervenant($intervenant)->renderTitle($title);


echo $this->vue('mission/liste-prime', [
    'intervenant'          => $intervenant->getId(),
    'missionsWithoutPrime' => $missionsWithoutPrime,
    'canGerer'             => $canGerer,
]);

echo '<br />';


