<?php
/**
 * @var $this                       \Application\View\Renderer\PhpRenderer
 * @var $intervenant                \Intervenant\Entity\Db\Intervenant
 * @var $missionsWithoutPrime       int
 * @var $canAddMission              bool
 * @var $typeVolumeHoraire          \Service\Entity\Db\TypeVolumeHoraire
 */

use Application\Provider\Privileges;
use Workflow\Entity\Db\WorkflowEtape;

$canGerer = $this->isAllowed(Privileges::getResourceId(Privileges::MISSION_PRIME_GESTION));

$title = 'Indemnités de fin de contrat';
$wfEtape = WorkflowEtape::MISSION_PRIME;

$this->intervenant($intervenant)->renderTitle($title);

echo $this->vue('mission/liste-prime', [
    'intervenant'          => $intervenant->getId(),
    'missionsWithoutPrime' => $missionsWithoutPrime,
    'canGerer'             => $canGerer,
]);

echo '<br />';

echo $this->vue('workflow/nav', ['intervenant' => $intervenant->getId(), 'etape' => $wfEtape]);