<?php

/**
 * @var $this                     \Application\View\Renderer\PhpRenderer
 * @var $title                    string
 * @var $prime                    \Mission\Entity\Db\Prime
 * @var $mission                  \Mission\Entity\Db\Mission
 * @var $intervenant              \Intervenant\Entity\Db\Intervenant
 * @var $missions                 \Application\Entity\Collection
 */

?>

<?= $this->tag('h1', ['class' => 'page-header'])->html($title); ?>
<?php if(!empty($missions)): ?>
<form action="<?= $this->url('prime/saisie', ['intervenant' => $intervenant->getId(), 'prime' => ($prime) ? $prime->getId() : '']) ?>" method="post">

    <?php foreach ($missions as $mission): ?>
        <?php

        $missionPrimeId = $mission->getPrime() ? $mission->getPrime()->getId() : '';
        $primeId        = $prime ? $prime->getId() : '';
        ?>
        <?php if (empty($mission->getPrime()) || $missionPrimeId == $primeId): ?>
            <div class="form-check">
                <input <?= ($missionPrimeId == $primeId && !empty($missionPrimeId)) ? 'checked' : '' ?> class="form-check-input" type="checkbox"
                                                                                                        name="missions[<?= $mission->getId() ?>]">
                <strong><?= $mission->getTypeMission()->getLibelle() . ' - ' . $mission->getStructure()->getLibelle() ?></strong><br/>
                <i> Du <?= $mission->getDateDebut()->format('d/m/Y') ?> au <?= $mission->getDateFin()->format('d/m/Y'); ?></i>

            </div>
        <?php endif; ?>

    <?php endforeach; ?>

    <input type="submit" name="submit" class="btn btn-primary btn-save" value="Enregistrer">
</form>
<?php else: ?>
<div class="text-center" >Aucune mission éligible à une indémnité de fin de contrat</div>
<?php endif; ?>
