<?php

use Application\Provider\Privileges;

/**
 * @var $this              \Application\View\Renderer\PhpRenderer
 * @var $structure         \Lieu\Entity\Db\Structure
 * @var $validation        \Workflow\Entity\Db\Validation
 * @var $services          \Referentiel\Entity\Db\ServiceReferentiel[]
 * @var $typeVolumeHoraire \Service\Entity\Db\TypeVolumeHoraire
 *
 */

$validerUrl = null;
$devaliderUrl = null;

if ($this->isAllowed($validation, $typeVolumeHoraire->getPrivilegeReferentielValidation())) {
    $validerUrl = $this->url('intervenant/validation/referentiel/valider', [
        'typeVolumeHoraire' => $typeVolumeHoraire->getId(),
        'structure'         => $structure->getId(),
    ], [], true);
}

if ($this->isAllowed($validation, Privileges::REFERENTIEL_DEVALIDATION)) {
    $devaliderUrl = $this->url('intervenant/validation/referentiel/devalider', [
        'validation' => $validation->getId(),
    ], [], true);
}

$id = $validation->getId() ? 'validation-' . $validation->getId() : 'structure-' . $structure->getId();

?>

<div class="validation card bg-<?= $validation->getId() ? 'success' : 'default' ?>" id="<?= $id ?>">
    <div class="card-header card-header-h3">
        <h3><?= $validation->getId() ? 'Validation ' : 'Référentiel ' ?><?= $structure ?></h3>
    </div>
    <div class="card-body">
        <!-- Informations -->

        <?php if ($validation->getId()): ?>
            <ul style="list-style-type: none">
                <li><i class="fas fa-thumbs-up"></i> Validé
                    le <?= $validation->getHistoCreation()->format(\Application\Constants::DATE_FORMAT) ?>
                    par <?= $this->utilisateur($validation->getHistoCreateur()) ?></li>
            </ul>
        <?php endif; ?>

        <!-- Enseignements concernés -->
        <a title="Cliquez pour afficher/masquer le référentiel concerné"
           href="#details-referentiel-<?= $id ?>"
           role="button"
           aria-expanded="false"
           aria-controls="details-referentiel-<?= $id ?>"
           data-bs-toggle="collapse"
        >Référentiel concerné
            <small>(cliquez pour afficher/cacher)</small>
        </a>
        <div class="collapse <?= $validation->getId() ? '' : 'in' ?>" id="details-referentiel-<?= $id ?>">
            <?php
                $cs = current($services);
                if ($cs) {
                    echo $this->referentiels($typeVolumeHoraire, current($services)->getIntervenant(), $services)->setReadonly(true)->render();
                }
            ?>
        </div>

    </div>

    <?php if ($validerUrl || $devaliderUrl): ?>
        <div class="card-footer">
            <!-- Actions -->
            <?php if ($validerUrl): ?>
                <a
                        href="<?= $validerUrl ?>"
                        class="validation-delete btn btn-primary btn-primary pop-ajax"
                        data-submit-reload="true"
                        data-content="<p class='lead text-danger'><strong>Attention!</strong> Confirmez-vous cette validation ?</p>"
                        data-confirm="true"
                        data-confirm-button="Oui"
                        data-cancel-button="Non"
                ><i class="fas fa-thumbs-up"></i> Valider</a>
            <?php endif; ?>
            <?php if ($devaliderUrl): ?>
                <a
                        href="<?= $devaliderUrl ?>"
                        class="validation-delete btn btn-primary btn-danger pop-ajax"
                        data-submit-reload="true"
                        data-content="<p class='lead text-danger'><strong>Attention!</strong> Confirmez-vous cette dévalidation ?</p>"
                        data-confirm="true"
                        data-confirm-button="Oui"
                        data-cancel-button="Non"
                ><i class="fas fa-thumbs-down"></i> Dévalider</a>
            <?php endif; ?>
        </div>
    <?php endif; ?>
</div>