<?php
/*
* @author JORIOT Florian <florian.joriot at unicaen.fr>
*/

/**
 * @var $this  \Application\View\Renderer\PhpRenderer
 */

use Application\Provider\Privilege\Privileges;

function affBooleen($flg)
{
    // affiche booléen avec des glypheIcon
    return ($flg ? '<i class="fas fa-check "></i>' : '<i class="fas fa-xmark "></i>');
}

$this->headTitle()->append("Gestion des types de formations");
$canEdit = $this->isAllowed(Privileges::getResourceId(Privileges::ODF_TYPE_FORMATION_EDITION));
echo $this->messenger()->addCurrentMessagesFromFlashMessenger();
?>

<h1 class="page-header">Gestion des types de formations</h1>
<div class="triables ui-sortable">
    <?php foreach ($groupeTypeFormations as $groupeTypeFormation): ?>
        <div class="champ-triable" data-id= <?php echo $groupeTypeFormation->getId() ?>>
            <div class="panel panel-default">
                <div class="panel-heading"><?= $groupeTypeFormation->getLibelleLong(); ?> (<?= $groupeTypeFormation->getLibelleCourt(); ?>)
                    <?php if ($canEdit): ?>
                        <div class="pull-right">
                            <a class="ajax-modal " data-event="type-formation-edition"
                               href="<?= $this->url('type-formation/saisie-groupe', ['groupeTypeFormation' => $groupeTypeFormation->getId()], ['query' => ['tab' => 'edition']]) ?>"
                               title="Modifier la collection"><i class="fas fa-pen-to-square"></i></a>

                            <a class="pop-ajax " data-title="Suppression d'une collection" data-content="Êtes-vous sur de vouloir supprimer"
                               data-confirm="true"
                               data-submit-reload="true"
                               href="<?= $this->url('type-formation/supprimer-groupe', ['groupeTypeFormation' => $groupeTypeFormation->getId()]) ?>"
                               title="Supprimer la collection"><i class="fas fa-trash-can"></i></a>
                            <i class="fas fa-arrows-up-down-left-right"
                               title="Vous pouvez trier les champs en déplaçant les lignes du tableau"></i>
                        </div>
                    <?php endif; ?>
                </div>

                <table class="table table-bordered table-condensed">
                    <thead>
                    <tr>
                        <th style="text-align: center">Libellé court</th>
                        <th style="text-align: center">Libellé long</th>
                        <th style="text-align: center">Source</th>
                        <?php if ($canEdit): ?>
                            <th style="text-align: center">Actions</th>
                        <?php endif; ?>
                    </tr>
                    </thead>
                    <tbody class="triables ui-sortable">
                    <?php foreach ($groupeTypeFormation->getTypeFormation() as $typeFormation): ?>
                        <tr class="champ-triable" data-id= <?php echo $typeFormation->getId() ?>>
                            <td><?= $typeFormation->getLibelleCourt(); ?></td>
                            <td style="text-align: center"><?= $typeFormation->getLibelleLong(); ?></td>
                            <td style="text-align: center"><?= $typeFormation->getSource()->getLibelle(); ?></td>
                            <?php if ($canEdit): ?>
                                <td style="text-align: center">
                                    <a class="ajax-modal" data-event="type-formation-edition"
                                       href="<?= $this->url('type-formation/saisie', ['typeFormation' => $typeFormation->getId()], ['query' => ['tab' => 'edition']]) ?>"
                                       title="Modifier le type de formation"><i class="fas fa-pen-to-square"></i></a>
                                    <a class="pop-ajax" data-title="Suppression du type de formation" data-content="Êtes-vous sur de vouloir supprimer"
                                       data-confirm="true"
                                       data-submit-reload="true"
                                       href="<?= $this->url('type-formation/supprimer', ['typeFormation' => $typeFormation->getId()]) ?>"
                                       title="Supprimer le type de formation"><i class="fas fa-trash-can"></i></a>
                                </td>
                            <?php endif; ?>

                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>


            </div>
        </div>
    <?php endforeach; ?>
</div>
<?php if ($canEdit): ?>
    <tr class="champ-triable">
        <a class="btn btn-primary ajax-modal " data-event="groupe-type-formation-edition" href="<?= $this->url('type-formation/saisie-groupe'); ?>"><i
                    class="fas fa-plus"></i>
            Ajout d'un nouveau groupe
        </a>
    </tr>
<?php endif; ?>
<?php if ($canEdit): ?>
    <tr class="champ-triable">
        <a class="btn btn-primary ajax-modal " data-event="type-formation-edition" href="<?= $this->url('type-formation/saisie'); ?>"><i
                    class="fas fa-plus"></i>
            Ajout d'un nouveau type de formation</a>
    </tr>
<?php endif; ?>


<script type="text/javascript">
    $(function () {
        $(".triables").sortable({
            handle: '.fa-arrows-up-down-left-right',
            axis: 'y',
            update: function (event, ui) {
                var champsIds = '';
                ui.item.parent().find('div.champ-triable').each(function () {
                    if (champsIds != '') champsIds += ',';
                    champsIds += $(this).data('id');
                });

                $.ajax({
                    type: 'POST',
                    url: "<?= $this->url('type-formation/trier')?>",
                    data: {champsIds: champsIds},
                    success: function () { alertFlash("Tri effectué", 'success', 3000); },
                });
            }
        });
    });

    $(function () {
        $("body").on("type-formation-edition", function (event, data) {
            window.location.reload();
        });
    });

    $(function () {
        $("body").on("groupe-type-formation-edition", function (event, data) {
            window.location.reload();
        });
    });
</script>