<?php

//@formatter:off

return [
    'name'        => 'ACT_ODF_RELATIONS',
    'temporary'   => FALSE,
    'logging'     => TRUE,
    'commentaire' => 'ACT_ODF_RELATIONS',
    'sequence'    => NULL,
    'columns'     => [
        'ANNEE_ID'            => [
            'name'        => 'ANNEE_ID',
            'type'        => 'int',
            'bdd-type'    => 'NUMBER',
            'length'      => 0,
            'scale'       => NULL,
            'precision'   => NULL,
            'nullable'    => TRUE,
            'default'     => NULL,
            'position'    => 1,
            'commentaire' => NULL,
        ],
        'CHOIX_MAXIMUM'       => [
            'name'        => 'CHOIX_MAXIMUM',
            'type'        => 'int',
            'bdd-type'    => 'NUMBER',
            'length'      => 0,
            'scale'       => '0',
            'precision'   => 2,
            'nullable'    => TRUE,
            'default'     => NULL,
            'position'    => 7,
            'commentaire' => NULL,
        ],
        'CHOIX_MINIMUM'       => [
            'name'        => 'CHOIX_MINIMUM',
            'type'        => 'int',
            'bdd-type'    => 'NUMBER',
            'length'      => 0,
            'scale'       => '0',
            'precision'   => 2,
            'nullable'    => TRUE,
            'default'     => NULL,
            'position'    => 6,
            'commentaire' => NULL,
        ],
        'COD_PEL'             => [
            'name'        => 'COD_PEL',
            'type'        => 'string',
            'bdd-type'    => 'VARCHAR2',
            'length'      => 20,
            'scale'       => NULL,
            'precision'   => NULL,
            'nullable'    => TRUE,
            'default'     => NULL,
            'position'    => 21,
            'commentaire' => NULL,
        ],
        'COMP_INF_ID'         => [
            'name'        => 'COMP_INF_ID',
            'type'        => 'string',
            'bdd-type'    => 'VARCHAR2',
            'length'      => 3,
            'scale'       => NULL,
            'precision'   => NULL,
            'nullable'    => TRUE,
            'default'     => NULL,
            'position'    => 17,
            'commentaire' => NULL,
        ],
        'COMP_SUP_ID'         => [
            'name'        => 'COMP_SUP_ID',
            'type'        => 'string',
            'bdd-type'    => 'VARCHAR2',
            'length'      => 3,
            'scale'       => NULL,
            'precision'   => NULL,
            'nullable'    => TRUE,
            'default'     => NULL,
            'position'    => 5,
            'commentaire' => NULL,
        ],
        'ECTS'                => [
            'name'        => 'ECTS',
            'type'        => 'int',
            'bdd-type'    => 'NUMBER',
            'length'      => 0,
            'scale'       => NULL,
            'precision'   => NULL,
            'nullable'    => TRUE,
            'default'     => NULL,
            'position'    => 23,
            'commentaire' => NULL,
        ],
        'LIBELLE'             => [
            'name'        => 'LIBELLE',
            'type'        => 'string',
            'bdd-type'    => 'VARCHAR2',
            'length'      => 120,
            'scale'       => NULL,
            'precision'   => NULL,
            'nullable'    => TRUE,
            'default'     => NULL,
            'position'    => 18,
            'commentaire' => NULL,
        ],
        'LIBELLE_COURT'       => [
            'name'        => 'LIBELLE_COURT',
            'type'        => 'string',
            'bdd-type'    => 'VARCHAR2',
            'length'      => 25,
            'scale'       => NULL,
            'precision'   => NULL,
            'nullable'    => TRUE,
            'default'     => NULL,
            'position'    => 19,
            'commentaire' => NULL,
        ],
        'LIBELLE_COURT_LISTE' => [
            'name'        => 'LIBELLE_COURT_LISTE',
            'type'        => 'string',
            'bdd-type'    => 'VARCHAR2',
            'length'      => 25,
            'scale'       => NULL,
            'precision'   => NULL,
            'nullable'    => TRUE,
            'default'     => NULL,
            'position'    => 13,
            'commentaire' => NULL,
        ],
        'LIBELLE_LISTE'       => [
            'name'        => 'LIBELLE_LISTE',
            'type'        => 'string',
            'bdd-type'    => 'VARCHAR2',
            'length'      => 120,
            'scale'       => NULL,
            'precision'   => NULL,
            'nullable'    => TRUE,
            'default'     => NULL,
            'position'    => 12,
            'commentaire' => NULL,
        ],
        'LIEN_LSE_EXPORTED'   => [
            'name'        => 'LIEN_LSE_EXPORTED',
            'type'        => 'string',
            'bdd-type'    => 'VARCHAR2',
            'length'      => 1,
            'scale'       => NULL,
            'precision'   => NULL,
            'nullable'    => TRUE,
            'default'     => NULL,
            'position'    => 10,
            'commentaire' => NULL,
        ],
        'LISTE_ID'            => [
            'name'        => 'LISTE_ID',
            'type'        => 'string',
            'bdd-type'    => 'VARCHAR2',
            'length'      => 20,
            'scale'       => NULL,
            'precision'   => NULL,
            'nullable'    => TRUE,
            'default'     => NULL,
            'position'    => 8,
            'commentaire' => NULL,
        ],
        'LSE_EXPORTED'        => [
            'name'        => 'LSE_EXPORTED',
            'type'        => 'string',
            'bdd-type'    => 'VARCHAR2',
            'length'      => 1,
            'scale'       => NULL,
            'precision'   => NULL,
            'nullable'    => TRUE,
            'default'     => NULL,
            'position'    => 9,
            'commentaire' => NULL,
        ],
        'NATURE'              => [
            'name'        => 'NATURE',
            'type'        => 'string',
            'bdd-type'    => 'VARCHAR2',
            'length'      => 20,
            'scale'       => NULL,
            'precision'   => NULL,
            'nullable'    => TRUE,
            'default'     => NULL,
            'position'    => 20,
            'commentaire' => NULL,
        ],
        'NOEUD_INF_EXPORTED'  => [
            'name'        => 'NOEUD_INF_EXPORTED',
            'type'        => 'string',
            'bdd-type'    => 'VARCHAR2',
            'length'      => 20,
            'scale'       => NULL,
            'precision'   => NULL,
            'nullable'    => TRUE,
            'default'     => NULL,
            'position'    => 15,
            'commentaire' => NULL,
        ],
        'NOEUD_INF_ID'        => [
            'name'        => 'NOEUD_INF_ID',
            'type'        => 'string',
            'bdd-type'    => 'VARCHAR2',
            'length'      => 20,
            'scale'       => NULL,
            'precision'   => NULL,
            'nullable'    => TRUE,
            'default'     => NULL,
            'position'    => 14,
            'commentaire' => NULL,
        ],
        'NOEUD_SUP_EXPORTED'  => [
            'name'        => 'NOEUD_SUP_EXPORTED',
            'type'        => 'string',
            'bdd-type'    => 'VARCHAR2',
            'length'      => 1,
            'scale'       => NULL,
            'precision'   => NULL,
            'nullable'    => TRUE,
            'default'     => NULL,
            'position'    => 3,
            'commentaire' => NULL,
        ],
        'NOEUD_SUP_ID'        => [
            'name'        => 'NOEUD_SUP_ID',
            'type'        => 'string',
            'bdd-type'    => 'VARCHAR2',
            'length'      => 20,
            'scale'       => NULL,
            'precision'   => NULL,
            'nullable'    => TRUE,
            'default'     => NULL,
            'position'    => 2,
            'commentaire' => NULL,
        ],
        'STRUCTURE_INF_ID'    => [
            'name'        => 'STRUCTURE_INF_ID',
            'type'        => 'string',
            'bdd-type'    => 'VARCHAR2',
            'length'      => 20,
            'scale'       => NULL,
            'precision'   => NULL,
            'nullable'    => TRUE,
            'default'     => NULL,
            'position'    => 16,
            'commentaire' => NULL,
        ],
        'STRUCTURE_SUP_ID'    => [
            'name'        => 'STRUCTURE_SUP_ID',
            'type'        => 'string',
            'bdd-type'    => 'VARCHAR2',
            'length'      => 20,
            'scale'       => NULL,
            'precision'   => NULL,
            'nullable'    => TRUE,
            'default'     => NULL,
            'position'    => 4,
            'commentaire' => NULL,
        ],
        'TEM_A_DIS_ELP'       => [
            'name'        => 'TEM_A_DIS_ELP',
            'type'        => 'string',
            'bdd-type'    => 'VARCHAR2',
            'length'      => 20,
            'scale'       => NULL,
            'precision'   => NULL,
            'nullable'    => TRUE,
            'default'     => NULL,
            'position'    => 22,
            'commentaire' => NULL,
        ],
        'TYPE_CHOIX'          => [
            'name'        => 'TYPE_CHOIX',
            'type'        => 'string',
            'bdd-type'    => 'VARCHAR2',
            'length'      => 1,
            'scale'       => NULL,
            'precision'   => NULL,
            'nullable'    => TRUE,
            'default'     => NULL,
            'position'    => 11,
            'commentaire' => NULL,
        ],
    ],
];

//@formatter:on
