<?php

//@formatter:off

return [
    'name'        => 'ACT_DIPLOME',
    'temporary'   => FALSE,
    'logging'     => TRUE,
    'commentaire' => 'ACT_DIPLOME',
    'sequence'    => NULL,
    'columns'     => [
        'ANNEE_ID'          => [
            'name'        => 'ANNEE_ID',
            'type'        => 'string',
            'bdd-type'    => 'VARCHAR2',
            'length'      => 4,
            'scale'       => NULL,
            'precision'   => NULL,
            'nullable'    => FALSE,
            'default'     => NULL,
            'position'    => 1,
            'commentaire' => NULL,
        ],
        'CMP_APO'           => [
            'name'        => 'CMP_APO',
            'type'        => 'string',
            'bdd-type'    => 'VARCHAR2',
            'length'      => 3,
            'scale'       => NULL,
            'precision'   => NULL,
            'nullable'    => TRUE,
            'default'     => NULL,
            'position'    => 7,
            'commentaire' => NULL,
        ],
        'COLLEGIUM'         => [
            'name'        => 'COLLEGIUM',
            'type'        => 'string',
            'bdd-type'    => 'VARCHAR2',
            'length'      => 6,
            'scale'       => NULL,
            'precision'   => NULL,
            'nullable'    => TRUE,
            'default'     => NULL,
            'position'    => 9,
            'commentaire' => NULL,
        ],
        'DOMAINE_FORMATION' => [
            'name'        => 'DOMAINE_FORMATION',
            'type'        => 'string',
            'bdd-type'    => 'VARCHAR2',
            'length'      => 4,
            'scale'       => NULL,
            'precision'   => NULL,
            'nullable'    => TRUE,
            'default'     => NULL,
            'position'    => 11,
            'commentaire' => NULL,
        ],
        'LIBELLE'           => [
            'name'        => 'LIBELLE',
            'type'        => 'string',
            'bdd-type'    => 'VARCHAR2',
            'length'      => 120,
            'scale'       => NULL,
            'precision'   => NULL,
            'nullable'    => TRUE,
            'default'     => NULL,
            'position'    => 2,
            'commentaire' => NULL,
        ],
        'LIBELLE_COURT'     => [
            'name'        => 'LIBELLE_COURT',
            'type'        => 'string',
            'bdd-type'    => 'VARCHAR2',
            'length'      => 25,
            'scale'       => NULL,
            'precision'   => NULL,
            'nullable'    => TRUE,
            'default'     => NULL,
            'position'    => 3,
            'commentaire' => NULL,
        ],
        'LIBELLE_COURT_VDI' => [
            'name'        => 'LIBELLE_COURT_VDI',
            'type'        => 'string',
            'bdd-type'    => 'VARCHAR2',
            'length'      => 25,
            'scale'       => NULL,
            'precision'   => NULL,
            'nullable'    => TRUE,
            'default'     => NULL,
            'position'    => 14,
            'commentaire' => NULL,
        ],
        'LIBELLE_VDI'       => [
            'name'        => 'LIBELLE_VDI',
            'type'        => 'string',
            'bdd-type'    => 'VARCHAR2',
            'length'      => 120,
            'scale'       => NULL,
            'precision'   => NULL,
            'nullable'    => TRUE,
            'default'     => NULL,
            'position'    => 13,
            'commentaire' => NULL,
        ],
        'MENTION_ACCREDITE' => [
            'name'        => 'MENTION_ACCREDITE',
            'type'        => 'string',
            'bdd-type'    => 'VARCHAR2',
            'length'      => 5,
            'scale'       => NULL,
            'precision'   => NULL,
            'nullable'    => TRUE,
            'default'     => NULL,
            'position'    => 5,
            'commentaire' => NULL,
        ],
        'SECTEUR_SISE'      => [
            'name'        => 'SECTEUR_SISE',
            'type'        => 'string',
            'bdd-type'    => 'VARCHAR2',
            'length'      => 4,
            'scale'       => NULL,
            'precision'   => NULL,
            'nullable'    => TRUE,
            'default'     => NULL,
            'position'    => 10,
            'commentaire' => NULL,
        ],
        'SOURCE_CODE'       => [
            'name'        => 'SOURCE_CODE',
            'type'        => 'string',
            'bdd-type'    => 'VARCHAR2',
            'length'      => 20,
            'scale'       => NULL,
            'precision'   => NULL,
            'nullable'    => FALSE,
            'default'     => NULL,
            'position'    => 8,
            'commentaire' => NULL,
        ],
        'TEM_EXPORTED'      => [
            'name'        => 'TEM_EXPORTED',
            'type'        => 'string',
            'bdd-type'    => 'VARCHAR2',
            'length'      => 1,
            'scale'       => NULL,
            'precision'   => NULL,
            'nullable'    => TRUE,
            'default'     => NULL,
            'position'    => 12,
            'commentaire' => NULL,
        ],
        'TEM_EXPORTED_VDI'  => [
            'name'        => 'TEM_EXPORTED_VDI',
            'type'        => 'string',
            'bdd-type'    => 'VARCHAR2',
            'length'      => 1,
            'scale'       => NULL,
            'precision'   => NULL,
            'nullable'    => TRUE,
            'default'     => NULL,
            'position'    => 15,
            'commentaire' => NULL,
        ],
        'Z_STRUCTURE_ID'    => [
            'name'        => 'Z_STRUCTURE_ID',
            'type'        => 'string',
            'bdd-type'    => 'VARCHAR2',
            'length'      => 20,
            'scale'       => NULL,
            'precision'   => NULL,
            'nullable'    => TRUE,
            'default'     => NULL,
            'position'    => 6,
            'commentaire' => NULL,
        ],
        'Z_TYPE_DIPLOME_ID' => [
            'name'        => 'Z_TYPE_DIPLOME_ID',
            'type'        => 'string',
            'bdd-type'    => 'VARCHAR2',
            'length'      => 20,
            'scale'       => NULL,
            'precision'   => NULL,
            'nullable'    => TRUE,
            'default'     => NULL,
            'position'    => 4,
            'commentaire' => NULL,
        ],
    ],
];

//@formatter:on
