<?php

//@formatter:off

return [
    'name'        => 'ACT_ETAPE',
    'temporary'   => FALSE,
    'logging'     => TRUE,
    'commentaire' => 'ACT_ETAPE',
    'sequence'    => NULL,
    'columns'     => [
        'ANNEE_ID'            => [
            'name'        => 'ANNEE_ID',
            'type'        => 'string',
            'bdd-type'    => 'VARCHAR2',
            'length'      => 4,
            'scale'       => NULL,
            'precision'   => NULL,
            'nullable'    => FALSE,
            'default'     => NULL,
            'position'    => 1,
            'commentaire' => NULL,
        ],
        'CMP_APO'             => [
            'name'        => 'CMP_APO',
            'type'        => 'string',
            'bdd-type'    => 'VARCHAR2',
            'length'      => 3,
            'scale'       => NULL,
            'precision'   => NULL,
            'nullable'    => TRUE,
            'default'     => NULL,
            'position'    => 7,
            'commentaire' => NULL,
        ],
        'COD_CGE'             => [
            'name'        => 'COD_CGE',
            'type'        => 'string',
            'bdd-type'    => 'VARCHAR2',
            'length'      => 6,
            'scale'       => NULL,
            'precision'   => NULL,
            'nullable'    => TRUE,
            'default'     => NULL,
            'position'    => 22,
            'commentaire' => NULL,
        ],
        'COD_ETP'             => [
            'name'        => 'COD_ETP',
            'type'        => 'string',
            'bdd-type'    => 'VARCHAR2',
            'length'      => 6,
            'scale'       => NULL,
            'precision'   => NULL,
            'nullable'    => FALSE,
            'default'     => NULL,
            'position'    => 14,
            'commentaire' => NULL,
        ],
        'COD_VRS_VET'         => [
            'name'        => 'COD_VRS_VET',
            'type'        => 'int',
            'bdd-type'    => 'NUMBER',
            'length'      => 0,
            'scale'       => '0',
            'precision'   => 3,
            'nullable'    => FALSE,
            'default'     => NULL,
            'position'    => 15,
            'commentaire' => NULL,
        ],
        'COLLEGIUM'           => [
            'name'        => 'COLLEGIUM',
            'type'        => 'string',
            'bdd-type'    => 'VARCHAR2',
            'length'      => 6,
            'scale'       => NULL,
            'precision'   => NULL,
            'nullable'    => TRUE,
            'default'     => NULL,
            'position'    => 25,
            'commentaire' => NULL,
        ],
        'DOMAINE_FONCTIONNEL' => [
            'name'        => 'DOMAINE_FONCTIONNEL',
            'type'        => 'string',
            'bdd-type'    => 'VARCHAR2',
            'length'      => 20,
            'scale'       => NULL,
            'precision'   => NULL,
            'nullable'    => FALSE,
            'default'     => NULL,
            'position'    => 10,
            'commentaire' => NULL,
        ],
        'DROIT_BOURSE'        => [
            'name'        => 'DROIT_BOURSE',
            'type'        => 'string',
            'bdd-type'    => 'VARCHAR2',
            'length'      => 10,
            'scale'       => NULL,
            'precision'   => NULL,
            'nullable'    => TRUE,
            'default'     => NULL,
            'position'    => 23,
            'commentaire' => NULL,
        ],
        'DUREE_ETAPE'         => [
            'name'        => 'DUREE_ETAPE',
            'type'        => 'string',
            'bdd-type'    => 'VARCHAR2',
            'length'      => 10,
            'scale'       => NULL,
            'precision'   => NULL,
            'nullable'    => TRUE,
            'default'     => NULL,
            'position'    => 26,
            'commentaire' => NULL,
        ],
        'FA'                  => [
            'name'        => 'FA',
            'type'        => 'bool',
            'bdd-type'    => 'NUMBER',
            'length'      => 0,
            'scale'       => '0',
            'precision'   => 1,
            'nullable'    => FALSE,
            'default'     => '0',
            'position'    => 12,
            'commentaire' => NULL,
        ],
        'FC'                  => [
            'name'        => 'FC',
            'type'        => 'bool',
            'bdd-type'    => 'NUMBER',
            'length'      => 0,
            'scale'       => '0',
            'precision'   => 1,
            'nullable'    => FALSE,
            'default'     => '0',
            'position'    => 13,
            'commentaire' => NULL,
        ],
        'FI'                  => [
            'name'        => 'FI',
            'type'        => 'bool',
            'bdd-type'    => 'NUMBER',
            'length'      => 0,
            'scale'       => '0',
            'precision'   => 1,
            'nullable'    => FALSE,
            'default'     => '1',
            'position'    => 11,
            'commentaire' => NULL,
        ],
        'ID'                  => [
            'name'        => 'ID',
            'type'        => 'string',
            'bdd-type'    => 'VARCHAR2',
            'length'      => 20,
            'scale'       => NULL,
            'precision'   => NULL,
            'nullable'    => FALSE,
            'default'     => NULL,
            'position'    => 16,
            'commentaire' => NULL,
        ],
        'LIBELLE'             => [
            'name'        => 'LIBELLE',
            'type'        => 'string',
            'bdd-type'    => 'VARCHAR2',
            'length'      => 120,
            'scale'       => NULL,
            'precision'   => NULL,
            'nullable'    => FALSE,
            'default'     => NULL,
            'position'    => 2,
            'commentaire' => NULL,
        ],
        'LIBELLE_COURT'       => [
            'name'        => 'LIBELLE_COURT',
            'type'        => 'string',
            'bdd-type'    => 'VARCHAR2',
            'length'      => 25,
            'scale'       => NULL,
            'precision'   => NULL,
            'nullable'    => FALSE,
            'default'     => NULL,
            'position'    => 3,
            'commentaire' => NULL,
        ],
        'LIBELLE_WEB'         => [
            'name'        => 'LIBELLE_WEB',
            'type'        => 'string',
            'bdd-type'    => 'VARCHAR2',
            'length'      => 120,
            'scale'       => NULL,
            'precision'   => NULL,
            'nullable'    => TRUE,
            'default'     => NULL,
            'position'    => 24,
            'commentaire' => NULL,
        ],
        'NIVEAU'              => [
            'name'        => 'NIVEAU',
            'type'        => 'int',
            'bdd-type'    => 'NUMBER',
            'length'      => 0,
            'scale'       => '0',
            'precision'   => 6,
            'nullable'    => TRUE,
            'default'     => NULL,
            'position'    => 5,
            'commentaire' => NULL,
        ],
        'PARCOURS_TYPE_APO'   => [
            'name'        => 'PARCOURS_TYPE_APO',
            'type'        => 'string',
            'bdd-type'    => 'VARCHAR2',
            'length'      => 32,
            'scale'       => NULL,
            'precision'   => NULL,
            'nullable'    => TRUE,
            'default'     => NULL,
            'position'    => 20,
            'commentaire' => NULL,
        ],
        'PREM_SEM'            => [
            'name'        => 'PREM_SEM',
            'type'        => 'string',
            'bdd-type'    => 'VARCHAR2',
            'length'      => 15,
            'scale'       => NULL,
            'precision'   => NULL,
            'nullable'    => TRUE,
            'default'     => NULL,
            'position'    => 21,
            'commentaire' => NULL,
        ],
        'SOURCE_CODE'         => [
            'name'        => 'SOURCE_CODE',
            'type'        => 'string',
            'bdd-type'    => 'VARCHAR2',
            'length'      => 20,
            'scale'       => NULL,
            'precision'   => NULL,
            'nullable'    => FALSE,
            'default'     => NULL,
            'position'    => 8,
            'commentaire' => NULL,
        ],
        'SPECIFIQUE_ECHANGES' => [
            'name'        => 'SPECIFIQUE_ECHANGES',
            'type'        => 'bool',
            'bdd-type'    => 'NUMBER',
            'length'      => 0,
            'scale'       => '0',
            'precision'   => 1,
            'nullable'    => FALSE,
            'default'     => '0',
            'position'    => 9,
            'commentaire' => NULL,
        ],
        'STATUT_ACTUL'        => [
            'name'        => 'STATUT_ACTUL',
            'type'        => 'string',
            'bdd-type'    => 'VARCHAR2',
            'length'      => 32,
            'scale'       => NULL,
            'precision'   => NULL,
            'nullable'    => TRUE,
            'default'     => NULL,
            'position'    => 18,
            'commentaire' => NULL,
        ],
        'TEM_DN'              => [
            'name'        => 'TEM_DN',
            'type'        => 'int',
            'bdd-type'    => 'NUMBER',
            'length'      => 0,
            'scale'       => NULL,
            'precision'   => NULL,
            'nullable'    => TRUE,
            'default'     => NULL,
            'position'    => 17,
            'commentaire' => NULL,
        ],
        'TEM_EXPORTED'        => [
            'name'        => 'TEM_EXPORTED',
            'type'        => 'string',
            'bdd-type'    => 'VARCHAR2',
            'length'      => 1,
            'scale'       => NULL,
            'precision'   => NULL,
            'nullable'    => TRUE,
            'default'     => NULL,
            'position'    => 19,
            'commentaire' => NULL,
        ],
        'VDI_VET_ANNEE_MAX'   => [
            'name'        => 'VDI_VET_ANNEE_MAX',
            'type'        => 'int',
            'bdd-type'    => 'NUMBER',
            'length'      => 0,
            'scale'       => NULL,
            'precision'   => NULL,
            'nullable'    => TRUE,
            'default'     => NULL,
            'position'    => 28,
            'commentaire' => NULL,
        ],
        'VDI_VET_ANNEE_MIN'   => [
            'name'        => 'VDI_VET_ANNEE_MIN',
            'type'        => 'int',
            'bdd-type'    => 'NUMBER',
            'length'      => 0,
            'scale'       => NULL,
            'precision'   => NULL,
            'nullable'    => TRUE,
            'default'     => NULL,
            'position'    => 27,
            'commentaire' => NULL,
        ],
        'Z_STRUCTURE_ID'      => [
            'name'        => 'Z_STRUCTURE_ID',
            'type'        => 'string',
            'bdd-type'    => 'VARCHAR2',
            'length'      => 20,
            'scale'       => NULL,
            'precision'   => NULL,
            'nullable'    => TRUE,
            'default'     => NULL,
            'position'    => 6,
            'commentaire' => NULL,
        ],
        'Z_TYPE_FORMATION_ID' => [
            'name'        => 'Z_TYPE_FORMATION_ID',
            'type'        => 'string',
            'bdd-type'    => 'VARCHAR2',
            'length'      => 20,
            'scale'       => NULL,
            'precision'   => NULL,
            'nullable'    => FALSE,
            'default'     => NULL,
            'position'    => 4,
            'commentaire' => NULL,
        ],
    ],
];

//@formatter:on
