<?php

/**
 * @var $this              \Application\View\Renderer\PhpRenderer
 * @var $title             string
 * @var $form              \Mission\Form\MissionForm
 */

echo $this->tag('h1', ['class' => 'page-header'])->html($title);
echo $this->messenger()->addCurrentMessagesFromFlashMessengerWithNoNamespace();
echo $this->form()->openTag($form);

if ($form->has('structure')) {
    echo $this->formControlGroup($form->get('structure'));
}
echo $this->formControlGroup($form->get('typeMission'));
echo '<div class="row">';
echo '<div class="col-md-6">';
echo $this->formControlGroup($form->get('dateDebut'));
echo '</div>';
echo '<div class="col-md-6">';
echo $this->formControlGroup($form->get('dateFin'));
echo '</div>';
echo '</div>';

echo '<div class="row">';
echo '<div class="col-md-6">';
echo $this->formControlGroup($form->get('missionTauxRemu'));
echo '</div>';
echo '<div class="col-md-6">';
echo $this->formControlGroup($form->get('heures'));

echo '</div>';
echo '</div>';

echo $this->formControlGroup($form->get('description'));
echo $this->formControlGroup($form->get('autoValidation'));

echo $this->formSubmit($form->get('submit'));

echo $this->form()->closeTag();