<?php

/**
 * @var $this              \Application\View\Renderer\PhpRenderer
 * @var $title             string
 * @var $form              \Mission\Form\MissionSuiviForm
 */

echo $this->tag('h1', ['class' => 'page-header'])->html($title);
echo $this->messenger()->addCurrentMessagesFromFlashMessengerWithNoNamespace();
echo $this->form()->openTag($form);

$tabs = $this->tab();
$tabs->addPages([
    'mission'   => 'Mission',
    'formation' => 'Formation',
    'conges'    => 'Congés',
])->setCurrent($form->get('mode')->getValue());

echo $tabs();
echo $tabs->contentBegin();
echo $tabs->pageBegin('mission');
?>

<?= $this->formControlGroup($form->get('mission')) ?>
<?= $this->formControlGroup($form->get('nocturne')) ?>

<?php
echo $tabs->pageEnd();
echo $tabs->pageBegin('formation');
?>
    formation
<?php
echo $tabs->pageEnd();
echo $tabs->pageBegin('conges');
?>
    congés
<?php
echo $tabs->pageEnd();
echo $tabs->contentEnd();

echo $this->formSubmit($form->get('submit'));

echo $this->form()->closeTag();