<?php
/**
 * @var $this              \Application\View\Renderer\PhpRenderer
 * @var $intervenant       \Application\Entity\Db\Intervenant
 * @var $missions          array
 */

use Application\Entity\Db\WfEtape;

$title     = 'Suivi de missions';
$nextEtape = WfEtape::CODE_MISSION_VALIDATION_REALISE;

$this->intervenant($intervenant)->renderTitle($title);

echo $this->vue('mission/suivi', [
    'intervenant' => $intervenant->getId(),
    'missions'    => $missions,
]);

echo '<br />';
echo $this->feuilleDeRoute($intervenant)->renderNav($nextEtape);