<?php

/**
 * @var $this              \Application\View\Renderer\PhpRenderer
 * @var $title             string
 * @var $form              \Mission\Form\MissionSuiviForm
 */

echo $this->messenger()->addCurrentMessagesFromFlashMessengerWithNoNamespace();
echo $this->form()->openTag($form);

echo $this->tag('h1', ['class' => 'page-header'])->html($title);

echo $this->formControlGroup($form->get('mission'));

echo '<div class="row">';

echo '<div class="col-md-4">';
echo $this->formControlGroup($form->get('date'));
echo '</div>';
echo '<div class="col-md-4">';
echo $this->formControlGroup($form->get('heureDebut'));
echo '</div>';
echo '<div class="col-md-4">';
echo $this->formControlGroup($form->get('heureFin'));
echo '</div>';

echo '</div>';


echo '<div class="row">';

echo '<div class="col-md-4">';
echo $this->formControlGroup($form->get('heures'));
echo '</div>';
echo '<div class="col-md-4"><label>&nbsp;</label>';
echo $this->formControlGroup($form->get('nocturne'));
echo '</div>';
echo '<div class="col-md-4"><label>&nbsp;</label>';
echo $this->formControlGroup($form->get('formation'));
echo '</div>';

echo '</div>';


echo $this->formControlGroup($form->get('description'));

echo $this->formSubmit($form->get('submit'));

echo $this->form()->closeTag();