<h1 class="page-header"><?php echo $this->title ?></h1>

<?php echo $this->messenger(true)->addMessages($messages) ?>

<?php if ($this->form): ?>
<div class="row">
    <div class="col-sm-4">
        <?php
        echo $this->form()->openTag($this->form);
        echo $this->formControlGroup($this->form->get('dateDecision'));
        echo $this->formHidden($this->form->get('security'));
        ?>
        
        <label>Cochez les intervenants à impacter :</label>
        <?php echo $this->formControlGroup($mcb = $this->form->get("intervenants")) ?>
        <hr />
        
        <?php echo $this->formSubmit($this->form->get('submit')->setAttribute('class', 'btn btn-primary')); ?>
        <?php echo $this->form()->closeTag(); ?>
    </div>
</div>
<?php endif ?>