<?php

/**
 * @var $this  \Application\View\Renderer\PhpRenderer
 * @var $form  \Application\Form\Agrement\Saisie
 */

?>
<h1 class="page-header">Saisie de l'agrément</h1>
<?= $this->messenger()->setCurrentMessagesFromFlashMessenger() ?>

<?php
echo $this->form()->openTag($form);
?>
<div class="row">
    <div class="col-md-12">
        <?= $this->formControlGroup($form->get('dateDecision')); ?>
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <?= $this->formSubmit($form->get('submit')->setAttribute('class', 'btn btn-primary')); ?>
    </div>
    <div class="col-md-6">
        <a class="btn btn-secondary pop-ajax-hide">Annuler</a>
    </div>
</div>
<?php

echo $this->formHidden($form->get('security'));
echo $this->form()->closeTag(); ?>
