<?php

/**
 * @var $this \Application\View\Renderer\PhpRenderer
 * @var $title string
 * @var $form \Application\Form\Agrement\Saisie
 */

?>
<h1 class="page-header"><?php echo $title ?></h1>
<?php echo $this->messenger()->setCurrentMessagesFromFlashMessenger() ?>
<div class="row">
    <div class="col-sm-5">
        <?php
        echo $this->form()->openTag($form);
        echo $this->formControlGroup($form->get('dateDecision'));
        echo $this->formHidden($form->get('security'));
        ?>
        <br />
        <?php echo $this->formSubmit($form->get('submit')->setAttribute('class', 'btn btn-primary')); ?>
        <?php echo $this->form()->closeTag(); ?>
    </div>
</div>