<?php

/**
 * @var $this  \Application\View\Renderer\PhpRenderer
 * @var $form  \OffreFormation\Form\EtapeSaisie
 * @var $title string
 */
echo $this->tag('h1', ['class' => 'page-header'])->html($title);
echo $this->form()->openTag($form->prepare());
echo $this->messenger()->addCurrentMessagesFromFlashMessenger();

?>
<div class="row">
    <div class="col-sm-4">
        <?php
        echo $this->formControlGroup($form->get('code'));
        ?>
    </div>
    <div class="col-sm-8">
        <?php
        echo $this->formControlGroup($form->get('structure'));
        ?>
    </div>
</div>
<div class="row">
    <div class="col-sm-12">
        <?php
        echo $this->formControlGroup($form->get('libelle'));
        ?>
    </div>
</div>
<div class="row">
    <div class="col-sm-5">
        <?php
        echo $this->formControlGroup($form->get('typeFormation'));
        ?>
    </div>
    <div class="col-sm-3">
        <?php
        echo $this->formControlGroup($form->get('niveau'));
        ?>
    </div>
    <div class="col-sm-4">
        <?php
        echo $this->formControlGroup($form->get('specifiqueEchanges'));
        ?>
    </div>
</div>
<div class="row">
    <div class="col-sm-6">
        <?= $this->formControlGroup($form->get('domaineFonctionnel')) ?>
    </div>
    <div class="col-sm-6">
        <?= $this->formControlGroup($form->get('autre1')) ?>
    </div>
</div>

<?php
echo $this->formRow($form->get('submit'));
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();
?>

<script>
    var pertinencesNiveau = <?= \Laminas\Json\Json::encode($form->getPertinencesNiveau()) ?>;
    $(function () {
        $("select[name=typeFormation]")
            .change(function () {
                var niveau = $("input[name=niveau]");
                var tfId = $(this).val();
                var pertinent = tfId in pertinencesNiveau && pertinencesNiveau[tfId];
                pertinent ? niveau.attr('disabled', false) : niveau.attr('disabled', true).val("");
            })
            .change();
    });
</script>