<?php
echo $this->messenger()->addCurrentMessagesFromFlashMessengerWithNamespace('error');

echo $this->form()->openTag($form);
echo '<h2 class="title">Ajouter/modifier un circuit de signature</h2>';
echo $this->formControlGroup($form->get('label'));
echo $this->formControlGroup($form->get('description'));
echo $this->formControlGroup($form->get('enabled'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag($form);


?>
