<?php
echo $this->messenger()->addCurrentMessagesFromFlashMessengerWithNamespace('error');

echo '<h2 class="title">Ajouter/modifier un étape de signature</h2>';
echo $this->form()->openTag($form);
echo $this->formControlGroup($form->get('label'));
echo $this->formControlGroup($form->get('level'));
echo $this->formControlGroup($form->get('recipientMethod'));
echo $this->formControlGroup($form->get('roles'));
echo $this->formControlGroup($form->get('order'));
echo $this->formControlGroup($form->get('allRecipientsSign'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag($form);

?>


<script>

    toggleViewElements = function ()
    {
        document.querySelectorAll('[name="recipientMethod"]').forEach(element => {
            // Vérifier la valeur de chaque élément
            element.removeEventListener("change", toggleViewElements);
            element.addEventListener("change", toggleViewElements);
            let method = element.value
            let elementRole = element.parentElement.nextSibling;

            if (method == 'by_etablissement' || method == 'by_etablissement_and_intervenant') {
                elementRole.style.display = "block";

            } else {
                elementRole.style.display = "none";
            }
        });
    }
    toggleViewElements();


</script>