<?php 
$this->form->prepare();
$dossier = $this->form->get('dossier'); /* @var $dossier \Application\Form\Intervenant\DossierFieldset */
?>

<style>
    div.rib-part { display: inline-block; vertical-align: top; }
    div.rib-part input { width: auto; }
</style>

<?php echo $this->form()->openTag($this->form) ?> 
<div class="row">
    <div class="col-md-3">
        <?php echo $this->formControlGroup($dossier->get('nomUsuel')->setAttribute('readonly', $this->readonly)); ?>
        <?php echo $this->formControlGroup($dossier->get('nomPatronymique')->setAttribute('readonly', $this->readonly)); ?>
        <?php echo $this->formControlGroup($dossier->get('prenom')->setAttribute('readonly', $this->readonly)); ?>
        <?php echo $this->formControlGroup($dossier->get('civilite')->setAttribute('disabled', $this->readonly)); ?>
        <?php echo $this->formControlGroup($dossier->get('dateNaissance')->setAttribute('readonly', $this->readonly)); ?>
        <?php echo $this->formControlGroup($dossier->get('paysNaissance')->setAttribute('disabled', $this->readonly)); ?>
        <?php echo $this->formControlGroup($dossier->get('departementNaissance')->setAttribute('disabled', $this->readonly)); ?>
        <?php echo $this->formControlGroup($dossier->get('villeNaissance')->setAttribute('readonly', $this->readonly)); ?>
    </div>
    <div class="col-md-4">
        <?php echo $this->formControlGroup($dossier->get('numeroInsee')->setAttribute('readonly', $this->readonly)); ?>
        <?php echo $this->formControlGroup($dossier->get('numeroInseeEstProvisoire')->setAttribute('disabled', $this->readonly)); ?>
        <?php echo $this->formControlGroup($dossier->get('adresse')->setAttribute('readonly', $this->readonly)); ?>
        <?php echo $this->formControlGroup($dossier->get('email')->setAttribute('readonly', $this->readonly)); ?>
        <?php if ($dossier->has('emailPerso')) {
            echo $this->formControlGroup($dossier->get('emailPerso')->setAttribute('readonly', $this->readonly)); 
        } ?>
        <?php echo $this->formControlGroup($dossier->get('telephone')->setAttribute('readonly', $this->readonly)); ?>
    </div>
    <div class="col-md-5">
        <fieldset class="rib">
            <legend><?php echo $dossier->get('rib')->getLabel() ?></legend>
            <div class="rib-part"><?php echo $this->formControlGroup($dossier->get('rib')->get('bic')->setAttribute('readonly', $this->readonly)); ?></div>
            <div class="rib-part"><?php echo $this->formControlGroup($dossier->get('rib')->get('iban')->setAttribute('readonly', $this->readonly)); ?></div>
            <?php echo $this->formControlGroup($dossier->get('rib')->get('hidden')); ?>
        </fieldset>
        <?php if ($dossier->has('premierRecrutement')) {
            echo $this->formControlGroup($dossier->get('premierRecrutement')->setAttribute('disabled', $this->readonly)); 
        } ?>
        <div class="statut">
            <?php echo $this->formControlGroup($dossier->get('statut')->setAttribute('disabled', $this->readonly)); ?>
        </div>
        
        <?php echo $this->formHidden($dossier->get('id')); ?>

        <?php echo $this->formHidden($this->form->get('security')); ?>
        <?php if (!$this->readonly): ?>
            <hr />
            <?php echo $this->formSubmit($this->form->get('submit')->setAttribute('class', 'btn btn-primary')) ?>
        <?php endif ?>
    </div>
</div>
<?php echo $this->form()->closeTag() ?>


<?php if ($this->dossier->getId()): ?>
    <hr/>
    <div class="pull-right"><em>Dernière modification: <?php echo $this->dossier->getHistoModificationEtModificateurToString() ?></em></div>
<?php endif ?>





<script type="text/javascript" src="<?php echo $this->basePath() . '/js/moment-with-locales.min.js' ?>"></script>

<script type="text/javascript">
    $(function() {
        var readonly = <?php echo $this->readonly ? 'true' : 'false' ?>;

        managePaysNaissance();
        manageDepartementNaissance();
        
        function managePaysNaissance()
        {
            var tfDate     = $("input[name='dossier[dateNaissance]']");
            var selectPays = $("select[name='dossier[paysNaissance]']");
            
            // sélection de la France par défaut
            if (! selectPays.val()) {
                $("option.france", selectPays).prop("selected", "selected");
            }
        
            moment.locale('fr');
            
            /**
             * Fonction chargée de ne faire apparaître dans la liste déroulante 
             * que les pays étant valides à la date d'observation spécifiée.
             * 
             * @param {object} dateObservation
             * @returns {void}
             */
            function updateSelectPays(dateObservation)
            {
                $("option.pays", selectPays).each(function() {
                    var option          = $(this);
                    var dateDebutValid  = moment(option.data("debut"), "D/M/YYYY", true);
                    var dateFinValid    = option.data("fin") ? moment(option.data("fin"), "D/M/YYYY", true) : moment();

                    if (dateObservation.isBetween(dateDebutValid, dateFinValid)) {
                        option.show();
                    }
                    else {
                        option.removeProp('selected');
                        option.hide();
                    }
                });
            }
            
            // mise à jour de la liste des pays à chaque modif de la date de naissance
            tfDate.change(function() {
                var dateObservation = moment(tfDate.val(), "D/M/YYYY", true);
                if (! dateObservation.isValid()) {
                    dateObservation = moment();
                }
                updateSelectPays(dateObservation);
            });
            
            // init de la liste : pays valides à la date du jour
            tfDate.change();
        }
        
        function manageDepartementNaissance()
        {
            if (readonly) {
                return;
            }
            
            var selectPays = $("select[name='dossier[paysNaissance]']");
            var selectDept = $("select[name='dossier[departementNaissance]']");
            var emptyDept  = $("option[value='']", selectDept);
            
            selectPays.change(function() {
                if ($("option:selected", selectPays).hasClass("france")) {
                    selectDept.removeProp('disabled').parent().show();
                    emptyDept.html("(Sélectionnez un département...)");
                }
                else {
                    selectDept.prop('disabled', 'disabled').parent().hide();
                    emptyDept.html("(Aucun)").prop('selected', 'selected');
                }
            });
            
            selectPays.change();
        }
    });
</script>