<?php

/* @var $role Application\Entity\Db\Role */
/* @var $statut Application\Entity\Db\StatutIntervenant */
/* @var $privilege Application\Entity\Db\Privilege */

$object = empty($role) ? $statut : $role;

if ($object->getPrivilege()->contains($privilege)):
?>

    <a href="javascript:void(0)" data-action="refuser" title="Privilège accordé. Cliquez pour le retirer.">
        <span class="glyphicon glyphicon-ok text-success"></span>
    </a>

<?php else: ?>

    <a class="refuse" href="javascript:void(0)" data-action="accorder" title="Privilège refusé. Cliquez pour l'accorder.">
        <span class="glyphicon glyphicon-remove text-danger"></span>
    </a>

<?php endif; ?>