<?php 

/* @var $indicateurs array  */

$this->headTitle()->append($title = "Indicateurs");

?>

<h1 class="page-header"><?php echo $title ?></h1>

<style>
    .categorie { width: 180px; }
    .notification { width: 180px; }
</style>

<?php
echo $this->partial('application/indicateur/partial/list', [
    'indicateurs'      => $indicateurs,
    'indicateursImpl'  => $this->indicateursImpl,
    'abonnements'      => $this->abonnements,
    'abonnementsInfos' => $this->abonnementsInfos,
    'abonnementUrl'    => $this->abonnementUrl,
    'showAbonnement'   => true,
]);
