<?php

use Application\Provider\Privilege\Privileges;

$this->intervenant($intervenant)->renderTitle('Candidature');
$canValiderCandidature = $this->isAllowed(Privileges::getResourceId(Privileges::MISSION_CANDIDATURE_VALIDER));


echo $this->vue('mission/liste-candidatures', [

    'intervenant'           => $intervenant->getId(),
    'canValiderCandidature' => $canValiderCandidature,
]);

$nextEtape = \Application\Entity\Db\WfEtape::CANDIDATURE_SAISIE;

echo '<hr />';

echo $this->feuilleDeRoute($intervenant)->renderNav($nextEtape);