<h1><?php echo $this->title ?></h1>

<?php echo $this->messenger(true) ?>

<?php $form->prepare(); ?>

<?php echo $this->form()->openTag($form) ?> 
<?php echo $this->formControlGroup($form->get('interv')); ?>
<input class="btn btn-primary" type="submit" value="Choisir" name="submit">
<?php echo $this->form()->closeTag() ?> 

<script>
    $(function() {
        $("form.intervenant-rech :input").tooltip({ /*placement: 'left'*/ });
        $("input[name='interv[label]']").focus();
    });
</script>