<?php $this->headTitle($this->title) ?>

<h1 class="page-header"><?= $this->title ?></h1>

<?= $this->messenger()->addMessagesFromFlashMessenger() ?>

<?php $form->prepare(); ?>

<?= $this->form()->openTag($form) ?>
<?= $this->formControlGroup($form->get('interv')); ?>
<input class="btn btn-primary" type="submit" value="Choisir" name="submit">
<?= $this->form()->closeTag() ?>

<hr />

<?php if ($recents): ?>
<h3>Vos recherches récentes :</h3>
<ul>
    <?php foreach($recents as $data): ?>
    <li><a class="choisir-recent"
                   data-id="<?= $data['sourceCode'] ?>"
                   data-label="<?= $data['nom'] ?>"
                   title="Cliquez pour choisir cet intervenant"
                   href="#"><?= $data['nom'] ?></a></li>
    <?php endforeach; ?>
</ul>
<?php endif; ?>

<script>
    $(function() {
        var form        = $("form.intervenant-rech");
        var intervId    = $("input[name='interv[id]']", form);
        var intervLabel = $("input[name='interv[label]']", form);
        var submit      = $("input[type=submit]", form);

        intervLabel.tooltip({ placement: 'bottom' }).focus();

        $("a.choisir-recent").click(function() {
            intervId.val($(this).data('id'));
            submit.click();
            return false;
        });
    });
</script>