<?php
$libelle = $this->translate('Je cloture la saisie de mon service réalisé.');
?>

<!----------------------------------------------------------------------------->
<!--                            Bouton de clôture                            -->
<!----------------------------------------------------------------------------->



    <?= $this->messenger()->renderMessage($this->avertissement, 'warning') ?>

    <button type="button" class="btn-cloturer-saisie btn btn-lg btn-info"><?= $libelle ?></button>

    <script>
        var url = '<?= $this->url('intervenant/cloturer-saisie', [], [], true) ?>';
        $(function() {
            $(".btn-cloturer-saisie").one('click', function(e) {
                e.preventDefault();
                e.stopImmediatePropagation(); // nécessaire si cette vue est rendue plus d'une fois.
                if (!confirm("<?= $this->confirm ?>")) {
                    return;
                }
                $.ajax({
                    type: 'POST',
                    url: url,
                    data: {cloturer: 1},
                    success: function () {
                        window.location.reload();
                    },
                });
            });
        });
    </script>


    <!----------------------------------------------------------------------------->
    <!--                       Clôture existante éventuelle                      -->
    <!----------------------------------------------------------------------------->
<?php if ($this->validation && $this->validation->getHistoModification() ): ?>
<?php if ($this->isAllowed($this->validation, 'read')): ?>

    <button type="button" class="btn-cloturer-saisie btn btn-lg btn-success" disabled="disabled"><?= $libelle ?> le
            <?= $this->validation->getHistoModification()->format(Application\Constants::DATETIME_FORMAT) ?></button>

    <script>
        $(function() {
            $(".btn-cloturer-saisie").parent().tooltip();
        });
    </script>

<?php endif;
endif;