<?php
/**
 * @var \Application\Entity\Db\Intervenant $intervenant
 * @var \ExportRh\Entity\IntervenantRh     $intervenantRh
 */

$intervenant->getNomUsuel()
?>
<br/>


<div class="messenger alert alert-warning">
    <?php if ($typeIntervenant == 'P'): ?>
        L'export des données intervenants vers le SIRH n'est disponible que pour les vacataires.
    <?php elseif (empty($intervenantDossierValidation)): ?>
        Vous devez d'abord valider les données personnelles de <?= $intervenant; ?> pour pouvoir les synchroniser avec le SIRH
    <?php endif; ?>
</div>
<table class="table">
    <thead>
    <tr>
        <th>Champs</th>
        <th>Intervenant OSE</th>
        <th>Intervenant SI RH</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td><input type="checkbox" checked="checked" name="nomUsuel"/> Nom usuel :</td>
        <td><?= $intervenant->getNomUsuel() ?></td>
        <td><?= $intervenantRh->getNomUsuel() ?></td>
    </tr>
    <tr>
        <td><input type="checkbox" checked="checked" name="nomUsuel"/> Prénom :</td>
        <td><?= $intervenant->getPrenom() ?></td>
        <td><?= $intervenantRh->getPrenom() ?></td>
    </tr>
    <tr>
        <td><input type="checkbox" checked="checked" name="nomUsuel"/> Date de naissance :</td>
        <td><?= $intervenant->getDateNaissance()->format('d/m/Y') ?></td>
        <td><?= $intervenantRh->getDateNaissance()->format('d/m/Y') ?></td>
    </tr>
    <tr>
        <td><input type="checkbox" checked="checked" name="nomUsuel"/> Numéro INSEE</td>
        <td><?= $intervenant->getNumeroInsee() ?></td>
        <td><?= $intervenantRh->getNumeroInsee() ?></td>
    </tr>
    <tr>
        <td><input type="checkbox" checked="checked" name="nomUsuel"/> Tel pro :</td>
        <td><?= $intervenant->getTelPro() ?></td>
        <td><?= $intervenantRh->getTelPro() ?></td>
    </tr>
    <tr>
        <td><input type="checkbox" checked="checked" name="nomUsuel"/> Tel perso :</td>
        <td><?= $intervenant->getTelPerso() ?></td>
        <td><?= $intervenantRh->getTelPerso() ?></td>
    </tr>

    </tbody>
</table>

