<?php
    /* @var $intervenants array */
?>
<table class="table table-bordered table-condensed">
    <thead>
    <tr>
        <th>&nbsp;</th>
        <th>Civilité</th>
        <th>Nom</th>
        <th>Prénom</th>
        <th>Structure</th>
        <th>Date de naissance</th>
        <th>N° personnel</th>
    </tr>
    </thead>
    <tbody class="table-hover">
    <?php foreach($intervenants as $sourceCode => $intervenant): ?>
    <tr>
        <td><a href="<?php echo $this->url('intervenant/voir', ['intervenant' => $sourceCode]); ?>">
                <span class="glyphicon glyphicon-eye-open"></span> Fiche
            </a></td>
        <td><?php echo $intervenant['civilite'] ?></td>
        <td><?php echo $intervenant['nom'] ?></td>
        <td><?php echo $intervenant['prenom'] ?></td>
        <td><?php echo $intervenant['structure'] ?></td>
        <td><?php echo $intervenant['date-naissance']->format(\Common\Constants::DATE_FORMAT) ?></td>
        <td><?php echo $intervenant['numero-personnel'] ?></td>
    </tr>
    </tbody>
    <?php endforeach; ?>
</table>