<?php
    /* @var $intervenants array */
?>
<table class="table table-bordered table-condensed">
    <thead>
    <tr>
        <th style="width:1%">&nbsp;</th>
        <th style="width:10%">Civilité</th>
        <th style="width:18%">Nom</th>
        <th style="width:18%">Prénom</th>
        <th style="width:18%">Structure</th>
        <th style="width:18%">Date de naissance</th>
        <th style="width:10%">N° personnel</th>
    </tr>
    </thead>
    <tbody class="table-hover">
    <?php foreach($intervenants as $sourceCode => $intervenant): ?>
    <tr>
        <td style="white-space: nowrap"><a href="<?php echo $this->url('intervenant/voir', ['intervenant' => $sourceCode]); ?>">
                <span class="glyphicon glyphicon-eye-open"></span> Fiche
            </a></td>
        <td><?php echo $intervenant['civilite'] ?></td>
        <td><?php echo $intervenant['nom'] ?></td>
        <td><?php echo $intervenant['prenom'] ?></td>
        <td><?php echo $intervenant['structure'] ?></td>
        <td><?php echo $intervenant['date-naissance']->format(\Application\Constants::DATE_FORMAT) ?></td>
        <td><?php echo $intervenant['numero-personnel'] ?></td>
    </tr>
    </tbody>
    <?php endforeach; ?>
</table>