<?php
    /* @var $recents []  */
?>
<h1>Rechercher un intervenant</h1>

<div style="padding:1em">
<div class="intervenant-recherche">
    <div class="critere">
        Saisissez le nom suivi éventuellement du prénom (2 lettres au moins) :
        <input id="critere" class="form-control input" type="text"  />
    </div>
    <div class="recherche" data-url="<?php echo $this->url('intervenant/recherche') ?>">

    </div>
</div>

<?php

if (! empty($recents)){
    echo '<h3>Fiches récemment consultées :</h3>';
    echo $this->partial('liste', ['intervenants' => $recents]);
}

?>
</div>
