<div class="jumbotron">
    <h1>Rechercher un intervenant</h1>
</div>

<?php $form->prepare(); ?>

<div class="row">
    <div class="col-md-4">
        <?php echo $this->form()->openTag($form) ?> 
        <?php echo $this->formControlGroup($form->get('interv')); ?>
        <input class="btn btn-primary" type="submit" value="Consulter" name="submit">
        <?php echo $this->form()->closeTag() ?> 
    </div>
    <div class="col-md-8 intervenant-voir">
        <?php if (false !== $intervenant): ?>
            <?php echo $intervenant ? $this->intervenantDl($intervenant, true) : "Intervenant introuvable dans OSE." ?> 
        <?php endif ?>
        <?php if ($intervenant): ?>
            <?php echo $this->navigation('navigation')->menuContextuel()->withTarget($intervenant->getId()) ?>
        <?php endif ?>
    </div>
</div>

<script>
    var url = '<?php echo $this->url('intervenant/default', array('action' => 'voir')) ?>';
    $("body").on("submit", "form.intervenant-rech", function(event) {
        var form = $(event.target);
        var id = $("input.sas", form).val();
        $.post(url, { 'id': id }, function(data) {
            $("div.intervenant-voir").html(data);
        });
        event.preventDefault();
    });
    
    $(document).ajaxComplete(function(event, xhr, settings) {
        if (xhr.status === 403) {
            alert("Votre session a expiré, vous allez devoir vous reconnecter...");
            $(location).attr('href', '<?php echo $this->url('zfcuser/login') ?>?redirect=' + $(location).attr('href'));
        }
    });

    $(function() {
        $(":input").tooltip();
    });
</script>

<div class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Modal title</h4>
            </div>
            <div class="modal-body">
                <p>One fine body&hellip;</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
