<h2 class="page-header">Saisie de dossier <small><?php echo $intervenant ?></small></h2>

<style>
    div.rib-part { display: inline-block; vertical-align: top; }
    div.rib-part input { width: auto; }
    div.ouinon label { font-weight: normal ; }
    input[type=radio] { margin-left: 2em; margin-right: 3px; }
</style>

<?php echo $this->form()->openTag($form->prepare()) ?> 
<div class="row">
    <div class="col-md-3">
        <?php echo $this->formControlGroup($form->get('nomUsuel')); ?>
        <?php echo $this->formControlGroup($form->get('nomPatronymique')); ?>
        <?php echo $this->formControlGroup($form->get('prenom')); ?>
        <?php echo $this->formControlGroup($form->get('civilite')); ?>
        <?php echo $this->formControlGroup($form->get('numeroInsee')); ?>
    </div>
    <div class="col-md-3">
        <?php echo $this->formControlGroup($form->get('adresse')); ?>
        <?php echo $this->formControlGroup($form->get('email')); ?>
        <?php echo $this->formControlGroup($form->get('telephone')); ?>
    </div>
    <div class="col-md-6">
        <?php echo $this->formControlGroup($form->get('typeEmployeur')); ?>
        <label class="control-label"><?php echo $form->get('premierRecrutement')->getLabel() ?></label><br />
        <div class="ouinon"><?php echo $this->formRadio($form->get('premierRecrutement')); ?></div>
        <label class="control-label"><?php echo $form->get('perteEmploi')->getLabel() ?></label><br />
        <div class="ouinon"><?php echo $this->formRadio($form->get('perteEmploi')); ?></div>
        <?php echo $this->formControlGroup($form->get('statut')); ?>
        <fieldset class="rib">
            <legend>RIB</legend>
            <div class="rib-part"><?php echo $this->formControlGroup($form->get('rib')->get('bic')); ?></div>
            <div class="rib-part"><?php echo $this->formControlGroup($form->get('rib')->get('iban')); ?></div>
            <?php echo $this->formControlGroup($form->get('rib')->get('hidden')); ?>
        </fieldset>
    </div>
</div>
<?php echo $this->formHidden($form->get('id')); ?>
<hr />
<input class="btn btn-primary" type="submit" value="Enregistrer" name="submit">
<?php echo $this->form()->closeTag() ?> 

<script>
    $(function() {
        $(":input").tooltip({ placement: 'bottom' });
    });
</script>

<?php //$this->navigation('navigation')->menuSecondaire()->addParam('id', $intervenant->getSourceCode()) ?>