<?php

use Application\Entity\Db\WfEtape;
use Application\Provider\Privilege\Privileges;
/**
 * @var $this              \Application\View\Renderer\PhpRenderer
 * @var $intervenant       \Application\Entity\Db\Intervenant
 * @var $typeVolumeHoraire \Application\Entity\Db\TypeVolumeHoraire
 */

$canAddService = $this->isAllowed($intervenant, Privileges::ENSEIGNEMENT_EDITION);

if ($typeVolumeHoraire->isPrevu()){
    $nextEtape = WfEtape::CODE_SERVICE_SAISIE;
    $title = 'Enseignements';
}else{
    $nextEtape = WfEtape::CODE_SERVICE_SAISIE_REALISE;
    $title = 'Constatation des enseignements réalisés';
}

$menuUrl = $this->url('intervenant/services', ['intervenant' => $intervenant->getRouteParam()], ['query' => ['menu' => 1]] );

$btnNextUrl = $this->url('workflow/feuille-de-route-btn-next', ['intervenant' => $intervenant->getRouteParam(), 'wfEtapeCode' => $nextEtape]);

$this->headTitle()->append($intervenant->getNomUsuel())->append($title);
$title .= ' <small>'.$intervenant.'</small>';


?>
<h1 class="page-header"><?php echo $title; ?></h1>
<?php

echo $this->messenger()->addCurrentMessagesFromFlashMessenger();

if (isset($clotureSaisie)) echo $clotureSaisie;

/* Services et horodatage */
$serviceListe = $this->serviceListe( $services );
$serviceListe->setTypeVolumeHoraire($typeVolumeHoraire)->setAddButtonVisibility($canAddService);
if ($canAddService && $typeVolumeHoraire->isPrevu()){
    $serviceListe->showPrevuToPrevu($intervenant);
}
echo $serviceListe->render();

echo $this->partial('application/intervenant/partial/horodatage', [
    'intervenant'       => $intervenant,
    'typeVolumeHoraire' => $typeVolumeHoraire,
    'referentiel'       => false
]);

/* Référentiel et horodatage */
if (isset($referentiel)){
    echo $referentiel;
    echo $this->partial('application/intervenant/partial/horodatage', [
        'intervenant'       => $intervenant,
        'typeVolumeHoraire' => $typeVolumeHoraire,
        'referentiel'       => true
    ]);
}var_dump('REFERENTIEL A FAIRE');

echo $formuleTotauxHetd;

if (isset($clotureSaisie)) echo $clotureSaisie;

?>

<hr/>
<div id="feuille-de-route-btn-next" data-url="<?php echo $btnNextUrl ?>">
    <?php echo $this->feuillederoute($intervenant)->renderNav($nextEtape); ?>
</div>
<script>

    $(function ()
    {

        $('.service-liste').serviceListe({
            'heures-change-exists': function ()
            {
                // chargement du menu pour faire apparaître ou disparaitre les liens de validation
                $('#sidebar').load('<?php echo $menuUrl; ?>');

                // rafraichissement du bouton de la feuille de route pour pointer vers la prochaine bonne étape
                $('#feuille-de-route-btn-next').refresh();
            },
            'heures-change': function ()
            {
                // on met à jour le résultat de la formule
                $("#formule-totaux-hetd").refresh(); // HETD rafraichis

                // on met à jour l'horodatage des services !!
                $("#s-horodatage").refresh();
            }
        });

    });

</script>