<?php

/**
 * @var $this        \Application\View\Renderer\PhpRenderer
 * @var $intervenant \Application\Entity\Db\Intervenant
 * @var $tree        \Application\Model\TreeNode
 */

if (!$tree) {
    ?>
    <script>
        window.location.href = "<?= $intervenant ? $this->url('intervenant/voir', ['intervenant' => 'code:' . $intervenant->getCode()]) : $this->url('intervenant/rechercher') ?>";
    </script>
    <div class="loading">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Veuillez patienter pendant le rechargement de la page ...
        ...
    </div>
    <?php
    die();
} else {
    ?>
    <script>
        $('#sidebar').load('<?= $this->url('intervenant/voir', ['intervenant' => $intervenant->getId()], ['query' => ['menu' => 1]]); ?>')
    </script>
    <?php
}

echo $this->tag('div', [
    'id'                  => 'int-suppr-div',
    'data-supprimer-url'  => $this->url('intervenant/supprimer', ['intervenant' => $intervenant->getId()]),
    'data-historiser-url' => $this->url('intervenant/historiser', ['intervenant' => $intervenant->getId()]),
])->open();

echo $this->messenger()->addCurrentMessagesFromFlashMessenger();

echo $this->tree($tree, ['id' => 'intervenant-suppr']);


?>
    <br/>

    <button id="suppressionIntervenantData" type="button" class="btn btn-danger" data-bs-toggle="popover" data-trigger="focus"
            title="Suppression de données intervenant">
        Supprimer les données sélectionnées
    </button>
    <div id="supprEnCours" style="display:none" class="loading">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Suppression en cours
        ...
    </div>
<?php if ($intervenant->estNonHistorise()): ?>
    <button id="historisationIntervenantData" type="button" class="btn btn-secondary" data-bs-toggle="popover" data-trigger="focus"
            title="Historisation de la fiche de l'intervenant">
        Historiser la fiche de l'intervenant
    </button>
<?php endif; ?>
    <script>
        $(function () {
            $('#suppressionIntervenantData').popover({
                html: true,
                content:
                    '<div class="alert alert-warning">Attention : les données supprimées ne pourront pas être restaurées</div>' +
                    'Souhaitez-vous vraiment supprimer les données sélectionnées ?<br /><br />' +
                    '<button onclick="supprimer()" class="btn btn-danger">Oui, supprimer</button>' +
                    '&nbsp;<button onclick="$(\'#suppressionIntervenantData\').popover(\'hide\')" class="btn btn-secondary">Non, laisser telle qu\'elle la fiche</button>'
            });

            $('#historisationIntervenantData').popover({
                html: true,
                content:
                    '<div class="alert alert-warning">Attention : Aucune donnée ne sera véritablement supprimée. La fiche de l\'intervenant ne sera simplement plus visible dans OSE ni dans les extractions (CSV, PDF, ...)</div>' +
                    'Souhaitez-vous vraiment historiser la fiche de l\'intervenant ?<br /><br />' +
                    '<button onclick="historiser()" class="btn btn-warning">Oui, historiser</button>' +
                    '&nbsp;<button onclick="$(\'#historisationIntervenantData\').popover(\'hide\')" class="btn btn-secondary">Non, laisser telle qu\'elle la fiche</button>'
            });
        });


        function supprimer()
        {
            $('#supprEnCours').show();

            var div = $('#int-suppr-div');
            var tree = $('#intervenant-suppr');
            var selectedElms = tree.jstree("get_selected", true);
            var ids = [];
            $.each(selectedElms, function ()
            {
                ids.push(this.id);
            });

            div.load(div.data('supprimer-url'), {
                ids: ids
            });
        }

        function historiser()
        {
            var div = $('#int-suppr-div');
            window.location.href = div.data('historiser-url');
        }

    </script>

<?php