<?php

/**
 * @var $this        \Application\View\Renderer\PhpRenderer
 * @var $intervenant \Application\Entity\Db\Intervenant
 * @var $tree        \Application\Model\TreeNode
 */

echo $this->tag('div', [
    'id'       => 'int-suppr-div',
    'data-url' => $this->url('intervenant/supprimer', ['intervenant' => $intervenant->getId()]),
])->open();

echo $this->messenger()->addCurrentMessagesFromFlashMessenger();

echo $this->tree($tree, ['id' => 'intervenant-suppr']);


?>
    <button class="btn btn-danger" onclick="supprimer()">Supprimer définitivement les données sélectionnées</button>
    <script>

        function supprimer()
        {
            var div = $('#int-suppr-div');
            var tree = $('#intervenant-suppr');
            var selectedElms = tree.jstree("get_selected", true);
            var ids = [];
            $.each(selectedElms, function ()
            {
                ids.push(this.id);
            });

            div.load(div.data('url'), {
                ids: ids
            });
        }

    </script>

<?php