<?php

/**
 * @var $this            \Application\View\Renderer\PhpRenderer
 * @var $intervenant     \Application\Entity\Db\Intervenant
 * @var $isImportable    bool
 * @var $data            array
 */

if (!$isImportable) {
    echo $this->tag('div', ['class' => 'alert alert-warning'])->html('Cet intervenant n\'est pas synchronisable');

    return;
}


?>
    <table class="table table-bordered table-condensed">
        <tr>
            <th>Source</th>
            <th colspan="2">OSE</th>
        </tr>
        <?php foreach ($data as $d): ?>
            <tr>
                <td><?= $d['source-statut'] ?></td>
                <td><?= $d['intervenant-statut'] ?></td>
                <td><?php
                    if ($d['histo-destruction']) {
                        echo 'Supprimée le ' . $d['histo-destruction'] . ' par ' . $d['histo-destructeur'] . ' ';
                        echo $this->tag('a', [
                            'class' => 'no-intranavigation',
                            'href'  => $this->url('intervenant/restaurer', ['intervenant' => $d['id']]),
                            'title' => 'Restaurer la fiche de l\'intervenant',
                        ])->html($this->tag('span', ['class' => 'glyphicon glyphicon-open']));
                    }
                    ?></td>
            </tr>
        <?php endforeach; ?>
    </table>
<?php

if ($isImportable) {
    echo $this->tag('a', [
        'href'  => $this->url('intervenant/synchroniser', ['intervenant' => $intervenant->getId()]),
        'title' => 'Synchroniser (import vers OSE)',
        'class' => 'btn btn-default no-intranavigation',
    ])->html('Synchroniser (import vers OSE)');
}