<?php
/* @var $this \Zend\View\Renderer\PhpRenderer */
/* @var $intervenant Application\Entity\Db\Intervenant */

$serviceDu          = $formule->getServiceDu($intervenant);
$modifServiceDu     = $formule->getModifServiceDu($intervenant);
$heures             = $formule->getHeuresComplementaires($intervenant);
$payer              = $formule->getAPayer($intervenant);
$heuresReelles      = $serviceDu + $modifServiceDu + $heures;

function ffh( $heures )
{
    $formated = number_format($heures,2, ',', ' ');

    if (0 == (int)$heures){
        $formated = '<span style="color:#bbb">'.$formated.'</span>';
    }

    echo $formated;
}

function ffc( $montant )
{
    ffh( $montant );
    echo ' €';
}

$url = $this->url('intervenant/total-heures-comp', ['intervenant' => $intervenant->getSourceCode()]);

?>

<div id="details-hetd" data-url="<?php echo $this->escapeHtmlAttr($url)?>">
<?php if ($intervenant instanceof \Application\Entity\Db\IntervenantExterieur): ?>
    <div class="row" style="font-size:16pt">
        <div class="col-md-5">Total d'heures éq. TD (HETD) :</div>
      <div class="col-md-7"><span class="label label-success"><?php ffh( $heuresReelles ); ?></span></div>
    </div>
<?php else: ?>
    <div class="row" style="font-size:16pt">
      <div class="col-md-5"><abbr title="en heures équivalent TD (HETD)">Service dû + Heures complémentaires :</abbr></div>
      <div class="col-md-7"><span class="label label-success"><?php ffh( $heuresReelles ); ?></span></div>
    </div>
    <?php if ($heures < 0 ): ?>
        <div class="row" style="font-size:16pt">
          <div class="col-md-5"><abbr title="en heures équivalent TD (HETD)">Sous-service :</abbr></div>
          <div class="col-md-7"><span class="label label-danger"><?php ffh( $heures * -1 ); ?></span></div>
        </div>
    <?php elseif($heures > 0): ?>
        <div class="row" style="font-size:16pt">
          <div class="col-md-5"><abbr title="en heures équivalent TD (HETD)">Dont heures complémentaires :</abbr></div>
          <div class="col-md-7"><span class="label label-success"><?php ffh( $heures ); ?></span></div>
        </div>
    <?php endif; ?>
<?php endif;?>

<div class="row" style="font-size:16pt">
  <div class="col-md-5">A payer (brut) :</div>
  <div class="col-md-7"><span class="label label-success"><?php ffc( $payer ); ?></span></div>
</div>
</div>