<?php


use Application\Provider\Privilege\Privileges;

/* @var $intervenant \Application\Entity\Db\Intervenant */
/* @var $tab string */

$this->intervenant($intervenant)->renderTitle('Fiche');


$tabs = [
    [
        'id'            => 'fiche',
        'label'         => '<i class="fas fa-eye"></i> Fiche',
        'content'       => $this->partial('application/intervenant/fiche.phtml', compact('intervenant')),
        'url'           => $this->url('intervenant/fiche', ['intervenant' => $intervenant->getId()]),
        'force-refresh' => true,
    ],
];

if ($this->isAllowed(Privileges::getResourceId(Privileges::INTERVENANT_EDITION))) {
    $tabs[] = [
        'id'    => 'edition',
        'label' => '<i class="fas fa-pencil"></i> Édition',
        'url'   => $this->url('intervenant/saisir', ['intervenant' => $intervenant->getId()]),
    ];
}

if ($this->isAllowed(Privileges::getResourceId(Privileges::INTERVENANT_EDITION))) {
    $tabs[] = [
        'id'            => 'synchronisation',
        'label'         => '<i class="fas fa-download"></i> Synchronisation',
        'url'           => $this->url('intervenant/synchronisation', ['intervenant' => $intervenant->getId()]),
        'force-refresh' => true,
    ];
}

if ($this->isAllowed($intervenant, \ExportRh\Assertion\ExportRhAssertion::PRIV_CAN_INTERVENANT_EXPORT_RH)) {
    $tabs[] = [
        'id'            => 'export-rh',
        'label'         => '<i class="fas fa-upload"></i> Export RH',
        'url'           => $this->url('intervenant/exporter', ['intervenant' => $intervenant->getId()]),
        'force-refresh' => true,
    ];
}


if ($this->isAllowed(Privileges::getResourceId(Privileges::INTERVENANT_SUPPRESSION))) {
    $tabs[] = [
        'id'            => 'suppression',
        'label'         => '<i class="fas fa-trash-can"></i> Suppression',
        'url'           => $this->url('intervenant/supprimer', ['intervenant' => $intervenant->getId()]),
        'force-refresh' => true,
    ];
}


if ($this->isAllowed(Privileges::getResourceId(Privileges::PLAFONDS_DEROGATIONS_VISUALISATION))) {
    $tabs[] = [
        'id'            => 'derogations',
        'label'         => '<i class="fas fa-shuffle"></i> Dérogations',
        'url'           => $this->url('derogations', ['intervenant' => $intervenant->getId()]),
        'force-refresh' => true,
    ];
}

if ($this->isAllowed(Privileges::getResourceId(Privileges::INTERVENANT_NOTE_VISUALISATION))) {
    $tabs[] = [
        'id'            => 'notes',
        'label'         => '<span class="glyphicon glyphicon-book"></span> Notes <span class="badge" style="background-color: red;font-size:10px;margin-bottom:5px;">4</span>',
        'url'           => $this->url('note', ['intervenant' => $intervenant->getId()]),
        'force-refresh' => true,
    ];
}

echo $this->tabajax($tabs, $tab);