<?php

use Application\Provider\Privilege\Privileges;

/* @var $intervenant \Application\Entity\Db\Intervenant */
/* @var $role \Application\Acl\Role */

$this->headTitle()->append($intervenant->getNomUsuel())->append("Fiche");

?>

    <h1 class="page-header"><?= $intervenant ?>
        <small><?= $intervenant->getStatut()->getTypeIntervenant() ?></small>
    </h1>

<?php

$tabs = [
    [
        'id'            => 'fiche',
        'label'         => '<span class="glyphicon glyphicon-eye-open"></span> Fiche',
        'content'       => $this->partial('application/intervenant/fiche.phtml', compact('intervenant', 'role')),
        'url'           => $this->url('intervenant/fiche', ['intervenant' => $intervenant->getRouteParam()]),
        'force-refresh' => true,
    ],
];

if ($this->isAllowed(Privileges::getResourceId(Privileges::INTERVENANT_EDITION))) {
    $tabs[] = [
        'id'    => 'edition',
        'label' => '<span class="glyphicon glyphicon-pencil"></span> Édition',
        'url'   => $this->url('intervenant/saisir', ['intervenant' => $intervenant->getRouteParam()]),
    ];
}

if ($this->isAllowed(Privileges::getResourceId(Privileges::INTERVENANT_SUPPRESSION))) {
    $tabs[] = [
        'id'            => 'suppression',
        'label'         => '<span class="glyphicon glyphicon-trash"></span> Suppression',
        'url'           => $this->url('intervenant/supprimer', ['intervenant' => $intervenant->getRouteParam()]),
        'force-refresh' => true,
    ];
}

echo $this->tabajax($tabs);
