<h1><?php echo $intervenant ?> <small><?php echo $intervenant->getType() ?></small></h1>

<?php echo $this->intervenantDl($intervenant, true) ?>

<?php echo $this->navigation('navigation')->menuContextuel()->withTarget($intervenant->getId()) ?>

<ul>
    <li><a href="<?php echo $this->url('intervenant/default', 
        array('action' => 'saisirServiceReferentiel'), 
        array('query' => array('sourceCode' => $intervenant->getSourceCode()))) ?>">Service référentiel</a></li>
</ul>