<?php

/* @var $annee \Application\Entity\Db\Annee */
/* @var $intervenant \Application\Entity\Db\Intervenant */
/* @var $form Application\Form\Intervenant\HeuresCompForm */
/* @var $typeVolumeHoraire Application\Entity\Db\TypeVolumeHoraire */
/* @var $etatVolumeHoraire Application\Entity\Db\EtatVolumeHoraire */
/* @var $data array */

$resultat = $intervenant->getUniqueFormuleResultat($annee, $typeVolumeHoraire, $etatVolumeHoraire);
$totalService =
        $resultat->getHeuresServiceFi()
      + $resultat->getHeuresServiceFa()
      + $resultat->getHeuresServiceFc()
      + $resultat->getHeuresServiceReferentiel();


$depassementServiceDuSansHC = $intervenant->getFormuleIntervenant()->getDepassementServiceDuSansHC();

$this->headTitle()->append($intervenant->getNomUsuel())->append("Heures compl.");

?>


<style>
    th { background-color: #eee }
</style>
<h1 class="page-header"><?php echo $intervenant ?> <small><?php echo $intervenant->getType() ?></small></h1>
<?php echo $this->form()->openTag($form->prepare()); ?>
<div class="row">
    <div class="col-sm-4"><?php echo $this->formControlGroup($form->get('type-volume-horaire')); ?></div>
    <div class="col-sm-4"><?php echo $this->formControlGroup($form->get('etat-volume-horaire')); ?></div>
    <div class="col-sm-2"><label>&nbsp;</label><br /><?php echo $this->formRow($form->get('submit')); ?></div>
</div>
<?php echo $this->form()->closeTag(); ?>

<?php if ($intervenant->estPermanent()): ?>
<h2>Service Dû</h2>
<div class="row">
    <div class="col-sm-4">Composante d'affectation</div>
    <div class="col-sm-2 nombre"><?php echo $this->structure( $data['structure-affectation'] )->renderLink() ?></div>
</div>
<div class="row">
    <div class="col-sm-4">Service statutaire</div>
    <div class="col-sm-2 nombre"><?php echo \Common\Util::formattedHeures($data['heures-service-statutaire']) ?></div>
</div>
<div class="row">
    <div class="col-sm-4">- Modifications de service</div>
    <div class="col-sm-2 nombre"><?php echo \Common\Util::formattedHeures($data['heures-modification-service']) ?></div>
</div>
<div class="row">
    <div class="col-sm-4">= Service dû<?php echo $depassementServiceDuSansHC ? '*' : '' ?></div>
    <div class="col-sm-2 nombre"><span class="label label-info" style="font-size:12pt"><?php echo \Common\Util::formattedHeures($resultat->getServiceDu()) ?></span></div>
</div>
<?php if ($depassementServiceDuSansHC): ?>
<div class="alert alert-info alert-dismissible" role="alert" style="margin-top:1em">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  <strong>* </strong>
  Le statut de cet intervenant (<?php echo $intervenant->getStatut() ?>) ne lui permet pas de prétendre à des heures complémentaires.
  Par conséquent, en cas de dépassement de service statutaire, l'ensemble de son service assuré est considéré comme étant du service dû.
</div>
<?php endif; ?>

<?php endif; ?>


<h2>Heures effectives d'enseignement</h2>
<?php if (count($data['services']) > 0): ?>
<table class="table table-bordered table-condensed table-extra-condensed">
<tr>
    <th rowspan="4">Elément ou établissement</th>
    <th colspan="<?php echo count($data['th-taux']) ?>">Taux</th>
    <?php if ($data['has-ponderation-service-compl']): ?>
    <th rowspan="4">Majoration FC</th>
    <?php endif; ?>
    <th rowspan="4">Composante d'intervention</th>
    <?php if (count($data['types-intervention']) > 0): ?>
    <th style="white-space:nowrap" colspan="<?php echo count($data['types-intervention']); ?>">Types d'intervention</th>
    <?php endif; ?>
    <th colspan="<?php echo (count($data['th-service']) + count($data['th-compl']))?>">HETD</th>
</tr>
<tr>
    <?php foreach( $data['th-taux'] as $th ): ?>
    <th rowspan="3"><?php echo $this->typeHeures($th) ?></th>
    <?php endforeach; ?>
    <?php foreach( $data['types-intervention'] as $ti ): ?>
    <th><abbr title="<?php echo $ti->getLibelle() ?>"><?php echo $ti->getCode() ?></abbr></th>
    <?php endforeach; ?>
    <?php if (count($data['th-service']) > 0): ?>
    <th colspan="<?php echo count($data['th-service']) ?>">Dans le service</th>
    <?php endif; ?>
    <?php if (count($data['th-compl']) > 0): ?>
    <th colspan="<?php echo count($data['th-compl']) ?>">Au-delà du service</th>
    <?php endif; ?>
</tr>
<tr>
    <?php foreach( $data['types-intervention'] as $ti ): ?>
    <td class="nombre"><abbr title="Pondération des heures de services"><?php echo \Common\Util::formattedHeures($ti->getTauxHetdService()) ?></abbr></td>
    <?php endforeach; ?>
    <?php foreach( $data['th-service'] as $th ):?>
    <th rowspan="2"><?php echo $this->typeHeures($th) ?></th>
    <?php endforeach; ?>
    <?php foreach( $data['th-compl'] as $th ):?>
    <th rowspan="2"><?php echo $this->typeHeures($th) ?></th>
    <?php endforeach; ?>
</tr>
<tr>
    <?php foreach( $data['types-intervention'] as $ti ): ?>
    <td class="nombre"><abbr title="Pondération des heures au-delà du service"><?php echo \Common\Util::formattedHeures($ti->getTauxHetdComplementaire()) ?></abbr></td>
    <?php endforeach; ?>
</tr>
<?php foreach( $data['services'] as $ls ): ?>
    <tr>
        <td><?php
            if ($ls['element-etablissement'] instanceof \Application\Entity\Db\ElementPedagogique){
                echo $this->elementPedagogique( $ls['element-etablissement'] )->renderLink();
            }else{
                echo $this->etablissement( $ls['element-etablissement'] )->renderLink();
            }
        ?></td>
        <?php foreach( $data['th-taux'] as $th ): ?>
        <td class="nombre">
            <?php if (isset($ls['taux'][$th->getId()])): ?>
                <?php echo \Common\Util::formattedPourcentage($ls['taux'][$th->getId()]) ?>
            <?php endif; ?>
        </td>
        <?php endforeach; ?>
        
        
        <?php if ($data['has-ponderation-service-compl']): ?>
            <td class="nombre">
                <?php echo \Common\Util::formattedHeures($ls['ponderation-service-compl'])?>
            </td>
        <?php endif; ?>
        
        <td><?php echo $this->structure( $ls['structure'] )->renderLink() ?></td>
        <?php foreach( $data['types-intervention'] as $ti ): ?>
        <td class="nombre">
            <?php echo isset($ls['heures'][$ti->getId()]) ? \Common\Util::formattedHeures($ls['heures'][$ti->getId()]) : null ?>
        </td>
        <?php endforeach; ?>
        <?php foreach( $data['th-service'] as $th ):?>
        <td class="nombre">
            <?php if (isset($ls['hetd']['service'][$th->getId()])): ?>
                <?php echo \Common\Util::formattedHeures($ls['hetd']['service'][$th->getId()])?>
            <?php endif; ?>
        </td>
        <?php endforeach; ?>
        <?php foreach( $data['th-compl'] as $th ):?>
        <td class="nombre">
            <?php if (isset($ls['hetd']['compl'][$th->getId()])): ?>
                <?php echo \Common\Util::formattedHeures($ls['hetd']['compl'][$th->getId()])?>
            <?php endif; ?>
        </td>
        <?php endforeach; ?>
    </tr>
<?php endforeach; ?>
</table>
<?php else: ?>
Aucun service.
<?php endif; ?>

<?php if (! empty($data['referentiel'])): ?>
<h2>Heures de référentiel</h2>
<table class="table table-bordered table-condensed table-extra-condensed" style="width:auto">
    <tr>
        <th>Structure</th>
        <th>Heures réelles</th>
        <th><abbr title="Heures Equivalent TD dans le service">HETD service</abbr></th>
        <th><abbr title="Heures Equivalent TD au-delà du service">HETD compl.</abbr></th>
    </tr>
    <?php foreach( $data['referentiel'] as $ref ): ?>
    <tr>
        <td><?php echo $this->structure( $ref['structure'] )->renderLink() ?></td>
        <td class="nombre"><?php echo \Common\Util::formattedHeures($ref['heures']) ?></td>
        <td class="nombre"><?php echo \Common\Util::formattedHeures($ref['hetd']) ?></td>
        <td class="nombre"><?php echo \Common\Util::formattedHeures($ref['hetd-compl']) ?></td>
    </tr>
    <?php endforeach; ?>
</table>
<?php endif; ?>

<h2>Totaux HETD</h2>
<div class="row">
    <div class="col-sm-4">Service FI</div>
    <div class="col-sm-2 nombre"><?php echo \Common\Util::formattedHeures($resultat->getHeuresServiceFi()) ?></div>
</div>
<div class="row">
    <div class="col-sm-4">Service FA</div>
    <div class="col-sm-2 nombre"><?php echo \Common\Util::formattedHeures($resultat->getHeuresServiceFa()) ?></div>
</div>
<div class="row">
    <div class="col-sm-4">Service FC</div>
    <div class="col-sm-2 nombre"><?php echo \Common\Util::formattedHeures($resultat->getHeuresServiceFc()) ?></div>
</div>
<div class="row">
    <div class="col-sm-4">+ référentiel</div>
    <div class="col-sm-2 nombre"><?php echo \Common\Util::formattedHeures($resultat->getHeuresServiceReferentiel()) ?></div>
</div>
<div class="row">
    <div class="col-sm-4">= Service assuré</div>
    <div class="col-sm-2 nombre"><span class="label label-info" style="font-size:12pt"><?php echo \Common\Util::formattedHeures($totalService) ?></span></div>
</div>
<div class="row">&nbsp;</div>
<div class="row">
    <div class="col-sm-4"><abbr title="Heures complémentaires (formation initiale)">HC FI</abbr></div>
    <div class="col-sm-2 nombre"><?php echo \Common\Util::formattedHeures($resultat->getHeuresComplFi()) ?></div>
</div>
<div class="row">
    <div class="col-sm-4"><abbr title="Heures complémentaires (formation en apprentissage)">HC FA</abbr></div>
    <div class="col-sm-2 nombre"><?php echo \Common\Util::formattedHeures($resultat->getHeuresComplFa()) ?></div>
</div>
<div class="row">
    <div class="col-sm-4"><abbr title="Heures complémentaires (formation continue)">HC FC</abbr></div>
    <div class="col-sm-2 nombre"><?php echo \Common\Util::formattedHeures($resultat->getHeuresComplFc()) ?></div>
</div>
<div class="row">
    <div class="col-sm-4"><abbr title="Rémunération FC au titre de l'article D714-60 du code de l’Éducation">Rémunération FC D714-60</abbr></div>
    <div class="col-sm-2 nombre"><?php echo \Common\Util::formattedHeures($resultat->getHeuresComplFcMajorees()) ?></div>
</div>
<div class="row">
    <div class="col-sm-4"><abbr title="Heures complémentaires (référentiel)">HC Référentiel</abbr></div>
    <div class="col-sm-2 nombre"><?php echo \Common\Util::formattedHeures($resultat->getHeuresComplReferentiel()) ?></div>
</div>
<div class="row">
    <div class="col-sm-4">= Heures complémentaires</div>
    <div class="col-sm-2 nombre"><span class="label label-info" style="font-size:12pt"><?php echo \Common\Util::formattedHeures($resultat->getSolde()) ?></span></div>
</div>
<br />
<div class="row">
    <div class="col-sm-4">Solde</div>
    <div class="col-sm-2 nombre"><span class="label label-<?php $hs = $resultat->getSolde(); if ($hs== 0) echo 'info'; elseif( $hs < 0) echo 'danger'; else echo 'warning'; ?>" style="font-size:12pt"><?php echo \Common\Util::formattedHeures($resultat->getSolde()) ?></span></div>
</div>