<?php
/**
 * Generated by UnicaenCode
 * Commande : php public/index.php UnicaenCode  module='Indicateur'
 */
return [
    'Indicateur\Controller\IndicateurController'              => __DIR__ . '/src/Controller/IndicateurController.php',
    'Indicateur\Controller\IndicateurControllerFactory'       => __DIR__ . '/src/Controller/IndicateurControllerFactory.php',
    'Indicateur\Entity\Db\IndicModifDossier'                  => __DIR__ . '/src/Entity/Db/IndicModifDossier.php',
    'Indicateur\Entity\Db\Indicateur'                         => __DIR__ . '/src/Entity/Db/Indicateur.php',
    'Indicateur\Entity\Db\IndicateurDepassementCharges'       => __DIR__ . '/src/Entity/Db/IndicateurDepassementCharges.php',
    'Indicateur\Entity\Db\NotificationIndicateur'             => __DIR__ . '/src/Entity/Db/NotificationIndicateur.php',
    'Indicateur\Entity\Db\TypeIndicateur'                     => __DIR__ . '/src/Entity/Db/TypeIndicateur.php',
    'Indicateur\Module'                                       => __DIR__ . '/Module.php',
    'Indicateur\Processus\IndicateurProcessus'                => __DIR__ . '/src/Processus/IndicateurProcessus.php',
    'Indicateur\Processus\IndicateurProcessusFactory'         => __DIR__ . '/src/Processus/IndicateurProcessusFactory.php',
    'Indicateur\Service\IndicateurService'                    => __DIR__ . '/src/Service/IndicateurService.php',
    'Indicateur\Service\IndicateurServiceFactory'             => __DIR__ . '/src/Service/IndicateurServiceFactory.php',
    'Indicateur\Service\NotificationIndicateurService'        => __DIR__ . '/src/Service/NotificationIndicateurService.php',
    'Indicateur\Service\NotificationIndicateurServiceFactory' => __DIR__ . '/src/Service/NotificationIndicateurServiceFactory.php',
];