<?php
/**
 * Generated by UnicaenCode
 * Commande : php public/index.php UnicaenCode  module='Indicateur'
 */
return [
    'indicateur/indicateur/mail/intervenants'       => __DIR__ . '/view/indicateur/indicateur/mail/intervenants.phtml',
    'indicateur/indicateur/mail/notification'       => __DIR__ . '/view/indicateur/indicateur/mail/notification.phtml',
    'indicateur/indicateur/abonnements'             => __DIR__ . '/view/indicateur/indicateur/abonnements.phtml',
    'indicateur/indicateur/envoi-mail-intervenants' => __DIR__ . '/view/indicateur/indicateur/envoi-mail-intervenants.phtml',
    'indicateur/indicateur/result'                  => __DIR__ . '/view/indicateur/indicateur/result.phtml',
    'indicateur/indicateur/depassement-charges'     => __DIR__ . '/view/indicateur/indicateur/depassement-charges.phtml',
    'indicateur/indicateur/index'                   => __DIR__ . '/view/indicateur/indicateur/index.phtml',
];