<?php

/**
 * @var $this          \Application\View\Renderer\PhpRenderer
 * @var $role          \Utilisateur\Acl\Role
 * @var $typeAgrement  \Agrement\Entity\Db\TypeAgrement
 * @var $intervenant   \Intervenant\Entity\Db\Intervenant
 * @var $data          array
 * @var $needStructure boolean
 * @var $hasActions    boolean
 */

$title = "Agrément par " . $typeAgrement->toString(true);
$this->intervenant($intervenant)->renderTitle($title);

if (!empty($data)): ?>
    <table class="table table-bordered table-hover">
        <thead>
        <tr>
            <?php if ($needStructure): ?>
                <th style="width: 100px">Composante</th><?php endif; ?>
            <th>Agrément</th>
            <?php if ($hasActions): ?>
                <th style="width:1px">Action</th><?php endif; ?>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($data as $d): extract($d); ?>
            <tr>
                <?php if ($needStructure): ?>
                    <td class="structure"><?= $ta->getStructure() ?></td>
                <?php endif; ?>
                <td class="agrement">
                    <?php
                    if ($agrement = $ta->getAgrement()) {
                        echo $this->agrement($agrement, $ta)->short()->box();
                    } else {
                        echo 'Aucun';
                    }
                    ?>
                </td>
                <?php if ($hasActions): ?>
                    <td>
                        <?php if (!empty($ta->getAnneeAgrement()) && $ta->getAnnee()->getId() != $ta->getAnneeAgrement()->getId()): ?>
                            L'agrément ne peut être retiré que l'année de sa décision.
                        <?php else: ?>
                            <?php if ($actionUrl): ?>
                                <a class="btn btn-primary pop-ajax " data-submit-reload="true" data-min-width="13em"
                                   data-placement="left"
                                   href="<?= $actionUrl ?>"><?= $actionLabel ?></a>
                            <?php endif; ?>
                        <?php endif; ?>

                    </td>
                <?php endif; ?>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
<?php endif; ?>
<?php if (empty($data)): ?>
    <div class="alert alert-info">Aucun agrément n'est nécessaire</div>
<?php endif; ?>


<hr/>
<?= $this->vue('workflow/nav', ['intervenant' => $intervenant->getId(), 'etape' => $typeAgrement->getCode()]); ?>
