<?php

/**
 * @var $this       \Application\View\Renderer\PhpRenderer
 * @var $structure  \Lieu\Entity\Db\Structure
 * @var $niveau     \OffreFormation\Entity\NiveauEtape
 * @var $etape      \OffreFormation\Entity\Db\Etape
 * @var $niveaux    \OffreFormation\Entity\NiveauEtape[]
 * @var $etapes     \OffreFormation\Entity\Db\Etape[]
 * @var $elements   \OffreFormation\Entity\Db\ElementPedagogique[]
 */

use Application\Provider\Privileges;


/**
 * @param \Lieu\Entity\Db\Structure          $structure
 * @param \OffreFormation\Entity\NiveauEtape $niveau
 * @param \OffreFormation\Entity\Db\Etape    $etape
 */
function makeQuery($structure = null, $niveau = null, $etape = null)
{
    $params = [];
    //@formatter:off
    if ($structure) $params['structure'] = $structure->getId();
    if ($niveau) $params['niveau'] = ($niveau->getPertinence()) ? $niveau->getId() : $niveau->getLib();
    if ($etape) $params['etape'] = $etape->getId();
    //@formatter:on

    return ['query' => $params];
}


/* Liste des niveaux */
$niveauxItems = [
    null => [
        'label'  => 'Tous niveaux confondus',
        'niveau' => null,
        'url'    => $this->url('of', [], makeQuery($structure)),
    ],
];

foreach ($niveaux as $code => $niv) {
    $niveauxItems[$code] = [
        'label'  => ($niv->getPertinence()) ? (string)$niv : $code,
        'niveau' => $niv,
        'url'    => $this->url('of', [], makeQuery($structure, $niv)),
    ];
}


/* Liste des étapes */
$etapesItems = [
    null => [
        'label'     => 'Toutes formations confondues',
        'etape'     => null,
        'orpheline' => false,
        'url'       => $this->url('of', [], makeQuery($structure, $niveau)),
    ],
];

foreach ($etapes as $etp) {
    $etapesItems[$etp->getId()] = [
        'label'     => sprintf("%s (%s EP)", $etp, count($etp->getCheminPedagogique())),
        'etape'     => $etp,
        'orpheline' => $etp->getCheminPedagogique()->count() === 0,
        'url'       => $this->url('of', [], makeQuery($structure, $niveau, $etp)),
    ];
}


/* Liste des éléments */

if ($structure) {
    $this->headTitle()->append((string)$structure);
}
$this->headTitle()->append("Offre de formation");

$canExport      = $this->isAllowed(Privileges::getResourceId(Privileges::ODF_EXPORT_CSV)) && count($elements);
$canViewEtape   = $this->isAllowed(Privileges::getResourceId(Privileges::ODF_ETAPE_VISUALISATION));
$canEditElement = $this->isAllowed($structure, Privileges::ODF_ELEMENT_EDITION);
$canEditEtape   = $this->isAllowed($structure, Privileges::ODF_ETAPE_EDITION);
$canSyncElement = $this->isAllowed(Privileges::getResourceId(Privileges::ODF_ELEMENT_SYNCHRONISATION));
?>
<style>
    ul.navigation-etape {
        padding: 0 0 3px 5px;
    }

    ul.navigation-etape li {
        list-style: none;
        display: inline;
    }

    /*th.action, td.action { min-width: 70px; }*/
    div.card-body label,
    div.card-body input {
        display: inline;
    }

    div.card-body input.form-control {
        width: 75%
    }

    .bootstrap-select.struct {
        max-width: 200px;
    }
</style>

<?php ?>
<h1 class="page-header">Offre de formation <?= $structure ? '<small>' . $structure . '</small>' : null ?></h1>

<div class="row">

    <div class="col-md-3">

        <!---------------- Champ de sélection d'une structure --------------->
        <div class="card bg-default">
            <div class="card-header">Structure</div>
            <div class="card-body">
                <?php
                $selectStructure = new \Lieu\Form\Element\Structure('structure');
                $selectStructure->init();
                $selectStructure->setEnseignement(true);
                $selectStructure
                    ->setValue($structure ? $structure->getId() : null)
                    ->setContextFilter(false)
                    ->setAttributes(['class' => 'struct selectpicker']);
                echo $this->formSelect($selectStructure);
                ?>
                <script>
                    $("body").on("change", "select.struct", function (event) {
                        $("*").css('cursor', 'wait');
                        var id = $(this).val();
                        var url = '<?= $this->url('of', [], ['query' => ['structure' => '__structure__']]) ?>';
                        $(location).attr('href', url.replace('__structure__', id));
                    });
                </script>
            </div>
        </div>

        <!---------------- Filtre niveau --------------->
        <div class="card bg-default">
            <div class="card-header">Niveau</div>
            <?php if (count($niveaux)): ?>
                <ul class="list-group list-group-flush">
                    <?php foreach ($niveauxItems as $ni): ?>
                        <?php if (($niveau === $ni['niveau']) || ($niveau && $ni['niveau'] && $niveau->getId() === $ni['niveau']->getId())): ?>
                            <li class="list-group-item active"><strong><?= $ni['label'] ?></strong></li>
                        <?php else: ?>
                            <li class="list-group-item">
                                <a class="niveau"
                                   title="Cliquez pour afficher les formations et les enseignements de ce niveau"
                                   href="<?= $ni['url'] ?>"><?= $ni['label'] ?></a>
                            </li>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </ul>
            <?php else: ?>
                <div class="card-body">
                    Cliquez sur le niveau dont vous voulez voir les formations et enseignements...
                </div>
            <?php endif; ?>

            <script>
                $("body").on("click", "a.niveau", function (event) {
                    $("*").css('cursor', 'wait');
                });
            </script>
        </div>

        <!---------------- Filtre étape --------------->
        <div class="card bg-default">
            <div class="card-header">
                Formation
                <?php if ($this->isAllowed($structure, Privileges::ODF_ETAPE_EDITION)) echo $this->etape($etape)->renderAjouterLink('<i class="fas fa-plus"></i>', ['class' => 'btn-sm', 'style' => 'float:right'], $structure) ?>
            </div>
            <?php if (count($etapes)): ?>
                <ul class="list-group list-group-flush">
                    <?php foreach ($etapesItems as $ei): ?>
                        <?php if ($etape === $ei['etape']): ?>
                            <li class="list-group-item active">
                            <strong><?= $ei['label'] ?></strong>
                        <?php else: ?>
                            <li class="list-group-item">
                            <a class="etape<?php if ($ei['orpheline']) echo ' text-danger'; ?>"
                               title="Cliquez pour afficher les enseignements de cette formation"
                               href="<?= $ei['url'] ?>"><?= $ei['label'] ?></a>
                        <?php endif; ?>
                        <?php
                        if ($canViewEtape && $ei['etape']) {
                            echo $this->etape($ei['etape'])->renderLink('<span class="btn btn-secondary btn-sm" style="float:right"><i class="fas fa-magnifying-glass"></i></span>');
                        }
                        ?>
                        <div style="clear: both"></div>
                        </li>
                    <?php endforeach; ?>
                </ul>
            <?php else: ?>
                <div class="card-body">
                    Cliquez sur la formation dont vous voulez voir les enseignements...
                </div>
            <?php endif; ?>
            <script>
                $("body").on("click", "a.etape", function (event) {
                    $("*").css('cursor', 'wait');
                });
            </script>
        </div>

    </div>

    <div class="col-md-9" role="main">

        <?php if (null === $elements): ?>

            <p><?= $this->messenger()->setMessage("Sélectionnez une structure...", 'info') ?></p>

        <?php else: ?>

            <!---------------- Champ de recherche d'un élément pédagogique --------------->
            <?php if ($canEditEtape && $compl = $etape && $etape->estHistorise()):
                echo "<br />" . $this->tag('a', ['class' => 'btn btn-primary', 'href' => $this->url('of/etape/restaurer', ['etape' => $etape->getId()])])->html('Restaurer la formation');
            endif; ?>

            <div class="card bg-default">
                <div class="card-header" style="margin-bottom:1em">
                    <?php $compl = $etape ? "de la formation <strong>$etape</strong>" : "toutes formations confondues"; ?>
                    Enseignements <?= $compl ?>
                    <!--------------- Bouton d'ajout d'élément pédagogique --------------->
                    <span class="float-end">
                    <?php
                    if ($canSyncElement && $structure && $serviceSchema->isImportedEntity($structure)) {
                        $attrs = [
                            'href'       => $this->url('of/element/synchronisation-par-code', [], ['query' => ['structure' => $structure->getId()]]),
                            'class'      => ['element-pedagogique-synchronisation', 'ajax-modal', 'iconify', 'btn', 'btn-secondary', 'btn-sm'],
                            'data-event' => 'element-pedagogique-synchronisation',
                            'title'      => 'Importer ou synchroniser un enseignement',
                        ];
                        echo $this->tag('a', $attrs)->html('<i class="fas fa-arrows-rotate"></i> Import élément');
                    }
                    if ($canEditElement) {
                        $attrs = [
                            'href'       => $this->url('of/element/ajouter'),
                            'class'      => ['element-pedagogique-ajouter-link', 'ajax-modal', 'iconify', 'btn', 'btn-secondary', 'btn-sm'],
                            'data-event' => 'element-pedagogique-ajouter',
                            'title'      => 'Ajouter un enseignement',
                        ];
                        echo $this->tag('a', $attrs)->html('<i class="fas fa-plus"></i> Nouvel élément pédagogique');
                    }
                    if ($canExport) {
                        $params = [
                            'structure' => $structure ? $structure->getId() : null,
                            'niveau'    => $niveau ? $niveau->getId() : null,
                            'etape'     => $etape ? $etape->getId() : null,
                        ];
                        $urlExportOf = $this->url('of/export', [], ['query' => $params]);

                        ?>
                        <a class="btn btn-secondary btn-sm" href="<?= $urlExportOf ?>">
                            <i class="fas fa-upload"></i> Télécharger (CSV)
                        </a>
                        <?php
                    }


                    ?>
                    </span>
                </div>

                <!---------------- Tableau des éléments pédagogiques --------------->
                <table class="table table-bordered table-sm table-hover table-sort">
                    <thead>
                    <tr>
                        <th colspan="3">Formations</th>
                        <th colspan="5">Eléments pédagogiquess</th>
                    </tr>
                    <tr>
                        <th>Niveau</th>
                        <th>Code Etape</th>
                        <th>Libellé</th>
                        <th>Code</th>
                        <th>Libellé</th>
                        <th>Période</th>
                        <th title="Formation ouverte à distance">FOAD</th>
                        <th title="Régime d'inscription">Rég. d'insc.</th>
                    </tr>
                    </thead>
                    <tbody>

                    <?php foreach ($elements as $ep): /* @var $ep \OffreFormation\Entity\Db\ElementPedagogique */ ?>
                        <tr id="<?= $ep->getId() ?>">
                            <td><?= $ep->getEtape()->getNiveauToString() ?></td>
                            <td class="etape"><?= $ep->getEtape()->getCode() ?></td>
                            <td class="etape"><?= $this->etape($ep->getEtape())->renderLink() ?></td>
                            <td class="element"><?= $ep->getCode() ?></td>
                            <td class="element"><?= $this->elementPedagogique($ep)->renderLink($ep->getLibelle()) ?></td>
                            <td class="periode"><?= $ep->getPeriode() ?: "" ?></td>
                            <td><?= (bool)$ep->getTauxFoad() ? "Oui" : "Non" ?></td>
                            <td><?= $ep->getRegimesInscription(true) ?></td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>

            </div>
        <?php endif; ?>

    </div>

</div>
