<?php
/* @var $this Application\View\Renderer\PhpRenderer */

/* @var $context ContextService */

use Application\Provider\Privilege\Privileges;
use Application\Service\ContextService;

$this->headTitle("Accueil");
echo $this->messenger()->addMessagesFromFlashMessenger();

$canAbonne = $this->isAllowed(Privileges::getResourceId(Privileges::INDICATEUR_ABONNEMENT));

$intervenant     = $context->getIntervenant();
$onlyIntervenant = $intervenant && (null == $context->getSelectedIdentityRole()->getDbRole());

?>
    <div class="jumbotron">
        <h1><span class="appname"><span class="c1">O</span><span class="c2">S</span><span class="c3">E</span></span>
            <small>Organisation des Services d'Enseignement</small>
        </h1>
        <p class="lead">Bienvenue dans l'application de saisie des enseignements de l'université de Caen Normandie.</p>
        <p class="lead">Année <?= $annee ?>.</p>

        <?php
        if ($context->getUtilisateur()) {

            if ($onlyIntervenant) {
                if ($intervenant->getStatut()->getNonAutorise()) {

                    ?><p>
                    <div class='alert alert-danger'> Votre statut ne vous permet pas de vous connecter à OSE.</div></p><?php
                } else {
                    echo $this->tag('div')->html($this->feuillederoute($intervenant)->renderCurrentBtn());

                    /* Guide à télécharger... */
                    $guideType = $intervenant->getStatut()->estVacataire() ? 'guide_ose_vacataire' : 'guide_ose_permanent';
                    $guideUrl  = $this->basePath() . '/doc/intervenant/' . $guideType . '.pdf';
                    echo $this->tag('div', ['class' => 'alert alert-info', 'style' => 'margin-top:1em', 'role' => 'alert'])->html(
                        'Un guide d\'utilisation de OSE vous est proposé. Vous pouvez le télécharger en suivant le lien ci-contre : '
                        . $this->tag('a', ['href' => $guideUrl])->html(
                            $this->tag('span', ['class' => 'glyphicon glyphicon-book'])->openClose() . ' Guide d\'utilisation'
                        )
                    );
                }
            } elseif ($context->getStructure()) {

                $url   = $this->url('service/resume');
                $label = $this->translate("Tableau synthétique des enseignements concernant ma composante...");
                ?><p><a class="btn btn-primary btn-large" href="<?= $url ?>"><?= $label ?></a></p><?php
            } elseif ($context->getUtilisateur()->getAffectation()->count() == 0) {
                ?>
                <div class="alert alert-danger" role="alert">
                    Vous n'êtes pas autorisé(e) à vous connecter à OSE avec ce compte. Nous vous prions de vous rapprocher de
                    votre composante pour en obtenir un valide.
                </div>
                <?php
            }
        } else {

            ?><a class="btn btn-success btn-large"
                 href="<?= $this->url('zfcuser/login') ?>"><?= $this->translate('Connectez-vous...') ?></a><?php
        }
        ?>
    </div>

    <!-------------------------- Indicateurs (AJAX) -------------------------->
<?php if (isset($this->abonnementsUrl)): ?>
    <script>
        $(function ()
        {
            var url = '<?= $this->abonnementsUrl ?>';
            $(".abonnements").hide();
            $("#abonnements").load(url, [], function ()
            {
                $(".abonnements").fadeIn();
                $(this).hide().fadeIn();
            });
        });
    </script>
    <h2 class="abonnements">Vos indicateurs <?php if ($canAbonne): ?><a class="btn btn-default btn-sm pull-right"
                                                                        href="<?= $this->url('indicateur') ?>">Gérer
                vos abonnements à des
                indicateurs</a><?php endif; ?></h2>
    <div id="abonnements">
        <div class="loading"></div>
    </div>
<?php endif ?>

    <!----------------------------- Feuille de route --------------------------->
<?php
if ($onlyIntervenant) {
    echo $this->feuillederoute($intervenant);
}
