<?php echo $this->messenger(true) ?>
<div class="jumbotron">
    <h1>OSE <small>Organisation des Services d'Enseignement</small></h1>
    <p class="lead">Bienvenue dans l'application de saisie des enseignements de l'université de Caen.</p>
    <p>Année <?php echo $annee ?>.</p>
    <p>
        <?php if (($identity = $this->identity())): ?>
        
            <?php 
            $message = null;
            if ($role instanceof \Application\Acl\IntervenantRole) {
                $intervenant = $role->getIntervenant();
                if ($intervenant instanceof \Application\Entity\Db\IntervenantExterieur) {
                    $message = null;
                    $url     = $this->url('intervenant/saisir-dossier', array('id' => $intervenant->getSourceCode()));
                    $label   = $this->translate("J'accède à mes données personnelles...");
                }
                elseif ($intervenant instanceof \Application\Entity\Db\IntervenantPermanent) {
                    $message = "L'application sera ouverte du ... au ...";
                    $url     = $this->url('intervenant/services', array('id' => $intervenant->getSourceCode()));
                    $label   = $this->translate("Je saisis mes enseignements...");
                }
            }
            elseif ($role instanceof \Application\Acl\ComposanteDbRole) {
                $url   = $this->url('service/resume');
                $label = $this->translate("Tableau synthétique des enseignements concernant ma composante...");
            }
            else {
                $url   = $this->url('home');
                $label = $this->translate("Accueil...");
            }
            ?>
            <?php if ($message): ?>
            <p><?php echo $message ?></p>
            <?php endif; ?>
            <a class="btn btn-primary btn-large" href="<?php echo $url ?>"><?php echo $label ?></a>

        <?php else: ?>

            <a class="btn btn-success btn-large" href="<?php echo $this->url('zfcuser/login') ?>"><?php echo $this->translate('Connectez-vous...') ?></a>

        <?php endif; ?>
    </p>
</div>