<?php
/**
 * @var \Utilisateur\Acl\Role|null $role
 * @var array                      $configPages
 */

if (!$role) {
    echo 'Vous devez être connecté pour accéder au plan de navigation';
    return;
}

$intervenantId = 999999999999999999;

?>
    <h1>Plan de l'application</h1>
    <script>

        var jsd = {
            liens: {},

            init: function () {
                $('a.osepage').each(function () {
                    var a = $(this);

                    //a.attr('target', '_blank');

                    if (a.attr("href").includes('<?= $intervenantId ?>')) {
                        jsd.liens[a.attr("href")] = a;
                    }
                    a.attr('href', '');
                });
            },

            exec: function (el) {
                for (url in jsd.liens) {
                    jsd.liens[url].attr('href', url.replace('<?= $intervenantId ?>', el.value));
                }
            }
        }

        $(function () {
            jsd.init();
        });

    </script>

<?php


$pi = $configPages['intervenant']['pages'];
uasort($pi, function ($a, $b) {
    return $a['order'] - $b['order'];
});

$pagesIntervenant = [
    $pi['rechercher']['label'] => $this->url($pi['rechercher']['route']),
];
unset($pi['rechercher']);
unset($pi['voir']);

$iparams = ['intervenant' => $intervenantId];

$pagesIntervenant['Fiche individuelle'] = [
    'Fiche'           => $this->url('intervenant/voir', $iparams, ['query' => ['tab' => 'fiche']]),
    'Édition'         => $this->url('intervenant/voir', $iparams, ['query' => ['tab' => 'edition']]),
    'Synchronisation' => $this->url('intervenant/voir', $iparams, ['query' => ['tab' => 'synchronisation']]),
    'Suppression'     => $this->url('intervenant/voir', $iparams, ['query' => ['tab' => 'suppression']]),
    'Dérogations'     => $this->url('intervenant/voir', $iparams, ['query' => ['tab' => 'derogations']]),
    'Notes'           => $this->url('intervenant/voir', $iparams, ['query' => ['tab' => 'notes']]),
];

foreach ($pi as $p) {
    $pagesIntervenant[$p['label']] = $this->url($p['route'], $iparams);
}

$pages = [
    'Intervenant'        => $pagesIntervenant,
    'Offre de formation' => [
        $configPages['of']['label'] => $this->url($configPages['of']['route']),
    ],
    'Services'           => [
        $configPages['service']['label'] => $this->url($configPages['service']['route']),
    ],
];

foreach ($configPages['chargens']['pages'] as $p) {
    $pages['Charges'][$p['label']] = $this->url($p['route']);
}

uasort($configPages['gestion']['pages'], function ($a, $b) {
    return $a['order'] - $b['order'];
});
foreach ($configPages['gestion']['pages'] as $p) {
    $pages['Gestion'][$p['label']] = [];
    foreach ($p['pages'] as $pp) {
        $pages['Gestion'][$p['label']][$pp['label']] = $this->url($pp['route']);
    }
}

uasort($configPages['administration']['pages'], function ($a, $b) {
    return $a['order'] - $b['order'];
});
foreach ($configPages['administration']['pages'] as $p) {
    $pages['Administration'][$p['label']] = [];
    foreach ($p['pages'] as $pp) {

        $pages['Administration'][$p['label']][$pp['label']] = $this->url($pp['route']);
    }
}

foreach ($pages as $rubrique => $rpages) {
    echo "<h2>$rubrique</h2>\n";
    if ('Intervenant' == $rubrique){
        ?>
        <div class="mb-2">
            <label class="form-label">ID d'intervenant :</label>
            <input class="form-inline" name="intervenant" type="text" value="" onchange="jsd.exec(this)"/>
        </div>
        <?php
    }
    echo "<ul>\n";
    foreach ($rpages as $label => $url) {
        if (is_array($url)) {
            echo "<li>$label\n";
            echo "<ul>\n";
            foreach ($url as $slabel => $surl) {
                echo "<li><a class=\"osepage\" href=\"$surl\">$slabel</a></li>\n";
            }
            echo "</ul>";
            echo "</li>\n";
        } else {
            echo "<li><a class=\"osepage\" href=\"$url\">$label</a></li>\n";
        }
    }
    echo "</ul>";
}