<?php

$this->headTitle()->append($title = 'An error occurred');
$details = isset($this->display_exceptions) && $this->display_exceptions && isset($this->exception) && ($this->exception instanceof Exception);

?>
<div class="alert alert-danger exception" role="alert">
    <span class="glyphicon glyphicon-alert"></span>
    <h1><?php echo $this->translate($title) ?> :</h1>
    <?php echo $this->exception->getMessage() ?>
    <?php if ($details): ?>
        <hr/>
        <h2><?php echo $this->translate('Additional information') ?>:</h2>
        <h3><?php echo get_class($this->exception); ?></h3>
        <dl>
            <dt><?php echo $this->translate('File') ?>:</dt>
            <dd>
                <pre class="prettyprint linenums"><?php echo $this->exception->getFile() ?>
                    :<?php echo $this->exception->getLine() ?></pre>
            </dd>
            <dt><?php echo $this->translate('Stack trace') ?>:</dt>
            <dd>
                <pre
                    class="prettyprint linenums"><?php echo \UnicaenApp\Util::formatTraceString($this->exception->getTraceAsString()) ?></pre>
            </dd>
        </dl>
        <?php
        $e = $this->exception->getPrevious();
        if ($e) :
            ?>
            <hr/>
            <h2><?php echo $this->translate('Previous exceptions') ?>:</h2>
            <ul class="unstyled">
                <?php while ($e) : $id = uniqid('bloc_code_'); ?>
                    <a role="button" data-toggle="collapse" href="#<?php echo $id ?>" aria-expanded="false"
                       aria-controls="collapseExample">
                        <?php echo get_class($e) ?>
                    </a><br/>
                    <div class="collapse" id="<?php echo $id ?>">

                        <dl>
                            <dt><?php echo $this->translate('File') ?>:</dt>
                            <dd>
                                <pre class="prettyprint linenums"><?php echo $e->getFile() ?>
                                    :<?php echo $e->getLine() ?></pre>
                            </dd>
                            <dt><?php echo $this->translate('Message') ?>:</dt>
                            <dd>
                                <pre class="prettyprint linenums"><?php echo $e->getMessage() ?></pre>
                            </dd>
                            <dt><?php echo $this->translate('Stack trace') ?>:</dt>
                            <dd>
                                <pre
                                    class="prettyprint linenums"><?php echo \UnicaenApp\Util::formatTraceString($e->getTraceAsString()) ?></pre>
                            </dd>
                        </dl>
                    </div>
                    <?php
                    $e = $e->getPrevious();
                endwhile;
                ?>
            </ul>
        <?php endif; ?>
    <?php endif ?>
</div>
