<?php

/**
 * @var $this \Application\View\Renderer\PhpRenderer
 */

$nav = $this->navigation('navigation');

/** @var \Laminas\Navigation\Page\Mvc $page */
$page = $nav->findActive($nav->getContainer())['page'];

echo $this->tag('h1', ['class' => 'page-header'])->html($page->getLabel());

echo $page->getTitle();

echo $this->navigation('navigation')->menuContextuel()->setPartial('unicaen-app/menu-dl.phtml');

echo $this->tag('a', [
    'href'  => $this->url('administration'),
    'class' => 'btn btn-secondary',
])->html('<i class="fas fa-rotate-left" aria-hidden="true"></i> Retour au menu d\'administration');