<?php

/**
 * @var $this     \Application\View\Renderer\PhpRenderer
 * @var $form     \Application\Form\Supprimer
 * @var $wfEtapeDep \Workflow\Entity\Db\WfEtapeDep
 */

echo '<h1 class="page-header">Suppression d\'une dépendance du Workflow</h1>';

echo $this->messenger()->addCurrentMessagesFromFlashMessenger();

if ($form){
    echo '<p class="lead text-danger"><strong>Attention!</strong> Confirmez-vous la suppression de cette dépendance ?</p>';

    echo $this->formSupprimer($form);
}