<?php echo $this->messenger()->addCurrentMessagesFromFlashMessenger(); ?>

<div class="card bg-default">
    <div class="card-header">Rechercher agent le SI RH</div>
    <div class="card-body">
        <form action="" method="post">
            <div class="form-group">
                <label for="">Nom</label>
                <input class="form-control" type="text" name="nomUsuel" value=""/>
            </div>
            <div class="form-group">
                <label for="">Prénom</label>
                <input class="form-control" type="text" name="prenom" value=""/>
            </div>
            <div class="form-group">
                <label for="">Numéro INSEE</label>
                <input class="form-control" type="text" name="insee" value=""/>
            </div>
            <button type="submit" class="btn btn-default">Rechercher</button>
        </form>
    </div>
</div>

<div>
    <table class="table table-bordered">
        <thead>
        <th>Nom</th>
        <th>Prenom</th>
        <th>Matricule</th>
        <th>Date de naissance</th>
        <th>Présent dans OSE</th>
        <th>Action</th>
        </thead>
        <tbody>
        <?php
        /**
         * @var \UnicaenSiham\Entity\Agent $agent
         */
        ?>
        <?php if (!empty($listIntervenantRh)): ?>
            <?php foreach ($listIntervenantRh as $intervenantRh): ?>
                <tr>
                    <td><?= $intervenantRh->getNomUsuel() ?></td>
                    <td><?= $intervenantRh->getPrenom() ?></td>
                    <td><?= $intervenantRh->getCodeRh() ?></td>
                    <td><?= $intervenantRh->getDateNaissance()->format('d/m/Y') ?></td>
                    <td><a href="<?= $this->url('intervenant/voir', ['intervenant' => 'code:' . $intervenantRh->getIntervenant()->getCode()]); ?>"><?php echo (!empty($intervenantRh->getIntervenant())) ? 'OUI' : 'NON'; ?></a></td>
                    <td><a href="" class="button">VOIR</a></td>
                </tr>
            <?php endforeach; ?>
        <?php else: ?>
            <tr>
                <td colspan="4" style="text-align:center;">Aucun intervenant trouvé</td>
            </tr>
        <?php endif; ?>
        </tbody>
    </table>
</div>
