<?php

/**
 * @var $this              \Application\View\Renderer\PhpRenderer
 * @var $intervenantParams ExportRH\Entity\IntervenantRHExportParams
 * @var $champs            array
 */

$title = "Administration de l'export vers le SI RH";

$this->headTitle()->append($title);

?>
    <h1 class="page-header"><?= $title ?></h1>
<?php

$canEdit = true;

echo $this->navigation('navigation')->menuContextuel()->setPartial('unicaen-app/menu-dl.phtml');

?>
    <h2>Paramètres généraux</h2>

    <h2>Données exportables</h2>
    <div style="column-count: 3;column-gap: 3em;">
        <?php foreach ($champs as $rubrique => $chs) : ?>
            <div class="panel panel-default" style="break-inside: avoid">

                <div class="panel-heading"><?= $rubrique ?></div>
                <div class="panel-body">
                    <?php foreach ($chs as $champ => $libelle) : ?>
                        <div class="row" style="border-bottom: 1px #eee solid">
                            <div class="col-md-10"><?= $libelle ?></div>
                            <div class="col-md-2">
                                <?php if (true): ?>
                                    <?php if ($canEdit): ?><a href="javascript:void(0)" data-action="desactiver"
                                        title="Synchronisation activée. Cliquez pour la désactiver."><?php endif; ?>
                                    <i class="fa-solid fa-check text-succes"></i>
                                    <?php if ($canEdit): ?></a><?php endif; ?>

                                <?php else: ?>

                                    <?php if ($canEdit): ?><a href="javascript:void(0)" data-action="activer"
                                        title="Synchtronisation désactivée. Cliquez pour l'activer."><?php endif; ?>
                                    <i class="fa-solid fa-xmark text-danger refuse"></i>
                                    <?php if ($canEdit): ?></a><?php endif; ?>
                                <?php endif; ?>
                            </div>
                        </div>
                    <?php endforeach; ?>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
<?php