<?php echo $this->messenger()->addCurrentMessagesFromFlashMessenger(); ?>

<?php
/**
 * @var \UnicaenSiham\Entity\Agent $agent
 */
?>

<?php if (!empty($agent)): ?>
    <div class="card bg-default">
        <div class="card-header">Données personnelles
            de <?= $agent->getPrenom() . ' ' . $agent->getNomUsuel() ?></div>
        <div class="card-body">
            <div class="row">
                <div class="col-md-6">
                    <strong>Matricule : </strong><?= $agent->getMatricule() ?><br/>
                    <strong>Nom patronymique :</strong> <?= $agent->getNomPatronymique() ?><br/>
                    <strong>Nom Usuel :</strong> <?= $agent->getNomUsuel() ?><br/>
                    <strong>Prénom :</strong> <?= $agent->getPrenom() ?><br/>

                </div>
                <div class="col-md-6">
                    <strong>Date de naissance :</strong> <?= $agent->getDateNaissance() ?><br/>
                    <strong>Pays de naissance :</strong> <?= $agent->getPaysNaissance() ?><br/>
                    <strong>Ville de naissance :</strong> <?= $agent->getVilleNaissance() ?><br/>
                    <strong>Numéro Insee :</strong> <?= $agent->getNumeroInseeDefinitif() ?><br/>
                </div>
            </div>
        </div>
    </div>
    <form action="/siham/save-adresse" method="post">
        <div class="card bg-default">
            <div class="card-header">Adresse principale
                de <?= $agent->getPrenom() . ' ' . $agent->getNomUsuel() ?></div>
            <div class="card-body">
                <div class="form-group">
                    <label for="">Numero de voie : </label>
                    <input class="form-control" type="text" name="noVoieAdresse" value="<?= $agent->getNoVoieAdresse() ?>"/>
                </div>
                <div class="form-group">
                    <label for="">Nature voie : </label>
                    <input class="form-control" type="text" name="natureVoieAdresse"
                           value="<?= $agent->getNatureVoieAdresse() ?>"/>
                </div>
                <div class="form-group">
                    <label for="">Nom de la voie : </label>
                    <input class="form-control" type="text" name="nomVoieAdresse" value="<?= $agent->getNomVoieAdresse() ?>"/>
                </div>
                <div class="form-group">
                    <label for="">Complement adresse : </label>
                    <input class="form-control" type="text" name="complementAdresse"
                           value="<?= $agent->getComplementAdresse() ?>"/>
                </div>
                <div class="form-group">
                    <label for="">Code postal : </label>
                    <input class="form-control" type="text" name="codePostal" value="<?= $agent->getCodePostalAdresse() ?>"/>
                </div>
                <div class="form-group">
                    <label for="">Ville : </label>
                    <input class="form-control" type="text" name="ville"
                           value="<?= $agent->getBureauDistributeurAdresse() ?>"/>
                </div>
                <div style="display:hidden">
                    <input class="form-control" type="hidden" name="dateDebut"
                           value="<?= $agent->getDateDebutAdresse() ?>"/>
                    <input class="form-control" disabled="disabled" type="hidden" name="dateFin"
                           value="<?= $agent->getDateFinAdresse() ?>"/>
                    <input type="hidden" name="matricule" value="<?= $agent->getMatricule() ?>"/>
                </div>
                <div>
                    <button type="submit" class="btn btn-default">Enregistrer adresse</button>
                </div>
            </div>
        </div>
    </form>
    <form action="/siham/save-coordonnees" method="post">
        <div class="card bg-default">
            <div class="card-header">Numéros de téléphone et Emails
                de <?= $agent->getPrenom() . ' ' . $agent->getNomUsuel() ?></div>
            <div class="card-body">
                <div class="form-group">
                    <label for="">Téléphone fixe professionnel : </label>
                    <input class="form-control" type="text" name="telFixePro" value="<?= $agent->getTelephonePro() ?>"/>
                    <div class="float-end" style="margin:10px 0;">
                        <a class="btn btn-danger" href="/siham/historiser-coordonnees/<?= $agent->getMatricule() ?>/telpro" role="button">
                            Historiser
                        </a>
                    </div>
                </div>
                <div class="clearfix"></div>
                <div class=" form-group">
                    <label for="">Téléphone portable perso : </label>
                    <input class="form-control" type="text" name="telPortablePerso"
                           value="<?= $agent->getTelephonePerso() ?>"/>
                    <div class="float-end" style="margin:10px 0;">
                        <a class="btn btn-danger" href="/siham/historiser-coordonnees/<?= $agent->getMatricule() ?>/telperso" role="button">
                            Historiser
                        </a>
                    </div>
                </div>
                <div class="clearfix"></div>
                <div class="form-group">
                    <label for="">Email pro : </label>
                    <input class="form-control" type="text" name="emailPro"
                           value="<?= $agent->getEmailPro() ?>"/>
                    <div class="float-end" style="margin:10px 0;">
                        <a class="btn btn-danger" href="/siham/historiser-coordonnees/<?= $agent->getMatricule() ?>/emailpro" role="button">
                            Historiser
                        </a>
                    </div>
                </div>
                <div class="clearfix"></div>
                <div class="form-group">
                    <label for="">Email perso : </label>
                    <input class="form-control" type="text" name="emailPerso"
                           value="<?= $agent->getEmailPerso() ?>"/>
                    <div class="float-end" style="margin:10px 0;">
                        <a class="btn btn-danger" href="/siham/historiser-coordonnees/<?= $agent->getMatricule() ?>/emailperso" role="button">
                            Historiser
                        </a>
                    </div>
                </div>
                <div style="display:hidden;">
                    <input type="hidden" name="matricule" value="<?= $agent->getMatricule() ?>"/>
                    <input class="form-control" type="hidden" name="emailProDateDebut"
                           value="<?= $agent->getEmailProDateDebut() ?>"/>
                    <input class="form-control" type="hidden" name="emailPersoDateDebut"
                           value="<?= $agent->getEmailPersoDateDebut() ?>"/>
                    <input class="form-control" type="hidden" name="telPortablePersoDateDebut"
                           value="<?= $agent->getTelephonePersoDateDebut() ?>"/>
                    <input class="form-control" type="hidden" name="telFixeProDateDebut"
                           value="<?= $agent->getTelephoneProDateDebut() ?>"/>


                </div>
                <div class="clearfix"></div>

                <div>
                    <button type="submit" class="btn btn-default">Enregistrer coordonnées</button>
                </div>
            </div>
        </div>
    </form>
    <form action="/siham/save-iban" method="post">
        <div class="card bg-default">
            <div class="card-header">Coordonnées bancaires
                de <?= $agent->getPrenom() . ' ' . $agent->getNomUsuel() ?></div>
            <div class="card-body">
                <div class="form-group">
                    <input class="form-control" type="text" name="iban"
                           value="<?= $agent->getIban() ?>"/>
                </div>
                <div class="form-group">
                    <input class="form-control" type="text" name="bic"
                           value="<?= $agent->getBic() ?>"/>
                </div>
                <div>
                    <button type="submit" class="btn btn-default">Enregistrer iban</button>
                </div>
            </div>
        </div>
    </form>
<?php endif; ?>
