<?php

use Application\Provider\Privileges;

/* @var $role \Utilisateur\Entity\Db\Role */
/* @var $statut Intervenant\Entity\Db\Statut */
/* @var $privilege \Utilisateur\Entity\Db\Privilege */

$object = empty($role) ? $statut : $role;

$canEdit = $this->isAllowed(Privileges::getResourceId(Privileges::DROIT_PRIVILEGE_EDITION));

if ($object->getPrivileges()->contains($privilege)):
    ?>

    <?php if ($canEdit): ?><a href="javascript:void(0)" data-action="refuser" title="Privilège accordé. Cliquez pour le retirer."><?php endif; ?>
    <i class="fas fa-check text-succes"></i
    <?php if ($canEdit): ?></a><?php endif; ?>

<?php else: ?>

    <?php if ($canEdit): ?><a href="javascript:void(0)" data-action="accorder" title="Privilège refusé. Cliquez pour l'accorder."><?php endif; ?>
    <i class="fas fa-xmark text-danger refuse"></i>
    <?php if ($canEdit): ?></a><?php endif; ?>

<?php endif; ?>