<?php
/**
 * @var $this                 \Application\View\Renderer\PhpRenderer
 * @var $centreCouts          \Application\Entity\Db\CentreCout[]
 * @var $centreCoutStructures \Application\Entity\Db\CentreCoutStructure[]
 */

use Application\Provider\Privilege\Privileges;

$this->headTitle()->append("Centres de coûts");

$canEdit = $this->isAllowed(Privileges::getResourceId(Privileges::CENTRES_COUTS_ADMINISTRATION_EDITION));

?>
<h1 class="page-header">Centres de coûts</h1>
<?php
$tblListe = [];
$tblRef   = [];
$i        = 0;
foreach ($centreCouts as $fr) {
    if ($fr->getParent() == null) $tblRef[$i++] = $fr;
}
$nTblListe = $i;
$i         = 0;
while ($i < $nTblListe) {
    $j            = 0;
    $tblListe[$i] = [];
    foreach ($centreCouts as $frf) {
        if (($frf->getParent()) && ($frf->getParent()->getId() == $tblRef[$i]->getId())) {
            $tblListe[$i][$j++] = $frf;
        }
    }
    $i++;
} ?>
<table class="table table-bordered table-sort">
    <thead>
    <th style="word-wrap: break-word ; ">Code</th>
    <th style="word-wrap: break-word ; ">Libellé</th>
    <th style="word-wrap: break-word ; ">Activité</th>
    <th style="word-wrap: break-word ; ">Type de ressource</th>
    <th style="word-wrap: break-word ; ">Unité budgétaire</th>
    <?php if ($canEdit) {
        echo '<th style="word-wrap: break-word ;">Source<br>Actions</th>';
    } else echo '<th style="word-wrap: break-word ; ">Source</th>' ?>
    <th style="word-wrap: break-word ; ">Structure</th>
    </thead>
    <tbody>
    <?php
    for ($i = 0;
         $i < $nTblListe;
         $i++) {
        $fr  = $tblRef[$i];
        $nFr = count($tblListe[$i]); ?>
        <td data-order="<?= $fr->getCode() ?>"><?= $fr->getCode() ?><br></td>
        <td><?= $fr->getLibelle() . '<br>' ?></td>
        <td><?= $fr->getActivite()->getLibelle() . '<br>' ?></td>
        <td><?= $fr->getTypeRessource() . '<br>' ?></td>
        <td><?= $fr->getUniteBudgetaire() . '<br>' ?></td>
        <td style=" text-align: center;"><?php if (($fr->getSource()->getLibelle() == 'OSE') && ($canEdit)) { ?>
                <a class="ajax-modal" data-event="centre-cout-saisie"
                   href="<?= $this->url('centre-cout/saisie', ['centre-cout' => $fr->getId()]) ?>"
                   title="Modifier la Centre de Coûts">
                    <span class="glyphicon glyphicon-edit"></span></a>
                <a class="pop-ajax"
                   href="<?= $this->url('centre-cout/delete', ['centre-cout' => $fr->getId()]) ?>"
                   title="Supprimer la Centre de Coûts"
                   data-content="<p class='lead text-danger'><strong>Attention!</strong> Confirmez-vous cette suppression ?</p>"
                   data-confirm="true"
                   data-confirm-button="Oui"
                   data-cancel-button="Non"
                   data-submit-reload="true"
                >
                    <span class="glyphicon glyphicon-remove"></span>
                </a>
            <?php } else echo $fr->getSource(); ?>
        </td>
        <td>
            <?php
            $tblOk = $okActions = false;
            foreach ($centreCoutStructures as $ccs) {
                if ($ccs->getCentreCout()->getId() == $fr->getId()) {
                    $tblOk = true;
                    if (($ccs->getSource()->getLibelle() == 'OSE') && $canEdit) $okActions = true;
                }
            }
            if ($tblOk) { ?>
                <?php foreach ($centreCoutStructures as $ccs) {
                    if ($ccs->getCentreCout()->getId() == $fr->getId()) { ?>
                        <?= $ccs->getStructure() ?>
                        <?php if (($ccs->getSource()->getLibelle() == 'OSE') && $canEdit) { ?>
                            <a class="ajax-modal" data-event="centre-cout-saisie"
                               href="<?= $this->url('centre-cout/saisie-structure', ['centre-cout' => $fr->getId(), 'centre-cout-structure' => $ccs->getId()]) ?>"
                               title="Modifier la structure">
                                <span class="glyphicon glyphicon-edit"></span></a>
                            <a class="pop-ajax"
                               href="<?= $this->url('centre-cout/delete-structure', ['centre-cout-structure' => $ccs->getId()]) ?>"
                               title="Supprimer la sructure du Centre de Coûts"
                               data-content="<p class='lead text-danger'><strong>Attention!</strong> Confirmez-vous cette suppression ?</p>"
                               data-confirm="true"
                               data-confirm-button="Oui"
                               data-cancel-button="Non"
                               data-submit-reload="true"
                            >
                                <span class="glyphicon glyphicon-remove"></span>
                            </a>
                        <?php } ?>
                        <br>
                    <?php }
                } ?>
            <?php } ?>
            <?php if ($canEdit) { ?>
                <a class="ajax-modal" data-event="centre-cout-saisie"
                   href="<?= $this->url('centre-cout/saisie-structure', ['centre-cout' => $fr->getId()]) ?>"
                   title="Ajouter une structure">
                    <button type="button" class="btn btn-xs btn-primary">Ajouter une structure</button>
                </a>
            <?php } ?>
        </td>
        </tr>
        <?php if ($nFr) { ?>
            <?php
            for ($j = 0;
                 $j < $nFr;
                 $j++) {
                $frf = $tblListe[$i][$j]; ?>
                <td data-order="<?= $fr->getCode() ?>"
                    style="word-wrap: break-word; padding-left:30px; "><?= $frf->getCode() ?></td>
                <td style="word-wrap: break-word ; "><?= $frf->getLibelle() ?></td>
                <td style="word-wrap: break-word ; "><?= $frf->getActivite()->getLibelle() ?></td>
                <td style="word-wrap: break-word ; "><?= $frf->getTypeRessource() ?></td>
                <td style="word-wrap: break-word ; "><?= $frf->getUniteBudgetaire() ?></td>
                <?php if (($frf->getSource()->getLibelle() == 'OSE') && $canEdit) { ?>
                    <td style="text-align:center;width:1px;white-space: nowrap">
                        <a class="ajax-modal" data-event="centre-cout-saisie"
                           href="<?= $this->url('centre-cout/saisie', ['centre-cout' => $frf->getId()]) ?>"
                           title="Modifier la Centre de Coûts">
                            <span class="glyphicon glyphicon-edit"></span></a>
                        <a class="pop-ajax"
                           href="<?= $this->url('centre-cout/delete', ['centre-cout' => $frf->getId()]) ?>"
                           title="Supprimer le Centre de Coûts"
                           data-content="<p class='lead text-danger'><strong>Attention!</strong> Confirmez-vous cette suppression ?</p>"
                           data-confirm="true"
                           data-confirm-button="Oui"
                           data-cancel-button="Non"
                           data-submit-reload="true"
                        >
                            <span class="glyphicon glyphicon-remove"></span>
                        </a>
                    </td>
                <?php } else echo '<td>' . $frf->getSource(); ?></td>
                <td>
                    <?php
                    $tblOk = $okActions = false;
                    foreach ($centreCoutStructures as $ccs) {
                        if ($ccs->getCentreCout()->getId() == $frf->getId()) {
                            $tblOk = true;
                            if (($ccs->getSource()->getLibelle() == 'OSE') && $canEdit) $okActions = true;
                        }
                    }
                    if ($tblOk) {
                        foreach ($centreCoutStructures as $ccs) {
                            if ($ccs->getCentreCout()->getId() == $frf->getId()) { ?>
                                <?= $ccs->getStructure() ?>
                                <?php if (($ccs->getSource()->getLibelle() == 'OSE') && $canEdit) { ?>
                                    <a class="ajax-modal" data-event="centre-cout-saisie"
                                       href="<?= $this->url('centre-cout/saisie-structure', ['centre-cout' => $fr->getId(), 'centre-cout-structure' => $ccs->getId()]) ?>"
                                       title="Modifier la structure">
                                        <span class="glyphicon glyphicon-edit"></span></a>
                                    <a class="pop-ajax"
                                       href="<?= $this->url('centre-cout/delete-structure', ['centre-cout-structure' => $ccs->getId()]) ?>"
                                       title="Supprimer la sructure du Centre de Coûts"
                                       data-content="<p class='lead text-danger'><strong>Attention!</strong> Confirmez-vous cette suppression ?</p>"
                                       data-confirm="true"
                                       data-confirm-button="Oui"
                                       data-cancel-button="Non"
                                       data-submit-reload="true"
                                    >
                                        <span class="glyphicon glyphicon-remove"></span>
                                    </a>
                                <?php } ?>
                                <br>
                            <?php }
                        } ?>
                    <?php } ?>
                    <?php if ($canEdit) { ?>
                        <a class="ajax-modal" data-event="centre-cout-saisie"
                           href="<?= $this->url('centre-cout/saisie-structure', ['centre-cout' => $frf->getId()]) ?>"
                           title="Ajouter une structure">
                            <button type="button" class="btn btn-xs btn-primary">Ajouter une structure</button>
                        </a>
                    <?php } ?>
                </td>
                </tr>
            <?php } ?>
        <?php } ?>
    <?php } ?>
    </tbody>
</table>
<?php if ($canEdit): ?>
    <a class="btn btn-primary ajax-modal" data-event="centre-cout-saisie"
       href="<?= $this->url('centre-cout/saisie') ?>"
       title="Ajouter un Centre de Coûts">
        <span class="glyphicon glyphicon-edit"></span>
        Ajouter un Centre de cout</a>

    <script type="text/javascript">
        $(function () {
            $("body").on("centre-cout-saisie", function (event, data) {
                window.location.reload();
            });
        });
    </script>
<?php endif ?>
