<?php
/**
 * @var $this                 \Application\View\Renderer\PhpRenderer
 * @var $centreCouts          \Application\Entity\Db\CentreCout[]
 * @var $centreCoutStructures \Application\Entity\Db\CentreCoutStructure[]
 */

use Application\Provider\Privilege\Privileges;

$this->headTitle()->append("Centres de cout");

$canEdit = $this->isAllowed(Privileges::getResourceId(Privileges::DROIT_PRIVILEGE_EDITION));

?>
<h1 class="page-header">Centres de cout</h1>

<table class="table table-bordered table-sort">
    <thead>
    <th style="word-wrap: break-word ; ">Code</th>
    <th style="word-wrap: break-word ; ">Libelle</th>
    <th style="word-wrap: break-word ; ">Activite</th>
    <th style="word-wrap: break-word ; ">Type Ressource</th>
    <th style="word-wrap: break-word ; ">Parent</th>
    <th style="word-wrap: break-word ; ">Source</th>
    <th style="word-wrap: break-word ; ">Source Code</th>
    <th style="word-wrap: break-word ; ">Unite Budgetaire</th>
    <?php if ($canEdit) echo '<th>Actions</th>' ?>
    <th>Structures</th>
    </thead>
    <tbody>
    <?php foreach ($centreCouts

                   as $fr): ?>
        <tr>
            <td style="word-wrap: break-word ; "><?= $fr->getCode() ?></td>
            <td style="word-wrap: break-word ; "><?= $fr->getLibelle() ?></td>
            <td style="word-wrap: break-word ; "><?= $fr->getActivite()->getLibelle() ?></td>
            <td style="word-wrap: break-word ; "><?= $fr->getTypeRessource() ?></td>
            <td style="word-wrap: break-word ; "><?= $fr->getParent() ?></td>
            <td style="word-wrap: break-word ; "><?= $fr->getSource() ?></td>
            <td style="word-wrap: break-word ; "><?= $fr->getSourceCode() ?></td>
            <td style="word-wrap: break-word ; "><?= $fr->getUniteBudgetaire() ?></td>
            <?php if (($fr->getSource()->getLibelle() == 'OSE') && $canEdit) { ?>
            <td style="text-align:center;width:1px;white-space: nowrap">
                <a class="ajax-modal" data-event="centre-cout-saisie"
                   href="<?= $this->url('centre-cout/saisie', ['centre-cout' => $fr->getId()]) ?>"
                   title="Modifier la Centre de Cout">
                    <span class="glyphicon glyphicon-edit"></span></a>
                <a class="pop-ajax"
                   href="<?= $this->url('centre-cout/delete', ['centre-cout' => $fr->getId()]) ?>"
                   title="Supprimer la Centre de Cout"
                   data-content="<p class='lead text-danger'><strong>Attention!</strong> Confirmez-vous cette suppression ?</p>"
                   data-confirm="true"
                   data-confirm-button="Oui"
                   data-cancel-button="Non"
                   data-submit-reload="true"
                >
                    <span class="glyphicon glyphicon-remove"></span>
                </a>
                <?php }
                else {
                    echo "<td>&nbsp;</td>";
                } ?>
            <td>
                <?php
                $tblOk = false;
                foreach ($centreCoutStructures as $ccs) {
                    if ($ccs->getCentreCout()->getId() == $fr->getId()) $tblOk = true;
                }
                if ($tblOk) { ?>
                    <table class="table table-bordered table-bordered">
                        <thead>
                        <th> Structure</th>
                        <th> Source</th>
                        <th> Code</th>
                        <th> Unité budgétaire</th>
                        <?php if ($canEdit) echo '<th>Actions</th>' ?>
                        </thead>
                        <tbody>
                        <?php foreach ($centreCoutStructures as $ccs) {
                            if ($ccs->getCentreCout()->getId() == $fr->getId()) { ?>
                                <tr>
                                    <td><?= $ccs->getStructure() ?></td>
                                    <td><?= $ccs->getSource() ?></td>
                                    <td><?= $ccs->getSourceCode() ?></td>
                                    <td><?= $ccs->getUniteBudgetaire() ?></td>
                                <?php if (($ccs->getSource()->getLibelle() == 'OSE') && $canEdit) { ?>
                                    <td>
                                        <a class="ajax-modal" data-event="centre-cout-saisie"
                                           href="<?= $this->url('centre-cout/saisie-structure', ['centre-cout' => $fr->getId(),'centre-cout-structure' => $ccs->getId()]) ?>"
                                           title="Modifier la structure">
                                            <span class="glyphicon glyphicon-edit"></span></a>
                                        <a class="pop-ajax"
                                           href="<?= $this->url('centre-cout/delete-structure', ['centre-cout-structure' => $ccs->getId()]) ?>"
                                           title="Supprimer la sructure du Centre de Cout"
                                           data-content="<p class='lead text-danger'><strong>Attention!</strong> Confirmez-vous cette suppression ?</p>"
                                           data-confirm="true"
                                           data-confirm-button="Oui"
                                           data-cancel-button="Non"
                                           data-submit-reload="true"
                                        >
                                            <span class="glyphicon glyphicon-remove"></span>
                                        </a>
                                        <?php } ?>
                                    </td>
                                </tr>
                            <?php }
                        } ?>
                        </tbody>
                    </table>
               <?php  } ?>
                 <?php if (($canEdit) && ($fr->getSource()->getLibelle() == 'OSE')){ ?>
                <a class="ajax-modal" data-event="centre-cout-saisie"
                   href="<?= $this->url('centre-cout/saisie-structure', ['centre-cout' => $fr->getId()]) ?>"
                   title="Ajouter une structure">
                   <button type="button" class="btn btn-xs btn-primary">Ajouter une structure</button>
                </a>
               <?php } ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<?php if ($canEdit): ?>
    <a class="btn btn-primary ajax-modal" data-event="centre-cout-saisie"
       href="<?= $this->url('centre-cout/saisie') ?>"
       title="Ajouter un Centre de Cout">
        <span class="glyphicon glyphicon-edit"></span>
        Ajouter un Centre de cout</a>

    <script type="text/javascript">
        $(function () {
            $("body").on("centre-cout-saisie", function (event, data) {
                window.location.reload();
            });
        });
    </script>
<?php endif ?>
