<?php

namespace Application;

use Application\Entity\Db\Indicateur;
use Application\Provider\Privilege\Privileges;

/**
 * @var $this        \Application\View\Renderer\PhpRenderer
 * @var $indicateurs Indicateur[]
 */

if (empty($indicateurs)): ?>
    Aucun
<?php else: ?>
<table class="table table-bordered table-condensed">
    <thead>
    <tr>
        <th class="categorie">Catégorie</th>
        <th class="numero">N°</th>
        <th class="intitule">Intitulé de l'indicateur</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($indicateurs as $indicateur):
        $urlResult = $this->url('indicateur/result', ['indicateur' => $indicateur->getId()]);
        ?>
        <tr class="indicateur" id="<?php echo $indicateur->getId() ?>">

            <td class="categorie"><?php echo $indicateur->getType() ?></td>
            <td class="numero"><?php echo $indicateur->getNumero() ?></td>
            <td class="intitule">
                <?php if ($indicateur->getCount()): ?>
                    <a href="<?php echo $urlResult ?>"
                       title="Cliquez pour vous rendre à la page concernée"><?php echo $indicateur->getLibelle() ?></a>
                <?php else: ?>
                    <?php echo $indicateur->getLibelle() ?>
                <?php endif ?>
            </td>

        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<?php endif;